import Link from 'next/link';
import type { ReactNode } from 'react';

/**
 * Minimal inline-markdown renderer for guide content: **bold** and
 * [label](href). Deliberately NOT a markdown library — the content
 * pipeline only ever emits these two constructs, and a full parser
 * would widen the rendering surface for JSON that is regenerated by
 * agents. Anything else renders as plain text.
 *
 * Internal links (href starting with /) use next/link so the guides'
 * maillage interne stays client-side navigable; external links open in
 * a new tab with rel=noopener.
 */
const INLINE_RE = /\*\*(.+?)\*\*|\[([^\]]+)\]\(([^)\s]+)\)/g;

export function RichText({ text }: { text: string }) {
  const nodes: ReactNode[] = [];
  let lastIndex = 0;
  let key = 0;

  for (const match of text.matchAll(INLINE_RE)) {
    const index = match.index ?? 0;
    if (index > lastIndex) {
      nodes.push(text.slice(lastIndex, index));
    }
    if (match[1] !== undefined) {
      nodes.push(<strong key={key++}>{match[1]}</strong>);
    } else {
      const label = match[2];
      const href = match[3];
      if (href.startsWith('/')) {
        nodes.push(
          <Link
            key={key++}
            href={href}
            className="text-terracotta underline underline-offset-2 hover:text-aubergine"
          >
            {label}
          </Link>,
        );
      } else {
        nodes.push(
          <a
            key={key++}
            href={href}
            target="_blank"
            rel="noopener noreferrer"
            className="text-terracotta underline underline-offset-2 hover:text-aubergine"
          >
            {label}
          </a>,
        );
      }
    }
    lastIndex = index + match[0].length;
  }
  if (lastIndex < text.length) {
    nodes.push(text.slice(lastIndex));
  }

  return <>{nodes}</>;
}
