import type { Metadata, Viewport } from 'next';
import { Newsreader, Karla } from 'next/font/google';
import { CookieBanner } from '@/components/cookie/CookieBanner';
import './globals.css';

const newsreader = Newsreader({
  subsets: ['latin'],
  variable: '--font-newsreader',
  display: 'swap',
  style: ['normal', 'italic'],
  weight: ['400', '500', '600', '700'],
});

const karla = Karla({
  subsets: ['latin'],
  variable: '--font-karla',
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: {
    default: 'Civique — Préparez votre examen civique français',
    // Per-route `metadata.title` strings get wrapped with this template,
    // so child pages get a consistent "Page · Civique" branding without
    // having to spell out " — Civique" themselves.
    template: '%s · Civique',
  },
  description:
    "Préparation indépendante à l'examen civique 2026 : 611 QCM officiels + 240 questions d'entretien, 8 langues, conforme à l'arrêté du 10 octobre 2025.",
  metadataBase: new URL('https://civique.integrafle.fr'),
  applicationName: 'Civique',
  authors: [{ name: 'Civique', url: 'https://civique.integrafle.fr' }],
  creator: 'Civique',
  publisher: 'Civique',
  keywords: [
    'examen civique',
    'examen civique français',
    'examen civique 2026',
    'naturalisation française',
    'carte de séjour pluriannuelle',
    'carte de résident',
    "contrat d'intégration républicaine",
    'CIR',
    'CSP',
    'CR',
    'livret du citoyen',
    "entretien d'assimilation",
    'questions naturalisation',
    'préparation naturalisation',
    "arrêté du 10 octobre 2025",
  ],
  // Explicit crawl directives. Override per route with
  // `metadata.robots = { index: false }` for auth-gated pages.
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // Favicons are emitted automatically from `app/icon.svg` + `app/apple-icon.png`
  // via Next.js' file-based metadata convention — no explicit icons block here.
  // OG image is generated by `app/opengraph-image.tsx` (Next file-based convention).
  openGraph: {
    title: 'Civique — Préparez votre examen civique français',
    description:
      "La préparation indépendante pour la carte de séjour, la carte de résident et la nationalité française. 8 langues.",
    url: 'https://civique.integrafle.fr',
    siteName: 'Civique',
    locale: 'fr_FR',
    type: 'website',
  },
  // Twitter card — falls back to openGraph.images automatically since
  // we don't specify a separate twitter-image. summary_large_image
  // gives the wide hero card style on x.com/Slack/Discord previews.
  twitter: {
    card: 'summary_large_image',
    title: 'Civique — Préparez votre examen civique français',
    description:
      "Préparation indépendante à l'examen civique 2026 : 611 QCM officiels + 240 questions d'entretien, 8 langues.",
  },
  // Verification tokens — populated when GSC/Bing/Yandex consoles are set up.
  // verification: { google: 'TODO', other: { 'msvalidate.01': 'TODO' } },
};

export const viewport: Viewport = {
  themeColor: '#F4ECDD',
  width: 'device-width',
  initialScale: 1,
};

// Force every route to render dynamically. We hit a Next.js 15 + React 19 +
// pnpm-workspace issue where static prerender of /404 and /500 throws
// "Cannot read properties of null (reading 'useContext')" — the root cause
// is React being resolved twice in the workspace's traced module graph.
// Dynamic rendering bypasses prerender entirely. Trade-off: no static HTML
// caching on the public landing/legal pages, but for an MVP at low traffic
// this is invisible to users and we keep all our Server Components +
// Server Actions intact.
// TODO post-launch: pin react/react-dom via pnpm.overrides at the workspace
// root once we confirm it doesn't break the mobile RN build, then drop this.
export const dynamic = 'force-dynamic';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="fr"
      className={`${newsreader.variable} ${karla.variable}`}
      suppressHydrationWarning
    >
      <body className="min-h-screen antialiased">
        {/* Site-wide schema.org JSON-LD: Organization + WebSite.
            Helps Google build the knowledge panel (logo, contact, social
            links — sameAs can be populated when official accounts exist)
            and enable site-link search box. Per-page JSON-LD (SoftwareApplication,
            Article, FAQPage…) is injected at the page level on top of this. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify([
              {
                '@context': 'https://schema.org',
                '@type': 'Organization',
                '@id': 'https://civique.integrafle.fr/#organization',
                name: 'Civique',
                url: 'https://civique.integrafle.fr',
                logo: {
                  '@type': 'ImageObject',
                  url: 'https://civique.integrafle.fr/logo-c.png',
                },
                description:
                  "Préparation indépendante à l'examen civique français 2026, sans affiliation officielle avec l'État.",
                email: 'support@integrafle.fr',
                contactPoint: {
                  '@type': 'ContactPoint',
                  email: 'support@integrafle.fr',
                  contactType: 'customer support',
                  availableLanguage: ['French', 'English', 'Arabic', 'Spanish', 'Portuguese', 'Persian', 'Hindi', 'Turkish'],
                },
              },
              {
                '@context': 'https://schema.org',
                '@type': 'WebSite',
                '@id': 'https://civique.integrafle.fr/#website',
                url: 'https://civique.integrafle.fr',
                name: 'Civique',
                description: "Préparation indépendante à l'examen civique français.",
                publisher: { '@id': 'https://civique.integrafle.fr/#organization' },
                inLanguage: 'fr-FR',
              },
            ]),
          }}
        />
        {/* Skip-to-main-content link for keyboard / screen-reader users.
            Stays visually hidden until focused, then surfaces as a focused chip. */}
        <a
          href="#main-content"
          className="
            sr-only focus:not-sr-only
            focus:fixed focus:top-3 focus:left-3 focus:z-[100]
            focus:inline-flex focus:items-center focus:px-4 focus:py-2
            focus:rounded-full focus:bg-aubergine focus:text-bone
            focus:font-semibold focus:text-sm focus:shadow-warm
            focus:outline-none focus-visible:ring-2 focus-visible:ring-terracotta focus-visible:ring-offset-2 focus-visible:ring-offset-bone
          "
        >
          Aller au contenu principal
        </a>
        {children}
        <CookieBanner />
      </body>
    </html>
  );
}
