export const theme4Pt = [
  // Q1
  { textFr: "En quelle année a débuté la Révolution française ?", lang: 'pt' as const, text: "Em que ano começou a Revolução Francesa?", explanation: "A Revolução Francesa começou em 1789 com a tomada da Bastilha em 14 de julho. Esse evento marca o fim do Antigo Regime e o início de uma era de profundas mudanças políticas e sociais na França.", choices: [{ id: 'a' as const, text: "1789" }, { id: 'b' as const, text: "1799" }, { id: 'c' as const, text: "1776" }, { id: 'd' as const, text: "1815" }] },
  // Q2
  { textFr: "Qui était Napoléon Ier ?", lang: 'pt' as const, text: "Quem foi Napoleão I?", explanation: "Napoleão I foi imperador dos franceses de 1804 a 1814 e brevemente em 1815. Ele modernizou a administração francesa e instituiu o Código Civil, ainda em vigor hoje.", choices: [{ id: 'a' as const, text: "O primeiro imperador dos franceses" }, { id: 'b' as const, text: "O último rei da França" }, { id: 'c' as const, text: "O fundador da Quinta República" }, { id: 'd' as const, text: "Um general da Primeira Guerra Mundial" }] },
  // Q3
  { textFr: "Lequel de ces personnages historiques est français ?", lang: 'pt' as const, text: "Qual desses personagens históricos é francês?", explanation: "Joana d'Arc é uma figura emblemática da história da França. Ela liderou os exércitos franceses contra os ingleses durante a Guerra dos Cem Anos no século XV.", choices: [{ id: 'a' as const, text: "Joana d'Arc" }, { id: 'b' as const, text: "Cristóvão Colombo" }, { id: 'c' as const, text: "Winston Churchill" }, { id: 'd' as const, text: "Leonardo da Vinci" }] },
  // Q4
  { textFr: "Dans quelle République est-on aujourd'hui ?", lang: 'pt' as const, text: "Em qual República estamos hoje?", explanation: "A França está atualmente sob a Quinta República, instaurada em 1958 pelo general de Gaulle. Ela reforçou o poder do presidente da República.", choices: [{ id: 'a' as const, text: "A Quinta República" }, { id: 'b' as const, text: "A Quarta República" }, { id: 'c' as const, text: "A Terceira República" }, { id: 'd' as const, text: "A Sexta República" }] },
  // Q5
  { textFr: "Qu'est-ce que la Shoah ?", lang: 'pt' as const, text: "O que é a Shoah?", explanation: "A Shoah designa o genocídio dos judeus da Europa pela Alemanha nazista durante a Segunda Guerra Mundial. Aproximadamente seis milhões de judeus foram exterminados entre 1941 e 1945.", choices: [{ id: 'a' as const, text: "O genocídio dos judeus durante a Segunda Guerra Mundial" }, { id: 'b' as const, text: "Uma batalha da Primeira Guerra Mundial" }, { id: 'c' as const, text: "Um tratado de paz europeu" }, { id: 'd' as const, text: "A resistência francesa contra a ocupação" }] },
  // Q6
  { textFr: "Quel pays ou région du monde a été colonisé par la France ?", lang: 'pt' as const, text: "Qual país ou região do mundo foi colonizado pela França?", explanation: "A Argélia foi colonizada pela França de 1830 a 1962. Era a mais importante colônia francesa no norte da África e sua independência foi obtida após uma longa guerra.", choices: [{ id: 'a' as const, text: "A Argélia" }, { id: 'b' as const, text: "O Brasil" }, { id: 'c' as const, text: "A Índia" }, { id: 'd' as const, text: "A Austrália" }] },
  // Q7
  { textFr: "Qui a rendu l'école gratuite, laïque et obligatoire ?", lang: 'pt' as const, text: "Quem tornou a escola gratuita, laica e obrigatória?", explanation: "Jules Ferry, ministro da Instrução Pública, fez aprovar as leis de 1881-1882 que tornaram a escola primária gratuita, laica e obrigatória. Essas leis são um pilar da República Francesa.", choices: [{ id: 'a' as const, text: "Jules Ferry" }, { id: 'b' as const, text: "Victor Hugo" }, { id: 'c' as const, text: "Napoleão Bonaparte" }, { id: 'd' as const, text: "Charles de Gaulle" }] },
  // Q8
  { textFr: "Quand a eu lieu la Seconde Guerre mondiale ?", lang: 'pt' as const, text: "Quando ocorreu a Segunda Guerra Mundial?", explanation: "A Segunda Guerra Mundial ocorreu de 1939 a 1945. Esse conflito mundial envolveu a maioria das nações e causou milhões de vítimas.", choices: [{ id: 'a' as const, text: "1939-1945" }, { id: 'b' as const, text: "1914-1918" }, { id: 'c' as const, text: "1870-1871" }, { id: 'd' as const, text: "1950-1953" }] },
  // Q9
  { textFr: "Quand a eu lieu la Première Guerre mondiale ?", lang: 'pt' as const, text: "Quando ocorreu a Primeira Guerra Mundial?", explanation: "A Primeira Guerra Mundial ocorreu de 1914 a 1918. Esse conflito opôs principalmente as potências da Tríplice Entente aos Impérios Centrais.", choices: [{ id: 'a' as const, text: "1914-1918" }, { id: 'b' as const, text: "1939-1945" }, { id: 'c' as const, text: "1870-1871" }, { id: 'd' as const, text: "1899-1902" }] },
  // Q10
  { textFr: "En quelle année a été créée la Communauté Économique Européenne (CEE) ?", lang: 'pt' as const, text: "Em que ano foi criada a Comunidade Econômica Europeia (CEE)?", explanation: "A CEE foi criada em 1957 pelo Tratado de Roma, assinado por seis países fundadores, incluindo a França. Ela é a precursora da atual União Europeia.", choices: [{ id: 'a' as const, text: "1957" }, { id: 'b' as const, text: "1945" }, { id: 'c' as const, text: "1962" }, { id: 'd' as const, text: "1951" }] },
  // Q11
  { textFr: "Le 11 novembre est un jour férié. À quoi correspond cette date ?", lang: 'pt' as const, text: "O 11 de novembro é feriado. A que corresponde essa data?", explanation: "O 11 de novembro de 1918 marca o armistício da Primeira Guerra Mundial. Esse feriado comemora o fim dos combates e presta homenagem aos soldados que morreram pela França.", choices: [{ id: 'a' as const, text: "O armistício da Primeira Guerra Mundial" }, { id: 'b' as const, text: "O fim da Segunda Guerra Mundial" }, { id: 'c' as const, text: "A festa nacional francesa" }, { id: 'd' as const, text: "A proclamação da República" }] },
  // Q12
  { textFr: "Qui a été le premier Président élu sous la Ve République ?", lang: 'pt' as const, text: "Quem foi o primeiro presidente eleito sob a Quinta República?", explanation: "Charles de Gaulle foi o primeiro presidente da Quinta República, eleito em 1958. Ele é o fundador desse regime e exerceu dois mandatos presidenciais.", choices: [{ id: 'a' as const, text: "Charles de Gaulle" }, { id: 'b' as const, text: "François Mitterrand" }, { id: 'c' as const, text: "Georges Pompidou" }, { id: 'd' as const, text: "René Coty" }] },
  // Q13
  { textFr: "En quelle année l'esclavage a-t-il été aboli définitivement en France ?", lang: 'pt' as const, text: "Em que ano a escravidão foi abolida definitivamente na França?", explanation: "A escravidão foi abolida definitivamente na França em 1848, por iniciativa de Victor Schœlcher. Um primeiro decreto de abolição havia sido promulgado em 1794, mas Napoleão o restabeleceu em 1802.", choices: [{ id: 'a' as const, text: "1848" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1865" }, { id: 'd' as const, text: "1794" }] },
  // Q14
  { textFr: "Depuis quelle année l'école publique est-elle gratuite ?", lang: 'pt' as const, text: "Desde que ano a escola pública é gratuita?", explanation: "A escola pública é gratuita desde 1881, graças às leis de Jules Ferry. Essas leis também tornaram o ensino primário obrigatório e laico.", choices: [{ id: 'a' as const, text: "1881" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1905" }, { id: 'd' as const, text: "1848" }] },
  // Q15
  { textFr: "Combien y a-t-il eu de républiques en France ?", lang: 'pt' as const, text: "Quantas repúblicas a França já teve?", explanation: "A França teve cinco repúblicas. A Primeira República foi proclamada em 1792 e a Quinta República, instaurada em 1958, é o regime atual.", choices: [{ id: 'a' as const, text: "Cinco" }, { id: 'b' as const, text: "Três" }, { id: 'c' as const, text: "Quatro" }, { id: 'd' as const, text: "Seis" }] },
  // Q16
  { textFr: "Qui était le roi de France au moment de la Révolution française ?", lang: 'pt' as const, text: "Quem era o rei da França no momento da Revolução Francesa?", explanation: "Luís XVI era rei da França durante a Revolução Francesa de 1789. Ele foi derrubado e guilhotinado em 1793.", choices: [{ id: 'a' as const, text: "Luís XVI" }, { id: 'b' as const, text: "Luís XIV" }, { id: 'c' as const, text: "Luís XV" }, { id: 'd' as const, text: "Henrique IV" }] },
  // Q17
  { textFr: "Qui a fondé la Ve République ?", lang: 'pt' as const, text: "Quem fundou a Quinta República?", explanation: "O general Charles de Gaulle fundou a Quinta República em 1958. Ele foi seu primeiro presidente e instaurou uma Constituição que reforçou o poder executivo.", choices: [{ id: 'a' as const, text: "O general de Gaulle" }, { id: 'b' as const, text: "François Mitterrand" }, { id: 'c' as const, text: "Napoleão III" }, { id: 'd' as const, text: "Léon Blum" }] },
  // Q18
  { textFr: "Que célèbre-t-on le 14 juillet ?", lang: 'pt' as const, text: "O que se comemora em 14 de julho?", explanation: "O 14 de julho é a festa nacional francesa. Ela comemora a tomada da Bastilha em 1789 e a Festa da Federação de 1790, símbolos da liberdade e da unidade nacional.", choices: [{ id: 'a' as const, text: "A festa nacional, aniversário da tomada da Bastilha" }, { id: 'b' as const, text: "O armistício de 1918" }, { id: 'c' as const, text: "O fim da Segunda Guerra Mundial" }, { id: 'd' as const, text: "A abolição da escravidão" }] },
  // Q19
  { textFr: "Quelle guerre a eu lieu entre 1914 et 1918 ?", lang: 'pt' as const, text: "Qual guerra ocorreu entre 1914 e 1918?", explanation: "A Primeira Guerra Mundial ocorreu de 1914 a 1918. Ela opôs os Aliados aos Impérios Centrais e causou milhões de mortos.", choices: [{ id: 'a' as const, text: "A Primeira Guerra Mundial" }, { id: 'b' as const, text: "A Segunda Guerra Mundial" }, { id: 'c' as const, text: "A guerra franco-prussiana" }, { id: 'd' as const, text: "A guerra da Argélia" }] },
  // Q20
  { textFr: "Pourquoi l'année 1958 est importante pour la France ?", lang: 'pt' as const, text: "Por que o ano de 1958 é importante para a França?", explanation: "O ano de 1958 marca a criação da Quinta República pelo general de Gaulle. Uma nova Constituição foi adotada, estabelecendo o regime político atual da França.", choices: [{ id: 'a' as const, text: "É o ano da criação da Quinta República" }, { id: 'b' as const, text: "É o ano do fim da Segunda Guerra Mundial" }, { id: 'c' as const, text: "É o ano da abolição da escravidão" }, { id: 'd' as const, text: "É o ano da Revolução Francesa" }] },
  // Q21
  { textFr: "Quel fleuve coule en France ?", lang: 'pt' as const, text: "Qual rio corre na França?", explanation: "O Loire é o rio mais longo da França com aproximadamente 1.012 km. Ele atravessa o centro da França do Maciço Central ao oceano Atlântico.", choices: [{ id: 'a' as const, text: "O Loire" }, { id: 'b' as const, text: "O Danúbio" }, { id: 'c' as const, text: "O Nilo" }, { id: 'd' as const, text: "O Amazonas" }] },
  // Q22
  { textFr: "Quelle ville est française ?", lang: 'pt' as const, text: "Qual cidade é francesa?", explanation: "Lyon é uma grande cidade francesa, capital da região Auvergne-Rhône-Alpes. É a terceira maior cidade da França depois de Paris e Marselha.", choices: [{ id: 'a' as const, text: "Lyon" }, { id: 'b' as const, text: "Genebra" }, { id: 'c' as const, text: "Bruxelas" }, { id: 'd' as const, text: "Barcelona" }] },
  // Q23
  { textFr: "Quel océan borde la côte ouest française ?", lang: 'pt' as const, text: "Qual oceano banha a costa oeste francesa?", explanation: "O oceano Atlântico banha a costa oeste da França metropolitana. Da Bretanha ao País Basco, essa fachada marítima se estende por centenas de quilômetros.", choices: [{ id: 'a' as const, text: "O oceano Atlântico" }, { id: 'b' as const, text: "O oceano Pacífico" }, { id: 'c' as const, text: "O oceano Índico" }, { id: 'd' as const, text: "O oceano Ártico" }] },
  // Q24
  { textFr: "Qu'est-ce que Paris ?", lang: 'pt' as const, text: "O que é Paris?", explanation: "Paris é a capital da França e seu centro político, econômico e cultural. É também a cidade mais populosa do país.", choices: [{ id: 'a' as const, text: "A capital da França" }, { id: 'b' as const, text: "Uma região da França" }, { id: 'c' as const, text: "Um departamento ultramarino" }, { id: 'd' as const, text: "A capital da Europa" }] },
  // Q25
  { textFr: "Quelle est la capitale de la France ?", lang: 'pt' as const, text: "Qual é a capital da França?", explanation: "Paris é a capital da França há séculos. Ela abriga as principais instituições do Estado, incluindo o Palácio do Eliseu e a Assembleia Nacional.", choices: [{ id: 'a' as const, text: "Paris" }, { id: 'b' as const, text: "Lyon" }, { id: 'c' as const, text: "Marselha" }, { id: 'd' as const, text: "Estrasburgo" }] },
  // Q26
  { textFr: "Sur quel continent se situe la France métropolitaine ?", lang: 'pt' as const, text: "Em qual continente se situa a França metropolitana?", explanation: "A França metropolitana se situa no continente europeu. Ela é banhada pelo oceano Atlântico a oeste, pelo mar Mediterrâneo ao sul e pelo Canal da Mancha ao norte.", choices: [{ id: 'a' as const, text: "A Europa" }, { id: 'b' as const, text: "A África" }, { id: 'c' as const, text: "A América" }, { id: 'd' as const, text: "A Ásia" }] },
  // Q27
  { textFr: "Quelle île est un département d'outre-mer français ?", lang: 'pt' as const, text: "Qual ilha é um departamento ultramarino francês?", explanation: "A Martinica é um departamento e uma região ultramarina francesa situada nas Antilhas. Ela faz parte integrante da República Francesa.", choices: [{ id: 'a' as const, text: "A Martinica" }, { id: 'b' as const, text: "Cuba" }, { id: 'c' as const, text: "A Jamaica" }, { id: 'd' as const, text: "Haiti" }] },
  // Q28
  { textFr: "Combien y a-t-il de régions en France métropolitaine ?", lang: 'pt' as const, text: "Quantas regiões existem na França metropolitana?", explanation: "Desde a reforma territorial de 2016, a França metropolitana conta com 13 regiões. Esse número foi reduzido de 22 para 13 para reforçar a eficiência das coletividades territoriais.", choices: [{ id: 'a' as const, text: "13" }, { id: 'b' as const, text: "18" }, { id: 'c' as const, text: "22" }, { id: 'd' as const, text: "10" }] },
  // Q29
  { textFr: "Quelle ville est un grand port maritime ?", lang: 'pt' as const, text: "Qual cidade é um grande porto marítimo?", explanation: "Marselha é o maior porto marítimo da França e um dos mais importantes do Mediterrâneo. É também a segunda maior cidade da França.", choices: [{ id: 'a' as const, text: "Marselha" }, { id: 'b' as const, text: "Clermont-Ferrand" }, { id: 'c' as const, text: "Grenoble" }, { id: 'd' as const, text: "Limoges" }] },
  // Q30
  { textFr: "Quelle est la mer au sud de la France métropolitaine ?", lang: 'pt' as const, text: "Qual é o mar ao sul da França metropolitana?", explanation: "O mar Mediterrâneo banha o sul da França metropolitana. Ele se estende da fronteira espanhola à fronteira italiana, ao longo da Côte d'Azur e do Languedoc.", choices: [{ id: 'a' as const, text: "O mar Mediterrâneo" }, { id: 'b' as const, text: "O mar do Norte" }, { id: 'c' as const, text: "O mar Báltico" }, { id: 'd' as const, text: "O Canal da Mancha" }] },
  // Q31
  { textFr: "Quelle ville est située au bord de la mer Méditerranée ?", lang: 'pt' as const, text: "Qual cidade está situada à beira do mar Mediterrâneo?", explanation: "Nice é uma cidade situada na Côte d'Azur, à beira do mar Mediterrâneo. É um dos principais destinos turísticos do sul da França.", choices: [{ id: 'a' as const, text: "Nice" }, { id: 'b' as const, text: "Lille" }, { id: 'c' as const, text: "Estrasburgo" }, { id: 'd' as const, text: "Rennes" }] },
  // Q32
  { textFr: "Où se situe la Corse ?", lang: 'pt' as const, text: "Onde se situa a Córsega?", explanation: "A Córsega é uma ilha situada no mar Mediterrâneo, a sudeste da França metropolitana. É uma coletividade territorial única que possui um estatuto particular.", choices: [{ id: 'a' as const, text: "No mar Mediterrâneo" }, { id: 'b' as const, text: "No oceano Atlântico" }, { id: 'c' as const, text: "No Canal da Mancha" }, { id: 'd' as const, text: "No mar do Norte" }] },
  // Q33
  { textFr: "Quelle chaîne de montagnes est située entre la France et l'Italie ?", lang: 'pt' as const, text: "Qual cadeia de montanhas está situada entre a França e a Itália?", explanation: "Os Alpes formam uma fronteira natural entre a França e a Itália. O Mont Blanc, situado nos Alpes, é o pico mais alto da Europa Ocidental com 4.809 metros.", choices: [{ id: 'a' as const, text: "Os Alpes" }, { id: 'b' as const, text: "Os Pireneus" }, { id: 'c' as const, text: "O Jura" }, { id: 'd' as const, text: "Os Vosges" }] },
  // Q34
  { textFr: "Qui était Molière ?", lang: 'pt' as const, text: "Quem foi Molière?", explanation: "Molière (1622-1673) foi um dramaturgo e comediante francês do século XVII. Ele é autor de célebres comédias como O Doente Imaginário e O Misantropo.", choices: [{ id: 'a' as const, text: "Um dramaturgo e comediante francês do século XVII" }, { id: 'b' as const, text: "Um pintor do Renascimento" }, { id: 'c' as const, text: "Um compositor de música clássica" }, { id: 'd' as const, text: "Um filósofo do Iluminismo" }] },
  // Q35
  { textFr: "Qui était Charles Baudelaire ?", lang: 'pt' as const, text: "Quem foi Charles Baudelaire?", explanation: "Charles Baudelaire (1821-1867) foi um poeta francês, autor da célebre coletânea As Flores do Mal. Ele é considerado um dos precursores da poesia moderna.", choices: [{ id: 'a' as const, text: "Um poeta francês, autor de As Flores do Mal" }, { id: 'b' as const, text: "Um romancista autor de Os Miseráveis" }, { id: 'c' as const, text: "Um escultor do século XIX" }, { id: 'd' as const, text: "Um músico romântico" }] },
  // Q36
  { textFr: "Qui était George Sand ?", lang: 'pt' as const, text: "Quem foi George Sand?", explanation: "George Sand (1804-1876) foi uma romancista francesa, cujo nome verdadeiro era Amantine Lucile Aurore Dupin. Ela é conhecida por seus romances campestres e seu engajamento pelos direitos das mulheres.", choices: [{ id: 'a' as const, text: "Uma romancista francesa do século XIX" }, { id: 'b' as const, text: "Uma rainha da França" }, { id: 'c' as const, text: "Uma cientista Prêmio Nobel" }, { id: 'd' as const, text: "Uma cantora de ópera" }] },
  // Q37
  { textFr: "Qui était Simone de Beauvoir ?", lang: 'pt' as const, text: "Quem foi Simone de Beauvoir?", explanation: "Simone de Beauvoir (1908-1986) foi uma filósofa e escritora francesa, figura importante do feminismo. Ela é notadamente autora de O Segundo Sexo, obra fundadora do feminismo moderno.", choices: [{ id: 'a' as const, text: "Uma filósofa e escritora feminista francesa" }, { id: 'b' as const, text: "Uma resistente da Segunda Guerra Mundial" }, { id: 'c' as const, text: "Uma física francesa" }, { id: 'd' as const, text: "Uma atriz de cinema francesa" }] },
  // Q38
  { textFr: "Qui était Albert Camus ?", lang: 'pt' as const, text: "Quem foi Albert Camus?", explanation: "Albert Camus (1913-1960) foi um escritor e filósofo francês, Prêmio Nobel de Literatura em 1957. Ele é autor de O Estrangeiro e A Peste.", choices: [{ id: 'a' as const, text: "Um escritor e filósofo francês, Prêmio Nobel de Literatura" }, { id: 'b' as const, text: "Um pintor impressionista" }, { id: 'c' as const, text: "Um político da Terceira República" }, { id: 'd' as const, text: "Um compositor de música clássica" }] },
  // Q39
  { textFr: "Qui était Paul Cézanne ?", lang: 'pt' as const, text: "Quem foi Paul Cézanne?", explanation: "Paul Cézanne (1839-1906) foi um pintor francês, considerado o pai da arte moderna. Suas obras influenciaram o cubismo e numerosos movimentos artísticos do século XX.", choices: [{ id: 'a' as const, text: "Um pintor francês, precursor da arte moderna" }, { id: 'b' as const, text: "Um escritor naturalista" }, { id: 'c' as const, text: "Um escultor do século XVIII" }, { id: 'd' as const, text: "Um arquiteto do Renascimento" }] },
  // Q40
  { textFr: "Qui était Marc Chagall ?", lang: 'pt' as const, text: "Quem foi Marc Chagall?", explanation: "Marc Chagall (1887-1985) foi um pintor e gravurista de origem russa naturalizado francês. Ele é célebre por suas obras coloridas que misturam fantasia e simbolismo, notadamente os vitrais da Ópera de Paris.", choices: [{ id: 'a' as const, text: "Um pintor de origem russa naturalizado francês" }, { id: 'b' as const, text: "Um filósofo francês do Iluminismo" }, { id: 'c' as const, text: "Um músico clássico austríaco" }, { id: 'd' as const, text: "Um diretor de cinema italiano" }] },
  // Q41
  { textFr: "Qui était Joséphine Baker ?", lang: 'pt' as const, text: "Quem foi Joséphine Baker?", explanation: "Joséphine Baker (1906-1975) foi uma artista franco-americana, cantora e dançarina, resistente durante a Segunda Guerra Mundial. Ela foi homenageada no Panteão em 2021 por seu engajamento.", choices: [{ id: 'a' as const, text: "Uma artista franco-americana, cantora, dançarina e resistente" }, { id: 'b' as const, text: "Uma cientista franco-polonesa" }, { id: 'c' as const, text: "Uma política francesa" }, { id: 'd' as const, text: "Uma romancista do século XIX" }] },
  // Q42
  { textFr: "Qui était une chanteuse française célèbre ?", lang: 'pt' as const, text: "Quem foi uma cantora francesa famosa?", explanation: "Édith Piaf (1915-1963) é uma das cantoras francesas mais famosas do mundo. Ela é conhecida por canções como La Vie en rose e Non, je ne regrette rien.", choices: [{ id: 'a' as const, text: "Édith Piaf" }, { id: 'b' as const, text: "Madonna" }, { id: 'c' as const, text: "Beyoncé" }, { id: 'd' as const, text: "Adele" }] },
  // Q43
  { textFr: "Qu'est-ce que le Louvre ?", lang: 'pt' as const, text: "O que é o Louvre?", explanation: "O Louvre é o maior museu de arte do mundo, situado em Paris. Antigo palácio real, ele abriga obras famosas como a Mona Lisa de Leonardo da Vinci.", choices: [{ id: 'a' as const, text: "O maior museu de arte do mundo, situado em Paris" }, { id: 'b' as const, text: "Um castelo do Loire" }, { id: 'c' as const, text: "Uma catedral gótica" }, { id: 'd' as const, text: "Um teatro nacional" }] },
  // Q44
  { textFr: "Qui était Jean de la Fontaine ?", lang: 'pt' as const, text: "Quem foi Jean de la Fontaine?", explanation: "Jean de la Fontaine (1621-1695) foi um poeta francês célebre por suas Fábulas. Suas obras, como O Corvo e a Raposa, ainda são ensinadas nas escolas francesas.", choices: [{ id: 'a' as const, text: "Um poeta francês célebre por suas Fábulas" }, { id: 'b' as const, text: "Um rei da França" }, { id: 'c' as const, text: "Um pintor do Renascimento" }, { id: 'd' as const, text: "Um explorador do Novo Mundo" }] },
  // Q45
  { textFr: "Quel écrivain est français ?", lang: 'pt' as const, text: "Qual escritor é francês?", explanation: "Victor Hugo (1802-1885) é um dos maiores escritores franceses. Ele é autor de obras-primas como Os Miseráveis e O Corcunda de Notre-Dame.", choices: [{ id: 'a' as const, text: "Victor Hugo" }, { id: 'b' as const, text: "Charles Dickens" }, { id: 'c' as const, text: "Miguel de Cervantes" }, { id: 'd' as const, text: "William Shakespeare" }] },
  // Q46
  { textFr: "Dans quelle ville se trouve la tour Eiffel ?", lang: 'pt' as const, text: "Em qual cidade se encontra a Torre Eiffel?", explanation: "A Torre Eiffel se encontra em Paris. Construída por Gustave Eiffel para a Exposição Universal de 1889, ela se tornou o símbolo mais emblemático da França.", choices: [{ id: 'a' as const, text: "Paris" }, { id: 'b' as const, text: "Lyon" }, { id: 'c' as const, text: "Marselha" }, { id: 'd' as const, text: "Bordeaux" }] },
  // Q47
  { textFr: "Quand célèbre-t-on Noël ?", lang: 'pt' as const, text: "Quando se comemora o Natal?", explanation: "O Natal é comemorado em 25 de dezembro. É um feriado na França, festa cristã que também se tornou uma tradição cultural marcada pelas refeições em família e pela troca de presentes.", choices: [{ id: 'a' as const, text: "Em 25 de dezembro" }, { id: 'b' as const, text: "Em 1º de janeiro" }, { id: 'c' as const, text: "Em 14 de julho" }, { id: 'd' as const, text: "Em 1º de novembro" }] },
  // Q48
  { textFr: "Quel était le surnom de Louis XIV ?", lang: 'pt' as const, text: "Qual era o apelido de Luís XIV?", explanation: "Luís XIV era apelidado de Rei Sol. Ele reinou de 1643 a 1715, ou seja, 72 anos, o mais longo reinado da história da França, e mandou construir o Palácio de Versalhes.", choices: [{ id: 'a' as const, text: "O Rei Sol" }, { id: 'b' as const, text: "O Rei dos reis" }, { id: 'c' as const, text: "O Bem-Amado" }, { id: 'd' as const, text: "O Grande" }] },
  // Q49
  { textFr: "Quel roi de France a été exécuté pendant la Révolution française ?", lang: 'pt' as const, text: "Qual rei da França foi executado durante a Revolução Francesa?", explanation: "Luís XVI foi guilhotinado em 21 de janeiro de 1793 na Praça da Revolução em Paris. Ele havia sido julgado e condenado à morte pela Convenção Nacional por traição.", choices: [{ id: 'a' as const, text: "Luís XVI" }, { id: 'b' as const, text: "Luís XIV" }, { id: 'c' as const, text: "Luís XV" }, { id: 'd' as const, text: "Carlos X" }] },
  // Q50
  { textFr: "En quelle année Napoléon Ier est-il devenu empereur ?", lang: 'pt' as const, text: "Em que ano Napoleão I se tornou imperador?", explanation: "Napoleão I se tornou imperador dos franceses em 1804. Sua coroação aconteceu em 2 de dezembro de 1804 na catedral de Notre-Dame de Paris.", choices: [{ id: 'a' as const, text: "1804" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1799" }, { id: 'd' as const, text: "1815" }] },
  // Q51
  { textFr: "Lequel de ces personnages a un lien avec la République française ?", lang: 'pt' as const, text: "Qual desses personagens tem ligação com a República Francesa?", explanation: "Marianne é o símbolo alegórico da República Francesa. Ela representa os valores de liberdade, igualdade e fraternidade, e seu busto está presente em todas as prefeituras.", choices: [{ id: 'a' as const, text: "Marianne" }, { id: 'b' as const, text: "Britannia" }, { id: 'c' as const, text: "Tio Sam" }, { id: 'd' as const, text: "John Bull" }] },
  // Q52
  { textFr: "De quand date l'appel à la résistance du général de Gaulle ?", lang: 'pt' as const, text: "De quando data o apelo à resistência do general de Gaulle?", explanation: "O apelo do general de Gaulle data de 18 de junho de 1940. De Londres, ele convocou os franceses a resistir contra a ocupação alemã pela BBC.", choices: [{ id: 'a' as const, text: "18 de junho de 1940" }, { id: 'b' as const, text: "8 de maio de 1945" }, { id: 'c' as const, text: "14 de julho de 1940" }, { id: 'd' as const, text: "25 de agosto de 1944" }] },
  // Q53
  { textFr: "Pourquoi la Shoah est-elle étudiée à l'école ?", lang: 'pt' as const, text: "Por que a Shoah é estudada na escola?", explanation: "A Shoah é estudada na escola para transmitir a memória desse genocídio e sensibilizar os alunos para o dever de memória. Isso permite combater o racismo, o antissemitismo e toda forma de discriminação.", choices: [{ id: 'a' as const, text: "Pelo dever de memória e para combater o racismo e o antissemitismo" }, { id: 'b' as const, text: "Para preparar os alunos para os exames de história" }, { id: 'c' as const, text: "Para ensinar a geografia da Europa" }, { id: 'd' as const, text: "Para estudar a economia de guerra" }] },
  // Q54
  { textFr: "Quel pays a été colonisé par la France ?", lang: 'pt' as const, text: "Qual país foi colonizado pela França?", explanation: "O Senegal foi uma colônia francesa da África Ocidental. Ele obteve sua independência em 1960, como muitos países africanos francófonos.", choices: [{ id: 'a' as const, text: "O Senegal" }, { id: 'b' as const, text: "A Nigéria" }, { id: 'c' as const, text: "A África do Sul" }, { id: 'd' as const, text: "A Etiópia" }] },
  // Q55
  { textFr: "Depuis quand les Français élisent-ils le président de la République au suffrage universel direct ?", lang: 'pt' as const, text: "Desde quando os franceses elegem o presidente da República por sufrágio universal direto?", explanation: "Desde 1962, os franceses elegem o presidente da República por sufrágio universal direto, após o referendo desejado pelo general de Gaulle. Antes dessa data, o presidente era eleito por um colégio eleitoral.", choices: [{ id: 'a' as const, text: "1962" }, { id: 'b' as const, text: "1958" }, { id: 'c' as const, text: "1945" }, { id: 'd' as const, text: "1981" }] },
  // Q56
  { textFr: "Quelle est la première étape de la construction européenne en 1951 ?", lang: 'pt' as const, text: "Qual é a primeira etapa da construção europeia em 1951?", explanation: "A Comunidade Europeia do Carvão e do Aço (CECA), criada em 1951, é a primeira etapa da construção europeia. Ela foi fundada por seis países para colocar em comum suas produções de carvão e aço.", choices: [{ id: 'a' as const, text: "A criação da Comunidade Europeia do Carvão e do Aço (CECA)" }, { id: 'b' as const, text: "A criação da União Europeia" }, { id: 'c' as const, text: "A assinatura do Tratado de Maastricht" }, { id: 'd' as const, text: "A adoção do euro" }] },
  // Q57
  { textFr: "Durant le mandat de quel président la peine de mort a-t-elle été abolie ?", lang: 'pt' as const, text: "Durante o mandato de qual presidente a pena de morte foi abolida?", explanation: "A pena de morte foi abolida em 1981 durante a presidência de François Mitterrand, graças à ação do Ministro da Justiça Robert Badinter. A França foi um dos últimos países da Europa Ocidental a aboli-la.", choices: [{ id: 'a' as const, text: "François Mitterrand" }, { id: 'b' as const, text: "Valéry Giscard d'Estaing" }, { id: 'c' as const, text: "Jacques Chirac" }, { id: 'd' as const, text: "Charles de Gaulle" }] },
  // Q58
  { textFr: "Quel régime politique a été mis en place pendant la Révolution française en 1792 ?", lang: 'pt' as const, text: "Qual regime político foi estabelecido durante a Revolução Francesa em 1792?", explanation: "A Primeira República foi proclamada em 21 de setembro de 1792, após a abolição da monarquia. É o primeiro regime republicano da história da França.", choices: [{ id: 'a' as const, text: "A República (Primeira República)" }, { id: 'b' as const, text: "O Império" }, { id: 'c' as const, text: "A monarquia constitucional" }, { id: 'd' as const, text: "A ditadura militar" }] },
  // Q59
  { textFr: "Qui était une figure de la Résistance française pendant la Seconde Guerre mondiale ?", lang: 'pt' as const, text: "Quem foi uma figura da Resistência Francesa durante a Segunda Guerra Mundial?", explanation: "Jean Moulin (1899-1943) foi um alto funcionário e resistente francês. Ele unificou os movimentos de resistência sob a autoridade do general de Gaulle antes de ser preso e morto pela Gestapo.", choices: [{ id: 'a' as const, text: "Jean Moulin" }, { id: 'b' as const, text: "Philippe Pétain" }, { id: 'c' as const, text: "Pierre Laval" }, { id: 'd' as const, text: "Adolphe Thiers" }] },
  // Q60
  { textFr: "En 1944, qu'est-ce qui a changé pour les femmes ?", lang: 'pt' as const, text: "Em 1944, o que mudou para as mulheres?", explanation: "Em 1944, as mulheres obtiveram o direito de voto na França. Elas votaram pela primeira vez nas eleições municipais de 29 de abril de 1945.", choices: [{ id: 'a' as const, text: "Elas obtiveram o direito de voto" }, { id: 'b' as const, text: "Elas obtiveram o direito de trabalhar" }, { id: 'c' as const, text: "Elas obtiveram o direito de se divorciar" }, { id: 'd' as const, text: "Elas obtiveram o direito de abrir uma conta bancária" }] },
  // Q61
  { textFr: "Quelle organisation internationale a été créée en 1945 après la Seconde Guerre mondiale ?", lang: 'pt' as const, text: "Qual organização internacional foi criada em 1945 após a Segunda Guerra Mundial?", explanation: "A Organização das Nações Unidas (ONU) foi criada em 1945 para manter a paz e a segurança internacionais. A França é um dos cinco membros permanentes do Conselho de Segurança.", choices: [{ id: 'a' as const, text: "A Organização das Nações Unidas (ONU)" }, { id: 'b' as const, text: "A União Europeia" }, { id: 'c' as const, text: "A OTAN" }, { id: 'd' as const, text: "A Cruz Vermelha" }] },
  // Q62
  { textFr: "Quelle peine a été supprimée en 1981 ?", lang: 'pt' as const, text: "Qual pena foi suprimida em 1981?", explanation: "A pena de morte foi abolida na França em 9 de outubro de 1981 pela lei apresentada por Robert Badinter. A França assim se juntou aos países europeus que haviam suprimido a pena capital.", choices: [{ id: 'a' as const, text: "A pena de morte" }, { id: 'b' as const, text: "A pena de prisão perpétua" }, { id: 'c' as const, text: "Os trabalhos forçados" }, { id: 'd' as const, text: "O banimento" }] },
  // Q63
  { textFr: "En quelle année l'euro est-il devenu la monnaie utilisée en France ?", lang: 'pt' as const, text: "Em que ano o euro se tornou a moeda utilizada na França?", explanation: "O euro se tornou a moeda utilizada na França em 1º de janeiro de 2002, substituindo o franco francês. O euro é hoje a moeda comum de 20 países da zona do euro.", choices: [{ id: 'a' as const, text: "2002" }, { id: 'b' as const, text: "1999" }, { id: 'c' as const, text: "1992" }, { id: 'd' as const, text: "2005" }] },
  // Q64
  { textFr: "En quelle année a commencé la Première Guerre mondiale ?", lang: 'pt' as const, text: "Em que ano começou a Primeira Guerra Mundial?", explanation: "A Primeira Guerra Mundial começou em 1914, desencadeada pelo assassinato do arquiduque Francisco Ferdinando da Áustria. A França se envolveu no conflito desde o início.", choices: [{ id: 'a' as const, text: "1914" }, { id: 'b' as const, text: "1916" }, { id: 'c' as const, text: "1912" }, { id: 'd' as const, text: "1939" }] },
  // Q65
  { textFr: "Où a eu lieu le débarquement en 1944 ?", lang: 'pt' as const, text: "Onde ocorreu o desembarque em 1944?", explanation: "O desembarque de 6 de junho de 1944 (Dia D) ocorreu nas praias da Normandia. Essa operação militar aliada marcou o início da libertação da França da ocupação nazista.", choices: [{ id: 'a' as const, text: "Na Normandia" }, { id: 'b' as const, text: "Na Bretanha" }, { id: 'c' as const, text: "Na Provença" }, { id: 'd' as const, text: "Na Picardia" }] },
  // Q66
  { textFr: "Quel continent a été le plus concerné par la décolonisation française après la Seconde Guerre mondiale ?", lang: 'pt' as const, text: "Qual continente foi mais afetado pela descolonização francesa após a Segunda Guerra Mundial?", explanation: "A África foi o continente mais afetado pela descolonização francesa. A maioria das colônias francesas na África obteve sua independência na década de 1960.", choices: [{ id: 'a' as const, text: "A África" }, { id: 'b' as const, text: "A Ásia" }, { id: 'c' as const, text: "A América do Sul" }, { id: 'd' as const, text: "A Oceania" }] },
  // Q67
  { textFr: "Que fête-t-on le 8 mai ?", lang: 'pt' as const, text: "O que se comemora em 8 de maio?", explanation: "O 8 de maio comemora o fim da Segunda Guerra Mundial na Europa (vitória dos Aliados sobre a Alemanha nazista em 1945). É um feriado na França.", choices: [{ id: 'a' as const, text: "O fim da Segunda Guerra Mundial na Europa" }, { id: 'b' as const, text: "A festa do Trabalho" }, { id: 'c' as const, text: "O armistício da Primeira Guerra Mundial" }, { id: 'd' as const, text: "A festa nacional" }] },
  // Q68
  { textFr: "Quelle mer ou océan borde la France métropolitaine ?", lang: 'pt' as const, text: "Qual mar ou oceano banha a França metropolitana?", explanation: "O mar Mediterrâneo banha o sul da França metropolitana. A França também é banhada pelo oceano Atlântico a oeste e pelo Canal da Mancha ao norte.", choices: [{ id: 'a' as const, text: "O mar Mediterrâneo" }, { id: 'b' as const, text: "O mar Cáspio" }, { id: 'c' as const, text: "O mar Negro" }, { id: 'd' as const, text: "O mar Vermelho" }] },
  // Q69
  { textFr: "Quel pays a une frontière terrestre avec la France métropolitaine ?", lang: 'pt' as const, text: "Qual país tem fronteira terrestre com a França metropolitana?", explanation: "A Espanha compartilha uma fronteira terrestre com a França ao sul, ao longo dos Pireneus. A França metropolitana também tem fronteiras com a Bélgica, Luxemburgo, Alemanha, Suíça, Itália e Mônaco.", choices: [{ id: 'a' as const, text: "A Espanha" }, { id: 'b' as const, text: "Portugal" }, { id: 'c' as const, text: "A Inglaterra" }, { id: 'd' as const, text: "A Polônia" }] },
  // Q70
  { textFr: "Quelle ville française est un port maritime ?", lang: 'pt' as const, text: "Qual cidade francesa é um porto marítimo?", explanation: "Le Havre é um grande porto marítimo francês situado na Normandia, na foz do Sena. É um dos mais importantes portos comerciais da França.", choices: [{ id: 'a' as const, text: "Le Havre" }, { id: 'b' as const, text: "Toulouse" }, { id: 'c' as const, text: "Clermont-Ferrand" }, { id: 'd' as const, text: "Estrasburgo" }] },
  // Q71
  { textFr: "Quelle mer se situe entre la France et l'Angleterre ?", lang: 'pt' as const, text: "Qual mar se situa entre a França e a Inglaterra?", explanation: "O Canal da Mancha separa a França da Inglaterra. Ele liga o oceano Atlântico ao mar do Norte e é atravessado pelo Eurotúnel desde 1994.", choices: [{ id: 'a' as const, text: "O Canal da Mancha" }, { id: 'b' as const, text: "O mar do Norte" }, { id: 'c' as const, text: "O mar Mediterrâneo" }, { id: 'd' as const, text: "O mar Báltico" }] },
  // Q72
  { textFr: "Qu'est-ce que la France d'outre-mer ?", lang: 'pt' as const, text: "O que é a França ultramarina?", explanation: "A França ultramarina designa o conjunto dos territórios franceses situados fora da Europa. Ela compreende departamentos (Guadalupe, Martinica, Guiana, Reunião, Mayotte) e coletividades ultramarinas.", choices: [{ id: 'a' as const, text: "O conjunto dos territórios franceses situados fora da Europa" }, { id: 'b' as const, text: "As regiões do sul da França" }, { id: 'c' as const, text: "As antigas colônias francesas independentes" }, { id: 'd' as const, text: "Os países francófonos da África" }] },
  // Q73
  { textFr: "Quelle chaîne de montagnes est située entre la France et l'Espagne ?", lang: 'pt' as const, text: "Qual cadeia de montanhas está situada entre a França e a Espanha?", explanation: "Os Pireneus formam uma fronteira natural entre a França e a Espanha em aproximadamente 430 km. Seu ponto culminante é o pico de Aneto (3.404 m) do lado espanhol.", choices: [{ id: 'a' as const, text: "Os Pireneus" }, { id: 'b' as const, text: "Os Alpes" }, { id: 'c' as const, text: "O Jura" }, { id: 'd' as const, text: "Os Vosges" }] },
  // Q74
  { textFr: "Quelle île française se trouve dans l'océan Indien ?", lang: 'pt' as const, text: "Qual ilha francesa se encontra no oceano Índico?", explanation: "A Reunião é um departamento francês ultramarino situado no oceano Índico, a leste de Madagáscar. É uma ilha vulcânica com aproximadamente 900.000 habitantes.", choices: [{ id: 'a' as const, text: "A Reunião" }, { id: 'b' as const, text: "A Martinica" }, { id: 'c' as const, text: "A Guadalupe" }, { id: 'd' as const, text: "A Córsega" }] },
  // Q75
  { textFr: "Quelle est la population approximative de la France en 2025 ?", lang: 'pt' as const, text: "Qual é a população aproximada da França em 2025?", explanation: "A França tem aproximadamente 68 milhões de habitantes em 2025, incluindo os territórios ultramarinos. É o segundo país mais populoso da União Europeia depois da Alemanha.", choices: [{ id: 'a' as const, text: "68 milhões de habitantes" }, { id: 'b' as const, text: "50 milhões de habitantes" }, { id: 'c' as const, text: "80 milhões de habitantes" }, { id: 'd' as const, text: "45 milhões de habitantes" }] },
  // Q76
  { textFr: "Quel fleuve traverse Paris ?", lang: 'pt' as const, text: "Qual rio atravessa Paris?", explanation: "O Sena atravessa Paris de leste a oeste. Esse rio de 776 km nasce na Borgonha e deságua no Canal da Mancha em Le Havre.", choices: [{ id: 'a' as const, text: "O Sena" }, { id: 'b' as const, text: "O Loire" }, { id: 'c' as const, text: "O Ródano" }, { id: 'd' as const, text: "O Garona" }] },
  // Q77
  { textFr: "Lequel de ces pays partage des frontières terrestres avec la France ?", lang: 'pt' as const, text: "Qual desses países compartilha fronteiras terrestres com a França?", explanation: "A Bélgica compartilha uma fronteira terrestre com a França ao norte. Os dois países são vizinhos e parceiros na União Europeia.", choices: [{ id: 'a' as const, text: "A Bélgica" }, { id: 'b' as const, text: "Os Países Baixos" }, { id: 'c' as const, text: "O Reino Unido" }, { id: 'd' as const, text: "A Dinamarca" }] },
  // Q78
  { textFr: "Quel pays a une frontière avec la France métropolitaine au nord-est ?", lang: 'pt' as const, text: "Qual país tem fronteira com a França metropolitana a nordeste?", explanation: "A Alemanha compartilha uma fronteira com a França a nordeste, ao longo do Reno. Essa fronteira foi palco de numerosos conflitos antes de se tornar um símbolo da reconciliação franco-alemã.", choices: [{ id: 'a' as const, text: "A Alemanha" }, { id: 'b' as const, text: "A Polônia" }, { id: 'c' as const, text: "A Áustria" }, { id: 'd' as const, text: "A República Tcheca" }] },
  // Q79
  { textFr: "Où se trouvent les principales activités économiques en France ?", lang: 'pt' as const, text: "Onde se encontram as principais atividades econômicas na França?", explanation: "As principais atividades econômicas na França se concentram nas grandes metrópoles, em particular na região parisiense (Île-de-France). Lyon, Marselha e outras grandes cidades também são polos econômicos importantes.", choices: [{ id: 'a' as const, text: "Nas grandes metrópoles e na região parisiense" }, { id: 'b' as const, text: "Somente no sul da França" }, { id: 'c' as const, text: "Principalmente nas zonas rurais" }, { id: 'd' as const, text: "Exclusivamente no litoral" }] },
  // Q80
  { textFr: "Parmi ces pays, lequel attire le plus de visiteurs chaque année ?", lang: 'pt' as const, text: "Entre esses países, qual atrai mais visitantes a cada ano?", explanation: "A França é o primeiro destino turístico mundial com aproximadamente 90 milhões de visitantes estrangeiros por ano. Seu patrimônio cultural, sua gastronomia e suas paisagens variadas atraem turistas do mundo inteiro.", choices: [{ id: 'a' as const, text: "A França" }, { id: 'b' as const, text: "A Itália" }, { id: 'c' as const, text: "Os Estados Unidos" }, { id: 'd' as const, text: "A Espanha" }] },
  // Q81
  { textFr: "Où habite la majorité des Français ?", lang: 'pt' as const, text: "Onde mora a maioria dos franceses?", explanation: "A maioria dos franceses mora em cidades (aproximadamente 80% da população é urbana). As grandes aglomerações como Paris, Lyon e Marselha concentram uma parte importante da população.", choices: [{ id: 'a' as const, text: "Na cidade" }, { id: 'b' as const, text: "No campo" }, { id: 'c' as const, text: "Na montanha" }, { id: 'd' as const, text: "No litoral" }] },
  // Q82
  { textFr: "Quelle région est la plus peuplée ?", lang: 'pt' as const, text: "Qual região é a mais populosa?", explanation: "A Île-de-France é a região mais populosa da França com aproximadamente 12 milhões de habitantes. Ela compreende Paris e seus subúrbios, concentrando um quinto da população francesa.", choices: [{ id: 'a' as const, text: "A Île-de-France" }, { id: 'b' as const, text: "A Provence-Alpes-Côte d'Azur" }, { id: 'c' as const, text: "A Occitânia" }, { id: 'd' as const, text: "A Nova Aquitânia" }] },
  // Q83
  { textFr: "Quelle ville française fait partie des 10 plus grandes métropoles du pays ?", lang: 'pt' as const, text: "Qual cidade francesa faz parte das 10 maiores metrópoles do país?", explanation: "Toulouse faz parte das 10 maiores metrópoles da França. É a quarta cidade da França por sua população e um polo importante da indústria aeronáutica.", choices: [{ id: 'a' as const, text: "Toulouse" }, { id: 'b' as const, text: "Basileia" }, { id: 'c' as const, text: "Lausanne" }, { id: 'd' as const, text: "Charleroi" }] },
  // Q84
  { textFr: "Lequel de ces départements de France est le plus touristique ?", lang: 'pt' as const, text: "Qual desses departamentos da França é o mais turístico?", explanation: "Paris (departamento 75) é o departamento mais turístico da França. A capital atrai milhões de visitantes a cada ano graças a seus monumentos, museus e vida cultural.", choices: [{ id: 'a' as const, text: "Paris" }, { id: 'b' as const, text: "Creuse" }, { id: 'c' as const, text: "Cantal" }, { id: 'd' as const, text: "Lozère" }] },
  // Q85
  { textFr: "Quand peut-on visiter gratuitement des lieux culturels en France ?", lang: 'pt' as const, text: "Quando é possível visitar gratuitamente locais culturais na França?", explanation: "As Jornadas Europeias do Patrimônio, organizadas todo ano em setembro, permitem visitar gratuitamente numerosos locais culturais e monumentos históricos na França.", choices: [{ id: 'a' as const, text: "Durante as Jornadas Europeias do Patrimônio" }, { id: 'b' as const, text: "Somente em 14 de julho" }, { id: 'c' as const, text: "Todos os domingos do ano" }, { id: 'd' as const, text: "Durante as férias escolares" }] },
  // Q86
  { textFr: "Combien de personnes parlent français dans le monde ?", lang: 'pt' as const, text: "Quantas pessoas falam francês no mundo?", explanation: "Aproximadamente 300 milhões de pessoas falam francês no mundo. O francês é a quinta língua mais falada e é língua oficial em 29 países.", choices: [{ id: 'a' as const, text: "Aproximadamente 300 milhões" }, { id: 'b' as const, text: "Aproximadamente 100 milhões" }, { id: 'c' as const, text: "Aproximadamente 500 milhões" }, { id: 'd' as const, text: "Aproximadamente 50 milhões" }] },
  // Q87
  { textFr: "Qui était Marguerite Yourcenar ?", lang: 'pt' as const, text: "Quem foi Marguerite Yourcenar?", explanation: "Marguerite Yourcenar (1903-1987) foi uma escritora francesa, primeira mulher eleita para a Academia Francesa em 1980. Ela é conhecida por seus romances históricos como Memórias de Adriano.", choices: [{ id: 'a' as const, text: "A primeira mulher eleita para a Academia Francesa" }, { id: 'b' as const, text: "Uma cientista Prêmio Nobel de Física" }, { id: 'c' as const, text: "Uma exploradora do século XIX" }, { id: 'd' as const, text: "Uma compositora de música barroca" }] },
  // Q88
  { textFr: "Quel peintre est français ?", lang: 'pt' as const, text: "Qual pintor é francês?", explanation: "Claude Monet (1840-1926) foi um pintor francês, fundador do movimento impressionista. Ele é célebre por suas séries de pinturas dos Nenúfares e da catedral de Rouen.", choices: [{ id: 'a' as const, text: "Claude Monet" }, { id: 'b' as const, text: "Pablo Picasso" }, { id: 'c' as const, text: "Vincent van Gogh" }, { id: 'd' as const, text: "Salvador Dalí" }] },
  // Q89
  { textFr: "Quel musée est situé à Paris ?", lang: 'pt' as const, text: "Qual museu está situado em Paris?", explanation: "O Museu d'Orsay está situado em Paris, em uma antiga estação ferroviária. Ele abriga a maior coleção de arte impressionista e pós-impressionista do mundo.", choices: [{ id: 'a' as const, text: "O Museu d'Orsay" }, { id: 'b' as const, text: "O British Museum" }, { id: 'c' as const, text: "O Museu do Prado" }, { id: 'd' as const, text: "O Metropolitan Museum" }] },
  // Q90
  { textFr: "Qui était Auguste Rodin ?", lang: 'pt' as const, text: "Quem foi Auguste Rodin?", explanation: "Auguste Rodin (1840-1917) foi um escultor francês, considerado o pai da escultura moderna. Ele é autor de O Pensador e Os Burgueses de Calais.", choices: [{ id: 'a' as const, text: "Um escultor francês, autor de O Pensador" }, { id: 'b' as const, text: "Um pintor impressionista" }, { id: 'c' as const, text: "Um arquiteto da Torre Eiffel" }, { id: 'd' as const, text: "Um escritor romântico" }] },
  // Q91
  { textFr: "Quel est le classement de la langue française parmi les langues les plus parlées dans le monde ?", lang: 'pt' as const, text: "Qual é a classificação da língua francesa entre as línguas mais faladas no mundo?", explanation: "O francês é a quinta língua mais falada no mundo. É língua oficial em 29 países e é falada nos cinco continentes.", choices: [{ id: 'a' as const, text: "5ª língua mais falada" }, { id: 'b' as const, text: "2ª língua mais falada" }, { id: 'c' as const, text: "10ª língua mais falada" }, { id: 'd' as const, text: "1ª língua mais falada" }] },
  // Q92
  { textFr: "Quelle cathédrale célèbre a été en partie détruite par un incendie en 2019 ?", lang: 'pt' as const, text: "Qual catedral famosa foi parcialmente destruída por um incêndio em 2019?", explanation: "A catedral de Notre-Dame de Paris foi gravemente danificada por um incêndio em 15 de abril de 2019. Sua torre e parte do telhado desabaram. Ela foi restaurada e reaberta em dezembro de 2024.", choices: [{ id: 'a' as const, text: "Notre-Dame de Paris" }, { id: 'b' as const, text: "A catedral de Reims" }, { id: 'c' as const, text: "A catedral de Chartres" }, { id: 'd' as const, text: "A catedral de Estrasburgo" }] },
  // Q93
  { textFr: "Qui était une écrivaine française célèbre ?", lang: 'pt' as const, text: "Quem foi uma escritora francesa famosa?", explanation: "Colette (1873-1954) foi uma romancista francesa famosa, autora de numerosos romances como a série Claudine. Ela foi a segunda mulher a receber funerais nacionais na França.", choices: [{ id: 'a' as const, text: "Colette" }, { id: 'b' as const, text: "Jane Austen" }, { id: 'c' as const, text: "Virginia Woolf" }, { id: 'd' as const, text: "Agatha Christie" }] },
  // Q94
  { textFr: "Qui était un célèbre musicien français ?", lang: 'pt' as const, text: "Quem foi um famoso músico francês?", explanation: "Claude Debussy (1862-1918) foi um compositor francês, figura importante da música impressionista. Ele é notadamente conhecido por Clair de lune e La Mer.", choices: [{ id: 'a' as const, text: "Claude Debussy" }, { id: 'b' as const, text: "Ludwig van Beethoven" }, { id: 'c' as const, text: "Wolfgang Amadeus Mozart" }, { id: 'd' as const, text: "Johann Sebastian Bach" }] },
  // Q95
  { textFr: "Qui était Auguste Renoir ?", lang: 'pt' as const, text: "Quem foi Auguste Renoir?", explanation: "Auguste Renoir (1841-1919) foi um pintor francês, um dos grandes mestres do impressionismo. Ele é célebre por suas cenas da vida cotidiana e seus retratos luminosos.", choices: [{ id: 'a' as const, text: "Um pintor impressionista francês" }, { id: 'b' as const, text: "Um escultor do século XVIII" }, { id: 'c' as const, text: "Um escritor realista" }, { id: 'd' as const, text: "Um arquiteto do Renascimento" }] },
  // Q96
  { textFr: "Quelle fête est française ?", lang: 'pt' as const, text: "Qual festa é francesa?", explanation: "A Festa da Música, celebrada em 21 de junho, é uma festa de origem francesa criada em 1982 por Jack Lang. Hoje ela é celebrada em numerosos países do mundo.", choices: [{ id: 'a' as const, text: "A Festa da Música" }, { id: 'b' as const, text: "Ação de Graças" }, { id: 'c' as const, text: "Halloween" }, { id: 'd' as const, text: "O Dia de São Patrício" }] },
  // Q97
  { textFr: "Parmi ces textes, lequel a été adopté sous Napoléon Ier ?", lang: 'pt' as const, text: "Entre esses textos, qual foi adotado sob Napoleão I?", explanation: "O Código Civil foi adotado em 1804 sob Napoleão I. Também chamado de Código Napoleão, ele unificou o direito francês e continua sendo a base do direito civil na França.", choices: [{ id: 'a' as const, text: "O Código Civil" }, { id: 'b' as const, text: "A Declaração dos Direitos do Homem e do Cidadão" }, { id: 'c' as const, text: "A lei de separação entre Igreja e Estado" }, { id: 'd' as const, text: "A Constituição da Quinta República" }] },
  // Q98
  { textFr: "Qui a été président de la Ve République ?", lang: 'pt' as const, text: "Quem foi presidente da Quinta República?", explanation: "Jacques Chirac foi presidente da Quinta República de 1995 a 2007. Ele foi o quinto presidente da Quinta República, precedido por François Mitterrand.", choices: [{ id: 'a' as const, text: "Jacques Chirac" }, { id: 'b' as const, text: "Winston Churchill" }, { id: 'c' as const, text: "Konrad Adenauer" }, { id: 'd' as const, text: "Benito Mussolini" }] },
  // Q99
  { textFr: "Que signifie la date du 14 juillet pour les Français ?", lang: 'pt' as const, text: "O que significa a data de 14 de julho para os franceses?", explanation: "O 14 de julho é a festa nacional francesa. Ela comemora a tomada da Bastilha em 1789, símbolo do fim do absolutismo, e a Festa da Federação de 1790.", choices: [{ id: 'a' as const, text: "É a festa nacional, comemorando a tomada da Bastilha" }, { id: 'b' as const, text: "É o aniversário da Constituição" }, { id: 'c' as const, text: "É a festa da Europa" }, { id: 'd' as const, text: "É o dia do armistício" }] },
  // Q100
  { textFr: "Lequel de ces pays est un pays fondateur de l'Union européenne ?", lang: 'pt' as const, text: "Qual desses países é um país fundador da União Europeia?", explanation: "A França é um dos seis países fundadores da construção europeia com a Alemanha, a Itália, a Bélgica, os Países Baixos e Luxemburgo. A CECA foi criada em 1951.", choices: [{ id: 'a' as const, text: "A França" }, { id: 'b' as const, text: "O Reino Unido" }, { id: 'c' as const, text: "A Espanha" }, { id: 'd' as const, text: "A Polônia" }] },
  // Q101
  { textFr: "Dans quelle région est située une partie des plages du débarquement ?", lang: 'pt' as const, text: "Em qual região está situada uma parte das praias do desembarque?", explanation: "As praias do desembarque de 6 de junho de 1944 estão situadas na Normandia. As cinco praias (Utah, Omaha, Gold, Juno, Sword) são locais de memória importantes.", choices: [{ id: 'a' as const, text: "A Normandia" }, { id: 'b' as const, text: "A Bretanha" }, { id: 'c' as const, text: "A Picardia" }, { id: 'd' as const, text: "A Aquitânia" }] },
  // Q102
  { textFr: "Dans quelle ville les rois de France étaient-ils couronnés ?", lang: 'pt' as const, text: "Em qual cidade os reis da França eram coroados?", explanation: "Os reis da França eram tradicionalmente coroados na catedral de Reims. Essa tradição remonta ao batismo de Clóvis por volta de 496 e perdurou por séculos.", choices: [{ id: 'a' as const, text: "Reims" }, { id: 'b' as const, text: "Paris" }, { id: 'c' as const, text: "Versalhes" }, { id: 'd' as const, text: "Orléans" }] },
  // Q103
  { textFr: "En quelle année l'Union européenne a-t-elle été fondée ?", lang: 'pt' as const, text: "Em que ano a União Europeia foi fundada?", explanation: "A União Europeia foi fundada em 1992 pelo Tratado de Maastricht. Esse tratado transformou a Comunidade Econômica Europeia em União Europeia e lançou as bases da moeda única.", choices: [{ id: 'a' as const, text: "1992" }, { id: 'b' as const, text: "1957" }, { id: 'c' as const, text: "2002" }, { id: 'd' as const, text: "1951" }] },
  // Q104
  { textFr: "Qui a aboli l'esclavage en France ?", lang: 'pt' as const, text: "Quem aboliu a escravidão na França?", explanation: "Victor Schœlcher está na origem do decreto de abolição definitiva da escravidão na França em 27 de abril de 1848. Ele era então subsecretário de Estado das colônias sob a Segunda República.", choices: [{ id: 'a' as const, text: "Victor Schœlcher" }, { id: 'b' as const, text: "Napoleão Bonaparte" }, { id: 'c' as const, text: "Jules Ferry" }, { id: 'd' as const, text: "Léon Gambetta" }] },
  // Q105
  { textFr: "Lors de la Seconde Guerre mondiale, à quelle date Paris a-t-elle été libérée ?", lang: 'pt' as const, text: "Durante a Segunda Guerra Mundial, em que data Paris foi libertada?", explanation: "Paris foi libertada em 25 de agosto de 1944 após uma insurreição popular e a chegada da 2ª Divisão Blindada do general Leclerc. Esse evento marca um momento decisivo na libertação da França.", choices: [{ id: 'a' as const, text: "25 de agosto de 1944" }, { id: 'b' as const, text: "6 de junho de 1944" }, { id: 'c' as const, text: "8 de maio de 1945" }, { id: 'd' as const, text: "18 de junho de 1940" }] },
  // Q106
  { textFr: "Quel était le principal port français impliqué dans la traite négrière au XVIIIe siècle ?", lang: 'pt' as const, text: "Qual era o principal porto francês envolvido no tráfico negreiro no século XVIII?", explanation: "Nantes era o principal porto francês envolvido no tráfico negreiro no século XVIII. A cidade organizou o maior número de expedições negreiras francesas e possui hoje um memorial da abolição da escravidão.", choices: [{ id: 'a' as const, text: "Nantes" }, { id: 'b' as const, text: "Marselha" }, { id: 'c' as const, text: "Le Havre" }, { id: 'd' as const, text: "Brest" }] },
  // Q107
  { textFr: "Quel célèbre philosophe des Lumières a dénoncé l'esclavage ?", lang: 'pt' as const, text: "Qual célebre filósofo do Iluminismo denunciou a escravidão?", explanation: "Voltaire (1694-1778) foi um filósofo do Iluminismo que denunciou a escravidão, notadamente em Cândido. Os filósofos do Iluminismo desempenharam um papel importante no questionamento dessa prática.", choices: [{ id: 'a' as const, text: "Voltaire" }, { id: 'b' as const, text: "Napoleão Bonaparte" }, { id: 'c' as const, text: "Luís XIV" }, { id: 'd' as const, text: "Richelieu" }] },
  // Q108
  { textFr: "Quel plat est une spécialité de la cuisine française ?", lang: 'pt' as const, text: "Qual prato é uma especialidade da culinária francesa?", explanation: "O coq au vin é um prato tradicional da culinária francesa, feito com frango cozido em vinho tinto com bacon e cogumelos. A gastronomia francesa está inscrita no patrimônio imaterial da UNESCO.", choices: [{ id: 'a' as const, text: "O coq au vin" }, { id: 'b' as const, text: "A paella" }, { id: 'c' as const, text: "Os sushis" }, { id: 'd' as const, text: "O fish and chips" }] },
  // Q109
  { textFr: "Qui était Marie Curie ?", lang: 'pt' as const, text: "Quem foi Marie Curie?", explanation: "Marie Curie (1867-1934) foi uma física e química franco-polonesa, primeira mulher a receber um Prêmio Nobel. Ela recebeu dois Prêmios Nobel (Física em 1903 e Química em 1911) por seus trabalhos sobre a radioatividade.", choices: [{ id: 'a' as const, text: "Uma física franco-polonesa, duas vezes Prêmio Nobel" }, { id: 'b' as const, text: "Uma romancista francesa do século XIX" }, { id: 'c' as const, text: "Uma resistente da Segunda Guerra Mundial" }, { id: 'd' as const, text: "Uma rainha da França" }] },
  // Q110
  { textFr: "Qui a peint « La Liberté guidant le peuple » ?", lang: 'pt' as const, text: "Quem pintou \"A Liberdade Guiando o Povo\"?", explanation: "Eugène Delacroix pintou A Liberdade Guiando o Povo em 1830. Esse célebre quadro representa a Revolução de Julho de 1830 e está exposto no Museu do Louvre.", choices: [{ id: 'a' as const, text: "Eugène Delacroix" }, { id: 'b' as const, text: "Claude Monet" }, { id: 'c' as const, text: "Paul Cézanne" }, { id: 'd' as const, text: "Auguste Renoir" }] },
  // Q111
  { textFr: "Dans quel grand musée parisien est exposée la Joconde ?", lang: 'pt' as const, text: "Em qual grande museu parisiense está exposta a Mona Lisa?", explanation: "A Mona Lisa de Leonardo da Vinci está exposta no Museu do Louvre em Paris. É o quadro mais famoso do mundo e uma das joias da coleção do museu.", choices: [{ id: 'a' as const, text: "O Museu do Louvre" }, { id: 'b' as const, text: "O Museu d'Orsay" }, { id: 'c' as const, text: "O Centro Pompidou" }, { id: 'd' as const, text: "O Museu Rodin" }] },
  // Q112
  { textFr: "Quel château célèbre se trouve près de Paris et symbolise le pouvoir royal de Louis XIV ?", lang: 'pt' as const, text: "Qual castelo famoso se encontra perto de Paris e simboliza o poder real de Luís XIV?", explanation: "O Palácio de Versalhes foi a residência principal dos reis da França de Luís XIV a Luís XVI. Construído no século XVII, ele simboliza o poder da monarquia absoluta.", choices: [{ id: 'a' as const, text: "O Palácio de Versalhes" }, { id: 'b' as const, text: "O Castelo de Chambord" }, { id: 'c' as const, text: "O Castelo de Fontainebleau" }, { id: 'd' as const, text: "O Castelo de Chenonceau" }] },
  // Q113
  { textFr: "Où peut-on voir des peintures préhistoriques en France ?", lang: 'pt' as const, text: "Onde se pode ver pinturas pré-históricas na França?", explanation: "A gruta de Lascaux, na Dordonha, abriga pinturas pré-históricas datando de aproximadamente 17.000 anos. Descoberta em 1940, ela é apelidada de \"Capela Sistina da Pré-História\".", choices: [{ id: 'a' as const, text: "Na gruta de Lascaux" }, { id: 'b' as const, text: "No Palácio de Versalhes" }, { id: 'c' as const, text: "No Museu do Louvre" }, { id: 'd' as const, text: "Na catedral de Chartres" }] },
  // Q114
  { textFr: "Quel peintre célèbre a peint les Nymphéas ?", lang: 'pt' as const, text: "Qual pintor famoso pintou os Nenúfares?", explanation: "Claude Monet pintou a célebre série dos Nenúfares em seu jardim de Giverny. Esses quadros impressionistas, pintados entre 1895 e 1926, estão expostos no Museu da Orangerie em Paris.", choices: [{ id: 'a' as const, text: "Claude Monet" }, { id: 'b' as const, text: "Edgar Degas" }, { id: 'c' as const, text: "Paul Gauguin" }, { id: 'd' as const, text: "Édouard Manet" }] },
  // Q115
  { textFr: "Que symbolise le 1er mai ?", lang: 'pt' as const, text: "O que simboliza o 1º de maio?", explanation: "O 1º de maio é o Dia do Trabalho na França, feriado desde 1947. É um dia de celebração dos direitos dos trabalhadores, tradicionalmente marcado pela oferta de ramos de lírio-do-vale.", choices: [{ id: 'a' as const, text: "O Dia do Trabalho" }, { id: 'b' as const, text: "A festa nacional" }, { id: 'c' as const, text: "A festa da música" }, { id: 'd' as const, text: "A festa da Vitória" }] },
  // Q116
  { textFr: "Qui était Monsieur Rouget de Lisle ?", lang: 'pt' as const, text: "Quem foi o senhor Rouget de Lisle?", explanation: "Claude Joseph Rouget de Lisle (1760-1836) foi um oficial e compositor francês, autor de La Marseillaise em 1792. Esse canto patriótico se tornou o hino nacional francês.", choices: [{ id: 'a' as const, text: "O compositor de La Marseillaise" }, { id: 'b' as const, text: "O fundador da Quinta República" }, { id: 'c' as const, text: "Um general de Napoleão" }, { id: 'd' as const, text: "Um filósofo do Iluminismo" }] },
  // Q117
  { textFr: "À quelle occasion a été construite la tour Eiffel ?", lang: 'pt' as const, text: "Por qual ocasião foi construída a Torre Eiffel?", explanation: "A Torre Eiffel foi construída para a Exposição Universal de 1889, que celebrava o centenário da Revolução Francesa. Projetada por Gustave Eiffel, ela deveria ser desmontada após a exposição.", choices: [{ id: 'a' as const, text: "A Exposição Universal de 1889" }, { id: 'b' as const, text: "Os Jogos Olímpicos de 1900" }, { id: 'c' as const, text: "A vitória de 1918" }, { id: 'd' as const, text: "A coroação de Napoleão" }] },
  // Q118
  { textFr: "Qui était un célèbre compositeur français ?", lang: 'pt' as const, text: "Quem foi um célebre compositor francês?", explanation: "Maurice Ravel (1875-1937) foi um compositor francês, autor do célebre Bolero. Ele é um dos maiores compositores franceses do século XX junto com Claude Debussy.", choices: [{ id: 'a' as const, text: "Maurice Ravel" }, { id: 'b' as const, text: "Giuseppe Verdi" }, { id: 'c' as const, text: "Richard Wagner" }, { id: 'd' as const, text: "Piotr Tchaikovsky" }] },
  // Q119
  { textFr: "Quel monument historique se trouve sur une île en Normandie ?", lang: 'pt' as const, text: "Qual monumento histórico se encontra em uma ilha na Normandia?", explanation: "O Mont-Saint-Michel é uma abadia medieval situada em um ilhéu rochoso na Normandia. É um dos sítios mais visitados da França e está classificado como Patrimônio Mundial da UNESCO.", choices: [{ id: 'a' as const, text: "O Mont-Saint-Michel" }, { id: 'b' as const, text: "O Castelo de Chambord" }, { id: 'c' as const, text: "A Ponte do Gard" }, { id: 'd' as const, text: "A cidadela de Carcassonne" }] },
  // Q120
  { textFr: "Quelle île fait partie des Antilles françaises ?", lang: 'pt' as const, text: "Qual ilha faz parte das Antilhas Francesas?", explanation: "A Guadalupe faz parte das Antilhas Francesas, no mar do Caribe. É um departamento e uma região ultramarina francesa composta por várias ilhas.", choices: [{ id: 'a' as const, text: "A Guadalupe" }, { id: 'b' as const, text: "Cuba" }, { id: 'c' as const, text: "A Jamaica" }, { id: 'd' as const, text: "Porto Rico" }] },
  // Q121
  { textFr: "Quelle île est française ?", lang: 'pt' as const, text: "Qual ilha é francesa?", explanation: "A Nova Caledônia é um território francês situado no oceano Pacífico. É uma coletividade sui generis da França com um estatuto particular dentro da República.", choices: [{ id: 'a' as const, text: "A Nova Caledônia" }, { id: 'b' as const, text: "As Bahamas" }, { id: 'c' as const, text: "As Maldivas" }, { id: 'd' as const, text: "Bornéu" }] },
  // Q122
  { textFr: "Quelle est la plus haute montagne de France ?", lang: 'pt' as const, text: "Qual é a montanha mais alta da França?", explanation: "O Mont Blanc, com 4.809 metros de altitude, é a montanha mais alta da França e da Europa Ocidental. Está situado nos Alpes, na fronteira entre a França e a Itália.", choices: [{ id: 'a' as const, text: "O Mont Blanc" }, { id: 'b' as const, text: "O Puy de Dôme" }, { id: 'c' as const, text: "O Pic du Midi" }, { id: 'd' as const, text: "O Mont Ventoux" }] },
  // Q123
  { textFr: "Quelle île française est située au sud-est du continent africain ?", lang: 'pt' as const, text: "Qual ilha francesa está situada a sudeste do continente africano?", explanation: "Mayotte é uma ilha francesa situada no oceano Índico, a sudeste do continente africano. Ela se tornou o 101º departamento francês em 2011.", choices: [{ id: 'a' as const, text: "Mayotte" }, { id: 'b' as const, text: "A Martinica" }, { id: 'c' as const, text: "A Guadalupe" }, { id: 'd' as const, text: "Saint-Pierre-et-Miquelon" }] },
  // Q124
  { textFr: "Quel département français a une frontière avec le Brésil ?", lang: 'pt' as const, text: "Qual departamento francês tem fronteira com o Brasil?", explanation: "A Guiana Francesa é um departamento ultramarino situado na América do Sul, compartilhando uma fronteira com o Brasil. É o maior departamento francês em superfície.", choices: [{ id: 'a' as const, text: "A Guiana" }, { id: 'b' as const, text: "A Martinica" }, { id: 'c' as const, text: "A Reunião" }, { id: 'd' as const, text: "Mayotte" }] },
  // Q125
  { textFr: "De quelle ville française décolle la fusée Ariane ?", lang: 'pt' as const, text: "De qual cidade francesa decola o foguete Ariane?", explanation: "O foguete Ariane decola de Kourou, na Guiana Francesa. O Centro Espacial Guianês é a base de lançamento da Agência Espacial Europeia (ESA) desde 1968.", choices: [{ id: 'a' as const, text: "Kourou" }, { id: 'b' as const, text: "Toulouse" }, { id: 'c' as const, text: "Bordeaux" }, { id: 'd' as const, text: "Marselha" }] },
  // Q126
  { textFr: "Quel est le principal port maritime de France ?", lang: 'pt' as const, text: "Qual é o principal porto marítimo da França?", explanation: "Marselha é o principal porto marítimo da França e o primeiro porto do Mediterrâneo. O Grande Porto Marítimo de Marselha processa milhões de toneladas de mercadorias a cada ano.", choices: [{ id: 'a' as const, text: "Marselha" }, { id: 'b' as const, text: "Nantes" }, { id: 'c' as const, text: "Brest" }, { id: 'd' as const, text: "Bordeaux" }] },
  // Q127
  { textFr: "Quel est le chef-lieu de la région Auvergne-Rhône-Alpes ?", lang: 'pt' as const, text: "Qual é a capital da região Auvergne-Rhône-Alpes?", explanation: "Lyon é a capital da região Auvergne-Rhône-Alpes. É a terceira maior cidade da França e um importante centro econômico e cultural.", choices: [{ id: 'a' as const, text: "Lyon" }, { id: 'b' as const, text: "Clermont-Ferrand" }, { id: 'c' as const, text: "Grenoble" }, { id: 'd' as const, text: "Saint-Étienne" }] },
  // Q128
  { textFr: "Quel est le chef-lieu de la région Bretagne ?", lang: 'pt' as const, text: "Qual é a capital da região Bretanha?", explanation: "Rennes é a capital da região Bretanha. É uma cidade dinâmica e universitária situada no oeste da França.", choices: [{ id: 'a' as const, text: "Rennes" }, { id: 'b' as const, text: "Brest" }, { id: 'c' as const, text: "Nantes" }, { id: 'd' as const, text: "Quimper" }] },
  // Q129
  { textFr: "Quel est le chef-lieu de la région Provence-Alpes-Côte d'Azur ?", lang: 'pt' as const, text: "Qual é a capital da região Provence-Alpes-Côte d'Azur?", explanation: "Marselha é a capital da região Provence-Alpes-Côte d'Azur (PACA). É a segunda maior cidade da França e um porto importante do Mediterrâneo.", choices: [{ id: 'a' as const, text: "Marselha" }, { id: 'b' as const, text: "Nice" }, { id: 'c' as const, text: "Toulon" }, { id: 'd' as const, text: "Aix-en-Provence" }] },
  // Q130
  { textFr: "Quel est le 101e département français depuis 2011 ?", lang: 'pt' as const, text: "Qual é o 101º departamento francês desde 2011?", explanation: "Mayotte se tornou o 101º departamento francês em 31 de março de 2011, após o referendo de 2009. É o mais recente departamento ultramarino a ter integrado a República Francesa.", choices: [{ id: 'a' as const, text: "Mayotte" }, { id: 'b' as const, text: "A Guiana" }, { id: 'c' as const, text: "A Nova Caledônia" }, { id: 'd' as const, text: "Saint-Martin" }] },
  // Q131
  { textFr: "Quelle région française est réputée pour ses stations de ski ?", lang: 'pt' as const, text: "Qual região francesa é famosa por suas estações de esqui?", explanation: "A região Auvergne-Rhône-Alpes é a mais famosa por suas estações de esqui na França. Ela abriga numerosas estações alpinas renomadas como Chamonix, Les Deux Alpes e Val-d'Isère.", choices: [{ id: 'a' as const, text: "Auvergne-Rhône-Alpes" }, { id: 'b' as const, text: "A Île-de-France" }, { id: 'c' as const, text: "A Nova Aquitânia" }, { id: 'd' as const, text: "A Bretanha" }] },
];
