export const theme2Es = [
  // Q1
  { textFr: "Qui nomme le Premier ministre ?", lang: 'es' as const, text: "¿Quién nombra al Primer Ministro?", explanation: "El Primer Ministro es nombrado por el Presidente de la República. Es una prerrogativa constitucional definida por el artículo 8 de la Constitución de 1958.", choices: [{ id: 'a' as const, text: "El Presidente de la República" }, { id: 'b' as const, text: "La Asamblea Nacional" }, { id: 'c' as const, text: "El Senado" }, { id: 'd' as const, text: "El Consejo Constitucional" }] },
  // Q2
  { textFr: "Le Parlement est composé :", lang: 'es' as const, text: "El Parlamento está compuesto por:", explanation: "El Parlamento francés es bicameral. Está compuesto por la Asamblea Nacional y el Senado, que votan las leyes y controlan la acción del Gobierno.", choices: [{ id: 'a' as const, text: "La Asamblea Nacional y el Senado" }, { id: 'b' as const, text: "El Senado y el Consejo Constitucional" }, { id: 'c' as const, text: "La Asamblea Nacional y el Gobierno" }, { id: 'd' as const, text: "El Consejo de Estado y la Asamblea Nacional" }] },
  // Q3
  { textFr: "Qu'est-ce que le pouvoir exécutif ? Le pouvoir :", lang: 'es' as const, text: "¿Qué es el poder ejecutivo? El poder:", explanation: "El poder ejecutivo es el poder de hacer cumplir las leyes. En Francia, lo ejercen el Presidente de la República y el Gobierno.", choices: [{ id: 'a' as const, text: "De hacer cumplir las leyes" }, { id: 'b' as const, text: "De votar las leyes" }, { id: 'c' as const, text: "De juzgar las infracciones" }, { id: 'd' as const, text: "De modificar la Constitución" }] },
  // Q4
  { textFr: "Les dirigeants sont élus par les citoyens dans :", lang: 'es' as const, text: "Los dirigentes son elegidos por los ciudadanos en:", explanation: "En una democracia, los dirigentes son elegidos por los ciudadanos en elecciones libres. Es el principio fundamental del régimen democrático.", choices: [{ id: 'a' as const, text: "Una democracia" }, { id: 'b' as const, text: "Una dictadura" }, { id: 'c' as const, text: "Una monarquía absoluta" }, { id: 'd' as const, text: "Una oligarquía" }] },
  // Q5
  { textFr: "A-t-on le droit de ne pas respecter une loi ?", lang: 'es' as const, text: "¿Se tiene derecho a no respetar una ley?", explanation: "No, nadie tiene derecho a no respetar la ley. La ley se aplica a todos de manera igualitaria. Nadie puede alegar ignorancia de la ley.", choices: [{ id: 'a' as const, text: "No, nunca" }, { id: 'b' as const, text: "Sí, si no se está de acuerdo con la ley" }, { id: 'c' as const, text: "Sí, si se es extranjero" }, { id: 'd' as const, text: "Sí, en ciertas circunstancias personales" }] },
  // Q6
  { textFr: "Qui doit respecter la loi ?", lang: 'es' as const, text: "¿Quién debe respetar la ley?", explanation: "Todos deben respetar la ley en Francia, sin excepción. Este principio se aplica a los ciudadanos, los extranjeros, los electos y los dirigentes.", choices: [{ id: 'a' as const, text: "Todo el mundo" }, { id: 'b' as const, text: "Solo los ciudadanos franceses" }, { id: 'c' as const, text: "Solo los adultos" }, { id: 'd' as const, text: "Solo las personas que viven en Francia" }] },
  // Q7
  { textFr: "Quel est le rôle de l'autorité judiciaire ?", lang: 'es' as const, text: "¿Cuál es el papel de la autoridad judicial?", explanation: "La autoridad judicial tiene el papel de velar por el cumplimiento de las leyes y sancionar su incumplimiento. Protege las libertades individuales.", choices: [{ id: 'a' as const, text: "Velar por el cumplimiento de las leyes y sancionar su incumplimiento" }, { id: 'b' as const, text: "Votar las leyes" }, { id: 'c' as const, text: "Proponer nuevas leyes" }, { id: 'd' as const, text: "Nombrar a los ministros" }] },
  // Q8
  { textFr: "Quel pouvoir détient un juge ? Le pouvoir :", lang: 'es' as const, text: "¿Qué poder tiene un juez? El poder:", explanation: "El juez tiene el poder judicial. Imparte justicia aplicando las leyes y sancionando las infracciones.", choices: [{ id: 'a' as const, text: "Judicial" }, { id: 'b' as const, text: "Ejecutivo" }, { id: 'c' as const, text: "Legislativo" }, { id: 'd' as const, text: "Administrativo" }] },
  // Q9
  { textFr: "L'autorité judiciaire est exercée par :", lang: 'es' as const, text: "La autoridad judicial es ejercida por:", explanation: "La autoridad judicial es ejercida por los magistrados y los jueces. Son independientes del poder ejecutivo y del poder legislativo.", choices: [{ id: 'a' as const, text: "Los magistrados y los jueces" }, { id: 'b' as const, text: "Los diputados" }, { id: 'c' as const, text: "Los ministros" }, { id: 'd' as const, text: "Los prefectos" }] },
  // Q10
  { textFr: "Que se passe-t-il si un ministre ne respecte pas la loi ?", lang: 'es' as const, text: "¿Qué sucede si un ministro no respeta la ley?", explanation: "Un ministro que no respeta la ley puede ser juzgado como cualquier ciudadano. Nadie está por encima de las leyes, incluidos los miembros del Gobierno.", choices: [{ id: 'a' as const, text: "Puede ser juzgado como cualquier ciudadano" }, { id: 'b' as const, text: "No puede ser juzgado porque es ministro" }, { id: 'c' as const, text: "Solo es destituido del Gobierno" }, { id: 'd' as const, text: "Está protegido por la inmunidad ministerial de por vida" }] },
  // Q11
  { textFr: "Qui est élu lors des élections législatives ?", lang: 'es' as const, text: "¿Quién es elegido en las elecciones legislativas?", explanation: "Los diputados son elegidos en las elecciones legislativas. Ocupan su escaño en la Asamblea Nacional y votan las leyes.", choices: [{ id: 'a' as const, text: "Los diputados" }, { id: 'b' as const, text: "Los senadores" }, { id: 'c' as const, text: "Los alcaldes" }, { id: 'd' as const, text: "Los consejeros regionales" }] },
  // Q12
  { textFr: "Combien de députés composent l'Assemblée nationale ?", lang: 'es' as const, text: "¿Cuántos diputados componen la Asamblea Nacional?", explanation: "La Asamblea Nacional está compuesta por 577 diputados. Son elegidos por sufragio universal directo para un mandato de 5 años.", choices: [{ id: 'a' as const, text: "577" }, { id: 'b' as const, text: "348" }, { id: 'c' as const, text: "500" }, { id: 'd' as const, text: "650" }] },
  // Q13
  { textFr: "Quand sont élus les sénateurs ?", lang: 'es' as const, text: "¿Cuándo son elegidos los senadores?", explanation: "Los senadores son elegidos por sufragio universal indirecto por los grandes electores. El Senado se renueva por mitades cada 3 años.", choices: [{ id: 'a' as const, text: "Son elegidos por sufragio universal indirecto" }, { id: 'b' as const, text: "Son elegidos por sufragio universal directo" }, { id: 'c' as const, text: "Son nombrados por el Presidente de la República" }, { id: 'd' as const, text: "Son designados por los diputados" }] },
  // Q14
  { textFr: "Qui est élu lors des élections municipales ?", lang: 'es' as const, text: "¿Quién es elegido en las elecciones municipales?", explanation: "Los concejales municipales son elegidos en las elecciones municipales. Luego eligen al alcalde entre ellos.", choices: [{ id: 'a' as const, text: "Los concejales municipales" }, { id: 'b' as const, text: "El alcalde directamente" }, { id: 'c' as const, text: "Los consejeros departamentales" }, { id: 'd' as const, text: "Los diputados" }] },
  // Q15
  { textFr: "Qui est élu lors des élections présidentielles ?", lang: 'es' as const, text: "¿Quién es elegido en las elecciones presidenciales?", explanation: "El Presidente de la República es elegido en las elecciones presidenciales, por sufragio universal directo desde 1962.", choices: [{ id: 'a' as const, text: "El Presidente de la República" }, { id: 'b' as const, text: "El Primer Ministro" }, { id: 'c' as const, text: "Los diputados" }, { id: 'd' as const, text: "Los senadores" }] },
  // Q16
  { textFr: "À partir de quel âge a-t-on le droit de voter ?", lang: 'es' as const, text: "¿A partir de qué edad se tiene derecho a votar?", explanation: "En Francia, el derecho al voto se concede a partir de los 18 años. Es la edad de la mayoría civil y política.", choices: [{ id: 'a' as const, text: "18 años" }, { id: 'b' as const, text: "16 años" }, { id: 'c' as const, text: "21 años" }, { id: 'd' as const, text: "25 años" }] },
  // Q17
  { textFr: "Pour combien de temps est élu le président de la République française ?", lang: 'es' as const, text: "¿Por cuánto tiempo es elegido el Presidente de la República francesa?", explanation: "El Presidente de la República es elegido para un mandato de 5 años (quinquenio) desde la reforma constitucional de 2000.", choices: [{ id: 'a' as const, text: "5 años" }, { id: 'b' as const, text: "7 años" }, { id: 'c' as const, text: "4 años" }, { id: 'd' as const, text: "6 años" }] },
  // Q18
  { textFr: "Pour combien de temps sont élus les députés ?", lang: 'es' as const, text: "¿Por cuánto tiempo son elegidos los diputados?", explanation: "Los diputados son elegidos para un mandato de 5 años. La Asamblea Nacional puede ser disuelta antes del fin del mandato por el Presidente de la República.", choices: [{ id: 'a' as const, text: "5 años" }, { id: 'b' as const, text: "6 años" }, { id: 'c' as const, text: "4 años" }, { id: 'd' as const, text: "7 años" }] },
  // Q19
  { textFr: "Pour combien de temps sont élus les sénateurs ?", lang: 'es' as const, text: "¿Por cuánto tiempo son elegidos los senadores?", explanation: "Los senadores son elegidos para un mandato de 6 años. El Senado se renueva por mitades cada 3 años.", choices: [{ id: 'a' as const, text: "6 años" }, { id: 'b' as const, text: "5 años" }, { id: 'c' as const, text: "4 años" }, { id: 'd' as const, text: "7 años" }] },
  // Q20
  { textFr: "Qui possède le pouvoir exécutif ?", lang: 'es' as const, text: "¿Quién posee el poder ejecutivo?", explanation: "El poder ejecutivo lo ostentan el Presidente de la República y el Gobierno. Hacen cumplir las leyes votadas por el Parlamento.", choices: [{ id: 'a' as const, text: "El Presidente de la República y el Gobierno" }, { id: 'b' as const, text: "El Parlamento" }, { id: 'c' as const, text: "Los jueces" }, { id: 'd' as const, text: "El Consejo Constitucional" }] },
  // Q21
  { textFr: "Quelle condition est nécessaire pour voter aux élections ?", lang: 'es' as const, text: "¿Qué condición es necesaria para votar en las elecciones?", explanation: "Para votar en las elecciones en Francia, hay que estar inscrito en las listas electorales. La inscripción es una condición previa indispensable.", choices: [{ id: 'a' as const, text: "Estar inscrito en las listas electorales" }, { id: 'b' as const, text: "Tener un empleo en Francia" }, { id: 'c' as const, text: "Poseer un bien inmueble" }, { id: 'd' as const, text: "Tener un diploma francés" }] },
  // Q22
  { textFr: "Qui peut voter aux élections en France ?", lang: 'es' as const, text: "¿Quién puede votar en las elecciones en Francia?", explanation: "Los ciudadanos franceses mayores de edad (18 años y más) que gocen de sus derechos civiles y políticos pueden votar en las elecciones en Francia.", choices: [{ id: 'a' as const, text: "Los ciudadanos franceses mayores de edad" }, { id: 'b' as const, text: "Toda persona que resida en Francia" }, { id: 'c' as const, text: "Las personas que tengan un permiso de residencia" }, { id: 'd' as const, text: "Las personas mayores de 21 años" }] },
  // Q23
  { textFr: "Que signifie « suffrage universel » ?", lang: 'es' as const, text: "¿Qué significa «sufragio universal»?", explanation: "El sufragio universal significa que todos los ciudadanos mayores de edad tienen derecho a votar, sin distinción de sexo, riqueza u origen.", choices: [{ id: 'a' as const, text: "Todos los ciudadanos mayores de edad tienen derecho a votar" }, { id: 'b' as const, text: "Solo los hombres tienen derecho a votar" }, { id: 'c' as const, text: "El voto es obligatorio para todos" }, { id: 'd' as const, text: "Solo los propietarios pueden votar" }] },
  // Q24
  { textFr: "Concernant les partis politiques, quelle proposition est correcte ?", lang: 'es' as const, text: "Respecto a los partidos políticos, ¿qué proposición es correcta?", explanation: "En Francia, existen varios partidos políticos y se puede adherir libremente al partido de su elección. El multipartidismo es un principio fundamental de la democracia.", choices: [{ id: 'a' as const, text: "Existen varios partidos políticos y se puede adherir al partido de su elección" }, { id: 'b' as const, text: "Solo existe un partido político en Francia" }, { id: 'c' as const, text: "Los partidos políticos están prohibidos" }, { id: 'd' as const, text: "Solo los funcionarios pueden adherirse a un partido" }] },
  // Q25
  { textFr: "Quel est le rôle des députés ?", lang: 'es' as const, text: "¿Cuál es el papel de los diputados?", explanation: "Los diputados votan las leyes y controlan la acción del Gobierno. Representan al pueblo en la Asamblea Nacional.", choices: [{ id: 'a' as const, text: "Votar las leyes y controlar la acción del Gobierno" }, { id: 'b' as const, text: "Dirigir el Gobierno" }, { id: 'c' as const, text: "Nombrar a los jueces" }, { id: 'd' as const, text: "Gestionar los municipios" }] },
  // Q26
  { textFr: "La séparation des pouvoirs est un principe fondamental. Quels sont les trois pouvoirs concernés ?", lang: 'es' as const, text: "La separación de poderes es un principio fundamental. ¿Cuáles son los tres poderes involucrados?", explanation: "Los tres poderes son: el poder legislativo (hacer las leyes), el poder ejecutivo (aplicar las leyes) y el poder judicial (juzgar). Este principio garantiza la democracia.", choices: [{ id: 'a' as const, text: "Legislativo, ejecutivo, judicial" }, { id: 'b' as const, text: "Presidencial, parlamentario, judicial" }, { id: 'c' as const, text: "Municipal, departamental, regional" }, { id: 'd' as const, text: "Militar, civil, religioso" }] },
  // Q27
  { textFr: "Qui possède le pouvoir législatif ?", lang: 'es' as const, text: "¿Quién posee el poder legislativo?", explanation: "El poder legislativo lo ostenta el Parlamento, compuesto por la Asamblea Nacional y el Senado. Vota las leyes.", choices: [{ id: 'a' as const, text: "El Parlamento (Asamblea Nacional y Senado)" }, { id: 'b' as const, text: "El Presidente de la República" }, { id: 'c' as const, text: "El Gobierno" }, { id: 'd' as const, text: "Los jueces" }] },
  // Q28
  { textFr: "Qui sanctionne l'auteur d'un vol ?", lang: 'es' as const, text: "¿Quién sanciona al autor de un robo?", explanation: "Es la justicia (un juez) quien sanciona al autor de un robo. El poder judicial es el único competente para pronunciar sanciones penales.", choices: [{ id: 'a' as const, text: "La justicia (un juez)" }, { id: 'b' as const, text: "La policía" }, { id: 'c' as const, text: "El alcalde" }, { id: 'd' as const, text: "La propia víctima" }] },
  // Q29
  { textFr: "Qui élit les députés ?", lang: 'es' as const, text: "¿Quién elige a los diputados?", explanation: "Los diputados son elegidos por los ciudadanos franceses por sufragio universal directo. Cada diputado representa una circunscripción.", choices: [{ id: 'a' as const, text: "Los ciudadanos franceses por sufragio universal directo" }, { id: 'b' as const, text: "Los senadores" }, { id: 'c' as const, text: "El Presidente de la República" }, { id: 'd' as const, text: "Los grandes electores" }] },
  // Q30
  { textFr: "Qui vote les lois ?", lang: 'es' as const, text: "¿Quién vota las leyes?", explanation: "El Parlamento (Asamblea Nacional y Senado) vota las leyes. Es la función principal del poder legislativo.", choices: [{ id: 'a' as const, text: "El Parlamento (Asamblea Nacional y Senado)" }, { id: 'b' as const, text: "El Presidente de la República" }, { id: 'c' as const, text: "El Gobierno" }, { id: 'd' as const, text: "El Consejo Constitucional" }] },
  // Q31
  { textFr: "Qui réside au palais de l'Élysée ?", lang: 'es' as const, text: "¿Quién reside en el palacio del Elíseo?", explanation: "El palacio del Elíseo es la residencia oficial del Presidente de la República francesa, situado en París.", choices: [{ id: 'a' as const, text: "El Presidente de la República" }, { id: 'b' as const, text: "El Primer Ministro" }, { id: 'c' as const, text: "El presidente de la Asamblea Nacional" }, { id: 'd' as const, text: "El presidente del Senado" }] },
  // Q32
  { textFr: "Combien y a-t-il de départements en France ?", lang: 'es' as const, text: "¿Cuántos departamentos hay en Francia?", explanation: "Francia tiene 101 departamentos: 96 departamentos metropolitanos y 5 departamentos de ultramar (Guadalupe, Martinica, Guayana, La Reunión, Mayotte).", choices: [{ id: 'a' as const, text: "101" }, { id: 'b' as const, text: "96" }, { id: 'c' as const, text: "95" }, { id: 'd' as const, text: "110" }] },
  // Q33
  { textFr: "Qui représente l'État dans un département ?", lang: 'es' as const, text: "¿Quién representa al Estado en un departamento?", explanation: "El prefecto representa al Estado en el departamento. Es nombrado por el Presidente de la República y vela por la aplicación de las leyes.", choices: [{ id: 'a' as const, text: "El prefecto" }, { id: 'b' as const, text: "El alcalde" }, { id: 'c' as const, text: "El diputado" }, { id: 'd' as const, text: "El senador" }] },
  // Q34
  { textFr: "Qui dirige la commune ?", lang: 'es' as const, text: "¿Quién dirige el municipio?", explanation: "El alcalde dirige el municipio. Es elegido por los concejales municipales y ejerce funciones tanto en nombre del municipio como en nombre del Estado.", choices: [{ id: 'a' as const, text: "El alcalde" }, { id: 'b' as const, text: "El prefecto" }, { id: 'c' as const, text: "El diputado" }, { id: 'd' as const, text: "El presidente del consejo departamental" }] },
  // Q35
  { textFr: "Est-ce que le président de la République a tous les pouvoirs ?", lang: 'es' as const, text: "¿Tiene el Presidente de la República todos los poderes?", explanation: "No, el Presidente de la República no tiene todos los poderes. La separación de poderes (legislativo, ejecutivo, judicial) garantiza que ninguna persona posea todos los poderes.", choices: [{ id: 'a' as const, text: "No, los poderes están separados" }, { id: 'b' as const, text: "Sí, tiene todos los poderes" }, { id: 'c' as const, text: "Sí, excepto el poder judicial" }, { id: 'd' as const, text: "Sí, en período de crisis" }] },
  // Q36
  { textFr: "Qui est le préfet ?", lang: 'es' as const, text: "¿Quién es el prefecto?", explanation: "El prefecto es el representante del Estado en el departamento. Es nombrado por el Presidente de la República en Consejo de Ministros.", choices: [{ id: 'a' as const, text: "El representante del Estado en el departamento" }, { id: 'b' as const, text: "El jefe de la policía municipal" }, { id: 'c' as const, text: "Un cargo electo local" }, { id: 'd' as const, text: "El director del hospital público" }] },
  // Q37
  { textFr: "Quel est le rôle du Parlement ?", lang: 'es' as const, text: "¿Cuál es el papel del Parlamento?", explanation: "El Parlamento vota las leyes y controla la acción del Gobierno. Ejerce el poder legislativo en Francia.", choices: [{ id: 'a' as const, text: "Votar las leyes y controlar la acción del Gobierno" }, { id: 'b' as const, text: "Dirigir el ejército" }, { id: 'c' as const, text: "Nombrar a los jueces" }, { id: 'd' as const, text: "Gestionar los impuestos locales" }] },
  // Q38
  { textFr: "Quel est le régime politique de la France aujourd'hui ?", lang: 'es' as const, text: "¿Cuál es el régimen político de Francia hoy en día?", explanation: "Francia es una república democrática. Su régimen es una democracia representativa donde los ciudadanos eligen a sus representantes.", choices: [{ id: 'a' as const, text: "Una república democrática" }, { id: 'b' as const, text: "Una monarquía constitucional" }, { id: 'c' as const, text: "Una dictadura" }, { id: 'd' as const, text: "Un imperio" }] },
  // Q39
  { textFr: "Combien d'États font partie de l'Union européenne au 1er janvier 2025 ?", lang: 'es' as const, text: "¿Cuántos Estados forman parte de la Unión Europea a 1 de enero de 2025?", explanation: "La Unión Europea cuenta con 27 Estados miembros a 1 de enero de 2025, desde la salida del Reino Unido en 2020.", choices: [{ id: 'a' as const, text: "27" }, { id: 'b' as const, text: "28" }, { id: 'c' as const, text: "25" }, { id: 'd' as const, text: "30" }] },
  // Q40
  { textFr: "Quel État n'est pas membre de l'Union européenne ?", lang: 'es' as const, text: "¿Qué Estado no es miembro de la Unión Europea?", explanation: "Suiza no es miembro de la Unión Europea. Ha elegido permanecer fuera de la UE manteniendo acuerdos bilaterales.", choices: [{ id: 'a' as const, text: "Suiza" }, { id: 'b' as const, text: "Alemania" }, { id: 'c' as const, text: "Italia" }, { id: 'd' as const, text: "España" }] },
  // Q41
  { textFr: "Quelle condition est nécessaire pour voter aux élections européennes ?", lang: 'es' as const, text: "¿Qué condición es necesaria para votar en las elecciones europeas?", explanation: "Para votar en las elecciones europeas, hay que ser ciudadano de un Estado miembro de la Unión Europea y estar inscrito en las listas electorales.", choices: [{ id: 'a' as const, text: "Ser ciudadano de un Estado miembro de la Unión Europea" }, { id: 'b' as const, text: "Ser ciudadano francés únicamente" }, { id: 'c' as const, text: "Residir en Francia desde hace más de 10 años" }, { id: 'd' as const, text: "Tener más de 21 años" }] },
  // Q42
  { textFr: "À quelle fréquence les élections européennes sont-elles organisées ?", lang: 'es' as const, text: "¿Con qué frecuencia se organizan las elecciones europeas?", explanation: "Las elecciones europeas se organizan cada 5 años. Los ciudadanos de la UE eligen a los eurodiputados que ocupan su escaño en el Parlamento Europeo.", choices: [{ id: 'a' as const, text: "Cada 5 años" }, { id: 'b' as const, text: "Cada 4 años" }, { id: 'c' as const, text: "Cada 6 años" }, { id: 'd' as const, text: "Cada 3 años" }] },
  // Q43
  { textFr: "Quel pays est un pays fondateur de l'Union européenne ?", lang: 'es' as const, text: "¿Qué país es un país fundador de la Unión Europea?", explanation: "Francia es uno de los seis países fundadores de la construcción europea (junto con Alemania, Italia, Bélgica, los Países Bajos y Luxemburgo), firmantes del Tratado de Roma en 1957.", choices: [{ id: 'a' as const, text: "Francia" }, { id: 'b' as const, text: "España" }, { id: 'c' as const, text: "El Reino Unido" }, { id: 'd' as const, text: "Polonia" }] },
  // Q44
  { textFr: "Quelle est la monnaie utilisée en France ?", lang: 'es' as const, text: "¿Cuál es la moneda utilizada en Francia?", explanation: "El euro es la moneda utilizada en Francia desde el 1 de enero de 2002. Es la moneda común a numerosos países de la Unión Europea.", choices: [{ id: 'a' as const, text: "El euro" }, { id: 'b' as const, text: "El franco" }, { id: 'c' as const, text: "La libra" }, { id: 'd' as const, text: "El dólar" }] },
  // Q45
  { textFr: "Qui élit les députés européens ?", lang: 'es' as const, text: "¿Quién elige a los eurodiputados?", explanation: "Los eurodiputados son elegidos por los ciudadanos de los Estados miembros de la Unión Europea por sufragio universal directo.", choices: [{ id: 'a' as const, text: "Los ciudadanos de los Estados miembros de la Unión Europea" }, { id: 'b' as const, text: "Los jefes de Estado de los países miembros" }, { id: 'c' as const, text: "La Comisión Europea" }, { id: 'd' as const, text: "Los parlamentos nacionales" }] },
  // Q46
  { textFr: "Quand célèbre-t-on la journée de l'Europe ?", lang: 'es' as const, text: "¿Cuándo se celebra el Día de Europa?", explanation: "El Día de Europa se celebra el 9 de mayo. Conmemora la declaración de Robert Schuman del 9 de mayo de 1950, considerada como el acto fundacional de la construcción europea.", choices: [{ id: 'a' as const, text: "El 9 de mayo" }, { id: 'b' as const, text: "El 14 de julio" }, { id: 'c' as const, text: "El 1 de enero" }, { id: 'd' as const, text: "El 25 de marzo" }] },
  // Q47
  { textFr: "Qu'est-ce que l'État de droit ?", lang: 'es' as const, text: "¿Qué es el Estado de derecho?", explanation: "El Estado de derecho es un sistema en el que los poderes públicos están sometidos al respeto del derecho. Toda persona, incluido el Estado, debe respetar las leyes.", choices: [{ id: 'a' as const, text: "Un Estado en el que los poderes públicos están sometidos al respeto del derecho" }, { id: 'b' as const, text: "Un Estado donde solo el presidente decide las leyes" }, { id: 'c' as const, text: "Un Estado sin Constitución" }, { id: 'd' as const, text: "Un Estado donde los jueces hacen las leyes" }] },
  // Q48
  { textFr: "Le président de la République a commis un crime. Quelle proposition est correcte ?", lang: 'es' as const, text: "El Presidente de la República ha cometido un crimen. ¿Qué proposición es correcta?", explanation: "El Presidente de la República puede ser juzgado después del fin de su mandato. Durante su mandato, goza de una inmunidad temporal, pero no está por encima de las leyes.", choices: [{ id: 'a' as const, text: "Puede ser juzgado después del fin de su mandato" }, { id: 'b' as const, text: "No puede ser juzgado nunca" }, { id: 'c' as const, text: "Es arrestado inmediatamente" }, { id: 'd' as const, text: "Es juzgado solo por el Parlamento" }] },
  // Q49
  { textFr: "La loi est l'expression de :", lang: 'es' as const, text: "La ley es la expresión de:", explanation: "La ley es la expresión de la voluntad general, como lo enuncia el artículo 6 de la Declaración de los Derechos del Hombre y del Ciudadano de 1789.", choices: [{ id: 'a' as const, text: "La voluntad general" }, { id: 'b' as const, text: "La voluntad del presidente" }, { id: 'c' as const, text: "La voluntad de los jueces" }, { id: 'd' as const, text: "La voluntad del Gobierno" }] },
  // Q50
  { textFr: "Quelle est la durée du mandat du conseil municipal et du maire ?", lang: 'es' as const, text: "¿Cuál es la duración del mandato del consejo municipal y del alcalde?", explanation: "El consejo municipal y el alcalde son elegidos para un mandato de 6 años. Las elecciones municipales se celebran cada 6 años.", choices: [{ id: 'a' as const, text: "6 años" }, { id: 'b' as const, text: "5 años" }, { id: 'c' as const, text: "4 años" }, { id: 'd' as const, text: "7 años" }] },
  // Q51
  { textFr: "Que garantit l'État de droit ?", lang: 'es' as const, text: "¿Qué garantiza el Estado de derecho?", explanation: "El Estado de derecho garantiza el respeto de los derechos fundamentales y de las libertades individuales. Asegura que nadie, ni siquiera el Estado, esté por encima de las leyes.", choices: [{ id: 'a' as const, text: "El respeto de los derechos fundamentales y de las libertades individuales" }, { id: 'b' as const, text: "Un empleo para todos los ciudadanos" }, { id: 'c' as const, text: "La gratuidad de todos los servicios públicos" }, { id: 'd' as const, text: "La ausencia total de impuestos" }] },
  // Q52
  { textFr: "Une personne peut-elle voter à la place d'une autre ?", lang: 'es' as const, text: "¿Puede una persona votar en lugar de otra?", explanation: "Sí, es posible votar por delegación. Un elector impedido puede otorgar un poder a otro elector inscrito en el mismo municipio para votar en su lugar.", choices: [{ id: 'a' as const, text: "Sí, por delegación de voto" }, { id: 'b' as const, text: "No, nunca" }, { id: 'c' as const, text: "Sí, sin ninguna formalidad" }, { id: 'd' as const, text: "Sí, únicamente para los miembros de su familia" }] },
  // Q53
  { textFr: "Est-ce que le vote est obligatoire ?", lang: 'es' as const, text: "¿Es obligatorio el voto?", explanation: "No, el voto no es obligatorio en Francia. Es un derecho y no una obligación legal, pero es un deber cívico.", choices: [{ id: 'a' as const, text: "No, no es obligatorio pero es un deber cívico" }, { id: 'b' as const, text: "Sí, es obligatorio para todos" }, { id: 'c' as const, text: "Sí, bajo pena de multa" }, { id: 'd' as const, text: "Sí, excepto para las personas mayores" }] },
  // Q54
  { textFr: "À la fin de son mandat, le président de la République peut-il décider de rester au pouvoir ?", lang: 'es' as const, text: "Al final de su mandato, ¿puede el Presidente de la República decidir permanecer en el poder?", explanation: "No, el presidente no puede decidir permanecer en el poder al final de su mandato. Debe presentarse de nuevo a las elecciones o dejar sus funciones. Es un principio fundamental de la democracia.", choices: [{ id: 'a' as const, text: "No, debe presentarse de nuevo a las elecciones o dejar sus funciones" }, { id: 'b' as const, text: "Sí, si lo decide" }, { id: 'c' as const, text: "Sí, con el acuerdo del Parlamento" }, { id: 'd' as const, text: "Sí, en caso de crisis nacional" }] },
  // Q55
  { textFr: "Qui dirige l'action du Gouvernement ?", lang: 'es' as const, text: "¿Quién dirige la acción del Gobierno?", explanation: "El Primer Ministro dirige la acción del Gobierno, conforme al artículo 21 de la Constitución. Coordina la acción de los ministros.", choices: [{ id: 'a' as const, text: "El Primer Ministro" }, { id: 'b' as const, text: "El Presidente de la República" }, { id: 'c' as const, text: "El presidente de la Asamblea Nacional" }, { id: 'd' as const, text: "El Ministro del Interior" }] },
  // Q56
  { textFr: "Quelle est l'organisation administrative de la France ?", lang: 'es' as const, text: "¿Cuál es la organización administrativa de Francia?", explanation: "Francia está organizada en municipios, departamentos y regiones. Son los tres niveles de colectividades territoriales previstos por la Constitución.", choices: [{ id: 'a' as const, text: "Municipios, departamentos y regiones" }, { id: 'b' as const, text: "Provincias, cantones y distritos" }, { id: 'c' as const, text: "Ciudades, condados y estados" }, { id: 'd' as const, text: "Distritos, prefecturas y metrópolis" }] },
  // Q57
  { textFr: "Qu'est-ce que le pouvoir législatif ? Le pouvoir :", lang: 'es' as const, text: "¿Qué es el poder legislativo? El poder:", explanation: "El poder legislativo es el poder de hacer las leyes. En Francia, lo ejerce el Parlamento (Asamblea Nacional y Senado).", choices: [{ id: 'a' as const, text: "De hacer las leyes" }, { id: 'b' as const, text: "De hacer cumplir las leyes" }, { id: 'c' as const, text: "De juzgar las infracciones" }, { id: 'd' as const, text: "De nombrar a los ministros" }] },
  // Q58
  { textFr: "Pourquoi séparer les trois pouvoirs dans une démocratie ?", lang: 'es' as const, text: "¿Por qué separar los tres poderes en una democracia?", explanation: "La separación de poderes permite evitar que una sola persona o institución concentre todos los poderes. Es una garantía contra el abuso de poder y la tiranía.", choices: [{ id: 'a' as const, text: "Para evitar la concentración de poderes y proteger las libertades" }, { id: 'b' as const, text: "Para crear más empleos públicos" }, { id: 'c' as const, text: "Para que las decisiones sean más lentas" }, { id: 'd' as const, text: "Para aumentar el número de elecciones" }] },
  // Q59
  { textFr: "Quel est le rôle du gouvernement ?", lang: 'es' as const, text: "¿Cuál es el papel del gobierno?", explanation: "El Gobierno determina y conduce la política de la nación. Dispone de la administración y de la fuerza armada (artículo 20 de la Constitución).", choices: [{ id: 'a' as const, text: "Determinar y conducir la política de la nación" }, { id: 'b' as const, text: "Votar las leyes" }, { id: 'c' as const, text: "Juzgar a los criminales" }, { id: 'd' as const, text: "Elegir al Presidente de la República" }] },
  // Q60
  { textFr: "Qu'est-ce que l'Hôtel de Matignon ?", lang: 'es' as const, text: "¿Qué es el Hotel de Matignon?", explanation: "El Hotel de Matignon es la residencia oficial y el lugar de trabajo del Primer Ministro, situado en París en el distrito 7.", choices: [{ id: 'a' as const, text: "La residencia oficial del Primer Ministro" }, { id: 'b' as const, text: "La residencia del Presidente de la República" }, { id: 'c' as const, text: "La sede de la Asamblea Nacional" }, { id: 'd' as const, text: "La sede del Consejo Constitucional" }] },
  // Q61
  { textFr: "Quel est le rôle du président de la République ?", lang: 'es' as const, text: "¿Cuál es el papel del Presidente de la República?", explanation: "El Presidente de la República vela por el respeto de la Constitución, asegura el funcionamiento de los poderes públicos y la continuidad del Estado. Es el garante de la independencia nacional.", choices: [{ id: 'a' as const, text: "Velar por el respeto de la Constitución y garantizar la independencia nacional" }, { id: 'b' as const, text: "Votar las leyes en el Parlamento" }, { id: 'c' as const, text: "Dirigir los tribunales" }, { id: 'd' as const, text: "Gestionar los municipios" }] },
  // Q62
  { textFr: "Quel est le rôle du Premier ministre ?", lang: 'es' as const, text: "¿Cuál es el papel del Primer Ministro?", explanation: "El Primer Ministro dirige la acción del Gobierno. Es responsable ante la Asamblea Nacional y asegura la ejecución de las leyes.", choices: [{ id: 'a' as const, text: "Dirigir la acción del Gobierno" }, { id: 'b' as const, text: "Presidir el Consejo Constitucional" }, { id: 'c' as const, text: "Votar las leyes" }, { id: 'd' as const, text: "Comandar los ejércitos" }] },
  // Q63
  { textFr: "Qui est le chef du Gouvernement ?", lang: 'es' as const, text: "¿Quién es el jefe del Gobierno?", explanation: "El Primer Ministro es el jefe del Gobierno. Dirige la acción del Gobierno y coordina el trabajo de los ministros.", choices: [{ id: 'a' as const, text: "El Primer Ministro" }, { id: 'b' as const, text: "El Presidente de la República" }, { id: 'c' as const, text: "El presidente de la Asamblea Nacional" }, { id: 'd' as const, text: "El Ministro del Interior" }] },
  // Q64
  { textFr: "Combien y a-t-il de régions en France ?", lang: 'es' as const, text: "¿Cuántas regiones hay en Francia?", explanation: "Francia tiene 18 regiones: 13 regiones metropolitanas (incluida Córcega) y 5 regiones de ultramar.", choices: [{ id: 'a' as const, text: "18" }, { id: 'b' as const, text: "13" }, { id: 'c' as const, text: "22" }, { id: 'd' as const, text: "15" }] },
  // Q65
  { textFr: "Quel est le rôle du Défenseur des droits ?", lang: 'es' as const, text: "¿Cuál es el papel del Defensor de los Derechos?", explanation: "El Defensor de los Derechos es una autoridad independiente encargada de velar por el respeto de los derechos y libertades. Puede ser contactado por toda persona que se considere perjudicada por un servicio público.", choices: [{ id: 'a' as const, text: "Velar por el respeto de los derechos y libertades de los ciudadanos" }, { id: 'b' as const, text: "Votar las leyes" }, { id: 'c' as const, text: "Comandar el ejército" }, { id: 'd' as const, text: "Gestionar el presupuesto del Estado" }] },
  // Q66
  { textFr: "Depuis quand l'euro est-il la monnaie unique ?", lang: 'es' as const, text: "¿Desde cuándo es el euro la moneda única?", explanation: "El euro se convirtió en la moneda única en circulación el 1 de enero de 2002. Había sido introducido como moneda escritural en 1999.", choices: [{ id: 'a' as const, text: "El 1 de enero de 2002" }, { id: 'b' as const, text: "El 1 de enero de 1999" }, { id: 'c' as const, text: "El 1 de enero de 1992" }, { id: 'd' as const, text: "El 1 de enero de 2005" }] },
  // Q67
  { textFr: "Quel est le rôle principal du département ?", lang: 'es' as const, text: "¿Cuál es el papel principal del departamento?", explanation: "El departamento tiene como papel principal la acción social y la solidaridad (ayuda social, RSA, protección de la infancia). También gestiona los colegios y las carreteras departamentales.", choices: [{ id: 'a' as const, text: "La acción social y la solidaridad" }, { id: 'b' as const, text: "La defensa nacional" }, { id: 'c' as const, text: "La política exterior" }, { id: 'd' as const, text: "La gestión de las universidades" }] },
  // Q68
  { textFr: "Quel est le rôle principal des communes ?", lang: 'es' as const, text: "¿Cuál es el papel principal de los municipios?", explanation: "Los municipios gestionan los servicios de proximidad: registro civil, escuelas infantiles y primarias, urbanismo, vías municipales, agua y saneamiento.", choices: [{ id: 'a' as const, text: "Gestionar los servicios de proximidad (registro civil, escuelas, urbanismo)" }, { id: 'b' as const, text: "Organizar la defensa nacional" }, { id: 'c' as const, text: "Gestionar los hospitales" }, { id: 'd' as const, text: "Recaudar los impuestos nacionales" }] },
  // Q69
  { textFr: "Combien de communes environ existe-t-il en France ?", lang: 'es' as const, text: "¿Cuántos municipios existen aproximadamente en Francia?", explanation: "Francia tiene aproximadamente 35 000 municipios, lo que la convierte en el país de Europa con el mayor número de municipios.", choices: [{ id: 'a' as const, text: "Aproximadamente 35 000" }, { id: 'b' as const, text: "Aproximadamente 10 000" }, { id: 'c' as const, text: "Aproximadamente 5 000" }, { id: 'd' as const, text: "Aproximadamente 50 000" }] },
  // Q70
  { textFr: "Quel traité concerne la construction de l'Union européenne ?", lang: 'es' as const, text: "¿Qué tratado concierne a la construcción de la Unión Europea?", explanation: "El Tratado de Maastricht (1992) es el tratado fundador de la Unión Europea. Instituyó la ciudadanía europea y sentó las bases de la moneda única.", choices: [{ id: 'a' as const, text: "El Tratado de Maastricht" }, { id: 'b' as const, text: "El Tratado de Versalles" }, { id: 'c' as const, text: "El Tratado de Westfalia" }, { id: 'd' as const, text: "El Tratado de Viena" }] },
  // Q71
  { textFr: "Quel État a quitté l'Union européenne en 2020 ?", lang: 'es' as const, text: "¿Qué Estado abandonó la Unión Europea en 2020?", explanation: "El Reino Unido abandonó la Unión Europea el 31 de enero de 2020, tras el referéndum sobre el Brexit de 2016.", choices: [{ id: 'a' as const, text: "El Reino Unido" }, { id: 'b' as const, text: "Noruega" }, { id: 'c' as const, text: "Suiza" }, { id: 'd' as const, text: "Islandia" }] },
  // Q72
  { textFr: "Quelle est la devise de l'Union européenne ?", lang: 'es' as const, text: "¿Cuál es el lema de la Unión Europea?", explanation: "El lema de la Unión Europea es «Unida en la diversidad». Simboliza la unidad de los pueblos europeos en el respeto de sus diferencias culturales.", choices: [{ id: 'a' as const, text: "Unida en la diversidad" }, { id: 'b' as const, text: "Libertad, Igualdad, Fraternidad" }, { id: 'c' as const, text: "Paz y prosperidad" }, { id: 'd' as const, text: "La unión hace la fuerza" }] },
  // Q73
  { textFr: "Quel est l'hymne de l'Union européenne ?", lang: 'es' as const, text: "¿Cuál es el himno de la Unión Europea?", explanation: "El himno de la Unión Europea es la Oda a la Alegría, extracto de la 9.a sinfonía de Ludwig van Beethoven. Fue adoptado por el Consejo de Europa en 1972.", choices: [{ id: 'a' as const, text: "La Oda a la Alegría de Beethoven" }, { id: 'b' as const, text: "La Marsellesa" }, { id: 'c' as const, text: "El Bolero de Ravel" }, { id: 'd' as const, text: "Las Cuatro Estaciones de Vivaldi" }] },
  // Q74
  { textFr: "De quoi est composé le drapeau européen ?", lang: 'es' as const, text: "¿De qué está compuesta la bandera europea?", explanation: "La bandera europea está compuesta por 12 estrellas doradas dispuestas en círculo sobre fondo azul. El número 12 simboliza la perfección y la unidad, no corresponde al número de Estados miembros.", choices: [{ id: 'a' as const, text: "12 estrellas doradas dispuestas en círculo sobre fondo azul" }, { id: 'b' as const, text: "27 estrellas sobre fondo azul" }, { id: 'c' as const, text: "Franjas horizontales azules y blancas" }, { id: 'd' as const, text: "15 estrellas doradas sobre fondo rojo" }] },
  // Q75
  { textFr: "De quelle couleur est le drapeau européen ?", lang: 'es' as const, text: "¿De qué color es la bandera europea?", explanation: "La bandera europea es azul con estrellas doradas (amarillas). El fondo azul representa el cielo y las estrellas simbolizan la unidad de los pueblos de Europa.", choices: [{ id: 'a' as const, text: "Azul con estrellas doradas" }, { id: 'b' as const, text: "Rojo con estrellas blancas" }, { id: 'c' as const, text: "Verde con estrellas doradas" }, { id: 'd' as const, text: "Blanco con estrellas azules" }] },
  // Q76
  { textFr: "En quelle année le traité de Maastricht a-t-il été signé ?", lang: 'es' as const, text: "¿En qué año se firmó el Tratado de Maastricht?", explanation: "El Tratado de Maastricht fue firmado el 7 de febrero de 1992. Creó la Unión Europea y sentó las bases de la moneda única (el euro).", choices: [{ id: 'a' as const, text: "1992" }, { id: 'b' as const, text: "1957" }, { id: 'c' as const, text: "1989" }, { id: 'd' as const, text: "2000" }] },
  // Q77
  { textFr: "Où est le siège du Parlement européen ?", lang: 'es' as const, text: "¿Dónde está la sede del Parlamento Europeo?", explanation: "La sede del Parlamento Europeo está en Estrasburgo (Francia). También se celebran sesiones en Bruselas (Bélgica).", choices: [{ id: 'a' as const, text: "En Estrasburgo" }, { id: 'b' as const, text: "En Bruselas" }, { id: 'c' as const, text: "En Luxemburgo" }, { id: 'd' as const, text: "En Berlín" }] },
  // Q78
  { textFr: "Où est le siège de la Commission européenne ?", lang: 'es' as const, text: "¿Dónde está la sede de la Comisión Europea?", explanation: "La sede de la Comisión Europea está en Bruselas (Bélgica). La Comisión es el órgano ejecutivo de la Unión Europea.", choices: [{ id: 'a' as const, text: "En Bruselas" }, { id: 'b' as const, text: "En Estrasburgo" }, { id: 'c' as const, text: "En Luxemburgo" }, { id: 'd' as const, text: "En París" }] },
  // Q79
  { textFr: "Comment est désigné le Premier ministre ?", lang: 'es' as const, text: "¿Cómo se designa al Primer Ministro?", explanation: "El Primer Ministro es nombrado por el Presidente de la República. No es elegido directamente por los ciudadanos.", choices: [{ id: 'a' as const, text: "Es nombrado por el Presidente de la República" }, { id: 'b' as const, text: "Es elegido por sufragio universal directo" }, { id: 'c' as const, text: "Es elegido por los diputados" }, { id: 'd' as const, text: "Es designado por el Consejo Constitucional" }] },
  // Q80
  { textFr: "Qui peut se présenter aux élections présidentielles ?", lang: 'es' as const, text: "¿Quién puede presentarse a las elecciones presidenciales?", explanation: "Todo ciudadano francés de al menos 18 años que goce de sus derechos civiles y políticos puede presentarse, a condición de obtener 500 avales de cargos electos.", choices: [{ id: 'a' as const, text: "Todo ciudadano francés que haya obtenido 500 avales de cargos electos" }, { id: 'b' as const, text: "Únicamente los miembros de un partido político" }, { id: 'c' as const, text: "Únicamente los antiguos ministros" }, { id: 'd' as const, text: "Únicamente las personas mayores de 40 años" }] },
  // Q81
  { textFr: "À qui appartient la souveraineté nationale ?", lang: 'es' as const, text: "¿A quién pertenece la soberanía nacional?", explanation: "La soberanía nacional pertenece al pueblo, que la ejerce a través de sus representantes y por la vía del referéndum (artículo 3 de la Constitución).", choices: [{ id: 'a' as const, text: "Al pueblo" }, { id: 'b' as const, text: "Al Presidente de la República" }, { id: 'c' as const, text: "Al Parlamento" }, { id: 'd' as const, text: "Al Gobierno" }] },
  // Q82
  { textFr: "L'inscription sur les listes électorales est :", lang: 'es' as const, text: "La inscripción en las listas electorales es:", explanation: "La inscripción en las listas electorales es obligatoria para todo ciudadano francés mayor de edad. Desde 2019, la inscripción es automática a los 18 años.", choices: [{ id: 'a' as const, text: "Obligatoria" }, { id: 'b' as const, text: "Facultativa" }, { id: 'c' as const, text: "Automática únicamente para los hombres" }, { id: 'd' as const, text: "Reservada a las personas mayores de 21 años" }] },
  // Q83
  { textFr: "Quelle condition est nécessaire pour voter aux élections présidentielles ?", lang: 'es' as const, text: "¿Qué condición es necesaria para votar en las elecciones presidenciales?", explanation: "Para votar en las elecciones presidenciales, hay que tener la nacionalidad francesa, tener 18 años cumplidos, gozar de sus derechos civiles y políticos, y estar inscrito en las listas electorales.", choices: [{ id: 'a' as const, text: "Tener la nacionalidad francesa, ser mayor de edad y estar inscrito en las listas electorales" }, { id: 'b' as const, text: "Ser residente en Francia desde al menos 5 años" }, { id: 'c' as const, text: "Tener antecedentes penales limpios" }, { id: 'd' as const, text: "Ser titular de un diploma" }] },
  // Q84
  { textFr: "Quelle condition faut-il remplir pour être candidat aux élections municipales ?", lang: 'es' as const, text: "¿Qué condición hay que cumplir para ser candidato en las elecciones municipales?", explanation: "Para ser candidato en las elecciones municipales, hay que tener 18 años cumplidos, ser de nacionalidad francesa o ciudadano de la UE, y estar inscrito en las listas electorales del municipio o pagar impuestos en él.", choices: [{ id: 'a' as const, text: "Tener 18 años y estar inscrito en las listas electorales del municipio" }, { id: 'b' as const, text: "Tener 25 años y residir en el municipio desde hace 10 años" }, { id: 'c' as const, text: "Ser funcionario" }, { id: 'd' as const, text: "Ser propietario en el municipio" }] },
  // Q85
  { textFr: "Parmi ces autorités, laquelle est élue ?", lang: 'es' as const, text: "Entre estas autoridades, ¿cuál es elegida?", explanation: "El alcalde es elegido por los concejales municipales. El prefecto es nombrado, el fiscal es un magistrado y el director de escuela es un funcionario.", choices: [{ id: 'a' as const, text: "El alcalde" }, { id: 'b' as const, text: "El prefecto" }, { id: 'c' as const, text: "El fiscal de la República" }, { id: 'd' as const, text: "El director de escuela" }] },
  // Q86
  { textFr: "Quelles sont les fonctions du maire ?", lang: 'es' as const, text: "¿Cuáles son las funciones del alcalde?", explanation: "El alcalde es a la vez oficial del registro civil, representante del Estado en el municipio y jefe de la administración municipal. Celebra matrimonios y expide permisos de construcción.", choices: [{ id: 'a' as const, text: "Oficial del registro civil, representante del Estado y jefe de la administración municipal" }, { id: 'b' as const, text: "Jefe de la policía nacional y de los bomberos" }, { id: 'c' as const, text: "Presidente del tribunal del municipio" }, { id: 'd' as const, text: "Responsable de la educación nacional en el municipio" }] },
  // Q87
  { textFr: "Une personne n'ayant pas d'accès à internet veut s'inscrire sur les listes électorales. Où peut-elle s'inscrire ?", lang: 'es' as const, text: "Una persona que no tiene acceso a internet quiere inscribirse en las listas electorales. ¿Dónde puede inscribirse?", explanation: "Una persona puede inscribirse en las listas electorales acudiendo al ayuntamiento de su domicilio. La inscripción en línea no es la única opción.", choices: [{ id: 'a' as const, text: "En el ayuntamiento de su domicilio" }, { id: 'b' as const, text: "En la prefectura únicamente" }, { id: 'c' as const, text: "En la comisaría de policía" }, { id: 'd' as const, text: "En el tribunal judicial" }] },
  // Q88
  { textFr: "À quel âge peut-on devenir électeur ?", lang: 'es' as const, text: "¿A qué edad se puede ser elector?", explanation: "Se puede ser elector a los 18 años en Francia. Es la edad de la mayoría civil y política desde 1974.", choices: [{ id: 'a' as const, text: "18 años" }, { id: 'b' as const, text: "16 años" }, { id: 'c' as const, text: "21 años" }, { id: 'd' as const, text: "25 años" }] },
  // Q89
  { textFr: "En France, est-ce obligatoire de voter ?", lang: 'es' as const, text: "En Francia, ¿es obligatorio votar?", explanation: "No, el voto no es obligatorio en Francia. Es un derecho y un deber cívico, pero no hay sanción en caso de abstención.", choices: [{ id: 'a' as const, text: "No, el voto es un derecho pero no una obligación legal" }, { id: 'b' as const, text: "Sí, bajo pena de multa" }, { id: 'c' as const, text: "Sí, bajo pena de prisión" }, { id: 'd' as const, text: "Sí, excepto para las personas mayores de 70 años" }] },
  // Q90
  { textFr: "Comment sont désignés les députés ?", lang: 'es' as const, text: "¿Cómo se designan los diputados?", explanation: "Los diputados son elegidos por sufragio universal directo por los ciudadanos franceses. Cada diputado representa una circunscripción legislativa.", choices: [{ id: 'a' as const, text: "Son elegidos por sufragio universal directo" }, { id: 'b' as const, text: "Son nombrados por el Presidente de la República" }, { id: 'c' as const, text: "Son elegidos por los senadores" }, { id: 'd' as const, text: "Son designados por los partidos políticos" }] },
  // Q91
  { textFr: "En France, est-ce possible d'adhérer à un parti politique ?", lang: 'es' as const, text: "En Francia, ¿es posible adherirse a un partido político?", explanation: "Sí, en Francia, toda persona puede adherirse libremente al partido político de su elección. La libertad de asociación y el pluralismo político están garantizados por la Constitución.", choices: [{ id: 'a' as const, text: "Sí, se puede adherir libremente al partido de su elección" }, { id: 'b' as const, text: "No, los partidos políticos están prohibidos" }, { id: 'c' as const, text: "Sí, pero únicamente si se es ciudadano francés" }, { id: 'd' as const, text: "No, solo los cargos electos pueden adherirse a un partido" }] },
  // Q92
  { textFr: "Qui gère les collèges publics ?", lang: 'es' as const, text: "¿Quién gestiona los colegios públicos?", explanation: "Los colegios públicos son gestionados por el departamento. La construcción, el mantenimiento y el funcionamiento de los colegios son competencia del consejo departamental.", choices: [{ id: 'a' as const, text: "El departamento" }, { id: 'b' as const, text: "El municipio" }, { id: 'c' as const, text: "La región" }, { id: 'd' as const, text: "El Estado directamente" }] },
  // Q93
  { textFr: "Qui gère les écoles primaires et maternelles publiques ?", lang: 'es' as const, text: "¿Quién gestiona las escuelas primarias y de infantil públicas?", explanation: "Las escuelas primarias y de infantil públicas son gestionadas por el municipio. El municipio asegura la construcción, el mantenimiento y el funcionamiento de los edificios escolares.", choices: [{ id: 'a' as const, text: "El municipio" }, { id: 'b' as const, text: "El departamento" }, { id: 'c' as const, text: "La región" }, { id: 'd' as const, text: "El Ministerio de Educación Nacional" }] },
  // Q94
  { textFr: "Comment sont désignés les maires ?", lang: 'es' as const, text: "¿Cómo se designan los alcaldes?", explanation: "Los alcaldes son elegidos por los concejales municipales durante la primera sesión del nuevo consejo municipal, después de las elecciones municipales.", choices: [{ id: 'a' as const, text: "Son elegidos por los concejales municipales" }, { id: 'b' as const, text: "Son elegidos directamente por los ciudadanos" }, { id: 'c' as const, text: "Son nombrados por el prefecto" }, { id: 'd' as const, text: "Son designados por el Presidente de la República" }] },
  // Q95
  { textFr: "Quelle collectivité territoriale est responsable des transports régionaux ?", lang: 'es' as const, text: "¿Qué colectividad territorial es responsable de los transportes regionales?", explanation: "La región es responsable de los transportes regionales (TER). Organiza y financia los servicios de transporte ferroviario regional de viajeros.", choices: [{ id: 'a' as const, text: "La región" }, { id: 'b' as const, text: "El departamento" }, { id: 'c' as const, text: "El municipio" }, { id: 'd' as const, text: "El Estado" }] },
  // Q96
  { textFr: "Quelle est l'une des voies possibles pour modifier la Constitution ?", lang: 'es' as const, text: "¿Cuál es una de las vías posibles para modificar la Constitución?", explanation: "La Constitución puede ser modificada por referéndum o por el Congreso (reunión de la Asamblea Nacional y del Senado) con la mayoría de 3/5 de los votos emitidos.", choices: [{ id: 'a' as const, text: "Por referéndum o por el Congreso (Asamblea Nacional + Senado)" }, { id: 'b' as const, text: "Por decisión del Presidente de la República solo" }, { id: 'c' as const, text: "Por un voto de los alcaldes de Francia" }, { id: 'd' as const, text: "Por una decisión del Consejo Constitucional" }] },
  // Q97
  { textFr: "Qui assure l'intérim du président de la République en cas de décès ?", lang: 'es' as const, text: "¿Quién asegura la interinidad del Presidente de la República en caso de fallecimiento?", explanation: "El presidente del Senado asegura la interinidad del Presidente de la República en caso de vacancia (fallecimiento, dimisión). Está previsto por el artículo 7 de la Constitución.", choices: [{ id: 'a' as const, text: "El presidente del Senado" }, { id: 'b' as const, text: "El Primer Ministro" }, { id: 'c' as const, text: "El presidente de la Asamblea Nacional" }, { id: 'd' as const, text: "El Ministro del Interior" }] },
  // Q98
  { textFr: "Quel est le rôle du Conseil constitutionnel ?", lang: 'es' as const, text: "¿Cuál es el papel del Consejo Constitucional?", explanation: "El Consejo Constitucional verifica la conformidad de las leyes con la Constitución. También vela por la regularidad de las elecciones presidenciales y de los referéndums.", choices: [{ id: 'a' as const, text: "Verificar la conformidad de las leyes con la Constitución" }, { id: 'b' as const, text: "Votar las leyes" }, { id: 'c' as const, text: "Dirigir el Gobierno" }, { id: 'd' as const, text: "Juzgar los asuntos penales" }] },
  // Q99
  { textFr: "Quelle condition est obligatoire pour se présenter à l'élection présidentielle ?", lang: 'es' as const, text: "¿Qué condición es obligatoria para presentarse a la elección presidencial?", explanation: "Para presentarse a la elección presidencial, hay que obtener 500 firmas (avales) de cargos electos provenientes de al menos 30 departamentos o colectividades de ultramar diferentes.", choices: [{ id: 'a' as const, text: "Obtener 500 avales de cargos electos" }, { id: 'b' as const, text: "Ser miembro de un partido político" }, { id: 'c' as const, text: "Haber sido diputado o senador" }, { id: 'd' as const, text: "Tener más de 40 años" }] },
  // Q100
  { textFr: "Comment est organisé le découpage administratif de la France ?", lang: 'es' as const, text: "¿Cómo está organizada la división administrativa de Francia?", explanation: "La división administrativa de Francia está organizada en municipios, departamentos y regiones. Estos tres niveles de colectividades territoriales se administran libremente.", choices: [{ id: 'a' as const, text: "En municipios, departamentos y regiones" }, { id: 'b' as const, text: "En provincias, cantones y distritos" }, { id: 'c' as const, text: "En ciudades, condados y estados federados" }, { id: 'd' as const, text: "En distritos y prefecturas únicamente" }] },
  // Q101
  { textFr: "En quelle année la citoyenneté européenne a-t-elle été créée ?", lang: 'es' as const, text: "¿En qué año se creó la ciudadanía europea?", explanation: "La ciudadanía europea fue creada por el Tratado de Maastricht en 1992. Confiere a los ciudadanos de la UE derechos como la libre circulación y el derecho de voto en las elecciones municipales y europeas en cualquier Estado miembro.", choices: [{ id: 'a' as const, text: "1992" }, { id: 'b' as const, text: "1957" }, { id: 'c' as const, text: "2000" }, { id: 'd' as const, text: "1985" }] },
  // Q102
  { textFr: "Qui a composé l'hymne de l'Union européenne ?", lang: 'es' as const, text: "¿Quién compuso el himno de la Unión Europea?", explanation: "El himno europeo es la Oda a la Alegría, compuesta por Ludwig van Beethoven. Es el último movimiento de su 9.a sinfonía.", choices: [{ id: 'a' as const, text: "Ludwig van Beethoven" }, { id: 'b' as const, text: "Wolfgang Amadeus Mozart" }, { id: 'c' as const, text: "Johann Sebastian Bach" }, { id: 'd' as const, text: "Claude Debussy" }] },
  // Q103
  { textFr: "Où est le siège de la Banque centrale européenne ?", lang: 'es' as const, text: "¿Dónde está la sede del Banco Central Europeo?", explanation: "La sede del Banco Central Europeo (BCE) se encuentra en Fráncfort del Meno, en Alemania. El BCE es responsable de la política monetaria de la zona euro.", choices: [{ id: 'a' as const, text: "En Fráncfort (Alemania)" }, { id: 'b' as const, text: "En Bruselas (Bélgica)" }, { id: 'c' as const, text: "En Luxemburgo" }, { id: 'd' as const, text: "En París (Francia)" }] },
  // Q104
  { textFr: "Qui siège au Parlement européen ?", lang: 'es' as const, text: "¿Quién ocupa su escaño en el Parlamento Europeo?", explanation: "Los eurodiputados ocupan su escaño en el Parlamento Europeo. Son elegidos por sufragio universal directo por los ciudadanos de los Estados miembros de la UE.", choices: [{ id: 'a' as const, text: "Los eurodiputados elegidos por los ciudadanos de la UE" }, { id: 'b' as const, text: "Los jefes de Estado de los países miembros" }, { id: 'c' as const, text: "Los ministros de Asuntos Exteriores" }, { id: 'd' as const, text: "Los embajadores de los países miembros" }] },
];
