export const theme2Pt = [
  // Q1
  { textFr: "Qui nomme le Premier ministre ?", lang: 'pt' as const, text: "Quem nomeia o Primeiro-Ministro?", explanation: "O Primeiro-Ministro é nomeado pelo Presidente da República. É uma prerrogativa constitucional definida pelo artigo 8 da Constituição de 1958.", choices: [{ id: 'a' as const, text: "O Presidente da República" }, { id: 'b' as const, text: "A Assembleia Nacional" }, { id: 'c' as const, text: "O Senado" }, { id: 'd' as const, text: "O Conselho Constitucional" }] },
  // Q2
  { textFr: "Le Parlement est composé :", lang: 'pt' as const, text: "O Parlamento é composto por:", explanation: "O Parlamento francês é bicameral. É composto pela Assembleia Nacional e pelo Senado, que votam as leis e controlam a ação do Governo.", choices: [{ id: 'a' as const, text: "A Assembleia Nacional e o Senado" }, { id: 'b' as const, text: "O Senado e o Conselho Constitucional" }, { id: 'c' as const, text: "A Assembleia Nacional e o Governo" }, { id: 'd' as const, text: "O Conselho de Estado e a Assembleia Nacional" }] },
  // Q3
  { textFr: "Qu'est-ce que le pouvoir exécutif ? Le pouvoir :", lang: 'pt' as const, text: "O que é o poder executivo? O poder:", explanation: "O poder executivo é o poder de fazer cumprir as leis. Na França, é exercido pelo Presidente da República e pelo Governo.", choices: [{ id: 'a' as const, text: "De fazer cumprir as leis" }, { id: 'b' as const, text: "De votar as leis" }, { id: 'c' as const, text: "De julgar as infrações" }, { id: 'd' as const, text: "De modificar a Constituição" }] },
  // Q4
  { textFr: "Les dirigeants sont élus par les citoyens dans :", lang: 'pt' as const, text: "Os dirigentes são eleitos pelos cidadãos em:", explanation: "Em uma democracia, os dirigentes são eleitos pelos cidadãos em eleições livres. É o princípio fundamental do regime democrático.", choices: [{ id: 'a' as const, text: "Uma democracia" }, { id: 'b' as const, text: "Uma ditadura" }, { id: 'c' as const, text: "Uma monarquia absoluta" }, { id: 'd' as const, text: "Uma oligarquia" }] },
  // Q5
  { textFr: "A-t-on le droit de ne pas respecter une loi ?", lang: 'pt' as const, text: "Temos o direito de não respeitar uma lei?", explanation: "Não, ninguém tem o direito de não respeitar a lei. A lei se aplica a todos de maneira igual. Ninguém pode alegar ignorância da lei.", choices: [{ id: 'a' as const, text: "Não, nunca" }, { id: 'b' as const, text: "Sim, se não concordarmos com a lei" }, { id: 'c' as const, text: "Sim, se for estrangeiro" }, { id: 'd' as const, text: "Sim, em certas circunstâncias pessoais" }] },
  // Q6
  { textFr: "Qui doit respecter la loi ?", lang: 'pt' as const, text: "Quem deve respeitar a lei?", explanation: "Todos devem respeitar a lei na França, sem exceção. Este princípio se aplica aos cidadãos, aos estrangeiros, aos eleitos e aos dirigentes.", choices: [{ id: 'a' as const, text: "Todos" }, { id: 'b' as const, text: "Somente os cidadãos franceses" }, { id: 'c' as const, text: "Somente os adultos" }, { id: 'd' as const, text: "Somente as pessoas que vivem na França" }] },
  // Q7
  { textFr: "Quel est le rôle de l'autorité judiciaire ?", lang: 'pt' as const, text: "Qual é o papel da autoridade judiciária?", explanation: "A autoridade judiciária tem o papel de zelar pelo cumprimento das leis e sancionar o seu descumprimento. Ela protege as liberdades individuais.", choices: [{ id: 'a' as const, text: "Zelar pelo cumprimento das leis e sancionar o seu descumprimento" }, { id: 'b' as const, text: "Votar as leis" }, { id: 'c' as const, text: "Propor novas leis" }, { id: 'd' as const, text: "Nomear os ministros" }] },
  // Q8
  { textFr: "Quel pouvoir détient un juge ? Le pouvoir :", lang: 'pt' as const, text: "Que poder detém um juiz? O poder:", explanation: "O juiz detém o poder judiciário. Ele aplica a justiça fazendo cumprir as leis e sancionando as infrações.", choices: [{ id: 'a' as const, text: "Judiciário" }, { id: 'b' as const, text: "Executivo" }, { id: 'c' as const, text: "Legislativo" }, { id: 'd' as const, text: "Administrativo" }] },
  // Q9
  { textFr: "L'autorité judiciaire est exercée par :", lang: 'pt' as const, text: "A autoridade judiciária é exercida por:", explanation: "A autoridade judiciária é exercida pelos magistrados e juízes. Eles são independentes do poder executivo e do poder legislativo.", choices: [{ id: 'a' as const, text: "Os magistrados e os juízes" }, { id: 'b' as const, text: "Os deputados" }, { id: 'c' as const, text: "Os ministros" }, { id: 'd' as const, text: "Os prefeitos" }] },
  // Q10
  { textFr: "Que se passe-t-il si un ministre ne respecte pas la loi ?", lang: 'pt' as const, text: "O que acontece se um ministro não respeitar a lei?", explanation: "Um ministro que não respeitar a lei pode ser julgado como qualquer cidadão. Ninguém está acima das leis, incluindo os membros do Governo.", choices: [{ id: 'a' as const, text: "Ele pode ser julgado como qualquer cidadão" }, { id: 'b' as const, text: "Ele não pode ser julgado porque é ministro" }, { id: 'c' as const, text: "Ele é apenas demitido do Governo" }, { id: 'd' as const, text: "Ele é protegido pela imunidade ministerial vitalícia" }] },
  // Q11
  { textFr: "Qui est élu lors des élections législatives ?", lang: 'pt' as const, text: "Quem é eleito nas eleições legislativas?", explanation: "Os deputados são eleitos nas eleições legislativas. Eles atuam na Assembleia Nacional e votam as leis.", choices: [{ id: 'a' as const, text: "Os deputados" }, { id: 'b' as const, text: "Os senadores" }, { id: 'c' as const, text: "Os prefeitos" }, { id: 'd' as const, text: "Os conselheiros regionais" }] },
  // Q12
  { textFr: "Combien de députés composent l'Assemblée nationale ?", lang: 'pt' as const, text: "Quantos deputados compõem a Assembleia Nacional?", explanation: "A Assembleia Nacional é composta por 577 deputados. Eles são eleitos por sufrágio universal direto para um mandato de 5 anos.", choices: [{ id: 'a' as const, text: "577" }, { id: 'b' as const, text: "348" }, { id: 'c' as const, text: "500" }, { id: 'd' as const, text: "650" }] },
  // Q13
  { textFr: "Quand sont élus les sénateurs ?", lang: 'pt' as const, text: "Quando são eleitos os senadores?", explanation: "Os senadores são eleitos por sufrágio universal indireto pelos grandes eleitores. O Senado é renovado pela metade a cada 3 anos.", choices: [{ id: 'a' as const, text: "Eles são eleitos por sufrágio universal indireto" }, { id: 'b' as const, text: "Eles são eleitos por sufrágio universal direto" }, { id: 'c' as const, text: "Eles são nomeados pelo Presidente da República" }, { id: 'd' as const, text: "Eles são designados pelos deputados" }] },
  // Q14
  { textFr: "Qui est élu lors des élections municipales ?", lang: 'pt' as const, text: "Quem é eleito nas eleições municipais?", explanation: "Os conselheiros municipais são eleitos nas eleições municipais. Eles então elegem o prefeito entre eles.", choices: [{ id: 'a' as const, text: "Os conselheiros municipais" }, { id: 'b' as const, text: "O prefeito diretamente" }, { id: 'c' as const, text: "Os conselheiros departamentais" }, { id: 'd' as const, text: "Os deputados" }] },
  // Q15
  { textFr: "Qui est élu lors des élections présidentielles ?", lang: 'pt' as const, text: "Quem é eleito nas eleições presidenciais?", explanation: "O Presidente da República é eleito nas eleições presidenciais, por sufrágio universal direto desde 1962.", choices: [{ id: 'a' as const, text: "O Presidente da República" }, { id: 'b' as const, text: "O Primeiro-Ministro" }, { id: 'c' as const, text: "Os deputados" }, { id: 'd' as const, text: "Os senadores" }] },
  // Q16
  { textFr: "À partir de quel âge a-t-on le droit de voter ?", lang: 'pt' as const, text: "A partir de que idade se tem o direito de votar?", explanation: "Na França, o direito de voto é concedido a partir dos 18 anos. É a idade da maioridade civil e política.", choices: [{ id: 'a' as const, text: "18 anos" }, { id: 'b' as const, text: "16 anos" }, { id: 'c' as const, text: "21 anos" }, { id: 'd' as const, text: "25 anos" }] },
  // Q17
  { textFr: "Pour combien de temps est élu le président de la République française ?", lang: 'pt' as const, text: "Por quanto tempo é eleito o Presidente da República Francesa?", explanation: "O Presidente da República é eleito para um mandato de 5 anos (quinquênio) desde a reforma constitucional de 2000.", choices: [{ id: 'a' as const, text: "5 anos" }, { id: 'b' as const, text: "7 anos" }, { id: 'c' as const, text: "4 anos" }, { id: 'd' as const, text: "6 anos" }] },
  // Q18
  { textFr: "Pour combien de temps sont élus les députés ?", lang: 'pt' as const, text: "Por quanto tempo são eleitos os deputados?", explanation: "Os deputados são eleitos para um mandato de 5 anos. A Assembleia Nacional pode ser dissolvida antes do fim do mandato pelo Presidente da República.", choices: [{ id: 'a' as const, text: "5 anos" }, { id: 'b' as const, text: "6 anos" }, { id: 'c' as const, text: "4 anos" }, { id: 'd' as const, text: "7 anos" }] },
  // Q19
  { textFr: "Pour combien de temps sont élus les sénateurs ?", lang: 'pt' as const, text: "Por quanto tempo são eleitos os senadores?", explanation: "Os senadores são eleitos para um mandato de 6 anos. O Senado é renovado pela metade a cada 3 anos.", choices: [{ id: 'a' as const, text: "6 anos" }, { id: 'b' as const, text: "5 anos" }, { id: 'c' as const, text: "4 anos" }, { id: 'd' as const, text: "7 anos" }] },
  // Q20
  { textFr: "Qui possède le pouvoir exécutif ?", lang: 'pt' as const, text: "Quem possui o poder executivo?", explanation: "O poder executivo é detido pelo Presidente da República e pelo Governo. Eles fazem cumprir as leis votadas pelo Parlamento.", choices: [{ id: 'a' as const, text: "O Presidente da República e o Governo" }, { id: 'b' as const, text: "O Parlamento" }, { id: 'c' as const, text: "Os juízes" }, { id: 'd' as const, text: "O Conselho Constitucional" }] },
  // Q21
  { textFr: "Quelle condition est nécessaire pour voter aux élections ?", lang: 'pt' as const, text: "Que condição é necessária para votar nas eleições?", explanation: "Para votar nas eleições na França, é necessário estar inscrito nas listas eleitorais. A inscrição é uma condição prévia indispensável.", choices: [{ id: 'a' as const, text: "Estar inscrito nas listas eleitorais" }, { id: 'b' as const, text: "Ter um emprego na França" }, { id: 'c' as const, text: "Possuir um imóvel" }, { id: 'd' as const, text: "Ter um diploma francês" }] },
  // Q22
  { textFr: "Qui peut voter aux élections en France ?", lang: 'pt' as const, text: "Quem pode votar nas eleições na França?", explanation: "Os cidadãos franceses maiores de idade (18 anos ou mais) que gozam de seus direitos civis e políticos podem votar nas eleições na França.", choices: [{ id: 'a' as const, text: "Os cidadãos franceses maiores de idade" }, { id: 'b' as const, text: "Qualquer pessoa residente na França" }, { id: 'c' as const, text: "As pessoas com autorização de residência" }, { id: 'd' as const, text: "As pessoas com mais de 21 anos" }] },
  // Q23
  { textFr: "Que signifie « suffrage universel » ?", lang: 'pt' as const, text: "O que significa \"sufrágio universal\"?", explanation: "O sufrágio universal significa que todos os cidadãos maiores de idade têm o direito de votar, sem distinção de sexo, riqueza ou origem.", choices: [{ id: 'a' as const, text: "Todos os cidadãos maiores de idade têm o direito de votar" }, { id: 'b' as const, text: "Somente os homens têm o direito de votar" }, { id: 'c' as const, text: "O voto é obrigatório para todos" }, { id: 'd' as const, text: "Somente os proprietários podem votar" }] },
  // Q24
  { textFr: "Concernant les partis politiques, quelle proposition est correcte ?", lang: 'pt' as const, text: "Sobre os partidos políticos, qual proposição é correta?", explanation: "Na França, existem vários partidos políticos e é possível filiar-se livremente ao partido de sua escolha. O multipartidarismo é um princípio fundamental da democracia.", choices: [{ id: 'a' as const, text: "Existem vários partidos políticos e é possível filiar-se ao partido de sua escolha" }, { id: 'b' as const, text: "Existe apenas um partido político na França" }, { id: 'c' as const, text: "Os partidos políticos são proibidos" }, { id: 'd' as const, text: "Somente os funcionários públicos podem filiar-se a um partido" }] },
  // Q25
  { textFr: "Quel est le rôle des députés ?", lang: 'pt' as const, text: "Qual é o papel dos deputados?", explanation: "Os deputados votam as leis e controlam a ação do Governo. Eles representam o povo na Assembleia Nacional.", choices: [{ id: 'a' as const, text: "Votar as leis e controlar a ação do Governo" }, { id: 'b' as const, text: "Dirigir o Governo" }, { id: 'c' as const, text: "Nomear os juízes" }, { id: 'd' as const, text: "Administrar os municípios" }] },
  // Q26
  { textFr: "La séparation des pouvoirs est un principe fondamental. Quels sont les trois pouvoirs concernés ?", lang: 'pt' as const, text: "A separação dos poderes é um princípio fundamental. Quais são os três poderes envolvidos?", explanation: "Os três poderes são: o poder legislativo (fazer as leis), o poder executivo (aplicar as leis) e o poder judiciário (julgar). Este princípio garante a democracia.", choices: [{ id: 'a' as const, text: "Legislativo, executivo, judiciário" }, { id: 'b' as const, text: "Presidencial, parlamentar, judiciário" }, { id: 'c' as const, text: "Municipal, departamental, regional" }, { id: 'd' as const, text: "Militar, civil, religioso" }] },
  // Q27
  { textFr: "Qui possède le pouvoir législatif ?", lang: 'pt' as const, text: "Quem possui o poder legislativo?", explanation: "O poder legislativo é detido pelo Parlamento, composto pela Assembleia Nacional e pelo Senado. Ele vota as leis.", choices: [{ id: 'a' as const, text: "O Parlamento (Assembleia Nacional e Senado)" }, { id: 'b' as const, text: "O Presidente da República" }, { id: 'c' as const, text: "O Governo" }, { id: 'd' as const, text: "Os juízes" }] },
  // Q28
  { textFr: "Qui sanctionne l'auteur d'un vol ?", lang: 'pt' as const, text: "Quem sanciona o autor de um roubo?", explanation: "É a justiça (um juiz) que sanciona o autor de um roubo. O poder judiciário é o único competente para pronunciar sanções penais.", choices: [{ id: 'a' as const, text: "A justiça (um juiz)" }, { id: 'b' as const, text: "A polícia" }, { id: 'c' as const, text: "O prefeito" }, { id: 'd' as const, text: "A própria vítima" }] },
  // Q29
  { textFr: "Qui élit les députés ?", lang: 'pt' as const, text: "Quem elege os deputados?", explanation: "Os deputados são eleitos pelos cidadãos franceses por sufrágio universal direto. Cada deputado representa uma circunscrição.", choices: [{ id: 'a' as const, text: "Os cidadãos franceses por sufrágio universal direto" }, { id: 'b' as const, text: "Os senadores" }, { id: 'c' as const, text: "O Presidente da República" }, { id: 'd' as const, text: "Os grandes eleitores" }] },
  // Q30
  { textFr: "Qui vote les lois ?", lang: 'pt' as const, text: "Quem vota as leis?", explanation: "O Parlamento (Assembleia Nacional e Senado) vota as leis. É a função principal do poder legislativo.", choices: [{ id: 'a' as const, text: "O Parlamento (Assembleia Nacional e Senado)" }, { id: 'b' as const, text: "O Presidente da República" }, { id: 'c' as const, text: "O Governo" }, { id: 'd' as const, text: "O Conselho Constitucional" }] },
  // Q31
  { textFr: "Qui réside au palais de l'Élysée ?", lang: 'pt' as const, text: "Quem reside no Palácio do Eliseu?", explanation: "O Palácio do Eliseu é a residência oficial do Presidente da República Francesa, localizado em Paris.", choices: [{ id: 'a' as const, text: "O Presidente da República" }, { id: 'b' as const, text: "O Primeiro-Ministro" }, { id: 'c' as const, text: "O presidente da Assembleia Nacional" }, { id: 'd' as const, text: "O presidente do Senado" }] },
  // Q32
  { textFr: "Combien y a-t-il de départements en France ?", lang: 'pt' as const, text: "Quantos departamentos existem na França?", explanation: "A França tem 101 departamentos: 96 departamentos metropolitanos e 5 departamentos ultramarinos (Guadalupe, Martinica, Guiana, Reunião, Mayotte).", choices: [{ id: 'a' as const, text: "101" }, { id: 'b' as const, text: "96" }, { id: 'c' as const, text: "95" }, { id: 'd' as const, text: "110" }] },
  // Q33
  { textFr: "Qui représente l'État dans un département ?", lang: 'pt' as const, text: "Quem representa o Estado em um departamento?", explanation: "O prefeito representa o Estado no departamento. Ele é nomeado pelo Presidente da República e zela pela aplicação das leis.", choices: [{ id: 'a' as const, text: "O prefeito" }, { id: 'b' as const, text: "O maire" }, { id: 'c' as const, text: "O deputado" }, { id: 'd' as const, text: "O senador" }] },
  // Q34
  { textFr: "Qui dirige la commune ?", lang: 'pt' as const, text: "Quem dirige o município?", explanation: "O maire (prefeito municipal) dirige o município. Ele é eleito pelos conselheiros municipais e exerce funções tanto em nome do município quanto em nome do Estado.", choices: [{ id: 'a' as const, text: "O maire (prefeito municipal)" }, { id: 'b' as const, text: "O prefeito departamental" }, { id: 'c' as const, text: "O deputado" }, { id: 'd' as const, text: "O presidente do conselho departamental" }] },
  // Q35
  { textFr: "Est-ce que le président de la République a tous les pouvoirs ?", lang: 'pt' as const, text: "O Presidente da República tem todos os poderes?", explanation: "Não, o Presidente da República não tem todos os poderes. A separação dos poderes (legislativo, executivo, judiciário) garante que nenhuma pessoa detenha todos os poderes.", choices: [{ id: 'a' as const, text: "Não, os poderes são separados" }, { id: 'b' as const, text: "Sim, ele tem todos os poderes" }, { id: 'c' as const, text: "Sim, exceto o poder judiciário" }, { id: 'd' as const, text: "Sim, em período de crise" }] },
  // Q36
  { textFr: "Qui est le préfet ?", lang: 'pt' as const, text: "Quem é o prefeito departamental?", explanation: "O prefeito departamental é o representante do Estado no departamento. Ele é nomeado pelo Presidente da República em Conselho de Ministros.", choices: [{ id: 'a' as const, text: "O representante do Estado no departamento" }, { id: 'b' as const, text: "O chefe da polícia municipal" }, { id: 'c' as const, text: "Um eleito local" }, { id: 'd' as const, text: "O diretor do hospital público" }] },
  // Q37
  { textFr: "Quel est le rôle du Parlement ?", lang: 'pt' as const, text: "Qual é o papel do Parlamento?", explanation: "O Parlamento vota as leis e controla a ação do Governo. Ele exerce o poder legislativo na França.", choices: [{ id: 'a' as const, text: "Votar as leis e controlar a ação do Governo" }, { id: 'b' as const, text: "Dirigir o exército" }, { id: 'c' as const, text: "Nomear os juízes" }, { id: 'd' as const, text: "Administrar os impostos locais" }] },
  // Q38
  { textFr: "Quel est le régime politique de la France aujourd'hui ?", lang: 'pt' as const, text: "Qual é o regime político da França hoje?", explanation: "A França é uma república democrática. Seu regime é uma democracia representativa onde os cidadãos elegem seus representantes.", choices: [{ id: 'a' as const, text: "Uma república democrática" }, { id: 'b' as const, text: "Uma monarquia constitucional" }, { id: 'c' as const, text: "Uma ditadura" }, { id: 'd' as const, text: "Um império" }] },
  // Q39
  { textFr: "Combien d'États font partie de l'Union européenne au 1er janvier 2025 ?", lang: 'pt' as const, text: "Quantos Estados fazem parte da União Europeia em 1º de janeiro de 2025?", explanation: "A União Europeia tem 27 Estados-membros em 1º de janeiro de 2025, desde a saída do Reino Unido em 2020.", choices: [{ id: 'a' as const, text: "27" }, { id: 'b' as const, text: "28" }, { id: 'c' as const, text: "25" }, { id: 'd' as const, text: "30" }] },
  // Q40
  { textFr: "Quel État n'est pas membre de l'Union européenne ?", lang: 'pt' as const, text: "Qual Estado não é membro da União Europeia?", explanation: "A Suíça não é membro da União Europeia. Ela escolheu permanecer fora da UE, mantendo acordos bilaterais.", choices: [{ id: 'a' as const, text: "A Suíça" }, { id: 'b' as const, text: "A Alemanha" }, { id: 'c' as const, text: "A Itália" }, { id: 'd' as const, text: "A Espanha" }] },
  // Q41
  { textFr: "Quelle condition est nécessaire pour voter aux élections européennes ?", lang: 'pt' as const, text: "Que condição é necessária para votar nas eleições europeias?", explanation: "Para votar nas eleições europeias, é necessário ser cidadão de um Estado-membro da União Europeia e estar inscrito nas listas eleitorais.", choices: [{ id: 'a' as const, text: "Ser cidadão de um Estado-membro da União Europeia" }, { id: 'b' as const, text: "Ser cidadão francês exclusivamente" }, { id: 'c' as const, text: "Residir na França há mais de 10 anos" }, { id: 'd' as const, text: "Ter mais de 21 anos" }] },
  // Q42
  { textFr: "À quelle fréquence les élections européennes sont-elles organisées ?", lang: 'pt' as const, text: "Com que frequência as eleições europeias são organizadas?", explanation: "As eleições europeias são organizadas a cada 5 anos. Os cidadãos da UE elegem os deputados europeus que atuam no Parlamento Europeu.", choices: [{ id: 'a' as const, text: "A cada 5 anos" }, { id: 'b' as const, text: "A cada 4 anos" }, { id: 'c' as const, text: "A cada 6 anos" }, { id: 'd' as const, text: "A cada 3 anos" }] },
  // Q43
  { textFr: "Quel pays est un pays fondateur de l'Union européenne ?", lang: 'pt' as const, text: "Qual país é um país fundador da União Europeia?", explanation: "A França é um dos seis países fundadores da construção europeia (junto com Alemanha, Itália, Bélgica, Países Baixos e Luxemburgo), signatários do Tratado de Roma em 1957.", choices: [{ id: 'a' as const, text: "A França" }, { id: 'b' as const, text: "A Espanha" }, { id: 'c' as const, text: "O Reino Unido" }, { id: 'd' as const, text: "A Polônia" }] },
  // Q44
  { textFr: "Quelle est la monnaie utilisée en France ?", lang: 'pt' as const, text: "Qual é a moeda utilizada na França?", explanation: "O euro é a moeda utilizada na França desde 1º de janeiro de 2002. É a moeda comum a muitos países da União Europeia.", choices: [{ id: 'a' as const, text: "O euro" }, { id: 'b' as const, text: "O franco" }, { id: 'c' as const, text: "A libra" }, { id: 'd' as const, text: "O dólar" }] },
  // Q45
  { textFr: "Qui élit les députés européens ?", lang: 'pt' as const, text: "Quem elege os deputados europeus?", explanation: "Os deputados europeus são eleitos pelos cidadãos dos Estados-membros da União Europeia por sufrágio universal direto.", choices: [{ id: 'a' as const, text: "Os cidadãos dos Estados-membros da União Europeia" }, { id: 'b' as const, text: "Os chefes de Estado dos países membros" }, { id: 'c' as const, text: "A Comissão Europeia" }, { id: 'd' as const, text: "Os parlamentos nacionais" }] },
  // Q46
  { textFr: "Quand célèbre-t-on la journée de l'Europe ?", lang: 'pt' as const, text: "Quando se celebra o Dia da Europa?", explanation: "O Dia da Europa é celebrado em 9 de maio. Ele comemora a Declaração de Robert Schuman de 9 de maio de 1950, considerada o ato fundador da construção europeia.", choices: [{ id: 'a' as const, text: "9 de maio" }, { id: 'b' as const, text: "14 de julho" }, { id: 'c' as const, text: "1º de janeiro" }, { id: 'd' as const, text: "25 de março" }] },
  // Q47
  { textFr: "Qu'est-ce que l'État de droit ?", lang: 'pt' as const, text: "O que é o Estado de direito?", explanation: "O Estado de direito é um sistema no qual os poderes públicos estão submetidos ao respeito do direito. Toda pessoa, incluindo o Estado, deve respeitar as leis.", choices: [{ id: 'a' as const, text: "Um Estado no qual os poderes públicos estão submetidos ao respeito do direito" }, { id: 'b' as const, text: "Um Estado onde apenas o presidente decide as leis" }, { id: 'c' as const, text: "Um Estado sem Constituição" }, { id: 'd' as const, text: "Um Estado onde os juízes fazem as leis" }] },
  // Q48
  { textFr: "Le président de la République a commis un crime. Quelle proposition est correcte ?", lang: 'pt' as const, text: "O Presidente da República cometeu um crime. Qual proposição é correta?", explanation: "O Presidente da República pode ser julgado após o fim de seu mandato. Durante seu mandato, ele se beneficia de uma imunidade temporária, mas não está acima das leis.", choices: [{ id: 'a' as const, text: "Ele pode ser julgado após o fim de seu mandato" }, { id: 'b' as const, text: "Ele nunca pode ser julgado" }, { id: 'c' as const, text: "Ele é imediatamente preso" }, { id: 'd' as const, text: "Ele é julgado apenas pelo Parlamento" }] },
  // Q49
  { textFr: "La loi est l'expression de :", lang: 'pt' as const, text: "A lei é a expressão de:", explanation: "A lei é a expressão da vontade geral, conforme enuncia o artigo 6 da Declaração dos Direitos do Homem e do Cidadão de 1789.", choices: [{ id: 'a' as const, text: "A vontade geral" }, { id: 'b' as const, text: "A vontade do presidente" }, { id: 'c' as const, text: "A vontade dos juízes" }, { id: 'd' as const, text: "A vontade do Governo" }] },
  // Q50
  { textFr: "Quelle est la durée du mandat du conseil municipal et du maire ?", lang: 'pt' as const, text: "Qual é a duração do mandato do conselho municipal e do maire?", explanation: "O conselho municipal e o maire são eleitos para um mandato de 6 anos. As eleições municipais acontecem a cada 6 anos.", choices: [{ id: 'a' as const, text: "6 anos" }, { id: 'b' as const, text: "5 anos" }, { id: 'c' as const, text: "4 anos" }, { id: 'd' as const, text: "7 anos" }] },
  // Q51
  { textFr: "Que garantit l'État de droit ?", lang: 'pt' as const, text: "O que o Estado de direito garante?", explanation: "O Estado de direito garante o respeito dos direitos fundamentais e das liberdades individuais. Ele assegura que ninguém, nem mesmo o Estado, esteja acima das leis.", choices: [{ id: 'a' as const, text: "O respeito dos direitos fundamentais e das liberdades individuais" }, { id: 'b' as const, text: "Um emprego para todos os cidadãos" }, { id: 'c' as const, text: "A gratuidade de todos os serviços públicos" }, { id: 'd' as const, text: "A ausência total de impostos" }] },
  // Q52
  { textFr: "Une personne peut-elle voter à la place d'une autre ?", lang: 'pt' as const, text: "Uma pessoa pode votar no lugar de outra?", explanation: "Sim, é possível votar por procuração. Um eleitor impedido pode dar procuração a outro eleitor inscrito no mesmo município para votar em seu lugar.", choices: [{ id: 'a' as const, text: "Sim, por procuração" }, { id: 'b' as const, text: "Não, nunca" }, { id: 'c' as const, text: "Sim, sem nenhuma formalidade" }, { id: 'd' as const, text: "Sim, apenas para membros de sua família" }] },
  // Q53
  { textFr: "Est-ce que le vote est obligatoire ?", lang: 'pt' as const, text: "O voto é obrigatório?", explanation: "Não, o voto não é obrigatório na França. É um direito e não uma obrigação legal, mas é um dever cívico.", choices: [{ id: 'a' as const, text: "Não, não é obrigatório, mas é um dever cívico" }, { id: 'b' as const, text: "Sim, é obrigatório para todos" }, { id: 'c' as const, text: "Sim, sob pena de multa" }, { id: 'd' as const, text: "Sim, exceto para idosos" }] },
  // Q54
  { textFr: "À la fin de son mandat, le président de la République peut-il décider de rester au pouvoir ?", lang: 'pt' as const, text: "Ao final de seu mandato, o Presidente da República pode decidir permanecer no poder?", explanation: "Não, o presidente não pode decidir permanecer no poder ao final de seu mandato. Ele deve se candidatar novamente às eleições ou deixar suas funções. É um princípio fundamental da democracia.", choices: [{ id: 'a' as const, text: "Não, ele deve se candidatar novamente às eleições ou deixar suas funções" }, { id: 'b' as const, text: "Sim, se ele decidir" }, { id: 'c' as const, text: "Sim, com a concordância do Parlamento" }, { id: 'd' as const, text: "Sim, em caso de crise nacional" }] },
  // Q55
  { textFr: "Qui dirige l'action du Gouvernement ?", lang: 'pt' as const, text: "Quem dirige a ação do Governo?", explanation: "O Primeiro-Ministro dirige a ação do Governo, conforme o artigo 21 da Constituição. Ele coordena a ação dos ministros.", choices: [{ id: 'a' as const, text: "O Primeiro-Ministro" }, { id: 'b' as const, text: "O Presidente da República" }, { id: 'c' as const, text: "O presidente da Assembleia Nacional" }, { id: 'd' as const, text: "O Ministro do Interior" }] },
  // Q56
  { textFr: "Quelle est l'organisation administrative de la France ?", lang: 'pt' as const, text: "Qual é a organização administrativa da França?", explanation: "A França é organizada em municípios, departamentos e regiões. São os três níveis de coletividades territoriais previstos pela Constituição.", choices: [{ id: 'a' as const, text: "Municípios, departamentos e regiões" }, { id: 'b' as const, text: "Províncias, cantões e distritos" }, { id: 'c' as const, text: "Cidades, condados e Estados" }, { id: 'd' as const, text: "Arrondissements, prefeituras e metrópoles" }] },
  // Q57
  { textFr: "Qu'est-ce que le pouvoir législatif ? Le pouvoir :", lang: 'pt' as const, text: "O que é o poder legislativo? O poder:", explanation: "O poder legislativo é o poder de fazer as leis. Na França, é exercido pelo Parlamento (Assembleia Nacional e Senado).", choices: [{ id: 'a' as const, text: "De fazer as leis" }, { id: 'b' as const, text: "De fazer cumprir as leis" }, { id: 'c' as const, text: "De julgar as infrações" }, { id: 'd' as const, text: "De nomear os ministros" }] },
  // Q58
  { textFr: "Pourquoi séparer les trois pouvoirs dans une démocratie ?", lang: 'pt' as const, text: "Por que separar os três poderes em uma democracia?", explanation: "A separação dos poderes permite evitar que uma única pessoa ou instituição concentre todos os poderes. É uma garantia contra o abuso de poder e a tirania.", choices: [{ id: 'a' as const, text: "Para evitar a concentração dos poderes e proteger as liberdades" }, { id: 'b' as const, text: "Para criar mais empregos públicos" }, { id: 'c' as const, text: "Para que as decisões sejam mais lentas" }, { id: 'd' as const, text: "Para aumentar o número de eleições" }] },
  // Q59
  { textFr: "Quel est le rôle du gouvernement ?", lang: 'pt' as const, text: "Qual é o papel do governo?", explanation: "O Governo determina e conduz a política da nação. Ele dispõe da administração e da força armada (artigo 20 da Constituição).", choices: [{ id: 'a' as const, text: "Determinar e conduzir a política da nação" }, { id: 'b' as const, text: "Votar as leis" }, { id: 'c' as const, text: "Julgar os criminosos" }, { id: 'd' as const, text: "Eleger o Presidente da República" }] },
  // Q60
  { textFr: "Qu'est-ce que l'Hôtel de Matignon ?", lang: 'pt' as const, text: "O que é o Hôtel de Matignon?", explanation: "O Hôtel de Matignon é a residência oficial e o local de trabalho do Primeiro-Ministro, localizado em Paris, no 7º arrondissement.", choices: [{ id: 'a' as const, text: "A residência oficial do Primeiro-Ministro" }, { id: 'b' as const, text: "A residência do Presidente da República" }, { id: 'c' as const, text: "A sede da Assembleia Nacional" }, { id: 'd' as const, text: "A sede do Conselho Constitucional" }] },
  // Q61
  { textFr: "Quel est le rôle du président de la République ?", lang: 'pt' as const, text: "Qual é o papel do Presidente da República?", explanation: "O Presidente da República zela pelo respeito à Constituição, assegura o funcionamento dos poderes públicos e a continuidade do Estado. Ele é o garante da independência nacional.", choices: [{ id: 'a' as const, text: "Zelar pelo respeito à Constituição e garantir a independência nacional" }, { id: 'b' as const, text: "Votar as leis no Parlamento" }, { id: 'c' as const, text: "Dirigir os tribunais" }, { id: 'd' as const, text: "Administrar os municípios" }] },
  // Q62
  { textFr: "Quel est le rôle du Premier ministre ?", lang: 'pt' as const, text: "Qual é o papel do Primeiro-Ministro?", explanation: "O Primeiro-Ministro dirige a ação do Governo. Ele é responsável perante a Assembleia Nacional e assegura a execução das leis.", choices: [{ id: 'a' as const, text: "Dirigir a ação do Governo" }, { id: 'b' as const, text: "Presidir o Conselho Constitucional" }, { id: 'c' as const, text: "Votar as leis" }, { id: 'd' as const, text: "Comandar os exércitos" }] },
  // Q63
  { textFr: "Qui est le chef du Gouvernement ?", lang: 'pt' as const, text: "Quem é o chefe do Governo?", explanation: "O Primeiro-Ministro é o chefe do Governo. Ele dirige a ação do Governo e coordena o trabalho dos ministros.", choices: [{ id: 'a' as const, text: "O Primeiro-Ministro" }, { id: 'b' as const, text: "O Presidente da República" }, { id: 'c' as const, text: "O presidente da Assembleia Nacional" }, { id: 'd' as const, text: "O Ministro do Interior" }] },
  // Q64
  { textFr: "Combien y a-t-il de régions en France ?", lang: 'pt' as const, text: "Quantas regiões existem na França?", explanation: "A França tem 18 regiões: 13 regiões metropolitanas (incluindo a Córsega) e 5 regiões ultramarinas.", choices: [{ id: 'a' as const, text: "18" }, { id: 'b' as const, text: "13" }, { id: 'c' as const, text: "22" }, { id: 'd' as const, text: "15" }] },
  // Q65
  { textFr: "Quel est le rôle du Défenseur des droits ?", lang: 'pt' as const, text: "Qual é o papel do Defensor dos Direitos?", explanation: "O Defensor dos Direitos é uma autoridade independente encarregada de zelar pelo respeito dos direitos e liberdades. Ele pode ser acionado por qualquer pessoa que se considere prejudicada por um serviço público.", choices: [{ id: 'a' as const, text: "Zelar pelo respeito dos direitos e liberdades dos cidadãos" }, { id: 'b' as const, text: "Votar as leis" }, { id: 'c' as const, text: "Comandar o exército" }, { id: 'd' as const, text: "Administrar o orçamento do Estado" }] },
  // Q66
  { textFr: "Depuis quand l'euro est-il la monnaie unique ?", lang: 'pt' as const, text: "Desde quando o euro é a moeda única?", explanation: "O euro se tornou a moeda única em circulação em 1º de janeiro de 2002. Ele havia sido introduzido como moeda escritural em 1999.", choices: [{ id: 'a' as const, text: "1º de janeiro de 2002" }, { id: 'b' as const, text: "1º de janeiro de 1999" }, { id: 'c' as const, text: "1º de janeiro de 1992" }, { id: 'd' as const, text: "1º de janeiro de 2005" }] },
  // Q67
  { textFr: "Quel est le rôle principal du département ?", lang: 'pt' as const, text: "Qual é o papel principal do departamento?", explanation: "O departamento tem como papel principal a ação social e a solidariedade (assistência social, RSA, proteção da infância). Ele também administra os colégios e as estradas departamentais.", choices: [{ id: 'a' as const, text: "A ação social e a solidariedade" }, { id: 'b' as const, text: "A defesa nacional" }, { id: 'c' as const, text: "A política externa" }, { id: 'd' as const, text: "A gestão das universidades" }] },
  // Q68
  { textFr: "Quel est le rôle principal des communes ?", lang: 'pt' as const, text: "Qual é o papel principal dos municípios?", explanation: "Os municípios administram os serviços de proximidade: registro civil, escolas maternais e primárias, urbanismo, vias municipais, água e saneamento.", choices: [{ id: 'a' as const, text: "Administrar os serviços de proximidade (registro civil, escolas, urbanismo)" }, { id: 'b' as const, text: "Organizar a defesa nacional" }, { id: 'c' as const, text: "Administrar os hospitais" }, { id: 'd' as const, text: "Cobrar os impostos nacionais" }] },
  // Q69
  { textFr: "Combien de communes environ existe-t-il en France ?", lang: 'pt' as const, text: "Quantos municípios aproximadamente existem na França?", explanation: "A França tem aproximadamente 35.000 municípios, o que a torna o país da Europa com o maior número de municípios.", choices: [{ id: 'a' as const, text: "Aproximadamente 35.000" }, { id: 'b' as const, text: "Aproximadamente 10.000" }, { id: 'c' as const, text: "Aproximadamente 5.000" }, { id: 'd' as const, text: "Aproximadamente 50.000" }] },
  // Q70
  { textFr: "Quel traité concerne la construction de l'Union européenne ?", lang: 'pt' as const, text: "Qual tratado diz respeito à construção da União Europeia?", explanation: "O Tratado de Maastricht (1992) é o tratado fundador da União Europeia. Ele instituiu a cidadania europeia e estabeleceu as bases da moeda única.", choices: [{ id: 'a' as const, text: "O Tratado de Maastricht" }, { id: 'b' as const, text: "O Tratado de Versalhes" }, { id: 'c' as const, text: "O Tratado de Vestfália" }, { id: 'd' as const, text: "O Tratado de Viena" }] },
  // Q71
  { textFr: "Quel État a quitté l'Union européenne en 2020 ?", lang: 'pt' as const, text: "Qual Estado deixou a União Europeia em 2020?", explanation: "O Reino Unido deixou a União Europeia em 31 de janeiro de 2020, após o referendo sobre o Brexit de 2016.", choices: [{ id: 'a' as const, text: "O Reino Unido" }, { id: 'b' as const, text: "A Noruega" }, { id: 'c' as const, text: "A Suíça" }, { id: 'd' as const, text: "A Islândia" }] },
  // Q72
  { textFr: "Quelle est la devise de l'Union européenne ?", lang: 'pt' as const, text: "Qual é o lema da União Europeia?", explanation: "O lema da União Europeia é \"Unida na diversidade\". Ele simboliza a unidade dos povos europeus no respeito às suas diferenças culturais.", choices: [{ id: 'a' as const, text: "Unida na diversidade" }, { id: 'b' as const, text: "Liberdade, Igualdade, Fraternidade" }, { id: 'c' as const, text: "Paz e prosperidade" }, { id: 'd' as const, text: "A união faz a força" }] },
  // Q73
  { textFr: "Quel est l'hymne de l'Union européenne ?", lang: 'pt' as const, text: "Qual é o hino da União Europeia?", explanation: "O hino da União Europeia é a Ode à Alegria, extraída da 9ª sinfonia de Ludwig van Beethoven. Foi adotado pelo Conselho da Europa em 1972.", choices: [{ id: 'a' as const, text: "A Ode à Alegria de Beethoven" }, { id: 'b' as const, text: "A Marselhesa" }, { id: 'c' as const, text: "O Bolero de Ravel" }, { id: 'd' as const, text: "As Quatro Estações de Vivaldi" }] },
  // Q74
  { textFr: "De quoi est composé le drapeau européen ?", lang: 'pt' as const, text: "Do que é composta a bandeira europeia?", explanation: "A bandeira europeia é composta por 12 estrelas douradas dispostas em círculo sobre fundo azul. O número 12 simboliza a perfeição e a unidade, não corresponde ao número de Estados-membros.", choices: [{ id: 'a' as const, text: "12 estrelas douradas dispostas em círculo sobre fundo azul" }, { id: 'b' as const, text: "27 estrelas sobre fundo azul" }, { id: 'c' as const, text: "Faixas horizontais azuis e brancas" }, { id: 'd' as const, text: "15 estrelas douradas sobre fundo vermelho" }] },
  // Q75
  { textFr: "De quelle couleur est le drapeau européen ?", lang: 'pt' as const, text: "De que cor é a bandeira europeia?", explanation: "A bandeira europeia é azul com estrelas douradas (amarelas). O fundo azul representa o céu e as estrelas simbolizam a unidade dos povos da Europa.", choices: [{ id: 'a' as const, text: "Azul com estrelas douradas" }, { id: 'b' as const, text: "Vermelho com estrelas brancas" }, { id: 'c' as const, text: "Verde com estrelas douradas" }, { id: 'd' as const, text: "Branco com estrelas azuis" }] },
  // Q76
  { textFr: "En quelle année le traité de Maastricht a-t-il été signé ?", lang: 'pt' as const, text: "Em que ano o Tratado de Maastricht foi assinado?", explanation: "O Tratado de Maastricht foi assinado em 7 de fevereiro de 1992. Ele criou a União Europeia e estabeleceu as bases da moeda única (o euro).", choices: [{ id: 'a' as const, text: "1992" }, { id: 'b' as const, text: "1957" }, { id: 'c' as const, text: "1989" }, { id: 'd' as const, text: "2000" }] },
  // Q77
  { textFr: "Où est le siège du Parlement européen ?", lang: 'pt' as const, text: "Onde fica a sede do Parlamento Europeu?", explanation: "A sede do Parlamento Europeu fica em Estrasburgo (França). Sessões também acontecem em Bruxelas (Bélgica).", choices: [{ id: 'a' as const, text: "Em Estrasburgo" }, { id: 'b' as const, text: "Em Bruxelas" }, { id: 'c' as const, text: "Em Luxemburgo" }, { id: 'd' as const, text: "Em Berlim" }] },
  // Q78
  { textFr: "Où est le siège de la Commission européenne ?", lang: 'pt' as const, text: "Onde fica a sede da Comissão Europeia?", explanation: "A sede da Comissão Europeia fica em Bruxelas (Bélgica). A Comissão é o órgão executivo da União Europeia.", choices: [{ id: 'a' as const, text: "Em Bruxelas" }, { id: 'b' as const, text: "Em Estrasburgo" }, { id: 'c' as const, text: "Em Luxemburgo" }, { id: 'd' as const, text: "Em Paris" }] },
  // Q79
  { textFr: "Comment est désigné le Premier ministre ?", lang: 'pt' as const, text: "Como é designado o Primeiro-Ministro?", explanation: "O Primeiro-Ministro é nomeado pelo Presidente da República. Ele não é eleito diretamente pelos cidadãos.", choices: [{ id: 'a' as const, text: "Ele é nomeado pelo Presidente da República" }, { id: 'b' as const, text: "Ele é eleito por sufrágio universal direto" }, { id: 'c' as const, text: "Ele é eleito pelos deputados" }, { id: 'd' as const, text: "Ele é designado pelo Conselho Constitucional" }] },
  // Q80
  { textFr: "Qui peut se présenter aux élections présidentielles ?", lang: 'pt' as const, text: "Quem pode se candidatar às eleições presidenciais?", explanation: "Todo cidadão francês com pelo menos 18 anos e no gozo de seus direitos civis e políticos pode se candidatar, desde que obtenha 500 patrocínios de eleitos.", choices: [{ id: 'a' as const, text: "Todo cidadão francês que tenha obtido 500 patrocínios de eleitos" }, { id: 'b' as const, text: "Apenas os membros de um partido político" }, { id: 'c' as const, text: "Apenas os ex-ministros" }, { id: 'd' as const, text: "Apenas as pessoas com mais de 40 anos" }] },
  // Q81
  { textFr: "À qui appartient la souveraineté nationale ?", lang: 'pt' as const, text: "A quem pertence a soberania nacional?", explanation: "A soberania nacional pertence ao povo, que a exerce por seus representantes e pela via do referendo (artigo 3 da Constituição).", choices: [{ id: 'a' as const, text: "Ao povo" }, { id: 'b' as const, text: "Ao Presidente da República" }, { id: 'c' as const, text: "Ao Parlamento" }, { id: 'd' as const, text: "Ao Governo" }] },
  // Q82
  { textFr: "L'inscription sur les listes électorales est :", lang: 'pt' as const, text: "A inscrição nas listas eleitorais é:", explanation: "A inscrição nas listas eleitorais é obrigatória para todo cidadão francês maior de idade. Desde 2019, a inscrição é automática aos 18 anos.", choices: [{ id: 'a' as const, text: "Obrigatória" }, { id: 'b' as const, text: "Facultativa" }, { id: 'c' as const, text: "Automática apenas para os homens" }, { id: 'd' as const, text: "Reservada às pessoas com mais de 21 anos" }] },
  // Q83
  { textFr: "Quelle condition est nécessaire pour voter aux élections présidentielles ?", lang: 'pt' as const, text: "Que condição é necessária para votar nas eleições presidenciais?", explanation: "Para votar nas eleições presidenciais, é necessário ter nacionalidade francesa, ter 18 anos completos, gozar de seus direitos civis e políticos e estar inscrito nas listas eleitorais.", choices: [{ id: 'a' as const, text: "Ter nacionalidade francesa, ser maior de idade e estar inscrito nas listas eleitorais" }, { id: 'b' as const, text: "Ser residente na França há pelo menos 5 anos" }, { id: 'c' as const, text: "Ter a ficha criminal limpa" }, { id: 'd' as const, text: "Ser titular de um diploma" }] },
  // Q84
  { textFr: "Quelle condition faut-il remplir pour être candidat aux élections municipales ?", lang: 'pt' as const, text: "Que condição é preciso preencher para ser candidato às eleições municipais?", explanation: "Para ser candidato às eleições municipais, é necessário ter 18 anos completos, ter nacionalidade francesa ou ser cidadão da UE, e estar inscrito nas listas eleitorais do município ou pagar impostos nele.", choices: [{ id: 'a' as const, text: "Ter 18 anos e estar inscrito nas listas eleitorais do município" }, { id: 'b' as const, text: "Ter 25 anos e residir no município há 10 anos" }, { id: 'c' as const, text: "Ser funcionário público" }, { id: 'd' as const, text: "Ser proprietário no município" }] },
  // Q85
  { textFr: "Parmi ces autorités, laquelle est élue ?", lang: 'pt' as const, text: "Entre estas autoridades, qual é eleita?", explanation: "O maire é eleito pelos conselheiros municipais. O prefeito é nomeado, o procurador é um magistrado e o diretor de escola é um funcionário público.", choices: [{ id: 'a' as const, text: "O maire" }, { id: 'b' as const, text: "O prefeito" }, { id: 'c' as const, text: "O procurador da República" }, { id: 'd' as const, text: "O diretor de escola" }] },
  // Q86
  { textFr: "Quelles sont les fonctions du maire ?", lang: 'pt' as const, text: "Quais são as funções do maire?", explanation: "O maire é ao mesmo tempo oficial de registro civil, representante do Estado no município e chefe da administração municipal. Ele celebra casamentos e emite alvarás de construção.", choices: [{ id: 'a' as const, text: "Oficial de registro civil, representante do Estado e chefe da administração municipal" }, { id: 'b' as const, text: "Chefe da polícia nacional e dos bombeiros" }, { id: 'c' as const, text: "Presidente do tribunal do município" }, { id: 'd' as const, text: "Responsável pela educação nacional no município" }] },
  // Q87
  { textFr: "Une personne n'ayant pas d'accès à internet veut s'inscrire sur les listes électorales. Où peut-elle s'inscrire ?", lang: 'pt' as const, text: "Uma pessoa sem acesso à internet quer se inscrever nas listas eleitorais. Onde ela pode se inscrever?", explanation: "Uma pessoa pode se inscrever nas listas eleitorais indo à prefeitura municipal de seu domicílio. A inscrição online não é a única opção.", choices: [{ id: 'a' as const, text: "Na prefeitura municipal de seu domicílio" }, { id: 'b' as const, text: "Apenas na prefeitura departamental" }, { id: 'c' as const, text: "Na delegacia de polícia" }, { id: 'd' as const, text: "No tribunal judiciário" }] },
  // Q88
  { textFr: "À quel âge peut-on devenir électeur ?", lang: 'pt' as const, text: "Com que idade é possível se tornar eleitor?", explanation: "É possível se tornar eleitor aos 18 anos na França. É a idade da maioridade civil e política desde 1974.", choices: [{ id: 'a' as const, text: "18 anos" }, { id: 'b' as const, text: "16 anos" }, { id: 'c' as const, text: "21 anos" }, { id: 'd' as const, text: "25 anos" }] },
  // Q89
  { textFr: "En France, est-ce obligatoire de voter ?", lang: 'pt' as const, text: "Na França, é obrigatório votar?", explanation: "Não, o voto não é obrigatório na França. É um direito e um dever cívico, mas não há sanção em caso de abstenção.", choices: [{ id: 'a' as const, text: "Não, o voto é um direito, mas não uma obrigação legal" }, { id: 'b' as const, text: "Sim, sob pena de multa" }, { id: 'c' as const, text: "Sim, sob pena de prisão" }, { id: 'd' as const, text: "Sim, exceto para pessoas com mais de 70 anos" }] },
  // Q90
  { textFr: "Comment sont désignés les députés ?", lang: 'pt' as const, text: "Como são designados os deputados?", explanation: "Os deputados são eleitos por sufrágio universal direto pelos cidadãos franceses. Cada deputado representa uma circunscrição legislativa.", choices: [{ id: 'a' as const, text: "Eles são eleitos por sufrágio universal direto" }, { id: 'b' as const, text: "Eles são nomeados pelo Presidente da República" }, { id: 'c' as const, text: "Eles são eleitos pelos senadores" }, { id: 'd' as const, text: "Eles são designados pelos partidos políticos" }] },
  // Q91
  { textFr: "En France, est-ce possible d'adhérer à un parti politique ?", lang: 'pt' as const, text: "Na França, é possível filiar-se a um partido político?", explanation: "Sim, na França, qualquer pessoa pode livremente filiar-se ao partido político de sua escolha. A liberdade de associação e o pluralismo político são garantidos pela Constituição.", choices: [{ id: 'a' as const, text: "Sim, é possível filiar-se livremente ao partido de sua escolha" }, { id: 'b' as const, text: "Não, os partidos políticos são proibidos" }, { id: 'c' as const, text: "Sim, mas apenas se for cidadão francês" }, { id: 'd' as const, text: "Não, apenas os eleitos podem filiar-se a um partido" }] },
  // Q92
  { textFr: "Qui gère les collèges publics ?", lang: 'pt' as const, text: "Quem administra os colégios públicos?", explanation: "Os colégios públicos são administrados pelo departamento. A construção, a manutenção e o funcionamento dos colégios são de competência do conselho departamental.", choices: [{ id: 'a' as const, text: "O departamento" }, { id: 'b' as const, text: "O município" }, { id: 'c' as const, text: "A região" }, { id: 'd' as const, text: "O Estado diretamente" }] },
  // Q93
  { textFr: "Qui gère les écoles primaires et maternelles publiques ?", lang: 'pt' as const, text: "Quem administra as escolas primárias e maternais públicas?", explanation: "As escolas primárias e maternais públicas são administradas pelo município. O município assegura a construção, a manutenção e o funcionamento dos prédios escolares.", choices: [{ id: 'a' as const, text: "O município" }, { id: 'b' as const, text: "O departamento" }, { id: 'c' as const, text: "A região" }, { id: 'd' as const, text: "O Ministério da Educação Nacional" }] },
  // Q94
  { textFr: "Comment sont désignés les maires ?", lang: 'pt' as const, text: "Como são designados os maires?", explanation: "Os maires são eleitos pelos conselheiros municipais na primeira sessão do novo conselho municipal, após as eleições municipais.", choices: [{ id: 'a' as const, text: "Eles são eleitos pelos conselheiros municipais" }, { id: 'b' as const, text: "Eles são eleitos diretamente pelos cidadãos" }, { id: 'c' as const, text: "Eles são nomeados pelo prefeito" }, { id: 'd' as const, text: "Eles são designados pelo Presidente da República" }] },
  // Q95
  { textFr: "Quelle collectivité territoriale est responsable des transports régionaux ?", lang: 'pt' as const, text: "Qual coletividade territorial é responsável pelos transportes regionais?", explanation: "A região é responsável pelos transportes regionais (TER). Ela organiza e financia os serviços de transporte ferroviário regional de passageiros.", choices: [{ id: 'a' as const, text: "A região" }, { id: 'b' as const, text: "O departamento" }, { id: 'c' as const, text: "O município" }, { id: 'd' as const, text: "O Estado" }] },
  // Q96
  { textFr: "Quelle est l'une des voies possibles pour modifier la Constitution ?", lang: 'pt' as const, text: "Qual é uma das vias possíveis para modificar a Constituição?", explanation: "A Constituição pode ser modificada por referendo ou pelo Congresso (reunião da Assembleia Nacional e do Senado) por maioria de 3/5 dos votos expressos.", choices: [{ id: 'a' as const, text: "Por referendo ou pelo Congresso (Assembleia Nacional + Senado)" }, { id: 'b' as const, text: "Por decisão do Presidente da República sozinho" }, { id: 'c' as const, text: "Por um voto dos maires da França" }, { id: 'd' as const, text: "Por uma decisão do Conselho Constitucional" }] },
  // Q97
  { textFr: "Qui assure l'intérim du président de la République en cas de décès ?", lang: 'pt' as const, text: "Quem assegura o interino do Presidente da República em caso de falecimento?", explanation: "O presidente do Senado assegura o interino do Presidente da República em caso de vacância (falecimento, demissão). Está previsto no artigo 7 da Constituição.", choices: [{ id: 'a' as const, text: "O presidente do Senado" }, { id: 'b' as const, text: "O Primeiro-Ministro" }, { id: 'c' as const, text: "O presidente da Assembleia Nacional" }, { id: 'd' as const, text: "O Ministro do Interior" }] },
  // Q98
  { textFr: "Quel est le rôle du Conseil constitutionnel ?", lang: 'pt' as const, text: "Qual é o papel do Conselho Constitucional?", explanation: "O Conselho Constitucional verifica a conformidade das leis com a Constituição. Ele também zela pela regularidade das eleições presidenciais e dos referendos.", choices: [{ id: 'a' as const, text: "Verificar a conformidade das leis com a Constituição" }, { id: 'b' as const, text: "Votar as leis" }, { id: 'c' as const, text: "Dirigir o Governo" }, { id: 'd' as const, text: "Julgar os casos penais" }] },
  // Q99
  { textFr: "Quelle condition est obligatoire pour se présenter à l'élection présidentielle ?", lang: 'pt' as const, text: "Que condição é obrigatória para se candidatar à eleição presidencial?", explanation: "Para se candidatar à eleição presidencial, é necessário obter 500 assinaturas (patrocínios) de eleitos provenientes de pelo menos 30 departamentos ou coletividades ultramarinas diferentes.", choices: [{ id: 'a' as const, text: "Obter 500 patrocínios de eleitos" }, { id: 'b' as const, text: "Ser membro de um partido político" }, { id: 'c' as const, text: "Ter sido deputado ou senador" }, { id: 'd' as const, text: "Ter mais de 40 anos" }] },
  // Q100
  { textFr: "Comment est organisé le découpage administratif de la France ?", lang: 'pt' as const, text: "Como é organizada a divisão administrativa da França?", explanation: "A divisão administrativa da França é organizada em municípios, departamentos e regiões. Esses três níveis de coletividades territoriais se administram livremente.", choices: [{ id: 'a' as const, text: "Em municípios, departamentos e regiões" }, { id: 'b' as const, text: "Em províncias, cantões e distritos" }, { id: 'c' as const, text: "Em cidades, condados e Estados federados" }, { id: 'd' as const, text: "Em arrondissements e prefeituras apenas" }] },
  // Q101
  { textFr: "En quelle année la citoyenneté européenne a-t-elle été créée ?", lang: 'pt' as const, text: "Em que ano a cidadania europeia foi criada?", explanation: "A cidadania europeia foi criada pelo Tratado de Maastricht em 1992. Ela confere aos cidadãos da UE direitos como a livre circulação e o direito de voto nas eleições municipais e europeias em qualquer Estado-membro.", choices: [{ id: 'a' as const, text: "1992" }, { id: 'b' as const, text: "1957" }, { id: 'c' as const, text: "2000" }, { id: 'd' as const, text: "1985" }] },
  // Q102
  { textFr: "Qui a composé l'hymne de l'Union européenne ?", lang: 'pt' as const, text: "Quem compôs o hino da União Europeia?", explanation: "O hino europeu é a Ode à Alegria, composta por Ludwig van Beethoven. É o último movimento de sua 9ª sinfonia.", choices: [{ id: 'a' as const, text: "Ludwig van Beethoven" }, { id: 'b' as const, text: "Wolfgang Amadeus Mozart" }, { id: 'c' as const, text: "Johann Sebastian Bach" }, { id: 'd' as const, text: "Claude Debussy" }] },
  // Q103
  { textFr: "Où est le siège de la Banque centrale européenne ?", lang: 'pt' as const, text: "Onde fica a sede do Banco Central Europeu?", explanation: "A sede do Banco Central Europeu (BCE) fica em Frankfurt am Main, na Alemanha. O BCE é responsável pela política monetária da zona do euro.", choices: [{ id: 'a' as const, text: "Em Frankfurt (Alemanha)" }, { id: 'b' as const, text: "Em Bruxelas (Bélgica)" }, { id: 'c' as const, text: "Em Luxemburgo" }, { id: 'd' as const, text: "Em Paris (França)" }] },
  // Q104
  { textFr: "Qui siège au Parlement européen ?", lang: 'pt' as const, text: "Quem atua no Parlamento Europeu?", explanation: "Os deputados europeus atuam no Parlamento Europeu. Eles são eleitos por sufrágio universal direto pelos cidadãos dos Estados-membros da UE.", choices: [{ id: 'a' as const, text: "Os deputados europeus eleitos pelos cidadãos da UE" }, { id: 'b' as const, text: "Os chefes de Estado dos países membros" }, { id: 'c' as const, text: "Os ministros das Relações Exteriores" }, { id: 'd' as const, text: "Os embaixadores dos países membros" }] },
];
