export const theme2Hi = [
  // Q1
  { textFr: "Qui nomme le Premier ministre ?", lang: 'hi' as const, text: "प्रधानमंत्री की नियुक्ति कौन करता है?", explanation: "प्रधानमंत्री की नियुक्ति गणराज्य के राष्ट्रपति द्वारा की जाती है। यह 1958 के संविधान के अनुच्छेद 8 द्वारा परिभाषित एक संवैधानिक विशेषाधिकार है।", choices: [{ id: 'a' as const, text: "गणराज्य के राष्ट्रपति" }, { id: 'b' as const, text: "राष्ट्रीय सभा" }, { id: 'c' as const, text: "सीनेट" }, { id: 'd' as const, text: "संवैधानिक परिषद" }] },
  // Q2
  { textFr: "Le Parlement est composé :", lang: 'hi' as const, text: "संसद किससे बनी है:", explanation: "फ्रांसीसी संसद द्विसदनीय है। यह राष्ट्रीय सभा और सीनेट से बनी है, जो कानून बनाती हैं और सरकार की कार्रवाई पर नियंत्रण रखती हैं।", choices: [{ id: 'a' as const, text: "राष्ट्रीय सभा और सीनेट" }, { id: 'b' as const, text: "सीनेट और संवैधानिक परिषद" }, { id: 'c' as const, text: "राष्ट्रीय सभा और सरकार" }, { id: 'd' as const, text: "राज्य परिषद और राष्ट्रीय सभा" }] },
  // Q3
  { textFr: "Qu'est-ce que le pouvoir exécutif ? Le pouvoir :", lang: 'hi' as const, text: "कार्यकारी शक्ति क्या है? यह शक्ति:", explanation: "कार्यकारी शक्ति कानूनों को लागू करने की शक्ति है। फ्रांस में, यह गणराज्य के राष्ट्रपति और सरकार द्वारा प्रयोग की जाती है।", choices: [{ id: 'a' as const, text: "कानूनों को लागू करने की" }, { id: 'b' as const, text: "कानून बनाने की" }, { id: 'c' as const, text: "अपराधों पर निर्णय लेने की" }, { id: 'd' as const, text: "संविधान में संशोधन करने की" }] },
  // Q4
  { textFr: "Les dirigeants sont élus par les citoyens dans :", lang: 'hi' as const, text: "नेता नागरिकों द्वारा चुने जाते हैं:", explanation: "लोकतंत्र में, नेता स्वतंत्र चुनावों के दौरान नागरिकों द्वारा चुने जाते हैं। यह लोकतांत्रिक शासन का मूल सिद्धांत है।", choices: [{ id: 'a' as const, text: "लोकतंत्र में" }, { id: 'b' as const, text: "तानाशाही में" }, { id: 'c' as const, text: "निरंकुश राजतंत्र में" }, { id: 'd' as const, text: "कुलीनतंत्र में" }] },
  // Q5
  { textFr: "A-t-on le droit de ne pas respecter une loi ?", lang: 'hi' as const, text: "क्या किसी कानून का पालन न करने का अधिकार है?", explanation: "नहीं, किसी को भी कानून का पालन न करने का अधिकार नहीं है। कानून सभी पर समान रूप से लागू होता है। कानून की अनभिज्ञता कोई बहाना नहीं है।", choices: [{ id: 'a' as const, text: "नहीं, कभी नहीं" }, { id: 'b' as const, text: "हाँ, यदि कानून से सहमत न हों" }, { id: 'c' as const, text: "हाँ, यदि विदेशी हों" }, { id: 'd' as const, text: "हाँ, कुछ व्यक्तिगत परिस्थितियों में" }] },
  // Q6
  { textFr: "Qui doit respecter la loi ?", lang: 'hi' as const, text: "कानून का पालन किसे करना चाहिए?", explanation: "फ्रांस में सभी को बिना किसी अपवाद के कानून का पालन करना चाहिए। यह सिद्धांत नागरिकों, विदेशियों, निर्वाचित प्रतिनिधियों और नेताओं पर लागू होता है।", choices: [{ id: 'a' as const, text: "सभी को" }, { id: 'b' as const, text: "केवल फ्रांसीसी नागरिकों को" }, { id: 'c' as const, text: "केवल वयस्कों को" }, { id: 'd' as const, text: "केवल फ्रांस में रहने वालों को" }] },
  // Q7
  { textFr: "Quel est le rôle de l'autorité judiciaire ?", lang: 'hi' as const, text: "न्यायिक प्राधिकरण की भूमिका क्या है?", explanation: "न्यायिक प्राधिकरण की भूमिका कानूनों के पालन की निगरानी करना और उनके उल्लंघन को दंडित करना है। यह व्यक्तिगत स्वतंत्रताओं की रक्षा करता है।", choices: [{ id: 'a' as const, text: "कानूनों के पालन की निगरानी करना और उनके उल्लंघन को दंडित करना" }, { id: 'b' as const, text: "कानून बनाना" }, { id: 'c' as const, text: "नए कानूनों का प्रस्ताव करना" }, { id: 'd' as const, text: "मंत्रियों की नियुक्ति करना" }] },
  // Q8
  { textFr: "Quel pouvoir détient un juge ? Le pouvoir :", lang: 'hi' as const, text: "न्यायाधीश के पास कौन सी शक्ति होती है? यह शक्ति:", explanation: "न्यायाधीश के पास न्यायिक शक्ति होती है। वह कानूनों को लागू करके और अपराधों को दंडित करके न्याय करता है।", choices: [{ id: 'a' as const, text: "न्यायिक" }, { id: 'b' as const, text: "कार्यकारी" }, { id: 'c' as const, text: "विधायी" }, { id: 'd' as const, text: "प्रशासनिक" }] },
  // Q9
  { textFr: "L'autorité judiciaire est exercée par :", lang: 'hi' as const, text: "न्यायिक प्राधिकरण का प्रयोग किसके द्वारा किया जाता है:", explanation: "न्यायिक प्राधिकरण का प्रयोग मजिस्ट्रेटों और न्यायाधीशों द्वारा किया जाता है। वे कार्यकारी और विधायी शक्ति से स्वतंत्र हैं।", choices: [{ id: 'a' as const, text: "मजिस्ट्रेट और न्यायाधीश" }, { id: 'b' as const, text: "सांसद" }, { id: 'c' as const, text: "मंत्री" }, { id: 'd' as const, text: "प्रीफेक्ट" }] },
  // Q10
  { textFr: "Que se passe-t-il si un ministre ne respecte pas la loi ?", lang: 'hi' as const, text: "यदि कोई मंत्री कानून का पालन नहीं करता तो क्या होता है?", explanation: "कानून का पालन न करने वाले मंत्री पर किसी भी नागरिक की तरह मुकदमा चलाया जा सकता है। कोई भी कानून से ऊपर नहीं है, सरकार के सदस्य भी नहीं।", choices: [{ id: 'a' as const, text: "उस पर किसी भी नागरिक की तरह मुकदमा चलाया जा सकता है" }, { id: 'b' as const, text: "मंत्री होने के कारण उस पर मुकदमा नहीं चलाया जा सकता" }, { id: 'c' as const, text: "उसे केवल सरकार से बर्खास्त किया जाता है" }, { id: 'd' as const, text: "उसे आजीवन मंत्रिपदीय प्रतिरक्षा प्राप्त है" }] },
  // Q11
  { textFr: "Qui est élu lors des élections législatives ?", lang: 'hi' as const, text: "विधानसभा चुनावों में कौन चुना जाता है?", explanation: "विधानसभा चुनावों में सांसद (डेप्युटी) चुने जाते हैं। वे राष्ट्रीय सभा में बैठते हैं और कानून बनाते हैं।", choices: [{ id: 'a' as const, text: "सांसद (डेप्युटी)" }, { id: 'b' as const, text: "सीनेटर" }, { id: 'c' as const, text: "मेयर" }, { id: 'd' as const, text: "क्षेत्रीय पार्षद" }] },
  // Q12
  { textFr: "Combien de députés composent l'Assemblée nationale ?", lang: 'hi' as const, text: "राष्ट्रीय सभा में कितने सांसद हैं?", explanation: "राष्ट्रीय सभा 577 सांसदों से बनी है। वे 5 वर्ष के कार्यकाल के लिए प्रत्यक्ष सार्वभौमिक मताधिकार द्वारा चुने जाते हैं।", choices: [{ id: 'a' as const, text: "577" }, { id: 'b' as const, text: "348" }, { id: 'c' as const, text: "500" }, { id: 'd' as const, text: "650" }] },
  // Q13
  { textFr: "Quand sont élus les sénateurs ?", lang: 'hi' as const, text: "सीनेटर कब चुने जाते हैं?", explanation: "सीनेटर महान निर्वाचकों द्वारा अप्रत्यक्ष सार्वभौमिक मताधिकार से चुने जाते हैं। सीनेट का हर 3 साल में आधा नवीनीकरण होता है।", choices: [{ id: 'a' as const, text: "वे अप्रत्यक्ष सार्वभौमिक मताधिकार से चुने जाते हैं" }, { id: 'b' as const, text: "वे प्रत्यक्ष सार्वभौमिक मताधिकार से चुने जाते हैं" }, { id: 'c' as const, text: "उन्हें गणराज्य के राष्ट्रपति द्वारा नामित किया जाता है" }, { id: 'd' as const, text: "उन्हें सांसदों द्वारा नामित किया जाता है" }] },
  // Q14
  { textFr: "Qui est élu lors des élections municipales ?", lang: 'hi' as const, text: "नगरपालिका चुनावों में कौन चुना जाता है?", explanation: "नगरपालिका चुनावों में नगर पार्षद चुने जाते हैं। फिर वे अपने बीच से मेयर का चुनाव करते हैं।", choices: [{ id: 'a' as const, text: "नगर पार्षद" }, { id: 'b' as const, text: "सीधे मेयर" }, { id: 'c' as const, text: "विभागीय पार्षद" }, { id: 'd' as const, text: "सांसद" }] },
  // Q15
  { textFr: "Qui est élu lors des élections présidentielles ?", lang: 'hi' as const, text: "राष्ट्रपति चुनाव में कौन चुना जाता है?", explanation: "गणराज्य के राष्ट्रपति राष्ट्रपति चुनाव में चुने जाते हैं, 1962 से प्रत्यक्ष सार्वभौमिक मताधिकार द्वारा।", choices: [{ id: 'a' as const, text: "गणराज्य के राष्ट्रपति" }, { id: 'b' as const, text: "प्रधानमंत्री" }, { id: 'c' as const, text: "सांसद" }, { id: 'd' as const, text: "सीनेटर" }] },
  // Q16
  { textFr: "À partir de quel âge a-t-on le droit de voter ?", lang: 'hi' as const, text: "किस उम्र से मतदान का अधिकार मिलता है?", explanation: "फ्रांस में 18 वर्ष की आयु से मतदान का अधिकार दिया जाता है। यह नागरिक और राजनीतिक वयस्कता की आयु है।", choices: [{ id: 'a' as const, text: "18 वर्ष" }, { id: 'b' as const, text: "16 वर्ष" }, { id: 'c' as const, text: "21 वर्ष" }, { id: 'd' as const, text: "25 वर्ष" }] },
  // Q17
  { textFr: "Pour combien de temps est élu le président de la République française ?", lang: 'hi' as const, text: "फ्रांसीसी गणराज्य के राष्ट्रपति कितने समय के लिए चुने जाते हैं?", explanation: "गणराज्य के राष्ट्रपति 2000 के संवैधानिक सुधार के बाद से 5 वर्ष (पंचवर्षीय कार्यकाल) के लिए चुने जाते हैं।", choices: [{ id: 'a' as const, text: "5 वर्ष" }, { id: 'b' as const, text: "7 वर्ष" }, { id: 'c' as const, text: "4 वर्ष" }, { id: 'd' as const, text: "6 वर्ष" }] },
  // Q18
  { textFr: "Pour combien de temps sont élus les députés ?", lang: 'hi' as const, text: "सांसद कितने समय के लिए चुने जाते हैं?", explanation: "सांसद 5 वर्ष के कार्यकाल के लिए चुने जाते हैं। राष्ट्रपति द्वारा कार्यकाल समाप्त होने से पहले राष्ट्रीय सभा को भंग किया जा सकता है।", choices: [{ id: 'a' as const, text: "5 वर्ष" }, { id: 'b' as const, text: "6 वर्ष" }, { id: 'c' as const, text: "4 वर्ष" }, { id: 'd' as const, text: "7 वर्ष" }] },
  // Q19
  { textFr: "Pour combien de temps sont élus les sénateurs ?", lang: 'hi' as const, text: "सीनेटर कितने समय के लिए चुने जाते हैं?", explanation: "सीनेटर 6 वर्ष के कार्यकाल के लिए चुने जाते हैं। सीनेट का हर 3 साल में आधा नवीनीकरण होता है।", choices: [{ id: 'a' as const, text: "6 वर्ष" }, { id: 'b' as const, text: "5 वर्ष" }, { id: 'c' as const, text: "4 वर्ष" }, { id: 'd' as const, text: "7 वर्ष" }] },
  // Q20
  { textFr: "Qui possède le pouvoir exécutif ?", lang: 'hi' as const, text: "कार्यकारी शक्ति किसके पास है?", explanation: "कार्यकारी शक्ति गणराज्य के राष्ट्रपति और सरकार के पास है। वे संसद द्वारा पारित कानूनों को लागू करते हैं।", choices: [{ id: 'a' as const, text: "गणराज्य के राष्ट्रपति और सरकार" }, { id: 'b' as const, text: "संसद" }, { id: 'c' as const, text: "न्यायाधीश" }, { id: 'd' as const, text: "संवैधानिक परिषद" }] },
  // Q21
  { textFr: "Quelle condition est nécessaire pour voter aux élections ?", lang: 'hi' as const, text: "चुनावों में मतदान के लिए कौन सी शर्त आवश्यक है?", explanation: "फ्रांस में चुनावों में मतदान करने के लिए मतदाता सूची में पंजीकृत होना आवश्यक है। पंजीकरण एक अनिवार्य पूर्व शर्त है।", choices: [{ id: 'a' as const, text: "मतदाता सूची में पंजीकृत होना" }, { id: 'b' as const, text: "फ्रांस में नौकरी होना" }, { id: 'c' as const, text: "अचल संपत्ति का मालिक होना" }, { id: 'd' as const, text: "फ्रांसीसी डिप्लोमा होना" }] },
  // Q22
  { textFr: "Qui peut voter aux élections en France ?", lang: 'hi' as const, text: "फ्रांस में चुनावों में कौन मतदान कर सकता है?", explanation: "वयस्क (18 वर्ष और अधिक) फ्रांसीसी नागरिक जो अपने नागरिक और राजनीतिक अधिकारों का उपभोग करते हैं, फ्रांस में चुनावों में मतदान कर सकते हैं।", choices: [{ id: 'a' as const, text: "वयस्क फ्रांसीसी नागरिक" }, { id: 'b' as const, text: "फ्रांस में रहने वाला कोई भी व्यक्ति" }, { id: 'c' as const, text: "निवास परमिट वाले व्यक्ति" }, { id: 'd' as const, text: "21 वर्ष से अधिक आयु के व्यक्ति" }] },
  // Q23
  { textFr: "Que signifie « suffrage universel » ?", lang: 'hi' as const, text: "\"सार्वभौमिक मताधिकार\" का क्या अर्थ है?", explanation: "सार्वभौमिक मताधिकार का अर्थ है कि सभी वयस्क नागरिकों को लिंग, धन या मूल की भेदभाव के बिना मतदान का अधिकार है।", choices: [{ id: 'a' as const, text: "सभी वयस्क नागरिकों को मतदान का अधिकार है" }, { id: 'b' as const, text: "केवल पुरुषों को मतदान का अधिकार है" }, { id: 'c' as const, text: "मतदान सभी के लिए अनिवार्य है" }, { id: 'd' as const, text: "केवल संपत्ति मालिक मतदान कर सकते हैं" }] },
  // Q24
  { textFr: "Concernant les partis politiques, quelle proposition est correcte ?", lang: 'hi' as const, text: "राजनीतिक दलों के बारे में कौन सा कथन सही है?", explanation: "फ्रांस में कई राजनीतिक दल हैं और कोई भी अपनी पसंद के दल में स्वतंत्र रूप से शामिल हो सकता है। बहुदलीय व्यवस्था लोकतंत्र का मूल सिद्धांत है।", choices: [{ id: 'a' as const, text: "कई राजनीतिक दल हैं और कोई भी अपनी पसंद के दल में शामिल हो सकता है" }, { id: 'b' as const, text: "फ्रांस में केवल एक राजनीतिक दल है" }, { id: 'c' as const, text: "राजनीतिक दल प्रतिबंधित हैं" }, { id: 'd' as const, text: "केवल सरकारी कर्मचारी किसी दल में शामिल हो सकते हैं" }] },
  // Q25
  { textFr: "Quel est le rôle des députés ?", lang: 'hi' as const, text: "सांसदों की भूमिका क्या है?", explanation: "सांसद कानून बनाते हैं और सरकार की कार्रवाई पर नियंत्रण रखते हैं। वे राष्ट्रीय सभा में जनता का प्रतिनिधित्व करते हैं।", choices: [{ id: 'a' as const, text: "कानून बनाना और सरकार की कार्रवाई पर नियंत्रण रखना" }, { id: 'b' as const, text: "सरकार का नेतृत्व करना" }, { id: 'c' as const, text: "न्यायाधीशों की नियुक्ति करना" }, { id: 'd' as const, text: "नगरपालिकाओं का प्रबंधन करना" }] },
  // Q26
  { textFr: "La séparation des pouvoirs est un principe fondamental. Quels sont les trois pouvoirs concernés ?", lang: 'hi' as const, text: "शक्तियों का पृथक्करण एक मौलिक सिद्धांत है। तीन संबंधित शक्तियाँ कौन सी हैं?", explanation: "तीन शक्तियाँ हैं: विधायी शक्ति (कानून बनाना), कार्यकारी शक्ति (कानून लागू करना) और न्यायिक शक्ति (न्याय करना)। यह सिद्धांत लोकतंत्र की गारंटी देता है।", choices: [{ id: 'a' as const, text: "विधायी, कार्यकारी, न्यायिक" }, { id: 'b' as const, text: "राष्ट्रपति, संसदीय, न्यायिक" }, { id: 'c' as const, text: "नगरपालिका, विभागीय, क्षेत्रीय" }, { id: 'd' as const, text: "सैन्य, नागरिक, धार्मिक" }] },
  // Q27
  { textFr: "Qui possède le pouvoir législatif ?", lang: 'hi' as const, text: "विधायी शक्ति किसके पास है?", explanation: "विधायी शक्ति संसद के पास है, जो राष्ट्रीय सभा और सीनेट से बनी है। यह कानून बनाती है।", choices: [{ id: 'a' as const, text: "संसद (राष्ट्रीय सभा और सीनेट)" }, { id: 'b' as const, text: "गणराज्य के राष्ट्रपति" }, { id: 'c' as const, text: "सरकार" }, { id: 'd' as const, text: "न्यायाधीश" }] },
  // Q28
  { textFr: "Qui sanctionne l'auteur d'un vol ?", lang: 'hi' as const, text: "चोरी के अपराधी को कौन दंडित करता है?", explanation: "न्यायपालिका (एक न्यायाधीश) चोरी के अपराधी को दंडित करती है। केवल न्यायिक शक्ति ही दंडात्मक प्रतिबंध लगाने के लिए सक्षम है।", choices: [{ id: 'a' as const, text: "न्यायपालिका (एक न्यायाधीश)" }, { id: 'b' as const, text: "पुलिस" }, { id: 'c' as const, text: "मेयर" }, { id: 'd' as const, text: "पीड़ित स्वयं" }] },
  // Q29
  { textFr: "Qui élit les députés ?", lang: 'hi' as const, text: "सांसदों का चुनाव कौन करता है?", explanation: "सांसद प्रत्यक्ष सार्वभौमिक मताधिकार द्वारा फ्रांसीसी नागरिकों द्वारा चुने जाते हैं। प्रत्येक सांसद एक निर्वाचन क्षेत्र का प्रतिनिधित्व करता है।", choices: [{ id: 'a' as const, text: "प्रत्यक्ष सार्वभौमिक मताधिकार द्वारा फ्रांसीसी नागरिक" }, { id: 'b' as const, text: "सीनेटर" }, { id: 'c' as const, text: "गणराज्य के राष्ट्रपति" }, { id: 'd' as const, text: "महान निर्वाचक" }] },
  // Q30
  { textFr: "Qui vote les lois ?", lang: 'hi' as const, text: "कानून कौन बनाता है?", explanation: "संसद (राष्ट्रीय सभा और सीनेट) कानून बनाती है। यह विधायी शक्ति का मुख्य कार्य है।", choices: [{ id: 'a' as const, text: "संसद (राष्ट्रीय सभा और सीनेट)" }, { id: 'b' as const, text: "गणराज्य के राष्ट्रपति" }, { id: 'c' as const, text: "सरकार" }, { id: 'd' as const, text: "संवैधानिक परिषद" }] },
  // Q31
  { textFr: "Qui réside au palais de l'Élysée ?", lang: 'hi' as const, text: "एलिसी पैलेस में कौन रहता है?", explanation: "एलिसी पैलेस पेरिस में स्थित फ्रांसीसी गणराज्य के राष्ट्रपति का आधिकारिक निवास है।", choices: [{ id: 'a' as const, text: "गणराज्य के राष्ट्रपति" }, { id: 'b' as const, text: "प्रधानमंत्री" }, { id: 'c' as const, text: "राष्ट्रीय सभा के अध्यक्ष" }, { id: 'd' as const, text: "सीनेट के अध्यक्ष" }] },
  // Q32
  { textFr: "Combien y a-t-il de départements en France ?", lang: 'hi' as const, text: "फ्रांस में कितने विभाग हैं?", explanation: "फ्रांस में 101 विभाग हैं: 96 मुख्य भूमि विभाग और 5 समुद्रपार विभाग (गुआदेलूप, मार्टीनिक, गुयाना, ला रियूनियन, मायोट)।", choices: [{ id: 'a' as const, text: "101" }, { id: 'b' as const, text: "96" }, { id: 'c' as const, text: "95" }, { id: 'd' as const, text: "110" }] },
  // Q33
  { textFr: "Qui représente l'État dans un département ?", lang: 'hi' as const, text: "विभाग में राज्य का प्रतिनिधित्व कौन करता है?", explanation: "प्रीफेक्ट विभाग में राज्य का प्रतिनिधित्व करता है। उसकी नियुक्ति गणराज्य के राष्ट्रपति द्वारा की जाती है और वह कानूनों के कार्यान्वयन की निगरानी करता है।", choices: [{ id: 'a' as const, text: "प्रीफेक्ट" }, { id: 'b' as const, text: "मेयर" }, { id: 'c' as const, text: "सांसद" }, { id: 'd' as const, text: "सीनेटर" }] },
  // Q34
  { textFr: "Qui dirige la commune ?", lang: 'hi' as const, text: "नगरपालिका का नेतृत्व कौन करता है?", explanation: "मेयर नगरपालिका का नेतृत्व करता है। वह नगर पार्षदों द्वारा चुना जाता है और नगरपालिका और राज्य दोनों के नाम पर कार्य करता है।", choices: [{ id: 'a' as const, text: "मेयर" }, { id: 'b' as const, text: "प्रीफेक्ट" }, { id: 'c' as const, text: "सांसद" }, { id: 'd' as const, text: "विभागीय परिषद के अध्यक्ष" }] },
  // Q35
  { textFr: "Est-ce que le président de la République a tous les pouvoirs ?", lang: 'hi' as const, text: "क्या गणराज्य के राष्ट्रपति के पास सभी शक्तियाँ हैं?", explanation: "नहीं, गणराज्य के राष्ट्रपति के पास सभी शक्तियाँ नहीं हैं। शक्तियों का पृथक्करण (विधायी, कार्यकारी, न्यायिक) यह सुनिश्चित करता है कि कोई भी व्यक्ति सभी शक्तियाँ नहीं रखता।", choices: [{ id: 'a' as const, text: "नहीं, शक्तियाँ पृथक हैं" }, { id: 'b' as const, text: "हाँ, उनके पास सभी शक्तियाँ हैं" }, { id: 'c' as const, text: "हाँ, न्यायिक शक्ति को छोड़कर" }, { id: 'd' as const, text: "हाँ, संकट काल में" }] },
  // Q36
  { textFr: "Qui est le préfet ?", lang: 'hi' as const, text: "प्रीफेक्ट कौन है?", explanation: "प्रीफेक्ट विभाग में राज्य का प्रतिनिधि है। उसकी नियुक्ति मंत्रिपरिषद में गणराज्य के राष्ट्रपति द्वारा की जाती है।", choices: [{ id: 'a' as const, text: "विभाग में राज्य का प्रतिनिधि" }, { id: 'b' as const, text: "नगरपालिका पुलिस का प्रमुख" }, { id: 'c' as const, text: "एक स्थानीय निर्वाचित प्रतिनिधि" }, { id: 'd' as const, text: "सार्वजनिक अस्पताल का निदेशक" }] },
  // Q37
  { textFr: "Quel est le rôle du Parlement ?", lang: 'hi' as const, text: "संसद की भूमिका क्या है?", explanation: "संसद कानून बनाती है और सरकार की कार्रवाई पर नियंत्रण रखती है। यह फ्रांस में विधायी शक्ति का प्रयोग करती है।", choices: [{ id: 'a' as const, text: "कानून बनाना और सरकार की कार्रवाई पर नियंत्रण रखना" }, { id: 'b' as const, text: "सेना का नेतृत्व करना" }, { id: 'c' as const, text: "न्यायाधीशों की नियुक्ति करना" }, { id: 'd' as const, text: "स्थानीय करों का प्रबंधन करना" }] },
  // Q38
  { textFr: "Quel est le régime politique de la France aujourd'hui ?", lang: 'hi' as const, text: "आज फ्रांस की राजनीतिक व्यवस्था क्या है?", explanation: "फ्रांस एक लोकतांत्रिक गणराज्य है। इसकी व्यवस्था एक प्रतिनिधि लोकतंत्र है जहाँ नागरिक अपने प्रतिनिधियों का चुनाव करते हैं।", choices: [{ id: 'a' as const, text: "एक लोकतांत्रिक गणराज्य" }, { id: 'b' as const, text: "एक संवैधानिक राजतंत्र" }, { id: 'c' as const, text: "एक तानाशाही" }, { id: 'd' as const, text: "एक साम्राज्य" }] },
  // Q39
  { textFr: "Combien d'États font partie de l'Union européenne au 1er janvier 2025 ?", lang: 'hi' as const, text: "1 जनवरी 2025 को यूरोपीय संघ में कितने सदस्य राज्य हैं?", explanation: "यूरोपीय संघ में 1 जनवरी 2025 को 27 सदस्य राज्य हैं, 2020 में यूनाइटेड किंगडम के बाहर निकलने के बाद।", choices: [{ id: 'a' as const, text: "27" }, { id: 'b' as const, text: "28" }, { id: 'c' as const, text: "25" }, { id: 'd' as const, text: "30" }] },
  // Q40
  { textFr: "Quel État n'est pas membre de l'Union européenne ?", lang: 'hi' as const, text: "कौन सा राज्य यूरोपीय संघ का सदस्य नहीं है?", explanation: "स्विट्जरलैंड यूरोपीय संघ का सदस्य नहीं है। उसने द्विपक्षीय समझौतों को बनाए रखते हुए यूरोपीय संघ से बाहर रहने का चुनाव किया है।", choices: [{ id: 'a' as const, text: "स्विट्जरलैंड" }, { id: 'b' as const, text: "जर्मनी" }, { id: 'c' as const, text: "इटली" }, { id: 'd' as const, text: "स्पेन" }] },
  // Q41
  { textFr: "Quelle condition est nécessaire pour voter aux élections européennes ?", lang: 'hi' as const, text: "यूरोपीय चुनावों में मतदान के लिए कौन सी शर्त आवश्यक है?", explanation: "यूरोपीय चुनावों में मतदान करने के लिए यूरोपीय संघ के किसी सदस्य राज्य का नागरिक होना और मतदाता सूची में पंजीकृत होना आवश्यक है।", choices: [{ id: 'a' as const, text: "यूरोपीय संघ के किसी सदस्य राज्य का नागरिक होना" }, { id: 'b' as const, text: "केवल फ्रांसीसी नागरिक होना" }, { id: 'c' as const, text: "10 वर्ष से अधिक समय से फ्रांस में रहना" }, { id: 'd' as const, text: "21 वर्ष से अधिक आयु का होना" }] },
  // Q42
  { textFr: "À quelle fréquence les élections européennes sont-elles organisées ?", lang: 'hi' as const, text: "यूरोपीय चुनाव कितनी बार आयोजित किए जाते हैं?", explanation: "यूरोपीय चुनाव हर 5 साल में आयोजित किए जाते हैं। यूरोपीय संघ के नागरिक यूरोपीय सांसदों का चुनाव करते हैं जो यूरोपीय संसद में बैठते हैं।", choices: [{ id: 'a' as const, text: "हर 5 साल" }, { id: 'b' as const, text: "हर 4 साल" }, { id: 'c' as const, text: "हर 6 साल" }, { id: 'd' as const, text: "हर 3 साल" }] },
  // Q43
  { textFr: "Quel pays est un pays fondateur de l'Union européenne ?", lang: 'hi' as const, text: "कौन सा देश यूरोपीय संघ का संस्थापक देश है?", explanation: "फ्रांस यूरोपीय निर्माण के छह संस्थापक देशों में से एक है (जर्मनी, इटली, बेल्जियम, नीदरलैंड और लक्समबर्ग के साथ), जिन्होंने 1957 में रोम की संधि पर हस्ताक्षर किए।", choices: [{ id: 'a' as const, text: "फ्रांस" }, { id: 'b' as const, text: "स्पेन" }, { id: 'c' as const, text: "यूनाइटेड किंगडम" }, { id: 'd' as const, text: "पोलैंड" }] },
  // Q44
  { textFr: "Quelle est la monnaie utilisée en France ?", lang: 'hi' as const, text: "फ्रांस में कौन सी मुद्रा उपयोग की जाती है?", explanation: "यूरो 1 जनवरी 2002 से फ्रांस में उपयोग की जाने वाली मुद्रा है। यह यूरोपीय संघ के कई देशों की साझी मुद्रा है।", choices: [{ id: 'a' as const, text: "यूरो" }, { id: 'b' as const, text: "फ्रैंक" }, { id: 'c' as const, text: "पाउंड" }, { id: 'd' as const, text: "डॉलर" }] },
  // Q45
  { textFr: "Qui élit les députés européens ?", lang: 'hi' as const, text: "यूरोपीय सांसदों का चुनाव कौन करता है?", explanation: "यूरोपीय सांसदों का चुनाव प्रत्यक्ष सार्वभौमिक मताधिकार द्वारा यूरोपीय संघ के सदस्य राज्यों के नागरिकों द्वारा किया जाता है।", choices: [{ id: 'a' as const, text: "यूरोपीय संघ के सदस्य राज्यों के नागरिक" }, { id: 'b' as const, text: "सदस्य देशों के राष्ट्र प्रमुख" }, { id: 'c' as const, text: "यूरोपीय आयोग" }, { id: 'd' as const, text: "राष्ट्रीय संसदें" }] },
  // Q46
  { textFr: "Quand célèbre-t-on la journée de l'Europe ?", lang: 'hi' as const, text: "यूरोप दिवस कब मनाया जाता है?", explanation: "यूरोप दिवस 9 मई को मनाया जाता है। यह 9 मई 1950 को रॉबर्ट शुमान की घोषणा की स्मृति में मनाया जाता है, जिसे यूरोपीय निर्माण का संस्थापक कार्य माना जाता है।", choices: [{ id: 'a' as const, text: "9 मई" }, { id: 'b' as const, text: "14 जुलाई" }, { id: 'c' as const, text: "1 जनवरी" }, { id: 'd' as const, text: "25 मार्च" }] },
  // Q47
  { textFr: "Qu'est-ce que l'État de droit ?", lang: 'hi' as const, text: "विधि का शासन क्या है?", explanation: "विधि का शासन एक ऐसी व्यवस्था है जिसमें सार्वजनिक प्राधिकरण कानून के सम्मान के अधीन हैं। राज्य सहित प्रत्येक व्यक्ति को कानूनों का पालन करना चाहिए।", choices: [{ id: 'a' as const, text: "एक ऐसा राज्य जिसमें सार्वजनिक प्राधिकरण कानून के सम्मान के अधीन हैं" }, { id: 'b' as const, text: "एक ऐसा राज्य जहाँ केवल राष्ट्रपति कानून तय करता है" }, { id: 'c' as const, text: "बिना संविधान वाला राज्य" }, { id: 'd' as const, text: "एक ऐसा राज्य जहाँ न्यायाधीश कानून बनाते हैं" }] },
  // Q48
  { textFr: "Le président de la République a commis un crime. Quelle proposition est correcte ?", lang: 'hi' as const, text: "गणराज्य के राष्ट्रपति ने अपराध किया है। कौन सा कथन सही है?", explanation: "गणराज्य के राष्ट्रपति पर उनके कार्यकाल की समाप्ति के बाद मुकदमा चलाया जा सकता है। अपने कार्यकाल के दौरान उन्हें अस्थायी प्रतिरक्षा प्राप्त है, लेकिन वे कानून से ऊपर नहीं हैं।", choices: [{ id: 'a' as const, text: "उन पर कार्यकाल समाप्ति के बाद मुकदमा चलाया जा सकता है" }, { id: 'b' as const, text: "उन पर कभी मुकदमा नहीं चलाया जा सकता" }, { id: 'c' as const, text: "उन्हें तुरंत गिरफ्तार किया जाता है" }, { id: 'd' as const, text: "उन पर केवल संसद द्वारा मुकदमा चलाया जाता है" }] },
  // Q49
  { textFr: "La loi est l'expression de :", lang: 'hi' as const, text: "कानून अभिव्यक्ति है:", explanation: "कानून सामान्य इच्छा की अभिव्यक्ति है, जैसा कि 1789 की मानवाधिकार और नागरिक अधिकारों की घोषणा के अनुच्छेद 6 में कहा गया है।", choices: [{ id: 'a' as const, text: "सामान्य इच्छा की" }, { id: 'b' as const, text: "राष्ट्रपति की इच्छा की" }, { id: 'c' as const, text: "न्यायाधीशों की इच्छा की" }, { id: 'd' as const, text: "सरकार की इच्छा की" }] },
  // Q50
  { textFr: "Quelle est la durée du mandat du conseil municipal et du maire ?", lang: 'hi' as const, text: "नगर परिषद और मेयर के कार्यकाल की अवधि क्या है?", explanation: "नगर परिषद और मेयर 6 वर्ष के कार्यकाल के लिए चुने जाते हैं। नगरपालिका चुनाव हर 6 साल में होते हैं।", choices: [{ id: 'a' as const, text: "6 वर्ष" }, { id: 'b' as const, text: "5 वर्ष" }, { id: 'c' as const, text: "4 वर्ष" }, { id: 'd' as const, text: "7 वर्ष" }] },
  // Q51
  { textFr: "Que garantit l'État de droit ?", lang: 'hi' as const, text: "विधि का शासन क्या गारंटी देता है?", explanation: "विधि का शासन मौलिक अधिकारों और व्यक्तिगत स्वतंत्रताओं के सम्मान की गारंटी देता है। यह सुनिश्चित करता है कि राज्य सहित कोई भी कानून से ऊपर नहीं है।", choices: [{ id: 'a' as const, text: "मौलिक अधिकारों और व्यक्तिगत स्वतंत्रताओं का सम्मान" }, { id: 'b' as const, text: "सभी नागरिकों के लिए रोजगार" }, { id: 'c' as const, text: "सभी सार्वजनिक सेवाओं की निःशुल्कता" }, { id: 'd' as const, text: "करों का पूर्ण अभाव" }] },
  // Q52
  { textFr: "Une personne peut-elle voter à la place d'une autre ?", lang: 'hi' as const, text: "क्या कोई व्यक्ति किसी अन्य की जगह मतदान कर सकता है?", explanation: "हाँ, प्रॉक्सी द्वारा मतदान संभव है। जो मतदाता उपस्थित नहीं हो सकता, वह उसी नगरपालिका में पंजीकृत किसी अन्य मतदाता को अपनी ओर से मतदान करने का अधिकार दे सकता है।", choices: [{ id: 'a' as const, text: "हाँ, प्रॉक्सी (प्रतिनिधि) द्वारा" }, { id: 'b' as const, text: "नहीं, कभी नहीं" }, { id: 'c' as const, text: "हाँ, बिना किसी औपचारिकता के" }, { id: 'd' as const, text: "हाँ, केवल परिवार के सदस्यों के लिए" }] },
  // Q53
  { textFr: "Est-ce que le vote est obligatoire ?", lang: 'hi' as const, text: "क्या मतदान अनिवार्य है?", explanation: "नहीं, फ्रांस में मतदान अनिवार्य नहीं है। यह एक अधिकार है, कानूनी बाध्यता नहीं, लेकिन यह एक नागरिक कर्तव्य है।", choices: [{ id: 'a' as const, text: "नहीं, यह अनिवार्य नहीं है लेकिन यह एक नागरिक कर्तव्य है" }, { id: 'b' as const, text: "हाँ, यह सभी के लिए अनिवार्य है" }, { id: 'c' as const, text: "हाँ, जुर्माने के दंड के साथ" }, { id: 'd' as const, text: "हाँ, बुजुर्गों को छोड़कर" }] },
  // Q54
  { textFr: "À la fin de son mandat, le président de la République peut-il décider de rester au pouvoir ?", lang: 'hi' as const, text: "अपने कार्यकाल के अंत में, क्या गणराज्य के राष्ट्रपति सत्ता में बने रहने का निर्णय ले सकते हैं?", explanation: "नहीं, राष्ट्रपति अपने कार्यकाल के अंत में सत्ता में बने रहने का निर्णय नहीं ले सकते। उन्हें फिर से चुनाव लड़ना चाहिए या पद छोड़ना चाहिए। यह लोकतंत्र का मूल सिद्धांत है।", choices: [{ id: 'a' as const, text: "नहीं, उन्हें फिर से चुनाव लड़ना या पद छोड़ना चाहिए" }, { id: 'b' as const, text: "हाँ, यदि वे चाहें" }, { id: 'c' as const, text: "हाँ, संसद की सहमति से" }, { id: 'd' as const, text: "हाँ, राष्ट्रीय संकट की स्थिति में" }] },
  // Q55
  { textFr: "Qui dirige l'action du Gouvernement ?", lang: 'hi' as const, text: "सरकार की कार्रवाई का नेतृत्व कौन करता है?", explanation: "प्रधानमंत्री संविधान के अनुच्छेद 21 के अनुसार सरकार की कार्रवाई का नेतृत्व करता है। वह मंत्रियों की कार्रवाई का समन्वय करता है।", choices: [{ id: 'a' as const, text: "प्रधानमंत्री" }, { id: 'b' as const, text: "गणराज्य के राष्ट्रपति" }, { id: 'c' as const, text: "राष्ट्रीय सभा के अध्यक्ष" }, { id: 'd' as const, text: "गृह मंत्री" }] },
  // Q56
  { textFr: "Quelle est l'organisation administrative de la France ?", lang: 'hi' as const, text: "फ्रांस का प्रशासनिक संगठन क्या है?", explanation: "फ्रांस नगरपालिकाओं, विभागों और क्षेत्रों में संगठित है। ये संविधान द्वारा प्रदत्त स्थानीय प्राधिकरणों के तीन स्तर हैं।", choices: [{ id: 'a' as const, text: "नगरपालिकाएँ, विभाग और क्षेत्र" }, { id: 'b' as const, text: "प्रांत, कैंटन और जिले" }, { id: 'c' as const, text: "शहर, काउंटी और राज्य" }, { id: 'd' as const, text: "अरोंदिसमाँ, प्रीफेक्चर और महानगर" }] },
  // Q57
  { textFr: "Qu'est-ce que le pouvoir législatif ? Le pouvoir :", lang: 'hi' as const, text: "विधायी शक्ति क्या है? यह शक्ति:", explanation: "विधायी शक्ति कानून बनाने की शक्ति है। फ्रांस में, इसका प्रयोग संसद (राष्ट्रीय सभा और सीनेट) द्वारा किया जाता है।", choices: [{ id: 'a' as const, text: "कानून बनाने की" }, { id: 'b' as const, text: "कानूनों को लागू करने की" }, { id: 'c' as const, text: "अपराधों पर निर्णय लेने की" }, { id: 'd' as const, text: "मंत्रियों की नियुक्ति करने की" }] },
  // Q58
  { textFr: "Pourquoi séparer les trois pouvoirs dans une démocratie ?", lang: 'hi' as const, text: "लोकतंत्र में तीन शक्तियों को अलग क्यों किया जाता है?", explanation: "शक्तियों का पृथक्करण किसी एक व्यक्ति या संस्था द्वारा सभी शक्तियों के केंद्रीकरण से बचने की अनुमति देता है। यह सत्ता के दुरुपयोग और अत्याचार के विरुद्ध एक गारंटी है।", choices: [{ id: 'a' as const, text: "शक्तियों के केंद्रीकरण से बचने और स्वतंत्रताओं की रक्षा के लिए" }, { id: 'b' as const, text: "अधिक सरकारी नौकरियाँ बनाने के लिए" }, { id: 'c' as const, text: "ताकि निर्णय धीमे हों" }, { id: 'd' as const, text: "चुनावों की संख्या बढ़ाने के लिए" }] },
  // Q59
  { textFr: "Quel est le rôle du gouvernement ?", lang: 'hi' as const, text: "सरकार की भूमिका क्या है?", explanation: "सरकार राष्ट्र की नीति निर्धारित करती है और उसका संचालन करती है। इसके पास प्रशासन और सशस्त्र बल हैं (संविधान का अनुच्छेद 20)।", choices: [{ id: 'a' as const, text: "राष्ट्र की नीति निर्धारित और संचालित करना" }, { id: 'b' as const, text: "कानून बनाना" }, { id: 'c' as const, text: "अपराधियों को दंडित करना" }, { id: 'd' as const, text: "गणराज्य के राष्ट्रपति का चुनाव करना" }] },
  // Q60
  { textFr: "Qu'est-ce que l'Hôtel de Matignon ?", lang: 'hi' as const, text: "ओटेल दे मातिन्योँ क्या है?", explanation: "ओटेल दे मातिन्योँ प्रधानमंत्री का आधिकारिक निवास और कार्यस्थल है, जो पेरिस के 7वें अरोंदिसमाँ में स्थित है।", choices: [{ id: 'a' as const, text: "प्रधानमंत्री का आधिकारिक निवास" }, { id: 'b' as const, text: "गणराज्य के राष्ट्रपति का निवास" }, { id: 'c' as const, text: "राष्ट्रीय सभा का मुख्यालय" }, { id: 'd' as const, text: "संवैधानिक परिषद का मुख्यालय" }] },
  // Q61
  { textFr: "Quel est le rôle du président de la République ?", lang: 'hi' as const, text: "गणराज्य के राष्ट्रपति की भूमिका क्या है?", explanation: "गणराज्य के राष्ट्रपति संविधान के सम्मान की निगरानी करते हैं, सार्वजनिक प्राधिकरणों के कामकाज और राज्य की निरंतरता सुनिश्चित करते हैं। वे राष्ट्रीय स्वतंत्रता के गारंटर हैं।", choices: [{ id: 'a' as const, text: "संविधान के सम्मान की निगरानी करना और राष्ट्रीय स्वतंत्रता की गारंटी देना" }, { id: 'b' as const, text: "संसद में कानून बनाना" }, { id: 'c' as const, text: "अदालतों का नेतृत्व करना" }, { id: 'd' as const, text: "नगरपालिकाओं का प्रबंधन करना" }] },
  // Q62
  { textFr: "Quel est le rôle du Premier ministre ?", lang: 'hi' as const, text: "प्रधानमंत्री की भूमिका क्या है?", explanation: "प्रधानमंत्री सरकार की कार्रवाई का नेतृत्व करता है। वह राष्ट्रीय सभा के प्रति उत्तरदायी है और कानूनों के कार्यान्वयन को सुनिश्चित करता है।", choices: [{ id: 'a' as const, text: "सरकार की कार्रवाई का नेतृत्व करना" }, { id: 'b' as const, text: "संवैधानिक परिषद की अध्यक्षता करना" }, { id: 'c' as const, text: "कानून बनाना" }, { id: 'd' as const, text: "सेना की कमान करना" }] },
  // Q63
  { textFr: "Qui est le chef du Gouvernement ?", lang: 'hi' as const, text: "सरकार का प्रमुख कौन है?", explanation: "प्रधानमंत्री सरकार का प्रमुख है। वह सरकार की कार्रवाई का नेतृत्व करता है और मंत्रियों के कार्य का समन्वय करता है।", choices: [{ id: 'a' as const, text: "प्रधानमंत्री" }, { id: 'b' as const, text: "गणराज्य के राष्ट्रपति" }, { id: 'c' as const, text: "राष्ट्रीय सभा के अध्यक्ष" }, { id: 'd' as const, text: "गृह मंत्री" }] },
  // Q64
  { textFr: "Combien y a-t-il de régions en France ?", lang: 'hi' as const, text: "फ्रांस में कितने क्षेत्र हैं?", explanation: "फ्रांस में 18 क्षेत्र हैं: 13 मुख्य भूमि क्षेत्र (कोर्सिका सहित) और 5 समुद्रपार क्षेत्र।", choices: [{ id: 'a' as const, text: "18" }, { id: 'b' as const, text: "13" }, { id: 'c' as const, text: "22" }, { id: 'd' as const, text: "15" }] },
  // Q65
  { textFr: "Quel est le rôle du Défenseur des droits ?", lang: 'hi' as const, text: "अधिकार रक्षक की भूमिका क्या है?", explanation: "अधिकार रक्षक एक स्वतंत्र प्राधिकरण है जो अधिकारों और स्वतंत्रताओं के सम्मान की निगरानी करता है। किसी सार्वजनिक सेवा द्वारा पीड़ित कोई भी व्यक्ति इसके पास शिकायत कर सकता है।", choices: [{ id: 'a' as const, text: "नागरिकों के अधिकारों और स्वतंत्रताओं के सम्मान की निगरानी करना" }, { id: 'b' as const, text: "कानून बनाना" }, { id: 'c' as const, text: "सेना की कमान करना" }, { id: 'd' as const, text: "राज्य के बजट का प्रबंधन करना" }] },
  // Q66
  { textFr: "Depuis quand l'euro est-il la monnaie unique ?", lang: 'hi' as const, text: "यूरो कब से एकल मुद्रा है?", explanation: "यूरो 1 जनवरी 2002 से प्रचलन में एकल मुद्रा बन गया। इसे 1999 में लेखा मुद्रा के रूप में पेश किया गया था।", choices: [{ id: 'a' as const, text: "1 जनवरी 2002" }, { id: 'b' as const, text: "1 जनवरी 1999" }, { id: 'c' as const, text: "1 जनवरी 1992" }, { id: 'd' as const, text: "1 जनवरी 2005" }] },
  // Q67
  { textFr: "Quel est le rôle principal du département ?", lang: 'hi' as const, text: "विभाग की मुख्य भूमिका क्या है?", explanation: "विभाग की मुख्य भूमिका सामाजिक कार्रवाई और एकजुटता है (सामाजिक सहायता, आरएसए, बाल संरक्षण)। यह कॉलेजों और विभागीय सड़कों का भी प्रबंधन करता है।", choices: [{ id: 'a' as const, text: "सामाजिक कार्रवाई और एकजुटता" }, { id: 'b' as const, text: "राष्ट्रीय रक्षा" }, { id: 'c' as const, text: "विदेश नीति" }, { id: 'd' as const, text: "विश्वविद्यालयों का प्रबंधन" }] },
  // Q68
  { textFr: "Quel est le rôle principal des communes ?", lang: 'hi' as const, text: "नगरपालिकाओं की मुख्य भूमिका क्या है?", explanation: "नगरपालिकाएँ निकटवर्ती सेवाओं का प्रबंधन करती हैं: नागरिक स्थिति, मातृ एवं प्राथमिक विद्यालय, शहरी नियोजन, सामुदायिक सड़कें, जल और स्वच्छता।", choices: [{ id: 'a' as const, text: "निकटवर्ती सेवाओं का प्रबंधन (नागरिक स्थिति, विद्यालय, शहरी नियोजन)" }, { id: 'b' as const, text: "राष्ट्रीय रक्षा का आयोजन" }, { id: 'c' as const, text: "अस्पतालों का प्रबंधन" }, { id: 'd' as const, text: "राष्ट्रीय करों का संग्रह" }] },
  // Q69
  { textFr: "Combien de communes environ existe-t-il en France ?", lang: 'hi' as const, text: "फ्रांस में लगभग कितनी नगरपालिकाएँ हैं?", explanation: "फ्रांस में लगभग 35,000 नगरपालिकाएँ हैं, जो इसे यूरोप में सबसे अधिक नगरपालिकाओं वाला देश बनाती है।", choices: [{ id: 'a' as const, text: "लगभग 35,000" }, { id: 'b' as const, text: "लगभग 10,000" }, { id: 'c' as const, text: "लगभग 5,000" }, { id: 'd' as const, text: "लगभग 50,000" }] },
  // Q70
  { textFr: "Quel traité concerne la construction de l'Union européenne ?", lang: 'hi' as const, text: "कौन सी संधि यूरोपीय संघ के निर्माण से संबंधित है?", explanation: "मास्ट्रिख्ट संधि (1992) यूरोपीय संघ की संस्थापक संधि है। इसने यूरोपीय नागरिकता की स्थापना की और एकल मुद्रा की नींव रखी।", choices: [{ id: 'a' as const, text: "मास्ट्रिख्ट संधि" }, { id: 'b' as const, text: "वर्साय संधि" }, { id: 'c' as const, text: "वेस्टफेलिया संधि" }, { id: 'd' as const, text: "वियना संधि" }] },
  // Q71
  { textFr: "Quel État a quitté l'Union européenne en 2020 ?", lang: 'hi' as const, text: "कौन सा राज्य 2020 में यूरोपीय संघ से बाहर निकला?", explanation: "यूनाइटेड किंगडम ने 2016 के ब्रेक्सिट जनमत संग्रह के बाद 31 जनवरी 2020 को यूरोपीय संघ छोड़ दिया।", choices: [{ id: 'a' as const, text: "यूनाइटेड किंगडम" }, { id: 'b' as const, text: "नॉर्वे" }, { id: 'c' as const, text: "स्विट्जरलैंड" }, { id: 'd' as const, text: "आइसलैंड" }] },
  // Q72
  { textFr: "Quelle est la devise de l'Union européenne ?", lang: 'hi' as const, text: "यूरोपीय संघ का आदर्श वाक्य क्या है?", explanation: "यूरोपीय संघ का आदर्श वाक्य \"विविधता में एकता\" है। यह उनकी सांस्कृतिक भिन्नताओं के सम्मान में यूरोपीय लोगों की एकता का प्रतीक है।", choices: [{ id: 'a' as const, text: "विविधता में एकता" }, { id: 'b' as const, text: "स्वतंत्रता, समानता, बंधुत्व" }, { id: 'c' as const, text: "शांति और समृद्धि" }, { id: 'd' as const, text: "एकता में शक्ति है" }] },
  // Q73
  { textFr: "Quel est l'hymne de l'Union européenne ?", lang: 'hi' as const, text: "यूरोपीय संघ का राष्ट्रगान क्या है?", explanation: "यूरोपीय संघ का राष्ट्रगान \"आनंद का गीत\" है, जो लुडविग वान बीथोवन की 9वीं सिम्फनी से लिया गया है। इसे 1972 में यूरोप परिषद द्वारा अपनाया गया था।", choices: [{ id: 'a' as const, text: "बीथोवन का \"आनंद का गीत\"" }, { id: 'b' as const, text: "ला मार्सेयेज़" }, { id: 'c' as const, text: "रावेल का बोलेरो" }, { id: 'd' as const, text: "विवाल्डी का \"चार ऋतुएँ\"" }] },
  // Q74
  { textFr: "De quoi est composé le drapeau européen ?", lang: 'hi' as const, text: "यूरोपीय ध्वज किससे बना है?", explanation: "यूरोपीय ध्वज नीली पृष्ठभूमि पर वृत्त में व्यवस्थित 12 सुनहरे सितारों से बना है। संख्या 12 पूर्णता और एकता का प्रतीक है, यह सदस्य राज्यों की संख्या से मेल नहीं खाती।", choices: [{ id: 'a' as const, text: "नीली पृष्ठभूमि पर वृत्त में व्यवस्थित 12 सुनहरे सितारे" }, { id: 'b' as const, text: "नीली पृष्ठभूमि पर 27 सितारे" }, { id: 'c' as const, text: "नीली और सफेद क्षैतिज पट्टियाँ" }, { id: 'd' as const, text: "लाल पृष्ठभूमि पर 15 सुनहरे सितारे" }] },
  // Q75
  { textFr: "De quelle couleur est le drapeau européen ?", lang: 'hi' as const, text: "यूरोपीय ध्वज किस रंग का है?", explanation: "यूरोपीय ध्वज सुनहरे (पीले) सितारों के साथ नीला है। नीली पृष्ठभूमि आकाश का प्रतिनिधित्व करती है और सितारे यूरोप के लोगों की एकता का प्रतीक हैं।", choices: [{ id: 'a' as const, text: "सुनहरे सितारों के साथ नीला" }, { id: 'b' as const, text: "सफेद सितारों के साथ लाल" }, { id: 'c' as const, text: "सुनहरे सितारों के साथ हरा" }, { id: 'd' as const, text: "नीले सितारों के साथ सफेद" }] },
  // Q76
  { textFr: "En quelle année le traité de Maastricht a-t-il été signé ?", lang: 'hi' as const, text: "मास्ट्रिख्ट संधि किस वर्ष हस्ताक्षरित हुई थी?", explanation: "मास्ट्रिख्ट संधि पर 7 फरवरी 1992 को हस्ताक्षर किए गए थे। इसने यूरोपीय संघ की स्थापना की और एकल मुद्रा (यूरो) की नींव रखी।", choices: [{ id: 'a' as const, text: "1992" }, { id: 'b' as const, text: "1957" }, { id: 'c' as const, text: "1989" }, { id: 'd' as const, text: "2000" }] },
  // Q77
  { textFr: "Où est le siège du Parlement européen ?", lang: 'hi' as const, text: "यूरोपीय संसद का मुख्यालय कहाँ है?", explanation: "यूरोपीय संसद का मुख्यालय स्ट्रासबर्ग (फ्रांस) में है। सत्र ब्रसेल्स (बेल्जियम) में भी आयोजित होते हैं।", choices: [{ id: 'a' as const, text: "स्ट्रासबर्ग में" }, { id: 'b' as const, text: "ब्रसेल्स में" }, { id: 'c' as const, text: "लक्समबर्ग में" }, { id: 'd' as const, text: "बर्लिन में" }] },
  // Q78
  { textFr: "Où est le siège de la Commission européenne ?", lang: 'hi' as const, text: "यूरोपीय आयोग का मुख्यालय कहाँ है?", explanation: "यूरोपीय आयोग का मुख्यालय ब्रसेल्स (बेल्जियम) में है। आयोग यूरोपीय संघ का कार्यकारी अंग है।", choices: [{ id: 'a' as const, text: "ब्रसेल्स में" }, { id: 'b' as const, text: "स्ट्रासबर्ग में" }, { id: 'c' as const, text: "लक्समबर्ग में" }, { id: 'd' as const, text: "पेरिस में" }] },
  // Q79
  { textFr: "Comment est désigné le Premier ministre ?", lang: 'hi' as const, text: "प्रधानमंत्री की नियुक्ति कैसे होती है?", explanation: "प्रधानमंत्री की नियुक्ति गणराज्य के राष्ट्रपति द्वारा की जाती है। वह नागरिकों द्वारा सीधे निर्वाचित नहीं होता।", choices: [{ id: 'a' as const, text: "उसकी नियुक्ति गणराज्य के राष्ट्रपति द्वारा होती है" }, { id: 'b' as const, text: "वह प्रत्यक्ष सार्वभौमिक मताधिकार से चुना जाता है" }, { id: 'c' as const, text: "वह सांसदों द्वारा चुना जाता है" }, { id: 'd' as const, text: "उसे संवैधानिक परिषद द्वारा नामित किया जाता है" }] },
  // Q80
  { textFr: "Qui peut se présenter aux élections présidentielles ?", lang: 'hi' as const, text: "राष्ट्रपति चुनाव में कौन उम्मीदवार हो सकता है?", explanation: "कोई भी फ्रांसीसी नागरिक जिसकी आयु कम से कम 18 वर्ष है और जो अपने नागरिक और राजनीतिक अधिकारों का उपभोग करता है, 500 निर्वाचित प्रतिनिधियों के समर्थन प्राप्त करने की शर्त पर उम्मीदवार हो सकता है।", choices: [{ id: 'a' as const, text: "कोई भी फ्रांसीसी नागरिक जिसने 500 निर्वाचित प्रतिनिधियों का समर्थन प्राप्त किया हो" }, { id: 'b' as const, text: "केवल किसी राजनीतिक दल के सदस्य" }, { id: 'c' as const, text: "केवल पूर्व मंत्री" }, { id: 'd' as const, text: "केवल 40 वर्ष से अधिक आयु के व्यक्ति" }] },
  // Q81
  { textFr: "À qui appartient la souveraineté nationale ?", lang: 'hi' as const, text: "राष्ट्रीय संप्रभुता किसकी है?", explanation: "राष्ट्रीय संप्रभुता जनता की है, जो इसे अपने प्रतिनिधियों के माध्यम से और जनमत संग्रह के द्वारा प्रयोग करती है (संविधान का अनुच्छेद 3)।", choices: [{ id: 'a' as const, text: "जनता की" }, { id: 'b' as const, text: "गणराज्य के राष्ट्रपति की" }, { id: 'c' as const, text: "संसद की" }, { id: 'd' as const, text: "सरकार की" }] },
  // Q82
  { textFr: "L'inscription sur les listes électorales est :", lang: 'hi' as const, text: "मतदाता सूची में पंजीकरण है:", explanation: "मतदाता सूची में पंजीकरण प्रत्येक वयस्क फ्रांसीसी नागरिक के लिए अनिवार्य है। 2019 से, 18 वर्ष की आयु में पंजीकरण स्वचालित है।", choices: [{ id: 'a' as const, text: "अनिवार्य" }, { id: 'b' as const, text: "ऐच्छिक" }, { id: 'c' as const, text: "केवल पुरुषों के लिए स्वचालित" }, { id: 'd' as const, text: "21 वर्ष से अधिक आयु के व्यक्तियों के लिए आरक्षित" }] },
  // Q83
  { textFr: "Quelle condition est nécessaire pour voter aux élections présidentielles ?", lang: 'hi' as const, text: "राष्ट्रपति चुनाव में मतदान के लिए कौन सी शर्त आवश्यक है?", explanation: "राष्ट्रपति चुनाव में मतदान करने के लिए फ्रांसीसी राष्ट्रीयता, 18 वर्ष की पूर्ण आयु, नागरिक और राजनीतिक अधिकारों का उपभोग और मतदाता सूची में पंजीकरण आवश्यक है।", choices: [{ id: 'a' as const, text: "फ्रांसीसी राष्ट्रीयता, वयस्क और मतदाता सूची में पंजीकृत होना" }, { id: 'b' as const, text: "कम से कम 5 वर्ष से फ्रांस में निवासी होना" }, { id: 'c' as const, text: "साफ आपराधिक रिकॉर्ड होना" }, { id: 'd' as const, text: "डिप्लोमा धारक होना" }] },
  // Q84
  { textFr: "Quelle condition faut-il remplir pour être candidat aux élections municipales ?", lang: 'hi' as const, text: "नगरपालिका चुनावों में उम्मीदवार होने के लिए कौन सी शर्त पूरी करनी होगी?", explanation: "नगरपालिका चुनावों में उम्मीदवार होने के लिए 18 वर्ष की पूर्ण आयु, फ्रांसीसी राष्ट्रीयता या यूरोपीय संघ की नागरिकता और नगरपालिका की मतदाता सूची में पंजीकृत या वहाँ कर देना आवश्यक है।", choices: [{ id: 'a' as const, text: "18 वर्ष और नगरपालिका की मतदाता सूची में पंजीकृत होना" }, { id: 'b' as const, text: "25 वर्ष और 10 वर्ष से नगरपालिका में निवासी होना" }, { id: 'c' as const, text: "सरकारी कर्मचारी होना" }, { id: 'd' as const, text: "नगरपालिका में संपत्ति मालिक होना" }] },
  // Q85
  { textFr: "Parmi ces autorités, laquelle est élue ?", lang: 'hi' as const, text: "इन प्राधिकरणों में से कौन निर्वाचित है?", explanation: "मेयर नगर पार्षदों द्वारा निर्वाचित होता है। प्रीफेक्ट नामित होता है, लोक अभियोजक एक मजिस्ट्रेट है, और विद्यालय निदेशक एक सरकारी कर्मचारी है।", choices: [{ id: 'a' as const, text: "मेयर" }, { id: 'b' as const, text: "प्रीफेक्ट" }, { id: 'c' as const, text: "गणराज्य का लोक अभियोजक" }, { id: 'd' as const, text: "विद्यालय निदेशक" }] },
  // Q86
  { textFr: "Quelles sont les fonctions du maire ?", lang: 'hi' as const, text: "मेयर के कार्य क्या हैं?", explanation: "मेयर एक साथ नागरिक स्थिति अधिकारी, नगरपालिका में राज्य का प्रतिनिधि और सामुदायिक प्रशासन का प्रमुख है। वह विवाह संपन्न कराता है और निर्माण अनुमति जारी करता है।", choices: [{ id: 'a' as const, text: "नागरिक स्थिति अधिकारी, राज्य का प्रतिनिधि और सामुदायिक प्रशासन का प्रमुख" }, { id: 'b' as const, text: "राष्ट्रीय पुलिस और अग्निशमन सेवा का प्रमुख" }, { id: 'c' as const, text: "नगरपालिका के न्यायालय का अध्यक्ष" }, { id: 'd' as const, text: "नगरपालिका में राष्ट्रीय शिक्षा का प्रभारी" }] },
  // Q87
  { textFr: "Une personne n'ayant pas d'accès à internet veut s'inscrire sur les listes électorales. Où peut-elle s'inscrire ?", lang: 'hi' as const, text: "इंटरनेट तक पहुँच न रखने वाला व्यक्ति मतदाता सूची में पंजीकरण करना चाहता है। वह कहाँ पंजीकरण कर सकता है?", explanation: "कोई व्यक्ति अपने निवास स्थान की नगरपालिका (मेयरी) में जाकर मतदाता सूची में पंजीकरण कर सकता है। ऑनलाइन पंजीकरण एकमात्र विकल्प नहीं है।", choices: [{ id: 'a' as const, text: "अपने निवास स्थान की नगरपालिका (मेयरी) में" }, { id: 'b' as const, text: "केवल प्रीफेक्चर में" }, { id: 'c' as const, text: "पुलिस थाने में" }, { id: 'd' as const, text: "न्यायिक न्यायालय में" }] },
  // Q88
  { textFr: "À quel âge peut-on devenir électeur ?", lang: 'hi' as const, text: "किस उम्र में मतदाता बना जा सकता है?", explanation: "फ्रांस में 18 वर्ष की आयु में मतदाता बना जा सकता है। 1974 से यह नागरिक और राजनीतिक वयस्कता की आयु है।", choices: [{ id: 'a' as const, text: "18 वर्ष" }, { id: 'b' as const, text: "16 वर्ष" }, { id: 'c' as const, text: "21 वर्ष" }, { id: 'd' as const, text: "25 वर्ष" }] },
  // Q89
  { textFr: "En France, est-ce obligatoire de voter ?", lang: 'hi' as const, text: "फ्रांस में, क्या मतदान करना अनिवार्य है?", explanation: "नहीं, फ्रांस में मतदान अनिवार्य नहीं है। यह एक अधिकार और नागरिक कर्तव्य है, लेकिन मतदान न करने पर कोई दंड नहीं है।", choices: [{ id: 'a' as const, text: "नहीं, मतदान एक अधिकार है लेकिन कानूनी बाध्यता नहीं" }, { id: 'b' as const, text: "हाँ, जुर्माने के दंड के साथ" }, { id: 'c' as const, text: "हाँ, कारावास के दंड के साथ" }, { id: 'd' as const, text: "हाँ, 70 वर्ष से अधिक आयु के व्यक्तियों को छोड़कर" }] },
  // Q90
  { textFr: "Comment sont désignés les députés ?", lang: 'hi' as const, text: "सांसदों की नियुक्ति कैसे होती है?", explanation: "सांसद फ्रांसीसी नागरिकों द्वारा प्रत्यक्ष सार्वभौमिक मताधिकार से चुने जाते हैं। प्रत्येक सांसद एक विधानसभा निर्वाचन क्षेत्र का प्रतिनिधित्व करता है।", choices: [{ id: 'a' as const, text: "वे प्रत्यक्ष सार्वभौमिक मताधिकार से चुने जाते हैं" }, { id: 'b' as const, text: "उन्हें गणराज्य के राष्ट्रपति द्वारा नामित किया जाता है" }, { id: 'c' as const, text: "उन्हें सीनेटरों द्वारा चुना जाता है" }, { id: 'd' as const, text: "उन्हें राजनीतिक दलों द्वारा नामित किया जाता है" }] },
  // Q91
  { textFr: "En France, est-ce possible d'adhérer à un parti politique ?", lang: 'hi' as const, text: "फ्रांस में, क्या किसी राजनीतिक दल में शामिल होना संभव है?", explanation: "हाँ, फ्रांस में कोई भी व्यक्ति अपनी पसंद के राजनीतिक दल में स्वतंत्र रूप से शामिल हो सकता है। संघ बनाने की स्वतंत्रता और राजनीतिक बहुलवाद संविधान द्वारा गारंटीकृत हैं।", choices: [{ id: 'a' as const, text: "हाँ, कोई भी अपनी पसंद के दल में स्वतंत्र रूप से शामिल हो सकता है" }, { id: 'b' as const, text: "नहीं, राजनीतिक दल प्रतिबंधित हैं" }, { id: 'c' as const, text: "हाँ, लेकिन केवल फ्रांसीसी नागरिक" }, { id: 'd' as const, text: "नहीं, केवल निर्वाचित प्रतिनिधि किसी दल में शामिल हो सकते हैं" }] },
  // Q92
  { textFr: "Qui gère les collèges publics ?", lang: 'hi' as const, text: "सार्वजनिक माध्यमिक विद्यालयों (कॉलेज) का प्रबंधन कौन करता है?", explanation: "सार्वजनिक माध्यमिक विद्यालय विभाग द्वारा प्रबंधित किए जाते हैं। उनका निर्माण, रखरखाव और संचालन विभागीय परिषद की जिम्मेदारी है।", choices: [{ id: 'a' as const, text: "विभाग" }, { id: 'b' as const, text: "नगरपालिका" }, { id: 'c' as const, text: "क्षेत्र" }, { id: 'd' as const, text: "सीधे राज्य" }] },
  // Q93
  { textFr: "Qui gère les écoles primaires et maternelles publiques ?", lang: 'hi' as const, text: "सार्वजनिक प्राथमिक और मातृ विद्यालयों का प्रबंधन कौन करता है?", explanation: "सार्वजनिक प्राथमिक और मातृ विद्यालय नगरपालिका द्वारा प्रबंधित किए जाते हैं। नगरपालिका विद्यालय भवनों के निर्माण, रखरखाव और संचालन को सुनिश्चित करती है।", choices: [{ id: 'a' as const, text: "नगरपालिका" }, { id: 'b' as const, text: "विभाग" }, { id: 'c' as const, text: "क्षेत्र" }, { id: 'd' as const, text: "राष्ट्रीय शिक्षा मंत्रालय" }] },
  // Q94
  { textFr: "Comment sont désignés les maires ?", lang: 'hi' as const, text: "मेयर कैसे नियुक्त किए जाते हैं?", explanation: "मेयर नगरपालिका चुनावों के बाद नई नगर परिषद के पहले सत्र में नगर पार्षदों द्वारा चुने जाते हैं।", choices: [{ id: 'a' as const, text: "उन्हें नगर पार्षदों द्वारा चुना जाता है" }, { id: 'b' as const, text: "उन्हें सीधे नागरिकों द्वारा चुना जाता है" }, { id: 'c' as const, text: "उन्हें प्रीफेक्ट द्वारा नामित किया जाता है" }, { id: 'd' as const, text: "उन्हें गणराज्य के राष्ट्रपति द्वारा नामित किया जाता है" }] },
  // Q95
  { textFr: "Quelle collectivité territoriale est responsable des transports régionaux ?", lang: 'hi' as const, text: "कौन सा स्थानीय प्राधिकरण क्षेत्रीय परिवहन के लिए जिम्मेदार है?", explanation: "क्षेत्र (रीजन) क्षेत्रीय परिवहन (TER) के लिए जिम्मेदार है। यह क्षेत्रीय यात्री रेल परिवहन सेवाओं का आयोजन और वित्तपोषण करता है।", choices: [{ id: 'a' as const, text: "क्षेत्र (रीजन)" }, { id: 'b' as const, text: "विभाग" }, { id: 'c' as const, text: "नगरपालिका" }, { id: 'd' as const, text: "राज्य" }] },
  // Q96
  { textFr: "Quelle est l'une des voies possibles pour modifier la Constitution ?", lang: 'hi' as const, text: "संविधान में संशोधन के संभावित तरीकों में से एक क्या है?", explanation: "संविधान में जनमत संग्रह या कांग्रेस (राष्ट्रीय सभा और सीनेट की संयुक्त बैठक) द्वारा व्यक्त मतों के 3/5 बहुमत से संशोधन किया जा सकता है।", choices: [{ id: 'a' as const, text: "जनमत संग्रह या कांग्रेस (राष्ट्रीय सभा + सीनेट) द्वारा" }, { id: 'b' as const, text: "केवल गणराज्य के राष्ट्रपति के निर्णय से" }, { id: 'c' as const, text: "फ्रांस के मेयरों के मतदान से" }, { id: 'd' as const, text: "संवैधानिक परिषद के निर्णय से" }] },
  // Q97
  { textFr: "Qui assure l'intérim du président de la République en cas de décès ?", lang: 'hi' as const, text: "राष्ट्रपति की मृत्यु की स्थिति में कौन अंतरिम राष्ट्रपति की भूमिका निभाता है?", explanation: "सीनेट के अध्यक्ष रिक्ति (मृत्यु, त्यागपत्र) की स्थिति में गणराज्य के राष्ट्रपति का अंतरिम कार्यभार संभालते हैं। यह संविधान के अनुच्छेद 7 में प्रावधानित है।", choices: [{ id: 'a' as const, text: "सीनेट के अध्यक्ष" }, { id: 'b' as const, text: "प्रधानमंत्री" }, { id: 'c' as const, text: "राष्ट्रीय सभा के अध्यक्ष" }, { id: 'd' as const, text: "गृह मंत्री" }] },
  // Q98
  { textFr: "Quel est le rôle du Conseil constitutionnel ?", lang: 'hi' as const, text: "संवैधानिक परिषद की भूमिका क्या है?", explanation: "संवैधानिक परिषद कानूनों की संविधान के अनुरूपता की जाँच करती है। यह राष्ट्रपति चुनावों और जनमत संग्रहों की नियमितता की भी निगरानी करती है।", choices: [{ id: 'a' as const, text: "कानूनों की संविधान के अनुरूपता की जाँच करना" }, { id: 'b' as const, text: "कानून बनाना" }, { id: 'c' as const, text: "सरकार का नेतृत्व करना" }, { id: 'd' as const, text: "आपराधिक मामलों पर निर्णय लेना" }] },
  // Q99
  { textFr: "Quelle condition est obligatoire pour se présenter à l'élection présidentielle ?", lang: 'hi' as const, text: "राष्ट्रपति चुनाव में उम्मीदवार होने के लिए कौन सी शर्त अनिवार्य है?", explanation: "राष्ट्रपति चुनाव में उम्मीदवार होने के लिए कम से कम 30 विभिन्न विभागों या समुद्रपार क्षेत्रों से निर्वाचित प्रतिनिधियों के 500 हस्ताक्षर (समर्थन) प्राप्त करना आवश्यक है।", choices: [{ id: 'a' as const, text: "निर्वाचित प्रतिनिधियों के 500 समर्थन प्राप्त करना" }, { id: 'b' as const, text: "किसी राजनीतिक दल का सदस्य होना" }, { id: 'c' as const, text: "सांसद या सीनेटर रह चुका होना" }, { id: 'd' as const, text: "40 वर्ष से अधिक आयु का होना" }] },
  // Q100
  { textFr: "Comment est organisé le découpage administratif de la France ?", lang: 'hi' as const, text: "फ्रांस का प्रशासनिक विभाजन कैसे संगठित है?", explanation: "फ्रांस का प्रशासनिक विभाजन नगरपालिकाओं, विभागों और क्षेत्रों में संगठित है। स्थानीय प्राधिकरणों के ये तीन स्तर स्वतंत्र रूप से प्रशासित होते हैं।", choices: [{ id: 'a' as const, text: "नगरपालिकाओं, विभागों और क्षेत्रों में" }, { id: 'b' as const, text: "प्रांतों, कैंटनों और जिलों में" }, { id: 'c' as const, text: "शहरों, काउंटियों और संघीय राज्यों में" }, { id: 'd' as const, text: "केवल अरोंदिसमाँ और प्रीफेक्चरों में" }] },
  // Q101
  { textFr: "En quelle année la citoyenneté européenne a-t-elle été créée ?", lang: 'hi' as const, text: "यूरोपीय नागरिकता किस वर्ष बनाई गई थी?", explanation: "यूरोपीय नागरिकता 1992 में मास्ट्रिख्ट संधि द्वारा बनाई गई थी। यह यूरोपीय संघ के नागरिकों को स्वतंत्र आवागमन और किसी भी सदस्य राज्य में नगरपालिका और यूरोपीय चुनावों में मतदान का अधिकार जैसे अधिकार प्रदान करती है।", choices: [{ id: 'a' as const, text: "1992" }, { id: 'b' as const, text: "1957" }, { id: 'c' as const, text: "2000" }, { id: 'd' as const, text: "1985" }] },
  // Q102
  { textFr: "Qui a composé l'hymne de l'Union européenne ?", lang: 'hi' as const, text: "यूरोपीय संघ के राष्ट्रगान की रचना किसने की?", explanation: "यूरोपीय राष्ट्रगान \"आनंद का गीत\" है, जिसकी रचना लुडविग वान बीथोवन ने की। यह उनकी 9वीं सिम्फनी का अंतिम भाग है।", choices: [{ id: 'a' as const, text: "लुडविग वान बीथोवन" }, { id: 'b' as const, text: "वोल्फगैंग अमाडेउस मोज़ार्ट" }, { id: 'c' as const, text: "योहान सेबास्टियन बाख" }, { id: 'd' as const, text: "क्लाउद देबुसी" }] },
  // Q103
  { textFr: "Où est le siège de la Banque centrale européenne ?", lang: 'hi' as const, text: "यूरोपीय केंद्रीय बैंक का मुख्यालय कहाँ है?", explanation: "यूरोपीय केंद्रीय बैंक (ECB) का मुख्यालय जर्मनी के फ्रैंकफर्ट-ऑन-द-मेन में है। ECB यूरो क्षेत्र की मौद्रिक नीति के लिए जिम्मेदार है।", choices: [{ id: 'a' as const, text: "फ्रैंकफर्ट (जर्मनी) में" }, { id: 'b' as const, text: "ब्रसेल्स (बेल्जियम) में" }, { id: 'c' as const, text: "लक्समबर्ग में" }, { id: 'd' as const, text: "पेरिस (फ्रांस) में" }] },
  // Q104
  { textFr: "Qui siège au Parlement européen ?", lang: 'hi' as const, text: "यूरोपीय संसद में कौन बैठता है?", explanation: "यूरोपीय सांसद यूरोपीय संसद में बैठते हैं। वे यूरोपीय संघ के सदस्य राज्यों के नागरिकों द्वारा प्रत्यक्ष सार्वभौमिक मताधिकार से चुने जाते हैं।", choices: [{ id: 'a' as const, text: "यूरोपीय संघ के नागरिकों द्वारा चुने गए यूरोपीय सांसद" }, { id: 'b' as const, text: "सदस्य देशों के राष्ट्र प्रमुख" }, { id: 'c' as const, text: "विदेश मंत्री" }, { id: 'd' as const, text: "सदस्य देशों के राजदूत" }] },
];
