export const theme4Fa = [
  // Q1
  { textFr: "En quelle année a débuté la Révolution française ?", lang: 'fa' as const, text: "انقلاب فرانسه در چه سالی آغاز شد؟", explanation: "انقلاب فرانسه در سال ۱۷۸۹ با سقوط زندان باستیل در ۱۴ ژوئیه آغاز شد. این رویداد پایان رژیم قدیم و آغاز دوران تحولات عمیق سیاسی و اجتماعی در فرانسه را رقم زد.", choices: [{ id: 'a' as const, text: "۱۷۸۹" }, { id: 'b' as const, text: "۱۷۹۹" }, { id: 'c' as const, text: "۱۷۷۶" }, { id: 'd' as const, text: "۱۸۱۵" }] },
  // Q2
  { textFr: "Qui était Napoléon Ier ?", lang: 'fa' as const, text: "ناپلئون اول چه کسی بود؟", explanation: "ناپلئون اول امپراتور فرانسه از سال ۱۸۰۴ تا ۱۸۱۴ و سپس به‌طور مختصر در سال ۱۸۱۵ بود. او نظام اداری فرانسه را مدرن کرد و قانون مدنی را بنیان نهاد که هنوز هم معتبر است.", choices: [{ id: 'a' as const, text: "نخستین امپراتور فرانسه" }, { id: 'b' as const, text: "آخرین پادشاه فرانسه" }, { id: 'c' as const, text: "بنیان‌گذار جمهوری پنجم" }, { id: 'd' as const, text: "یک ژنرال جنگ جهانی اول" }] },
  // Q3
  { textFr: "Lequel de ces personnages historiques est français ?", lang: 'fa' as const, text: "کدام یک از این شخصیت‌های تاریخی فرانسوی است؟", explanation: "ژان دارک یکی از چهره‌های نمادین تاریخ فرانسه است. او در قرن پانزدهم ارتش فرانسه را در جنگ صدساله علیه انگلیسی‌ها رهبری کرد.", choices: [{ id: 'a' as const, text: "ژان دارک" }, { id: 'b' as const, text: "کریستف کلمب" }, { id: 'c' as const, text: "وینستون چرچیل" }, { id: 'd' as const, text: "لئوناردو داوینچی" }] },
  // Q4
  { textFr: "Dans quelle République est-on aujourd'hui ?", lang: 'fa' as const, text: "امروزه در کدام جمهوری هستیم؟", explanation: "فرانسه در حال حاضر تحت جمهوری پنجم است که در سال ۱۹۵۸ توسط ژنرال دوگل تأسیس شد. این جمهوری قدرت رئیس‌جمهور را تقویت کرد.", choices: [{ id: 'a' as const, text: "جمهوری پنجم" }, { id: 'b' as const, text: "جمهوری چهارم" }, { id: 'c' as const, text: "جمهوری سوم" }, { id: 'd' as const, text: "جمهوری ششم" }] },
  // Q5
  { textFr: "Qu'est-ce que la Shoah ?", lang: 'fa' as const, text: "شوآ چیست؟", explanation: "شوآ به نسل‌کشی یهودیان اروپا توسط آلمان نازی در جنگ جهانی دوم اشاره دارد. حدود شش میلیون یهودی بین سال‌های ۱۹۴۱ تا ۱۹۴۵ قتل‌عام شدند.", choices: [{ id: 'a' as const, text: "نسل‌کشی یهودیان در جنگ جهانی دوم" }, { id: 'b' as const, text: "یک نبرد در جنگ جهانی اول" }, { id: 'c' as const, text: "یک پیمان صلح اروپایی" }, { id: 'd' as const, text: "مقاومت فرانسه علیه اشغال" }] },
  // Q6
  { textFr: "Quel pays ou région du monde a été colonisé par la France ?", lang: 'fa' as const, text: "کدام کشور یا منطقه جهان توسط فرانسه استعمار شد؟", explanation: "الجزایر از سال ۱۸۳۰ تا ۱۹۶۲ مستعمره فرانسه بود. این مهم‌ترین مستعمره فرانسه در شمال آفریقا بود و استقلال آن پس از یک جنگ طولانی به دست آمد.", choices: [{ id: 'a' as const, text: "الجزایر" }, { id: 'b' as const, text: "برزیل" }, { id: 'c' as const, text: "هند" }, { id: 'd' as const, text: "استرالیا" }] },
  // Q7
  { textFr: "Qui a rendu l'école gratuite, laïque et obligatoire ?", lang: 'fa' as const, text: "چه کسی مدرسه را رایگان، لائیک و اجباری کرد؟", explanation: "ژول فری، وزیر آموزش عمومی، قوانین ۱۸۸۱-۱۸۸۲ را به تصویب رساند که آموزش ابتدایی را رایگان، لائیک و اجباری کرد. این قوانین یکی از ارکان جمهوری فرانسه هستند.", choices: [{ id: 'a' as const, text: "ژول فری" }, { id: 'b' as const, text: "ویکتور هوگو" }, { id: 'c' as const, text: "ناپلئون بناپارت" }, { id: 'd' as const, text: "شارل دوگل" }] },
  // Q8
  { textFr: "Quand a eu lieu la Seconde Guerre mondiale ?", lang: 'fa' as const, text: "جنگ جهانی دوم چه زمانی رخ داد؟", explanation: "جنگ جهانی دوم از سال ۱۹۳۹ تا ۱۹۴۵ ادامه داشت. این جنگ جهانی بیشتر کشورها را درگیر کرد و میلیون‌ها قربانی بر جای گذاشت.", choices: [{ id: 'a' as const, text: "۱۹۳۹-۱۹۴۵" }, { id: 'b' as const, text: "۱۹۱۴-۱۹۱۸" }, { id: 'c' as const, text: "۱۸۷۰-۱۸۷۱" }, { id: 'd' as const, text: "۱۹۵۰-۱۹۵۳" }] },
  // Q9
  { textFr: "Quand a eu lieu la Première Guerre mondiale ?", lang: 'fa' as const, text: "جنگ جهانی اول چه زمانی رخ داد؟", explanation: "جنگ جهانی اول از سال ۱۹۱۴ تا ۱۹۱۸ ادامه داشت. این جنگ عمدتاً قدرت‌های اتحاد سه‌گانه را در برابر امپراتوری‌های مرکزی قرار داد.", choices: [{ id: 'a' as const, text: "۱۹۱۴-۱۹۱۸" }, { id: 'b' as const, text: "۱۹۳۹-۱۹۴۵" }, { id: 'c' as const, text: "۱۸۷۰-۱۸۷۱" }, { id: 'd' as const, text: "۱۸۹۹-۱۹۰۲" }] },
  // Q10
  { textFr: "En quelle année a été créée la Communauté Économique Européenne (CEE) ?", lang: 'fa' as const, text: "جامعه اقتصادی اروپا (CEE) در چه سالی تأسیس شد؟", explanation: "جامعه اقتصادی اروپا در سال ۱۹۵۷ با پیمان رم توسط شش کشور بنیان‌گذار از جمله فرانسه ایجاد شد. این سازمان پیش‌نیاز اتحادیه اروپای کنونی است.", choices: [{ id: 'a' as const, text: "۱۹۵۷" }, { id: 'b' as const, text: "۱۹۴۵" }, { id: 'c' as const, text: "۱۹۶۲" }, { id: 'd' as const, text: "۱۹۵۱" }] },
  // Q11
  { textFr: "Le 11 novembre est un jour férié. À quoi correspond cette date ?", lang: 'fa' as const, text: "۱۱ نوامبر یک روز تعطیل رسمی است. این تاریخ به چه چیزی مربوط می‌شود؟", explanation: "۱۱ نوامبر ۱۹۱۸ نشان‌دهنده آتش‌بس جنگ جهانی اول است. این روز تعطیل رسمی پایان جنگ را گرامی می‌دارد و به سربازانی که برای فرانسه جان باختند ادای احترام می‌کند.", choices: [{ id: 'a' as const, text: "آتش‌بس جنگ جهانی اول" }, { id: 'b' as const, text: "پایان جنگ جهانی دوم" }, { id: 'c' as const, text: "روز ملی فرانسه" }, { id: 'd' as const, text: "اعلام جمهوری" }] },
  // Q12
  { textFr: "Qui a été le premier Président élu sous la Ve République ?", lang: 'fa' as const, text: "چه کسی اولین رئیس‌جمهور منتخب جمهوری پنجم بود؟", explanation: "شارل دوگل اولین رئیس‌جمهور جمهوری پنجم بود که در سال ۱۹۵۸ انتخاب شد. او بنیان‌گذار این نظام بود و دو دوره ریاست‌جمهوری داشت.", choices: [{ id: 'a' as const, text: "شارل دوگل" }, { id: 'b' as const, text: "فرانسوا میتران" }, { id: 'c' as const, text: "ژرژ پمپیدو" }, { id: 'd' as const, text: "رنه کوتی" }] },
  // Q13
  { textFr: "En quelle année l'esclavage a-t-il été aboli définitivement en France ?", lang: 'fa' as const, text: "بردگی در چه سالی به‌طور قطعی در فرانسه لغو شد؟", explanation: "بردگی در سال ۱۸۴۸ به‌طور قطعی در فرانسه به همت ویکتور شولشر لغو شد. اولین فرمان لغو بردگی در سال ۱۷۹۴ صادر شده بود اما ناپلئون آن را در سال ۱۸۰۲ بازگرداند.", choices: [{ id: 'a' as const, text: "۱۸۴۸" }, { id: 'b' as const, text: "۱۷۸۹" }, { id: 'c' as const, text: "۱۸۶۵" }, { id: 'd' as const, text: "۱۷۹۴" }] },
  // Q14
  { textFr: "Depuis quelle année l'école publique est-elle gratuite ?", lang: 'fa' as const, text: "مدرسه دولتی از چه سالی رایگان است؟", explanation: "مدرسه دولتی از سال ۱۸۸۱ به لطف قوانین ژول فری رایگان شد. این قوانین همچنین آموزش ابتدایی را اجباری و لائیک کردند.", choices: [{ id: 'a' as const, text: "۱۸۸۱" }, { id: 'b' as const, text: "۱۷۸۹" }, { id: 'c' as const, text: "۱۹۰۵" }, { id: 'd' as const, text: "۱۸۴۸" }] },
  // Q15
  { textFr: "Combien y a-t-il eu de républiques en France ?", lang: 'fa' as const, text: "فرانسه چند جمهوری داشته است؟", explanation: "فرانسه پنج جمهوری داشته است. جمهوری اول در سال ۱۷۹۲ اعلام شد و جمهوری پنجم که در سال ۱۹۵۸ تأسیس شد نظام کنونی فرانسه است.", choices: [{ id: 'a' as const, text: "پنج" }, { id: 'b' as const, text: "سه" }, { id: 'c' as const, text: "چهار" }, { id: 'd' as const, text: "شش" }] },
  // Q16
  { textFr: "Qui était le roi de France au moment de la Révolution française ?", lang: 'fa' as const, text: "در زمان انقلاب فرانسه چه کسی پادشاه فرانسه بود؟", explanation: "لوئی شانزدهم در زمان انقلاب فرانسه در سال ۱۷۸۹ پادشاه فرانسه بود. او سرنگون و سپس در سال ۱۷۹۳ گردن زده شد.", choices: [{ id: 'a' as const, text: "لوئی شانزدهم" }, { id: 'b' as const, text: "لوئی چهاردهم" }, { id: 'c' as const, text: "لوئی پانزدهم" }, { id: 'd' as const, text: "هانری چهارم" }] },
  // Q17
  { textFr: "Qui a fondé la Ve République ?", lang: 'fa' as const, text: "چه کسی جمهوری پنجم را بنیان نهاد؟", explanation: "ژنرال شارل دوگل جمهوری پنجم را در سال ۱۹۵۸ بنیان نهاد. او اولین رئیس‌جمهور آن بود و قانون اساسی‌ای را وضع کرد که قدرت اجرایی را تقویت می‌کرد.", choices: [{ id: 'a' as const, text: "ژنرال دوگل" }, { id: 'b' as const, text: "فرانسوا میتران" }, { id: 'c' as const, text: "ناپلئون سوم" }, { id: 'd' as const, text: "لئون بلوم" }] },
  // Q18
  { textFr: "Que célèbre-t-on le 14 juillet ?", lang: 'fa' as const, text: "۱۴ ژوئیه چه چیزی جشن گرفته می‌شود؟", explanation: "۱۴ ژوئیه روز ملی فرانسه است. این روز یادبود سقوط باستیل در سال ۱۷۸۹ و جشن فدراسیون ۱۷۹۰ است که نماد آزادی و وحدت ملی هستند.", choices: [{ id: 'a' as const, text: "روز ملی، سالگرد سقوط باستیل" }, { id: 'b' as const, text: "آتش‌بس ۱۹۱۸" }, { id: 'c' as const, text: "پایان جنگ جهانی دوم" }, { id: 'd' as const, text: "لغو بردگی" }] },
  // Q19
  { textFr: "Quelle guerre a eu lieu entre 1914 et 1918 ?", lang: 'fa' as const, text: "چه جنگی بین سال‌های ۱۹۱۴ و ۱۹۱۸ رخ داد؟", explanation: "جنگ جهانی اول از سال ۱۹۱۴ تا ۱۹۱۸ ادامه داشت. این جنگ متفقین را در برابر امپراتوری‌های مرکزی قرار داد و میلیون‌ها کشته بر جای گذاشت.", choices: [{ id: 'a' as const, text: "جنگ جهانی اول" }, { id: 'b' as const, text: "جنگ جهانی دوم" }, { id: 'c' as const, text: "جنگ فرانسه و پروس" }, { id: 'd' as const, text: "جنگ الجزایر" }] },
  // Q20
  { textFr: "Pourquoi l'année 1958 est importante pour la France ?", lang: 'fa' as const, text: "چرا سال ۱۹۵۸ برای فرانسه مهم است؟", explanation: "سال ۱۹۵۸ نشان‌دهنده تأسیس جمهوری پنجم توسط ژنرال دوگل است. قانون اساسی جدیدی تصویب شد که نظام سیاسی فعلی فرانسه را بنا نهاد.", choices: [{ id: 'a' as const, text: "سال تأسیس جمهوری پنجم است" }, { id: 'b' as const, text: "سال پایان جنگ جهانی دوم است" }, { id: 'c' as const, text: "سال لغو بردگی است" }, { id: 'd' as const, text: "سال انقلاب فرانسه است" }] },
  // Q21
  { textFr: "Quel fleuve coule en France ?", lang: 'fa' as const, text: "کدام رود در فرانسه جاری است؟", explanation: "لوآر طولانی‌ترین رود فرانسه با حدود ۱۰۱۲ کیلومتر است. این رود از مرکز فرانسه از ماسیف سانترال تا اقیانوس اطلس جریان دارد.", choices: [{ id: 'a' as const, text: "لوآر" }, { id: 'b' as const, text: "دانوب" }, { id: 'c' as const, text: "نیل" }, { id: 'd' as const, text: "آمازون" }] },
  // Q22
  { textFr: "Quelle ville est française ?", lang: 'fa' as const, text: "کدام شهر فرانسوی است؟", explanation: "لیون یک شهر بزرگ فرانسوی و مرکز منطقه اورن-رون-آلپ است. این شهر سومین شهر بزرگ فرانسه پس از پاریس و مارسی است.", choices: [{ id: 'a' as const, text: "لیون" }, { id: 'b' as const, text: "ژنو" }, { id: 'c' as const, text: "بروکسل" }, { id: 'd' as const, text: "بارسلون" }] },
  // Q23
  { textFr: "Quel océan borde la côte ouest française ?", lang: 'fa' as const, text: "کدام اقیانوس ساحل غربی فرانسه را در بر می‌گیرد؟", explanation: "اقیانوس اطلس ساحل غربی فرانسه متروپل را در بر می‌گیرد. از برتانی تا سرزمین باسک، این نوار ساحلی صدها کیلومتر امتداد دارد.", choices: [{ id: 'a' as const, text: "اقیانوس اطلس" }, { id: 'b' as const, text: "اقیانوس آرام" }, { id: 'c' as const, text: "اقیانوس هند" }, { id: 'd' as const, text: "اقیانوس منجمد شمالی" }] },
  // Q24
  { textFr: "Qu'est-ce que Paris ?", lang: 'fa' as const, text: "پاریس چیست؟", explanation: "پاریس پایتخت فرانسه و مرکز سیاسی، اقتصادی و فرهنگی آن است. همچنین پرجمعیت‌ترین شهر کشور است.", choices: [{ id: 'a' as const, text: "پایتخت فرانسه" }, { id: 'b' as const, text: "یک منطقه فرانسه" }, { id: 'c' as const, text: "یک استان فرادریایی" }, { id: 'd' as const, text: "پایتخت اروپا" }] },
  // Q25
  { textFr: "Quelle est la capitale de la France ?", lang: 'fa' as const, text: "پایتخت فرانسه کجاست؟", explanation: "پاریس قرن‌هاست که پایتخت فرانسه است. این شهر محل نهادهای اصلی دولت از جمله کاخ الیزه و مجلس ملی است.", choices: [{ id: 'a' as const, text: "پاریس" }, { id: 'b' as const, text: "لیون" }, { id: 'c' as const, text: "مارسی" }, { id: 'd' as const, text: "استراسبورگ" }] },
  // Q26
  { textFr: "Sur quel continent se situe la France métropolitaine ?", lang: 'fa' as const, text: "فرانسه متروپل در کدام قاره قرار دارد؟", explanation: "فرانسه متروپل در قاره اروپا واقع شده است. در غرب با اقیانوس اطلس، در جنوب با دریای مدیترانه و در شمال با کانال مانش هم‌مرز است.", choices: [{ id: 'a' as const, text: "اروپا" }, { id: 'b' as const, text: "آفریقا" }, { id: 'c' as const, text: "آمریکا" }, { id: 'd' as const, text: "آسیا" }] },
  // Q27
  { textFr: "Quelle île est un département d'outre-mer français ?", lang: 'fa' as const, text: "کدام جزیره یک استان فرادریایی فرانسه است؟", explanation: "مارتینیک یک استان و منطقه فرادریایی فرانسه واقع در آنتیل است. این جزیره بخش جدایی‌ناپذیری از جمهوری فرانسه است.", choices: [{ id: 'a' as const, text: "مارتینیک" }, { id: 'b' as const, text: "کوبا" }, { id: 'c' as const, text: "جامائیکا" }, { id: 'd' as const, text: "هائیتی" }] },
  // Q28
  { textFr: "Combien y a-t-il de régions en France métropolitaine ?", lang: 'fa' as const, text: "فرانسه متروپل چند منطقه دارد؟", explanation: "از زمان اصلاحات سرزمینی ۲۰۱۶، فرانسه متروپل ۱۳ منطقه دارد. این تعداد از ۲۲ به ۱۳ کاهش یافت تا کارایی نهادهای محلی تقویت شود.", choices: [{ id: 'a' as const, text: "۱۳" }, { id: 'b' as const, text: "۱۸" }, { id: 'c' as const, text: "۲۲" }, { id: 'd' as const, text: "۱۰" }] },
  // Q29
  { textFr: "Quelle ville est un grand port maritime ?", lang: 'fa' as const, text: "کدام شهر یک بندر بزرگ دریایی است؟", explanation: "مارسی بزرگ‌ترین بندر دریایی فرانسه و یکی از مهم‌ترین بنادر مدیترانه است. همچنین دومین شهر بزرگ فرانسه است.", choices: [{ id: 'a' as const, text: "مارسی" }, { id: 'b' as const, text: "کلرمون‌فران" }, { id: 'c' as const, text: "گرنوبل" }, { id: 'd' as const, text: "لیموژ" }] },
  // Q30
  { textFr: "Quelle est la mer au sud de la France métropolitaine ?", lang: 'fa' as const, text: "دریای جنوب فرانسه متروپل کدام است؟", explanation: "دریای مدیترانه جنوب فرانسه متروپل را در بر می‌گیرد. این دریا از مرز اسپانیا تا مرز ایتالیا، در امتداد ساحل آزور و لانگدوک کشیده شده است.", choices: [{ id: 'a' as const, text: "دریای مدیترانه" }, { id: 'b' as const, text: "دریای شمال" }, { id: 'c' as const, text: "دریای بالتیک" }, { id: 'd' as const, text: "کانال مانش" }] },
  // Q31
  { textFr: "Quelle ville est située au bord de la mer Méditerranée ?", lang: 'fa' as const, text: "کدام شهر در کنار دریای مدیترانه واقع شده است؟", explanation: "نیس شهری واقع در ساحل آزور در کنار دریای مدیترانه است. این شهر یکی از مقاصد اصلی گردشگری جنوب فرانسه است.", choices: [{ id: 'a' as const, text: "نیس" }, { id: 'b' as const, text: "لیل" }, { id: 'c' as const, text: "استراسبورگ" }, { id: 'd' as const, text: "رن" }] },
  // Q32
  { textFr: "Où se situe la Corse ?", lang: 'fa' as const, text: "کُرس کجا واقع شده است؟", explanation: "کُرس جزیره‌ای در دریای مدیترانه در جنوب شرقی فرانسه متروپل است. این جزیره یک واحد سرزمینی ویژه با وضعیت خاص است.", choices: [{ id: 'a' as const, text: "در دریای مدیترانه" }, { id: 'b' as const, text: "در اقیانوس اطلس" }, { id: 'c' as const, text: "در کانال مانش" }, { id: 'd' as const, text: "در دریای شمال" }] },
  // Q33
  { textFr: "Quelle chaîne de montagnes est située entre la France et l'Italie ?", lang: 'fa' as const, text: "کدام رشته‌کوه بین فرانسه و ایتالیا قرار دارد؟", explanation: "آلپ مرز طبیعی بین فرانسه و ایتالیا را تشکیل می‌دهد. مون‌بلان واقع در آلپ با ارتفاع ۴۸۰۹ متر بلندترین قله اروپای غربی است.", choices: [{ id: 'a' as const, text: "آلپ" }, { id: 'b' as const, text: "پیرنه" }, { id: 'c' as const, text: "ژورا" }, { id: 'd' as const, text: "ووژ" }] },
  // Q34
  { textFr: "Qui était Molière ?", lang: 'fa' as const, text: "مولیر چه کسی بود؟", explanation: "مولیر (۱۶۲۲-۱۶۷۳) نمایشنامه‌نویس و بازیگر فرانسوی قرن هفدهم بود. او نویسنده کمدی‌های معروفی مانند «بیمار خیالی» و «مردم‌گریز» است.", choices: [{ id: 'a' as const, text: "نمایشنامه‌نویس و بازیگر فرانسوی قرن هفدهم" }, { id: 'b' as const, text: "نقاش دوره رنسانس" }, { id: 'c' as const, text: "آهنگساز موسیقی کلاسیک" }, { id: 'd' as const, text: "فیلسوف عصر روشنگری" }] },
  // Q35
  { textFr: "Qui était Charles Baudelaire ?", lang: 'fa' as const, text: "شارل بودلر چه کسی بود؟", explanation: "شارل بودلر (۱۸۲۱-۱۸۶۷) شاعر فرانسوی و نویسنده مجموعه شعر معروف «گل‌های بدی» بود. او یکی از پیشگامان شعر مدرن محسوب می‌شود.", choices: [{ id: 'a' as const, text: "شاعر فرانسوی، نویسنده گل‌های بدی" }, { id: 'b' as const, text: "رمان‌نویس، نویسنده بینوایان" }, { id: 'c' as const, text: "مجسمه‌ساز قرن نوزدهم" }, { id: 'd' as const, text: "موسیقیدان رمانتیک" }] },
  // Q36
  { textFr: "Qui était George Sand ?", lang: 'fa' as const, text: "ژرژ ساند چه کسی بود؟", explanation: "ژرژ ساند (۱۸۰۴-۱۸۷۶) رمان‌نویس فرانسوی بود که نام اصلی‌اش آمانتین لوسیل اورور دوپن بود. او به خاطر رمان‌های روستایی و تلاش‌هایش برای حقوق زنان شناخته شده است.", choices: [{ id: 'a' as const, text: "رمان‌نویس فرانسوی قرن نوزدهم" }, { id: 'b' as const, text: "ملکه فرانسه" }, { id: 'c' as const, text: "دانشمند برنده جایزه نوبل" }, { id: 'd' as const, text: "خواننده اپرا" }] },
  // Q37
  { textFr: "Qui était Simone de Beauvoir ?", lang: 'fa' as const, text: "سیمون دو بووار چه کسی بود؟", explanation: "سیمون دو بووار (۱۹۰۸-۱۹۸۶) فیلسوف و نویسنده فرانسوی و چهره برجسته فمینیسم بود. او به‌ویژه نویسنده کتاب «جنس دوم» است که اثری بنیادین در فمینیسم مدرن محسوب می‌شود.", choices: [{ id: 'a' as const, text: "فیلسوف و نویسنده فمینیست فرانسوی" }, { id: 'b' as const, text: "مقاومت‌کننده جنگ جهانی دوم" }, { id: 'c' as const, text: "فیزیکدان فرانسوی" }, { id: 'd' as const, text: "بازیگر سینمای فرانسه" }] },
  // Q38
  { textFr: "Qui était Albert Camus ?", lang: 'fa' as const, text: "آلبر کامو چه کسی بود؟", explanation: "آلبر کامو (۱۹۱۳-۱۹۶۰) نویسنده و فیلسوف فرانسوی و برنده جایزه نوبل ادبیات در سال ۱۹۵۷ بود. او نویسنده «بیگانه» و «طاعون» است.", choices: [{ id: 'a' as const, text: "نویسنده و فیلسوف فرانسوی، برنده جایزه نوبل ادبیات" }, { id: 'b' as const, text: "نقاش امپرسیونیست" }, { id: 'c' as const, text: "سیاستمدار جمهوری سوم" }, { id: 'd' as const, text: "آهنگساز موسیقی کلاسیک" }] },
  // Q39
  { textFr: "Qui était Paul Cézanne ?", lang: 'fa' as const, text: "پل سزان چه کسی بود؟", explanation: "پل سزان (۱۸۳۹-۱۹۰۶) نقاش فرانسوی بود که پدر هنر مدرن شناخته می‌شود. آثار او بر کوبیسم و بسیاری از جنبش‌های هنری قرن بیستم تأثیر گذاشت.", choices: [{ id: 'a' as const, text: "نقاش فرانسوی، پیشگام هنر مدرن" }, { id: 'b' as const, text: "نویسنده ناتورالیست" }, { id: 'c' as const, text: "مجسمه‌ساز قرن هجدهم" }, { id: 'd' as const, text: "معمار دوره رنسانس" }] },
  // Q40
  { textFr: "Qui était Marc Chagall ?", lang: 'fa' as const, text: "مارک شاگال چه کسی بود؟", explanation: "مارک شاگال (۱۸۸۷-۱۹۸۵) نقاش و حکاک روس‌تبار بود که تابعیت فرانسه گرفت. او به خاطر آثار رنگارنگ خود با ترکیبی از خیال و نمادگرایی، به‌ویژه شیشه‌های رنگی اپرای پاریس مشهور است.", choices: [{ id: 'a' as const, text: "نقاش روس‌تبار با تابعیت فرانسوی" }, { id: 'b' as const, text: "فیلسوف فرانسوی عصر روشنگری" }, { id: 'c' as const, text: "موسیقیدان کلاسیک اتریشی" }, { id: 'd' as const, text: "کارگردان سینمای ایتالیایی" }] },
  // Q41
  { textFr: "Qui était Joséphine Baker ?", lang: 'fa' as const, text: "ژوزفین بیکر چه کسی بود؟", explanation: "ژوزفین بیکر (۱۹۰۶-۱۹۷۵) هنرمند فرانسوی-آمریکایی، خواننده، رقصنده و مقاومت‌کننده در جنگ جهانی دوم بود. او در سال ۲۰۲۱ به خاطر تلاش‌هایش به پانتئون منتقل شد.", choices: [{ id: 'a' as const, text: "هنرمند فرانسوی-آمریکایی، خواننده، رقصنده و مقاومت‌کننده" }, { id: 'b' as const, text: "دانشمند فرانسوی-لهستانی" }, { id: 'c' as const, text: "سیاستمدار فرانسوی" }, { id: 'd' as const, text: "رمان‌نویس قرن نوزدهم" }] },
  // Q42
  { textFr: "Qui était une chanteuse française célèbre ?", lang: 'fa' as const, text: "چه کسی خواننده مشهور فرانسوی بود؟", explanation: "ادیت پیاف (۱۹۱۵-۱۹۶۳) یکی از مشهورترین خوانندگان فرانسوی در جهان است. او به خاطر ترانه‌هایی مانند «زندگی در رنگ صورتی» و «نه، پشیمان نیستم» شناخته می‌شود.", choices: [{ id: 'a' as const, text: "ادیت پیاف" }, { id: 'b' as const, text: "مدونا" }, { id: 'c' as const, text: "بیانسه" }, { id: 'd' as const, text: "ادل" }] },
  // Q43
  { textFr: "Qu'est-ce que le Louvre ?", lang: 'fa' as const, text: "لوور چیست؟", explanation: "لوور بزرگ‌ترین موزه هنری جهان است که در پاریس واقع شده. این کاخ سلطنتی سابق آثار مشهوری مانند مونالیزای لئوناردو داوینچی را در خود جای داده است.", choices: [{ id: 'a' as const, text: "بزرگ‌ترین موزه هنری جهان، واقع در پاریس" }, { id: 'b' as const, text: "یک قصر در دره لوآر" }, { id: 'c' as const, text: "یک کلیسای گوتیک" }, { id: 'd' as const, text: "یک تئاتر ملی" }] },
  // Q44
  { textFr: "Qui était Jean de la Fontaine ?", lang: 'fa' as const, text: "ژان دو لافونتن چه کسی بود؟", explanation: "ژان دو لافونتن (۱۶۲۱-۱۶۹۵) شاعر فرانسوی بود که به خاطر حکایت‌هایش مشهور است. آثار او مانند «کلاغ و روباه» هنوز هم در مدارس فرانسه تدریس می‌شوند.", choices: [{ id: 'a' as const, text: "شاعر فرانسوی مشهور به خاطر حکایت‌هایش" }, { id: 'b' as const, text: "یک پادشاه فرانسه" }, { id: 'c' as const, text: "یک نقاش دوره رنسانس" }, { id: 'd' as const, text: "یک کاشف دنیای نو" }] },
  // Q45
  { textFr: "Quel écrivain est français ?", lang: 'fa' as const, text: "کدام نویسنده فرانسوی است؟", explanation: "ویکتور هوگو (۱۸۰۲-۱۸۸۵) یکی از بزرگ‌ترین نویسندگان فرانسوی است. او نویسنده شاهکارهایی مانند «بینوایان» و «گوژپشت نتردام» است.", choices: [{ id: 'a' as const, text: "ویکتور هوگو" }, { id: 'b' as const, text: "چارلز دیکنز" }, { id: 'c' as const, text: "میگل دو سروانتس" }, { id: 'd' as const, text: "ویلیام شکسپیر" }] },
  // Q46
  { textFr: "Dans quelle ville se trouve la tour Eiffel ?", lang: 'fa' as const, text: "برج ایفل در کدام شهر قرار دارد؟", explanation: "برج ایفل در پاریس قرار دارد. این برج توسط گوستاو ایفل برای نمایشگاه جهانی ۱۸۸۹ ساخته شد و به نمادین‌ترین بنای فرانسه تبدیل شده است.", choices: [{ id: 'a' as const, text: "پاریس" }, { id: 'b' as const, text: "لیون" }, { id: 'c' as const, text: "مارسی" }, { id: 'd' as const, text: "بوردو" }] },
  // Q47
  { textFr: "Quand célèbre-t-on Noël ?", lang: 'fa' as const, text: "کریسمس چه زمانی جشن گرفته می‌شود؟", explanation: "کریسمس در ۲۵ دسامبر جشن گرفته می‌شود. این روز در فرانسه تعطیل رسمی است و یک جشن مسیحی که به سنتی فرهنگی نیز تبدیل شده و با غذای خانوادگی و تبادل هدایا همراه است.", choices: [{ id: 'a' as const, text: "۲۵ دسامبر" }, { id: 'b' as const, text: "۱ ژانویه" }, { id: 'c' as const, text: "۱۴ ژوئیه" }, { id: 'd' as const, text: "۱ نوامبر" }] },
  // Q48
  { textFr: "Quel était le surnom de Louis XIV ?", lang: 'fa' as const, text: "لقب لوئی چهاردهم چه بود؟", explanation: "لوئی چهاردهم به «شاه خورشید» ملقب بود. او از ۱۶۴۳ تا ۱۷۱۵ یعنی ۷۲ سال حکومت کرد که طولانی‌ترین دوره حکومت در تاریخ فرانسه است و کاخ ورسای را بنا کرد.", choices: [{ id: 'a' as const, text: "شاه خورشید" }, { id: 'b' as const, text: "شاه شاهان" }, { id: 'c' as const, text: "محبوب" }, { id: 'd' as const, text: "بزرگ" }] },
  // Q49
  { textFr: "Quel roi de France a été exécuté pendant la Révolution française ?", lang: 'fa' as const, text: "کدام پادشاه فرانسه در دوران انقلاب فرانسه اعدام شد؟", explanation: "لوئی شانزدهم در ۲۱ ژانویه ۱۷۹۳ در میدان انقلاب پاریس با گیوتین اعدام شد. او توسط مجلس ملی محاکمه و به خیانت محکوم شده بود.", choices: [{ id: 'a' as const, text: "لوئی شانزدهم" }, { id: 'b' as const, text: "لوئی چهاردهم" }, { id: 'c' as const, text: "لوئی پانزدهم" }, { id: 'd' as const, text: "شارل دهم" }] },
  // Q50
  { textFr: "En quelle année Napoléon Ier est-il devenu empereur ?", lang: 'fa' as const, text: "ناپلئون اول در چه سالی امپراتور شد؟", explanation: "ناپلئون اول در سال ۱۸۰۴ امپراتور فرانسه شد. مراسم تاجگذاری او در ۲ دسامبر ۱۸۰۴ در کلیسای نتردام پاریس برگزار شد.", choices: [{ id: 'a' as const, text: "۱۸۰۴" }, { id: 'b' as const, text: "۱۷۸۹" }, { id: 'c' as const, text: "۱۷۹۹" }, { id: 'd' as const, text: "۱۸۱۵" }] },
  // Q51
  { textFr: "Lequel de ces personnages a un lien avec la République française ?", lang: 'fa' as const, text: "کدام یک از این شخصیت‌ها با جمهوری فرانسه ارتباط دارد؟", explanation: "ماریان نماد تمثیلی جمهوری فرانسه است. او نماد ارزش‌های آزادی، برابری و برادری است و مجسمه نیم‌تنه او در تمام شهرداری‌ها وجود دارد.", choices: [{ id: 'a' as const, text: "ماریان" }, { id: 'b' as const, text: "بریتانیا" }, { id: 'c' as const, text: "عمو سام" }, { id: 'd' as const, text: "جان بول" }] },
  // Q52
  { textFr: "De quand date l'appel à la résistance du général de Gaulle ?", lang: 'fa' as const, text: "فراخوان مقاومت ژنرال دوگل از چه تاریخی است؟", explanation: "فراخوان ژنرال دوگل مربوط به ۱۸ ژوئن ۱۹۴۰ است. او از لندن و از طریق بی‌بی‌سی فرانسویان را به مقاومت علیه اشغال آلمان فراخواند.", choices: [{ id: 'a' as const, text: "۱۸ ژوئن ۱۹۴۰" }, { id: 'b' as const, text: "۸ مه ۱۹۴۵" }, { id: 'c' as const, text: "۱۴ ژوئیه ۱۹۴۰" }, { id: 'd' as const, text: "۲۵ اوت ۱۹۴۴" }] },
  // Q53
  { textFr: "Pourquoi la Shoah est-elle étudiée à l'école ?", lang: 'fa' as const, text: "چرا شوآ در مدرسه آموزش داده می‌شود؟", explanation: "شوآ در مدرسه آموزش داده می‌شود تا خاطره این نسل‌کشی حفظ شود و دانش‌آموزان نسبت به وظیفه یادآوری حساس شوند. این امر به مبارزه با نژادپرستی، یهودستیزی و هر شکلی از تبعیض کمک می‌کند.", choices: [{ id: 'a' as const, text: "برای وظیفه یادآوری و مبارزه با نژادپرستی و یهودستیزی" }, { id: 'b' as const, text: "برای آماده‌سازی دانش‌آموزان برای امتحانات تاریخ" }, { id: 'c' as const, text: "برای آموزش جغرافیای اروپا" }, { id: 'd' as const, text: "برای مطالعه اقتصاد جنگ" }] },
  // Q54
  { textFr: "Quel pays a été colonisé par la France ?", lang: 'fa' as const, text: "کدام کشور توسط فرانسه استعمار شد؟", explanation: "سنگال یکی از مستعمرات فرانسه در آفریقای غربی بود. این کشور در سال ۱۹۶۰ مانند بسیاری از کشورهای فرانسوی‌زبان آفریقایی به استقلال رسید.", choices: [{ id: 'a' as const, text: "سنگال" }, { id: 'b' as const, text: "نیجریه" }, { id: 'c' as const, text: "آفریقای جنوبی" }, { id: 'd' as const, text: "اتیوپی" }] },
  // Q55
  { textFr: "Depuis quand les Français élisent-ils le président de la République au suffrage universel direct ?", lang: 'fa' as const, text: "از چه زمانی فرانسویان رئیس‌جمهور را با رأی مستقیم همگانی انتخاب می‌کنند؟", explanation: "از سال ۱۹۶۲ فرانسویان رئیس‌جمهور را با رأی مستقیم همگانی انتخاب می‌کنند، پس از همه‌پرسی مورد نظر ژنرال دوگل. پیش از آن، رئیس‌جمهور توسط هیئت انتخاباتی انتخاب می‌شد.", choices: [{ id: 'a' as const, text: "۱۹۶۲" }, { id: 'b' as const, text: "۱۹۵۸" }, { id: 'c' as const, text: "۱۹۴۵" }, { id: 'd' as const, text: "۱۹۸۱" }] },
  // Q56
  { textFr: "Quelle est la première étape de la construction européenne en 1951 ?", lang: 'fa' as const, text: "اولین گام ساخت اتحادیه اروپا در سال ۱۹۵۱ چه بود؟", explanation: "جامعه اروپایی زغال‌سنگ و فولاد (CECA) که در سال ۱۹۵۱ تأسیس شد، اولین گام ساخت اتحادیه اروپا بود. این سازمان توسط شش کشور برای اشتراک تولید زغال‌سنگ و فولاد بنیان‌گذاری شد.", choices: [{ id: 'a' as const, text: "تأسیس جامعه اروپایی زغال‌سنگ و فولاد (CECA)" }, { id: 'b' as const, text: "تأسیس اتحادیه اروپا" }, { id: 'c' as const, text: "امضای پیمان ماستریخت" }, { id: 'd' as const, text: "پذیرش یورو" }] },
  // Q57
  { textFr: "Durant le mandat de quel président la peine de mort a-t-elle été abolie ?", lang: 'fa' as const, text: "مجازات اعدام در دوران ریاست‌جمهوری چه کسی لغو شد؟", explanation: "مجازات اعدام در سال ۱۹۸۱ در دوران ریاست‌جمهوری فرانسوا میتران و به همت وزیر دادگستری روبر بادنتر لغو شد. فرانسه یکی از آخرین کشورهای اروپای غربی بود که این مجازات را لغو کرد.", choices: [{ id: 'a' as const, text: "فرانسوا میتران" }, { id: 'b' as const, text: "والری ژیسکار دستن" }, { id: 'c' as const, text: "ژاک شیراک" }, { id: 'd' as const, text: "شارل دوگل" }] },
  // Q58
  { textFr: "Quel régime politique a été mis en place pendant la Révolution française en 1792 ?", lang: 'fa' as const, text: "چه نظام سیاسی در دوران انقلاب فرانسه در سال ۱۷۹۲ برقرار شد؟", explanation: "جمهوری اول در ۲۱ سپتامبر ۱۷۹۲ پس از لغو سلطنت اعلام شد. این اولین نظام جمهوری در تاریخ فرانسه بود.", choices: [{ id: 'a' as const, text: "جمهوری (جمهوری اول)" }, { id: 'b' as const, text: "امپراتوری" }, { id: 'c' as const, text: "سلطنت مشروطه" }, { id: 'd' as const, text: "دیکتاتوری نظامی" }] },
  // Q59
  { textFr: "Qui était une figure de la Résistance française pendant la Seconde Guerre mondiale ?", lang: 'fa' as const, text: "چه کسی از چهره‌های مقاومت فرانسه در جنگ جهانی دوم بود؟", explanation: "ژان مولن (۱۸۹۹-۱۹۴۳) مقام بلندپایه و مقاومت‌کننده فرانسوی بود. او جنبش‌های مقاومت را زیر نظر ژنرال دوگل متحد کرد و سپس توسط گشتاپو دستگیر و کشته شد.", choices: [{ id: 'a' as const, text: "ژان مولن" }, { id: 'b' as const, text: "فیلیپ پتن" }, { id: 'c' as const, text: "پیر لاوال" }, { id: 'd' as const, text: "آدولف تی‌یر" }] },
  // Q60
  { textFr: "En 1944, qu'est-ce qui a changé pour les femmes ?", lang: 'fa' as const, text: "در سال ۱۹۴۴ چه چیزی برای زنان تغییر کرد؟", explanation: "در سال ۱۹۴۴ زنان حق رأی را در فرانسه به دست آوردند. آنها برای اولین بار در انتخابات شهرداری ۲۹ آوریل ۱۹۴۵ رأی دادند.", choices: [{ id: 'a' as const, text: "آنها حق رأی به دست آوردند" }, { id: 'b' as const, text: "آنها حق کار کردن به دست آوردند" }, { id: 'c' as const, text: "آنها حق طلاق به دست آوردند" }, { id: 'd' as const, text: "آنها حق افتتاح حساب بانکی به دست آوردند" }] },
  // Q61
  { textFr: "Quelle organisation internationale a été créée en 1945 après la Seconde Guerre mondiale ?", lang: 'fa' as const, text: "کدام سازمان بین‌المللی در سال ۱۹۴۵ پس از جنگ جهانی دوم تأسیس شد؟", explanation: "سازمان ملل متحد (UN) در سال ۱۹۴۵ برای حفظ صلح و امنیت بین‌المللی تأسیس شد. فرانسه یکی از پنج عضو دائم شورای امنیت است.", choices: [{ id: 'a' as const, text: "سازمان ملل متحد (UN)" }, { id: 'b' as const, text: "اتحادیه اروپا" }, { id: 'c' as const, text: "ناتو" }, { id: 'd' as const, text: "صلیب سرخ" }] },
  // Q62
  { textFr: "Quelle peine a été supprimée en 1981 ?", lang: 'fa' as const, text: "کدام مجازات در سال ۱۹۸۱ حذف شد؟", explanation: "مجازات اعدام در فرانسه در ۹ اکتبر ۱۹۸۱ توسط قانونی که روبر بادنتر ارائه کرد لغو شد. فرانسه بدین ترتیب به کشورهای اروپایی که مجازات اعدام را حذف کرده بودند پیوست.", choices: [{ id: 'a' as const, text: "مجازات اعدام" }, { id: 'b' as const, text: "حبس ابد" }, { id: 'c' as const, text: "کار اجباری" }, { id: 'd' as const, text: "تبعید" }] },
  // Q63
  { textFr: "En quelle année l'euro est-il devenu la monnaie utilisée en France ?", lang: 'fa' as const, text: "یورو در چه سالی واحد پول مورد استفاده در فرانسه شد؟", explanation: "یورو در ۱ ژانویه ۲۰۰۲ جایگزین فرانک فرانسه شد. امروزه یورو واحد پول مشترک ۲۰ کشور منطقه یورو است.", choices: [{ id: 'a' as const, text: "۲۰۰۲" }, { id: 'b' as const, text: "۱۹۹۹" }, { id: 'c' as const, text: "۱۹۹۲" }, { id: 'd' as const, text: "۲۰۰۵" }] },
  // Q64
  { textFr: "En quelle année a commencé la Première Guerre mondiale ?", lang: 'fa' as const, text: "جنگ جهانی اول در چه سالی آغاز شد؟", explanation: "جنگ جهانی اول در سال ۱۹۱۴ با ترور آرشیدوک فرانتس فردیناند اتریش آغاز شد. فرانسه از همان ابتدا وارد جنگ شد.", choices: [{ id: 'a' as const, text: "۱۹۱۴" }, { id: 'b' as const, text: "۱۹۱۶" }, { id: 'c' as const, text: "۱۹۱۲" }, { id: 'd' as const, text: "۱۹۳۹" }] },
  // Q65
  { textFr: "Où a eu lieu le débarquement en 1944 ?", lang: 'fa' as const, text: "پیاده‌شدن نیروها در سال ۱۹۴۴ کجا انجام شد؟", explanation: "پیاده‌شدن ۶ ژوئن ۱۹۴۴ (روز D) در سواحل نرماندی انجام شد. این عملیات نظامی متفقین آغاز آزادسازی فرانسه از اشغال نازی بود.", choices: [{ id: 'a' as const, text: "در نرماندی" }, { id: 'b' as const, text: "در برتانی" }, { id: 'c' as const, text: "در پرووانس" }, { id: 'd' as const, text: "در پیکاردی" }] },
  // Q66
  { textFr: "Quel continent a été le plus concerné par la décolonisation française après la Seconde Guerre mondiale ?", lang: 'fa' as const, text: "کدام قاره بیشتر تحت تأثیر استعمارزدایی فرانسه پس از جنگ جهانی دوم قرار گرفت؟", explanation: "آفریقا قاره‌ای بود که بیشتر تحت تأثیر استعمارزدایی فرانسه قرار گرفت. اکثر مستعمرات فرانسوی در آفریقا در دهه ۱۹۶۰ به استقلال رسیدند.", choices: [{ id: 'a' as const, text: "آفریقا" }, { id: 'b' as const, text: "آسیا" }, { id: 'c' as const, text: "آمریکای جنوبی" }, { id: 'd' as const, text: "اقیانوسیه" }] },
  // Q67
  { textFr: "Que fête-t-on le 8 mai ?", lang: 'fa' as const, text: "۸ مه چه چیزی جشن گرفته می‌شود؟", explanation: "۸ مه پایان جنگ جهانی دوم در اروپا (پیروزی متفقین بر آلمان نازی در ۱۹۴۵) را گرامی می‌دارد. این روز در فرانسه تعطیل رسمی است.", choices: [{ id: 'a' as const, text: "پایان جنگ جهانی دوم در اروپا" }, { id: 'b' as const, text: "روز کارگر" }, { id: 'c' as const, text: "آتش‌بس جنگ جهانی اول" }, { id: 'd' as const, text: "روز ملی" }] },
  // Q68
  { textFr: "Quelle mer ou océan borde la France métropolitaine ?", lang: 'fa' as const, text: "کدام دریا یا اقیانوس فرانسه متروپل را در بر می‌گیرد؟", explanation: "دریای مدیترانه جنوب فرانسه متروپل را در بر می‌گیرد. فرانسه همچنین در غرب با اقیانوس اطلس و در شمال با کانال مانش هم‌مرز است.", choices: [{ id: 'a' as const, text: "دریای مدیترانه" }, { id: 'b' as const, text: "دریای خزر" }, { id: 'c' as const, text: "دریای سیاه" }, { id: 'd' as const, text: "دریای سرخ" }] },
  // Q69
  { textFr: "Quel pays a une frontière terrestre avec la France métropolitaine ?", lang: 'fa' as const, text: "کدام کشور مرز زمینی با فرانسه متروپل دارد؟", explanation: "اسپانیا در جنوب در امتداد رشته‌کوه پیرنه مرز زمینی با فرانسه دارد. فرانسه متروپل همچنین با بلژیک، لوکزامبورگ، آلمان، سوئیس، ایتالیا و موناکو هم‌مرز است.", choices: [{ id: 'a' as const, text: "اسپانیا" }, { id: 'b' as const, text: "پرتغال" }, { id: 'c' as const, text: "انگلستان" }, { id: 'd' as const, text: "لهستان" }] },
  // Q70
  { textFr: "Quelle ville française est un port maritime ?", lang: 'fa' as const, text: "کدام شهر فرانسوی یک بندر دریایی است؟", explanation: "لو آور یک بندر بزرگ دریایی فرانسوی واقع در نرماندی در دهانه رود سن است. این بندر یکی از مهم‌ترین بنادر تجاری فرانسه است.", choices: [{ id: 'a' as const, text: "لو آور" }, { id: 'b' as const, text: "تولوز" }, { id: 'c' as const, text: "کلرمون‌فران" }, { id: 'd' as const, text: "استراسبورگ" }] },
  // Q71
  { textFr: "Quelle mer se situe entre la France et l'Angleterre ?", lang: 'fa' as const, text: "کدام دریا بین فرانسه و انگلستان واقع شده است؟", explanation: "کانال مانش فرانسه را از انگلستان جدا می‌کند. این کانال اقیانوس اطلس را به دریای شمال متصل می‌کند و از سال ۱۹۹۴ تونل زیر مانش از آن عبور می‌کند.", choices: [{ id: 'a' as const, text: "کانال مانش" }, { id: 'b' as const, text: "دریای شمال" }, { id: 'c' as const, text: "دریای مدیترانه" }, { id: 'd' as const, text: "دریای بالتیک" }] },
  // Q72
  { textFr: "Qu'est-ce que la France d'outre-mer ?", lang: 'fa' as const, text: "فرانسه فرادریایی چیست؟", explanation: "فرانسه فرادریایی مجموعه سرزمین‌های فرانسوی واقع در خارج از اروپا را شامل می‌شود. این سرزمین‌ها شامل استان‌ها (گوادلوپ، مارتینیک، گویان، رئونیون، مایوت) و مجموعه‌های فرادریایی هستند.", choices: [{ id: 'a' as const, text: "مجموعه سرزمین‌های فرانسوی واقع در خارج از اروپا" }, { id: 'b' as const, text: "مناطق جنوب فرانسه" }, { id: 'c' as const, text: "مستعمرات سابق فرانسه که مستقل شده‌اند" }, { id: 'd' as const, text: "کشورهای فرانسوی‌زبان آفریقا" }] },
  // Q73
  { textFr: "Quelle chaîne de montagnes est située entre la France et l'Espagne ?", lang: 'fa' as const, text: "کدام رشته‌کوه بین فرانسه و اسپانیا واقع شده است؟", explanation: "پیرنه مرز طبیعی بین فرانسه و اسپانیا را در حدود ۴۳۰ کیلومتر تشکیل می‌دهد. بلندترین قله آن پیک آنتو (۳۴۰۴ متر) در سمت اسپانیا است.", choices: [{ id: 'a' as const, text: "پیرنه" }, { id: 'b' as const, text: "آلپ" }, { id: 'c' as const, text: "ژورا" }, { id: 'd' as const, text: "ووژ" }] },
  // Q74
  { textFr: "Quelle île française se trouve dans l'océan Indien ?", lang: 'fa' as const, text: "کدام جزیره فرانسوی در اقیانوس هند واقع شده است؟", explanation: "رئونیون یک استان فرادریایی فرانسه واقع در اقیانوس هند در شرق ماداگاسکار است. این جزیره آتشفشانی حدود ۹۰۰ هزار نفر جمعیت دارد.", choices: [{ id: 'a' as const, text: "رئونیون" }, { id: 'b' as const, text: "مارتینیک" }, { id: 'c' as const, text: "گوادلوپ" }, { id: 'd' as const, text: "کُرس" }] },
  // Q75
  { textFr: "Quelle est la population approximative de la France en 2025 ?", lang: 'fa' as const, text: "جمعیت تقریبی فرانسه در سال ۲۰۲۵ چقدر است؟", explanation: "فرانسه در سال ۲۰۲۵ حدود ۶۸ میلیون نفر جمعیت دارد، شامل سرزمین‌های فرادریایی. این کشور دومین کشور پرجمعیت اتحادیه اروپا پس از آلمان است.", choices: [{ id: 'a' as const, text: "۶۸ میلیون نفر" }, { id: 'b' as const, text: "۵۰ میلیون نفر" }, { id: 'c' as const, text: "۸۰ میلیون نفر" }, { id: 'd' as const, text: "۴۵ میلیون نفر" }] },
  // Q76
  { textFr: "Quel fleuve traverse Paris ?", lang: 'fa' as const, text: "کدام رود از پاریس عبور می‌کند؟", explanation: "رود سن از شرق به غرب پاریس را طی می‌کند. این رود ۷۷۶ کیلومتری از بورگوندی سرچشمه می‌گیرد و در لو آور به کانال مانش می‌ریزد.", choices: [{ id: 'a' as const, text: "سن" }, { id: 'b' as const, text: "لوآر" }, { id: 'c' as const, text: "رُن" }, { id: 'd' as const, text: "گارُن" }] },
  // Q77
  { textFr: "Lequel de ces pays partage des frontières terrestres avec la France ?", lang: 'fa' as const, text: "کدام یک از این کشورها مرز زمینی با فرانسه دارد؟", explanation: "بلژیک در شمال مرز زمینی با فرانسه دارد. دو کشور همسایه و شریک در اتحادیه اروپا هستند.", choices: [{ id: 'a' as const, text: "بلژیک" }, { id: 'b' as const, text: "هلند" }, { id: 'c' as const, text: "بریتانیا" }, { id: 'd' as const, text: "دانمارک" }] },
  // Q78
  { textFr: "Quel pays a une frontière avec la France métropolitaine au nord-est ?", lang: 'fa' as const, text: "کدام کشور در شمال شرق با فرانسه متروپل هم‌مرز است؟", explanation: "آلمان در شمال شرق در امتداد رود راین با فرانسه هم‌مرز است. این مرز صحنه جنگ‌های بسیاری بود تا اینکه به نماد آشتی فرانسه و آلمان تبدیل شد.", choices: [{ id: 'a' as const, text: "آلمان" }, { id: 'b' as const, text: "لهستان" }, { id: 'c' as const, text: "اتریش" }, { id: 'd' as const, text: "جمهوری چک" }] },
  // Q79
  { textFr: "Où se trouvent les principales activités économiques en France ?", lang: 'fa' as const, text: "فعالیت‌های اصلی اقتصادی فرانسه کجا متمرکز هستند؟", explanation: "فعالیت‌های اصلی اقتصادی فرانسه در کلان‌شهرها، به‌ویژه منطقه پاریس (ایل‌دوفرانس) متمرکز هستند. لیون، مارسی و دیگر شهرهای بزرگ نیز قطب‌های اقتصادی مهمی هستند.", choices: [{ id: 'a' as const, text: "در کلان‌شهرها و منطقه پاریس" }, { id: 'b' as const, text: "فقط در جنوب فرانسه" }, { id: 'c' as const, text: "عمدتاً در مناطق روستایی" }, { id: 'd' as const, text: "انحصاراً در سواحل" }] },
  // Q80
  { textFr: "Parmi ces pays, lequel attire le plus de visiteurs chaque année ?", lang: 'fa' as const, text: "از بین این کشورها، کدام یک هر ساله بیشترین بازدیدکننده را جذب می‌کند؟", explanation: "فرانسه اولین مقصد گردشگری جهان با حدود ۹۰ میلیون بازدیدکننده خارجی در سال است. میراث فرهنگی، آشپزی و مناظر متنوع آن گردشگران سراسر جهان را جذب می‌کند.", choices: [{ id: 'a' as const, text: "فرانسه" }, { id: 'b' as const, text: "ایتالیا" }, { id: 'c' as const, text: "ایالات متحده" }, { id: 'd' as const, text: "اسپانیا" }] },
  // Q81
  { textFr: "Où habite la majorité des Français ?", lang: 'fa' as const, text: "اکثر فرانسویان کجا زندگی می‌کنند؟", explanation: "اکثر فرانسویان در شهر زندگی می‌کنند (حدود ۸۰ درصد جمعیت شهرنشین است). کلان‌شهرهایی مانند پاریس، لیون و مارسی بخش مهمی از جمعیت را در خود جای داده‌اند.", choices: [{ id: 'a' as const, text: "در شهر" }, { id: 'b' as const, text: "در روستا" }, { id: 'c' as const, text: "در کوهستان" }, { id: 'd' as const, text: "در ساحل" }] },
  // Q82
  { textFr: "Quelle région est la plus peuplée ?", lang: 'fa' as const, text: "کدام منطقه پرجمعیت‌ترین است؟", explanation: "ایل‌دوفرانس پرجمعیت‌ترین منطقه فرانسه با حدود ۱۲ میلیون نفر جمعیت است. این منطقه شامل پاریس و حومه آن است و یک‌پنجم جمعیت فرانسه را در خود جای داده است.", choices: [{ id: 'a' as const, text: "ایل‌دوفرانس" }, { id: 'b' as const, text: "پرووانس-آلپ-کوت دازور" }, { id: 'c' as const, text: "اکسیتانی" }, { id: 'd' as const, text: "نوول-آکیتن" }] },
  // Q83
  { textFr: "Quelle ville française fait partie des 10 plus grandes métropoles du pays ?", lang: 'fa' as const, text: "کدام شهر فرانسوی جزو ۱۰ کلان‌شهر بزرگ کشور است؟", explanation: "تولوز جزو ۱۰ کلان‌شهر بزرگ فرانسه است. این شهر چهارمین شهر فرانسه از نظر جمعیت و قطب اصلی صنعت هوافضا است.", choices: [{ id: 'a' as const, text: "تولوز" }, { id: 'b' as const, text: "بال" }, { id: 'c' as const, text: "لوزان" }, { id: 'd' as const, text: "شارلروا" }] },
  // Q84
  { textFr: "Lequel de ces départements de France est le plus touristique ?", lang: 'fa' as const, text: "کدام یک از استان‌های فرانسه گردشگرپذیرترین است؟", explanation: "پاریس (استان ۷۵) گردشگرپذیرترین استان فرانسه است. پایتخت هر ساله میلیون‌ها بازدیدکننده را به لطف بناها، موزه‌ها و زندگی فرهنگی خود جذب می‌کند.", choices: [{ id: 'a' as const, text: "پاریس" }, { id: 'b' as const, text: "کروز" }, { id: 'c' as const, text: "کانتال" }, { id: 'd' as const, text: "لوزر" }] },
  // Q85
  { textFr: "Quand peut-on visiter gratuitement des lieux culturels en France ?", lang: 'fa' as const, text: "چه زمانی می‌توان اماکن فرهنگی را در فرانسه رایگان بازدید کرد؟", explanation: "روزهای اروپایی میراث فرهنگی که هر سال در ماه سپتامبر برگزار می‌شود، امکان بازدید رایگان از بسیاری از اماکن فرهنگی و بناهای تاریخی فرانسه را فراهم می‌کند.", choices: [{ id: 'a' as const, text: "در روزهای اروپایی میراث فرهنگی" }, { id: 'b' as const, text: "فقط در ۱۴ ژوئیه" }, { id: 'c' as const, text: "همه یکشنبه‌های سال" }, { id: 'd' as const, text: "در تعطیلات مدارس" }] },
  // Q86
  { textFr: "Combien de personnes parlent français dans le monde ?", lang: 'fa' as const, text: "چند نفر در جهان فرانسوی صحبت می‌کنند؟", explanation: "حدود ۳۰۰ میلیون نفر در جهان فرانسوی صحبت می‌کنند. زبان فرانسه پنجمین زبان پرگویشور جهان و زبان رسمی ۲۹ کشور است.", choices: [{ id: 'a' as const, text: "حدود ۳۰۰ میلیون" }, { id: 'b' as const, text: "حدود ۱۰۰ میلیون" }, { id: 'c' as const, text: "حدود ۵۰۰ میلیون" }, { id: 'd' as const, text: "حدود ۵۰ میلیون" }] },
  // Q87
  { textFr: "Qui était Marguerite Yourcenar ?", lang: 'fa' as const, text: "مارگریت یورسنار چه کسی بود؟", explanation: "مارگریت یورسنار (۱۹۰۳-۱۹۸۷) نویسنده فرانسوی و اولین زنی بود که در سال ۱۹۸۰ به عضویت آکادمی فرانسه درآمد. او به خاطر رمان‌های تاریخی‌اش مانند «خاطرات هادریان» شناخته شده است.", choices: [{ id: 'a' as const, text: "اولین زن عضو آکادمی فرانسه" }, { id: 'b' as const, text: "دانشمند برنده جایزه نوبل فیزیک" }, { id: 'c' as const, text: "کاشف قرن نوزدهم" }, { id: 'd' as const, text: "آهنگساز موسیقی باروک" }] },
  // Q88
  { textFr: "Quel peintre est français ?", lang: 'fa' as const, text: "کدام نقاش فرانسوی است؟", explanation: "کلود مونه (۱۸۴۰-۱۹۲۶) نقاش فرانسوی و بنیان‌گذار جنبش امپرسیونیسم بود. او به خاطر مجموعه نقاشی‌های نیلوفرهای آبی و کلیسای جامع روان مشهور است.", choices: [{ id: 'a' as const, text: "کلود مونه" }, { id: 'b' as const, text: "پابلو پیکاسو" }, { id: 'c' as const, text: "ونسان ون گوگ" }, { id: 'd' as const, text: "سالوادور دالی" }] },
  // Q89
  { textFr: "Quel musée est situé à Paris ?", lang: 'fa' as const, text: "کدام موزه در پاریس واقع شده است؟", explanation: "موزه اورسی در پاریس در یک ایستگاه راه‌آهن سابق واقع شده است. این موزه بزرگ‌ترین مجموعه هنر امپرسیونیسم و پسا-امپرسیونیسم جهان را در خود جای داده است.", choices: [{ id: 'a' as const, text: "موزه اورسی" }, { id: 'b' as const, text: "موزه بریتانیا" }, { id: 'c' as const, text: "موزه پرادو" }, { id: 'd' as const, text: "موزه متروپولیتن" }] },
  // Q90
  { textFr: "Qui était Auguste Rodin ?", lang: 'fa' as const, text: "اگوست رودن چه کسی بود؟", explanation: "اگوست رودن (۱۸۴۰-۱۹۱۷) مجسمه‌ساز فرانسوی بود که پدر مجسمه‌سازی مدرن شناخته می‌شود. او خالق «متفکر» و «بورژواهای کاله» است.", choices: [{ id: 'a' as const, text: "مجسمه‌ساز فرانسوی، خالق متفکر" }, { id: 'b' as const, text: "نقاش امپرسیونیست" }, { id: 'c' as const, text: "معمار برج ایفل" }, { id: 'd' as const, text: "نویسنده رمانتیک" }] },
  // Q91
  { textFr: "Quel est le classement de la langue française parmi les langues les plus parlées dans le monde ?", lang: 'fa' as const, text: "رتبه زبان فرانسه در بین پرگویشورترین زبان‌های جهان چیست؟", explanation: "زبان فرانسه پنجمین زبان پرگویشور جهان است. این زبان در ۲۹ کشور زبان رسمی است و در پنج قاره صحبت می‌شود.", choices: [{ id: 'a' as const, text: "پنجمین زبان پرگویشور" }, { id: 'b' as const, text: "دومین زبان پرگویشور" }, { id: 'c' as const, text: "دهمین زبان پرگویشور" }, { id: 'd' as const, text: "اولین زبان پرگویشور" }] },
  // Q92
  { textFr: "Quelle cathédrale célèbre a été en partie détruite par un incendie en 2019 ?", lang: 'fa' as const, text: "کدام کلیسای جامع مشهور در سال ۲۰۱۹ بر اثر آتش‌سوزی تا حدی تخریب شد؟", explanation: "کلیسای جامع نتردام پاریس در ۱۵ آوریل ۲۰۱۹ بر اثر آتش‌سوزی شدیداً آسیب دید. مناره و بخشی از سقف آن فرو ریخت. این کلیسا بازسازی و در دسامبر ۲۰۲۴ بازگشایی شد.", choices: [{ id: 'a' as const, text: "نتردام پاریس" }, { id: 'b' as const, text: "کلیسای جامع رنس" }, { id: 'c' as const, text: "کلیسای جامع شارتر" }, { id: 'd' as const, text: "کلیسای جامع استراسبورگ" }] },
  // Q93
  { textFr: "Qui était une écrivaine française célèbre ?", lang: 'fa' as const, text: "چه کسی نویسنده زن مشهور فرانسوی بود؟", explanation: "کولت (۱۸۷۳-۱۹۵۴) رمان‌نویس مشهور فرانسوی بود که رمان‌های متعددی مانند مجموعه کلودین نوشت. او دومین زنی بود که در فرانسه تشییع جنازه ملی برایش برگزار شد.", choices: [{ id: 'a' as const, text: "کولت" }, { id: 'b' as const, text: "جین آستین" }, { id: 'c' as const, text: "ویرجینیا وولف" }, { id: 'd' as const, text: "آگاتا کریستی" }] },
  // Q94
  { textFr: "Qui était un célèbre musicien français ?", lang: 'fa' as const, text: "چه کسی موسیقیدان مشهور فرانسوی بود؟", explanation: "کلود دبوسی (۱۸۶۲-۱۹۱۸) آهنگساز فرانسوی و چهره برجسته موسیقی امپرسیونیستی بود. او به‌ویژه به خاطر «مهتاب» و «دریا» شناخته شده است.", choices: [{ id: 'a' as const, text: "کلود دبوسی" }, { id: 'b' as const, text: "لودویگ فان بتهوون" }, { id: 'c' as const, text: "ولفگانگ آمادئوس موتسارت" }, { id: 'd' as const, text: "یوهان سباستیان باخ" }] },
  // Q95
  { textFr: "Qui était Auguste Renoir ?", lang: 'fa' as const, text: "اگوست رنوار چه کسی بود؟", explanation: "اگوست رنوار (۱۸۴۱-۱۹۱۹) نقاش فرانسوی و یکی از استادان بزرگ امپرسیونیسم بود. او به خاطر صحنه‌های زندگی روزمره و پرتره‌های درخشانش مشهور است.", choices: [{ id: 'a' as const, text: "نقاش امپرسیونیست فرانسوی" }, { id: 'b' as const, text: "مجسمه‌ساز قرن هجدهم" }, { id: 'c' as const, text: "نویسنده رئالیست" }, { id: 'd' as const, text: "معمار دوره رنسانس" }] },
  // Q96
  { textFr: "Quelle fête est française ?", lang: 'fa' as const, text: "کدام جشن فرانسوی است؟", explanation: "جشن موسیقی که در ۲۱ ژوئن برگزار می‌شود، جشنی با ریشه فرانسوی است که در سال ۱۹۸۲ توسط ژاک لانگ ایجاد شد. امروزه این جشن در بسیاری از کشورهای جهان برگزار می‌شود.", choices: [{ id: 'a' as const, text: "جشن موسیقی" }, { id: 'b' as const, text: "شکرگزاری" }, { id: 'c' as const, text: "هالووین" }, { id: 'd' as const, text: "روز سنت پاتریک" }] },
  // Q97
  { textFr: "Parmi ces textes, lequel a été adopté sous Napoléon Ier ?", lang: 'fa' as const, text: "از بین این متون، کدام یک در دوران ناپلئون اول تصویب شد؟", explanation: "قانون مدنی در سال ۱۸۰۴ در دوران ناپلئون اول تصویب شد. این قانون که به نام قانون ناپلئون نیز شناخته می‌شود، حقوق فرانسه را یکپارچه کرد و همچنان پایه حقوق مدنی فرانسه است.", choices: [{ id: 'a' as const, text: "قانون مدنی" }, { id: 'b' as const, text: "اعلامیه حقوق بشر و شهروند" }, { id: 'c' as const, text: "قانون جدایی کلیسا و دولت" }, { id: 'd' as const, text: "قانون اساسی جمهوری پنجم" }] },
  // Q98
  { textFr: "Qui a été président de la Ve République ?", lang: 'fa' as const, text: "چه کسی رئیس‌جمهور جمهوری پنجم بوده است؟", explanation: "ژاک شیراک از سال ۱۹۹۵ تا ۲۰۰۷ رئیس‌جمهور جمهوری پنجم بود. او پنجمین رئیس‌جمهور جمهوری پنجم بود که پس از فرانسوا میتران به قدرت رسید.", choices: [{ id: 'a' as const, text: "ژاک شیراک" }, { id: 'b' as const, text: "وینستون چرچیل" }, { id: 'c' as const, text: "کنراد آدناور" }, { id: 'd' as const, text: "بنیتو موسولینی" }] },
  // Q99
  { textFr: "Que signifie la date du 14 juillet pour les Français ?", lang: 'fa' as const, text: "تاریخ ۱۴ ژوئیه برای فرانسویان چه معنایی دارد؟", explanation: "۱۴ ژوئیه روز ملی فرانسه است. این روز یادبود سقوط باستیل در سال ۱۷۸۹ که نماد پایان استبداد مطلق است و جشن فدراسیون ۱۷۹۰ را گرامی می‌دارد.", choices: [{ id: 'a' as const, text: "روز ملی است که سقوط باستیل را گرامی می‌دارد" }, { id: 'b' as const, text: "سالگرد قانون اساسی است" }, { id: 'c' as const, text: "روز اروپا است" }, { id: 'd' as const, text: "روز آتش‌بس است" }] },
  // Q100
  { textFr: "Lequel de ces pays est un pays fondateur de l'Union européenne ?", lang: 'fa' as const, text: "کدام یک از این کشورها یکی از کشورهای بنیان‌گذار اتحادیه اروپا است؟", explanation: "فرانسه یکی از شش کشور بنیان‌گذار ساختار اروپایی به همراه آلمان، ایتالیا، بلژیک، هلند و لوکزامبورگ است. جامعه اروپایی زغال‌سنگ و فولاد در سال ۱۹۵۱ تأسیس شد.", choices: [{ id: 'a' as const, text: "فرانسه" }, { id: 'b' as const, text: "بریتانیا" }, { id: 'c' as const, text: "اسپانیا" }, { id: 'd' as const, text: "لهستان" }] },
  // Q101
  { textFr: "Dans quelle région est située une partie des plages du débarquement ?", lang: 'fa' as const, text: "سواحل پیاده‌شدن نیروها در کدام منطقه واقع شده‌اند؟", explanation: "سواحل پیاده‌شدن ۶ ژوئن ۱۹۴۴ در نرماندی واقع شده‌اند. پنج ساحل (یوتا، اوماها، گلد، ژونو، سورد) اماکن یادبود مهمی هستند.", choices: [{ id: 'a' as const, text: "نرماندی" }, { id: 'b' as const, text: "برتانی" }, { id: 'c' as const, text: "پیکاردی" }, { id: 'd' as const, text: "آکیتن" }] },
  // Q102
  { textFr: "Dans quelle ville les rois de France étaient-ils couronnés ?", lang: 'fa' as const, text: "پادشاهان فرانسه در کدام شهر تاج‌گذاری می‌شدند؟", explanation: "پادشاهان فرانسه به‌طور سنتی در کلیسای جامع رنس تاج‌گذاری می‌شدند. این سنت به غسل تعمید کلوویس حدود سال ۴۹۶ بازمی‌گردد و قرن‌ها ادامه یافت.", choices: [{ id: 'a' as const, text: "رنس" }, { id: 'b' as const, text: "پاریس" }, { id: 'c' as const, text: "ورسای" }, { id: 'd' as const, text: "اورلئان" }] },
  // Q103
  { textFr: "En quelle année l'Union européenne a-t-elle été fondée ?", lang: 'fa' as const, text: "اتحادیه اروپا در چه سالی تأسیس شد؟", explanation: "اتحادیه اروپا در سال ۱۹۹۲ با پیمان ماستریخت تأسیس شد. این پیمان جامعه اقتصادی اروپا را به اتحادیه اروپا تبدیل کرد و پایه‌های واحد پول مشترک را بنا نهاد.", choices: [{ id: 'a' as const, text: "۱۹۹۲" }, { id: 'b' as const, text: "۱۹۵۷" }, { id: 'c' as const, text: "۲۰۰۲" }, { id: 'd' as const, text: "۱۹۵۱" }] },
  // Q104
  { textFr: "Qui a aboli l'esclavage en France ?", lang: 'fa' as const, text: "چه کسی بردگی را در فرانسه لغو کرد؟", explanation: "ویکتور شولشر مسئول صدور فرمان لغو قطعی بردگی در فرانسه در ۲۷ آوریل ۱۸۴۸ بود. او در آن زمان معاون وزیر مستعمرات در جمهوری دوم بود.", choices: [{ id: 'a' as const, text: "ویکتور شولشر" }, { id: 'b' as const, text: "ناپلئون بناپارت" }, { id: 'c' as const, text: "ژول فری" }, { id: 'd' as const, text: "لئون گامبتا" }] },
  // Q105
  { textFr: "Lors de la Seconde Guerre mondiale, à quelle date Paris a-t-elle été libérée ?", lang: 'fa' as const, text: "در جنگ جهانی دوم، پاریس در چه تاریخی آزاد شد؟", explanation: "پاریس در ۲۵ اوت ۱۹۴۴ پس از قیام مردمی و ورود لشکر دوم زرهی ژنرال لوکلرک آزاد شد. این رویداد نقطه عطفی در آزادسازی فرانسه بود.", choices: [{ id: 'a' as const, text: "۲۵ اوت ۱۹۴۴" }, { id: 'b' as const, text: "۶ ژوئن ۱۹۴۴" }, { id: 'c' as const, text: "۸ مه ۱۹۴۵" }, { id: 'd' as const, text: "۱۸ ژوئن ۱۹۴۰" }] },
  // Q106
  { textFr: "Quel était le principal port français impliqué dans la traite négrière au XVIIIe siècle ?", lang: 'fa' as const, text: "اصلی‌ترین بندر فرانسوی درگیر در تجارت برده در قرن هجدهم کدام بود؟", explanation: "نانت اصلی‌ترین بندر فرانسوی درگیر در تجارت برده در قرن هجدهم بود. این شهر بیشترین تعداد سفرهای تجارت برده فرانسوی را سازمان‌دهی کرد و امروزه یادبودی برای لغو بردگی دارد.", choices: [{ id: 'a' as const, text: "نانت" }, { id: 'b' as const, text: "مارسی" }, { id: 'c' as const, text: "لو آور" }, { id: 'd' as const, text: "برست" }] },
  // Q107
  { textFr: "Quel célèbre philosophe des Lumières a dénoncé l'esclavage ?", lang: 'fa' as const, text: "کدام فیلسوف مشهور عصر روشنگری بردگی را محکوم کرد؟", explanation: "ولتر (۱۶۹۴-۱۷۷۸) فیلسوف عصر روشنگری بود که بردگی را به‌ویژه در «کاندید» محکوم کرد. فیلسوفان عصر روشنگری نقش مهمی در به‌چالش‌کشیدن این عمل داشتند.", choices: [{ id: 'a' as const, text: "ولتر" }, { id: 'b' as const, text: "ناپلئون بناپارت" }, { id: 'c' as const, text: "لوئی چهاردهم" }, { id: 'd' as const, text: "ریشلیو" }] },
  // Q108
  { textFr: "Quel plat est une spécialité de la cuisine française ?", lang: 'fa' as const, text: "کدام غذا از تخصص‌های آشپزی فرانسوی است؟", explanation: "کُک اُ ون یک غذای سنتی فرانسوی است که با مرغ پخته‌شده در شراب قرمز با گوشت نمک‌سود شده و قارچ تهیه می‌شود. آشپزی فرانسوی در میراث ناملموس یونسکو ثبت شده است.", choices: [{ id: 'a' as const, text: "کُک اُ ون" }, { id: 'b' as const, text: "پائیا" }, { id: 'c' as const, text: "سوشی" }, { id: 'd' as const, text: "فیش اند چیپس" }] },
  // Q109
  { textFr: "Qui était Marie Curie ?", lang: 'fa' as const, text: "ماری کوری چه کسی بود؟", explanation: "ماری کوری (۱۸۶۷-۱۹۳۴) فیزیکدان و شیمیدان فرانسوی-لهستانی بود و اولین زنی که جایزه نوبل دریافت کرد. او دو جایزه نوبل (فیزیک در ۱۹۰۳ و شیمی در ۱۹۱۱) برای تحقیقاتش در زمینه رادیواکتیویته دریافت کرد.", choices: [{ id: 'a' as const, text: "فیزیکدان فرانسوی-لهستانی، برنده دو جایزه نوبل" }, { id: 'b' as const, text: "رمان‌نویس فرانسوی قرن نوزدهم" }, { id: 'c' as const, text: "مقاومت‌کننده جنگ جهانی دوم" }, { id: 'd' as const, text: "ملکه فرانسه" }] },
  // Q110
  { textFr: "Qui a peint « La Liberté guidant le peuple » ?", lang: 'fa' as const, text: "چه کسی «آزادی هدایت‌کننده مردم» را نقاشی کرد؟", explanation: "اوژن دلاکروا «آزادی هدایت‌کننده مردم» را در سال ۱۸۳۰ نقاشی کرد. این تابلوی مشهور انقلاب ژوئیه ۱۸۳۰ را به تصویر می‌کشد و در موزه لوور به نمایش گذاشته شده است.", choices: [{ id: 'a' as const, text: "اوژن دلاکروا" }, { id: 'b' as const, text: "کلود مونه" }, { id: 'c' as const, text: "پل سزان" }, { id: 'd' as const, text: "اگوست رنوار" }] },
  // Q111
  { textFr: "Dans quel grand musée parisien est exposée la Joconde ?", lang: 'fa' as const, text: "مونالیزا در کدام موزه بزرگ پاریس به نمایش گذاشته شده است؟", explanation: "مونالیزا (یا ژوکوند) اثر لئوناردو داوینچی در موزه لوور در پاریس به نمایش گذاشته شده است. این مشهورترین تابلوی جهان و یکی از آثار ارزشمند مجموعه موزه است.", choices: [{ id: 'a' as const, text: "موزه لوور" }, { id: 'b' as const, text: "موزه اورسی" }, { id: 'c' as const, text: "مرکز پمپیدو" }, { id: 'd' as const, text: "موزه رودن" }] },
  // Q112
  { textFr: "Quel château célèbre se trouve près de Paris et symbolise le pouvoir royal de Louis XIV ?", lang: 'fa' as const, text: "کدام قصر مشهور نزدیک پاریس واقع شده و نماد قدرت سلطنتی لوئی چهاردهم است؟", explanation: "کاخ ورسای اقامتگاه اصلی پادشاهان فرانسه از لوئی چهاردهم تا لوئی شانزدهم بود. این کاخ که در قرن هفدهم ساخته شد، نماد قدرت سلطنت مطلقه است.", choices: [{ id: 'a' as const, text: "کاخ ورسای" }, { id: 'b' as const, text: "قصر شامبور" }, { id: 'c' as const, text: "قصر فونتنبلو" }, { id: 'd' as const, text: "قصر شنونسو" }] },
  // Q113
  { textFr: "Où peut-on voir des peintures préhistoriques en France ?", lang: 'fa' as const, text: "کجا می‌توان نقاشی‌های پیش از تاریخ را در فرانسه مشاهده کرد؟", explanation: "غار لاسکو در دوردونی نقاشی‌های پیش از تاریخ حدود ۱۷ هزار ساله را در خود جای داده است. این غار که در سال ۱۹۴۰ کشف شد، «کلیسای سیستین پیش از تاریخ» لقب گرفته است.", choices: [{ id: 'a' as const, text: "در غار لاسکو" }, { id: 'b' as const, text: "در کاخ ورسای" }, { id: 'c' as const, text: "در موزه لوور" }, { id: 'd' as const, text: "در کلیسای جامع شارتر" }] },
  // Q114
  { textFr: "Quel peintre célèbre a peint les Nymphéas ?", lang: 'fa' as const, text: "کدام نقاش مشهور نیلوفرهای آبی را نقاشی کرد؟", explanation: "کلود مونه مجموعه مشهور نیلوفرهای آبی را در باغش در ژیورنی نقاشی کرد. این تابلوهای امپرسیونیستی که بین سال‌های ۱۸۹۵ تا ۱۹۲۶ کشیده شدند، در موزه اورانژری در پاریس به نمایش گذاشته شده‌اند.", choices: [{ id: 'a' as const, text: "کلود مونه" }, { id: 'b' as const, text: "ادگار دگا" }, { id: 'c' as const, text: "پل گوگن" }, { id: 'd' as const, text: "ادوارد مانه" }] },
  // Q115
  { textFr: "Que symbolise le 1er mai ?", lang: 'fa' as const, text: "۱ مه نماد چیست؟", explanation: "۱ مه روز کارگر در فرانسه است و از سال ۱۹۴۷ تعطیل رسمی است. این روز جشن حقوق کارگران است که به‌طور سنتی با اهدای شاخه‌های سوسن دره همراه است.", choices: [{ id: 'a' as const, text: "روز کارگر" }, { id: 'b' as const, text: "روز ملی" }, { id: 'c' as const, text: "جشن موسیقی" }, { id: 'd' as const, text: "روز پیروزی" }] },
  // Q116
  { textFr: "Qui était Monsieur Rouget de Lisle ?", lang: 'fa' as const, text: "آقای روژه دو لیل چه کسی بود؟", explanation: "کلود ژوزف روژه دو لیل (۱۷۶۰-۱۸۳۶) افسر و آهنگساز فرانسوی بود که سرود «مارسیز» را در سال ۱۷۹۲ ساخت. این سرود میهنی به سرود ملی فرانسه تبدیل شد.", choices: [{ id: 'a' as const, text: "آهنگساز سرود مارسیز" }, { id: 'b' as const, text: "بنیان‌گذار جمهوری پنجم" }, { id: 'c' as const, text: "یک ژنرال ناپلئون" }, { id: 'd' as const, text: "یک فیلسوف عصر روشنگری" }] },
  // Q117
  { textFr: "À quelle occasion a été construite la tour Eiffel ?", lang: 'fa' as const, text: "برج ایفل به چه مناسبتی ساخته شد؟", explanation: "برج ایفل برای نمایشگاه جهانی ۱۸۸۹ که صدمین سالگرد انقلاب فرانسه را جشن می‌گرفت ساخته شد. این برج که توسط گوستاو ایفل طراحی شده بود، قرار بود پس از نمایشگاه تخریب شود.", choices: [{ id: 'a' as const, text: "نمایشگاه جهانی ۱۸۸۹" }, { id: 'b' as const, text: "بازی‌های المپیک ۱۹۰۰" }, { id: 'c' as const, text: "پیروزی ۱۹۱۸" }, { id: 'd' as const, text: "تاج‌گذاری ناپلئون" }] },
  // Q118
  { textFr: "Qui était un célèbre compositeur français ?", lang: 'fa' as const, text: "چه کسی آهنگساز مشهور فرانسوی بود؟", explanation: "موریس راول (۱۸۷۵-۱۹۳۷) آهنگساز فرانسوی و خالق بولرو مشهور بود. او یکی از بزرگ‌ترین آهنگسازان فرانسوی قرن بیستم به همراه کلود دبوسی است.", choices: [{ id: 'a' as const, text: "موریس راول" }, { id: 'b' as const, text: "جوزپه وردی" }, { id: 'c' as const, text: "ریشارد واگنر" }, { id: 'd' as const, text: "پیوتر چایکوفسکی" }] },
  // Q119
  { textFr: "Quel monument historique se trouve sur une île en Normandie ?", lang: 'fa' as const, text: "کدام بنای تاریخی بر روی جزیره‌ای در نرماندی واقع شده است؟", explanation: "مون‌سن‌میشل صومعه‌ای قرون‌وسطایی است که بر روی صخره‌ای جزیره‌ای در نرماندی واقع شده است. این بنا یکی از پربازدیدترین مکان‌های فرانسه و در فهرست میراث جهانی یونسکو ثبت شده است.", choices: [{ id: 'a' as const, text: "مون‌سن‌میشل" }, { id: 'b' as const, text: "قصر شامبور" }, { id: 'c' as const, text: "پل دو گار" }, { id: 'd' as const, text: "شهر کارکاسون" }] },
  // Q120
  { textFr: "Quelle île fait partie des Antilles françaises ?", lang: 'fa' as const, text: "کدام جزیره بخشی از آنتیل فرانسه است؟", explanation: "گوادلوپ بخشی از آنتیل فرانسه در دریای کارائیب است. این جزیره یک استان و منطقه فرادریایی فرانسه متشکل از چندین جزیره است.", choices: [{ id: 'a' as const, text: "گوادلوپ" }, { id: 'b' as const, text: "کوبا" }, { id: 'c' as const, text: "جامائیکا" }, { id: 'd' as const, text: "پورتوریکو" }] },
  // Q121
  { textFr: "Quelle île est française ?", lang: 'fa' as const, text: "کدام جزیره فرانسوی است؟", explanation: "کالدونیای نو سرزمین فرانسوی واقع در اقیانوس آرام است. این سرزمین یک نهاد حقوقی ویژه فرانسه با وضعیت خاص در جمهوری است.", choices: [{ id: 'a' as const, text: "کالدونیای نو" }, { id: 'b' as const, text: "باهاما" }, { id: 'c' as const, text: "مالدیو" }, { id: 'd' as const, text: "بورنئو" }] },
  // Q122
  { textFr: "Quelle est la plus haute montagne de France ?", lang: 'fa' as const, text: "بلندترین کوه فرانسه کدام است؟", explanation: "مون‌بلان با ارتفاع ۴۸۰۹ متر بلندترین کوه فرانسه و اروپای غربی است. این کوه در آلپ در مرز فرانسه و ایتالیا واقع شده است.", choices: [{ id: 'a' as const, text: "مون‌بلان" }, { id: 'b' as const, text: "پوی دو دوم" }, { id: 'c' as const, text: "پیک دو میدی" }, { id: 'd' as const, text: "مون ونتو" }] },
  // Q123
  { textFr: "Quelle île française est située au sud-est du continent africain ?", lang: 'fa' as const, text: "کدام جزیره فرانسوی در جنوب شرق قاره آفریقا واقع شده است؟", explanation: "مایوت جزیره‌ای فرانسوی در اقیانوس هند در جنوب شرق قاره آفریقا است. این جزیره در سال ۲۰۱۱ به صد و یکمین استان فرانسه تبدیل شد.", choices: [{ id: 'a' as const, text: "مایوت" }, { id: 'b' as const, text: "مارتینیک" }, { id: 'c' as const, text: "گوادلوپ" }, { id: 'd' as const, text: "سن‌پیر و میکلن" }] },
  // Q124
  { textFr: "Quel département français a une frontière avec le Brésil ?", lang: 'fa' as const, text: "کدام استان فرانسه با برزیل هم‌مرز است؟", explanation: "گویان فرانسه یک استان فرادریایی واقع در آمریکای جنوبی است که با برزیل هم‌مرز است. این استان بزرگ‌ترین استان فرانسه از نظر مساحت است.", choices: [{ id: 'a' as const, text: "گویان" }, { id: 'b' as const, text: "مارتینیک" }, { id: 'c' as const, text: "رئونیون" }, { id: 'd' as const, text: "مایوت" }] },
  // Q125
  { textFr: "De quelle ville française décolle la fusée Ariane ?", lang: 'fa' as const, text: "موشک آریان از کدام شهر فرانسوی پرتاب می‌شود؟", explanation: "موشک آریان از کورو در گویان فرانسه پرتاب می‌شود. مرکز فضایی گویان از سال ۱۹۶۸ پایگاه پرتاب آژانس فضایی اروپا (ESA) است.", choices: [{ id: 'a' as const, text: "کورو" }, { id: 'b' as const, text: "تولوز" }, { id: 'c' as const, text: "بوردو" }, { id: 'd' as const, text: "مارسی" }] },
  // Q126
  { textFr: "Quel est le principal port maritime de France ?", lang: 'fa' as const, text: "اصلی‌ترین بندر دریایی فرانسه کدام است؟", explanation: "مارسی اصلی‌ترین بندر دریایی فرانسه و اولین بندر مدیترانه است. بندر بزرگ دریایی مارسی هر ساله میلیون‌ها تن کالا جابه‌جا می‌کند.", choices: [{ id: 'a' as const, text: "مارسی" }, { id: 'b' as const, text: "نانت" }, { id: 'c' as const, text: "برست" }, { id: 'd' as const, text: "بوردو" }] },
  // Q127
  { textFr: "Quel est le chef-lieu de la région Auvergne-Rhône-Alpes ?", lang: 'fa' as const, text: "مرکز منطقه اورن-رون-آلپ کجاست؟", explanation: "لیون مرکز منطقه اورن-رون-آلپ است. این شهر سومین شهر بزرگ فرانسه و مرکز مهم اقتصادی و فرهنگی است.", choices: [{ id: 'a' as const, text: "لیون" }, { id: 'b' as const, text: "کلرمون‌فران" }, { id: 'c' as const, text: "گرنوبل" }, { id: 'd' as const, text: "سنت‌اتین" }] },
  // Q128
  { textFr: "Quel est le chef-lieu de la région Bretagne ?", lang: 'fa' as const, text: "مرکز منطقه برتانی کجاست؟", explanation: "رن مرکز منطقه برتانی است. این شهر پویا و دانشگاهی در غرب فرانسه واقع شده است.", choices: [{ id: 'a' as const, text: "رن" }, { id: 'b' as const, text: "برست" }, { id: 'c' as const, text: "نانت" }, { id: 'd' as const, text: "کمپر" }] },
  // Q129
  { textFr: "Quel est le chef-lieu de la région Provence-Alpes-Côte d'Azur ?", lang: 'fa' as const, text: "مرکز منطقه پرووانس-آلپ-کوت دازور کجاست؟", explanation: "مارسی مرکز منطقه پرووانس-آلپ-کوت دازور (PACA) است. این شهر دومین شهر بزرگ فرانسه و بندر اصلی مدیترانه است.", choices: [{ id: 'a' as const, text: "مارسی" }, { id: 'b' as const, text: "نیس" }, { id: 'c' as const, text: "تولون" }, { id: 'd' as const, text: "اکس‌آن‌پرووانس" }] },
  // Q130
  { textFr: "Quel est le 101e département français depuis 2011 ?", lang: 'fa' as const, text: "صد و یکمین استان فرانسه از سال ۲۰۱۱ کدام است؟", explanation: "مایوت در ۳۱ مارس ۲۰۱۱ پس از همه‌پرسی ۲۰۰۹ به صد و یکمین استان فرانسه تبدیل شد. این جدیدترین استان فرادریایی است که به جمهوری فرانسه پیوسته است.", choices: [{ id: 'a' as const, text: "مایوت" }, { id: 'b' as const, text: "گویان" }, { id: 'c' as const, text: "کالدونیای نو" }, { id: 'd' as const, text: "سن‌مارتن" }] },
  // Q131
  { textFr: "Quelle région française est réputée pour ses stations de ski ?", lang: 'fa' as const, text: "کدام منطقه فرانسه به خاطر پیست‌های اسکی‌اش مشهور است؟", explanation: "منطقه اورن-رون-آلپ مشهورترین منطقه فرانسه برای پیست‌های اسکی است. این منطقه پیست‌های اسکی معروف آلپی مانند شامونی، لِ دُ آلپ و وال دیزر را در خود جای داده است.", choices: [{ id: 'a' as const, text: "اورن-رون-آلپ" }, { id: 'b' as const, text: "ایل‌دوفرانس" }, { id: 'c' as const, text: "نوول-آکیتن" }, { id: 'd' as const, text: "برتانی" }] },
];
