export const theme4Hi = [
  // Q1
  { textFr: "En quelle année a débuté la Révolution française ?", lang: 'hi' as const, text: "फ्रांसीसी क्रांति किस वर्ष शुरू हुई?", explanation: "फ्रांसीसी क्रांति 1789 में बैस्टिल के पतन के साथ शुरू हुई। इस घटना ने पुरानी व्यवस्था के अंत और फ्रांस में गहन राजनीतिक और सामाजिक परिवर्तनों के युग की शुरुआत को चिह्नित किया।", choices: [{ id: 'a' as const, text: "1789" }, { id: 'b' as const, text: "1799" }, { id: 'c' as const, text: "1776" }, { id: 'd' as const, text: "1815" }] },
  // Q2
  { textFr: "Qui était Napoléon Ier ?", lang: 'hi' as const, text: "नेपोलियन प्रथम कौन थे?", explanation: "नेपोलियन प्रथम 1804 से 1814 तक और फिर 1815 में संक्षेप में फ्रांस के सम्राट थे। उन्होंने फ्रांसीसी प्रशासन का आधुनिकीकरण किया और नागरिक संहिता की स्थापना की, जो आज भी लागू है।", choices: [{ id: 'a' as const, text: "फ्रांस के पहले सम्राट" }, { id: 'b' as const, text: "फ्रांस के अंतिम राजा" }, { id: 'c' as const, text: "पाँचवें गणराज्य के संस्थापक" }, { id: 'd' as const, text: "प्रथम विश्व युद्ध के एक जनरल" }] },
  // Q3
  { textFr: "Lequel de ces personnages historiques est français ?", lang: 'hi' as const, text: "इनमें से कौन सा ऐतिहासिक व्यक्ति फ्रांसीसी है?", explanation: "जोन ऑफ आर्क फ्रांस के इतिहास की एक प्रतिष्ठित शख्सियत हैं। उन्होंने 15वीं शताब्दी में सौ साल के युद्ध के दौरान अंग्रेजों के खिलाफ फ्रांसीसी सेनाओं का नेतृत्व किया।", choices: [{ id: 'a' as const, text: "जोन ऑफ आर्क" }, { id: 'b' as const, text: "क्रिस्टोफर कोलंबस" }, { id: 'c' as const, text: "विंस्टन चर्चिल" }, { id: 'd' as const, text: "लिओनार्दो दा विंची" }] },
  // Q4
  { textFr: "Dans quelle République est-on aujourd'hui ?", lang: 'hi' as const, text: "आज हम किस गणराज्य में हैं?", explanation: "फ्रांस वर्तमान में पाँचवें गणराज्य के अंतर्गत है, जिसकी स्थापना 1958 में जनरल डे गॉल ने की थी। इसने राष्ट्रपति की शक्ति को मजबूत किया।", choices: [{ id: 'a' as const, text: "पाँचवाँ गणराज्य" }, { id: 'b' as const, text: "चौथा गणराज्य" }, { id: 'c' as const, text: "तीसरा गणराज्य" }, { id: 'd' as const, text: "छठा गणराज्य" }] },
  // Q5
  { textFr: "Qu'est-ce que la Shoah ?", lang: 'hi' as const, text: "शोआ (होलोकॉस्ट) क्या है?", explanation: "शोआ का अर्थ है द्वितीय विश्व युद्ध के दौरान नाजी जर्मनी द्वारा यूरोप के यहूदियों का नरसंहार। 1941 और 1945 के बीच लगभग साठ लाख यहूदियों का संहार किया गया।", choices: [{ id: 'a' as const, text: "द्वितीय विश्व युद्ध के दौरान यहूदियों का नरसंहार" }, { id: 'b' as const, text: "प्रथम विश्व युद्ध की एक लड़ाई" }, { id: 'c' as const, text: "एक यूरोपीय शांति संधि" }, { id: 'd' as const, text: "कब्जे के खिलाफ फ्रांसीसी प्रतिरोध" }] },
  // Q6
  { textFr: "Quel pays ou région du monde a été colonisé par la France ?", lang: 'hi' as const, text: "विश्व के किस देश या क्षेत्र को फ्रांस ने उपनिवेश बनाया?", explanation: "अल्जीरिया 1830 से 1962 तक फ्रांस का उपनिवेश था। यह उत्तरी अफ्रीका में फ्रांस का सबसे बड़ा उपनिवेश था और एक लंबे युद्ध के बाद इसे स्वतंत्रता मिली।", choices: [{ id: 'a' as const, text: "अल्जीरिया" }, { id: 'b' as const, text: "ब्राज़ील" }, { id: 'c' as const, text: "भारत" }, { id: 'd' as const, text: "ऑस्ट्रेलिया" }] },
  // Q7
  { textFr: "Qui a rendu l'école gratuite, laïque et obligatoire ?", lang: 'hi' as const, text: "किसने स्कूल को मुफ्त, धर्मनिरपेक्ष और अनिवार्य बनाया?", explanation: "शिक्षा मंत्री जूल्स फेरी ने 1881-1882 के कानून पारित कराए जिन्होंने प्राथमिक शिक्षा को मुफ्त, धर्मनिरपेक्ष और अनिवार्य बनाया। ये कानून फ्रांसीसी गणराज्य का एक स्तंभ हैं।", choices: [{ id: 'a' as const, text: "जूल्स फेरी" }, { id: 'b' as const, text: "विक्टर ह्यूगो" }, { id: 'c' as const, text: "नेपोलियन बोनापार्ट" }, { id: 'd' as const, text: "शार्ल डे गॉल" }] },
  // Q8
  { textFr: "Quand a eu lieu la Seconde Guerre mondiale ?", lang: 'hi' as const, text: "द्वितीय विश्व युद्ध कब हुआ?", explanation: "द्वितीय विश्व युद्ध 1939 से 1945 तक चला। इस वैश्विक संघर्ष में अधिकांश राष्ट्र शामिल थे और इसमें लाखों लोग मारे गए।", choices: [{ id: 'a' as const, text: "1939-1945" }, { id: 'b' as const, text: "1914-1918" }, { id: 'c' as const, text: "1870-1871" }, { id: 'd' as const, text: "1950-1953" }] },
  // Q9
  { textFr: "Quand a eu lieu la Première Guerre mondiale ?", lang: 'hi' as const, text: "प्रथम विश्व युद्ध कब हुआ?", explanation: "प्रथम विश्व युद्ध 1914 से 1918 तक हुआ। इस संघर्ष में मुख्य रूप से त्रिपक्षीय मैत्री शक्तियाँ और केंद्रीय शक्तियाँ आमने-सामने थीं।", choices: [{ id: 'a' as const, text: "1914-1918" }, { id: 'b' as const, text: "1939-1945" }, { id: 'c' as const, text: "1870-1871" }, { id: 'd' as const, text: "1899-1902" }] },
  // Q10
  { textFr: "En quelle année a été créée la Communauté Économique Européenne (CEE) ?", lang: 'hi' as const, text: "यूरोपीय आर्थिक समुदाय (EEC) की स्थापना किस वर्ष हुई?", explanation: "EEC की स्थापना 1957 में रोम की संधि द्वारा हुई, जिस पर फ्रांस सहित छह संस्थापक देशों ने हस्ताक्षर किए। यह वर्तमान यूरोपीय संघ का पूर्ववर्ती है।", choices: [{ id: 'a' as const, text: "1957" }, { id: 'b' as const, text: "1945" }, { id: 'c' as const, text: "1962" }, { id: 'd' as const, text: "1951" }] },
  // Q11
  { textFr: "Le 11 novembre est un jour férié. À quoi correspond cette date ?", lang: 'hi' as const, text: "11 नवंबर एक सार्वजनिक अवकाश है। इस तिथि का क्या अर्थ है?", explanation: "11 नवंबर 1918 प्रथम विश्व युद्ध के युद्धविराम का दिन है। यह सार्वजनिक अवकाश लड़ाई की समाप्ति को याद करता है और फ्रांस के लिए मारे गए सैनिकों को श्रद्धांजलि देता है।", choices: [{ id: 'a' as const, text: "प्रथम विश्व युद्ध का युद्धविराम" }, { id: 'b' as const, text: "द्वितीय विश्व युद्ध का अंत" }, { id: 'c' as const, text: "फ्रांसीसी राष्ट्रीय दिवस" }, { id: 'd' as const, text: "गणराज्य की घोषणा" }] },
  // Q12
  { textFr: "Qui a été le premier Président élu sous la Ve République ?", lang: 'hi' as const, text: "पाँचवें गणराज्य के तहत चुने गए पहले राष्ट्रपति कौन थे?", explanation: "शार्ल डे गॉल पाँचवें गणराज्य के पहले राष्ट्रपति थे, जो 1958 में चुने गए। वे इस शासन के संस्थापक थे और उन्होंने दो राष्ट्रपति कार्यकाल पूरे किए।", choices: [{ id: 'a' as const, text: "शार्ल डे गॉल" }, { id: 'b' as const, text: "फ्रांस्वा मितेरां" }, { id: 'c' as const, text: "जॉर्ज पोम्पिदू" }, { id: 'd' as const, text: "रेने कोटी" }] },
  // Q13
  { textFr: "En quelle année l'esclavage a-t-il été aboli définitivement en France ?", lang: 'hi' as const, text: "फ्रांस में दासता को अंतिम रूप से किस वर्ष समाप्त किया गया?", explanation: "फ्रांस में दासता को 1848 में विक्टर शोल्शर की पहल पर अंतिम रूप से समाप्त किया गया। 1794 में एक पहला उन्मूलन आदेश जारी किया गया था लेकिन नेपोलियन ने 1802 में इसे फिर से स्थापित कर दिया था।", choices: [{ id: 'a' as const, text: "1848" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1865" }, { id: 'd' as const, text: "1794" }] },
  // Q14
  { textFr: "Depuis quelle année l'école publique est-elle gratuite ?", lang: 'hi' as const, text: "सार्वजनिक स्कूल किस वर्ष से मुफ्त है?", explanation: "सार्वजनिक स्कूल 1881 से मुफ्त है, जूल्स फेरी के कानूनों की बदौलत। इन कानूनों ने प्राथमिक शिक्षा को अनिवार्य और धर्मनिरपेक्ष भी बनाया।", choices: [{ id: 'a' as const, text: "1881" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1905" }, { id: 'd' as const, text: "1848" }] },
  // Q15
  { textFr: "Combien y a-t-il eu de républiques en France ?", lang: 'hi' as const, text: "फ्रांस में कितने गणराज्य रहे हैं?", explanation: "फ्रांस ने पाँच गणराज्य देखे हैं। पहला गणराज्य 1792 में घोषित किया गया और पाँचवाँ गणराज्य, 1958 में स्थापित, वर्तमान शासन है।", choices: [{ id: 'a' as const, text: "पाँच" }, { id: 'b' as const, text: "तीन" }, { id: 'c' as const, text: "चार" }, { id: 'd' as const, text: "छह" }] },
  // Q16
  { textFr: "Qui était le roi de France au moment de la Révolution française ?", lang: 'hi' as const, text: "फ्रांसीसी क्रांति के समय फ्रांस का राजा कौन था?", explanation: "लुई XVI 1789 की फ्रांसीसी क्रांति के समय फ्रांस के राजा थे। उन्हें पदच्युत किया गया और 1793 में गिलोटिन से मार दिया गया।", choices: [{ id: 'a' as const, text: "लुई XVI" }, { id: 'b' as const, text: "लुई XIV" }, { id: 'c' as const, text: "लुई XV" }, { id: 'd' as const, text: "हेनरी IV" }] },
  // Q17
  { textFr: "Qui a fondé la Ve République ?", lang: 'hi' as const, text: "पाँचवें गणराज्य की स्थापना किसने की?", explanation: "जनरल शार्ल डे गॉल ने 1958 में पाँचवें गणराज्य की स्थापना की। वे इसके पहले राष्ट्रपति बने और कार्यकारी शक्ति को मजबूत करने वाला संविधान लागू किया।", choices: [{ id: 'a' as const, text: "जनरल डे गॉल" }, { id: 'b' as const, text: "फ्रांस्वा मितेरां" }, { id: 'c' as const, text: "नेपोलियन III" }, { id: 'd' as const, text: "लिओन ब्लम" }] },
  // Q18
  { textFr: "Que célèbre-t-on le 14 juillet ?", lang: 'hi' as const, text: "14 जुलाई को क्या मनाया जाता है?", explanation: "14 जुलाई फ्रांस का राष्ट्रीय दिवस है। यह 1789 में बैस्टिल के पतन और 1790 के संघ उत्सव की याद में मनाया जाता है, जो स्वतंत्रता और राष्ट्रीय एकता के प्रतीक हैं।", choices: [{ id: 'a' as const, text: "राष्ट्रीय दिवस, बैस्टिल के पतन की वर्षगाँठ" }, { id: 'b' as const, text: "1918 का युद्धविराम" }, { id: 'c' as const, text: "द्वितीय विश्व युद्ध का अंत" }, { id: 'd' as const, text: "दासता का उन्मूलन" }] },
  // Q19
  { textFr: "Quelle guerre a eu lieu entre 1914 et 1918 ?", lang: 'hi' as const, text: "1914 और 1918 के बीच कौन सा युद्ध हुआ?", explanation: "प्रथम विश्व युद्ध 1914 से 1918 तक हुआ। इसमें मित्र राष्ट्र और केंद्रीय शक्तियाँ आमने-सामने थीं और लाखों लोग मारे गए।", choices: [{ id: 'a' as const, text: "प्रथम विश्व युद्ध" }, { id: 'b' as const, text: "द्वितीय विश्व युद्ध" }, { id: 'c' as const, text: "फ्रांस-प्रशिया युद्ध" }, { id: 'd' as const, text: "अल्जीरिया का युद्ध" }] },
  // Q20
  { textFr: "Pourquoi l'année 1958 est importante pour la France ?", lang: 'hi' as const, text: "वर्ष 1958 फ्रांस के लिए क्यों महत्वपूर्ण है?", explanation: "वर्ष 1958 जनरल डे गॉल द्वारा पाँचवें गणराज्य की स्थापना का वर्ष है। एक नया संविधान अपनाया गया जिसने फ्रांस की वर्तमान राजनीतिक व्यवस्था की स्थापना की।", choices: [{ id: 'a' as const, text: "यह पाँचवें गणराज्य की स्थापना का वर्ष है" }, { id: 'b' as const, text: "यह द्वितीय विश्व युद्ध के अंत का वर्ष है" }, { id: 'c' as const, text: "यह दासता के उन्मूलन का वर्ष है" }, { id: 'd' as const, text: "यह फ्रांसीसी क्रांति का वर्ष है" }] },
  // Q21
  { textFr: "Quel fleuve coule en France ?", lang: 'hi' as const, text: "कौन सी नदी फ्रांस में बहती है?", explanation: "लॉयर फ्रांस की सबसे लंबी नदी है, लगभग 1,012 किमी लंबी। यह फ्रांस के केंद्र से मासिफ सेंट्रल से अटलांटिक महासागर तक बहती है।", choices: [{ id: 'a' as const, text: "लॉयर" }, { id: 'b' as const, text: "डैन्यूब" }, { id: 'c' as const, text: "नील" }, { id: 'd' as const, text: "अमेज़न" }] },
  // Q22
  { textFr: "Quelle ville est française ?", lang: 'hi' as const, text: "कौन सा शहर फ्रांसीसी है?", explanation: "लियोन फ्रांस का एक बड़ा शहर है, ऑवेर्न-रोन-आल्प्स क्षेत्र की राजधानी। यह पेरिस और मार्सेय के बाद फ्रांस का तीसरा सबसे बड़ा शहर है।", choices: [{ id: 'a' as const, text: "लियोन" }, { id: 'b' as const, text: "जिनेवा" }, { id: 'c' as const, text: "ब्रसेल्स" }, { id: 'd' as const, text: "बार्सिलोना" }] },
  // Q23
  { textFr: "Quel océan borde la côte ouest française ?", lang: 'hi' as const, text: "फ्रांस के पश्चिमी तट पर कौन सा महासागर है?", explanation: "अटलांटिक महासागर मुख्य भूमि फ्रांस के पश्चिमी तट की सीमा बनाता है। ब्रिटनी से बास्क देश तक, यह तटरेखा सैकड़ों किलोमीटर तक फैली है।", choices: [{ id: 'a' as const, text: "अटलांटिक महासागर" }, { id: 'b' as const, text: "प्रशांत महासागर" }, { id: 'c' as const, text: "हिंद महासागर" }, { id: 'd' as const, text: "आर्कटिक महासागर" }] },
  // Q24
  { textFr: "Qu'est-ce que Paris ?", lang: 'hi' as const, text: "पेरिस क्या है?", explanation: "पेरिस फ्रांस की राजधानी और इसका राजनीतिक, आर्थिक और सांस्कृतिक केंद्र है। यह देश का सबसे अधिक आबादी वाला शहर भी है।", choices: [{ id: 'a' as const, text: "फ्रांस की राजधानी" }, { id: 'b' as const, text: "फ्रांस का एक क्षेत्र" }, { id: 'c' as const, text: "एक समुद्रपारीय विभाग" }, { id: 'd' as const, text: "यूरोप की राजधानी" }] },
  // Q25
  { textFr: "Quelle est la capitale de la France ?", lang: 'hi' as const, text: "फ्रांस की राजधानी क्या है?", explanation: "पेरिस सदियों से फ्रांस की राजधानी है। यहाँ राज्य के प्रमुख संस्थान हैं, जिनमें एलिज़ी पैलेस और नेशनल असेंबली शामिल हैं।", choices: [{ id: 'a' as const, text: "पेरिस" }, { id: 'b' as const, text: "लियोन" }, { id: 'c' as const, text: "मार्सेय" }, { id: 'd' as const, text: "स्ट्रासबर्ग" }] },
  // Q26
  { textFr: "Sur quel continent se situe la France métropolitaine ?", lang: 'hi' as const, text: "मुख्य भूमि फ्रांस किस महाद्वीप पर स्थित है?", explanation: "मुख्य भूमि फ्रांस यूरोपीय महाद्वीप पर स्थित है। इसकी सीमा पश्चिम में अटलांटिक महासागर, दक्षिण में भूमध्य सागर और उत्तर में इंग्लिश चैनल से लगती है।", choices: [{ id: 'a' as const, text: "यूरोप" }, { id: 'b' as const, text: "अफ्रीका" }, { id: 'c' as const, text: "अमेरिका" }, { id: 'd' as const, text: "एशिया" }] },
  // Q27
  { textFr: "Quelle île est un département d'outre-mer français ?", lang: 'hi' as const, text: "कौन सा द्वीप फ्रांस का समुद्रपारीय विभाग है?", explanation: "मार्टिनिक एंटिल्स में स्थित एक फ्रांसीसी समुद्रपारीय विभाग और क्षेत्र है। यह फ्रांसीसी गणराज्य का अभिन्न अंग है।", choices: [{ id: 'a' as const, text: "मार्टिनिक" }, { id: 'b' as const, text: "क्यूबा" }, { id: 'c' as const, text: "जमैका" }, { id: 'd' as const, text: "हैती" }] },
  // Q28
  { textFr: "Combien y a-t-il de régions en France métropolitaine ?", lang: 'hi' as const, text: "मुख्य भूमि फ्रांस में कितने क्षेत्र हैं?", explanation: "2016 के क्षेत्रीय सुधार के बाद से, मुख्य भूमि फ्रांस में 13 क्षेत्र हैं। क्षेत्रीय इकाइयों की दक्षता बढ़ाने के लिए यह संख्या 22 से घटाकर 13 कर दी गई।", choices: [{ id: 'a' as const, text: "13" }, { id: 'b' as const, text: "18" }, { id: 'c' as const, text: "22" }, { id: 'd' as const, text: "10" }] },
  // Q29
  { textFr: "Quelle ville est un grand port maritime ?", lang: 'hi' as const, text: "कौन सा शहर एक बड़ा समुद्री बंदरगाह है?", explanation: "मार्सेय फ्रांस का सबसे बड़ा समुद्री बंदरगाह और भूमध्य सागर के सबसे महत्वपूर्ण बंदरगाहों में से एक है। यह फ्रांस का दूसरा सबसे बड़ा शहर भी है।", choices: [{ id: 'a' as const, text: "मार्सेय" }, { id: 'b' as const, text: "क्लेरमों-फेरां" }, { id: 'c' as const, text: "ग्रेनोबल" }, { id: 'd' as const, text: "लिमोज" }] },
  // Q30
  { textFr: "Quelle est la mer au sud de la France métropolitaine ?", lang: 'hi' as const, text: "मुख्य भूमि फ्रांस के दक्षिण में कौन सा सागर है?", explanation: "भूमध्य सागर मुख्य भूमि फ्रांस के दक्षिणी तट पर है। यह स्पेनिश सीमा से इतालवी सीमा तक फैला हुआ है, कोत दाज़ूर और लैंगडोक तट के किनारे।", choices: [{ id: 'a' as const, text: "भूमध्य सागर" }, { id: 'b' as const, text: "उत्तरी सागर" }, { id: 'c' as const, text: "बाल्टिक सागर" }, { id: 'd' as const, text: "इंग्लिश चैनल" }] },
  // Q31
  { textFr: "Quelle ville est située au bord de la mer Méditerranée ?", lang: 'hi' as const, text: "कौन सा शहर भूमध्य सागर के किनारे स्थित है?", explanation: "नीस कोत दाज़ूर पर भूमध्य सागर के किनारे स्थित एक शहर है। यह दक्षिणी फ्रांस के प्रमुख पर्यटन स्थलों में से एक है।", choices: [{ id: 'a' as const, text: "नीस" }, { id: 'b' as const, text: "लील" }, { id: 'c' as const, text: "स्ट्रासबर्ग" }, { id: 'd' as const, text: "रेन" }] },
  // Q32
  { textFr: "Où se situe la Corse ?", lang: 'hi' as const, text: "कोर्सिका कहाँ स्थित है?", explanation: "कोर्सिका भूमध्य सागर में, मुख्य भूमि फ्रांस के दक्षिण-पूर्व में स्थित एक द्वीप है। यह एक अद्वितीय क्षेत्रीय इकाई है जिसका विशेष दर्जा है।", choices: [{ id: 'a' as const, text: "भूमध्य सागर में" }, { id: 'b' as const, text: "अटलांटिक महासागर में" }, { id: 'c' as const, text: "इंग्लिश चैनल में" }, { id: 'd' as const, text: "उत्तरी सागर में" }] },
  // Q33
  { textFr: "Quelle chaîne de montagnes est située entre la France et l'Italie ?", lang: 'hi' as const, text: "कौन सी पर्वत श्रृंखला फ्रांस और इटली के बीच स्थित है?", explanation: "आल्प्स फ्रांस और इटली के बीच एक प्राकृतिक सीमा बनाते हैं। आल्प्स में स्थित मोंट ब्लांक 4,809 मीटर के साथ पश्चिमी यूरोप का सबसे ऊँचा शिखर है।", choices: [{ id: 'a' as const, text: "आल्प्स" }, { id: 'b' as const, text: "पिरेनीज़" }, { id: 'c' as const, text: "जुरा" }, { id: 'd' as const, text: "वोज" }] },
  // Q34
  { textFr: "Qui était Molière ?", lang: 'hi' as const, text: "मोलिएर कौन थे?", explanation: "मोलिएर (1622-1673) 17वीं शताब्दी के एक फ्रांसीसी नाटककार और अभिनेता थे। वे ले मालाद इमाजिनेर और ले मिज़ांथ्रोप जैसी प्रसिद्ध हास्य रचनाओं के लेखक हैं।", choices: [{ id: 'a' as const, text: "17वीं शताब्दी के एक फ्रांसीसी नाटककार और अभिनेता" }, { id: 'b' as const, text: "पुनर्जागरण काल के एक चित्रकार" }, { id: 'c' as const, text: "एक शास्त्रीय संगीत रचयिता" }, { id: 'd' as const, text: "प्रबोधन काल के एक दार्शनिक" }] },
  // Q35
  { textFr: "Qui était Charles Baudelaire ?", lang: 'hi' as const, text: "शार्ल बोदलेर कौन थे?", explanation: "शार्ल बोदलेर (1821-1867) एक फ्रांसीसी कवि थे, प्रसिद्ध काव्य संग्रह 'ले फ्लूर दू माल' के लेखक। उन्हें आधुनिक कविता के अग्रदूतों में से एक माना जाता है।", choices: [{ id: 'a' as const, text: "एक फ्रांसीसी कवि, ले फ्लूर दू माल के लेखक" }, { id: 'b' as const, text: "ले मिज़रेबल के लेखक उपन्यासकार" }, { id: 'c' as const, text: "19वीं शताब्दी के एक मूर्तिकार" }, { id: 'd' as const, text: "एक रोमांटिक संगीतकार" }] },
  // Q36
  { textFr: "Qui était George Sand ?", lang: 'hi' as const, text: "जॉर्ज सैंड कौन थीं?", explanation: "जॉर्ज सैंड (1804-1876) एक फ्रांसीसी उपन्यासकार थीं, जिनका असली नाम अमांतिन लुसील ऑरोर दुपिन था। वे अपने ग्रामीण उपन्यासों और महिलाओं के अधिकारों के लिए अपनी प्रतिबद्धता के लिए प्रसिद्ध हैं।", choices: [{ id: 'a' as const, text: "19वीं शताब्दी की एक फ्रांसीसी उपन्यासकार" }, { id: 'b' as const, text: "फ्रांस की एक रानी" }, { id: 'c' as const, text: "एक नोबेल पुरस्कार विजेता वैज्ञानिक" }, { id: 'd' as const, text: "एक ओपेरा गायिका" }] },
  // Q37
  { textFr: "Qui était Simone de Beauvoir ?", lang: 'hi' as const, text: "सिमोन द बोवुआर कौन थीं?", explanation: "सिमोन द बोवुआर (1908-1986) एक फ्रांसीसी दार्शनिक और लेखिका थीं, नारीवाद की प्रमुख हस्ती। वे विशेष रूप से 'द सेकेंड सेक्स' की लेखिका हैं, जो आधुनिक नारीवाद का एक मूलभूत ग्रंथ है।", choices: [{ id: 'a' as const, text: "एक फ्रांसीसी नारीवादी दार्शनिक और लेखिका" }, { id: 'b' as const, text: "द्वितीय विश्व युद्ध की एक प्रतिरोधी" }, { id: 'c' as const, text: "एक फ्रांसीसी भौतिक विज्ञानी" }, { id: 'd' as const, text: "एक फ्रांसीसी सिनेमा अभिनेत्री" }] },
  // Q38
  { textFr: "Qui était Albert Camus ?", lang: 'hi' as const, text: "अल्बेर कामू कौन थे?", explanation: "अल्बेर कामू (1913-1960) एक फ्रांसीसी लेखक और दार्शनिक थे, 1957 में साहित्य के नोबेल पुरस्कार विजेता। वे 'ल'एत्रांजे' और 'ला पेस्ट' के लेखक हैं।", choices: [{ id: 'a' as const, text: "एक फ्रांसीसी लेखक और दार्शनिक, साहित्य के नोबेल पुरस्कार विजेता" }, { id: 'b' as const, text: "एक प्रभाववादी चित्रकार" }, { id: 'c' as const, text: "तीसरे गणराज्य के एक राजनेता" }, { id: 'd' as const, text: "एक शास्त्रीय संगीत रचयिता" }] },
  // Q39
  { textFr: "Qui était Paul Cézanne ?", lang: 'hi' as const, text: "पॉल सेज़ान कौन थे?", explanation: "पॉल सेज़ान (1839-1906) एक फ्रांसीसी चित्रकार थे, जिन्हें आधुनिक कला का जनक माना जाता है। उनकी रचनाओं ने क्यूबिज़्म और 20वीं शताब्दी के कई कलात्मक आंदोलनों को प्रभावित किया।", choices: [{ id: 'a' as const, text: "एक फ्रांसीसी चित्रकार, आधुनिक कला के अग्रदूत" }, { id: 'b' as const, text: "एक प्रकृतिवादी लेखक" }, { id: 'c' as const, text: "18वीं शताब्दी के एक मूर्तिकार" }, { id: 'd' as const, text: "पुनर्जागरण काल के एक वास्तुकार" }] },
  // Q40
  { textFr: "Qui était Marc Chagall ?", lang: 'hi' as const, text: "मार्क शगाल कौन थे?", explanation: "मार्क शगाल (1887-1985) रूसी मूल के एक चित्रकार और उत्कीर्णक थे जिन्हें फ्रांसीसी नागरिकता मिली। वे अपनी रंगीन कृतियों के लिए प्रसिद्ध हैं जो कल्पना और प्रतीकवाद का मिश्रण करती हैं, विशेषकर पेरिस ओपेरा की काँच की खिड़कियाँ।", choices: [{ id: 'a' as const, text: "रूसी मूल के फ्रांसीसी नागरिकता प्राप्त चित्रकार" }, { id: 'b' as const, text: "प्रबोधन काल के एक फ्रांसीसी दार्शनिक" }, { id: 'c' as const, text: "एक ऑस्ट्रियाई शास्त्रीय संगीतकार" }, { id: 'd' as const, text: "एक इतालवी फिल्म निर्देशक" }] },
  // Q41
  { textFr: "Qui était Joséphine Baker ?", lang: 'hi' as const, text: "जोज़ेफ़िन बेकर कौन थीं?", explanation: "जोज़ेफ़िन बेकर (1906-1975) एक फ्रांसीसी-अमेरिकी कलाकार, गायिका और नर्तकी थीं, द्वितीय विश्व युद्ध के दौरान प्रतिरोध सेनानी। उन्हें 2021 में उनकी प्रतिबद्धता के लिए पैंथियन में सम्मानित किया गया।", choices: [{ id: 'a' as const, text: "एक फ्रांसीसी-अमेरिकी कलाकार, गायिका, नर्तकी और प्रतिरोध सेनानी" }, { id: 'b' as const, text: "एक फ्रांसीसी-पोलिश वैज्ञानिक" }, { id: 'c' as const, text: "एक फ्रांसीसी महिला राजनेता" }, { id: 'd' as const, text: "19वीं शताब्दी की एक उपन्यासकार" }] },
  // Q42
  { textFr: "Qui était une chanteuse française célèbre ?", lang: 'hi' as const, text: "एक प्रसिद्ध फ्रांसीसी गायिका कौन थीं?", explanation: "एदित पियाफ (1915-1963) दुनिया की सबसे प्रसिद्ध फ्रांसीसी गायिकाओं में से एक हैं। वे 'ला वी एन रोज़' और 'नों, ज नी रग्रेत रीयन' जैसे गानों के लिए जानी जाती हैं।", choices: [{ id: 'a' as const, text: "एदित पियाफ" }, { id: 'b' as const, text: "मडोना" }, { id: 'c' as const, text: "बियॉन्से" }, { id: 'd' as const, text: "अडेल" }] },
  // Q43
  { textFr: "Qu'est-ce que le Louvre ?", lang: 'hi' as const, text: "लूव्र क्या है?", explanation: "लूव्र पेरिस में स्थित दुनिया का सबसे बड़ा कला संग्रहालय है। पूर्व शाही महल, इसमें लिओनार्दो दा विंची की मोना लिसा जैसी प्रसिद्ध कलाकृतियाँ हैं।", choices: [{ id: 'a' as const, text: "पेरिस में स्थित दुनिया का सबसे बड़ा कला संग्रहालय" }, { id: 'b' as const, text: "लॉयर का एक महल" }, { id: 'c' as const, text: "एक गॉथिक गिरजाघर" }, { id: 'd' as const, text: "एक राष्ट्रीय थिएटर" }] },
  // Q44
  { textFr: "Qui était Jean de la Fontaine ?", lang: 'hi' as const, text: "ज्यां दी ला फोंटेन कौन थे?", explanation: "ज्यां दी ला फोंटेन (1621-1695) एक फ्रांसीसी कवि थे जो अपनी दंतकथाओं (फ़ेबल) के लिए प्रसिद्ध थे। उनकी रचनाएँ, जैसे ले कॉर्बो ए ले रेनार, आज भी फ्रांसीसी स्कूलों में पढ़ाई जाती हैं।", choices: [{ id: 'a' as const, text: "अपनी दंतकथाओं के लिए प्रसिद्ध एक फ्रांसीसी कवि" }, { id: 'b' as const, text: "फ्रांस के एक राजा" }, { id: 'c' as const, text: "पुनर्जागरण काल के एक चित्रकार" }, { id: 'd' as const, text: "नई दुनिया के एक खोजकर्ता" }] },
  // Q45
  { textFr: "Quel écrivain est français ?", lang: 'hi' as const, text: "कौन सा लेखक फ्रांसीसी है?", explanation: "विक्टर ह्यूगो (1802-1885) फ्रांस के सबसे महान लेखकों में से एक हैं। वे ले मिज़रेबल और नोत्रे-डाम डी पेरिस जैसी उत्कृष्ट कृतियों के लेखक हैं।", choices: [{ id: 'a' as const, text: "विक्टर ह्यूगो" }, { id: 'b' as const, text: "चार्ल्स डिकेंस" }, { id: 'c' as const, text: "मिगुएल डे सेर्वांतेस" }, { id: 'd' as const, text: "विलियम शेक्सपियर" }] },
  // Q46
  { textFr: "Dans quelle ville se trouve la tour Eiffel ?", lang: 'hi' as const, text: "एफिल टॉवर किस शहर में है?", explanation: "एफिल टॉवर पेरिस में है। 1889 के विश्व मेले के लिए गुस्ताव एफिल द्वारा निर्मित, यह फ्रांस का सबसे प्रतिष्ठित प्रतीक बन गया है।", choices: [{ id: 'a' as const, text: "पेरिस" }, { id: 'b' as const, text: "लियोन" }, { id: 'c' as const, text: "मार्सेय" }, { id: 'd' as const, text: "बोर्दो" }] },
  // Q47
  { textFr: "Quand célèbre-t-on Noël ?", lang: 'hi' as const, text: "क्रिसमस कब मनाया जाता है?", explanation: "क्रिसमस 25 दिसंबर को मनाया जाता है। फ्रांस में यह एक सार्वजनिक अवकाश है, एक ईसाई त्योहार जो पारिवारिक भोज और उपहारों के आदान-प्रदान की सांस्कृतिक परंपरा भी बन गया है।", choices: [{ id: 'a' as const, text: "25 दिसंबर" }, { id: 'b' as const, text: "1 जनवरी" }, { id: 'c' as const, text: "14 जुलाई" }, { id: 'd' as const, text: "1 नवंबर" }] },
  // Q48
  { textFr: "Quel était le surnom de Louis XIV ?", lang: 'hi' as const, text: "लुई XIV का उपनाम क्या था?", explanation: "लुई XIV को सूर्य राजा कहा जाता था। उन्होंने 1643 से 1715 तक शासन किया, यानी 72 वर्ष, फ्रांस के इतिहास का सबसे लंबा शासनकाल, और वर्साय का महल बनवाया।", choices: [{ id: 'a' as const, text: "सूर्य राजा" }, { id: 'b' as const, text: "राजाओं का राजा" }, { id: 'c' as const, text: "प्रिय" }, { id: 'd' as const, text: "महान" }] },
  // Q49
  { textFr: "Quel roi de France a été exécuté pendant la Révolution française ?", lang: 'hi' as const, text: "फ्रांसीसी क्रांति के दौरान फ्रांस के किस राजा को मृत्युदंड दिया गया?", explanation: "लुई XVI को 21 जनवरी 1793 को पेरिस में क्रांति चौक पर गिलोटिन से मार दिया गया। उन्हें राष्ट्रीय सम्मेलन द्वारा देशद्रोह के लिए दोषी ठहराया गया था।", choices: [{ id: 'a' as const, text: "लुई XVI" }, { id: 'b' as const, text: "लुई XIV" }, { id: 'c' as const, text: "लुई XV" }, { id: 'd' as const, text: "शार्ल X" }] },
  // Q50
  { textFr: "En quelle année Napoléon Ier est-il devenu empereur ?", lang: 'hi' as const, text: "नेपोलियन प्रथम किस वर्ष सम्राट बने?", explanation: "नेपोलियन प्रथम 1804 में फ्रांस के सम्राट बने। उनका राज्याभिषेक 2 दिसंबर 1804 को पेरिस के नोत्रे-डाम गिरजाघर में हुआ।", choices: [{ id: 'a' as const, text: "1804" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1799" }, { id: 'd' as const, text: "1815" }] },
  // Q51
  { textFr: "Lequel de ces personnages a un lien avec la République française ?", lang: 'hi' as const, text: "इनमें से किस व्यक्ति का फ्रांसीसी गणराज्य से संबंध है?", explanation: "मारिआन फ्रांसीसी गणराज्य का रूपक प्रतीक है। वह स्वतंत्रता, समानता और बंधुत्व के मूल्यों का प्रतिनिधित्व करती है, और उसकी प्रतिमा सभी नगर पालिकाओं में मौजूद है।", choices: [{ id: 'a' as const, text: "मारिआन" }, { id: 'b' as const, text: "ब्रिटानिया" }, { id: 'c' as const, text: "अंकल सैम" }, { id: 'd' as const, text: "जॉन बुल" }] },
  // Q52
  { textFr: "De quand date l'appel à la résistance du général de Gaulle ?", lang: 'hi' as const, text: "जनरल डे गॉल के प्रतिरोध आह्वान की तारीख क्या है?", explanation: "जनरल डे गॉल का आह्वान 18 जून 1940 का है। लंदन से उन्होंने बीबीसी के माध्यम से फ्रांसीसियों से जर्मन कब्जे के खिलाफ प्रतिरोध करने का आह्वान किया।", choices: [{ id: 'a' as const, text: "18 जून 1940" }, { id: 'b' as const, text: "8 मई 1945" }, { id: 'c' as const, text: "14 जुलाई 1940" }, { id: 'd' as const, text: "25 अगस्त 1944" }] },
  // Q53
  { textFr: "Pourquoi la Shoah est-elle étudiée à l'école ?", lang: 'hi' as const, text: "शोआ (होलोकॉस्ट) का अध्ययन स्कूल में क्यों किया जाता है?", explanation: "शोआ का अध्ययन स्कूल में इस नरसंहार की स्मृति को संरक्षित करने और छात्रों को स्मृति के कर्तव्य के प्रति संवेदनशील बनाने के लिए किया जाता है। यह नस्लवाद, यहूदी-विरोध और हर प्रकार के भेदभाव से लड़ने में मदद करता है।", choices: [{ id: 'a' as const, text: "स्मृति के कर्तव्य और नस्लवाद तथा यहूदी-विरोध से लड़ने के लिए" }, { id: 'b' as const, text: "छात्रों को इतिहास की परीक्षा के लिए तैयार करने के लिए" }, { id: 'c' as const, text: "यूरोप का भूगोल पढ़ाने के लिए" }, { id: 'd' as const, text: "युद्धकालीन अर्थव्यवस्था का अध्ययन करने के लिए" }] },
  // Q54
  { textFr: "Quel pays a été colonisé par la France ?", lang: 'hi' as const, text: "किस देश को फ्रांस ने उपनिवेश बनाया?", explanation: "सेनेगल पश्चिम अफ्रीका में एक फ्रांसीसी उपनिवेश था। इसने 1960 में स्वतंत्रता प्राप्त की, जैसा कि कई फ्रांसीसी भाषी अफ्रीकी देशों ने किया।", choices: [{ id: 'a' as const, text: "सेनेगल" }, { id: 'b' as const, text: "नाइजीरिया" }, { id: 'c' as const, text: "दक्षिण अफ्रीका" }, { id: 'd' as const, text: "इथियोपिया" }] },
  // Q55
  { textFr: "Depuis quand les Français élisent-ils le président de la République au suffrage universel direct ?", lang: 'hi' as const, text: "फ्रांसीसी लोग कब से प्रत्यक्ष सार्वभौमिक मतदान द्वारा गणराज्य के राष्ट्रपति का चुनाव करते हैं?", explanation: "1962 से फ्रांसीसी लोग प्रत्यक्ष सार्वभौमिक मतदान द्वारा राष्ट्रपति का चुनाव करते हैं, जनरल डे गॉल द्वारा आयोजित जनमत संग्रह के बाद। इससे पहले राष्ट्रपति का चुनाव एक निर्वाचक मंडल द्वारा किया जाता था।", choices: [{ id: 'a' as const, text: "1962" }, { id: 'b' as const, text: "1958" }, { id: 'c' as const, text: "1945" }, { id: 'd' as const, text: "1981" }] },
  // Q56
  { textFr: "Quelle est la première étape de la construction européenne en 1951 ?", lang: 'hi' as const, text: "1951 में यूरोपीय निर्माण का पहला चरण क्या था?", explanation: "यूरोपीय कोयला और इस्पात समुदाय (ECSC), 1951 में स्थापित, यूरोपीय निर्माण का पहला चरण था। इसकी स्थापना छह देशों द्वारा अपने कोयला और इस्पात उत्पादन को साझा करने के लिए की गई थी।", choices: [{ id: 'a' as const, text: "यूरोपीय कोयला और इस्पात समुदाय (ECSC) की स्थापना" }, { id: 'b' as const, text: "यूरोपीय संघ की स्थापना" }, { id: 'c' as const, text: "मास्ट्रिच संधि पर हस्ताक्षर" }, { id: 'd' as const, text: "यूरो को अपनाना" }] },
  // Q57
  { textFr: "Durant le mandat de quel président la peine de mort a-t-elle été abolie ?", lang: 'hi' as const, text: "किस राष्ट्रपति के कार्यकाल में मृत्युदंड समाप्त किया गया?", explanation: "1981 में फ्रांस्वा मितेरां के राष्ट्रपति काल में न्याय मंत्री रॉबेर बादांतेर के प्रयासों से मृत्युदंड समाप्त किया गया। फ्रांस पश्चिमी यूरोप के अंतिम देशों में से एक था जिसने इसे समाप्त किया।", choices: [{ id: 'a' as const, text: "फ्रांस्वा मितेरां" }, { id: 'b' as const, text: "वालेरी जिस्कार देस्तां" }, { id: 'c' as const, text: "जाक शिराक" }, { id: 'd' as const, text: "शार्ल डे गॉल" }] },
  // Q58
  { textFr: "Quel régime politique a été mis en place pendant la Révolution française en 1792 ?", lang: 'hi' as const, text: "1792 में फ्रांसीसी क्रांति के दौरान कौन सी राजनीतिक व्यवस्था स्थापित की गई?", explanation: "प्रथम गणराज्य 21 सितंबर 1792 को राजतंत्र के उन्मूलन के बाद घोषित किया गया। यह फ्रांस के इतिहास की पहली गणतांत्रिक व्यवस्था थी।", choices: [{ id: 'a' as const, text: "गणराज्य (प्रथम गणराज्य)" }, { id: 'b' as const, text: "साम्राज्य" }, { id: 'c' as const, text: "संवैधानिक राजतंत्र" }, { id: 'd' as const, text: "सैन्य तानाशाही" }] },
  // Q59
  { textFr: "Qui était une figure de la Résistance française pendant la Seconde Guerre mondiale ?", lang: 'hi' as const, text: "द्वितीय विश्व युद्ध के दौरान फ्रांसीसी प्रतिरोध की एक प्रमुख हस्ती कौन थे?", explanation: "ज्यां मूलां (1899-1943) एक उच्च अधिकारी और फ्रांसीसी प्रतिरोध सेनानी थे। उन्होंने जनरल डे गॉल के अधिकार के तहत प्रतिरोध आंदोलनों को एकजुट किया, इससे पहले कि गेस्टापो ने उन्हें गिरफ्तार कर मार डाला।", choices: [{ id: 'a' as const, text: "ज्यां मूलां" }, { id: 'b' as const, text: "फिलिप पेतां" }, { id: 'c' as const, text: "पिएर लावाल" }, { id: 'd' as const, text: "अडॉल्फ तिएर" }] },
  // Q60
  { textFr: "En 1944, qu'est-ce qui a changé pour les femmes ?", lang: 'hi' as const, text: "1944 में महिलाओं के लिए क्या बदला?", explanation: "1944 में फ्रांस में महिलाओं को मतदान का अधिकार मिला। उन्होंने पहली बार 29 अप्रैल 1945 के नगरपालिका चुनावों में मतदान किया।", choices: [{ id: 'a' as const, text: "उन्हें मतदान का अधिकार मिला" }, { id: 'b' as const, text: "उन्हें काम करने का अधिकार मिला" }, { id: 'c' as const, text: "उन्हें तलाक का अधिकार मिला" }, { id: 'd' as const, text: "उन्हें बैंक खाता खोलने का अधिकार मिला" }] },
  // Q61
  { textFr: "Quelle organisation internationale a été créée en 1945 après la Seconde Guerre mondiale ?", lang: 'hi' as const, text: "द्वितीय विश्व युद्ध के बाद 1945 में कौन सा अंतर्राष्ट्रीय संगठन बनाया गया?", explanation: "संयुक्त राष्ट्र संगठन (UNO) की स्थापना 1945 में अंतर्राष्ट्रीय शांति और सुरक्षा बनाए रखने के लिए की गई थी। फ्रांस सुरक्षा परिषद के पाँच स्थायी सदस्यों में से एक है।", choices: [{ id: 'a' as const, text: "संयुक्त राष्ट्र संगठन (UNO)" }, { id: 'b' as const, text: "यूरोपीय संघ" }, { id: 'c' as const, text: "नाटो" }, { id: 'd' as const, text: "रेड क्रॉस" }] },
  // Q62
  { textFr: "Quelle peine a été supprimée en 1981 ?", lang: 'hi' as const, text: "1981 में कौन सी सज़ा समाप्त की गई?", explanation: "फ्रांस में 9 अक्टूबर 1981 को रॉबेर बादांतेर द्वारा प्रस्तुत कानून द्वारा मृत्युदंड समाप्त किया गया। इस प्रकार फ्रांस उन यूरोपीय देशों में शामिल हो गया जिन्होंने मृत्युदंड समाप्त किया था।", choices: [{ id: 'a' as const, text: "मृत्युदंड" }, { id: 'b' as const, text: "आजीवन कारावास" }, { id: 'c' as const, text: "बेगार" }, { id: 'd' as const, text: "निर्वासन" }] },
  // Q63
  { textFr: "En quelle année l'euro est-il devenu la monnaie utilisée en France ?", lang: 'hi' as const, text: "फ्रांस में यूरो किस वर्ष आधिकारिक मुद्रा बना?", explanation: "यूरो 1 जनवरी 2002 को फ्रांस में उपयोग की जाने वाली मुद्रा बन गया, जिसने फ्रांसीसी फ्रैंक की जगह ली। आज यूरो यूरोज़ोन के 20 देशों की साझा मुद्रा है।", choices: [{ id: 'a' as const, text: "2002" }, { id: 'b' as const, text: "1999" }, { id: 'c' as const, text: "1992" }, { id: 'd' as const, text: "2005" }] },
  // Q64
  { textFr: "En quelle année a commencé la Première Guerre mondiale ?", lang: 'hi' as const, text: "प्रथम विश्व युद्ध किस वर्ष शुरू हुआ?", explanation: "प्रथम विश्व युद्ध 1914 में ऑस्ट्रिया के आर्चड्यूक फ्रांज फर्डिनेंड की हत्या से शुरू हुआ। फ्रांस शुरू से ही इस संघर्ष में शामिल हो गया।", choices: [{ id: 'a' as const, text: "1914" }, { id: 'b' as const, text: "1916" }, { id: 'c' as const, text: "1912" }, { id: 'd' as const, text: "1939" }] },
  // Q65
  { textFr: "Où a eu lieu le débarquement en 1944 ?", lang: 'hi' as const, text: "1944 में सैन्य अवतरण कहाँ हुआ?", explanation: "6 जून 1944 (डी-डे) का सैन्य अवतरण नॉरमैंडी के समुद्र तटों पर हुआ। यह मित्र राष्ट्रों का सैन्य अभियान था जिसने नाज़ी कब्जे से फ्रांस की मुक्ति की शुरुआत की।", choices: [{ id: 'a' as const, text: "नॉरमैंडी में" }, { id: 'b' as const, text: "ब्रिटनी में" }, { id: 'c' as const, text: "प्रोवांस में" }, { id: 'd' as const, text: "पिकार्डी में" }] },
  // Q66
  { textFr: "Quel continent a été le plus concerné par la décolonisation française après la Seconde Guerre mondiale ?", lang: 'hi' as const, text: "द्वितीय विश्व युद्ध के बाद फ्रांसीसी उपनिवेशवाद-मुक्ति से सबसे अधिक प्रभावित महाद्वीप कौन सा था?", explanation: "अफ्रीका फ्रांसीसी उपनिवेशवाद-मुक्ति से सबसे अधिक प्रभावित महाद्वीप था। अधिकांश फ्रांसीसी अफ्रीकी उपनिवेशों ने 1960 के दशक में स्वतंत्रता प्राप्त की।", choices: [{ id: 'a' as const, text: "अफ्रीका" }, { id: 'b' as const, text: "एशिया" }, { id: 'c' as const, text: "दक्षिण अमेरिका" }, { id: 'd' as const, text: "ओशिनिया" }] },
  // Q67
  { textFr: "Que fête-t-on le 8 mai ?", lang: 'hi' as const, text: "8 मई को क्या मनाया जाता है?", explanation: "8 मई यूरोप में द्वितीय विश्व युद्ध के अंत (1945 में नाज़ी जर्मनी पर मित्र राष्ट्रों की विजय) की याद में मनाया जाता है। यह फ्रांस में सार्वजनिक अवकाश है।", choices: [{ id: 'a' as const, text: "यूरोप में द्वितीय विश्व युद्ध का अंत" }, { id: 'b' as const, text: "श्रम दिवस" }, { id: 'c' as const, text: "प्रथम विश्व युद्ध का युद्धविराम" }, { id: 'd' as const, text: "राष्ट्रीय दिवस" }] },
  // Q68
  { textFr: "Quelle mer ou océan borde la France métropolitaine ?", lang: 'hi' as const, text: "कौन सा सागर या महासागर मुख्य भूमि फ्रांस की सीमा बनाता है?", explanation: "भूमध्य सागर मुख्य भूमि फ्रांस के दक्षिण की सीमा बनाता है। फ्रांस की सीमा पश्चिम में अटलांटिक महासागर और उत्तर में इंग्लिश चैनल से भी लगती है।", choices: [{ id: 'a' as const, text: "भूमध्य सागर" }, { id: 'b' as const, text: "कैस्पियन सागर" }, { id: 'c' as const, text: "काला सागर" }, { id: 'd' as const, text: "लाल सागर" }] },
  // Q69
  { textFr: "Quel pays a une frontière terrestre avec la France métropolitaine ?", lang: 'hi' as const, text: "किस देश की मुख्य भूमि फ्रांस के साथ भूमि सीमा है?", explanation: "स्पेन पिरेनीज़ पर्वतमाला के साथ दक्षिण में फ्रांस के साथ भूमि सीमा साझा करता है। मुख्य भूमि फ्रांस की बेल्जियम, लक्ज़मबर्ग, जर्मनी, स्विट्ज़रलैंड, इटली और मोनाको के साथ भी सीमाएँ हैं।", choices: [{ id: 'a' as const, text: "स्पेन" }, { id: 'b' as const, text: "पुर्तगाल" }, { id: 'c' as const, text: "इंग्लैंड" }, { id: 'd' as const, text: "पोलैंड" }] },
  // Q70
  { textFr: "Quelle ville française est un port maritime ?", lang: 'hi' as const, text: "कौन सा फ्रांसीसी शहर एक समुद्री बंदरगाह है?", explanation: "ला आव्र नॉरमैंडी में सीन नदी के मुहाने पर स्थित एक बड़ा फ्रांसीसी समुद्री बंदरगाह है। यह फ्रांस के सबसे महत्वपूर्ण व्यापारिक बंदरगाहों में से एक है।", choices: [{ id: 'a' as const, text: "ला आव्र" }, { id: 'b' as const, text: "तूलूज़" }, { id: 'c' as const, text: "क्लेरमों-फेरां" }, { id: 'd' as const, text: "स्ट्रासबर्ग" }] },
  // Q71
  { textFr: "Quelle mer se situe entre la France et l'Angleterre ?", lang: 'hi' as const, text: "फ्रांस और इंग्लैंड के बीच कौन सा सागर है?", explanation: "इंग्लिश चैनल (ला मांश) फ्रांस और इंग्लैंड को अलग करती है। यह अटलांटिक महासागर और उत्तरी सागर को जोड़ती है और 1994 से चैनल टनल इसके नीचे से गुज़रती है।", choices: [{ id: 'a' as const, text: "इंग्लिश चैनल (ला मांश)" }, { id: 'b' as const, text: "उत्तरी सागर" }, { id: 'c' as const, text: "भूमध्य सागर" }, { id: 'd' as const, text: "बाल्टिक सागर" }] },
  // Q72
  { textFr: "Qu'est-ce que la France d'outre-mer ?", lang: 'hi' as const, text: "समुद्रपारीय फ्रांस क्या है?", explanation: "समुद्रपारीय फ्रांस यूरोप के बाहर स्थित सभी फ्रांसीसी क्षेत्रों को संदर्भित करता है। इसमें विभाग (ग्वाडेलूप, मार्टिनिक, गयाना, रेयूनियन, मायोट) और समुद्रपारीय समूह शामिल हैं।", choices: [{ id: 'a' as const, text: "यूरोप के बाहर स्थित सभी फ्रांसीसी क्षेत्र" }, { id: 'b' as const, text: "दक्षिणी फ्रांस के क्षेत्र" }, { id: 'c' as const, text: "पूर्व स्वतंत्र फ्रांसीसी उपनिवेश" }, { id: 'd' as const, text: "अफ्रीका के फ्रांसीसी भाषी देश" }] },
  // Q73
  { textFr: "Quelle chaîne de montagnes est située entre la France et l'Espagne ?", lang: 'hi' as const, text: "कौन सी पर्वत श्रृंखला फ्रांस और स्पेन के बीच स्थित है?", explanation: "पिरेनीज़ लगभग 430 किमी तक फ्रांस और स्पेन के बीच एक प्राकृतिक सीमा बनाते हैं। इनका सर्वोच्च शिखर स्पेनिश तरफ पिक दानेतो (3,404 मी) है।", choices: [{ id: 'a' as const, text: "पिरेनीज़" }, { id: 'b' as const, text: "आल्प्स" }, { id: 'c' as const, text: "जुरा" }, { id: 'd' as const, text: "वोज" }] },
  // Q74
  { textFr: "Quelle île française se trouve dans l'océan Indien ?", lang: 'hi' as const, text: "कौन सा फ्रांसीसी द्वीप हिंद महासागर में स्थित है?", explanation: "रेयूनियन हिंद महासागर में मेडागास्कर के पूर्व में स्थित एक फ्रांसीसी समुद्रपारीय विभाग है। यह लगभग 9,00,000 निवासियों वाला एक ज्वालामुखीय द्वीप है।", choices: [{ id: 'a' as const, text: "रेयूनियन" }, { id: 'b' as const, text: "मार्टिनिक" }, { id: 'c' as const, text: "ग्वाडेलूप" }, { id: 'd' as const, text: "कोर्सिका" }] },
  // Q75
  { textFr: "Quelle est la population approximative de la France en 2025 ?", lang: 'hi' as const, text: "2025 में फ्रांस की अनुमानित जनसंख्या कितनी है?", explanation: "फ्रांस में 2025 में समुद्रपारीय क्षेत्रों सहित लगभग 6.8 करोड़ निवासी हैं। यह जर्मनी के बाद यूरोपीय संघ का दूसरा सबसे अधिक आबादी वाला देश है।", choices: [{ id: 'a' as const, text: "6.8 करोड़ निवासी" }, { id: 'b' as const, text: "5 करोड़ निवासी" }, { id: 'c' as const, text: "8 करोड़ निवासी" }, { id: 'd' as const, text: "4.5 करोड़ निवासी" }] },
  // Q76
  { textFr: "Quel fleuve traverse Paris ?", lang: 'hi' as const, text: "कौन सी नदी पेरिस से होकर गुज़रती है?", explanation: "सीन नदी पेरिस से पूर्व से पश्चिम की ओर गुज़रती है। 776 किमी लंबी यह नदी बरगंडी में उद्गम लेती है और ला आव्र में इंग्लिश चैनल में मिलती है।", choices: [{ id: 'a' as const, text: "सीन" }, { id: 'b' as const, text: "लॉयर" }, { id: 'c' as const, text: "रोन" }, { id: 'd' as const, text: "गारोन" }] },
  // Q77
  { textFr: "Lequel de ces pays partage des frontières terrestres avec la France ?", lang: 'hi' as const, text: "इनमें से कौन सा देश फ्रांस के साथ भूमि सीमा साझा करता है?", explanation: "बेल्जियम उत्तर में फ्रांस के साथ भूमि सीमा साझा करता है। दोनों देश पड़ोसी हैं और यूरोपीय संघ के भागीदार हैं।", choices: [{ id: 'a' as const, text: "बेल्जियम" }, { id: 'b' as const, text: "नीदरलैंड" }, { id: 'c' as const, text: "यूनाइटेड किंगडम" }, { id: 'd' as const, text: "डेनमार्क" }] },
  // Q78
  { textFr: "Quel pays a une frontière avec la France métropolitaine au nord-est ?", lang: 'hi' as const, text: "किस देश की उत्तर-पूर्व में मुख्य भूमि फ्रांस के साथ सीमा है?", explanation: "जर्मनी राइन नदी के साथ उत्तर-पूर्व में फ्रांस के साथ सीमा साझा करता है। यह सीमा कई संघर्षों का स्थान रही है, लेकिन अब फ्रांसीसी-जर्मन मेल-मिलाप का प्रतीक बन गई है।", choices: [{ id: 'a' as const, text: "जर्मनी" }, { id: 'b' as const, text: "पोलैंड" }, { id: 'c' as const, text: "ऑस्ट्रिया" }, { id: 'd' as const, text: "चेक गणराज्य" }] },
  // Q79
  { textFr: "Où se trouvent les principales activités économiques en France ?", lang: 'hi' as const, text: "फ्रांस में प्रमुख आर्थिक गतिविधियाँ कहाँ स्थित हैं?", explanation: "फ्रांस में प्रमुख आर्थिक गतिविधियाँ बड़े महानगरों में केंद्रित हैं, विशेष रूप से पेरिस क्षेत्र (इल-दे-फ्रांस) में। लियोन, मार्सेय और अन्य बड़े शहर भी प्रमुख आर्थिक केंद्र हैं।", choices: [{ id: 'a' as const, text: "बड़े महानगरों और पेरिस क्षेत्र में" }, { id: 'b' as const, text: "केवल दक्षिणी फ्रांस में" }, { id: 'c' as const, text: "मुख्य रूप से ग्रामीण क्षेत्रों में" }, { id: 'd' as const, text: "केवल तटों पर" }] },
  // Q80
  { textFr: "Parmi ces pays, lequel attire le plus de visiteurs chaque année ?", lang: 'hi' as const, text: "इन देशों में से कौन सा हर साल सबसे अधिक पर्यटकों को आकर्षित करता है?", explanation: "फ्रांस प्रति वर्ष लगभग 9 करोड़ विदेशी पर्यटकों के साथ दुनिया का शीर्ष पर्यटन गंतव्य है। इसकी सांस्कृतिक विरासत, भोजन और विविध परिदृश्य दुनिया भर के पर्यटकों को आकर्षित करते हैं।", choices: [{ id: 'a' as const, text: "फ्रांस" }, { id: 'b' as const, text: "इटली" }, { id: 'c' as const, text: "संयुक्त राज्य अमेरिका" }, { id: 'd' as const, text: "स्पेन" }] },
  // Q81
  { textFr: "Où habite la majorité des Français ?", lang: 'hi' as const, text: "अधिकांश फ्रांसीसी लोग कहाँ रहते हैं?", explanation: "अधिकांश फ्रांसीसी लोग शहरों में रहते हैं (लगभग 80% जनसंख्या शहरी है)। पेरिस, लियोन और मार्सेय जैसे बड़े शहरी क्षेत्र जनसंख्या का एक बड़ा हिस्सा केंद्रित करते हैं।", choices: [{ id: 'a' as const, text: "शहर में" }, { id: 'b' as const, text: "ग्रामीण क्षेत्र में" }, { id: 'c' as const, text: "पहाड़ों में" }, { id: 'd' as const, text: "तट पर" }] },
  // Q82
  { textFr: "Quelle région est la plus peuplée ?", lang: 'hi' as const, text: "कौन सा क्षेत्र सबसे अधिक आबादी वाला है?", explanation: "इल-दे-फ्रांस लगभग 1.2 करोड़ निवासियों के साथ फ्रांस का सबसे अधिक आबादी वाला क्षेत्र है। इसमें पेरिस और उसके उपनगर शामिल हैं, जो फ्रांसीसी जनसंख्या का पाँचवाँ हिस्सा केंद्रित करते हैं।", choices: [{ id: 'a' as const, text: "इल-दे-फ्रांस" }, { id: 'b' as const, text: "प्रोवांस-आल्प्स-कोत दाज़ूर" }, { id: 'c' as const, text: "ऑक्सिटानी" }, { id: 'd' as const, text: "नूवेल-अकितेन" }] },
  // Q83
  { textFr: "Quelle ville française fait partie des 10 plus grandes métropoles du pays ?", lang: 'hi' as const, text: "कौन सा फ्रांसीसी शहर देश के 10 सबसे बड़े महानगरों में शामिल है?", explanation: "तूलूज़ फ्रांस के 10 सबसे बड़े महानगरों में शामिल है। यह जनसंख्या के हिसाब से फ्रांस का चौथा शहर है और विमानन उद्योग का एक प्रमुख केंद्र है।", choices: [{ id: 'a' as const, text: "तूलूज़" }, { id: 'b' as const, text: "बाज़ेल" }, { id: 'c' as const, text: "लोज़ान" }, { id: 'd' as const, text: "शार्लरोआ" }] },
  // Q84
  { textFr: "Lequel de ces départements de France est le plus touristique ?", lang: 'hi' as const, text: "फ्रांस के इन विभागों में से सबसे अधिक पर्यटन वाला कौन सा है?", explanation: "पेरिस (विभाग 75) फ्रांस का सबसे अधिक पर्यटन वाला विभाग है। राजधानी अपने स्मारकों, संग्रहालयों और सांस्कृतिक जीवन के कारण हर साल लाखों पर्यटकों को आकर्षित करती है।", choices: [{ id: 'a' as const, text: "पेरिस" }, { id: 'b' as const, text: "क्रूज़" }, { id: 'c' as const, text: "कांताल" }, { id: 'd' as const, text: "लोज़ेर" }] },
  // Q85
  { textFr: "Quand peut-on visiter gratuitement des lieux culturels en France ?", lang: 'hi' as const, text: "फ्रांस में सांस्कृतिक स्थलों का मुफ्त भ्रमण कब किया जा सकता है?", explanation: "यूरोपीय विरासत दिवस, जो हर साल सितंबर में आयोजित होते हैं, फ्रांस में कई सांस्कृतिक स्थलों और ऐतिहासिक स्मारकों का मुफ्त भ्रमण करने की अनुमति देते हैं।", choices: [{ id: 'a' as const, text: "यूरोपीय विरासत दिवसों के दौरान" }, { id: 'b' as const, text: "केवल 14 जुलाई को" }, { id: 'c' as const, text: "वर्ष के हर रविवार को" }, { id: 'd' as const, text: "स्कूल की छुट्टियों के दौरान" }] },
  // Q86
  { textFr: "Combien de personnes parlent français dans le monde ?", lang: 'hi' as const, text: "दुनिया में कितने लोग फ्रांसीसी बोलते हैं?", explanation: "दुनिया में लगभग 30 करोड़ लोग फ्रांसीसी बोलते हैं। फ्रांसीसी पाँचवीं सबसे अधिक बोली जाने वाली भाषा है और 29 देशों में आधिकारिक भाषा है।", choices: [{ id: 'a' as const, text: "लगभग 30 करोड़" }, { id: 'b' as const, text: "लगभग 10 करोड़" }, { id: 'c' as const, text: "लगभग 50 करोड़" }, { id: 'd' as const, text: "लगभग 5 करोड़" }] },
  // Q87
  { textFr: "Qui était Marguerite Yourcenar ?", lang: 'hi' as const, text: "मार्गरीत यूर्सनार कौन थीं?", explanation: "मार्गरीत यूर्सनार (1903-1987) एक फ्रांसीसी लेखिका थीं, 1980 में अकादेमी फ्रांसेज़ में चुनी गई पहली महिला। वे अपने ऐतिहासिक उपन्यासों जैसे 'मेमोयर्स डादरियन' के लिए जानी जाती हैं।", choices: [{ id: 'a' as const, text: "अकादेमी फ्रांसेज़ में चुनी गई पहली महिला" }, { id: 'b' as const, text: "भौतिकी की नोबेल पुरस्कार विजेता वैज्ञानिक" }, { id: 'c' as const, text: "19वीं शताब्दी की एक अन्वेषक" }, { id: 'd' as const, text: "बारोक संगीत की एक संगीतकार" }] },
  // Q88
  { textFr: "Quel peintre est français ?", lang: 'hi' as const, text: "कौन सा चित्रकार फ्रांसीसी है?", explanation: "क्लॉद मोने (1840-1926) एक फ्रांसीसी चित्रकार और प्रभाववाद आंदोलन के संस्थापक थे। वे अपनी नीम्फ़ेया और रूएन गिरजाघर की चित्र श्रृंखलाओं के लिए प्रसिद्ध हैं।", choices: [{ id: 'a' as const, text: "क्लॉद मोने" }, { id: 'b' as const, text: "पाब्लो पिकासो" }, { id: 'c' as const, text: "विन्सेंट वैन गॉग" }, { id: 'd' as const, text: "सल्वाडोर डाली" }] },
  // Q89
  { textFr: "Quel musée est situé à Paris ?", lang: 'hi' as const, text: "कौन सा संग्रहालय पेरिस में स्थित है?", explanation: "मुसे दोर्से पेरिस में एक पुराने रेलवे स्टेशन में स्थित है। इसमें दुनिया का सबसे बड़ा प्रभाववादी और उत्तर-प्रभाववादी कला संग्रह है।", choices: [{ id: 'a' as const, text: "मुसे दोर्से" }, { id: 'b' as const, text: "ब्रिटिश म्यूज़ियम" }, { id: 'c' as const, text: "प्राडो संग्रहालय" }, { id: 'd' as const, text: "मेट्रोपॉलिटन म्यूज़ियम" }] },
  // Q90
  { textFr: "Qui était Auguste Rodin ?", lang: 'hi' as const, text: "ऑगस्ट रोदां कौन थे?", explanation: "ऑगस्ट रोदां (1840-1917) एक फ्रांसीसी मूर्तिकार थे, जिन्हें आधुनिक मूर्तिकला का जनक माना जाता है। वे 'ले पांसर' (विचारक) और 'ले बुर्जुआ द कालै' के रचयिता हैं।", choices: [{ id: 'a' as const, text: "एक फ्रांसीसी मूर्तिकार, ले पांसर के रचयिता" }, { id: 'b' as const, text: "एक प्रभाववादी चित्रकार" }, { id: 'c' as const, text: "एफिल टॉवर के वास्तुकार" }, { id: 'd' as const, text: "एक रोमांटिक लेखक" }] },
  // Q91
  { textFr: "Quel est le classement de la langue française parmi les langues les plus parlées dans le monde ?", lang: 'hi' as const, text: "दुनिया में सबसे अधिक बोली जाने वाली भाषाओं में फ्रांसीसी भाषा का क्या स्थान है?", explanation: "फ्रांसीसी दुनिया में पाँचवीं सबसे अधिक बोली जाने वाली भाषा है। यह 29 देशों में आधिकारिक भाषा है और पाँचों महाद्वीपों में बोली जाती है।", choices: [{ id: 'a' as const, text: "पाँचवीं सबसे अधिक बोली जाने वाली भाषा" }, { id: 'b' as const, text: "दूसरी सबसे अधिक बोली जाने वाली भाषा" }, { id: 'c' as const, text: "दसवीं सबसे अधिक बोली जाने वाली भाषा" }, { id: 'd' as const, text: "पहली सबसे अधिक बोली जाने वाली भाषा" }] },
  // Q92
  { textFr: "Quelle cathédrale célèbre a été en partie détruite par un incendie en 2019 ?", lang: 'hi' as const, text: "कौन सा प्रसिद्ध गिरजाघर 2019 में आग से आंशिक रूप से नष्ट हो गया?", explanation: "पेरिस का नोत्रे-डाम गिरजाघर 15 अप्रैल 2019 को आग से गंभीर रूप से क्षतिग्रस्त हो गया था। इसका शिखर और छत का एक हिस्सा ढह गया। इसका जीर्णोद्धार किया गया और दिसंबर 2024 में इसे फिर से खोला गया।", choices: [{ id: 'a' as const, text: "नोत्रे-डाम डी पेरिस" }, { id: 'b' as const, text: "रैंस का गिरजाघर" }, { id: 'c' as const, text: "शार्त्र का गिरजाघर" }, { id: 'd' as const, text: "स्ट्रासबर्ग का गिरजाघर" }] },
  // Q93
  { textFr: "Qui était une écrivaine française célèbre ?", lang: 'hi' as const, text: "एक प्रसिद्ध फ्रांसीसी लेखिका कौन थीं?", explanation: "कोलेत (1873-1954) एक प्रसिद्ध फ्रांसीसी उपन्यासकार थीं, क्लोडीन श्रृंखला सहित कई उपन्यासों की लेखिका। वे फ्रांस में राष्ट्रीय अंतिम संस्कार प्राप्त करने वाली दूसरी महिला थीं।", choices: [{ id: 'a' as const, text: "कोलेत" }, { id: 'b' as const, text: "जेन ऑस्टिन" }, { id: 'c' as const, text: "वर्जीनिया वुल्फ" }, { id: 'd' as const, text: "अगाथा क्रिस्टी" }] },
  // Q94
  { textFr: "Qui était un célèbre musicien français ?", lang: 'hi' as const, text: "एक प्रसिद्ध फ्रांसीसी संगीतकार कौन थे?", explanation: "क्लॉद देबुसी (1862-1918) एक फ्रांसीसी संगीतकार और प्रभाववादी संगीत के प्रमुख व्यक्तित्व थे। वे विशेष रूप से 'क्लेर दे ल्यून' और 'ला मेर' के लिए जाने जाते हैं।", choices: [{ id: 'a' as const, text: "क्लॉद देबुसी" }, { id: 'b' as const, text: "लुडविग वान बीथोवन" }, { id: 'c' as const, text: "वॉल्फगैंग अमेडियस मोत्सार्ट" }, { id: 'd' as const, text: "योहान सेबैस्टियन बाख" }] },
  // Q95
  { textFr: "Qui était Auguste Renoir ?", lang: 'hi' as const, text: "ऑगस्ट रेनोआर कौन थे?", explanation: "ऑगस्ट रेनोआर (1841-1919) एक फ्रांसीसी चित्रकार और प्रभाववाद के महान उस्तादों में से एक थे। वे अपने दैनिक जीवन के दृश्यों और अपने चमकदार चित्रों के लिए प्रसिद्ध हैं।", choices: [{ id: 'a' as const, text: "एक फ्रांसीसी प्रभाववादी चित्रकार" }, { id: 'b' as const, text: "18वीं शताब्दी के एक मूर्तिकार" }, { id: 'c' as const, text: "एक यथार्थवादी लेखक" }, { id: 'd' as const, text: "पुनर्जागरण काल के एक वास्तुकार" }] },
  // Q96
  { textFr: "Quelle fête est française ?", lang: 'hi' as const, text: "कौन सा त्योहार फ्रांसीसी है?", explanation: "21 जून को मनाया जाने वाला संगीत उत्सव 1982 में जैक लैंग द्वारा बनाया गया एक फ्रांसीसी मूल का त्योहार है। आज इसे दुनिया के कई देशों में मनाया जाता है।", choices: [{ id: 'a' as const, text: "संगीत उत्सव" }, { id: 'b' as const, text: "थैंक्सगिविंग" }, { id: 'c' as const, text: "हैलोवीन" }, { id: 'd' as const, text: "सेंट पैट्रिक दिवस" }] },
  // Q97
  { textFr: "Parmi ces textes, lequel a été adopté sous Napoléon Ier ?", lang: 'hi' as const, text: "इन ग्रंथों में से कौन सा नेपोलियन प्रथम के शासन में अपनाया गया?", explanation: "नागरिक संहिता 1804 में नेपोलियन प्रथम के शासन में अपनाई गई। नेपोलियन कोड भी कहा जाने वाला, इसने फ्रांसीसी कानून को एकीकृत किया और आज भी फ्रांस में नागरिक कानून का आधार है।", choices: [{ id: 'a' as const, text: "नागरिक संहिता" }, { id: 'b' as const, text: "मानव और नागरिक अधिकारों की घोषणा" }, { id: 'c' as const, text: "चर्च और राज्य के अलगाव का कानून" }, { id: 'd' as const, text: "पाँचवें गणराज्य का संविधान" }] },
  // Q98
  { textFr: "Qui a été président de la Ve République ?", lang: 'hi' as const, text: "पाँचवें गणराज्य के राष्ट्रपति कौन रहे हैं?", explanation: "जाक शिराक 1995 से 2007 तक पाँचवें गणराज्य के राष्ट्रपति रहे। वे पाँचवें गणराज्य के पाँचवें राष्ट्रपति थे, फ्रांस्वा मितेरां के बाद।", choices: [{ id: 'a' as const, text: "जाक शिराक" }, { id: 'b' as const, text: "विंस्टन चर्चिल" }, { id: 'c' as const, text: "कोनराड एडेनॉयर" }, { id: 'd' as const, text: "बेनिटो मुसोलिनी" }] },
  // Q99
  { textFr: "Que signifie la date du 14 juillet pour les Français ?", lang: 'hi' as const, text: "14 जुलाई की तारीख फ्रांसीसियों के लिए क्या अर्थ रखती है?", explanation: "14 जुलाई फ्रांस का राष्ट्रीय दिवस है। यह 1789 में बैस्टिल के पतन, निरंकुशता के अंत के प्रतीक, और 1790 के संघ उत्सव की याद में मनाया जाता है।", choices: [{ id: 'a' as const, text: "यह राष्ट्रीय दिवस है, बैस्टिल के पतन की स्मृति में" }, { id: 'b' as const, text: "यह संविधान की वर्षगाँठ है" }, { id: 'c' as const, text: "यह यूरोप दिवस है" }, { id: 'd' as const, text: "यह युद्धविराम का दिन है" }] },
  // Q100
  { textFr: "Lequel de ces pays est un pays fondateur de l'Union européenne ?", lang: 'hi' as const, text: "इनमें से कौन सा देश यूरोपीय संघ का संस्थापक देश है?", explanation: "फ्रांस जर्मनी, इटली, बेल्जियम, नीदरलैंड और लक्ज़मबर्ग के साथ यूरोपीय निर्माण के छह संस्थापक देशों में से एक है। ECSC की स्थापना 1951 में हुई।", choices: [{ id: 'a' as const, text: "फ्रांस" }, { id: 'b' as const, text: "यूनाइटेड किंगडम" }, { id: 'c' as const, text: "स्पेन" }, { id: 'd' as const, text: "पोलैंड" }] },
  // Q101
  { textFr: "Dans quelle région est située une partie des plages du débarquement ?", lang: 'hi' as const, text: "सैन्य अवतरण के कुछ समुद्र तट किस क्षेत्र में स्थित हैं?", explanation: "6 जून 1944 के सैन्य अवतरण के समुद्र तट नॉरमैंडी में स्थित हैं। पाँच समुद्र तट (यूटा, ओमाहा, गोल्ड, जूनो, स्वॉर्ड) प्रमुख स्मृति स्थल हैं।", choices: [{ id: 'a' as const, text: "नॉरमैंडी" }, { id: 'b' as const, text: "ब्रिटनी" }, { id: 'c' as const, text: "पिकार्डी" }, { id: 'd' as const, text: "अकितेन" }] },
  // Q102
  { textFr: "Dans quelle ville les rois de France étaient-ils couronnés ?", lang: 'hi' as const, text: "फ्रांस के राजाओं का राज्याभिषेक किस शहर में होता था?", explanation: "फ्रांस के राजाओं का राज्याभिषेक पारंपरिक रूप से रैंस के गिरजाघर में होता था। यह परंपरा लगभग 496 में क्लोविस के बपतिस्मा से शुरू हुई और सदियों तक जारी रही।", choices: [{ id: 'a' as const, text: "रैंस" }, { id: 'b' as const, text: "पेरिस" }, { id: 'c' as const, text: "वर्साय" }, { id: 'd' as const, text: "ऑर्लिएं" }] },
  // Q103
  { textFr: "En quelle année l'Union européenne a-t-elle été fondée ?", lang: 'hi' as const, text: "यूरोपीय संघ की स्थापना किस वर्ष हुई?", explanation: "यूरोपीय संघ की स्थापना 1992 में मास्ट्रिच संधि द्वारा हुई। इस संधि ने यूरोपीय आर्थिक समुदाय को यूरोपीय संघ में बदल दिया और एकल मुद्रा की नींव रखी।", choices: [{ id: 'a' as const, text: "1992" }, { id: 'b' as const, text: "1957" }, { id: 'c' as const, text: "2002" }, { id: 'd' as const, text: "1951" }] },
  // Q104
  { textFr: "Qui a aboli l'esclavage en France ?", lang: 'hi' as const, text: "फ्रांस में दासता को किसने समाप्त किया?", explanation: "विक्टर शोल्शर ने 27 अप्रैल 1848 को फ्रांस में दासता के अंतिम उन्मूलन के आदेश का प्रणयन किया। वे उस समय दूसरे गणराज्य के तहत उपनिवेश मामलों के उप-सचिव थे।", choices: [{ id: 'a' as const, text: "विक्टर शोल्शर" }, { id: 'b' as const, text: "नेपोलियन बोनापार्ट" }, { id: 'c' as const, text: "जूल्स फेरी" }, { id: 'd' as const, text: "लिओन गांबेता" }] },
  // Q105
  { textFr: "Lors de la Seconde Guerre mondiale, à quelle date Paris a-t-elle été libérée ?", lang: 'hi' as const, text: "द्वितीय विश्व युद्ध के दौरान पेरिस किस तारीख को मुक्त हुआ?", explanation: "पेरिस 25 अगस्त 1944 को एक जनविद्रोह और जनरल लेक्लेर्क की दूसरी बख्तरबंद डिवीजन के आगमन के बाद मुक्त हुआ। इस घटना ने फ्रांस की मुक्ति में एक महत्वपूर्ण मोड़ दिया।", choices: [{ id: 'a' as const, text: "25 अगस्त 1944" }, { id: 'b' as const, text: "6 जून 1944" }, { id: 'c' as const, text: "8 मई 1945" }, { id: 'd' as const, text: "18 जून 1940" }] },
  // Q106
  { textFr: "Quel était le principal port français impliqué dans la traite négrière au XVIIIe siècle ?", lang: 'hi' as const, text: "18वीं शताब्दी में दास व्यापार में शामिल मुख्य फ्रांसीसी बंदरगाह कौन सा था?", explanation: "नांत 18वीं शताब्दी में दास व्यापार में शामिल मुख्य फ्रांसीसी बंदरगाह था। शहर ने सबसे अधिक फ्रांसीसी दास व्यापार अभियान आयोजित किए और आज वहाँ दासता उन्मूलन का एक स्मारक है।", choices: [{ id: 'a' as const, text: "नांत" }, { id: 'b' as const, text: "मार्सेय" }, { id: 'c' as const, text: "ला आव्र" }, { id: 'd' as const, text: "ब्रेस्ट" }] },
  // Q107
  { textFr: "Quel célèbre philosophe des Lumières a dénoncé l'esclavage ?", lang: 'hi' as const, text: "प्रबोधन काल के किस प्रसिद्ध दार्शनिक ने दासता की निंदा की?", explanation: "वोल्तेयर (1694-1778) प्रबोधन काल के एक दार्शनिक थे जिन्होंने दासता की निंदा की, विशेषकर 'कंदीद' में। प्रबोधन के दार्शनिकों ने इस प्रथा पर सवाल उठाने में प्रमुख भूमिका निभाई।", choices: [{ id: 'a' as const, text: "वोल्तेयर" }, { id: 'b' as const, text: "नेपोलियन बोनापार्ट" }, { id: 'c' as const, text: "लुई XIV" }, { id: 'd' as const, text: "रिशलू" }] },
  // Q108
  { textFr: "Quel plat est une spécialité de la cuisine française ?", lang: 'hi' as const, text: "कौन सा व्यंजन फ्रांसीसी पाक कला की विशेषता है?", explanation: "कॉक ओ वाँ फ्रांसीसी पाक कला का एक पारंपरिक व्यंजन है, जो लाल शराब में पकाए गए मुर्गे, बेकन और मशरूम से बनाया जाता है। फ्रांसीसी भोजन कला को यूनेस्को की अमूर्त सांस्कृतिक विरासत में शामिल किया गया है।", choices: [{ id: 'a' as const, text: "कॉक ओ वाँ" }, { id: 'b' as const, text: "पैएला" }, { id: 'c' as const, text: "सुशी" }, { id: 'd' as const, text: "फिश एंड चिप्स" }] },
  // Q109
  { textFr: "Qui était Marie Curie ?", lang: 'hi' as const, text: "मैरी क्यूरी कौन थीं?", explanation: "मैरी क्यूरी (1867-1934) एक फ्रांसीसी-पोलिश भौतिक विज्ञानी और रसायनज्ञ थीं, नोबेल पुरस्कार प्राप्त करने वाली पहली महिला। उन्होंने रेडियोधर्मिता पर अपने कार्य के लिए दो नोबेल पुरस्कार (1903 में भौतिकी और 1911 में रसायन विज्ञान) प्राप्त किए।", choices: [{ id: 'a' as const, text: "एक फ्रांसीसी-पोलिश भौतिक विज्ञानी, दो बार नोबेल पुरस्कार विजेता" }, { id: 'b' as const, text: "19वीं शताब्दी की एक फ्रांसीसी उपन्यासकार" }, { id: 'c' as const, text: "द्वितीय विश्व युद्ध की एक प्रतिरोधी" }, { id: 'd' as const, text: "फ्रांस की एक रानी" }] },
  // Q110
  { textFr: "Qui a peint « La Liberté guidant le peuple » ?", lang: 'hi' as const, text: "«स्वतंत्रता जनता का नेतृत्व करते हुए» किसने चित्रित किया?", explanation: "यूजीन देलाक्रोआ ने 1830 में 'स्वतंत्रता जनता का नेतृत्व करते हुए' चित्रित किया। यह प्रसिद्ध चित्र जुलाई 1830 की क्रांति को दर्शाता है और लूव्र संग्रहालय में प्रदर्शित है।", choices: [{ id: 'a' as const, text: "यूजीन देलाक्रोआ" }, { id: 'b' as const, text: "क्लॉद मोने" }, { id: 'c' as const, text: "पॉल सेज़ान" }, { id: 'd' as const, text: "ऑगस्ट रेनोआर" }] },
  // Q111
  { textFr: "Dans quel grand musée parisien est exposée la Joconde ?", lang: 'hi' as const, text: "मोना लिसा किस बड़े पेरिसी संग्रहालय में प्रदर्शित है?", explanation: "लिओनार्दो दा विंची की मोना लिसा (ला जोकोंड) पेरिस के लूव्र संग्रहालय में प्रदर्शित है। यह दुनिया की सबसे प्रसिद्ध पेंटिंग और संग्रहालय के संग्रह का एक रत्न है।", choices: [{ id: 'a' as const, text: "लूव्र संग्रहालय" }, { id: 'b' as const, text: "मुसे दोर्से" }, { id: 'c' as const, text: "पोम्पिदू केंद्र" }, { id: 'd' as const, text: "रोदां संग्रहालय" }] },
  // Q112
  { textFr: "Quel château célèbre se trouve près de Paris et symbolise le pouvoir royal de Louis XIV ?", lang: 'hi' as const, text: "कौन सा प्रसिद्ध महल पेरिस के निकट है और लुई XIV की शाही शक्ति का प्रतीक है?", explanation: "वर्साय का महल लुई XIV से लुई XVI तक फ्रांस के राजाओं का मुख्य निवास था। 17वीं शताब्दी में निर्मित, यह निरंकुश राजतंत्र की शक्ति का प्रतीक है।", choices: [{ id: 'a' as const, text: "वर्साय का महल" }, { id: 'b' as const, text: "शांबोर का महल" }, { id: 'c' as const, text: "फॉन्तेनब्लो का महल" }, { id: 'd' as const, text: "शेनोंसो का महल" }] },
  // Q113
  { textFr: "Où peut-on voir des peintures préhistoriques en France ?", lang: 'hi' as const, text: "फ्रांस में प्रागैतिहासिक चित्रकारी कहाँ देखी जा सकती है?", explanation: "डॉर्डॉन में लास्को गुफा में लगभग 17,000 वर्ष पुरानी प्रागैतिहासिक चित्रकारियाँ हैं। 1940 में खोजी गई, इसे 'प्रागैतिहास की सिस्टिन चैपल' कहा जाता है।", choices: [{ id: 'a' as const, text: "लास्को गुफा में" }, { id: 'b' as const, text: "वर्साय के महल में" }, { id: 'c' as const, text: "लूव्र संग्रहालय में" }, { id: 'd' as const, text: "शार्त्र के गिरजाघर में" }] },
  // Q114
  { textFr: "Quel peintre célèbre a peint les Nymphéas ?", lang: 'hi' as const, text: "किस प्रसिद्ध चित्रकार ने नीम्फ़ेया (वाटर लिलीज़) चित्रित किए?", explanation: "क्लॉद मोने ने जिवेर्नी में अपने बगीचे में प्रसिद्ध नीम्फ़ेया श्रृंखला चित्रित की। 1895 से 1926 के बीच बनाई गई ये प्रभाववादी पेंटिंग पेरिस में ऑरांजरी संग्रहालय में प्रदर्शित हैं।", choices: [{ id: 'a' as const, text: "क्लॉद मोने" }, { id: 'b' as const, text: "एडगार देगा" }, { id: 'c' as const, text: "पॉल गॉगैं" }, { id: 'd' as const, text: "एडुआर मानेट" }] },
  // Q115
  { textFr: "Que symbolise le 1er mai ?", lang: 'hi' as const, text: "1 मई क्या प्रतीक है?", explanation: "1 मई फ्रांस में श्रम दिवस है, 1947 से सार्वजनिक अवकाश। यह श्रमिकों के अधिकारों का उत्सव दिवस है, जो पारंपरिक रूप से लिली ऑफ़ द वैली की टहनी भेंट करके मनाया जाता है।", choices: [{ id: 'a' as const, text: "श्रम दिवस" }, { id: 'b' as const, text: "राष्ट्रीय दिवस" }, { id: 'c' as const, text: "संगीत उत्सव" }, { id: 'd' as const, text: "विजय दिवस" }] },
  // Q116
  { textFr: "Qui était Monsieur Rouget de Lisle ?", lang: 'hi' as const, text: "श्रीमान रूजे दी लील कौन थे?", explanation: "क्लॉद जोज़ेफ रूजे दी लील (1760-1836) एक फ्रांसीसी अधिकारी और संगीतकार थे, जिन्होंने 1792 में ला मार्सेयेज़ की रचना की। यह देशभक्ति गीत फ्रांसीसी राष्ट्रगान बन गया।", choices: [{ id: 'a' as const, text: "ला मार्सेयेज़ के रचयिता" }, { id: 'b' as const, text: "पाँचवें गणराज्य के संस्थापक" }, { id: 'c' as const, text: "नेपोलियन के एक जनरल" }, { id: 'd' as const, text: "प्रबोधन काल के एक दार्शनिक" }] },
  // Q117
  { textFr: "À quelle occasion a été construite la tour Eiffel ?", lang: 'hi' as const, text: "एफिल टॉवर किस अवसर पर बनाया गया?", explanation: "एफिल टॉवर 1889 के विश्व मेले के लिए बनाया गया था, जो फ्रांसीसी क्रांति की शताब्दी मनाता था। गुस्ताव एफिल द्वारा डिज़ाइन किया गया, इसे मेले के बाद हटा दिया जाना था।", choices: [{ id: 'a' as const, text: "1889 का विश्व मेला" }, { id: 'b' as const, text: "1900 के ओलंपिक खेल" }, { id: 'c' as const, text: "1918 की विजय" }, { id: 'd' as const, text: "नेपोलियन का राज्याभिषेक" }] },
  // Q118
  { textFr: "Qui était un célèbre compositeur français ?", lang: 'hi' as const, text: "एक प्रसिद्ध फ्रांसीसी संगीत रचयिता कौन थे?", explanation: "मॉरिस रावेल (1875-1937) एक फ्रांसीसी संगीत रचयिता थे, प्रसिद्ध बोलेरो के लेखक। वे क्लॉद देबुसी के साथ 20वीं शताब्दी के सबसे महान फ्रांसीसी संगीत रचयिताओं में से एक हैं।", choices: [{ id: 'a' as const, text: "मॉरिस रावेल" }, { id: 'b' as const, text: "जूसेप्पे वेर्दी" }, { id: 'c' as const, text: "रिखार्ड वाग्नर" }, { id: 'd' as const, text: "प्योत्र चाइकोव्स्की" }] },
  // Q119
  { textFr: "Quel monument historique se trouve sur une île en Normandie ?", lang: 'hi' as const, text: "कौन सा ऐतिहासिक स्मारक नॉरमैंडी में एक द्वीप पर स्थित है?", explanation: "मों-सां-मिशेल नॉरमैंडी में एक चट्टानी टापू पर स्थित एक मध्ययुगीन मठ है। यह फ्रांस के सबसे अधिक देखे जाने वाले स्थलों में से एक है और यूनेस्को विश्व धरोहर में शामिल है।", choices: [{ id: 'a' as const, text: "मों-सां-मिशेल" }, { id: 'b' as const, text: "शांबोर का महल" }, { id: 'c' as const, text: "पोन दू गार" }, { id: 'd' as const, text: "कार्कासोन का किला" }] },
  // Q120
  { textFr: "Quelle île fait partie des Antilles françaises ?", lang: 'hi' as const, text: "कौन सा द्वीप फ्रांसीसी एंटिल्स का हिस्सा है?", explanation: "ग्वाडेलूप कैरेबियन सागर में फ्रांसीसी एंटिल्स का हिस्सा है। यह कई द्वीपों से बना एक फ्रांसीसी समुद्रपारीय विभाग और क्षेत्र है।", choices: [{ id: 'a' as const, text: "ग्वाडेलूप" }, { id: 'b' as const, text: "क्यूबा" }, { id: 'c' as const, text: "जमैका" }, { id: 'd' as const, text: "पोर्टो रिको" }] },
  // Q121
  { textFr: "Quelle île est française ?", lang: 'hi' as const, text: "कौन सा द्वीप फ्रांसीसी है?", explanation: "न्यू कैलेडोनिया प्रशांत महासागर में स्थित एक फ्रांसीसी क्षेत्र है। यह गणराज्य के भीतर विशेष दर्जे वाली एक विशिष्ट संस्था है।", choices: [{ id: 'a' as const, text: "न्यू कैलेडोनिया" }, { id: 'b' as const, text: "बहामास" }, { id: 'c' as const, text: "मालदीव" }, { id: 'd' as const, text: "बोर्नियो" }] },
  // Q122
  { textFr: "Quelle est la plus haute montagne de France ?", lang: 'hi' as const, text: "फ्रांस का सबसे ऊँचा पर्वत कौन सा है?", explanation: "मोंट ब्लांक, 4,809 मीटर ऊँचा, फ्रांस और पश्चिमी यूरोप का सबसे ऊँचा पर्वत है। यह फ्रांस और इटली की सीमा पर आल्प्स में स्थित है।", choices: [{ id: 'a' as const, text: "मोंट ब्लांक" }, { id: 'b' as const, text: "प्यू दे डोम" }, { id: 'c' as const, text: "पिक दू मिदी" }, { id: 'd' as const, text: "मों वांतू" }] },
  // Q123
  { textFr: "Quelle île française est située au sud-est du continent africain ?", lang: 'hi' as const, text: "कौन सा फ्रांसीसी द्वीप अफ्रीकी महाद्वीप के दक्षिण-पूर्व में स्थित है?", explanation: "मायोट हिंद महासागर में, अफ्रीकी महाद्वीप के दक्षिण-पूर्व में स्थित एक फ्रांसीसी द्वीप है। यह 2011 में फ्रांस का 101वाँ विभाग बना।", choices: [{ id: 'a' as const, text: "मायोट" }, { id: 'b' as const, text: "मार्टिनिक" }, { id: 'c' as const, text: "ग्वाडेलूप" }, { id: 'd' as const, text: "सां-पिएर-ए-मिकेलों" }] },
  // Q124
  { textFr: "Quel département français a une frontière avec le Brésil ?", lang: 'hi' as const, text: "किस फ्रांसीसी विभाग की ब्राज़ील के साथ सीमा है?", explanation: "फ्रांसीसी गयाना दक्षिण अमेरिका में स्थित एक समुद्रपारीय विभाग है जो ब्राज़ील के साथ सीमा साझा करता है। यह क्षेत्रफल के हिसाब से सबसे बड़ा फ्रांसीसी विभाग है।", choices: [{ id: 'a' as const, text: "गयाना" }, { id: 'b' as const, text: "मार्टिनिक" }, { id: 'c' as const, text: "रेयूनियन" }, { id: 'd' as const, text: "मायोट" }] },
  // Q125
  { textFr: "De quelle ville française décolle la fusée Ariane ?", lang: 'hi' as const, text: "एरियन रॉकेट किस फ्रांसीसी शहर से उड़ान भरता है?", explanation: "एरियन रॉकेट फ्रांसीसी गयाना के कूरू से उड़ान भरता है। गयाना अंतरिक्ष केंद्र 1968 से यूरोपीय अंतरिक्ष एजेंसी (ESA) का प्रक्षेपण आधार है।", choices: [{ id: 'a' as const, text: "कूरू" }, { id: 'b' as const, text: "तूलूज़" }, { id: 'c' as const, text: "बोर्दो" }, { id: 'd' as const, text: "मार्सेय" }] },
  // Q126
  { textFr: "Quel est le principal port maritime de France ?", lang: 'hi' as const, text: "फ्रांस का मुख्य समुद्री बंदरगाह कौन सा है?", explanation: "मार्सेय फ्रांस का मुख्य समुद्री बंदरगाह और भूमध्य सागर का पहला बंदरगाह है। मार्सेय का ग्रैंड पोर्ट मैरिटाइम हर साल लाखों टन माल का प्रबंधन करता है।", choices: [{ id: 'a' as const, text: "मार्सेय" }, { id: 'b' as const, text: "नांत" }, { id: 'c' as const, text: "ब्रेस्ट" }, { id: 'd' as const, text: "बोर्दो" }] },
  // Q127
  { textFr: "Quel est le chef-lieu de la région Auvergne-Rhône-Alpes ?", lang: 'hi' as const, text: "ऑवेर्न-रोन-आल्प्स क्षेत्र की राजधानी क्या है?", explanation: "लियोन ऑवेर्न-रोन-आल्प्स क्षेत्र की राजधानी है। यह फ्रांस का तीसरा सबसे बड़ा शहर और एक महत्वपूर्ण आर्थिक और सांस्कृतिक केंद्र है।", choices: [{ id: 'a' as const, text: "लियोन" }, { id: 'b' as const, text: "क्लेरमों-फेरां" }, { id: 'c' as const, text: "ग्रेनोबल" }, { id: 'd' as const, text: "सां-तेतिएन" }] },
  // Q128
  { textFr: "Quel est le chef-lieu de la région Bretagne ?", lang: 'hi' as const, text: "ब्रिटनी क्षेत्र की राजधानी क्या है?", explanation: "रेन ब्रिटनी क्षेत्र की राजधानी है। यह पश्चिमी फ्रांस में स्थित एक गतिशील और विश्वविद्यालयी शहर है।", choices: [{ id: 'a' as const, text: "रेन" }, { id: 'b' as const, text: "ब्रेस्ट" }, { id: 'c' as const, text: "नांत" }, { id: 'd' as const, text: "कांपेर" }] },
  // Q129
  { textFr: "Quel est le chef-lieu de la région Provence-Alpes-Côte d'Azur ?", lang: 'hi' as const, text: "प्रोवांस-आल्प्स-कोत दाज़ूर क्षेत्र की राजधानी क्या है?", explanation: "मार्सेय प्रोवांस-आल्प्स-कोत दाज़ूर (PACA) क्षेत्र की राजधानी है। यह फ्रांस का दूसरा सबसे बड़ा शहर और भूमध्य सागर का एक प्रमुख बंदरगाह है।", choices: [{ id: 'a' as const, text: "मार्सेय" }, { id: 'b' as const, text: "नीस" }, { id: 'c' as const, text: "तूलों" }, { id: 'd' as const, text: "ऐक्स-ऑं-प्रोवांस" }] },
  // Q130
  { textFr: "Quel est le 101e département français depuis 2011 ?", lang: 'hi' as const, text: "2011 से फ्रांस का 101वाँ विभाग कौन सा है?", explanation: "मायोट 2009 के जनमत संग्रह के बाद 31 मार्च 2011 को फ्रांस का 101वाँ विभाग बना। यह फ्रांसीसी गणराज्य में शामिल होने वाला सबसे नया समुद्रपारीय विभाग है।", choices: [{ id: 'a' as const, text: "मायोट" }, { id: 'b' as const, text: "गयाना" }, { id: 'c' as const, text: "न्यू कैलेडोनिया" }, { id: 'd' as const, text: "सां-मार्टन" }] },
  // Q131
  { textFr: "Quelle région française est réputée pour ses stations de ski ?", lang: 'hi' as const, text: "कौन सा फ्रांसीसी क्षेत्र अपने स्की रिसॉर्ट के लिए प्रसिद्ध है?", explanation: "ऑवेर्न-रोन-आल्प्स क्षेत्र फ्रांस में स्की रिसॉर्ट के लिए सबसे प्रसिद्ध है। इसमें शामोनी, ले दो आल्प्स और वाल-डी'ज़ेर जैसे कई प्रसिद्ध आल्पाइन स्की रिसॉर्ट हैं।", choices: [{ id: 'a' as const, text: "ऑवेर्न-रोन-आल्प्स" }, { id: 'b' as const, text: "इल-दे-फ्रांस" }, { id: 'c' as const, text: "नूवेल-अकितेन" }, { id: 'd' as const, text: "ब्रिटनी" }] },
];
