export const theme5Ar = [
  // Q1
  { textFr: "Quel numéro d'urgence permet d'appeler le SAMU ?", lang: 'ar' as const, text: "ما هو رقم الطوارئ للاتصال بخدمة الإسعاف (SAMU)؟", explanation: "الرقم 15 هو رقم الطوارئ لخدمة الإسعاف (SAMU - خدمة المساعدة الطبية العاجلة). يتيح الاتصال بطبيب منظم يقيّم الوضع ويرسل فرق الإنقاذ المناسبة.", choices: [{ id: 'a' as const, text: "15" }, { id: 'b' as const, text: "17" }, { id: 'c' as const, text: "18" }, { id: 'd' as const, text: "112" }] },
  // Q2
  { textFr: "Quel numéro d'urgence permet d'appeler les pompiers ?", lang: 'ar' as const, text: "ما هو رقم الطوارئ للاتصال بالإطفاء؟", explanation: "الرقم 18 هو رقم رجال الإطفاء. يتيح الإبلاغ عن حريق أو حادث أو أي وضع يستدعي تدخلاً طارئاً.", choices: [{ id: 'a' as const, text: "18" }, { id: 'b' as const, text: "15" }, { id: 'c' as const, text: "17" }, { id: 'd' as const, text: "114" }] },
  // Q3
  { textFr: "Après avoir obtenu le permis de conduire, que faut-il faire pour pouvoir conduire sa voiture ?", lang: 'ar' as const, text: "بعد الحصول على رخصة القيادة، ماذا يجب فعله لتتمكن من قيادة سيارتك؟", explanation: "للقيادة بشكل قانوني، يجب تأمين مركبتك لدى شركة تأمين. التأمين على السيارات إلزامي في فرنسا لتغطية الأضرار التي تلحق بالغير.", choices: [{ id: 'a' as const, text: "تأمين المركبة لدى شركة تأمين" }, { id: 'b' as const, text: "التسجيل في مقر الشرطة" }, { id: 'c' as const, text: "إجراء فحص طبي إلزامي" }, { id: 'd' as const, text: "الحصول على تصريح خاص من البلدية" }] },
  // Q4
  { textFr: "À quelles conditions un mariage est-il reconnu juridiquement ?", lang: 'ar' as const, text: "بأي شروط يُعترف بالزواج قانونياً؟", explanation: "في فرنسا، الزواج المدني المُبرم في البلدية فقط هو المعترف به قانونياً. الزواج الديني ليس له قيمة قانونية إذا لم يسبقه زواج مدني.", choices: [{ id: 'a' as const, text: "إذا أُبرم في البلدية (زواج مدني)" }, { id: 'b' as const, text: "إذا أُبرم في مكان عبادة" }, { id: 'c' as const, text: "إذا اعترفت به عائلتا الزوجين" }, { id: 'd' as const, text: "إذا نظّمه كاتب عدل" }] },
  // Q5
  { textFr: "Quand faut-il déclarer son enfant au service d'état civil de la mairie ?", lang: 'ar' as const, text: "متى يجب التصريح بالمولود في مصلحة الحالة المدنية بالبلدية؟", explanation: "يجب التصريح بالولادة في غضون 5 أيام من الولادة لدى بلدية مكان الولادة. هذه المهلة محددة بالقانون.", choices: [{ id: 'a' as const, text: "في غضون 5 أيام من الولادة" }, { id: 'b' as const, text: "في غضون 30 يوماً من الولادة" }, { id: 'c' as const, text: "في غضون 3 أشهر من الولادة" }, { id: 'd' as const, text: "قبل مغادرة المستشفى" }] },
  // Q6
  { textFr: "Le travail non déclaré est :", lang: 'ar' as const, text: "العمل غير المصرّح به هو:", explanation: "العمل غير المصرّح به (العمل الأسود) محظور بموجب القانون. يحرم العامل من الحماية الاجتماعية ويعرّض صاحب العمل والعامل لعقوبات جزائية ومالية.", choices: [{ id: 'a' as const, text: "محظور بموجب القانون" }, { id: 'b' as const, text: "مسموح به للأعمال الصغيرة" }, { id: 'c' as const, text: "مسموح به إذا وافق العامل" }, { id: 'd' as const, text: "مسموح به للعمال الأجانب" }] },
  // Q7
  { textFr: "Que doit faire un employeur pour fixer un salaire ?", lang: 'ar' as const, text: "ماذا يجب على صاحب العمل فعله لتحديد الراتب؟", explanation: "يجب على صاحب العمل احترام الحد الأدنى للأجور (SMIC) والاتفاقيات الجماعية المعمول بها. لا يمكنه تحديد راتب أقل من الحد الأدنى القانوني.", choices: [{ id: 'a' as const, text: "احترام الحد الأدنى للأجور والاتفاقية الجماعية على الأقل" }, { id: 'b' as const, text: "تحديد المبلغ بحرية دون أي قيود" }, { id: 'c' as const, text: "طلب إذن من البلدية" }, { id: 'd' as const, text: "استشارة أصحاب العمل الآخرين في الحي" }] },
  // Q8
  { textFr: "Qu'est-ce que le SMIC ?", lang: 'ar' as const, text: "ما هو الحد الأدنى للأجور (SMIC)؟", explanation: "SMIC هو الحد الأدنى للأجور بين المهن. وهو الحد الأدنى القانوني للأجر بالساعة الذي لا يمكن لأي عامل أن يتقاضى أقل منه في فرنسا.", choices: [{ id: 'a' as const, text: "الحد الأدنى القانوني للأجور الذي لا يمكن دفع أقل منه للعامل" }, { id: 'b' as const, text: "متوسط رواتب الفرنسيين" }, { id: 'c' as const, text: "مساعدة مالية تدفعها الدولة للعاطلين عن العمل" }, { id: 'd' as const, text: "الحد الأقصى للراتب المسموح به قانوناً" }] },
  // Q9
  { textFr: "Quelle est la première démarche à réaliser pour chercher un emploi ?", lang: 'ar' as const, text: "ما هي الخطوة الأولى للبحث عن عمل؟", explanation: "الخطوة الأولى للبحث عن عمل هي التسجيل في France Travail (بول إمبلوا سابقاً). هذه المؤسسة تساعد الباحثين عن عمل في بحثهم ويمكنها صرف تعويضات لهم.", choices: [{ id: 'a' as const, text: "التسجيل في France Travail (بول إمبلوا سابقاً)" }, { id: 'b' as const, text: "الكتابة مباشرة إلى رئيس الجمهورية" }, { id: 'c' as const, text: "التسجيل في بلدية مكان الإقامة" }, { id: 'd' as const, text: "نشر إعلان في جريدة" }] },
  // Q10
  { textFr: "Quelle est la durée légale du temps de travail par semaine ?", lang: 'ar' as const, text: "ما هي المدة القانونية لوقت العمل الأسبوعي؟", explanation: "المدة القانونية للعمل في فرنسا هي 35 ساعة أسبوعياً. بعد ذلك، تُمنح الساعات الإضافية زيادة في الراتب أو راحة تعويضية.", choices: [{ id: 'a' as const, text: "35 ساعة" }, { id: 'b' as const, text: "39 ساعة" }, { id: 'c' as const, text: "40 ساعة" }, { id: 'd' as const, text: "32 ساعة" }] },
  // Q11
  { textFr: "Qui est aidé par France Travail ?", lang: 'ar' as const, text: "من يساعده France Travail؟", explanation: "يساعد France Travail (بول إمبلوا سابقاً) الأشخاص الباحثين عن عمل. يقدم مرافقة شخصية وتدريبات وصرف تعويضات البطالة.", choices: [{ id: 'a' as const, text: "الأشخاص الباحثون عن عمل" }, { id: 'b' as const, text: "المتقاعدون فقط" }, { id: 'c' as const, text: "أصحاب العمل حصراً" }, { id: 'd' as const, text: "الطلاب في التعليم الأولي" }] },
  // Q12
  { textFr: "Une personne étrangère en situation régulière peut créer son entreprise :", lang: 'ar' as const, text: "هل يمكن لشخص أجنبي في وضع قانوني إنشاء مشروعه التجاري:", explanation: "في فرنسا، يحق للشخص الأجنبي المقيم بشكل قانوني إنشاء مشروعه التجاري كأي مواطن فرنسي. لا توجد قيود على الجنسية لريادة الأعمال إذا كانت بطاقة الإقامة تسمح بذلك.", choices: [{ id: 'a' as const, text: "نعم، مثل أي شخص آخر" }, { id: 'b' as const, text: "لا، الفرنسيون فقط يمكنهم ذلك" }, { id: 'c' as const, text: "فقط بتصريح خاص من المحافظ" }, { id: 'd' as const, text: "فقط بعد 10 سنوات من الإقامة في فرنسا" }] },
  // Q13
  { textFr: "Une femme peut-elle créer son entreprise ?", lang: 'ar' as const, text: "هل يمكن للمرأة إنشاء مشروعها التجاري؟", explanation: "نعم، يمكن للمرأة إنشاء مشروعها التجاري في فرنسا. المساواة بين المرأة والرجل مبدأ أساسي في الجمهورية، بما في ذلك في المجال الاقتصادي والمهني.", choices: [{ id: 'a' as const, text: "نعم، بنفس شروط الرجل" }, { id: 'b' as const, text: "لا، يجب أن تحصل على موافقة زوجها" }, { id: 'c' as const, text: "فقط في بعض القطاعات المهنية" }, { id: 'd' as const, text: "فقط إذا كانت فرنسية الجنسية" }] },
  // Q14
  { textFr: "À partir de quel âge un mineur peut-il travailler ?", lang: 'ar' as const, text: "من أي سن يمكن للقاصر العمل؟", explanation: "في فرنسا، يمكن للقاصر العمل ابتداءً من سن 16 عاماً بإذن والديه. توجد استثناءات للتدريب المهني ابتداءً من 15 عاماً بشروط معينة.", choices: [{ id: 'a' as const, text: "16 سنة" }, { id: 'b' as const, text: "14 سنة" }, { id: 'c' as const, text: "18 سنة" }, { id: 'd' as const, text: "12 سنة" }] },
  // Q15
  { textFr: "Auprès de quel organisme faut-il demander le remboursement des frais de santé ?", lang: 'ar' as const, text: "لدى أي مؤسسة يجب طلب استرداد تكاليف الرعاية الصحية؟", explanation: "يجب طلب استرداد تكاليف الرعاية الصحية من الضمان الاجتماعي (التأمين الصحي / CPAM). يتحمل جزءاً من النفقات الطبية.", choices: [{ id: 'a' as const, text: "الضمان الاجتماعي (التأمين الصحي)" }, { id: 'b' as const, text: "البلدية" }, { id: 'c' as const, text: "France Travail" }, { id: 'd' as const, text: "بنك فرنسا" }] },
  // Q16
  { textFr: "Qu'est-ce qu'un numéro d'urgence ?", lang: 'ar' as const, text: "ما هو رقم الطوارئ؟", explanation: "رقم الطوارئ هو رقم هاتف مجاني، متاح على مدار الساعة، يتيح الاتصال بخدمات الإنقاذ (الإسعاف، الإطفاء، الشرطة) في حالات الطوارئ.", choices: [{ id: 'a' as const, text: "رقم مجاني للاتصال بخدمات الإنقاذ في أي وقت" }, { id: 'b' as const, text: "رقم مدفوع مخصص للأطباء" }, { id: 'c' as const, text: "رقم متاح فقط خلال النهار" }, { id: 'd' as const, text: "رقم للاتصال بالتأمين الصحي التكميلي" }] },
  // Q17
  { textFr: "Concernant l'accès aux soins, quelle proposition est correcte ?", lang: 'ar' as const, text: "بخصوص الحصول على الرعاية الصحية، أي عبارة صحيحة؟", explanation: "في فرنسا، لكل شخص الحق في العلاج بغض النظر عن جنسيته أو وضعه المالي. الحصول على الرعاية الصحية حق أساسي يكفله القانون.", choices: [{ id: 'a' as const, text: "لكل شخص الحق في العلاج" }, { id: 'b' as const, text: "المواطنون الفرنسيون فقط لهم حق الحصول على الرعاية" }, { id: 'c' as const, text: "الحصول على الرعاية يعتمد على مستوى الدخل" }, { id: 'd' as const, text: "يجب الحصول على تصريح من المحافظة لاستشارة طبيب" }] },
  // Q18
  { textFr: "En cas de problème de santé non urgent, à qui faut-il s'adresser en premier ?", lang: 'ar' as const, text: "في حالة مشكلة صحية غير طارئة، إلى من يجب التوجه أولاً؟", explanation: "في حالة مشكلة صحية غير طارئة، يجب استشارة الطبيب المعالج أولاً. ينسق الرعاية ويوجه إلى أخصائي عند الحاجة. هذا يتجنب اكتظاظ أقسام الطوارئ بالمستشفيات.", choices: [{ id: 'a' as const, text: "الطبيب المعالج" }, { id: 'b' as const, text: "قسم الطوارئ بالمستشفى" }, { id: 'c' as const, text: "الصيدلية" }, { id: 'd' as const, text: "خدمة الإسعاف بالاتصال على 15" }] },
  // Q19
  { textFr: "Quel est le rôle du médecin traitant ?", lang: 'ar' as const, text: "ما هو دور الطبيب المعالج؟", explanation: "يضمن الطبيب المعالج المتابعة الطبية الشاملة للمريض. ينسق الرعاية ويوجه إلى أخصائيين عند الحاجة ويُحدّث الملف الطبي. هو المحاور الأول للأسئلة الصحية.", choices: [{ id: 'a' as const, text: "ضمان المتابعة الطبية وتنسيق رعاية المريض" }, { id: 'b' as const, text: "وصف الأدوية الجنيسة فقط" }, { id: 'c' as const, text: "إدارة الطوارئ بالمستشفى" }, { id: 'd' as const, text: "استرداد تكاليف الرعاية الصحية" }] },
  // Q20
  { textFr: "Dans quelles situations doit-on se rendre aux urgences de l'hôpital ?", lang: 'ar' as const, text: "في أي حالات يجب التوجه إلى قسم الطوارئ بالمستشفى؟", explanation: "قسم الطوارئ بالمستشفى مخصص للحالات الخطيرة التي تتطلب رعاية فورية: حادث خطير، ألم شديد، صعوبة في التنفس، إلخ. للمشاكل غير الطارئة، يجب استشارة الطبيب المعالج.", choices: [{ id: 'a' as const, text: "في حالة حادث خطير أو وضع يهدد الحياة" }, { id: 'b' as const, text: "لنزلة برد بسيطة أو إنفلونزا خفيفة" }, { id: 'c' as const, text: "لتجديد وصفة طبية" }, { id: 'd' as const, text: "للحصول على شهادة طبية رياضية" }] },
  // Q21
  { textFr: "Quel est l'objectif des vaccinations obligatoires ?", lang: 'ar' as const, text: "ما هو الهدف من التطعيمات الإلزامية؟", explanation: "تهدف التطعيمات الإلزامية إلى حماية صحة كل فرد والمجتمع بمنع انتشار الأمراض الخطيرة. هذا هو مبدأ الحماية الجماعية.", choices: [{ id: 'a' as const, text: "حماية الصحة الفردية والجماعية من الأمراض الخطيرة" }, { id: 'b' as const, text: "تمكين شركات الأدوية من تحقيق أرباح" }, { id: 'c' as const, text: "مراقبة السكان" }, { id: 'd' as const, text: "الاستغناء عن زيارة الطبيب" }] },
  // Q22
  { textFr: "À quoi sert la carte Vitale ?", lang: 'ar' as const, text: "ما فائدة بطاقة Vitale؟", explanation: "بطاقة Vitale هي بطاقة التأمين الصحي. تتيح استرداد تكاليف الرعاية الصحية بسرعة أكبر من الضمان الاجتماعي. تحتوي على المعلومات الإدارية للمؤمَّن.", choices: [{ id: 'a' as const, text: "استرداد تكاليف الرعاية الصحية من الضمان الاجتماعي" }, { id: 'b' as const, text: "الحصول على تخفيضات في الصيدليات" }, { id: 'c' as const, text: "إثبات الهوية" }, { id: 'd' as const, text: "دفع الضرائب" }] },
  // Q23
  { textFr: "À quoi sert une mutuelle santé ?", lang: 'ar' as const, text: "ما فائدة التأمين الصحي التكميلي؟", explanation: "التأمين الصحي التكميلي (المتبادلة) يكمل تعويضات الضمان الاجتماعي. يتحمل كل أو جزء من تكاليف الرعاية الصحية المتبقية على عاتق المؤمَّن.", choices: [{ id: 'a' as const, text: "تكملة تعويضات الضمان الاجتماعي" }, { id: 'b' as const, text: "استبدال الضمان الاجتماعي" }, { id: 'c' as const, text: "الحصول على عمل" }, { id: 'd' as const, text: "تمويل التقاعد" }] },
  // Q24
  { textFr: "Jusqu'à quel âge l'école est-elle obligatoire ?", lang: 'ar' as const, text: "حتى أي سن يكون التعليم إلزامياً؟", explanation: "التعليم إلزامي في فرنسا لجميع الأطفال من 3 إلى 16 سنة. منذ قانون 2019، يبدأ التعليم الإلزامي من سن 3 سنوات ويستمر حتى 16 سنة.", choices: [{ id: 'a' as const, text: "16 سنة" }, { id: 'b' as const, text: "14 سنة" }, { id: 'c' as const, text: "18 سنة" }, { id: 'd' as const, text: "12 سنة" }] },
  // Q25
  { textFr: "L'autorité parentale prévoit l'obligation :", lang: 'ar' as const, text: "تنص السلطة الأبوية على واجب:", explanation: "تنص السلطة الأبوية على واجب حماية الطفل وتعليمه والسماح بنموه. يجب على الوالدين الحرص على صحته وسلامته وأخلاقه.", choices: [{ id: 'a' as const, text: "حماية الطفل وتعليمه وضمان نموه" }, { id: 'b' as const, text: "ترك الطفل يقرر مستقبله وحده من سن 10 سنوات" }, { id: 'c' as const, text: "تسليم الطفل للدولة منذ ولادته" }, { id: 'd' as const, text: "تسجيل الطفل في مدرسة خاصة" }] },
  // Q26
  { textFr: "Pour qui l'école est-elle obligatoire ?", lang: 'ar' as const, text: "لمن يكون التعليم إلزامياً؟", explanation: "التعليم إلزامي لجميع الأطفال المقيمين في فرنسا من 3 إلى 16 سنة، بغض النظر عن جنسيتهم أو وضعهم الإداري.", choices: [{ id: 'a' as const, text: "لجميع الأطفال المقيمين في فرنسا من 3 إلى 16 سنة" }, { id: 'b' as const, text: "فقط للأطفال الذين يحملون الجنسية الفرنسية" }, { id: 'c' as const, text: "فقط للأولاد" }, { id: 'd' as const, text: "للأطفال من 6 إلى 18 سنة" }] },
  // Q27
  { textFr: "Quel diplôme obtient-on à la fin du lycée ?", lang: 'ar' as const, text: "ما هي الشهادة التي يحصل عليها الطالب في نهاية الثانوية؟", explanation: "البكالوريا هي الشهادة التي تُمنح في نهاية الثانوية. تُختتم بها الدراسة الثانوية وتتيح الالتحاق بالتعليم العالي.", choices: [{ id: 'a' as const, text: "البكالوريا" }, { id: 'b' as const, text: "شهادة الإعدادية" }, { id: 'c' as const, text: "شهادة الكفاءة المهنية (CAP)" }, { id: 'd' as const, text: "الإجازة" }] },
  // Q28
  { textFr: "Dans quels établissements scolaires vont les élèves après l'école élémentaire ?", lang: 'ar' as const, text: "إلى أي مؤسسة تعليمية يذهب التلاميذ بعد المدرسة الابتدائية؟", explanation: "بعد المدرسة الابتدائية، يذهب التلاميذ إلى الإعدادية (الكوليج). تستقبل الإعدادية التلاميذ من الصف السادس إلى الصف الثالث، عادة من 11 إلى 15 سنة.", choices: [{ id: 'a' as const, text: "الإعدادية (الكوليج)" }, { id: 'b' as const, text: "الثانوية (الليسيه)" }, { id: 'c' as const, text: "الجامعة" }, { id: 'd' as const, text: "الروضة" }] },
  // Q29
  { textFr: "Un enfant inscrit à l'école :", lang: 'ar' as const, text: "الطفل المسجل في المدرسة:", explanation: "يجب على الطفل المسجل في المدرسة الحضور بانتظام. الانتظام المدرسي التزام قانوني. الغيابات غير المبررة قد تؤدي إلى عقوبات على الوالدين.", choices: [{ id: 'a' as const, text: "يجب أن يحضر إلى المدرسة بانتظام (واجب الانتظام)" }, { id: 'b' as const, text: "يمكنه التغيب متى شاء" }, { id: 'c' as const, text: "غير ملزم بحضور جميع الحصص" }, { id: 'd' as const, text: "يمكنه مغادرة المدرسة في أي وقت من اليوم" }] },
  // Q30
  { textFr: "Les enfants qui ne parlent pas français :", lang: 'ar' as const, text: "الأطفال الذين لا يتحدثون الفرنسية:", explanation: "يستفيد الأطفال الذين لا يتحدثون الفرنسية من تعليم مكيّف لتعلم الفرنسية. توجد برامج خاصة (UPE2A) في المدارس لمساعدتهم في تعلم اللغة.", choices: [{ id: 'a' as const, text: "يستفيدون من تعليم مكيّف لتعلم الفرنسية في المدرسة" }, { id: 'b' as const, text: "لا يمكن تسجيلهم في المدرسة العامة" }, { id: 'c' as const, text: "يجب عليهم تعلم الفرنسية أولاً قبل الذهاب للمدرسة" }, { id: 'd' as const, text: "يُوجَّهون إلى مدارس خاصة منفصلة" }] },
  // Q31
  { textFr: "Quel mariage est reconnu par l'État ?", lang: 'ar' as const, text: "أي زواج تعترف به الدولة؟", explanation: "الزواج المدني المُبرم في البلدية أمام موظف الحالة المدنية هو الوحيد المعترف به من الدولة الفرنسية. الزواج الديني ليس له أي قيمة قانونية في فرنسا.", choices: [{ id: 'a' as const, text: "الزواج المدني المُبرم في البلدية" }, { id: 'b' as const, text: "الزواج الديني المُبرم في مكان العبادة" }, { id: 'c' as const, text: "الزواج العرفي المُبرم في العائلة" }, { id: 'd' as const, text: "جميع أنواع الزواج معترف بها من الدولة" }] },
  // Q32
  { textFr: "Auprès de quelle institution les parents peuvent-ils inscrire leur enfant à l'école publique ?", lang: 'ar' as const, text: "لدى أي مؤسسة يمكن للوالدين تسجيل طفلهم في المدرسة العامة؟", explanation: "يجب على الوالدين تسجيل طفلهم في المدرسة العامة لدى بلدية بلدة إقامتهم. تحدد لهم البلدية المدرسة المرجعية حسب مكان السكن.", choices: [{ id: 'a' as const, text: "بلدية بلدتهم" }, { id: 'b' as const, text: "المحافظة" }, { id: 'c' as const, text: "الأكاديمية التعليمية" }, { id: 'd' as const, text: "وزارة التربية الوطنية" }] },
  // Q33
  { textFr: "En cas de divorce, qui exerce l'autorité parentale ?", lang: 'ar' as const, text: "في حالة الطلاق، من يمارس السلطة الأبوية؟", explanation: "في حالة الطلاق، يستمر كلا الوالدين في ممارسة السلطة الأبوية بشكل مشترك، إلا إذا قرر القاضي خلاف ذلك. مصلحة الطفل لها الأولوية في جميع القرارات.", choices: [{ id: 'a' as const, text: "كلا الوالدين بشكل مشترك" }, { id: 'b' as const, text: "الأم فقط" }, { id: 'c' as const, text: "الأب فقط" }, { id: 'd' as const, text: "الدولة تتكفل بالطفل" }] },
  // Q34
  { textFr: "Quelle aide permet aux personnes qui ont des difficultés financières d'avoir un avocat ?", lang: 'ar' as const, text: "ما هي المساعدة التي تتيح للأشخاص ذوي الصعوبات المالية الحصول على محامٍ؟", explanation: "المساعدة القضائية تتيح للأشخاص ذوي الدخل المنخفض الاستفادة من محامٍ تتحمل الدولة تكاليفه كلياً أو جزئياً. تضمن حق الوصول إلى العدالة للجميع.", choices: [{ id: 'a' as const, text: "المساعدة القضائية" }, { id: 'b' as const, text: "RSA (دخل التضامن الفعال)" }, { id: 'c' as const, text: "بدل السكن" }, { id: 'd' as const, text: "CMU (التغطية الصحية الشاملة)" }] },
  // Q35
  { textFr: "Où faut-il déclarer la naissance d'un enfant ?", lang: 'ar' as const, text: "أين يجب التصريح بولادة طفل؟", explanation: "يجب التصريح بولادة الطفل في بلدية مكان الولادة في غضون 5 أيام من الوضع. يقوم موظف الحالة المدنية بإعداد شهادة الميلاد.", choices: [{ id: 'a' as const, text: "في بلدية مكان الولادة" }, { id: 'b' as const, text: "في محافظة المقاطعة" }, { id: 'c' as const, text: "في مركز الشرطة" }, { id: 'd' as const, text: "في المحكمة القضائية" }] },
  // Q36
  { textFr: "Quelle est l'une des conditions pour passer l'examen du permis de conduire ?", lang: 'ar' as const, text: "ما هو أحد شروط اجتياز امتحان رخصة القيادة؟", explanation: "لاجتياز امتحان رخصة القيادة في فرنسا، يجب أن يكون عمرك 17 سنة على الأقل (أو 15 سنة للقيادة المرافقة). كما يجب الحصول على قانون المرور.", choices: [{ id: 'a' as const, text: "أن يكون عمرك 17 سنة على الأقل" }, { id: 'b' as const, text: "أن يكون عمرك 21 سنة على الأقل" }, { id: 'c' as const, text: "أن تكون فرنسي الجنسية" }, { id: 'd' as const, text: "امتلاك سيارة خاصة" }] },
  // Q37
  { textFr: "Un bail locatif est valide s'il est :", lang: 'ar' as const, text: "يكون عقد الإيجار صالحاً إذا كان:", explanation: "يكون عقد الإيجار صالحاً إذا كان موقعاً من المالك والمستأجر. يجب أن يكون مكتوباً ويحتوي على بيانات إلزامية مثل وصف المسكن ومبلغ الإيجار والمدة.", choices: [{ id: 'a' as const, text: "موقعاً من المالك والمستأجر" }, { id: 'b' as const, text: "مصادقاً عليه من البلدية" }, { id: 'c' as const, text: "مسجلاً في المحكمة" }, { id: 'd' as const, text: "معتمداً من كاتب عدل إلزامياً" }] },
  // Q38
  { textFr: "Où peut-on déposer un lave-vaisselle cassé ?", lang: 'ar' as const, text: "أين يمكن التخلص من غسالة أطباق معطلة؟", explanation: "غسالة الأطباق المعطلة هي نفايات أجهزة كهربائية وإلكترونية (DEEE). يمكن إيداعها في مركز إعادة التدوير أو استردادها مجاناً من المتجر عند شراء جهاز جديد مماثل.", choices: [{ id: 'a' as const, text: "في مركز إعادة التدوير أو استردادها من متجر" }, { id: 'b' as const, text: "على الرصيف أمام المنزل" }, { id: 'c' as const, text: "في سلة النفايات المنزلية" }, { id: 'd' as const, text: "في حاوية إعادة تدوير الزجاج" }] },
  // Q39
  { textFr: "Quel numéro d'urgence permet d'appeler la police ?", lang: 'ar' as const, text: "ما هو رقم الطوارئ للاتصال بالشرطة؟", explanation: "الرقم 17 هو رقم الطوارئ للاتصال بالشرطة أو الدرك. يتيح الإبلاغ عن حالة طوارئ تتطلب تدخل قوات الأمن.", choices: [{ id: 'a' as const, text: "17" }, { id: 'b' as const, text: "15" }, { id: 'c' as const, text: "18" }, { id: 'd' as const, text: "119" }] },
  // Q40
  { textFr: "À qui est accessible la contraception ?", lang: 'ar' as const, text: "لمن تتاح وسائل منع الحمل؟", explanation: "وسائل منع الحمل متاحة لكل شخص، بما في ذلك القاصرون. يمكن للقاصرات الحصول على وسائل منع الحمل مجاناً وبسرية تامة، دون إذن الوالدين.", choices: [{ id: 'a' as const, text: "لكل شخص، بما في ذلك القاصرون" }, { id: 'b' as const, text: "للبالغين فقط" }, { id: 'c' as const, text: "للنساء المتزوجات فقط" }, { id: 'd' as const, text: "فقط بوصفة من أخصائي" }] },
  // Q41
  { textFr: "Qu'est-ce que le principe de confidentialité dans le domaine de la santé ?", lang: 'ar' as const, text: "ما هو مبدأ السرية في مجال الصحة؟", explanation: "مبدأ السرية (السر الطبي) يعني أن الطبيب لا يمكنه الكشف عن معلومات صحة مريضه لأطراف ثالثة دون موافقته. هذا حق أساسي للمريض.", choices: [{ id: 'a' as const, text: "لا يمكن للطبيب الكشف عن المعلومات الطبية للمريض دون موافقته" }, { id: 'b' as const, text: "لا يمكن للمريض معرفة تشخيصه الخاص" }, { id: 'c' as const, text: "تُنشر النتائج الطبية للبحث العلمي" }, { id: 'd' as const, text: "صاحب العمل لديه حق الوصول إلى الملف الطبي للموظف" }] },
  // Q42
  { textFr: "L'inscription à l'Assurance maladie est :", lang: 'ar' as const, text: "التسجيل في التأمين الصحي هو:", explanation: "التسجيل في التأمين الصحي إلزامي. كل شخص يعمل أو يقيم في فرنسا بشكل مستقر ومنتظم له الحق في تغطية تكاليفه الصحية.", choices: [{ id: 'a' as const, text: "إلزامي" }, { id: 'b' as const, text: "اختياري" }, { id: 'c' as const, text: "مخصص للموظفين فقط" }, { id: 'd' as const, text: "مدفوع واختياري" }] },
  // Q43
  { textFr: "Qui peut demander un congé parental d'éducation ?", lang: 'ar' as const, text: "من يمكنه طلب إجازة أبوية تربوية؟", explanation: "يمكن للأب أو الأم طلب إجازة أبوية تربوية دون تمييز. تتيح التوقف عن العمل أو تقليله للعناية بالطفل.", choices: [{ id: 'a' as const, text: "الأب أو الأم" }, { id: 'b' as const, text: "الأم فقط" }, { id: 'c' as const, text: "الأب فقط" }, { id: 'd' as const, text: "لا أحد منهما، الإجازة تلقائية" }] },
  // Q44
  { textFr: "Quelles sont les affaires traitées par le conseil de prud'hommes ?", lang: 'ar' as const, text: "ما هي القضايا التي يعالجها مجلس العمل (البرودوم)؟", explanation: "يعالج مجلس العمل النزاعات بين العمال وأصحاب العمل المتعلقة بعقد العمل: الفصل التعسفي، عدم دفع الراتب، التحرش في العمل، إلخ.", choices: [{ id: 'a' as const, text: "النزاعات بين العمال وأصحاب العمل المتعلقة بعقد العمل" }, { id: 'b' as const, text: "قضايا الطلاق" }, { id: 'c' as const, text: "الجرائم الجنائية" }, { id: 'd' as const, text: "النزاعات بين الجيران" }] },
  // Q45
  { textFr: "Lorsqu'un employeur veut qu'un salarié travaille plus longtemps que la durée prévue dans le contrat de travail :", lang: 'ar' as const, text: "عندما يريد صاحب العمل أن يعمل الموظف أكثر من المدة المنصوص عليها في عقد العمل:", explanation: "يجب أن تُدفع الساعات الإضافية بزيادة في الراتب أو تُعوَّض براحة. لا يمكن لصاحب العمل فرض ساعات إضافية دون احترام القواعد القانونية.", choices: [{ id: 'a' as const, text: "يجب عليه دفع الساعات الإضافية بزيادة" }, { id: 'b' as const, text: "يمكنه المطالبة بذلك دون تعويض" }, { id: 'c' as const, text: "يجب على الموظف الرفض دائماً" }, { id: 'd' as const, text: "هذا غير قانوني في جميع الحالات" }] },
  // Q46
  { textFr: "Quelle est la mission de France Travail ?", lang: 'ar' as const, text: "ما هي مهمة France Travail؟", explanation: "مهمة France Travail (بول إمبلوا سابقاً) هي مرافقة الباحثين عن عمل في بحثهم، وتعويض العاطلين عن العمل، ومساعدة الشركات في التوظيف.", choices: [{ id: 'a' as const, text: "مرافقة الباحثين عن عمل وتعويض العاطلين" }, { id: 'b' as const, text: "تحديد الرواتب في الشركات" }, { id: 'c' as const, text: "مراقبة ظروف العمل في الشركات" }, { id: 'd' as const, text: "إدارة تقاعد الموظفين" }] },
  // Q47
  { textFr: "Dans une entreprise, le droit syndical permet :", lang: 'ar' as const, text: "في شركة، يتيح الحق النقابي:", explanation: "يتيح الحق النقابي للعمال التجمع للدفاع عن مصالحهم المهنية. تتفاوض النقابات على ظروف العمل والرواتب مع صاحب العمل.", choices: [{ id: 'a' as const, text: "للعمال التجمع للدفاع عن مصالحهم المهنية" }, { id: 'b' as const, text: "لصاحب العمل الفصل بحرية" }, { id: 'c' as const, text: "للعمال عدم العمل متى شاءوا" }, { id: 'd' as const, text: "للدولة مراقبة الشركة" }] },
  // Q48
  { textFr: "Dans une entreprise, le droit de grève autorise :", lang: 'ar' as const, text: "في شركة، يسمح حق الإضراب بـ:", explanation: "حق الإضراب المعترف به في الدستور يسمح للعمال بالتوقف الجماعي عن العمل للدفاع عن مطالبهم المهنية. هذا حق أساسي في فرنسا.", choices: [{ id: 'a' as const, text: "توقف العمال جماعياً عن العمل للدفاع عن مطالبهم" }, { id: 'b' as const, text: "إغلاق صاحب العمل للشركة دون إشعار" }, { id: 'c' as const, text: "تدمير العمال لمعدات الشركة" }, { id: 'd' as const, text: "عدم عودة العمال للعمل أبداً" }] },
  // Q49
  { textFr: "Quelles sont les conditions pour toucher les allocations chômage ?", lang: 'ar' as const, text: "ما هي شروط الحصول على تعويضات البطالة؟", explanation: "للحصول على تعويضات البطالة، يجب أن تكون قد عملت لفترة كافية (6 أشهر على الأقل خلال 24 شهراً الأخيرة)، وأن تكون مسجلاً في France Travail وتبحث بنشاط عن عمل.", choices: [{ id: 'a' as const, text: "العمل لفترة كافية والتسجيل في France Travail والبحث النشط عن عمل" }, { id: 'b' as const, text: "يكفي ألا يكون لديك عمل" }, { id: 'c' as const, text: "أن تحمل الجنسية الفرنسية" }, { id: 'd' as const, text: "أن يكون عمرك أكثر من 25 سنة" }] },
  // Q50
  { textFr: "Qu'est-ce que l'école maternelle ?", lang: 'ar' as const, text: "ما هي الروضة (المدرسة التحضيرية)؟", explanation: "الروضة تستقبل الأطفال من 3 إلى 6 سنوات. تمثل المرحلة الأولى من التعليم وتحضر الأطفال للتعلمات الأساسية في المدرسة الابتدائية.", choices: [{ id: 'a' as const, text: "المدرسة التي تستقبل الأطفال من 3 إلى 6 سنوات" }, { id: 'b' as const, text: "مدرسة مخصصة للفتيات" }, { id: 'c' as const, text: "مؤسسة للأطفال من 6 إلى 11 سنة" }, { id: 'd' as const, text: "حضانة تديرها الدولة" }] },
  // Q51
  { textFr: "Comment s'appelle le diplôme passé par les élèves à la fin du collège ?", lang: 'ar' as const, text: "ما اسم الشهادة التي يجتازها التلاميذ في نهاية الإعدادية؟", explanation: "شهادة البريفيه الوطنية (DNB)، المعروفة بشهادة الإعدادية، تُجتاز في نهاية الصف الثالث. تقيّم المعارف المكتسبة خلال الدراسة في الإعدادية.", choices: [{ id: 'a' as const, text: "شهادة البريفيه الوطنية (شهادة الإعدادية)" }, { id: 'b' as const, text: "البكالوريا" }, { id: 'c' as const, text: "شهادة الدراسة الابتدائية" }, { id: 'd' as const, text: "شهادة الكفاءة المهنية (CAP)" }] },
  // Q52
  { textFr: "Les parents d'élève ont le droit de :", lang: 'ar' as const, text: "يحق لأولياء أمور التلاميذ:", explanation: "يحق لأولياء أمور التلاميذ المشاركة في حياة المدرسة، لا سيما بانتخاب ممثلي أولياء الأمور والمشاركة في مجالس المدرسة أو الفصل.", choices: [{ id: 'a' as const, text: "المشاركة في حياة المدرسة وانتخاب ممثلي الأولياء" }, { id: 'b' as const, text: "اختيار معلمي طفلهم" }, { id: 'c' as const, text: "تعديل المنهج الدراسي" }, { id: 'd' as const, text: "تحديد أوقات الحصص" }] },
  // Q53
  { textFr: "Qui peut manger à la cantine scolaire ?", lang: 'ar' as const, text: "من يمكنه تناول الطعام في المقصف المدرسي؟", explanation: "يمكن لجميع التلاميذ المسجلين في المؤسسة تناول الطعام في المقصف المدرسي. الوصول إلى المطعم المدرسي حق لجميع الأطفال المتمدرسين دون تمييز.", choices: [{ id: 'a' as const, text: "جميع التلاميذ المسجلين في المؤسسة" }, { id: 'b' as const, text: "فقط التلاميذ الذين يعمل أولياؤهم" }, { id: 'c' as const, text: "فقط التلاميذ البعيدون عن المدرسة" }, { id: 'd' as const, text: "فقط التلاميذ المستفيدون من المنح" }] },
  // Q54
  { textFr: "À quel âge commence l'instruction obligatoire des enfants ?", lang: 'ar' as const, text: "في أي سن يبدأ التعليم الإلزامي للأطفال؟", explanation: "منذ قانون 26 يوليو 2019، أصبح التعليم إلزامياً من سن 3 سنوات في فرنسا. يتوافق ذلك مع الدخول إلى الروضة.", choices: [{ id: 'a' as const, text: "3 سنوات" }, { id: 'b' as const, text: "5 سنوات" }, { id: 'c' as const, text: "6 سنوات" }, { id: 'd' as const, text: "4 سنوات" }] },
  // Q55
  { textFr: "Quel est l'âge de la majorité ?", lang: 'ar' as const, text: "ما هو سن الرشد؟", explanation: "سن الرشد في فرنسا هو 18 سنة. في هذا السن، يكتسب الشخص الأهلية القانونية الكاملة: يمكنه التصويت وتوقيع العقود والزواج دون إذن الوالدين، إلخ.", choices: [{ id: 'a' as const, text: "18 سنة" }, { id: 'b' as const, text: "16 سنة" }, { id: 'c' as const, text: "21 سنة" }, { id: 'd' as const, text: "17 سنة" }] },
  // Q56
  { textFr: "À l'école, il est interdit aux parents de :", lang: 'ar' as const, text: "في المدرسة، يُحظر على الأولياء:", explanation: "في المدرسة، لا يمكن للأولياء الاعتراض على تدريس بعض المواد الإلزامية في المنهج الدراسي. المحتوى التعليمي تحدده وزارة التربية الوطنية ويُفرض على الجميع.", choices: [{ id: 'a' as const, text: "الاعتراض على تدريس بعض المواد الإلزامية" }, { id: 'b' as const, text: "المشاركة في اجتماعات أولياء الأمور والمعلمين" }, { id: 'c' as const, text: "الاطلاع على دفتر نصوص طفلهم" }, { id: 'd' as const, text: "لقاء معلمي طفلهم" }] },
  // Q57
  { textFr: "Quel motif d'absence est accepté par l'école ?", lang: 'ar' as const, text: "ما هو سبب الغياب المقبول من المدرسة؟", explanation: "مرض الطفل (مع شهادة طبية) هو سبب غياب مشروع تقبله المدرسة. تشمل الأسباب المقبولة الأخرى الالتزامات العائلية الملحة أو الأعياد الدينية.", choices: [{ id: 'a' as const, text: "مرض الطفل" }, { id: 'b' as const, text: "رحلة عائلية للعطلة" }, { id: 'c' as const, text: "التخفيضات في المتاجر" }, { id: 'd' as const, text: "إرهاق الطفل" }] },
  // Q58
  { textFr: "Des parents ne respectent pas l'obligation d'instruction pour leurs enfants. Quelle sanction maximale risquent-ils ?", lang: 'ar' as const, text: "لا يحترم بعض الأولياء واجب تعليم أطفالهم. ما هي العقوبة القصوى التي يتعرضون لها؟", explanation: "يتعرض الأولياء الذين لا يحترمون واجب تعليم أطفالهم لعقوبة تصل إلى سنتين سجناً و30,000 يورو غرامة. التعليم التزام قانوني في فرنسا.", choices: [{ id: 'a' as const, text: "سنتان سجناً و30,000 يورو غرامة" }, { id: 'b' as const, text: "مجرد تحذير من البلدية" }, { id: 'c' as const, text: "غرامة 150 يورو" }, { id: 'd' as const, text: "لا توجد عقوبة منصوص عليها" }] },
  // Q59
  { textFr: "Quand ont lieu les vacances scolaires de Noël ?", lang: 'ar' as const, text: "متى تكون عطلة عيد الميلاد المدرسية؟", explanation: "تكون عطلة عيد الميلاد المدرسية في ديسمبر-يناير، عادة لمدة أسبوعين حول 25 ديسمبر و1 يناير. وهي موحدة لجميع المناطق المدرسية.", choices: [{ id: 'a' as const, text: "في ديسمبر-يناير لمدة أسبوعين تقريباً" }, { id: 'b' as const, text: "في نوفمبر لمدة أسبوع" }, { id: 'c' as const, text: "في فبراير لمدة أسبوعين" }, { id: 'd' as const, text: "في أكتوبر لمدة أسبوع" }] },
  // Q60
  { textFr: "À l'école, un enfant en situation de handicap :", lang: 'ar' as const, text: "في المدرسة، الطفل ذو الإعاقة:", explanation: "في فرنسا، يحق للطفل ذي الإعاقة التسجيل في أقرب مدرسة من مكان سكنه. المدرسة الشاملة مبدأ أساسي: لكل طفل الحق في تعليم مكيّف.", choices: [{ id: 'a' as const, text: "له الحق في التسجيل في أقرب مدرسة من مكان سكنه" }, { id: 'b' as const, text: "يجب أن يذهب حتماً إلى مؤسسة متخصصة" }, { id: 'c' as const, text: "لا يمكنه الالتحاق بالمدرسة" }, { id: 'd' as const, text: "يجب أن يبقى في المنزل مع معلم خاص" }] },
  // Q61
  { textFr: "Quelle action peut réaliser le locataire d'un logement sans l'autorisation du propriétaire ?", lang: 'ar' as const, text: "ما الإجراء الذي يمكن للمستأجر القيام به دون إذن المالك؟", explanation: "يمكن للمستأجر إجراء تعديلات بسيطة (ديكور، طلاء، أعمال صغيرة) دون طلب إذن المالك، بشرط عدم تغيير المسكن هيكلياً.", choices: [{ id: 'a' as const, text: "إجراء تعديلات بسيطة مثل طلاء الجدران أو تركيب أرفف" }, { id: 'b' as const, text: "هدم جدار فاصل" }, { id: 'c' as const, text: "تأجير المسكن من الباطن لشخص آخر" }, { id: 'd' as const, text: "تغيير النوافذ والباب الرئيسي" }] },
  // Q62
  { textFr: "Le stationnement sur une place réservée aux personnes handicapées :", lang: 'ar' as const, text: "الوقوف في مكان مخصص لذوي الإعاقة:", explanation: "الوقوف في مكان مخصص لذوي الإعاقة ممنوع بدون بطاقة التنقل الشاملة (CMI). يتعرض المخالفون لغرامة 135 يورو وسحب سيارتهم.", choices: [{ id: 'a' as const, text: "ممنوع بدون بطاقة التنقل الشاملة ويعاقب عليه بغرامة" }, { id: 'b' as const, text: "مسموح للجميع يوم الأحد" }, { id: 'c' as const, text: "مسموح إذا كان لفترة قصيرة" }, { id: 'd' as const, text: "غير منظم بالقانون" }] },
  // Q63
  { textFr: "Si une machine à laver est cassée, il est possible de :", lang: 'ar' as const, text: "إذا تعطلت غسالة ملابس، يمكن:", explanation: "يمكن إيداع الجهاز الكهربائي المنزلي المعطل في مركز إعادة التدوير أو استرداده من المتجر عند شراء جهاز جديد (التزام الاسترداد 1 مقابل 1). لا يجب رميه مع النفايات المنزلية.", choices: [{ id: 'a' as const, text: "إيداعها في مركز إعادة التدوير أو استردادها من متجر" }, { id: 'b' as const, text: "رميها في سلة النفايات المنزلية" }, { id: 'c' as const, text: "تركها على الرصيف" }, { id: 'd' as const, text: "رميها في حاوية إعادة التدوير" }] },
  // Q64
  { textFr: "Dans quel cas faut-il déclarer son enfant au service d'état civil ?", lang: 'ar' as const, text: "في أي حالة يجب التصريح بالطفل في مصلحة الحالة المدنية؟", explanation: "يجب التصريح بالطفل في مصلحة الحالة المدنية بالبلدية عند كل ولادة. هذا التصريح إلزامي في غضون 5 أيام من الولادة ويسمح بإعداد شهادة الميلاد.", choices: [{ id: 'a' as const, text: "عند كل ولادة طفل" }, { id: 'b' as const, text: "فقط للطفل الأول" }, { id: 'c' as const, text: "عندما يدخل الطفل المدرسة" }, { id: 'd' as const, text: "عندما يبلغ الطفل 18 سنة" }] },
  // Q65
  { textFr: "Qui peut demander le divorce de personnes mariées ?", lang: 'ar' as const, text: "من يمكنه طلب طلاق الأشخاص المتزوجين؟", explanation: "يمكن طلب الطلاق من أحد الزوجين أو من كليهما معاً (طلاق بالتراضي). طلب الطلاق حق معترف به لكل من الزوجين.", choices: [{ id: 'a' as const, text: "أحد الزوجين أو كلاهما معاً" }, { id: 'b' as const, text: "الزوج فقط" }, { id: 'c' as const, text: "عائلة الزوجين فقط" }, { id: 'd' as const, text: "رئيس البلدية" }] },
  // Q66
  { textFr: "La contraception :", lang: 'ar' as const, text: "وسائل منع الحمل:", explanation: "وسائل منع الحمل حق في فرنسا. متاحة للجميع بما في ذلك القاصرون، ويمكن الحصول عليها مجاناً لمن هم دون 26 سنة. اختيار وسيلة منع الحمل حر.", choices: [{ id: 'a' as const, text: "حق متاح للجميع بما في ذلك القاصرون" }, { id: 'b' as const, text: "محظورة في فرنسا" }, { id: 'c' as const, text: "تتطلب موافقة الزوج/الزوجة" }, { id: 'd' as const, text: "مخصصة للمتزوجين فقط" }] },
  // Q67
  { textFr: "Qu'est-ce que le tiers payant ?", lang: 'ar' as const, text: "ما هو نظام الدفع من طرف ثالث؟", explanation: "نظام الدفع من طرف ثالث يعفي المريض من دفع تكاليف الرعاية الصحية مسبقاً. يتم الدفع مباشرة للمهني الصحي من التأمين الصحي و/أو التأمين التكميلي.", choices: [{ id: 'a' as const, text: "نظام يعفي المريض من دفع تكاليف الرعاية مسبقاً" }, { id: 'b' as const, text: "ضريبة على الأدوية" }, { id: 'c' as const, text: "مبلغ إضافي يُدفع عند الاستشارة" }, { id: 'd' as const, text: "تأمين إلزامي للأطباء" }] },
  // Q68
  { textFr: "L'avortement est-il possible en France ?", lang: 'ar' as const, text: "هل الإجهاض ممكن في فرنسا؟", explanation: "نعم، الإجهاض (الإنهاء الطوعي للحمل - IVG) قانوني في فرنسا. منذ 2022، يمكن إجراؤه حتى 14 أسبوعاً من الحمل. أصبح حقاً دستورياً منذ 2024.", choices: [{ id: 'a' as const, text: "نعم، هو حق يكفله القانون" }, { id: 'b' as const, text: "لا، هو ممنوع تماماً" }, { id: 'c' as const, text: "فقط في حالة خطر على الأم" }, { id: 'd' as const, text: "فقط بموافقة الزوج/الشريك" }] },
  // Q69
  { textFr: "Quels sont les textes qui définissent les règles au travail ?", lang: 'ar' as const, text: "ما هي النصوص التي تحدد قواعد العمل؟", explanation: "تُحدد قواعد العمل بقانون العمل والاتفاقيات الجماعية وعقد العمل. يضع قانون العمل الإطار القانوني الأدنى الذي يجب على كل صاحب عمل احترامه.", choices: [{ id: 'a' as const, text: "قانون العمل والاتفاقيات الجماعية وعقد العمل" }, { id: 'b' as const, text: "النظام الداخلي للشركة فقط" }, { id: 'c' as const, text: "قرارات رئيس البلدية" }, { id: 'd' as const, text: "الاتفاقات الشفهية بين الزملاء" }] },
  // Q70
  { textFr: "Qui a le droit de se syndiquer ?", lang: 'ar' as const, text: "من له الحق في الانضمام لنقابة؟", explanation: "لكل عامل الحق في الانضمام لنقابة بغض النظر عن جنسيته. الحرية النقابية حق أساسي يعترف به الدستور الفرنسي والاتفاقيات الدولية.", choices: [{ id: 'a' as const, text: "كل عامل بغض النظر عن جنسيته" }, { id: 'b' as const, text: "العمال الفرنسيون فقط" }, { id: 'c' as const, text: "الإطارات فقط" }, { id: 'd' as const, text: "الموظفون الحكوميون فقط" }] },
  // Q71
  { textFr: "Est-il possible de licencier une femme enceinte ou en congé maternité, en raison de sa grossesse ?", lang: 'ar' as const, text: "هل يمكن فصل امرأة حامل أو في إجازة أمومة بسبب حملها؟", explanation: "لا، يُحظر فصل امرأة بسبب حملها أو خلال إجازة الأمومة. يحمي القانون النساء الحوامل من أي تمييز مرتبط بالأمومة.", choices: [{ id: 'a' as const, text: "لا، هذا محظور بالقانون" }, { id: 'b' as const, text: "نعم، صاحب العمل حر في فصل من يشاء" }, { id: 'c' as const, text: "نعم، لكن مع إشعار مسبق بـ 3 أشهر" }, { id: 'd' as const, text: "نعم، إذا كانت الشركة تواجه صعوبات اقتصادية" }] },
  // Q72
  { textFr: "L'instruction des enfants est obligatoire de :", lang: 'ar' as const, text: "تعليم الأطفال إلزامي من:", explanation: "تعليم الأطفال إلزامي من 3 سنوات إلى 16 سنة في فرنسا. ينطبق هذا الالتزام على جميع الأطفال المقيمين في الأراضي الفرنسية بغض النظر عن جنسيتهم.", choices: [{ id: 'a' as const, text: "3 سنوات إلى 16 سنة" }, { id: 'b' as const, text: "6 سنوات إلى 16 سنة" }, { id: 'c' as const, text: "3 سنوات إلى 18 سنة" }, { id: 'd' as const, text: "5 سنوات إلى 14 سنة" }] },
  // Q73
  { textFr: "Quelle est la définition de l'autorité parentale ?", lang: 'ar' as const, text: "ما هو تعريف السلطة الأبوية؟", explanation: "السلطة الأبوية هي مجموع حقوق وواجبات الوالدين تجاه طفلهم القاصر. تهدف إلى مصلحة الطفل: حمايته وصحته وسلامته وتعليمه ونموه.", choices: [{ id: 'a' as const, text: "مجموع حقوق وواجبات الوالدين لحماية وتعليم طفلهم" }, { id: 'b' as const, text: "حق الوالدين في معاقبة طفلهم بحرية" }, { id: 'c' as const, text: "سلطة الدولة على العائلات" }, { id: 'd' as const, text: "حق الأجداد على أحفادهم" }] },
  // Q74
  { textFr: "En tant que parent d'élève, il est possible de :", lang: 'ar' as const, text: "بصفتك ولي أمر تلميذ، يمكنك:", explanation: "بصفتك ولي أمر تلميذ، يمكنك المشاركة في هيئات المدرسة (مجلس المدرسة، مجلس الفصل) والترشح كممثل لأولياء الأمور لإسماع صوتك.", choices: [{ id: 'a' as const, text: "المشاركة في هيئات المدرسة والترشح كممثل للأولياء" }, { id: 'b' as const, text: "اختيار المواد المُدرَّسة لطفلك" }, { id: 'c' as const, text: "تقرير انتقال طفلك للصف الأعلى" }, { id: 'd' as const, text: "الحلول محل معلم غائب" }] },
  // Q75
  { textFr: "Quelle instruction est prévue pour les enfants qui ne parlent pas français ?", lang: 'ar' as const, text: "ما هو التعليم المخصص للأطفال الذين لا يتحدثون الفرنسية؟", explanation: "يستفيد الأطفال غير الناطقين بالفرنسية من تعليم خاص للفرنسية في وحدات تربوية (UPE2A) مع تسجيلهم في فصل عادي يتناسب مع أعمارهم.", choices: [{ id: 'a' as const, text: "تعليم خاص للفرنسية (UPE2A) بموازاة فصل عادي" }, { id: 'b' as const, text: "لا شيء، يجب عليهم التعلم بمفردهم" }, { id: 'c' as const, text: "يُعادون إلى بلدهم الأصلي" }, { id: 'd' as const, text: "يُوضعون في مدارس متخصصة منفصلة" }] },
  // Q76
  { textFr: "S'agissant de l'accueil des enfants en situation de handicap à l'école, laquelle des propositions est vraie ?", lang: 'ar' as const, text: "فيما يخص استقبال الأطفال ذوي الإعاقة في المدرسة، أي عبارة صحيحة؟", explanation: "المدرسة الشاملة حق في فرنسا. لكل طفل ذي إعاقة الحق في التمدرس في مدرسة حيه مع تكييفات مناسبة (مرافق AESH، معدات متخصصة، إلخ).", choices: [{ id: 'a' as const, text: "لكل طفل ذي إعاقة الحق في التمدرس في بيئة عادية مع تكييفات" }, { id: 'b' as const, text: "لا يمكن للأطفال ذوي الإعاقة الذهاب للمدرسة" }, { id: 'c' as const, text: "فقط الأطفال ذوو الإعاقة الخفيفة يمكنهم الذهاب للمدرسة" }, { id: 'd' as const, text: "يجب على الأطفال ذوي الإعاقة الذهاب إلى محافظة أخرى" }] },
  // Q77
  { textFr: "Depuis le 1er juillet 2021, quelle est la durée du congé paternité ?", lang: 'ar' as const, text: "منذ 1 يوليو 2021، ما هي مدة إجازة الأبوة؟", explanation: "منذ 1 يوليو 2021، أصبحت إجازة الأبوة 25 يوماً تقويمياً (32 يوماً في حالة الولادات المتعددة). ضاعف هذا الإصلاح المدة السابقة البالغة 11 يوماً.", choices: [{ id: 'a' as const, text: "25 يوماً تقويمياً" }, { id: 'b' as const, text: "11 يوماً تقويمياً" }, { id: 'c' as const, text: "14 يوماً تقويمياً" }, { id: 'd' as const, text: "30 يوماً تقويمياً" }] },
  // Q78
  { textFr: "Est-ce possible de punir physiquement ses enfants ?", lang: 'ar' as const, text: "هل يمكن معاقبة الأطفال جسدياً؟", explanation: "لا، العنف الجسدي ضد الأطفال محظور في فرنسا. منذ قانون 10 يوليو 2019، يُحظر كل عنف تربوي عادي (صفع، لطم، إلخ). تُمارس السلطة الأبوية دون عنف.", choices: [{ id: 'a' as const, text: "لا، كل عنف جسدي ضد الأطفال محظور" }, { id: 'b' as const, text: "نعم، إذا كان لأسباب تربوية" }, { id: 'c' as const, text: "نعم، طالما لا يترك آثاراً" }, { id: 'd' as const, text: "نعم، هذا حق من حقوق الوالدين" }] },
];
