export const theme4Es = [
  // ─── Q1–Q47: CSP questions (difficulty 1) ──────────────────────────────────

  { textFr: "En quelle année a débuté la Révolution française ?", lang: 'es' as const, text: "¿En qué año comenzó la Revolución francesa?", explanation: "La Revolución francesa comenzó en 1789 con la toma de la Bastilla el 14 de julio. Este acontecimiento marca el fin del Antiguo Régimen y el inicio de una era de profundos cambios políticos y sociales en Francia.", choices: [{ id: 'a' as const, text: "1789" }, { id: 'b' as const, text: "1799" }, { id: 'c' as const, text: "1776" }, { id: 'd' as const, text: "1815" }] },

  { textFr: "Qui était Napoléon Ier ?", lang: 'es' as const, text: "¿Quién fue Napoleón I?", explanation: "Napoleón I fue emperador de los franceses de 1804 a 1814 y brevemente en 1815. Modernizó la administración francesa e instauró el Código Civil, aún vigente hoy en día.", choices: [{ id: 'a' as const, text: "El primer emperador de los franceses" }, { id: 'b' as const, text: "El último rey de Francia" }, { id: 'c' as const, text: "El fundador de la V República" }, { id: 'd' as const, text: "Un general de la Primera Guerra Mundial" }] },

  { textFr: "Lequel de ces personnages historiques est français ?", lang: 'es' as const, text: "¿Cuál de estos personajes históricos es francés?", explanation: "Juana de Arco es una figura emblemática de la historia de Francia. Lideró los ejércitos franceses contra los ingleses durante la Guerra de los Cien Años en el siglo XV.", choices: [{ id: 'a' as const, text: "Juana de Arco" }, { id: 'b' as const, text: "Cristóbal Colón" }, { id: 'c' as const, text: "Winston Churchill" }, { id: 'd' as const, text: "Leonardo da Vinci" }] },

  { textFr: "Dans quelle République est-on aujourd'hui ?", lang: 'es' as const, text: "¿En qué República estamos actualmente?", explanation: "Francia se encuentra actualmente bajo la V República, instaurada en 1958 por el general de Gaulle. Esta reforzó el poder del presidente de la República.", choices: [{ id: 'a' as const, text: "La V República" }, { id: 'b' as const, text: "La IV República" }, { id: 'c' as const, text: "La III República" }, { id: 'd' as const, text: "La VI República" }] },

  { textFr: "Qu'est-ce que la Shoah ?", lang: 'es' as const, text: "¿Qué es la Shoah?", explanation: "La Shoah designa el genocidio de los judíos de Europa por la Alemania nazi durante la Segunda Guerra Mundial. Aproximadamente seis millones de judíos fueron exterminados entre 1941 y 1945.", choices: [{ id: 'a' as const, text: "El genocidio de los judíos durante la Segunda Guerra Mundial" }, { id: 'b' as const, text: "Una batalla de la Primera Guerra Mundial" }, { id: 'c' as const, text: "Un tratado de paz europeo" }, { id: 'd' as const, text: "La resistencia francesa contra la ocupación" }] },

  { textFr: "Quel pays ou région du monde a été colonisé par la France ?", lang: 'es' as const, text: "¿Qué país o región del mundo fue colonizado por Francia?", explanation: "Argelia fue colonizada por Francia de 1830 a 1962. Fue la colonia francesa más importante del norte de África y su independencia se obtuvo tras una larga guerra.", choices: [{ id: 'a' as const, text: "Argelia" }, { id: 'b' as const, text: "Brasil" }, { id: 'c' as const, text: "India" }, { id: 'd' as const, text: "Australia" }] },

  { textFr: "Qui a rendu l'école gratuite, laïque et obligatoire ?", lang: 'es' as const, text: "¿Quién hizo la escuela gratuita, laica y obligatoria?", explanation: "Jules Ferry, ministro de Instrucción Pública, hizo aprobar las leyes de 1881-1882 que hicieron la escuela primaria gratuita, laica y obligatoria. Estas leyes son un pilar de la República francesa.", choices: [{ id: 'a' as const, text: "Jules Ferry" }, { id: 'b' as const, text: "Victor Hugo" }, { id: 'c' as const, text: "Napoleón Bonaparte" }, { id: 'd' as const, text: "Charles de Gaulle" }] },

  { textFr: "Quand a eu lieu la Seconde Guerre mondiale ?", lang: 'es' as const, text: "¿Cuándo tuvo lugar la Segunda Guerra Mundial?", explanation: "La Segunda Guerra Mundial se desarrolló de 1939 a 1945. Este conflicto mundial involucró a la mayoría de las naciones y causó millones de víctimas.", choices: [{ id: 'a' as const, text: "1939-1945" }, { id: 'b' as const, text: "1914-1918" }, { id: 'c' as const, text: "1870-1871" }, { id: 'd' as const, text: "1950-1953" }] },

  { textFr: "Quand a eu lieu la Première Guerre mondiale ?", lang: 'es' as const, text: "¿Cuándo tuvo lugar la Primera Guerra Mundial?", explanation: "La Primera Guerra Mundial tuvo lugar de 1914 a 1918. Este conflicto enfrentó principalmente a las potencias de la Triple Entente con los Imperios Centrales.", choices: [{ id: 'a' as const, text: "1914-1918" }, { id: 'b' as const, text: "1939-1945" }, { id: 'c' as const, text: "1870-1871" }, { id: 'd' as const, text: "1899-1902" }] },

  { textFr: "En quelle année a été créée la Communauté Économique Européenne (CEE) ?", lang: 'es' as const, text: "¿En qué año se creó la Comunidad Económica Europea (CEE)?", explanation: "La CEE fue creada en 1957 por el Tratado de Roma, firmado por seis países fundadores entre ellos Francia. Es la predecesora de la actual Unión Europea.", choices: [{ id: 'a' as const, text: "1957" }, { id: 'b' as const, text: "1945" }, { id: 'c' as const, text: "1962" }, { id: 'd' as const, text: "1951" }] },

  { textFr: "Le 11 novembre est un jour férié. À quoi correspond cette date ?", lang: 'es' as const, text: "El 11 de noviembre es un día festivo. ¿A qué corresponde esta fecha?", explanation: "El 11 de noviembre de 1918 marca el armisticio de la Primera Guerra Mundial. Este día festivo conmemora el fin de los combates y rinde homenaje a los soldados caídos por Francia.", choices: [{ id: 'a' as const, text: "El armisticio de la Primera Guerra Mundial" }, { id: 'b' as const, text: "El fin de la Segunda Guerra Mundial" }, { id: 'c' as const, text: "La fiesta nacional francesa" }, { id: 'd' as const, text: "La proclamación de la República" }] },

  { textFr: "Qui a été le premier Président élu sous la Ve République ?", lang: 'es' as const, text: "¿Quién fue el primer presidente electo bajo la V República?", explanation: "Charles de Gaulle fue el primer presidente de la V República, elegido en 1958. Es el fundador de este régimen y ejerció dos mandatos presidenciales.", choices: [{ id: 'a' as const, text: "Charles de Gaulle" }, { id: 'b' as const, text: "François Mitterrand" }, { id: 'c' as const, text: "Georges Pompidou" }, { id: 'd' as const, text: "René Coty" }] },

  { textFr: "En quelle année l'esclavage a-t-il été aboli définitivement en France ?", lang: 'es' as const, text: "¿En qué año fue abolida definitivamente la esclavitud en Francia?", explanation: "La esclavitud fue abolida definitivamente en Francia en 1848, por impulso de Victor Schœlcher. Un primer decreto de abolición se había dictado en 1794 pero Napoleón la restableció en 1802.", choices: [{ id: 'a' as const, text: "1848" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1865" }, { id: 'd' as const, text: "1794" }] },

  { textFr: "Depuis quelle année l'école publique est-elle gratuite ?", lang: 'es' as const, text: "¿Desde qué año es gratuita la escuela pública?", explanation: "La escuela pública es gratuita desde 1881, gracias a las leyes de Jules Ferry. Estas leyes también hicieron la enseñanza primaria obligatoria y laica.", choices: [{ id: 'a' as const, text: "1881" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1905" }, { id: 'd' as const, text: "1848" }] },

  { textFr: "Combien y a-t-il eu de républiques en France ?", lang: 'es' as const, text: "¿Cuántas repúblicas ha habido en Francia?", explanation: "Francia ha conocido cinco repúblicas. La I República fue proclamada en 1792 y la V República, instaurada en 1958, es el régimen actual.", choices: [{ id: 'a' as const, text: "Cinco" }, { id: 'b' as const, text: "Tres" }, { id: 'c' as const, text: "Cuatro" }, { id: 'd' as const, text: "Seis" }] },

  { textFr: "Qui était le roi de France au moment de la Révolution française ?", lang: 'es' as const, text: "¿Quién era el rey de Francia en el momento de la Revolución francesa?", explanation: "Luis XVI era rey de Francia durante la Revolución francesa de 1789. Fue derrocado y luego guillotinado en 1793.", choices: [{ id: 'a' as const, text: "Luis XVI" }, { id: 'b' as const, text: "Luis XIV" }, { id: 'c' as const, text: "Luis XV" }, { id: 'd' as const, text: "Enrique IV" }] },

  { textFr: "Qui a fondé la Ve République ?", lang: 'es' as const, text: "¿Quién fundó la V República?", explanation: "El general Charles de Gaulle fundó la V República en 1958. Fue su primer presidente e instauró una Constitución que reforzó el poder ejecutivo.", choices: [{ id: 'a' as const, text: "El general de Gaulle" }, { id: 'b' as const, text: "François Mitterrand" }, { id: 'c' as const, text: "Napoleón III" }, { id: 'd' as const, text: "Léon Blum" }] },

  { textFr: "Que célèbre-t-on le 14 juillet ?", lang: 'es' as const, text: "¿Qué se celebra el 14 de julio?", explanation: "El 14 de julio es la fiesta nacional francesa. Conmemora la toma de la Bastilla en 1789 y la Fiesta de la Federación de 1790, símbolos de la libertad y la unidad nacional.", choices: [{ id: 'a' as const, text: "La fiesta nacional, aniversario de la toma de la Bastilla" }, { id: 'b' as const, text: "El armisticio de 1918" }, { id: 'c' as const, text: "El fin de la Segunda Guerra Mundial" }, { id: 'd' as const, text: "La abolición de la esclavitud" }] },

  { textFr: "Quelle guerre a eu lieu entre 1914 et 1918 ?", lang: 'es' as const, text: "¿Qué guerra tuvo lugar entre 1914 y 1918?", explanation: "La Primera Guerra Mundial tuvo lugar de 1914 a 1918. Enfrentó a los Aliados con los Imperios Centrales y causó millones de muertos.", choices: [{ id: 'a' as const, text: "La Primera Guerra Mundial" }, { id: 'b' as const, text: "La Segunda Guerra Mundial" }, { id: 'c' as const, text: "La guerra franco-prusiana" }, { id: 'd' as const, text: "La guerra de Argelia" }] },

  { textFr: "Pourquoi l'année 1958 est importante pour la France ?", lang: 'es' as const, text: "¿Por qué el año 1958 es importante para Francia?", explanation: "El año 1958 marca la creación de la V República por el general de Gaulle. Se adoptó una nueva Constitución, estableciendo el régimen político actual de Francia.", choices: [{ id: 'a' as const, text: "Es el año de la creación de la V República" }, { id: 'b' as const, text: "Es el año del fin de la Segunda Guerra Mundial" }, { id: 'c' as const, text: "Es el año de la abolición de la esclavitud" }, { id: 'd' as const, text: "Es el año de la Revolución francesa" }] },

  { textFr: "Quel fleuve coule en France ?", lang: 'es' as const, text: "¿Qué río fluye en Francia?", explanation: "El Loira es el río más largo de Francia con aproximadamente 1.012 km. Atraviesa el centro de Francia desde el Macizo Central hasta el océano Atlántico.", choices: [{ id: 'a' as const, text: "El Loira" }, { id: 'b' as const, text: "El Danubio" }, { id: 'c' as const, text: "El Nilo" }, { id: 'd' as const, text: "El Amazonas" }] },

  { textFr: "Quelle ville est française ?", lang: 'es' as const, text: "¿Qué ciudad es francesa?", explanation: "Lyon es una gran ciudad francesa, capital de la región Auvernia-Ródano-Alpes. Es la tercera ciudad más grande de Francia después de París y Marsella.", choices: [{ id: 'a' as const, text: "Lyon" }, { id: 'b' as const, text: "Ginebra" }, { id: 'c' as const, text: "Bruselas" }, { id: 'd' as const, text: "Barcelona" }] },

  { textFr: "Quel océan borde la côte ouest française ?", lang: 'es' as const, text: "¿Qué océano bordea la costa oeste francesa?", explanation: "El océano Atlántico bordea la costa oeste de la Francia metropolitana. Desde Bretaña hasta el País Vasco, esta fachada marítima se extiende a lo largo de cientos de kilómetros.", choices: [{ id: 'a' as const, text: "El océano Atlántico" }, { id: 'b' as const, text: "El océano Pacífico" }, { id: 'c' as const, text: "El océano Índico" }, { id: 'd' as const, text: "El océano Ártico" }] },

  { textFr: "Qu'est-ce que Paris ?", lang: 'es' as const, text: "¿Qué es París?", explanation: "París es la capital de Francia y su centro político, económico y cultural. Es también la ciudad más poblada del país.", choices: [{ id: 'a' as const, text: "La capital de Francia" }, { id: 'b' as const, text: "Una región de Francia" }, { id: 'c' as const, text: "Un departamento de ultramar" }, { id: 'd' as const, text: "La capital de Europa" }] },

  { textFr: "Quelle est la capitale de la France ?", lang: 'es' as const, text: "¿Cuál es la capital de Francia?", explanation: "París es la capital de Francia desde hace siglos. Alberga las principales instituciones del Estado, entre ellas el Palacio del Elíseo y la Asamblea Nacional.", choices: [{ id: 'a' as const, text: "París" }, { id: 'b' as const, text: "Lyon" }, { id: 'c' as const, text: "Marsella" }, { id: 'd' as const, text: "Estrasburgo" }] },

  { textFr: "Sur quel continent se situe la France métropolitaine ?", lang: 'es' as const, text: "¿En qué continente se encuentra la Francia metropolitana?", explanation: "La Francia metropolitana se encuentra en el continente europeo. Está bordeada por el océano Atlántico al oeste, el mar Mediterráneo al sur y el canal de la Mancha al norte.", choices: [{ id: 'a' as const, text: "Europa" }, { id: 'b' as const, text: "África" }, { id: 'c' as const, text: "América" }, { id: 'd' as const, text: "Asia" }] },

  { textFr: "Quelle île est un département d'outre-mer français ?", lang: 'es' as const, text: "¿Qué isla es un departamento de ultramar francés?", explanation: "Martinica es un departamento y una región de ultramar francés situado en las Antillas. Forma parte integral de la República francesa.", choices: [{ id: 'a' as const, text: "Martinica" }, { id: 'b' as const, text: "Cuba" }, { id: 'c' as const, text: "Jamaica" }, { id: 'd' as const, text: "Haití" }] },

  { textFr: "Combien y a-t-il de régions en France métropolitaine ?", lang: 'es' as const, text: "¿Cuántas regiones hay en la Francia metropolitana?", explanation: "Desde la reforma territorial de 2016, la Francia metropolitana cuenta con 13 regiones. Este número se redujo de 22 a 13 para reforzar la eficacia de las colectividades territoriales.", choices: [{ id: 'a' as const, text: "13" }, { id: 'b' as const, text: "18" }, { id: 'c' as const, text: "22" }, { id: 'd' as const, text: "10" }] },

  { textFr: "Quelle ville est un grand port maritime ?", lang: 'es' as const, text: "¿Qué ciudad es un gran puerto marítimo?", explanation: "Marsella es el puerto marítimo más grande de Francia y uno de los más importantes del Mediterráneo. Es también la segunda ciudad más grande de Francia.", choices: [{ id: 'a' as const, text: "Marsella" }, { id: 'b' as const, text: "Clermont-Ferrand" }, { id: 'c' as const, text: "Grenoble" }, { id: 'd' as const, text: "Limoges" }] },

  { textFr: "Quelle est la mer au sud de la France métropolitaine ?", lang: 'es' as const, text: "¿Cuál es el mar al sur de la Francia metropolitana?", explanation: "El mar Mediterráneo bordea el sur de la Francia metropolitana. Se extiende desde la frontera española hasta la frontera italiana, recorriendo la Costa Azul y el Languedoc.", choices: [{ id: 'a' as const, text: "El mar Mediterráneo" }, { id: 'b' as const, text: "El mar del Norte" }, { id: 'c' as const, text: "El mar Báltico" }, { id: 'd' as const, text: "El canal de la Mancha" }] },

  { textFr: "Quelle ville est située au bord de la mer Méditerranée ?", lang: 'es' as const, text: "¿Qué ciudad está situada a orillas del mar Mediterráneo?", explanation: "Niza es una ciudad situada en la Costa Azul, a orillas del mar Mediterráneo. Es uno de los principales destinos turísticos del sur de Francia.", choices: [{ id: 'a' as const, text: "Niza" }, { id: 'b' as const, text: "Lille" }, { id: 'c' as const, text: "Estrasburgo" }, { id: 'd' as const, text: "Rennes" }] },

  { textFr: "Où se situe la Corse ?", lang: 'es' as const, text: "¿Dónde se encuentra Córcega?", explanation: "Córcega es una isla situada en el mar Mediterráneo, al sureste de la Francia metropolitana. Es una colectividad territorial única que posee un estatus particular.", choices: [{ id: 'a' as const, text: "En el mar Mediterráneo" }, { id: 'b' as const, text: "En el océano Atlántico" }, { id: 'c' as const, text: "En el canal de la Mancha" }, { id: 'd' as const, text: "En el mar del Norte" }] },

  { textFr: "Quelle chaîne de montagnes est située entre la France et l'Italie ?", lang: 'es' as const, text: "¿Qué cadena montañosa se encuentra entre Francia e Italia?", explanation: "Los Alpes forman una frontera natural entre Francia e Italia. El Mont Blanc, situado en los Alpes, es la cumbre más alta de Europa occidental con 4.809 metros.", choices: [{ id: 'a' as const, text: "Los Alpes" }, { id: 'b' as const, text: "Los Pirineos" }, { id: 'c' as const, text: "El Jura" }, { id: 'd' as const, text: "Los Vosgos" }] },

  { textFr: "Qui était Molière ?", lang: 'es' as const, text: "¿Quién fue Molière?", explanation: "Molière (1622-1673) fue un dramaturgo y comediante francés del siglo XVII. Es autor de célebres comedias como El enfermo imaginario y El misántropo.", choices: [{ id: 'a' as const, text: "Un dramaturgo y comediante francés del siglo XVII" }, { id: 'b' as const, text: "Un pintor del Renacimiento" }, { id: 'c' as const, text: "Un compositor de música clásica" }, { id: 'd' as const, text: "Un filósofo de la Ilustración" }] },

  { textFr: "Qui était Charles Baudelaire ?", lang: 'es' as const, text: "¿Quién fue Charles Baudelaire?", explanation: "Charles Baudelaire (1821-1867) fue un poeta francés, autor de la célebre colección Las flores del mal. Es considerado uno de los precursores de la poesía moderna.", choices: [{ id: 'a' as const, text: "Un poeta francés, autor de Las flores del mal" }, { id: 'b' as const, text: "Un novelista autor de Los miserables" }, { id: 'c' as const, text: "Un escultor del siglo XIX" }, { id: 'd' as const, text: "Un músico romántico" }] },

  { textFr: "Qui était George Sand ?", lang: 'es' as const, text: "¿Quién fue George Sand?", explanation: "George Sand (1804-1876) fue una novelista francesa, cuyo verdadero nombre era Amantine Lucile Aurore Dupin. Es conocida por sus novelas campestres y su compromiso con los derechos de las mujeres.", choices: [{ id: 'a' as const, text: "Una novelista francesa del siglo XIX" }, { id: 'b' as const, text: "Una reina de Francia" }, { id: 'c' as const, text: "Una científica Premio Nobel" }, { id: 'd' as const, text: "Una cantante de ópera" }] },

  { textFr: "Qui était Simone de Beauvoir ?", lang: 'es' as const, text: "¿Quién fue Simone de Beauvoir?", explanation: "Simone de Beauvoir (1908-1986) fue una filósofa y escritora francesa, figura destacada del feminismo. Es autora de El segundo sexo, obra fundadora del feminismo moderno.", choices: [{ id: 'a' as const, text: "Una filósofa y escritora feminista francesa" }, { id: 'b' as const, text: "Una resistente de la Segunda Guerra Mundial" }, { id: 'c' as const, text: "Una física francesa" }, { id: 'd' as const, text: "Una actriz de cine francesa" }] },

  { textFr: "Qui était Albert Camus ?", lang: 'es' as const, text: "¿Quién fue Albert Camus?", explanation: "Albert Camus (1913-1960) fue un escritor y filósofo francés, premio Nobel de literatura en 1957. Es autor de El extranjero y La peste.", choices: [{ id: 'a' as const, text: "Un escritor y filósofo francés, premio Nobel de literatura" }, { id: 'b' as const, text: "Un pintor impresionista" }, { id: 'c' as const, text: "Un político de la III República" }, { id: 'd' as const, text: "Un compositor de música clásica" }] },

  { textFr: "Qui était Paul Cézanne ?", lang: 'es' as const, text: "¿Quién fue Paul Cézanne?", explanation: "Paul Cézanne (1839-1906) fue un pintor francés, considerado el padre del arte moderno. Sus obras influyeron en el cubismo y numerosos movimientos artísticos del siglo XX.", choices: [{ id: 'a' as const, text: "Un pintor francés, precursor del arte moderno" }, { id: 'b' as const, text: "Un escritor naturalista" }, { id: 'c' as const, text: "Un escultor del siglo XVIII" }, { id: 'd' as const, text: "Un arquitecto del Renacimiento" }] },

  { textFr: "Qui était Marc Chagall ?", lang: 'es' as const, text: "¿Quién fue Marc Chagall?", explanation: "Marc Chagall (1887-1985) fue un pintor y grabador de origen ruso nacionalizado francés. Es célebre por sus obras coloridas que mezclan fantasía y simbolismo, especialmente los vitrales de la Ópera de París.", choices: [{ id: 'a' as const, text: "Un pintor de origen ruso nacionalizado francés" }, { id: 'b' as const, text: "Un filósofo francés de la Ilustración" }, { id: 'c' as const, text: "Un músico clásico austriaco" }, { id: 'd' as const, text: "Un director de cine italiano" }] },

  { textFr: "Qui était Joséphine Baker ?", lang: 'es' as const, text: "¿Quién fue Joséphine Baker?", explanation: "Joséphine Baker (1906-1975) fue una artista franco-estadounidense, cantante y bailarina, resistente durante la Segunda Guerra Mundial. Fue recibida en el Panteón en 2021 por su compromiso.", choices: [{ id: 'a' as const, text: "Una artista franco-estadounidense, cantante, bailarina y resistente" }, { id: 'b' as const, text: "Una científica franco-polaca" }, { id: 'c' as const, text: "Una política francesa" }, { id: 'd' as const, text: "Una novelista del siglo XIX" }] },

  { textFr: "Qui était une chanteuse française célèbre ?", lang: 'es' as const, text: "¿Quién fue una cantante francesa célebre?", explanation: "Édith Piaf (1915-1963) es una de las cantantes francesas más célebres del mundo. Es conocida por canciones como La vie en rose y Non, je ne regrette rien.", choices: [{ id: 'a' as const, text: "Édith Piaf" }, { id: 'b' as const, text: "Madonna" }, { id: 'c' as const, text: "Beyoncé" }, { id: 'd' as const, text: "Adele" }] },

  { textFr: "Qu'est-ce que le Louvre ?", lang: 'es' as const, text: "¿Qué es el Louvre?", explanation: "El Louvre es el museo de arte más grande del mundo, situado en París. Antiguo palacio real, alberga obras célebres como La Gioconda de Leonardo da Vinci.", choices: [{ id: 'a' as const, text: "El museo de arte más grande del mundo, situado en París" }, { id: 'b' as const, text: "Un castillo del Loira" }, { id: 'c' as const, text: "Una catedral gótica" }, { id: 'd' as const, text: "Un teatro nacional" }] },

  { textFr: "Qui était Jean de la Fontaine ?", lang: 'es' as const, text: "¿Quién fue Jean de la Fontaine?", explanation: "Jean de la Fontaine (1621-1695) fue un poeta francés célebre por sus Fábulas. Sus obras, como El cuervo y el zorro, todavía se enseñan en las escuelas francesas.", choices: [{ id: 'a' as const, text: "Un poeta francés célebre por sus Fábulas" }, { id: 'b' as const, text: "Un rey de Francia" }, { id: 'c' as const, text: "Un pintor del Renacimiento" }, { id: 'd' as const, text: "Un explorador del Nuevo Mundo" }] },

  { textFr: "Quel écrivain est français ?", lang: 'es' as const, text: "¿Qué escritor es francés?", explanation: "Victor Hugo (1802-1885) es uno de los más grandes escritores franceses. Es autor de obras maestras como Los miserables y Nuestra Señora de París.", choices: [{ id: 'a' as const, text: "Victor Hugo" }, { id: 'b' as const, text: "Charles Dickens" }, { id: 'c' as const, text: "Miguel de Cervantes" }, { id: 'd' as const, text: "William Shakespeare" }] },

  { textFr: "Dans quelle ville se trouve la tour Eiffel ?", lang: 'es' as const, text: "¿En qué ciudad se encuentra la Torre Eiffel?", explanation: "La Torre Eiffel se encuentra en París. Construida por Gustave Eiffel para la Exposición Universal de 1889, se ha convertido en el símbolo más emblemático de Francia.", choices: [{ id: 'a' as const, text: "París" }, { id: 'b' as const, text: "Lyon" }, { id: 'c' as const, text: "Marsella" }, { id: 'd' as const, text: "Burdeos" }] },

  { textFr: "Quand célèbre-t-on Noël ?", lang: 'es' as const, text: "¿Cuándo se celebra la Navidad?", explanation: "La Navidad se celebra el 25 de diciembre. Es un día festivo en Francia, fiesta cristiana que se ha convertido también en una tradición cultural marcada por las comidas en familia y el intercambio de regalos.", choices: [{ id: 'a' as const, text: "El 25 de diciembre" }, { id: 'b' as const, text: "El 1 de enero" }, { id: 'c' as const, text: "El 14 de julio" }, { id: 'd' as const, text: "El 1 de noviembre" }] },

  // ─── Q48–Q96: CR-only questions (difficulty 2) ─────────────────────────────

  { textFr: "Quel était le surnom de Louis XIV ?", lang: 'es' as const, text: "¿Cuál era el apodo de Luis XIV?", explanation: "Luis XIV era apodado el Rey Sol. Reinó de 1643 a 1715, es decir 72 años, el reinado más largo de la historia de Francia, e hizo construir el Palacio de Versalles.", choices: [{ id: 'a' as const, text: "El Rey Sol" }, { id: 'b' as const, text: "El Rey de reyes" }, { id: 'c' as const, text: "El Bienamado" }, { id: 'd' as const, text: "El Grande" }] },

  { textFr: "Quel roi de France a été exécuté pendant la Révolution française ?", lang: 'es' as const, text: "¿Qué rey de Francia fue ejecutado durante la Revolución francesa?", explanation: "Luis XVI fue guillotinado el 21 de enero de 1793 en la plaza de la Revolución de París. Había sido juzgado y condenado a muerte por la Convención Nacional por traición.", choices: [{ id: 'a' as const, text: "Luis XVI" }, { id: 'b' as const, text: "Luis XIV" }, { id: 'c' as const, text: "Luis XV" }, { id: 'd' as const, text: "Carlos X" }] },

  { textFr: "En quelle année Napoléon Ier est-il devenu empereur ?", lang: 'es' as const, text: "¿En qué año Napoleón I se convirtió en emperador?", explanation: "Napoleón I se convirtió en emperador de los franceses en 1804. Su coronación tuvo lugar el 2 de diciembre de 1804 en la catedral de Notre-Dame de París.", choices: [{ id: 'a' as const, text: "1804" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1799" }, { id: 'd' as const, text: "1815" }] },

  { textFr: "Lequel de ces personnages a un lien avec la République française ?", lang: 'es' as const, text: "¿Cuál de estos personajes tiene un vínculo con la República francesa?", explanation: "Marianne es el símbolo alegórico de la República francesa. Representa los valores de libertad, igualdad y fraternidad, y su busto está presente en todos los ayuntamientos.", choices: [{ id: 'a' as const, text: "Marianne" }, { id: 'b' as const, text: "Britannia" }, { id: 'c' as const, text: "Uncle Sam" }, { id: 'd' as const, text: "John Bull" }] },

  { textFr: "De quand date l'appel à la résistance du général de Gaulle ?", lang: 'es' as const, text: "¿De cuándo data el llamado a la resistencia del general de Gaulle?", explanation: "El llamado del general de Gaulle data del 18 de junio de 1940. Desde Londres, llamó a los franceses a resistir contra la ocupación alemana a través de la BBC.", choices: [{ id: 'a' as const, text: "El 18 de junio de 1940" }, { id: 'b' as const, text: "El 8 de mayo de 1945" }, { id: 'c' as const, text: "El 14 de julio de 1940" }, { id: 'd' as const, text: "El 25 de agosto de 1944" }] },

  { textFr: "Pourquoi la Shoah est-elle étudiée à l'école ?", lang: 'es' as const, text: "¿Por qué se estudia la Shoah en la escuela?", explanation: "La Shoah se estudia en la escuela para transmitir la memoria de este genocidio y sensibilizar a los alumnos sobre el deber de memoria. Esto permite luchar contra el racismo, el antisemitismo y toda forma de discriminación.", choices: [{ id: 'a' as const, text: "Por el deber de memoria y para luchar contra el racismo y el antisemitismo" }, { id: 'b' as const, text: "Para preparar a los alumnos para los exámenes de historia" }, { id: 'c' as const, text: "Para enseñar la geografía de Europa" }, { id: 'd' as const, text: "Para estudiar la economía de guerra" }] },

  { textFr: "Quel pays a été colonisé par la France ?", lang: 'es' as const, text: "¿Qué país fue colonizado por Francia?", explanation: "Senegal fue una colonia francesa de África occidental. Obtuvo su independencia en 1960, como muchos países africanos francófonos.", choices: [{ id: 'a' as const, text: "Senegal" }, { id: 'b' as const, text: "Nigeria" }, { id: 'c' as const, text: "Sudáfrica" }, { id: 'd' as const, text: "Etiopía" }] },

  { textFr: "Depuis quand les Français élisent-ils le président de la République au suffrage universel direct ?", lang: 'es' as const, text: "¿Desde cuándo los franceses eligen al presidente de la República por sufragio universal directo?", explanation: "Desde 1962, los franceses eligen al presidente de la República por sufragio universal directo, tras el referéndum impulsado por el general de Gaulle. Antes de esa fecha, el presidente era elegido por un colegio electoral.", choices: [{ id: 'a' as const, text: "1962" }, { id: 'b' as const, text: "1958" }, { id: 'c' as const, text: "1945" }, { id: 'd' as const, text: "1981" }] },

  { textFr: "Quelle est la première étape de la construction européenne en 1951 ?", lang: 'es' as const, text: "¿Cuál es la primera etapa de la construcción europea en 1951?", explanation: "La Comunidad Europea del Carbón y del Acero (CECA), creada en 1951, es la primera etapa de la construcción europea. Fue fundada por seis países para poner en común sus producciones de carbón y acero.", choices: [{ id: 'a' as const, text: "La creación de la Comunidad Europea del Carbón y del Acero (CECA)" }, { id: 'b' as const, text: "La creación de la Unión Europea" }, { id: 'c' as const, text: "La firma del Tratado de Maastricht" }, { id: 'd' as const, text: "La adopción del euro" }] },

  { textFr: "Durant le mandat de quel président la peine de mort a-t-elle été abolie ?", lang: 'es' as const, text: "¿Durante el mandato de qué presidente fue abolida la pena de muerte?", explanation: "La pena de muerte fue abolida en 1981 bajo la presidencia de François Mitterrand, gracias a la acción del ministro de Justicia Robert Badinter. Francia fue uno de los últimos países de Europa occidental en abolirla.", choices: [{ id: 'a' as const, text: "François Mitterrand" }, { id: 'b' as const, text: "Valéry Giscard d'Estaing" }, { id: 'c' as const, text: "Jacques Chirac" }, { id: 'd' as const, text: "Charles de Gaulle" }] },

  { textFr: "Quel régime politique a été mis en place pendant la Révolution française en 1792 ?", lang: 'es' as const, text: "¿Qué régimen político se estableció durante la Revolución francesa en 1792?", explanation: "La I República fue proclamada el 21 de septiembre de 1792, tras la abolición de la monarquía. Es el primer régimen republicano de la historia de Francia.", choices: [{ id: 'a' as const, text: "La República (I República)" }, { id: 'b' as const, text: "El Imperio" }, { id: 'c' as const, text: "La monarquía constitucional" }, { id: 'd' as const, text: "La dictadura militar" }] },

  { textFr: "Qui était une figure de la Résistance française pendant la Seconde Guerre mondiale ?", lang: 'es' as const, text: "¿Quién fue una figura de la Resistencia francesa durante la Segunda Guerra Mundial?", explanation: "Jean Moulin (1899-1943) fue un alto funcionario y resistente francés. Unificó los movimientos de resistencia bajo la autoridad del general de Gaulle antes de ser arrestado y asesinado por la Gestapo.", choices: [{ id: 'a' as const, text: "Jean Moulin" }, { id: 'b' as const, text: "Philippe Pétain" }, { id: 'c' as const, text: "Pierre Laval" }, { id: 'd' as const, text: "Adolphe Thiers" }] },

  { textFr: "En 1944, qu'est-ce qui a changé pour les femmes ?", lang: 'es' as const, text: "En 1944, ¿qué cambió para las mujeres?", explanation: "En 1944, las mujeres obtuvieron el derecho al voto en Francia. Votaron por primera vez en las elecciones municipales del 29 de abril de 1945.", choices: [{ id: 'a' as const, text: "Obtuvieron el derecho al voto" }, { id: 'b' as const, text: "Obtuvieron el derecho a trabajar" }, { id: 'c' as const, text: "Obtuvieron el derecho al divorcio" }, { id: 'd' as const, text: "Obtuvieron el derecho a abrir una cuenta bancaria" }] },

  { textFr: "Quelle organisation internationale a été créée en 1945 après la Seconde Guerre mondiale ?", lang: 'es' as const, text: "¿Qué organización internacional fue creada en 1945 después de la Segunda Guerra Mundial?", explanation: "La Organización de las Naciones Unidas (ONU) fue creada en 1945 para mantener la paz y la seguridad internacionales. Francia es uno de los cinco miembros permanentes del Consejo de Seguridad.", choices: [{ id: 'a' as const, text: "La Organización de las Naciones Unidas (ONU)" }, { id: 'b' as const, text: "La Unión Europea" }, { id: 'c' as const, text: "La OTAN" }, { id: 'd' as const, text: "La Cruz Roja" }] },

  { textFr: "Quelle peine a été supprimée en 1981 ?", lang: 'es' as const, text: "¿Qué pena fue suprimida en 1981?", explanation: "La pena de muerte fue abolida en Francia el 9 de octubre de 1981 por la ley promovida por Robert Badinter. Francia se une así a los países europeos que han suprimido la pena capital.", choices: [{ id: 'a' as const, text: "La pena de muerte" }, { id: 'b' as const, text: "La pena de prisión perpetua" }, { id: 'c' as const, text: "Los trabajos forzados" }, { id: 'd' as const, text: "El destierro" }] },

  { textFr: "En quelle année l'euro est-il devenu la monnaie utilisée en France ?", lang: 'es' as const, text: "¿En qué año el euro se convirtió en la moneda utilizada en Francia?", explanation: "El euro se convirtió en la moneda utilizada en Francia el 1 de enero de 2002, reemplazando al franco francés. El euro es hoy la moneda común de 20 países de la zona euro.", choices: [{ id: 'a' as const, text: "2002" }, { id: 'b' as const, text: "1999" }, { id: 'c' as const, text: "1992" }, { id: 'd' as const, text: "2005" }] },

  { textFr: "En quelle année a commencé la Première Guerre mondiale ?", lang: 'es' as const, text: "¿En qué año comenzó la Primera Guerra Mundial?", explanation: "La Primera Guerra Mundial comenzó en 1914, desencadenada por el asesinato del archiduque Francisco Fernando de Austria. Francia se involucró en el conflicto desde el principio.", choices: [{ id: 'a' as const, text: "1914" }, { id: 'b' as const, text: "1916" }, { id: 'c' as const, text: "1912" }, { id: 'd' as const, text: "1939" }] },

  { textFr: "Où a eu lieu le débarquement en 1944 ?", lang: 'es' as const, text: "¿Dónde tuvo lugar el desembarco en 1944?", explanation: "El desembarco del 6 de junio de 1944 (Día D) tuvo lugar en las playas de Normandía. Esta operación militar aliada marcó el inicio de la liberación de Francia de la ocupación nazi.", choices: [{ id: 'a' as const, text: "En Normandía" }, { id: 'b' as const, text: "En Bretaña" }, { id: 'c' as const, text: "En Provenza" }, { id: 'd' as const, text: "En Picardía" }] },

  { textFr: "Quel continent a été le plus concerné par la décolonisation française après la Seconde Guerre mondiale ?", lang: 'es' as const, text: "¿Qué continente fue el más afectado por la descolonización francesa después de la Segunda Guerra Mundial?", explanation: "África fue el continente más afectado por la descolonización francesa. La mayoría de las colonias francesas de África obtuvieron su independencia en los años 1960.", choices: [{ id: 'a' as const, text: "África" }, { id: 'b' as const, text: "Asia" }, { id: 'c' as const, text: "América del Sur" }, { id: 'd' as const, text: "Oceanía" }] },

  { textFr: "Que fête-t-on le 8 mai ?", lang: 'es' as const, text: "¿Qué se celebra el 8 de mayo?", explanation: "El 8 de mayo conmemora el fin de la Segunda Guerra Mundial en Europa (victoria de los Aliados sobre la Alemania nazi en 1945). Es un día festivo en Francia.", choices: [{ id: 'a' as const, text: "El fin de la Segunda Guerra Mundial en Europa" }, { id: 'b' as const, text: "La fiesta del Trabajo" }, { id: 'c' as const, text: "El armisticio de la Primera Guerra Mundial" }, { id: 'd' as const, text: "La fiesta nacional" }] },

  { textFr: "Quelle mer ou océan borde la France métropolitaine ?", lang: 'es' as const, text: "¿Qué mar u océano bordea la Francia metropolitana?", explanation: "El mar Mediterráneo bordea el sur de la Francia metropolitana. Francia también está bordeada por el océano Atlántico al oeste y el canal de la Mancha al norte.", choices: [{ id: 'a' as const, text: "El mar Mediterráneo" }, { id: 'b' as const, text: "El mar Caspio" }, { id: 'c' as const, text: "El mar Negro" }, { id: 'd' as const, text: "El mar Rojo" }] },

  { textFr: "Quel pays a une frontière terrestre avec la France métropolitaine ?", lang: 'es' as const, text: "¿Qué país tiene una frontera terrestre con la Francia metropolitana?", explanation: "España comparte una frontera terrestre con Francia al sur, a lo largo de los Pirineos. La Francia metropolitana también tiene fronteras con Bélgica, Luxemburgo, Alemania, Suiza, Italia y Mónaco.", choices: [{ id: 'a' as const, text: "España" }, { id: 'b' as const, text: "Portugal" }, { id: 'c' as const, text: "Inglaterra" }, { id: 'd' as const, text: "Polonia" }] },

  { textFr: "Quelle ville française est un port maritime ?", lang: 'es' as const, text: "¿Qué ciudad francesa es un puerto marítimo?", explanation: "El Havre es un gran puerto marítimo francés situado en Normandía, en la desembocadura del Sena. Es uno de los puertos comerciales más importantes de Francia.", choices: [{ id: 'a' as const, text: "El Havre" }, { id: 'b' as const, text: "Toulouse" }, { id: 'c' as const, text: "Clermont-Ferrand" }, { id: 'd' as const, text: "Estrasburgo" }] },

  { textFr: "Quelle mer se situe entre la France et l'Angleterre ?", lang: 'es' as const, text: "¿Qué mar se encuentra entre Francia e Inglaterra?", explanation: "El canal de la Mancha separa Francia de Inglaterra. Conecta el océano Atlántico con el mar del Norte y es atravesado por el túnel del Canal de la Mancha desde 1994.", choices: [{ id: 'a' as const, text: "El canal de la Mancha" }, { id: 'b' as const, text: "El mar del Norte" }, { id: 'c' as const, text: "El mar Mediterráneo" }, { id: 'd' as const, text: "El mar Báltico" }] },

  { textFr: "Qu'est-ce que la France d'outre-mer ?", lang: 'es' as const, text: "¿Qué es la Francia de ultramar?", explanation: "La Francia de ultramar designa el conjunto de territorios franceses situados fuera de Europa. Comprende departamentos (Guadalupe, Martinica, Guayana, La Reunión, Mayotte) y colectividades de ultramar.", choices: [{ id: 'a' as const, text: "El conjunto de territorios franceses situados fuera de Europa" }, { id: 'b' as const, text: "Las regiones del sur de Francia" }, { id: 'c' as const, text: "Las antiguas colonias francesas independientes" }, { id: 'd' as const, text: "Los países francófonos de África" }] },

  { textFr: "Quelle chaîne de montagnes est située entre la France et l'Espagne ?", lang: 'es' as const, text: "¿Qué cadena montañosa se encuentra entre Francia y España?", explanation: "Los Pirineos forman una frontera natural entre Francia y España a lo largo de unos 430 km. Su punto culminante es el pico Aneto (3.404 m) del lado español.", choices: [{ id: 'a' as const, text: "Los Pirineos" }, { id: 'b' as const, text: "Los Alpes" }, { id: 'c' as const, text: "El Jura" }, { id: 'd' as const, text: "Los Vosgos" }] },

  { textFr: "Quelle île française se trouve dans l'océan Indien ?", lang: 'es' as const, text: "¿Qué isla francesa se encuentra en el océano Índico?", explanation: "La Reunión es un departamento francés de ultramar situado en el océano Índico, al este de Madagascar. Es una isla volcánica de aproximadamente 900.000 habitantes.", choices: [{ id: 'a' as const, text: "La Reunión" }, { id: 'b' as const, text: "Martinica" }, { id: 'c' as const, text: "Guadalupe" }, { id: 'd' as const, text: "Córcega" }] },

  { textFr: "Quelle est la population approximative de la France en 2025 ?", lang: 'es' as const, text: "¿Cuál es la población aproximada de Francia en 2025?", explanation: "Francia cuenta con aproximadamente 68 millones de habitantes en 2025, incluyendo los territorios de ultramar. Es el segundo país más poblado de la Unión Europea después de Alemania.", choices: [{ id: 'a' as const, text: "68 millones de habitantes" }, { id: 'b' as const, text: "50 millones de habitantes" }, { id: 'c' as const, text: "80 millones de habitantes" }, { id: 'd' as const, text: "45 millones de habitantes" }] },

  { textFr: "Quel fleuve traverse Paris ?", lang: 'es' as const, text: "¿Qué río atraviesa París?", explanation: "El Sena atraviesa París de este a oeste. Este río de 776 km nace en Borgoña y desemboca en el canal de la Mancha en El Havre.", choices: [{ id: 'a' as const, text: "El Sena" }, { id: 'b' as const, text: "El Loira" }, { id: 'c' as const, text: "El Ródano" }, { id: 'd' as const, text: "El Garona" }] },

  { textFr: "Lequel de ces pays partage des frontières terrestres avec la France ?", lang: 'es' as const, text: "¿Cuál de estos países comparte fronteras terrestres con Francia?", explanation: "Bélgica comparte una frontera terrestre con Francia al norte. Los dos países son vecinos y socios dentro de la Unión Europea.", choices: [{ id: 'a' as const, text: "Bélgica" }, { id: 'b' as const, text: "Países Bajos" }, { id: 'c' as const, text: "Reino Unido" }, { id: 'd' as const, text: "Dinamarca" }] },

  { textFr: "Quel pays a une frontière avec la France métropolitaine au nord-est ?", lang: 'es' as const, text: "¿Qué país tiene una frontera con la Francia metropolitana al noreste?", explanation: "Alemania comparte una frontera con Francia al noreste, a lo largo del Rin. Esta frontera fue escenario de numerosos conflictos antes de convertirse en un símbolo de la reconciliación franco-alemana.", choices: [{ id: 'a' as const, text: "Alemania" }, { id: 'b' as const, text: "Polonia" }, { id: 'c' as const, text: "Austria" }, { id: 'd' as const, text: "República Checa" }] },

  { textFr: "Où se trouvent les principales activités économiques en France ?", lang: 'es' as const, text: "¿Dónde se encuentran las principales actividades económicas en Francia?", explanation: "Las principales actividades económicas en Francia se concentran en las grandes metrópolis, en particular la región parisina (Isla de Francia). Lyon, Marsella y otras grandes ciudades son también polos económicos importantes.", choices: [{ id: 'a' as const, text: "En las grandes metrópolis y la región parisina" }, { id: 'b' as const, text: "Únicamente en el sur de Francia" }, { id: 'c' as const, text: "Principalmente en las zonas rurales" }, { id: 'd' as const, text: "Exclusivamente en las costas" }] },

  { textFr: "Parmi ces pays, lequel attire le plus de visiteurs chaque année ?", lang: 'es' as const, text: "Entre estos países, ¿cuál atrae más visitantes cada año?", explanation: "Francia es el primer destino turístico mundial con aproximadamente 90 millones de visitantes extranjeros al año. Su patrimonio cultural, su gastronomía y sus paisajes variados atraen turistas de todo el mundo.", choices: [{ id: 'a' as const, text: "Francia" }, { id: 'b' as const, text: "Italia" }, { id: 'c' as const, text: "Estados Unidos" }, { id: 'd' as const, text: "España" }] },

  { textFr: "Où habite la majorité des Français ?", lang: 'es' as const, text: "¿Dónde vive la mayoría de los franceses?", explanation: "La mayoría de los franceses vive en la ciudad (aproximadamente el 80% de la población es urbana). Las grandes aglomeraciones como París, Lyon y Marsella concentran una parte importante de la población.", choices: [{ id: 'a' as const, text: "En la ciudad" }, { id: 'b' as const, text: "En el campo" }, { id: 'c' as const, text: "En la montaña" }, { id: 'd' as const, text: "En el litoral" }] },

  { textFr: "Quelle région est la plus peuplée ?", lang: 'es' as const, text: "¿Qué región es la más poblada?", explanation: "La Isla de Francia es la región más poblada de Francia con aproximadamente 12 millones de habitantes. Comprende París y su periferia, concentrando un quinto de la población francesa.", choices: [{ id: 'a' as const, text: "La Isla de Francia" }, { id: 'b' as const, text: "Provenza-Alpes-Costa Azul" }, { id: 'c' as const, text: "Occitania" }, { id: 'd' as const, text: "Nueva Aquitania" }] },

  { textFr: "Quelle ville française fait partie des 10 plus grandes métropoles du pays ?", lang: 'es' as const, text: "¿Qué ciudad francesa forma parte de las 10 mayores metrópolis del país?", explanation: "Toulouse forma parte de las 10 mayores metrópolis de Francia. Es la cuarta ciudad de Francia por su población y un polo importante de la industria aeronáutica.", choices: [{ id: 'a' as const, text: "Toulouse" }, { id: 'b' as const, text: "Basilea" }, { id: 'c' as const, text: "Lausana" }, { id: 'd' as const, text: "Charleroi" }] },

  { textFr: "Lequel de ces départements de France est le plus touristique ?", lang: 'es' as const, text: "¿Cuál de estos departamentos de Francia es el más turístico?", explanation: "París (departamento 75) es el departamento más turístico de Francia. La capital atrae millones de visitantes cada año gracias a sus monumentos, museos y vida cultural.", choices: [{ id: 'a' as const, text: "París" }, { id: 'b' as const, text: "La Creuse" }, { id: 'c' as const, text: "El Cantal" }, { id: 'd' as const, text: "La Lozère" }] },

  { textFr: "Quand peut-on visiter gratuitement des lieux culturels en France ?", lang: 'es' as const, text: "¿Cuándo se pueden visitar gratuitamente lugares culturales en Francia?", explanation: "Las Jornadas Europeas del Patrimonio, organizadas cada año en septiembre, permiten visitar gratuitamente numerosos lugares culturales y monumentos históricos en Francia.", choices: [{ id: 'a' as const, text: "Durante las Jornadas Europeas del Patrimonio" }, { id: 'b' as const, text: "Solo el 14 de julio" }, { id: 'c' as const, text: "Todos los domingos del año" }, { id: 'd' as const, text: "Durante las vacaciones escolares" }] },

  { textFr: "Combien de personnes parlent français dans le monde ?", lang: 'es' as const, text: "¿Cuántas personas hablan francés en el mundo?", explanation: "Aproximadamente 300 millones de personas hablan francés en el mundo. El francés es la quinta lengua más hablada y es lengua oficial en 29 países.", choices: [{ id: 'a' as const, text: "Aproximadamente 300 millones" }, { id: 'b' as const, text: "Aproximadamente 100 millones" }, { id: 'c' as const, text: "Aproximadamente 500 millones" }, { id: 'd' as const, text: "Aproximadamente 50 millones" }] },

  { textFr: "Qui était Marguerite Yourcenar ?", lang: 'es' as const, text: "¿Quién fue Marguerite Yourcenar?", explanation: "Marguerite Yourcenar (1903-1987) fue una escritora francesa, primera mujer elegida en la Academia Francesa en 1980. Es conocida por sus novelas históricas como Memorias de Adriano.", choices: [{ id: 'a' as const, text: "La primera mujer elegida en la Academia Francesa" }, { id: 'b' as const, text: "Una científica Premio Nobel de física" }, { id: 'c' as const, text: "Una exploradora del siglo XIX" }, { id: 'd' as const, text: "Una compositora de música barroca" }] },

  { textFr: "Quel peintre est français ?", lang: 'es' as const, text: "¿Qué pintor es francés?", explanation: "Claude Monet (1840-1926) fue un pintor francés, fundador del movimiento impresionista. Es célebre por sus series de pinturas de los Nenúfares y de la catedral de Ruán.", choices: [{ id: 'a' as const, text: "Claude Monet" }, { id: 'b' as const, text: "Pablo Picasso" }, { id: 'c' as const, text: "Vincent van Gogh" }, { id: 'd' as const, text: "Salvador Dalí" }] },

  { textFr: "Quel musée est situé à Paris ?", lang: 'es' as const, text: "¿Qué museo está situado en París?", explanation: "El Museo de Orsay está situado en París, en una antigua estación de ferrocarril. Alberga la mayor colección de arte impresionista y postimpresionista del mundo.", choices: [{ id: 'a' as const, text: "El Museo de Orsay" }, { id: 'b' as const, text: "El Museo Británico" }, { id: 'c' as const, text: "El Museo del Prado" }, { id: 'd' as const, text: "El Museo Metropolitano" }] },

  { textFr: "Qui était Auguste Rodin ?", lang: 'es' as const, text: "¿Quién fue Auguste Rodin?", explanation: "Auguste Rodin (1840-1917) fue un escultor francés, considerado el padre de la escultura moderna. Es autor de El pensador y Los burgueses de Calais.", choices: [{ id: 'a' as const, text: "Un escultor francés, autor de El pensador" }, { id: 'b' as const, text: "Un pintor impresionista" }, { id: 'c' as const, text: "Un arquitecto de la Torre Eiffel" }, { id: 'd' as const, text: "Un escritor romántico" }] },

  { textFr: "Quel est le classement de la langue française parmi les langues les plus parlées dans le monde ?", lang: 'es' as const, text: "¿Cuál es la clasificación de la lengua francesa entre las lenguas más habladas del mundo?", explanation: "El francés es la quinta lengua más hablada del mundo. Es lengua oficial en 29 países y se habla en los cinco continentes.", choices: [{ id: 'a' as const, text: "5.ª lengua más hablada" }, { id: 'b' as const, text: "2.ª lengua más hablada" }, { id: 'c' as const, text: "10.ª lengua más hablada" }, { id: 'd' as const, text: "1.ª lengua más hablada" }] },

  { textFr: "Quelle cathédrale célèbre a été en partie détruite par un incendie en 2019 ?", lang: 'es' as const, text: "¿Qué catedral célebre fue parcialmente destruida por un incendio en 2019?", explanation: "La catedral de Notre-Dame de París fue gravemente dañada por un incendio el 15 de abril de 2019. Su aguja y parte del techo se derrumbaron. Fue restaurada y reabierta en diciembre de 2024.", choices: [{ id: 'a' as const, text: "Notre-Dame de París" }, { id: 'b' as const, text: "La catedral de Reims" }, { id: 'c' as const, text: "La catedral de Chartres" }, { id: 'd' as const, text: "La catedral de Estrasburgo" }] },

  { textFr: "Qui était une écrivaine française célèbre ?", lang: 'es' as const, text: "¿Quién fue una escritora francesa célebre?", explanation: "Colette (1873-1954) fue una novelista francesa célebre, autora de numerosas novelas como la serie de las Claudine. Fue la segunda mujer en recibir funerales nacionales en Francia.", choices: [{ id: 'a' as const, text: "Colette" }, { id: 'b' as const, text: "Jane Austen" }, { id: 'c' as const, text: "Virginia Woolf" }, { id: 'd' as const, text: "Agatha Christie" }] },

  { textFr: "Qui était un célèbre musicien français ?", lang: 'es' as const, text: "¿Quién fue un célebre músico francés?", explanation: "Claude Debussy (1862-1918) fue un compositor francés, figura destacada de la música impresionista. Es conocido principalmente por Claro de luna y El mar.", choices: [{ id: 'a' as const, text: "Claude Debussy" }, { id: 'b' as const, text: "Ludwig van Beethoven" }, { id: 'c' as const, text: "Wolfgang Amadeus Mozart" }, { id: 'd' as const, text: "Johann Sebastian Bach" }] },

  { textFr: "Qui était Auguste Renoir ?", lang: 'es' as const, text: "¿Quién fue Auguste Renoir?", explanation: "Auguste Renoir (1841-1919) fue un pintor francés, uno de los grandes maestros del impresionismo. Es célebre por sus escenas de la vida cotidiana y sus retratos luminosos.", choices: [{ id: 'a' as const, text: "Un pintor impresionista francés" }, { id: 'b' as const, text: "Un escultor del siglo XVIII" }, { id: 'c' as const, text: "Un escritor realista" }, { id: 'd' as const, text: "Un arquitecto del Renacimiento" }] },

  { textFr: "Quelle fête est française ?", lang: 'es' as const, text: "¿Qué fiesta es francesa?", explanation: "La Fiesta de la Música, celebrada el 21 de junio, es una fiesta de origen francés creada en 1982 por Jack Lang. Hoy se celebra en numerosos países del mundo.", choices: [{ id: 'a' as const, text: "La Fiesta de la Música" }, { id: 'b' as const, text: "Acción de Gracias" }, { id: 'c' as const, text: "Halloween" }, { id: 'd' as const, text: "San Patricio" }] },

  // ─── Q97–Q131: NAT-only questions (difficulty 3) ───────────────────────────

  { textFr: "Parmi ces textes, lequel a été adopté sous Napoléon Ier ?", lang: 'es' as const, text: "Entre estos textos, ¿cuál fue adoptado bajo Napoleón I?", explanation: "El Código Civil fue adoptado en 1804 bajo Napoleón I. También llamado Código Napoleón, unificó el derecho francés y sigue siendo la base del derecho civil en Francia.", choices: [{ id: 'a' as const, text: "El Código Civil" }, { id: 'b' as const, text: "La Declaración de los Derechos del Hombre y del Ciudadano" }, { id: 'c' as const, text: "La ley de separación de las Iglesias y el Estado" }, { id: 'd' as const, text: "La Constitución de la V República" }] },

  { textFr: "Qui a été président de la Ve République ?", lang: 'es' as const, text: "¿Quién fue presidente de la V República?", explanation: "Jacques Chirac fue presidente de la V República de 1995 a 2007. Fue el quinto presidente de la V República, precedido por François Mitterrand.", choices: [{ id: 'a' as const, text: "Jacques Chirac" }, { id: 'b' as const, text: "Winston Churchill" }, { id: 'c' as const, text: "Konrad Adenauer" }, { id: 'd' as const, text: "Benito Mussolini" }] },

  { textFr: "Que signifie la date du 14 juillet pour les Français ?", lang: 'es' as const, text: "¿Qué significa la fecha del 14 de julio para los franceses?", explanation: "El 14 de julio es la fiesta nacional francesa. Conmemora la toma de la Bastilla en 1789, símbolo del fin del absolutismo, y la Fiesta de la Federación de 1790.", choices: [{ id: 'a' as const, text: "Es la fiesta nacional, que conmemora la toma de la Bastilla" }, { id: 'b' as const, text: "Es el aniversario de la Constitución" }, { id: 'c' as const, text: "Es la fiesta de Europa" }, { id: 'd' as const, text: "Es el día del armisticio" }] },

  { textFr: "Lequel de ces pays est un pays fondateur de l'Union européenne ?", lang: 'es' as const, text: "¿Cuál de estos países es un país fundador de la Unión Europea?", explanation: "Francia es uno de los seis países fundadores de la construcción europea junto con Alemania, Italia, Bélgica, los Países Bajos y Luxemburgo. La CECA fue creada en 1951.", choices: [{ id: 'a' as const, text: "Francia" }, { id: 'b' as const, text: "Reino Unido" }, { id: 'c' as const, text: "España" }, { id: 'd' as const, text: "Polonia" }] },

  { textFr: "Dans quelle région est située une partie des plages du débarquement ?", lang: 'es' as const, text: "¿En qué región se encuentran algunas de las playas del desembarco?", explanation: "Las playas del desembarco del 6 de junio de 1944 se encuentran en Normandía. Las cinco playas (Utah, Omaha, Gold, Juno, Sword) son lugares de memoria de gran importancia.", choices: [{ id: 'a' as const, text: "Normandía" }, { id: 'b' as const, text: "Bretaña" }, { id: 'c' as const, text: "Picardía" }, { id: 'd' as const, text: "Aquitania" }] },

  { textFr: "Dans quelle ville les rois de France étaient-ils couronnés ?", lang: 'es' as const, text: "¿En qué ciudad eran coronados los reyes de Francia?", explanation: "Los reyes de Francia eran tradicionalmente coronados en la catedral de Reims. Esta tradición se remonta al bautismo de Clodoveo hacia el año 496 y perduró durante siglos.", choices: [{ id: 'a' as const, text: "Reims" }, { id: 'b' as const, text: "París" }, { id: 'c' as const, text: "Versalles" }, { id: 'd' as const, text: "Orleans" }] },

  { textFr: "En quelle année l'Union européenne a-t-elle été fondée ?", lang: 'es' as const, text: "¿En qué año fue fundada la Unión Europea?", explanation: "La Unión Europea fue fundada en 1992 por el Tratado de Maastricht. Este tratado transformó la Comunidad Económica Europea en Unión Europea y sentó las bases de la moneda única.", choices: [{ id: 'a' as const, text: "1992" }, { id: 'b' as const, text: "1957" }, { id: 'c' as const, text: "2002" }, { id: 'd' as const, text: "1951" }] },

  { textFr: "Qui a aboli l'esclavage en France ?", lang: 'es' as const, text: "¿Quién abolió la esclavitud en Francia?", explanation: "Victor Schœlcher fue el impulsor del decreto de abolición definitiva de la esclavitud en Francia el 27 de abril de 1848. Era entonces subsecretario de Estado de las colonias bajo la II República.", choices: [{ id: 'a' as const, text: "Victor Schœlcher" }, { id: 'b' as const, text: "Napoleón Bonaparte" }, { id: 'c' as const, text: "Jules Ferry" }, { id: 'd' as const, text: "Léon Gambetta" }] },

  { textFr: "Lors de la Seconde Guerre mondiale, à quelle date Paris a-t-elle été libérée ?", lang: 'es' as const, text: "Durante la Segunda Guerra Mundial, ¿en qué fecha fue liberada París?", explanation: "París fue liberada el 25 de agosto de 1944 tras una insurrección popular y la llegada de la 2.ª división blindada del general Leclerc. Este acontecimiento marca un punto de inflexión en la liberación de Francia.", choices: [{ id: 'a' as const, text: "El 25 de agosto de 1944" }, { id: 'b' as const, text: "El 6 de junio de 1944" }, { id: 'c' as const, text: "El 8 de mayo de 1945" }, { id: 'd' as const, text: "El 18 de junio de 1940" }] },

  { textFr: "Quel était le principal port français impliqué dans la traite négrière au XVIIIe siècle ?", lang: 'es' as const, text: "¿Cuál era el principal puerto francés involucrado en la trata de esclavos en el siglo XVIII?", explanation: "Nantes era el principal puerto francés involucrado en la trata de esclavos en el siglo XVIII. La ciudad organizó el mayor número de expediciones negreras francesas y hoy posee un memorial de la abolición de la esclavitud.", choices: [{ id: 'a' as const, text: "Nantes" }, { id: 'b' as const, text: "Marsella" }, { id: 'c' as const, text: "El Havre" }, { id: 'd' as const, text: "Brest" }] },

  { textFr: "Quel célèbre philosophe des Lumières a dénoncé l'esclavage ?", lang: 'es' as const, text: "¿Qué célebre filósofo de la Ilustración denunció la esclavitud?", explanation: "Voltaire (1694-1778) fue un filósofo de la Ilustración que denunció la esclavitud, especialmente en Cándido. Los filósofos de la Ilustración desempeñaron un papel fundamental en la denuncia de esta práctica.", choices: [{ id: 'a' as const, text: "Voltaire" }, { id: 'b' as const, text: "Napoleón Bonaparte" }, { id: 'c' as const, text: "Luis XIV" }, { id: 'd' as const, text: "Richelieu" }] },

  { textFr: "Quel plat est une spécialité de la cuisine française ?", lang: 'es' as const, text: "¿Qué plato es una especialidad de la cocina francesa?", explanation: "El coq au vin es un plato tradicional de la cocina francesa, a base de pollo estofado en vino tinto con panceta y champiñones. La gastronomía francesa está inscrita en el patrimonio inmaterial de la UNESCO.", choices: [{ id: 'a' as const, text: "El coq au vin" }, { id: 'b' as const, text: "La paella" }, { id: 'c' as const, text: "El sushi" }, { id: 'd' as const, text: "El fish and chips" }] },

  { textFr: "Qui était Marie Curie ?", lang: 'es' as const, text: "¿Quién fue Marie Curie?", explanation: "Marie Curie (1867-1934) fue una física y química franco-polaca, primera mujer en recibir un premio Nobel. Obtuvo dos premios Nobel (física en 1903 y química en 1911) por sus trabajos sobre la radiactividad.", choices: [{ id: 'a' as const, text: "Una física franco-polaca, doble premio Nobel" }, { id: 'b' as const, text: "Una novelista francesa del siglo XIX" }, { id: 'c' as const, text: "Una resistente de la Segunda Guerra Mundial" }, { id: 'd' as const, text: "Una reina de Francia" }] },

  { textFr: "Qui a peint « La Liberté guidant le peuple » ?", lang: 'es' as const, text: "¿Quién pintó «La Libertad guiando al pueblo»?", explanation: "Eugène Delacroix pintó La Libertad guiando al pueblo en 1830. Este célebre cuadro representa la revolución de julio de 1830 y está expuesto en el Museo del Louvre.", choices: [{ id: 'a' as const, text: "Eugène Delacroix" }, { id: 'b' as const, text: "Claude Monet" }, { id: 'c' as const, text: "Paul Cézanne" }, { id: 'd' as const, text: "Auguste Renoir" }] },

  { textFr: "Dans quel grand musée parisien est exposée la Joconde ?", lang: 'es' as const, text: "¿En qué gran museo parisino está expuesta la Gioconda?", explanation: "La Gioconda (o Mona Lisa) de Leonardo da Vinci está expuesta en el Museo del Louvre en París. Es el cuadro más célebre del mundo y una de las joyas de la colección del museo.", choices: [{ id: 'a' as const, text: "El Museo del Louvre" }, { id: 'b' as const, text: "El Museo de Orsay" }, { id: 'c' as const, text: "El Centro Pompidou" }, { id: 'd' as const, text: "El Museo Rodin" }] },

  { textFr: "Quel château célèbre se trouve près de Paris et symbolise le pouvoir royal de Louis XIV ?", lang: 'es' as const, text: "¿Qué castillo célebre se encuentra cerca de París y simboliza el poder real de Luis XIV?", explanation: "El Palacio de Versalles fue la residencia principal de los reyes de Francia desde Luis XIV hasta Luis XVI. Construido en el siglo XVII, simboliza el poder de la monarquía absoluta.", choices: [{ id: 'a' as const, text: "El Palacio de Versalles" }, { id: 'b' as const, text: "El castillo de Chambord" }, { id: 'c' as const, text: "El castillo de Fontainebleau" }, { id: 'd' as const, text: "El castillo de Chenonceau" }] },

  { textFr: "Où peut-on voir des peintures préhistoriques en France ?", lang: 'es' as const, text: "¿Dónde se pueden ver pinturas prehistóricas en Francia?", explanation: "La cueva de Lascaux, en Dordoña, alberga pinturas prehistóricas que datan de aproximadamente 17.000 años. Descubierta en 1940, es apodada la «Capilla Sixtina de la Prehistoria».", choices: [{ id: 'a' as const, text: "En la cueva de Lascaux" }, { id: 'b' as const, text: "En el Palacio de Versalles" }, { id: 'c' as const, text: "En el Museo del Louvre" }, { id: 'd' as const, text: "En la catedral de Chartres" }] },

  { textFr: "Quel peintre célèbre a peint les Nymphéas ?", lang: 'es' as const, text: "¿Qué pintor célebre pintó los Nenúfares?", explanation: "Claude Monet pintó la célebre serie de los Nenúfares en su jardín de Giverny. Estos cuadros impresionistas, pintados entre 1895 y 1926, están expuestos en el Museo de la Orangerie en París.", choices: [{ id: 'a' as const, text: "Claude Monet" }, { id: 'b' as const, text: "Edgar Degas" }, { id: 'c' as const, text: "Paul Gauguin" }, { id: 'd' as const, text: "Édouard Manet" }] },

  { textFr: "Que symbolise le 1er mai ?", lang: 'es' as const, text: "¿Qué simboliza el 1 de mayo?", explanation: "El 1 de mayo es el Día del Trabajo en Francia, día festivo desde 1947. Es un día de celebración de los derechos de los trabajadores, tradicionalmente marcado por la ofrenda de ramitas de lirio de los valles.", choices: [{ id: 'a' as const, text: "El Día del Trabajo" }, { id: 'b' as const, text: "La fiesta nacional" }, { id: 'c' as const, text: "La Fiesta de la Música" }, { id: 'd' as const, text: "La fiesta de la Victoria" }] },

  { textFr: "Qui était Monsieur Rouget de Lisle ?", lang: 'es' as const, text: "¿Quién fue el señor Rouget de Lisle?", explanation: "Claude Joseph Rouget de Lisle (1760-1836) fue un oficial y compositor francés, autor de La Marsellesa en 1792. Este canto patriótico se convirtió en el himno nacional francés.", choices: [{ id: 'a' as const, text: "El compositor de La Marsellesa" }, { id: 'b' as const, text: "El fundador de la V República" }, { id: 'c' as const, text: "Un general de Napoleón" }, { id: 'd' as const, text: "Un filósofo de la Ilustración" }] },

  { textFr: "À quelle occasion a été construite la tour Eiffel ?", lang: 'es' as const, text: "¿Con qué ocasión fue construida la Torre Eiffel?", explanation: "La Torre Eiffel fue construida para la Exposición Universal de 1889, que celebraba el centenario de la Revolución francesa. Diseñada por Gustave Eiffel, debía ser desmontada después de la exposición.", choices: [{ id: 'a' as const, text: "La Exposición Universal de 1889" }, { id: 'b' as const, text: "Los Juegos Olímpicos de 1900" }, { id: 'c' as const, text: "La victoria de 1918" }, { id: 'd' as const, text: "La coronación de Napoleón" }] },

  { textFr: "Qui était un célèbre compositeur français ?", lang: 'es' as const, text: "¿Quién fue un célebre compositor francés?", explanation: "Maurice Ravel (1875-1937) fue un compositor francés, autor del célebre Bolero. Es uno de los más grandes compositores franceses del siglo XX junto con Claude Debussy.", choices: [{ id: 'a' as const, text: "Maurice Ravel" }, { id: 'b' as const, text: "Giuseppe Verdi" }, { id: 'c' as const, text: "Richard Wagner" }, { id: 'd' as const, text: "Piotr Chaikovski" }] },

  { textFr: "Quel monument historique se trouve sur une île en Normandie ?", lang: 'es' as const, text: "¿Qué monumento histórico se encuentra en una isla en Normandía?", explanation: "El Monte Saint-Michel es una abadía medieval situada en un islote rocoso en Normandía. Es uno de los sitios más visitados de Francia y está clasificado como Patrimonio de la Humanidad por la UNESCO.", choices: [{ id: 'a' as const, text: "El Monte Saint-Michel" }, { id: 'b' as const, text: "El castillo de Chambord" }, { id: 'c' as const, text: "El puente del Gard" }, { id: 'd' as const, text: "La ciudad de Carcasona" }] },

  { textFr: "Quelle île fait partie des Antilles françaises ?", lang: 'es' as const, text: "¿Qué isla forma parte de las Antillas francesas?", explanation: "Guadalupe forma parte de las Antillas francesas, en el mar Caribe. Es un departamento y una región de ultramar francés compuesto por varias islas.", choices: [{ id: 'a' as const, text: "Guadalupe" }, { id: 'b' as const, text: "Cuba" }, { id: 'c' as const, text: "Jamaica" }, { id: 'd' as const, text: "Puerto Rico" }] },

  { textFr: "Quelle île est française ?", lang: 'es' as const, text: "¿Qué isla es francesa?", explanation: "Nueva Caledonia es un territorio francés situado en el océano Pacífico. Es una colectividad sui generis de Francia con un estatus particular dentro de la República.", choices: [{ id: 'a' as const, text: "Nueva Caledonia" }, { id: 'b' as const, text: "Las Bahamas" }, { id: 'c' as const, text: "Las Maldivas" }, { id: 'd' as const, text: "Borneo" }] },

  { textFr: "Quelle est la plus haute montagne de France ?", lang: 'es' as const, text: "¿Cuál es la montaña más alta de Francia?", explanation: "El Mont Blanc, que culmina a 4.809 metros, es la montaña más alta de Francia y de Europa occidental. Está situado en los Alpes, en la frontera entre Francia e Italia.", choices: [{ id: 'a' as const, text: "El Mont Blanc" }, { id: 'b' as const, text: "El Puy de Dôme" }, { id: 'c' as const, text: "El Pic du Midi" }, { id: 'd' as const, text: "El Mont Ventoux" }] },

  { textFr: "Quelle île française est située au sud-est du continent africain ?", lang: 'es' as const, text: "¿Qué isla francesa está situada al sureste del continente africano?", explanation: "Mayotte es una isla francesa situada en el océano Índico, al sureste del continente africano. Se convirtió en el departamento francés número 101 en 2011.", choices: [{ id: 'a' as const, text: "Mayotte" }, { id: 'b' as const, text: "Martinica" }, { id: 'c' as const, text: "Guadalupe" }, { id: 'd' as const, text: "San Pedro y Miquelón" }] },

  { textFr: "Quel département français a une frontière avec le Brésil ?", lang: 'es' as const, text: "¿Qué departamento francés tiene frontera con Brasil?", explanation: "La Guayana Francesa es un departamento de ultramar situado en América del Sur, que comparte frontera con Brasil. Es el departamento francés más grande por su superficie.", choices: [{ id: 'a' as const, text: "La Guayana" }, { id: 'b' as const, text: "Martinica" }, { id: 'c' as const, text: "La Reunión" }, { id: 'd' as const, text: "Mayotte" }] },

  { textFr: "De quelle ville française décolle la fusée Ariane ?", lang: 'es' as const, text: "¿Desde qué ciudad francesa despega el cohete Ariane?", explanation: "El cohete Ariane despega desde Kourou, en la Guayana Francesa. El Centro Espacial Guyanés es la base de lanzamiento de la Agencia Espacial Europea (ESA) desde 1968.", choices: [{ id: 'a' as const, text: "Kourou" }, { id: 'b' as const, text: "Toulouse" }, { id: 'c' as const, text: "Burdeos" }, { id: 'd' as const, text: "Marsella" }] },

  { textFr: "Quel est le principal port maritime de France ?", lang: 'es' as const, text: "¿Cuál es el principal puerto marítimo de Francia?", explanation: "Marsella es el principal puerto marítimo de Francia y el primer puerto del Mediterráneo. El Gran Puerto Marítimo de Marsella gestiona millones de toneladas de mercancías cada año.", choices: [{ id: 'a' as const, text: "Marsella" }, { id: 'b' as const, text: "Nantes" }, { id: 'c' as const, text: "Brest" }, { id: 'd' as const, text: "Burdeos" }] },

  { textFr: "Quel est le chef-lieu de la région Auvergne-Rhône-Alpes ?", lang: 'es' as const, text: "¿Cuál es la capital de la región Auvernia-Ródano-Alpes?", explanation: "Lyon es la capital de la región Auvernia-Ródano-Alpes. Es la tercera ciudad más grande de Francia y un importante centro económico y cultural.", choices: [{ id: 'a' as const, text: "Lyon" }, { id: 'b' as const, text: "Clermont-Ferrand" }, { id: 'c' as const, text: "Grenoble" }, { id: 'd' as const, text: "Saint-Étienne" }] },

  { textFr: "Quel est le chef-lieu de la région Bretagne ?", lang: 'es' as const, text: "¿Cuál es la capital de la región Bretaña?", explanation: "Rennes es la capital de la región Bretaña. Es una ciudad dinámica y universitaria situada en el oeste de Francia.", choices: [{ id: 'a' as const, text: "Rennes" }, { id: 'b' as const, text: "Brest" }, { id: 'c' as const, text: "Nantes" }, { id: 'd' as const, text: "Quimper" }] },

  { textFr: "Quel est le chef-lieu de la région Provence-Alpes-Côte d'Azur ?", lang: 'es' as const, text: "¿Cuál es la capital de la región Provenza-Alpes-Costa Azul?", explanation: "Marsella es la capital de la región Provenza-Alpes-Costa Azul (PACA). Es la segunda ciudad más grande de Francia y un puerto importante del Mediterráneo.", choices: [{ id: 'a' as const, text: "Marsella" }, { id: 'b' as const, text: "Niza" }, { id: 'c' as const, text: "Tolón" }, { id: 'd' as const, text: "Aix-en-Provence" }] },

  { textFr: "Quel est le 101e département français depuis 2011 ?", lang: 'es' as const, text: "¿Cuál es el departamento francés número 101 desde 2011?", explanation: "Mayotte se convirtió en el departamento francés número 101 el 31 de marzo de 2011, tras el referéndum de 2009. Es el departamento de ultramar más reciente en integrarse a la República francesa.", choices: [{ id: 'a' as const, text: "Mayotte" }, { id: 'b' as const, text: "La Guayana" }, { id: 'c' as const, text: "Nueva Caledonia" }, { id: 'd' as const, text: "San Martín" }] },

  { textFr: "Quelle région française est réputée pour ses stations de ski ?", lang: 'es' as const, text: "¿Qué región francesa es famosa por sus estaciones de esquí?", explanation: "La región Auvernia-Ródano-Alpes es la más famosa por sus estaciones de esquí en Francia. Alberga numerosas estaciones alpinas de renombre como Chamonix, Les Deux Alpes y Val-d'Isère.", choices: [{ id: 'a' as const, text: "Auvernia-Ródano-Alpes" }, { id: 'b' as const, text: "La Isla de Francia" }, { id: 'c' as const, text: "Nueva Aquitania" }, { id: 'd' as const, text: "Bretaña" }] },
];
