export const theme5Es = [
  // Q1
  { textFr: "Quel numéro d'urgence permet d'appeler le SAMU ?", lang: 'es' as const, text: "\u00bfQu\u00e9 n\u00famero de emergencia permite llamar al SAMU?", explanation: "El 15 es el n\u00famero de emergencia del SAMU (Servicio de Ayuda M\u00e9dica Urgente). Permite contactar a un m\u00e9dico regulador que eval\u00faa la situaci\u00f3n y env\u00eda los servicios de socorro adecuados.", choices: [{ id: 'a' as const, text: 'El 15' }, { id: 'b' as const, text: 'El 17' }, { id: 'c' as const, text: 'El 18' }, { id: 'd' as const, text: 'El 112' }] },
  // Q2
  { textFr: "Quel numéro d'urgence permet d'appeler les pompiers ?", lang: 'es' as const, text: "\u00bfQu\u00e9 n\u00famero de emergencia permite llamar a los bomberos?", explanation: "El 18 es el n\u00famero de los bomberos. Permite reportar un incendio, un accidente o cualquier situaci\u00f3n que requiera una intervenci\u00f3n de emergencia.", choices: [{ id: 'a' as const, text: 'El 18' }, { id: 'b' as const, text: 'El 15' }, { id: 'c' as const, text: 'El 17' }, { id: 'd' as const, text: 'El 114' }] },
  // Q3
  { textFr: "Après avoir obtenu le permis de conduire, que faut-il faire pour pouvoir conduire sa voiture ?", lang: 'es' as const, text: "Despu\u00e9s de obtener el permiso de conducir, \u00bfqu\u00e9 hay que hacer para poder conducir su coche?", explanation: "Para conducir legalmente, es necesario asegurar su veh\u00edculo con una compa\u00f1\u00eda de seguros. El seguro de autom\u00f3vil es obligatorio en Francia para cubrir los da\u00f1os causados a terceros.", choices: [{ id: 'a' as const, text: 'Asegurar su veh\u00edculo con una compa\u00f1\u00eda de seguros' }, { id: 'b' as const, text: 'Inscribirse en la prefectura de polic\u00eda' }, { id: 'c' as const, text: 'Pasar un examen m\u00e9dico obligatorio' }, { id: 'd' as const, text: 'Obtener una autorizaci\u00f3n especial del ayuntamiento' }] },
  // Q4
  { textFr: "À quelles conditions un mariage est-il reconnu juridiquement ?", lang: 'es' as const, text: "\u00bfBajo qu\u00e9 condiciones un matrimonio es reconocido jur\u00eddicamente?", explanation: "En Francia, solo el matrimonio civil celebrado en el ayuntamiento es reconocido jur\u00eddicamente. El matrimonio religioso no tiene valor legal si no es precedido por un matrimonio civil.", choices: [{ id: 'a' as const, text: 'Si se celebra en el ayuntamiento (matrimonio civil)' }, { id: 'b' as const, text: 'Si se celebra en un lugar de culto' }, { id: 'c' as const, text: 'Si es reconocido por la familia de los c\u00f3nyuges' }, { id: 'd' as const, text: 'Si es organizado por un notario' }] },
  // Q5
  { textFr: "Quand faut-il déclarer son enfant au service d'état civil de la mairie ?", lang: 'es' as const, text: "\u00bfCu\u00e1ndo hay que declarar a su hijo en el servicio de registro civil del ayuntamiento?", explanation: "La declaraci\u00f3n de nacimiento debe realizarse dentro de los 5 d\u00edas siguientes al nacimiento en el ayuntamiento del lugar de nacimiento. Este plazo est\u00e1 fijado por la ley.", choices: [{ id: 'a' as const, text: 'Dentro de los 5 d\u00edas siguientes al nacimiento' }, { id: 'b' as const, text: 'Dentro de los 30 d\u00edas siguientes al nacimiento' }, { id: 'c' as const, text: 'Dentro de los 3 meses siguientes al nacimiento' }, { id: 'd' as const, text: 'Antes de salir del hospital' }] },
  // Q6
  { textFr: "Le travail non déclaré est :", lang: 'es' as const, text: "El trabajo no declarado es:", explanation: "El trabajo no declarado (trabajo en negro) est\u00e1 prohibido por la ley. Priva al empleado de protecci\u00f3n social y expone al empleador y al empleado a sanciones penales y financieras.", choices: [{ id: 'a' as const, text: 'Prohibido por la ley' }, { id: 'b' as const, text: 'Autorizado para peque\u00f1os trabajos' }, { id: 'c' as const, text: 'Tolerado si el empleado est\u00e1 de acuerdo' }, { id: 'd' as const, text: 'Autorizado para los trabajadores extranjeros' }] },
  // Q7
  { textFr: "Que doit faire un employeur pour fixer un salaire ?", lang: 'es' as const, text: "\u00bfQu\u00e9 debe hacer un empleador para fijar un salario?", explanation: "El empleador debe respetar el SMIC (Salario M\u00ednimo Interprofesional de Crecimiento) y los convenios colectivos aplicables. No puede fijar un salario inferior al m\u00ednimo legal.", choices: [{ id: 'a' as const, text: 'Respetar como m\u00ednimo el SMIC y el convenio colectivo' }, { id: 'b' as const, text: 'Fijar libremente el monto sin ninguna restricci\u00f3n' }, { id: 'c' as const, text: 'Pedir la autorizaci\u00f3n del ayuntamiento' }, { id: 'd' as const, text: 'Consultar a los dem\u00e1s empleadores del barrio' }] },
  // Q8
  { textFr: "Qu'est-ce que le SMIC ?", lang: 'es' as const, text: "\u00bfQu\u00e9 es el SMIC?", explanation: "El SMIC es el Salario M\u00ednimo Interprofesional de Crecimiento. Es el salario por hora m\u00ednimo legal por debajo del cual ning\u00fan empleado puede ser remunerado en Francia.", choices: [{ id: 'a' as const, text: 'El salario m\u00ednimo legal por debajo del cual un empleado no puede ser pagado' }, { id: 'b' as const, text: 'El salario medio de los franceses' }, { id: 'c' as const, text: 'Una ayuda financiera otorgada por el Estado a los desempleados' }, { id: 'd' as const, text: 'El salario m\u00e1ximo autorizado por la ley' }] },
  // Q9
  { textFr: "Quelle est la première démarche à réaliser pour chercher un emploi ?", lang: 'es' as const, text: "\u00bfCu\u00e1l es el primer tr\u00e1mite a realizar para buscar empleo?", explanation: "El primer tr\u00e1mite para buscar empleo es inscribirse en France Travail (anteriormente P\u00f4le emploi). Este organismo acompa\u00f1a a los demandantes de empleo en sus b\u00fasquedas y puede otorgarles prestaciones.", choices: [{ id: 'a' as const, text: 'Inscribirse en France Travail (anteriormente P\u00f4le emploi)' }, { id: 'b' as const, text: 'Escribir directamente al presidente de la Rep\u00fablica' }, { id: 'c' as const, text: 'Inscribirse en el ayuntamiento de su domicilio' }, { id: 'd' as const, text: 'Publicar un anuncio en un peri\u00f3dico' }] },
  // Q10
  { textFr: "Quelle est la durée légale du temps de travail par semaine ?", lang: 'es' as const, text: "\u00bfCu\u00e1l es la duraci\u00f3n legal del tiempo de trabajo por semana?", explanation: "La duraci\u00f3n legal del trabajo en Francia es de 35 horas por semana. M\u00e1s all\u00e1 de eso, las horas extraordinarias dan lugar a un aumento de salario o a un descanso compensatorio.", choices: [{ id: 'a' as const, text: '35 horas' }, { id: 'b' as const, text: '39 horas' }, { id: 'c' as const, text: '40 horas' }, { id: 'd' as const, text: '32 horas' }] },
  // Q11
  { textFr: "Qui est aidé par France Travail ?", lang: 'es' as const, text: "\u00bfA qui\u00e9n ayuda France Travail?", explanation: "France Travail (anteriormente P\u00f4le emploi) ayuda a las personas que buscan empleo. Ofrece acompa\u00f1amiento personalizado, formaciones y el pago de prestaciones por desempleo.", choices: [{ id: 'a' as const, text: 'A las personas que buscan empleo' }, { id: 'b' as const, text: 'Solo a las personas jubiladas' }, { id: 'c' as const, text: 'Exclusivamente a los empleadores' }, { id: 'd' as const, text: 'A los estudiantes en formaci\u00f3n inicial' }] },
  // Q12
  { textFr: "Une personne étrangère en situation régulière peut créer son entreprise :", lang: 'es' as const, text: "Una persona extranjera en situaci\u00f3n regular puede crear su empresa:", explanation: "En Francia, una persona extranjera en situaci\u00f3n regular tiene derecho a crear su empresa, como cualquier ciudadano franc\u00e9s. No hay restricci\u00f3n de nacionalidad para el emprendimiento si el permiso de residencia lo permite.", choices: [{ id: 'a' as const, text: 'S\u00ed, como cualquier otra persona' }, { id: 'b' as const, text: 'No, solo los franceses pueden' }, { id: 'c' as const, text: 'Solo con una autorizaci\u00f3n especial del prefecto' }, { id: 'd' as const, text: 'Solo despu\u00e9s de 10 a\u00f1os de residencia en Francia' }] },
  // Q13
  { textFr: "Une femme peut-elle créer son entreprise ?", lang: 'es' as const, text: "\u00bfPuede una mujer crear su empresa?", explanation: "S\u00ed, una mujer puede crear su empresa en Francia. La igualdad entre mujeres y hombres es un principio fundamental de la Rep\u00fablica, incluso en el \u00e1mbito econ\u00f3mico y profesional.", choices: [{ id: 'a' as const, text: 'S\u00ed, en las mismas condiciones que un hombre' }, { id: 'b' as const, text: 'No, debe obtener el acuerdo de su marido' }, { id: 'c' as const, text: 'Solo en ciertos sectores de actividad' }, { id: 'd' as const, text: 'Solo si es de nacionalidad francesa' }] },
  // Q14
  { textFr: "À partir de quel âge un mineur peut-il travailler ?", lang: 'es' as const, text: "\u00bfA partir de qu\u00e9 edad un menor puede trabajar?", explanation: "En Francia, un menor puede trabajar a partir de los 16 a\u00f1os, con la autorizaci\u00f3n de sus padres. Existen excepciones para el aprendizaje desde los 15 a\u00f1os bajo ciertas condiciones.", choices: [{ id: 'a' as const, text: '16 a\u00f1os' }, { id: 'b' as const, text: '14 a\u00f1os' }, { id: 'c' as const, text: '18 a\u00f1os' }, { id: 'd' as const, text: '12 a\u00f1os' }] },
  // Q15
  { textFr: "Auprès de quel organisme faut-il demander le remboursement des frais de santé ?", lang: 'es' as const, text: "\u00bfAnte qu\u00e9 organismo hay que solicitar el reembolso de los gastos de salud?", explanation: "Es ante la Seguridad Social (Seguro de enfermedad / CPAM) donde hay que solicitar el reembolso de los gastos de salud. Se encarga de una parte de los gastos m\u00e9dicos.", choices: [{ id: 'a' as const, text: 'La Seguridad Social (Seguro de enfermedad)' }, { id: 'b' as const, text: 'El ayuntamiento' }, { id: 'c' as const, text: 'France Travail' }, { id: 'd' as const, text: 'El Banco de Francia' }] },
  // Q16
  { textFr: "Qu'est-ce qu'un numéro d'urgence ?", lang: 'es' as const, text: "\u00bfQu\u00e9 es un n\u00famero de emergencia?", explanation: "Un n\u00famero de emergencia es un n\u00famero de tel\u00e9fono gratuito, accesible las 24 horas del d\u00eda, que permite contactar a los servicios de socorro (SAMU, bomberos, polic\u00eda) en caso de situaci\u00f3n de emergencia.", choices: [{ id: 'a' as const, text: 'Un n\u00famero gratuito para contactar a los servicios de socorro en cualquier momento' }, { id: 'b' as const, text: 'Un n\u00famero de pago reservado a los m\u00e9dicos' }, { id: 'c' as const, text: 'Un n\u00famero disponible solo durante el d\u00eda' }, { id: 'd' as const, text: 'Un n\u00famero para contactar a su mutua' }] },
  // Q17
  { textFr: "Concernant l'accès aux soins, quelle proposition est correcte ?", lang: 'es' as const, text: "Respecto al acceso a la atenci\u00f3n m\u00e9dica, \u00bfqu\u00e9 proposici\u00f3n es correcta?", explanation: "En Francia, toda persona tiene derecho a ser atendida, sin importar su nacionalidad o su situaci\u00f3n financiera. El acceso a la atenci\u00f3n m\u00e9dica es un derecho fundamental garantizado por la ley.", choices: [{ id: 'a' as const, text: 'Toda persona tiene derecho a ser atendida' }, { id: 'b' as const, text: 'Solo los ciudadanos franceses tienen acceso a la atenci\u00f3n m\u00e9dica' }, { id: 'c' as const, text: 'El acceso a la atenci\u00f3n m\u00e9dica depende del nivel de ingresos' }, { id: 'd' as const, text: 'Se necesita una autorizaci\u00f3n prefectoral para consultar a un m\u00e9dico' }] },
  // Q18
  { textFr: "En cas de problème de santé non urgent, à qui faut-il s'adresser en premier ?", lang: 'es' as const, text: "En caso de problema de salud no urgente, \u00bfa qui\u00e9n hay que dirigirse primero?", explanation: "En caso de problema de salud no urgente, hay que consultar primero a su m\u00e9dico de cabecera. Coordina la atenci\u00f3n y deriva a un especialista si es necesario. Esto evita la saturaci\u00f3n de las urgencias hospitalarias.", choices: [{ id: 'a' as const, text: 'A su m\u00e9dico de cabecera' }, { id: 'b' as const, text: 'A urgencias del hospital' }, { id: 'c' as const, text: 'A la farmacia' }, { id: 'd' as const, text: 'Al SAMU llamando al 15' }] },
  // Q19
  { textFr: "Quel est le rôle du médecin traitant ?", lang: 'es' as const, text: "\u00bfCu\u00e1l es el papel del m\u00e9dico de cabecera?", explanation: "El m\u00e9dico de cabecera asegura el seguimiento m\u00e9dico global del paciente. Coordina la atenci\u00f3n, deriva a especialistas si es necesario y mantiene actualizado el expediente m\u00e9dico. Es el primer interlocutor para las cuestiones de salud.", choices: [{ id: 'a' as const, text: 'Asegurar el seguimiento m\u00e9dico y coordinar la atenci\u00f3n del paciente' }, { id: 'b' as const, text: 'Prescribir \u00fanicamente medicamentos gen\u00e9ricos' }, { id: 'c' as const, text: 'Gestionar las urgencias hospitalarias' }, { id: 'd' as const, text: 'Reembolsar los gastos de salud' }] },
  // Q20
  { textFr: "Dans quelles situations doit-on se rendre aux urgences de l'hôpital ?", lang: 'es' as const, text: "\u00bfEn qu\u00e9 situaciones se debe acudir a urgencias del hospital?", explanation: "Las urgencias del hospital est\u00e1n reservadas para situaciones graves que requieren atenci\u00f3n inmediata: accidente grave, dolor intenso, dificultad respiratoria, etc. Para problemas no urgentes, hay que consultar a su m\u00e9dico de cabecera.", choices: [{ id: 'a' as const, text: 'En caso de accidente grave o situaci\u00f3n que pone la vida en peligro' }, { id: 'b' as const, text: 'Para un simple resfriado o una gripe leve' }, { id: 'c' as const, text: 'Para renovar una receta m\u00e9dica' }, { id: 'd' as const, text: 'Para obtener un certificado m\u00e9dico deportivo' }] },
  // Q21
  { textFr: "Quel est l'objectif des vaccinations obligatoires ?", lang: 'es' as const, text: "\u00bfCu\u00e1l es el objetivo de las vacunas obligatorias?", explanation: "Las vacunas obligatorias tienen como objetivo proteger la salud de cada persona y de la colectividad impidiendo la propagaci\u00f3n de enfermedades graves. Es el principio de la protecci\u00f3n colectiva.", choices: [{ id: 'a' as const, text: 'Proteger la salud individual y colectiva contra enfermedades graves' }, { id: 'b' as const, text: 'Permitir que los laboratorios farmac\u00e9uticos obtengan beneficios' }, { id: 'c' as const, text: 'Controlar a la poblaci\u00f3n' }, { id: 'd' as const, text: 'Reemplazar las consultas con el m\u00e9dico' }] },
  // Q22
  { textFr: "À quoi sert la carte Vitale ?", lang: 'es' as const, text: "\u00bfPara qu\u00e9 sirve la tarjeta Vitale?", explanation: "La tarjeta Vitale es la tarjeta del seguro de enfermedad. Permite ser reembolsado m\u00e1s r\u00e1pidamente de los gastos de salud por la Seguridad Social. Contiene la informaci\u00f3n administrativa del asegurado.", choices: [{ id: 'a' as const, text: 'Para ser reembolsado de los gastos de salud por la Seguridad Social' }, { id: 'b' as const, text: 'Para obtener descuentos en las farmacias' }, { id: 'c' as const, text: 'Para probar su identidad' }, { id: 'd' as const, text: 'Para pagar sus impuestos' }] },
  // Q23
  { textFr: "À quoi sert une mutuelle santé ?", lang: 'es' as const, text: "\u00bfPara qu\u00e9 sirve una mutua de salud?", explanation: "Una mutua de salud (seguro complementario de salud) sirve para complementar los reembolsos de la Seguridad Social. Se encarga de todo o parte de los gastos de salud que quedan a cargo del asegurado.", choices: [{ id: 'a' as const, text: 'Para complementar los reembolsos de la Seguridad Social' }, { id: 'b' as const, text: 'Para reemplazar a la Seguridad Social' }, { id: 'c' as const, text: 'Para obtener un empleo' }, { id: 'd' as const, text: 'Para financiar su jubilaci\u00f3n' }] },
  // Q24
  { textFr: "Jusqu'à quel âge l'école est-elle obligatoire ?", lang: 'es' as const, text: "\u00bfHasta qu\u00e9 edad la escuela es obligatoria?", explanation: "La instrucci\u00f3n es obligatoria en Francia para todos los ni\u00f1os de 3 a 16 a\u00f1os. Desde la ley de 2019, la obligaci\u00f3n de instrucci\u00f3n comienza a los 3 a\u00f1os y contin\u00faa hasta los 16 a\u00f1os.", choices: [{ id: 'a' as const, text: '16 a\u00f1os' }, { id: 'b' as const, text: '14 a\u00f1os' }, { id: 'c' as const, text: '18 a\u00f1os' }, { id: 'd' as const, text: '12 a\u00f1os' }] },
  // Q25
  { textFr: "L'autorité parentale prévoit l'obligation :", lang: 'es' as const, text: "La autoridad parental prev\u00e9 la obligaci\u00f3n:", explanation: "La autoridad parental prev\u00e9 la obligaci\u00f3n de proteger al ni\u00f1o, asegurar su educaci\u00f3n y permitir su desarrollo. Los padres deben velar por su salud, su seguridad y su moralidad.", choices: [{ id: 'a' as const, text: 'De proteger, educar y asegurar el desarrollo del ni\u00f1o' }, { id: 'b' as const, text: 'De dejar que el ni\u00f1o decida solo su futuro desde los 10 a\u00f1os' }, { id: 'c' as const, text: 'De confiar al ni\u00f1o al Estado desde su nacimiento' }, { id: 'd' as const, text: 'De inscribir al ni\u00f1o en una escuela privada' }] },
  // Q26
  { textFr: "Pour qui l'école est-elle obligatoire ?", lang: 'es' as const, text: "\u00bfPara qui\u00e9n es obligatoria la escuela?", explanation: "La escuela (la instrucci\u00f3n) es obligatoria para todos los ni\u00f1os que residen en Francia, de 3 a 16 a\u00f1os, sin importar su nacionalidad o su situaci\u00f3n administrativa.", choices: [{ id: 'a' as const, text: 'Para todos los ni\u00f1os que residen en Francia, de 3 a 16 a\u00f1os' }, { id: 'b' as const, text: 'Solo para los ni\u00f1os de nacionalidad francesa' }, { id: 'c' as const, text: 'Solo para los ni\u00f1os' }, { id: 'd' as const, text: 'Para los ni\u00f1os de 6 a 18 a\u00f1os' }] },
  // Q27
  { textFr: "Quel diplôme obtient-on à la fin du lycée ?", lang: 'es' as const, text: "\u00bfQu\u00e9 diploma se obtiene al final del liceo?", explanation: "El bachillerato (baccalaur\u00e9at) es el diploma obtenido al final del liceo. Certifica el fin de los estudios secundarios y permite el acceso a la ense\u00f1anza superior.", choices: [{ id: 'a' as const, text: 'El bachillerato (baccalaur\u00e9at)' }, { id: 'b' as const, text: 'El diploma de secundaria (brevet des coll\u00e8ges)' }, { id: 'c' as const, text: 'El CAP' }, { id: 'd' as const, text: 'La licenciatura' }] },
  // Q28
  { textFr: "Dans quels établissements scolaires vont les élèves après l'école élémentaire ?", lang: 'es' as const, text: "\u00bfA qu\u00e9 establecimientos escolares van los alumnos despu\u00e9s de la escuela primaria?", explanation: "Despu\u00e9s de la escuela primaria (elemental), los alumnos van al coll\u00e8ge (secundaria inferior). El coll\u00e8ge acoge a los alumnos de 6\u00e8me a 3\u00e8me, generalmente de 11 a 15 a\u00f1os.", choices: [{ id: 'a' as const, text: 'Al coll\u00e8ge (secundaria inferior)' }, { id: 'b' as const, text: 'Al liceo' }, { id: 'c' as const, text: 'A la universidad' }, { id: 'd' as const, text: 'A la escuela maternal' }] },
  // Q29
  { textFr: "Un enfant inscrit à l'école :", lang: 'es' as const, text: "Un ni\u00f1o inscrito en la escuela:", explanation: "Un ni\u00f1o inscrito en la escuela debe asistir regularmente. La asistencia escolar es una obligaci\u00f3n legal. Las ausencias no justificadas pueden conllevar sanciones para los padres.", choices: [{ id: 'a' as const, text: 'Debe asistir a la escuela regularmente (obligaci\u00f3n de asistencia)' }, { id: 'b' as const, text: 'Puede ausentarse cuando lo desee' }, { id: 'c' as const, text: 'No est\u00e1 obligado a seguir todos los cursos' }, { id: 'd' as const, text: 'Puede abandonar la escuela en cualquier momento del d\u00eda' }] },
  // Q30
  { textFr: "Les enfants qui ne parlent pas français :", lang: 'es' as const, text: "Los ni\u00f1os que no hablan franc\u00e9s:", explanation: "Los ni\u00f1os que no hablan franc\u00e9s se benefician de una ense\u00f1anza adaptada para aprender franc\u00e9s. Existen dispositivos espec\u00edficos (UPE2A) en las escuelas para acompa\u00f1arlos en el aprendizaje del idioma.", choices: [{ id: 'a' as const, text: 'Se benefician de una ense\u00f1anza adaptada para aprender franc\u00e9s en la escuela' }, { id: 'b' as const, text: 'No pueden inscribirse en la escuela p\u00fablica' }, { id: 'c' as const, text: 'Deben primero aprender franc\u00e9s antes de ir a la escuela' }, { id: 'd' as const, text: 'Son orientados hacia escuelas especiales privadas' }] },
  // Q31
  { textFr: "Quel mariage est reconnu par l'État ?", lang: 'es' as const, text: "\u00bfQu\u00e9 matrimonio es reconocido por el Estado?", explanation: "Solo el matrimonio civil, celebrado en el ayuntamiento ante un oficial del registro civil, es reconocido por el Estado franc\u00e9s. El matrimonio religioso no tiene ning\u00fan valor jur\u00eddico en Francia.", choices: [{ id: 'a' as const, text: 'El matrimonio civil celebrado en el ayuntamiento' }, { id: 'b' as const, text: 'El matrimonio religioso celebrado en un lugar de culto' }, { id: 'c' as const, text: 'El matrimonio consuetudinario celebrado en familia' }, { id: 'd' as const, text: 'Todo tipo de matrimonio es reconocido por el Estado' }] },
  // Q32
  { textFr: "Auprès de quelle institution les parents peuvent-ils inscrire leur enfant à l'école publique ?", lang: 'es' as const, text: "\u00bfAnte qu\u00e9 instituci\u00f3n los padres pueden inscribir a su hijo en la escuela p\u00fablica?", explanation: "Los padres deben inscribir a su hijo en la escuela p\u00fablica en el ayuntamiento de su municipio de residencia. El ayuntamiento les indica la escuela correspondiente seg\u00fan el lugar de residencia.", choices: [{ id: 'a' as const, text: 'El ayuntamiento de su municipio' }, { id: 'b' as const, text: 'La prefectura' }, { id: 'c' as const, text: 'El rectorado' }, { id: 'd' as const, text: 'El Ministerio de Educaci\u00f3n Nacional' }] },
  // Q33
  { textFr: "En cas de divorce, qui exerce l'autorité parentale ?", lang: 'es' as const, text: "En caso de divorcio, \u00bfqui\u00e9n ejerce la autoridad parental?", explanation: "En caso de divorcio, ambos padres contin\u00faan ejerciendo conjuntamente la autoridad parental, salvo decisi\u00f3n contraria del juez. El inter\u00e9s del ni\u00f1o prevalece en todas las decisiones.", choices: [{ id: 'a' as const, text: 'Ambos padres conjuntamente' }, { id: 'b' as const, text: 'Solo la madre' }, { id: 'c' as const, text: 'Solo el padre' }, { id: 'd' as const, text: 'El Estado se hace cargo del ni\u00f1o' }] },
  // Q34
  { textFr: "Quelle aide permet aux personnes qui ont des difficultés financières d'avoir un avocat ?", lang: 'es' as const, text: "\u00bfQu\u00e9 ayuda permite a las personas con dificultades financieras tener un abogado?", explanation: "La asistencia jur\u00eddica permite a las personas con bajos ingresos beneficiarse de un abogado financiado total o parcialmente por el Estado. Garantiza el acceso a la justicia para todos.", choices: [{ id: 'a' as const, text: 'La asistencia jur\u00eddica' }, { id: 'b' as const, text: 'El RSA (Ingreso de Solidaridad Activa)' }, { id: 'c' as const, text: 'La ayuda para vivienda' }, { id: 'd' as const, text: 'La CMU (Cobertura M\u00e9dica Universal)' }] },
  // Q35
  { textFr: "Où faut-il déclarer la naissance d'un enfant ?", lang: 'es' as const, text: "\u00bfD\u00f3nde hay que declarar el nacimiento de un ni\u00f1o?", explanation: "El nacimiento de un ni\u00f1o debe declararse en el ayuntamiento del lugar de nacimiento, dentro de los 5 d\u00edas siguientes al parto. El oficial del registro civil elabora entonces el acta de nacimiento.", choices: [{ id: 'a' as const, text: 'En el ayuntamiento del lugar de nacimiento' }, { id: 'b' as const, text: 'En la prefectura del departamento' }, { id: 'c' as const, text: 'En la comisar\u00eda de polic\u00eda' }, { id: 'd' as const, text: 'En el tribunal judicial' }] },
  // Q36
  { textFr: "Quelle est l'une des conditions pour passer l'examen du permis de conduire ?", lang: 'es' as const, text: "\u00bfCu\u00e1l es una de las condiciones para presentar el examen del permiso de conducir?", explanation: "Para presentar el examen del permiso de conducir en Francia, hay que tener al menos 17 a\u00f1os (o 15 a\u00f1os para la conducci\u00f3n acompa\u00f1ada). Tambi\u00e9n es necesario haber obtenido el c\u00f3digo de la carretera.", choices: [{ id: 'a' as const, text: 'Tener al menos 17 a\u00f1os' }, { id: 'b' as const, text: 'Tener al menos 21 a\u00f1os' }, { id: 'c' as const, text: 'Ser de nacionalidad francesa' }, { id: 'd' as const, text: 'Poseer su propio veh\u00edculo' }] },
  // Q37
  { textFr: "Un bail locatif est valide s'il est :", lang: 'es' as const, text: "Un contrato de alquiler es v\u00e1lido si est\u00e1:", explanation: "Un contrato de alquiler es v\u00e1lido si est\u00e1 firmado por el propietario y el inquilino. Debe ser por escrito e incluir ciertas menciones obligatorias como la descripci\u00f3n de la vivienda, el monto del alquiler y la duraci\u00f3n.", choices: [{ id: 'a' as const, text: 'Firmado por el propietario y el inquilino' }, { id: 'b' as const, text: 'Validado por el ayuntamiento' }, { id: 'c' as const, text: 'Registrado en el tribunal' }, { id: 'd' as const, text: 'Aprobado por un notario obligatoriamente' }] },
  // Q38
  { textFr: "Où peut-on déposer un lave-vaisselle cassé ?", lang: 'es' as const, text: "\u00bfD\u00f3nde se puede depositar un lavavajillas roto?", explanation: "Un lavavajillas roto es un residuo de aparato el\u00e9ctrico y electr\u00f3nico (RAEE). Puede depositarse en un punto limpio o ser recogido gratuitamente por la tienda al comprar un nuevo aparato equivalente.", choices: [{ id: 'a' as const, text: 'En el punto limpio o hacerlo recoger por una tienda' }, { id: 'b' as const, text: 'En la acera frente a su casa' }, { id: 'c' as const, text: 'En el cubo de basura dom\u00e9stica' }, { id: 'd' as const, text: 'En un contenedor de reciclaje de vidrio' }] },
  // Q39
  { textFr: "Quel numéro d'urgence permet d'appeler la police ?", lang: 'es' as const, text: "\u00bfQu\u00e9 n\u00famero de emergencia permite llamar a la polic\u00eda?", explanation: "El 17 es el n\u00famero de emergencia para contactar a la polic\u00eda o la gendarmer\u00eda. Permite reportar una situaci\u00f3n de emergencia que requiere la intervenci\u00f3n de las fuerzas del orden.", choices: [{ id: 'a' as const, text: 'El 17' }, { id: 'b' as const, text: 'El 15' }, { id: 'c' as const, text: 'El 18' }, { id: 'd' as const, text: 'El 119' }] },
  // Q40
  { textFr: "À qui est accessible la contraception ?", lang: 'es' as const, text: "\u00bfA qui\u00e9n es accesible la anticoncepci\u00f3n?", explanation: "La anticoncepci\u00f3n es accesible para toda persona, incluidos los menores. Las menores pueden obtener anticonceptivos gratuitamente y de manera confidencial, sin autorizaci\u00f3n parental.", choices: [{ id: 'a' as const, text: 'A toda persona, incluidos los menores' }, { id: 'b' as const, text: 'Solo a las personas mayores de edad' }, { id: 'c' as const, text: 'Solo a las mujeres casadas' }, { id: 'd' as const, text: 'Solo con receta de un especialista' }] },
  // Q41
  { textFr: "Qu'est-ce que le principe de confidentialité dans le domaine de la santé ?", lang: 'es' as const, text: "\u00bfQu\u00e9 es el principio de confidencialidad en el \u00e1mbito de la salud?", explanation: "El principio de confidencialidad (secreto m\u00e9dico) significa que el m\u00e9dico no puede divulgar informaci\u00f3n sobre la salud de su paciente a terceros sin su consentimiento. Es un derecho fundamental del paciente.", choices: [{ id: 'a' as const, text: 'El m\u00e9dico no puede revelar la informaci\u00f3n m\u00e9dica del paciente sin su consentimiento' }, { id: 'b' as const, text: 'El paciente no puede conocer su propio diagn\u00f3stico' }, { id: 'c' as const, text: 'Los resultados m\u00e9dicos se publican para la investigaci\u00f3n' }, { id: 'd' as const, text: 'El empleador tiene acceso al expediente m\u00e9dico del empleado' }] },
  // Q42
  { textFr: "L'inscription à l'Assurance maladie est :", lang: 'es' as const, text: "La inscripci\u00f3n en el Seguro de enfermedad es:", explanation: "La inscripci\u00f3n en el Seguro de enfermedad es obligatoria. Toda persona que trabaja o reside en Francia de manera estable y regular tiene derecho a la cobertura de sus gastos de salud.", choices: [{ id: 'a' as const, text: 'Obligatoria' }, { id: 'b' as const, text: 'Facultativa' }, { id: 'c' as const, text: 'Reservada a los asalariados' }, { id: 'd' as const, text: 'De pago y opcional' }] },
  // Q43
  { textFr: "Qui peut demander un congé parental d'éducation ?", lang: 'es' as const, text: "\u00bfQui\u00e9n puede solicitar un permiso parental de educaci\u00f3n?", explanation: "El permiso parental de educaci\u00f3n puede ser solicitado por el padre o la madre, sin distinci\u00f3n. Permite cesar o reducir su actividad profesional para cuidar de su hijo.", choices: [{ id: 'a' as const, text: 'El padre o la madre' }, { id: 'b' as const, text: 'Solo la madre' }, { id: 'c' as const, text: 'Solo el padre' }, { id: 'd' as const, text: 'Ninguno de los dos, es autom\u00e1tico' }] },
  // Q44
  { textFr: "Quelles sont les affaires traitées par le conseil de prud'hommes ?", lang: 'es' as const, text: "\u00bfQu\u00e9 asuntos trata el consejo de prud'hommes (tribunal laboral)?", explanation: "El consejo de prud'hommes (tribunal laboral) trata los litigios entre empleados y empleadores relacionados con el contrato de trabajo: despido abusivo, impago de salario, acoso laboral, etc.", choices: [{ id: 'a' as const, text: 'Los litigios entre empleados y empleadores relacionados con el contrato de trabajo' }, { id: 'b' as const, text: 'Los asuntos de divorcio' }, { id: 'c' as const, text: 'Las infracciones penales' }, { id: 'd' as const, text: 'Los litigios entre vecinos' }] },
  // Q45
  { textFr: "Lorsqu'un employeur veut qu'un salarié travaille plus longtemps que la durée prévue dans le contrat de travail :", lang: 'es' as const, text: "Cuando un empleador quiere que un empleado trabaje m\u00e1s tiempo del previsto en el contrato de trabajo:", explanation: "Las horas extraordinarias deben ser remuneradas con un aumento de salario o compensadas con un descanso. El empleador no puede imponer horas extraordinarias sin respetar las normas legales.", choices: [{ id: 'a' as const, text: 'Debe remunerar las horas extraordinarias con un aumento' }, { id: 'b' as const, text: 'Puede exigirlo sin compensaci\u00f3n' }, { id: 'c' as const, text: 'El empleado debe rechazar siempre' }, { id: 'd' as const, text: 'Es ilegal en todos los casos' }] },
  // Q46
  { textFr: "Quelle est la mission de France Travail ?", lang: 'es' as const, text: "\u00bfCu\u00e1l es la misi\u00f3n de France Travail?", explanation: "France Travail (anteriormente P\u00f4le emploi) tiene como misi\u00f3n acompa\u00f1ar a los demandantes de empleo en su b\u00fasqueda de trabajo, indemnizar a los desempleados y ayudar a las empresas en sus contrataciones.", choices: [{ id: 'a' as const, text: 'Acompa\u00f1ar a los demandantes de empleo e indemnizar a los desempleados' }, { id: 'b' as const, text: 'Fijar los salarios en las empresas' }, { id: 'c' as const, text: 'Controlar las condiciones de trabajo en las empresas' }, { id: 'd' as const, text: 'Gestionar las jubilaciones de los asalariados' }] },
  // Q47
  { textFr: "Dans une entreprise, le droit syndical permet :", lang: 'es' as const, text: "En una empresa, el derecho sindical permite:", explanation: "El derecho sindical permite a los empleados agruparse para defender sus intereses profesionales. Los sindicatos negocian las condiciones de trabajo y los salarios con el empleador.", choices: [{ id: 'a' as const, text: 'A los empleados agruparse para defender sus intereses profesionales' }, { id: 'b' as const, text: 'Al empleador despedir libremente' }, { id: 'c' as const, text: 'A los empleados no trabajar cuando lo deseen' }, { id: 'd' as const, text: 'Al Estado controlar la empresa' }] },
  // Q48
  { textFr: "Dans une entreprise, le droit de grève autorise :", lang: 'es' as const, text: "En una empresa, el derecho de huelga autoriza:", explanation: "El derecho de huelga, reconocido por la Constituci\u00f3n, autoriza a los empleados a cesar colectivamente el trabajo para defender sus reivindicaciones profesionales. Es un derecho fundamental en Francia.", choices: [{ id: 'a' as const, text: 'A los empleados a cesar colectivamente el trabajo para defender sus reivindicaciones' }, { id: 'b' as const, text: 'Al empleador a cerrar la empresa sin preaviso' }, { id: 'c' as const, text: 'A los empleados a destruir el material de la empresa' }, { id: 'd' as const, text: 'A los empleados a no volver nunca m\u00e1s a trabajar' }] },
  // Q49
  { textFr: "Quelles sont les conditions pour toucher les allocations chômage ?", lang: 'es' as const, text: "\u00bfCu\u00e1les son las condiciones para recibir las prestaciones por desempleo?", explanation: "Para recibir las prestaciones por desempleo, hay que haber trabajado el tiempo suficiente (al menos 6 meses en los \u00faltimos 24 meses), estar inscrito en France Travail y buscar activamente empleo.", choices: [{ id: 'a' as const, text: 'Haber trabajado lo suficiente, estar inscrito en France Travail y buscar activamente empleo' }, { id: 'b' as const, text: 'Basta con no tener empleo' }, { id: 'c' as const, text: 'Tener la nacionalidad francesa' }, { id: 'd' as const, text: 'Tener m\u00e1s de 25 a\u00f1os' }] },
  // Q50
  { textFr: "Qu'est-ce que l'école maternelle ?", lang: 'es' as const, text: "\u00bfQu\u00e9 es la escuela maternal?", explanation: "La escuela maternal acoge a los ni\u00f1os de 3 a 6 a\u00f1os. Constituye la primera etapa de la escolaridad y prepara a los ni\u00f1os para los aprendizajes fundamentales de la escuela primaria.", choices: [{ id: 'a' as const, text: 'La escuela que acoge a los ni\u00f1os de 3 a 6 a\u00f1os' }, { id: 'b' as const, text: 'Una escuela reservada a las ni\u00f1as' }, { id: 'c' as const, text: 'Un establecimiento para los ni\u00f1os de 6 a 11 a\u00f1os' }, { id: 'd' as const, text: 'Una guarder\u00eda gestionada por el Estado' }] },
  // Q51
  { textFr: "Comment s'appelle le diplôme passé par les élèves à la fin du collège ?", lang: 'es' as const, text: "\u00bfC\u00f3mo se llama el diploma que obtienen los alumnos al final del coll\u00e8ge?", explanation: "El diploma nacional del brevet (DNB), com\u00fanmente llamado brevet des coll\u00e8ges, se obtiene al final de la clase de 3\u00e8me. Eval\u00faa los conocimientos adquiridos durante la escolaridad en el coll\u00e8ge.", choices: [{ id: 'a' as const, text: 'El diploma nacional del brevet (brevet des coll\u00e8ges)' }, { id: 'b' as const, text: 'El bachillerato (baccalaur\u00e9at)' }, { id: 'c' as const, text: 'El certificado de estudios primarios' }, { id: 'd' as const, text: 'El CAP' }] },
  // Q52
  { textFr: "Les parents d'élève ont le droit de :", lang: 'es' as const, text: "Los padres de alumnos tienen el derecho de:", explanation: "Los padres de alumnos tienen el derecho de participar en la vida de la escuela, especialmente eligiendo representantes de padres de alumnos y participando en los consejos de escuela o de clase.", choices: [{ id: 'a' as const, text: 'Participar en la vida de la escuela y elegir representantes de padres' }, { id: 'b' as const, text: 'Elegir a los profesores de su hijo' }, { id: 'c' as const, text: 'Modificar el programa escolar' }, { id: 'd' as const, text: 'Decidir los horarios de clase' }] },
  // Q53
  { textFr: "Qui peut manger à la cantine scolaire ?", lang: 'es' as const, text: "\u00bfQui\u00e9n puede comer en el comedor escolar?", explanation: "Todos los alumnos inscritos en el establecimiento pueden comer en el comedor escolar. El acceso al comedor escolar es un derecho para todos los ni\u00f1os escolarizados, sin discriminaci\u00f3n.", choices: [{ id: 'a' as const, text: 'Todos los alumnos inscritos en el establecimiento' }, { id: 'b' as const, text: 'Solo los alumnos cuyos padres trabajan' }, { id: 'c' as const, text: 'Solo los alumnos que viven lejos de la escuela' }, { id: 'd' as const, text: 'Solo los alumnos becados' }] },
  // Q54
  { textFr: "À quel âge commence l'instruction obligatoire des enfants ?", lang: 'es' as const, text: "\u00bfA qu\u00e9 edad comienza la instrucci\u00f3n obligatoria de los ni\u00f1os?", explanation: "Desde la ley del 26 de julio de 2019, la instrucci\u00f3n es obligatoria a partir de los 3 a\u00f1os en Francia. Esto corresponde a la entrada en la escuela maternal.", choices: [{ id: 'a' as const, text: '3 a\u00f1os' }, { id: 'b' as const, text: '5 a\u00f1os' }, { id: 'c' as const, text: '6 a\u00f1os' }, { id: 'd' as const, text: '4 a\u00f1os' }] },
  // Q55
  { textFr: "Quel est l'âge de la majorité ?", lang: 'es' as const, text: "\u00bfCu\u00e1l es la edad de la mayor\u00eda de edad?", explanation: "La edad de la mayor\u00eda de edad en Francia es 18 a\u00f1os. A esa edad, una persona adquiere plena capacidad jur\u00eddica: puede votar, firmar contratos, casarse sin autorizaci\u00f3n parental, etc.", choices: [{ id: 'a' as const, text: '18 a\u00f1os' }, { id: 'b' as const, text: '16 a\u00f1os' }, { id: 'c' as const, text: '21 a\u00f1os' }, { id: 'd' as const, text: '17 a\u00f1os' }] },
  // Q56
  { textFr: "À l'école, il est interdit aux parents de :", lang: 'es' as const, text: "En la escuela, est\u00e1 prohibido a los padres:", explanation: "En la escuela, los padres no pueden oponerse a la ense\u00f1anza de ciertas materias obligatorias del programa escolar. El contenido pedag\u00f3gico es definido por Educaci\u00f3n Nacional y se impone a todos.", choices: [{ id: 'a' as const, text: 'Oponerse a la ense\u00f1anza de ciertas materias obligatorias' }, { id: 'b' as const, text: 'Participar en las reuniones de padres y profesores' }, { id: 'c' as const, text: 'Consultar el cuaderno de textos de su hijo' }, { id: 'd' as const, text: 'Reunirse con los profesores de su hijo' }] },
  // Q57
  { textFr: "Quel motif d'absence est accepté par l'école ?", lang: 'es' as const, text: "\u00bfQu\u00e9 motivo de ausencia es aceptado por la escuela?", explanation: "La enfermedad del ni\u00f1o (con certificado m\u00e9dico) es un motivo de ausencia leg\u00edtimo aceptado por la escuela. Otros motivos aceptados incluyen las obligaciones familiares imperiosas o las fiestas religiosas.", choices: [{ id: 'a' as const, text: 'La enfermedad del ni\u00f1o' }, { id: 'b' as const, text: 'Un viaje de vacaciones en familia' }, { id: 'c' as const, text: 'Las rebajas en las tiendas' }, { id: 'd' as const, text: 'El cansancio del ni\u00f1o' }] },
  // Q58
  { textFr: "Des parents ne respectent pas l'obligation d'instruction pour leurs enfants. Quelle sanction maximale risquent-ils ?", lang: 'es' as const, text: "Unos padres no respetan la obligaci\u00f3n de instrucci\u00f3n para sus hijos. \u00bfQu\u00e9 sanci\u00f3n m\u00e1xima arriesgan?", explanation: "Los padres que no respetan la obligaci\u00f3n de instrucci\u00f3n de sus hijos arriesgan hasta 2 a\u00f1os de prisi\u00f3n y 30.000 euros de multa. La instrucci\u00f3n es una obligaci\u00f3n legal en Francia.", choices: [{ id: 'a' as const, text: '2 a\u00f1os de prisi\u00f3n y 30.000 euros de multa' }, { id: 'b' as const, text: 'Una simple advertencia del ayuntamiento' }, { id: 'c' as const, text: 'Una multa de 150 euros' }, { id: 'd' as const, text: 'Ninguna sanci\u00f3n est\u00e1 prevista' }] },
  // Q59
  { textFr: "Quand ont lieu les vacances scolaires de Noël ?", lang: 'es' as const, text: "\u00bfCu\u00e1ndo tienen lugar las vacaciones escolares de Navidad?", explanation: "Las vacaciones escolares de Navidad tienen lugar en diciembre-enero, generalmente durante dos semanas alrededor del 25 de diciembre y del 1 de enero. Son comunes a todas las zonas escolares.", choices: [{ id: 'a' as const, text: 'En diciembre-enero, durante aproximadamente dos semanas' }, { id: 'b' as const, text: 'En noviembre, durante una semana' }, { id: 'c' as const, text: 'En febrero, durante dos semanas' }, { id: 'd' as const, text: 'En octubre, durante una semana' }] },
  // Q60
  { textFr: "À l'école, un enfant en situation de handicap :", lang: 'es' as const, text: "En la escuela, un ni\u00f1o en situaci\u00f3n de discapacidad:", explanation: "En Francia, un ni\u00f1o en situaci\u00f3n de discapacidad tiene derecho a ser inscrito en la escuela m\u00e1s cercana a su domicilio. La escuela inclusiva es un principio fundamental: cada ni\u00f1o tiene derecho a una escolarizaci\u00f3n adaptada.", choices: [{ id: 'a' as const, text: 'Tiene derecho a ser inscrito en la escuela m\u00e1s cercana a su domicilio' }, { id: 'b' as const, text: 'Debe obligatoriamente ir a un establecimiento especializado' }, { id: 'c' as const, text: 'No puede ser escolarizado' }, { id: 'd' as const, text: 'Debe quedarse en casa con un profesor privado' }] },
  // Q61
  { textFr: "Quelle action peut réaliser le locataire d'un logement sans l'autorisation du propriétaire ?", lang: 'es' as const, text: "\u00bfQu\u00e9 acci\u00f3n puede realizar el inquilino de una vivienda sin la autorizaci\u00f3n del propietario?", explanation: "El inquilino puede realizar peque\u00f1as mejoras (decoraci\u00f3n, pintura, peque\u00f1as obras) sin pedir autorizaci\u00f3n al propietario, siempre y cuando no transforme la vivienda de manera estructural.", choices: [{ id: 'a' as const, text: 'Hacer peque\u00f1as mejoras como pintar las paredes o colocar estanter\u00edas' }, { id: 'b' as const, text: 'Derribar un tabique' }, { id: 'c' as const, text: 'Subalquilar la vivienda a otra persona' }, { id: 'd' as const, text: 'Cambiar las ventanas y la puerta de entrada' }] },
  // Q62
  { textFr: "Le stationnement sur une place réservée aux personnes handicapées :", lang: 'es' as const, text: "El estacionamiento en una plaza reservada a personas con discapacidad:", explanation: "El estacionamiento en una plaza reservada a personas con discapacidad est\u00e1 prohibido sin la tarjeta de movilidad de inclusi\u00f3n (CMI). Los infractores se exponen a una multa de 135 euros y a la retirada de su veh\u00edculo al dep\u00f3sito.", choices: [{ id: 'a' as const, text: 'Est\u00e1 prohibido sin tarjeta de movilidad de inclusi\u00f3n y es sancionable con multa' }, { id: 'b' as const, text: 'Est\u00e1 autorizado para todos los domingos' }, { id: 'c' as const, text: 'Est\u00e1 autorizado si es por un corto periodo' }, { id: 'd' as const, text: 'No est\u00e1 regulado por la ley' }] },
  // Q63
  { textFr: "Si une machine à laver est cassée, il est possible de :", lang: 'es' as const, text: "Si una lavadora est\u00e1 rota, es posible:", explanation: "Un electrodom\u00e9stico roto puede depositarse en un punto limpio o ser recogido por la tienda al comprar un nuevo aparato (obligaci\u00f3n de recogida 1 por 1). No se debe tirar con la basura dom\u00e9stica.", choices: [{ id: 'a' as const, text: 'Depositarla en un punto limpio o hacerla recoger por una tienda' }, { id: 'b' as const, text: 'Tirarla en el cubo de basura dom\u00e9stica' }, { id: 'c' as const, text: 'Dejarla en la acera' }, { id: 'd' as const, text: 'Tirarla en un contenedor de reciclaje' }] },
  // Q64
  { textFr: "Dans quel cas faut-il déclarer son enfant au service d'état civil ?", lang: 'es' as const, text: "\u00bfEn qu\u00e9 caso hay que declarar a su hijo en el servicio de registro civil?", explanation: "Hay que declarar a su hijo en el servicio de registro civil del ayuntamiento en cada nacimiento. Esta declaraci\u00f3n es obligatoria dentro de los 5 d\u00edas siguientes al nacimiento y permite establecer el acta de nacimiento.", choices: [{ id: 'a' as const, text: 'En cada nacimiento de un hijo' }, { id: 'b' as const, text: 'Solo para el primer hijo' }, { id: 'c' as const, text: 'Cuando el ni\u00f1o entra a la escuela' }, { id: 'd' as const, text: 'Cuando el ni\u00f1o cumple 18 a\u00f1os' }] },
  // Q65
  { textFr: "Qui peut demander le divorce de personnes mariées ?", lang: 'es' as const, text: "\u00bfQui\u00e9n puede solicitar el divorcio de personas casadas?", explanation: "El divorcio puede ser solicitado por uno de los c\u00f3nyuges o por ambos juntos (divorcio por consentimiento mutuo). La solicitud de divorcio es un derecho reconocido a cada uno de los c\u00f3nyuges.", choices: [{ id: 'a' as const, text: 'Uno de los c\u00f3nyuges o ambos juntos' }, { id: 'b' as const, text: 'Solo el marido' }, { id: 'c' as const, text: 'Solo la familia de los c\u00f3nyuges' }, { id: 'd' as const, text: 'El alcalde del municipio' }] },
  // Q66
  { textFr: "La contraception :", lang: 'es' as const, text: "La anticoncepci\u00f3n:", explanation: "La anticoncepci\u00f3n es un derecho en Francia. Es accesible para todos, incluidos los menores, y puede obtenerse gratuitamente para los menores de 26 a\u00f1os. La elecci\u00f3n del m\u00e9todo anticonceptivo es libre.", choices: [{ id: 'a' as const, text: 'Es un derecho accesible para todos, incluidos los menores' }, { id: 'b' as const, text: 'Est\u00e1 prohibida en Francia' }, { id: 'c' as const, text: 'Necesita la autorizaci\u00f3n del c\u00f3nyuge' }, { id: 'd' as const, text: 'Est\u00e1 reservada a las personas casadas' }] },
  // Q67
  { textFr: "Qu'est-ce que le tiers payant ?", lang: 'es' as const, text: "\u00bfQu\u00e9 es el pago por terceros (tiers payant)?", explanation: "El pago por terceros es un sistema que exime al paciente de adelantar los gastos de salud. El profesional de salud es pagado directamente por el Seguro de enfermedad y/o la mutua.", choices: [{ id: 'a' as const, text: 'Un sistema que exime al paciente de adelantar los gastos de salud' }, { id: 'b' as const, text: 'Un impuesto sobre los medicamentos' }, { id: 'c' as const, text: 'Un suplemento a pagar durante una consulta' }, { id: 'd' as const, text: 'Un seguro obligatorio para los m\u00e9dicos' }] },
  // Q68
  { textFr: "L'avortement est-il possible en France ?", lang: 'es' as const, text: "\u00bfEs posible el aborto en Francia?", explanation: "S\u00ed, el aborto (IVG - Interrupci\u00f3n Voluntaria del Embarazo) es legal en Francia. Desde 2022, puede practicarse hasta las 14 semanas de embarazo. Es un derecho constitucional desde 2024.", choices: [{ id: 'a' as const, text: 'S\u00ed, es un derecho garantizado por la ley' }, { id: 'b' as const, text: 'No, est\u00e1 totalmente prohibido' }, { id: 'c' as const, text: 'Solo en caso de peligro para la madre' }, { id: 'd' as const, text: 'Solo con el acuerdo del c\u00f3nyuge' }] },
  // Q69
  { textFr: "Quels sont les textes qui définissent les règles au travail ?", lang: 'es' as const, text: "\u00bfCu\u00e1les son los textos que definen las normas en el trabajo?", explanation: "Las normas en el trabajo est\u00e1n definidas por el C\u00f3digo del Trabajo, los convenios colectivos y el contrato de trabajo. El C\u00f3digo del Trabajo fija el marco legal m\u00ednimo que todo empleador debe respetar.", choices: [{ id: 'a' as const, text: 'El C\u00f3digo del Trabajo, los convenios colectivos y el contrato de trabajo' }, { id: 'b' as const, text: 'Solo el reglamento interno de la empresa' }, { id: 'c' as const, text: 'Las decisiones del alcalde del municipio' }, { id: 'd' as const, text: 'Los acuerdos verbales entre colegas' }] },
  // Q70
  { textFr: "Qui a le droit de se syndiquer ?", lang: 'es' as const, text: "\u00bfQui\u00e9n tiene derecho a sindicarse?", explanation: "Todo empleado tiene derecho a sindicarse, sin importar su nacionalidad. La libertad sindical es un derecho fundamental reconocido por la Constituci\u00f3n francesa y los convenios internacionales.", choices: [{ id: 'a' as const, text: 'Todo empleado, sin importar su nacionalidad' }, { id: 'b' as const, text: 'Solo los empleados franceses' }, { id: 'c' as const, text: 'Solo los directivos' }, { id: 'd' as const, text: 'Solo los funcionarios' }] },
  // Q71
  { textFr: "Est-il possible de licencier une femme enceinte ou en congé maternité, en raison de sa grossesse ?", lang: 'es' as const, text: "\u00bfEs posible despedir a una mujer embarazada o en permiso de maternidad, por raz\u00f3n de su embarazo?", explanation: "No, est\u00e1 prohibido despedir a una mujer por raz\u00f3n de su embarazo o durante su permiso de maternidad. La ley protege a las mujeres embarazadas contra toda discriminaci\u00f3n relacionada con la maternidad.", choices: [{ id: 'a' as const, text: 'No, est\u00e1 prohibido por la ley' }, { id: 'b' as const, text: 'S\u00ed, el empleador es libre de despedir a quien quiera' }, { id: 'c' as const, text: 'S\u00ed, pero con un preaviso de 3 meses' }, { id: 'd' as const, text: 'S\u00ed, si la empresa tiene dificultades econ\u00f3micas' }] },
  // Q72
  { textFr: "L'instruction des enfants est obligatoire de :", lang: 'es' as const, text: "La instrucci\u00f3n de los ni\u00f1os es obligatoria de:", explanation: "La instrucci\u00f3n de los ni\u00f1os es obligatoria de 3 a 16 a\u00f1os en Francia. Esta obligaci\u00f3n se aplica a todos los ni\u00f1os que residen en el territorio franc\u00e9s, sin importar su nacionalidad.", choices: [{ id: 'a' as const, text: '3 a\u00f1os a 16 a\u00f1os' }, { id: 'b' as const, text: '6 a\u00f1os a 16 a\u00f1os' }, { id: 'c' as const, text: '3 a\u00f1os a 18 a\u00f1os' }, { id: 'd' as const, text: '5 a\u00f1os a 14 a\u00f1os' }] },
  // Q73
  { textFr: "Quelle est la définition de l'autorité parentale ?", lang: 'es' as const, text: "\u00bfCu\u00e1l es la definici\u00f3n de la autoridad parental?", explanation: "La autoridad parental es el conjunto de derechos y deberes de los padres hacia su hijo menor. Tiene como finalidad el inter\u00e9s del ni\u00f1o: su protecci\u00f3n, su salud, su seguridad, su educaci\u00f3n y su desarrollo.", choices: [{ id: 'a' as const, text: 'El conjunto de derechos y deberes de los padres para proteger y educar a su hijo' }, { id: 'b' as const, text: 'El derecho de los padres a castigar libremente a su hijo' }, { id: 'c' as const, text: 'El poder del Estado sobre las familias' }, { id: 'd' as const, text: 'El derecho de los abuelos sobre sus nietos' }] },
  // Q74
  { textFr: "En tant que parent d'élève, il est possible de :", lang: 'es' as const, text: "Como padre de alumno, es posible:", explanation: "Como padre de alumno, es posible participar en las instancias de la escuela (consejo de escuela, consejo de clase) y ser elegido representante de padres de alumnos para hacer o\u00edr su voz.", choices: [{ id: 'a' as const, text: 'Participar en las instancias de la escuela y ser elegido representante de padres' }, { id: 'b' as const, text: 'Elegir las materias ense\u00f1adas a su hijo' }, { id: 'c' as const, text: 'Decidir el paso al curso superior de su hijo' }, { id: 'd' as const, text: 'Sustituir a un profesor ausente' }] },
  // Q75
  { textFr: "Quelle instruction est prévue pour les enfants qui ne parlent pas français ?", lang: 'es' as const, text: "\u00bfQu\u00e9 instrucci\u00f3n est\u00e1 prevista para los ni\u00f1os que no hablan franc\u00e9s?", explanation: "Los ni\u00f1os al\u00f3fonos (que no hablan franc\u00e9s) se benefician de una ense\u00f1anza espec\u00edfica de franc\u00e9s en unidades pedag\u00f3gicas (UPE2A) mientras est\u00e1n inscritos en una clase ordinaria correspondiente a su edad.", choices: [{ id: 'a' as const, text: 'Una ense\u00f1anza espec\u00edfica de franc\u00e9s (UPE2A) en paralelo a una clase ordinaria' }, { id: 'b' as const, text: 'Ninguna, deben aprender solos' }, { id: 'c' as const, text: 'Son devueltos a su pa\u00eds de origen' }, { id: 'd' as const, text: 'Son colocados en escuelas especializadas separadas' }] },
  // Q76
  { textFr: "S'agissant de l'accueil des enfants en situation de handicap à l'école, laquelle des propositions est vraie ?", lang: 'es' as const, text: "Respecto a la acogida de ni\u00f1os en situaci\u00f3n de discapacidad en la escuela, \u00bfcu\u00e1l de las propuestas es verdadera?", explanation: "La escuela inclusiva es un derecho en Francia. Todo ni\u00f1o en situaci\u00f3n de discapacidad puede ser escolarizado en la escuela de su barrio con adaptaciones adecuadas (AESH, material especializado, etc.).", choices: [{ id: 'a' as const, text: 'Todo ni\u00f1o con discapacidad tiene derecho a ser escolarizado en medio ordinario con adaptaciones' }, { id: 'b' as const, text: 'Los ni\u00f1os con discapacidad no pueden ir a la escuela' }, { id: 'c' as const, text: 'Solo los ni\u00f1os con discapacidad leve pueden ir a la escuela' }, { id: 'd' as const, text: 'Los ni\u00f1os con discapacidad deben ir a otro departamento' }] },
  // Q77
  { textFr: "Depuis le 1er juillet 2021, quelle est la durée du congé paternité ?", lang: 'es' as const, text: "Desde el 1 de julio de 2021, \u00bfcu\u00e1l es la duraci\u00f3n del permiso de paternidad?", explanation: "Desde el 1 de julio de 2021, el permiso de paternidad es de 25 d\u00edas naturales (32 d\u00edas en caso de nacimientos m\u00faltiples). Esta reforma duplic\u00f3 la duraci\u00f3n anterior de 11 d\u00edas.", choices: [{ id: 'a' as const, text: '25 d\u00edas naturales' }, { id: 'b' as const, text: '11 d\u00edas naturales' }, { id: 'c' as const, text: '14 d\u00edas naturales' }, { id: 'd' as const, text: '30 d\u00edas naturales' }] },
  // Q78
  { textFr: "Est-ce possible de punir physiquement ses enfants ?", lang: 'es' as const, text: "\u00bfEs posible castigar f\u00edsicamente a sus hijos?", explanation: "No, la violencia f\u00edsica contra los ni\u00f1os est\u00e1 prohibida en Francia. Desde la ley del 10 de julio de 2019, toda violencia educativa ordinaria (azote, bofetada, etc.) est\u00e1 prohibida. La autoridad parental se ejerce sin violencia.", choices: [{ id: 'a' as const, text: 'No, toda violencia f\u00edsica contra los ni\u00f1os est\u00e1 prohibida' }, { id: 'b' as const, text: 'S\u00ed, si es por razones educativas' }, { id: 'c' as const, text: 'S\u00ed, siempre que no deje marcas' }, { id: 'd' as const, text: 'S\u00ed, es un derecho de los padres' }] },
];
