export const theme4Ar = [
  // Q1
  { textFr: "En quelle année a débuté la Révolution française ?", lang: 'ar' as const, text: "في أي سنة بدأت الثورة الفرنسية؟", explanation: "بدأت الثورة الفرنسية عام 1789 مع اقتحام سجن الباستيل في 14 يوليو. يمثل هذا الحدث نهاية النظام القديم وبداية حقبة من التغييرات السياسية والاجتماعية العميقة في فرنسا.", choices: [{ id: 'a' as const, text: "1789" }, { id: 'b' as const, text: "1799" }, { id: 'c' as const, text: "1776" }, { id: 'd' as const, text: "1815" }] },
  // Q2
  { textFr: "Qui était Napoléon Ier ?", lang: 'ar' as const, text: "من كان نابليون الأول؟", explanation: "كان نابليون الأول إمبراطور الفرنسيين من 1804 إلى 1814 ثم لفترة وجيزة عام 1815. قام بتحديث الإدارة الفرنسية وأسس القانون المدني الذي لا يزال ساريًا حتى اليوم.", choices: [{ id: 'a' as const, text: "أول إمبراطور للفرنسيين" }, { id: 'b' as const, text: "آخر ملوك فرنسا" }, { id: 'c' as const, text: "مؤسس الجمهورية الخامسة" }, { id: 'd' as const, text: "جنرال في الحرب العالمية الأولى" }] },
  // Q3
  { textFr: "Lequel de ces personnages historiques est français ?", lang: 'ar' as const, text: "أي من هذه الشخصيات التاريخية فرنسي؟", explanation: "جان دارك هي شخصية رمزية في تاريخ فرنسا. قادت الجيوش الفرنسية ضد الإنجليز خلال حرب المئة عام في القرن الخامس عشر.", choices: [{ id: 'a' as const, text: "جان دارك" }, { id: 'b' as const, text: "كريستوفر كولومبوس" }, { id: 'c' as const, text: "ونستون تشرشل" }, { id: 'd' as const, text: "ليوناردو دافنشي" }] },
  // Q4
  { textFr: "Dans quelle République est-on aujourd'hui ?", lang: 'ar' as const, text: "في أي جمهورية نعيش اليوم؟", explanation: "فرنسا حاليًا تحت الجمهورية الخامسة التي أُسست عام 1958 على يد الجنرال ديغول. عززت هذه الجمهورية سلطة رئيس الجمهورية.", choices: [{ id: 'a' as const, text: "الجمهورية الخامسة" }, { id: 'b' as const, text: "الجمهورية الرابعة" }, { id: 'c' as const, text: "الجمهورية الثالثة" }, { id: 'd' as const, text: "الجمهورية السادسة" }] },
  // Q5
  { textFr: "Qu'est-ce que la Shoah ?", lang: 'ar' as const, text: "ما هي الهولوكوست (الشواه)؟", explanation: "تشير الشواه إلى إبادة يهود أوروبا على يد ألمانيا النازية خلال الحرب العالمية الثانية. تم إبادة حوالي ستة ملايين يهودي بين عامي 1941 و1945.", choices: [{ id: 'a' as const, text: "إبادة اليهود خلال الحرب العالمية الثانية" }, { id: 'b' as const, text: "معركة من الحرب العالمية الأولى" }, { id: 'c' as const, text: "معاهدة سلام أوروبية" }, { id: 'd' as const, text: "المقاومة الفرنسية ضد الاحتلال" }] },
  // Q6
  { textFr: "Quel pays ou région du monde a été colonisé par la France ?", lang: 'ar' as const, text: "أي بلد أو منطقة في العالم استعمرتها فرنسا؟", explanation: "استعمرت فرنسا الجزائر من 1830 إلى 1962. كانت أهم مستعمرة فرنسية في شمال أفريقيا وحصلت على استقلالها بعد حرب طويلة.", choices: [{ id: 'a' as const, text: "الجزائر" }, { id: 'b' as const, text: "البرازيل" }, { id: 'c' as const, text: "الهند" }, { id: 'd' as const, text: "أستراليا" }] },
  // Q7
  { textFr: "Qui a rendu l'école gratuite, laïque et obligatoire ?", lang: 'ar' as const, text: "من جعل المدرسة مجانية وعلمانية وإلزامية؟", explanation: "جول فيري، وزير التعليم العام، أصدر قوانين 1881-1882 التي جعلت التعليم الابتدائي مجانيًا وعلمانيًا وإلزاميًا. هذه القوانين ركيزة أساسية للجمهورية الفرنسية.", choices: [{ id: 'a' as const, text: "جول فيري" }, { id: 'b' as const, text: "فيكتور هوغو" }, { id: 'c' as const, text: "نابليون بونابرت" }, { id: 'd' as const, text: "شارل ديغول" }] },
  // Q8
  { textFr: "Quand a eu lieu la Seconde Guerre mondiale ?", lang: 'ar' as const, text: "متى وقعت الحرب العالمية الثانية؟", explanation: "وقعت الحرب العالمية الثانية من 1939 إلى 1945. شمل هذا الصراع العالمي معظم الأمم وتسبب في ملايين الضحايا.", choices: [{ id: 'a' as const, text: "1939-1945" }, { id: 'b' as const, text: "1914-1918" }, { id: 'c' as const, text: "1870-1871" }, { id: 'd' as const, text: "1950-1953" }] },
  // Q9
  { textFr: "Quand a eu lieu la Première Guerre mondiale ?", lang: 'ar' as const, text: "متى وقعت الحرب العالمية الأولى؟", explanation: "وقعت الحرب العالمية الأولى من 1914 إلى 1918. واجه هذا الصراع بشكل رئيسي قوى الوفاق الثلاثي ضد الإمبراطوريات المركزية.", choices: [{ id: 'a' as const, text: "1914-1918" }, { id: 'b' as const, text: "1939-1945" }, { id: 'c' as const, text: "1870-1871" }, { id: 'd' as const, text: "1899-1902" }] },
  // Q10
  { textFr: "En quelle année a été créée la Communauté Économique Européenne (CEE) ?", lang: 'ar' as const, text: "في أي سنة تم إنشاء المجموعة الاقتصادية الأوروبية؟", explanation: "تم إنشاء المجموعة الاقتصادية الأوروبية عام 1957 بموجب معاهدة روما التي وقعتها ست دول مؤسسة من بينها فرنسا. وهي سلف الاتحاد الأوروبي الحالي.", choices: [{ id: 'a' as const, text: "1957" }, { id: 'b' as const, text: "1945" }, { id: 'c' as const, text: "1962" }, { id: 'd' as const, text: "1951" }] },
  // Q11
  { textFr: "Le 11 novembre est un jour férié. À quoi correspond cette date ?", lang: 'ar' as const, text: "الحادي عشر من نوفمبر هو يوم عطلة رسمية. بماذا يتعلق هذا التاريخ؟", explanation: "يمثل 11 نوفمبر 1918 الهدنة في الحرب العالمية الأولى. يحيي هذا اليوم ذكرى نهاية القتال ويكرّم الجنود الذين ماتوا من أجل فرنسا.", choices: [{ id: 'a' as const, text: "هدنة الحرب العالمية الأولى" }, { id: 'b' as const, text: "نهاية الحرب العالمية الثانية" }, { id: 'c' as const, text: "العيد الوطني الفرنسي" }, { id: 'd' as const, text: "إعلان الجمهورية" }] },
  // Q12
  { textFr: "Qui a été le premier Président élu sous la Ve République ?", lang: 'ar' as const, text: "من كان أول رئيس منتخب في ظل الجمهورية الخامسة؟", explanation: "كان شارل ديغول أول رئيس للجمهورية الخامسة، انتُخب عام 1958. وهو مؤسس هذا النظام وشغل فترتين رئاسيتين.", choices: [{ id: 'a' as const, text: "شارل ديغول" }, { id: 'b' as const, text: "فرانسوا ميتران" }, { id: 'c' as const, text: "جورج بومبيدو" }, { id: 'd' as const, text: "رينيه كوتي" }] },
  // Q13
  { textFr: "En quelle année l'esclavage a-t-il été aboli définitivement en France ?", lang: 'ar' as const, text: "في أي سنة تم إلغاء العبودية نهائيًا في فرنسا؟", explanation: "تم إلغاء العبودية نهائيًا في فرنسا عام 1848 بفضل فيكتور شولشر. كان قد صدر مرسوم أول للإلغاء عام 1794 لكن نابليون أعاد العمل بها عام 1802.", choices: [{ id: 'a' as const, text: "1848" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1865" }, { id: 'd' as const, text: "1794" }] },
  // Q14
  { textFr: "Depuis quelle année l'école publique est-elle gratuite ?", lang: 'ar' as const, text: "منذ أي سنة أصبحت المدرسة العامة مجانية؟", explanation: "أصبحت المدرسة العامة مجانية منذ عام 1881 بفضل قوانين جول فيري. جعلت هذه القوانين أيضًا التعليم الابتدائي إلزاميًا وعلمانيًا.", choices: [{ id: 'a' as const, text: "1881" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1905" }, { id: 'd' as const, text: "1848" }] },
  // Q15
  { textFr: "Combien y a-t-il eu de républiques en France ?", lang: 'ar' as const, text: "كم عدد الجمهوريات التي عرفتها فرنسا؟", explanation: "عرفت فرنسا خمس جمهوريات. أُعلنت الجمهورية الأولى عام 1792 والجمهورية الخامسة التي أُسست عام 1958 هي النظام الحالي.", choices: [{ id: 'a' as const, text: "خمس" }, { id: 'b' as const, text: "ثلاث" }, { id: 'c' as const, text: "أربع" }, { id: 'd' as const, text: "ست" }] },
  // Q16
  { textFr: "Qui était le roi de France au moment de la Révolution française ?", lang: 'ar' as const, text: "من كان ملك فرنسا وقت الثورة الفرنسية؟", explanation: "كان لويس السادس عشر ملك فرنسا أثناء الثورة الفرنسية عام 1789. تمت الإطاحة به ثم إعدامه بالمقصلة عام 1793.", choices: [{ id: 'a' as const, text: "لويس السادس عشر" }, { id: 'b' as const, text: "لويس الرابع عشر" }, { id: 'c' as const, text: "لويس الخامس عشر" }, { id: 'd' as const, text: "هنري الرابع" }] },
  // Q17
  { textFr: "Qui a fondé la Ve République ?", lang: 'ar' as const, text: "من أسس الجمهورية الخامسة؟", explanation: "أسس الجنرال شارل ديغول الجمهورية الخامسة عام 1958. كان أول رئيس لها ووضع دستورًا يعزز السلطة التنفيذية.", choices: [{ id: 'a' as const, text: "الجنرال ديغول" }, { id: 'b' as const, text: "فرانسوا ميتران" }, { id: 'c' as const, text: "نابليون الثالث" }, { id: 'd' as const, text: "ليون بلوم" }] },
  // Q18
  { textFr: "Que célèbre-t-on le 14 juillet ?", lang: 'ar' as const, text: "ماذا نحتفل في 14 يوليو؟", explanation: "الرابع عشر من يوليو هو العيد الوطني الفرنسي. يحيي ذكرى اقتحام الباستيل عام 1789 وعيد الاتحاد عام 1790 كرمزين للحرية والوحدة الوطنية.", choices: [{ id: 'a' as const, text: "العيد الوطني، ذكرى اقتحام الباستيل" }, { id: 'b' as const, text: "هدنة 1918" }, { id: 'c' as const, text: "نهاية الحرب العالمية الثانية" }, { id: 'd' as const, text: "إلغاء العبودية" }] },
  // Q19
  { textFr: "Quelle guerre a eu lieu entre 1914 et 1918 ?", lang: 'ar' as const, text: "أي حرب وقعت بين 1914 و1918؟", explanation: "وقعت الحرب العالمية الأولى من 1914 إلى 1918. واجهت الحلفاء ضد الإمبراطوريات المركزية وأسفرت عن ملايين القتلى.", choices: [{ id: 'a' as const, text: "الحرب العالمية الأولى" }, { id: 'b' as const, text: "الحرب العالمية الثانية" }, { id: 'c' as const, text: "الحرب الفرنسية البروسية" }, { id: 'd' as const, text: "حرب الجزائر" }] },
  // Q20
  { textFr: "Pourquoi l'année 1958 est importante pour la France ?", lang: 'ar' as const, text: "لماذا يعتبر عام 1958 مهمًا لفرنسا؟", explanation: "يمثل عام 1958 إنشاء الجمهورية الخامسة على يد الجنرال ديغول. تم اعتماد دستور جديد أسس النظام السياسي الحالي لفرنسا.", choices: [{ id: 'a' as const, text: "هو عام إنشاء الجمهورية الخامسة" }, { id: 'b' as const, text: "هو عام نهاية الحرب العالمية الثانية" }, { id: 'c' as const, text: "هو عام إلغاء العبودية" }, { id: 'd' as const, text: "هو عام الثورة الفرنسية" }] },
  // Q21
  { textFr: "Quel fleuve coule en France ?", lang: 'ar' as const, text: "أي نهر يجري في فرنسا؟", explanation: "نهر اللوار هو أطول نهر في فرنسا بطول حوالي 1012 كم. يعبر وسط فرنسا من الكتلة الجبلية المركزية إلى المحيط الأطلسي.", choices: [{ id: 'a' as const, text: "اللوار" }, { id: 'b' as const, text: "الدانوب" }, { id: 'c' as const, text: "النيل" }, { id: 'd' as const, text: "الأمازون" }] },
  // Q22
  { textFr: "Quelle ville est française ?", lang: 'ar' as const, text: "أي مدينة فرنسية؟", explanation: "ليون مدينة فرنسية كبيرة وعاصمة منطقة أوفيرن-رون-ألب. وهي ثالث أكبر مدينة في فرنسا بعد باريس ومرسيليا.", choices: [{ id: 'a' as const, text: "ليون" }, { id: 'b' as const, text: "جنيف" }, { id: 'c' as const, text: "بروكسل" }, { id: 'd' as const, text: "برشلونة" }] },
  // Q23
  { textFr: "Quel océan borde la côte ouest française ?", lang: 'ar' as const, text: "أي محيط يحد الساحل الغربي الفرنسي؟", explanation: "يحد المحيط الأطلسي الساحل الغربي لفرنسا الحضرية. من بريتاني إلى بلاد الباسك تمتد هذه الواجهة البحرية على مئات الكيلومترات.", choices: [{ id: 'a' as const, text: "المحيط الأطلسي" }, { id: 'b' as const, text: "المحيط الهادئ" }, { id: 'c' as const, text: "المحيط الهندي" }, { id: 'd' as const, text: "المحيط المتجمد الشمالي" }] },
  // Q24
  { textFr: "Qu'est-ce que Paris ?", lang: 'ar' as const, text: "ما هي باريس؟", explanation: "باريس هي عاصمة فرنسا ومركزها السياسي والاقتصادي والثقافي. وهي أيضًا المدينة الأكثر اكتظاظًا بالسكان في البلاد.", choices: [{ id: 'a' as const, text: "عاصمة فرنسا" }, { id: 'b' as const, text: "منطقة في فرنسا" }, { id: 'c' as const, text: "إقليم ما وراء البحار" }, { id: 'd' as const, text: "عاصمة أوروبا" }] },
  // Q25
  { textFr: "Quelle est la capitale de la France ?", lang: 'ar' as const, text: "ما هي عاصمة فرنسا؟", explanation: "باريس هي عاصمة فرنسا منذ قرون. تضم المؤسسات الرئيسية للدولة بما في ذلك قصر الإليزيه والجمعية الوطنية.", choices: [{ id: 'a' as const, text: "باريس" }, { id: 'b' as const, text: "ليون" }, { id: 'c' as const, text: "مرسيليا" }, { id: 'd' as const, text: "ستراسبورغ" }] },
  // Q26
  { textFr: "Sur quel continent se situe la France métropolitaine ?", lang: 'ar' as const, text: "في أي قارة تقع فرنسا الحضرية؟", explanation: "تقع فرنسا الحضرية في القارة الأوروبية. يحدها المحيط الأطلسي من الغرب والبحر الأبيض المتوسط من الجنوب والقنال الإنجليزي من الشمال.", choices: [{ id: 'a' as const, text: "أوروبا" }, { id: 'b' as const, text: "أفريقيا" }, { id: 'c' as const, text: "أمريكا" }, { id: 'd' as const, text: "آسيا" }] },
  // Q27
  { textFr: "Quelle île est un département d'outre-mer français ?", lang: 'ar' as const, text: "أي جزيرة هي إقليم فرنسي فيما وراء البحار؟", explanation: "مارتينيك هي إقليم ومنطقة فرنسية فيما وراء البحار تقع في جزر الأنتيل. وهي جزء لا يتجزأ من الجمهورية الفرنسية.", choices: [{ id: 'a' as const, text: "مارتينيك" }, { id: 'b' as const, text: "كوبا" }, { id: 'c' as const, text: "جامايكا" }, { id: 'd' as const, text: "هايتي" }] },
  // Q28
  { textFr: "Combien y a-t-il de régions en France métropolitaine ?", lang: 'ar' as const, text: "كم عدد المناطق في فرنسا الحضرية؟", explanation: "منذ الإصلاح الإقليمي لعام 2016 تضم فرنسا الحضرية 13 منطقة. تم تقليص العدد من 22 إلى 13 لتعزيز فعالية الهيئات الإقليمية.", choices: [{ id: 'a' as const, text: "13" }, { id: 'b' as const, text: "18" }, { id: 'c' as const, text: "22" }, { id: 'd' as const, text: "10" }] },
  // Q29
  { textFr: "Quelle ville est un grand port maritime ?", lang: 'ar' as const, text: "أي مدينة هي ميناء بحري كبير؟", explanation: "مرسيليا هي أكبر ميناء بحري في فرنسا وأحد أهم الموانئ في البحر الأبيض المتوسط. وهي أيضًا ثاني أكبر مدينة في فرنسا.", choices: [{ id: 'a' as const, text: "مرسيليا" }, { id: 'b' as const, text: "كليرمون فيران" }, { id: 'c' as const, text: "غرونوبل" }, { id: 'd' as const, text: "ليموج" }] },
  // Q30
  { textFr: "Quelle est la mer au sud de la France métropolitaine ?", lang: 'ar' as const, text: "ما هو البحر جنوب فرنسا الحضرية؟", explanation: "يحد البحر الأبيض المتوسط جنوب فرنسا الحضرية. يمتد من الحدود الإسبانية إلى الحدود الإيطالية على طول الريفييرا الفرنسية ولانغدوك.", choices: [{ id: 'a' as const, text: "البحر الأبيض المتوسط" }, { id: 'b' as const, text: "بحر الشمال" }, { id: 'c' as const, text: "بحر البلطيق" }, { id: 'd' as const, text: "القنال الإنجليزي" }] },
  // Q31
  { textFr: "Quelle ville est située au bord de la mer Méditerranée ?", lang: 'ar' as const, text: "أي مدينة تقع على ساحل البحر الأبيض المتوسط؟", explanation: "نيس مدينة تقع على الريفييرا الفرنسية على ساحل البحر الأبيض المتوسط. وهي إحدى أهم الوجهات السياحية في جنوب فرنسا.", choices: [{ id: 'a' as const, text: "نيس" }, { id: 'b' as const, text: "ليل" }, { id: 'c' as const, text: "ستراسبورغ" }, { id: 'd' as const, text: "رين" }] },
  // Q32
  { textFr: "Où se situe la Corse ?", lang: 'ar' as const, text: "أين تقع كورسيكا؟", explanation: "كورسيكا جزيرة تقع في البحر الأبيض المتوسط جنوب شرق فرنسا الحضرية. وهي هيئة إقليمية فريدة ذات وضع خاص.", choices: [{ id: 'a' as const, text: "في البحر الأبيض المتوسط" }, { id: 'b' as const, text: "في المحيط الأطلسي" }, { id: 'c' as const, text: "في القنال الإنجليزي" }, { id: 'd' as const, text: "في بحر الشمال" }] },
  // Q33
  { textFr: "Quelle chaîne de montagnes est située entre la France et l'Italie ?", lang: 'ar' as const, text: "أي سلسلة جبلية تقع بين فرنسا وإيطاليا؟", explanation: "تشكل جبال الألب حدودًا طبيعية بين فرنسا وإيطاليا. جبل مون بلان الواقع في الألب هو أعلى قمة في أوروبا الغربية بارتفاع 4809 أمتار.", choices: [{ id: 'a' as const, text: "جبال الألب" }, { id: 'b' as const, text: "جبال البيرينيه" }, { id: 'c' as const, text: "جبال الجورا" }, { id: 'd' as const, text: "جبال الفوج" }] },
  // Q34
  { textFr: "Qui était Molière ?", lang: 'ar' as const, text: "من كان موليير؟", explanation: "موليير (1622-1673) كان كاتبًا مسرحيًا وممثلًا فرنسيًا من القرن السابع عشر. وهو مؤلف مسرحيات كوميدية شهيرة مثل المريض بالوهم والبخيل.", choices: [{ id: 'a' as const, text: "كاتب مسرحي وممثل فرنسي من القرن السابع عشر" }, { id: 'b' as const, text: "رسام من عصر النهضة" }, { id: 'c' as const, text: "مؤلف موسيقى كلاسيكية" }, { id: 'd' as const, text: "فيلسوف من عصر التنوير" }] },
  // Q35
  { textFr: "Qui était Charles Baudelaire ?", lang: 'ar' as const, text: "من كان شارل بودلير؟", explanation: "شارل بودلير (1821-1867) كان شاعرًا فرنسيًا مؤلف ديوان أزهار الشر الشهير. يُعتبر من رواد الشعر الحديث.", choices: [{ id: 'a' as const, text: "شاعر فرنسي مؤلف أزهار الشر" }, { id: 'b' as const, text: "روائي مؤلف البؤساء" }, { id: 'c' as const, text: "نحات من القرن التاسع عشر" }, { id: 'd' as const, text: "موسيقي رومانسي" }] },
  // Q36
  { textFr: "Qui était George Sand ?", lang: 'ar' as const, text: "من كانت جورج صاند؟", explanation: "جورج صاند (1804-1876) كانت روائية فرنسية واسمها الحقيقي أمانتين لوسيل أورور دوبان. اشتهرت برواياتها الريفية والتزامها بحقوق المرأة.", choices: [{ id: 'a' as const, text: "روائية فرنسية من القرن التاسع عشر" }, { id: 'b' as const, text: "ملكة فرنسا" }, { id: 'c' as const, text: "عالمة حائزة على جائزة نوبل" }, { id: 'd' as const, text: "مغنية أوبرا" }] },
  // Q37
  { textFr: "Qui était Simone de Beauvoir ?", lang: 'ar' as const, text: "من كانت سيمون دو بوفوار؟", explanation: "سيمون دو بوفوار (1908-1986) كانت فيلسوفة وكاتبة فرنسية وشخصية بارزة في الحركة النسوية. وهي مؤلفة كتاب الجنس الآخر المؤسس للنسوية الحديثة.", choices: [{ id: 'a' as const, text: "فيلسوفة وكاتبة نسوية فرنسية" }, { id: 'b' as const, text: "مقاومة في الحرب العالمية الثانية" }, { id: 'c' as const, text: "فيزيائية فرنسية" }, { id: 'd' as const, text: "ممثلة سينمائية فرنسية" }] },
  // Q38
  { textFr: "Qui était Albert Camus ?", lang: 'ar' as const, text: "من كان ألبير كامو؟", explanation: "ألبير كامو (1913-1960) كان كاتبًا وفيلسوفًا فرنسيًا حائزًا على جائزة نوبل في الأدب عام 1957. وهو مؤلف الغريب والطاعون.", choices: [{ id: 'a' as const, text: "كاتب وفيلسوف فرنسي حائز على جائزة نوبل في الأدب" }, { id: 'b' as const, text: "رسام انطباعي" }, { id: 'c' as const, text: "سياسي من الجمهورية الثالثة" }, { id: 'd' as const, text: "مؤلف موسيقى كلاسيكية" }] },
  // Q39
  { textFr: "Qui était Paul Cézanne ?", lang: 'ar' as const, text: "من كان بول سيزان؟", explanation: "بول سيزان (1839-1906) كان رسامًا فرنسيًا يُعتبر أب الفن الحديث. أثرت أعماله على التكعيبية والعديد من الحركات الفنية في القرن العشرين.", choices: [{ id: 'a' as const, text: "رسام فرنسي رائد الفن الحديث" }, { id: 'b' as const, text: "كاتب طبيعي" }, { id: 'c' as const, text: "نحات من القرن الثامن عشر" }, { id: 'd' as const, text: "مهندس معماري من عصر النهضة" }] },
  // Q40
  { textFr: "Qui était Marc Chagall ?", lang: 'ar' as const, text: "من كان مارك شاغال؟", explanation: "مارك شاغال (1887-1985) كان رسامًا ونقاشًا روسي الأصل تجنس بالجنسية الفرنسية. اشتهر بأعماله الملونة التي تمزج الخيال والرمزية وخاصة زجاج أوبرا باريس.", choices: [{ id: 'a' as const, text: "رسام روسي الأصل تجنس بالجنسية الفرنسية" }, { id: 'b' as const, text: "فيلسوف فرنسي من عصر التنوير" }, { id: 'c' as const, text: "موسيقي كلاسيكي نمساوي" }, { id: 'd' as const, text: "مخرج سينمائي إيطالي" }] },
  // Q41
  { textFr: "Qui était Joséphine Baker ?", lang: 'ar' as const, text: "من كانت جوزفين بيكر؟", explanation: "جوزفين بيكر (1906-1975) كانت فنانة فرنسية أمريكية ومغنية وراقصة ومقاومة خلال الحرب العالمية الثانية. دُفنت في البانتيون عام 2021 تكريمًا لالتزامها.", choices: [{ id: 'a' as const, text: "فنانة فرنسية أمريكية ومغنية وراقصة ومقاومة" }, { id: 'b' as const, text: "عالمة فرنسية بولندية" }, { id: 'c' as const, text: "سياسية فرنسية" }, { id: 'd' as const, text: "روائية من القرن التاسع عشر" }] },
  // Q42
  { textFr: "Qui était une chanteuse française célèbre ?", lang: 'ar' as const, text: "من كانت مغنية فرنسية شهيرة؟", explanation: "إديث بياف (1915-1963) هي واحدة من أشهر المغنيات الفرنسيات في العالم. اشتهرت بأغانٍ مثل الحياة بالوردي ولا أندم على شيء.", choices: [{ id: 'a' as const, text: "إديث بياف" }, { id: 'b' as const, text: "مادونا" }, { id: 'c' as const, text: "بيونسيه" }, { id: 'd' as const, text: "أديل" }] },
  // Q43
  { textFr: "Qu'est-ce que le Louvre ?", lang: 'ar' as const, text: "ما هو اللوفر؟", explanation: "اللوفر هو أكبر متحف فني في العالم ويقع في باريس. قصر ملكي سابق يضم أعمالًا فنية شهيرة مثل الموناليزا لليوناردو دافنشي.", choices: [{ id: 'a' as const, text: "أكبر متحف فني في العالم يقع في باريس" }, { id: 'b' as const, text: "قصر من قصور اللوار" }, { id: 'c' as const, text: "كاتدرائية قوطية" }, { id: 'd' as const, text: "مسرح وطني" }] },
  // Q44
  { textFr: "Qui était Jean de la Fontaine ?", lang: 'ar' as const, text: "من كان جان دو لافونتين؟", explanation: "جان دو لافونتين (1621-1695) كان شاعرًا فرنسيًا اشتهر بحكاياته. لا تزال أعماله مثل الغراب والثعلب تُدرَّس في المدارس الفرنسية.", choices: [{ id: 'a' as const, text: "شاعر فرنسي اشتهر بحكاياته" }, { id: 'b' as const, text: "ملك فرنسا" }, { id: 'c' as const, text: "رسام من عصر النهضة" }, { id: 'd' as const, text: "مستكشف في العالم الجديد" }] },
  // Q45
  { textFr: "Quel écrivain est français ?", lang: 'ar' as const, text: "أي كاتب فرنسي؟", explanation: "فيكتور هوغو (1802-1885) هو أحد أعظم الكتاب الفرنسيين. وهو مؤلف روائع أدبية مثل البؤساء وأحدب نوتردام.", choices: [{ id: 'a' as const, text: "فيكتور هوغو" }, { id: 'b' as const, text: "تشارلز ديكنز" }, { id: 'c' as const, text: "ميغيل دي ثيربانتس" }, { id: 'd' as const, text: "وليم شكسبير" }] },
  // Q46
  { textFr: "Dans quelle ville se trouve la tour Eiffel ?", lang: 'ar' as const, text: "في أي مدينة يوجد برج إيفل؟", explanation: "يوجد برج إيفل في باريس. بناه غوستاف إيفل للمعرض العالمي عام 1889 وأصبح الرمز الأكثر شهرة لفرنسا.", choices: [{ id: 'a' as const, text: "باريس" }, { id: 'b' as const, text: "ليون" }, { id: 'c' as const, text: "مرسيليا" }, { id: 'd' as const, text: "بوردو" }] },
  // Q47
  { textFr: "Quand célèbre-t-on Noël ?", lang: 'ar' as const, text: "متى نحتفل بعيد الميلاد؟", explanation: "يُحتفل بعيد الميلاد في 25 ديسمبر. وهو يوم عطلة رسمية في فرنسا وعيد مسيحي أصبح أيضًا تقليدًا ثقافيًا يتميز بالوجبات العائلية وتبادل الهدايا.", choices: [{ id: 'a' as const, text: "25 ديسمبر" }, { id: 'b' as const, text: "1 يناير" }, { id: 'c' as const, text: "14 يوليو" }, { id: 'd' as const, text: "1 نوفمبر" }] },
  // Q48
  { textFr: "Quel était le surnom de Louis XIV ?", lang: 'ar' as const, text: "ما كان لقب لويس الرابع عشر؟", explanation: "لُقب لويس الرابع عشر بملك الشمس. حكم من 1643 إلى 1715 أي 72 عامًا وهو أطول حكم في تاريخ فرنسا وبنى قصر فرساي.", choices: [{ id: 'a' as const, text: "ملك الشمس" }, { id: 'b' as const, text: "ملك الملوك" }, { id: 'c' as const, text: "المحبوب" }, { id: 'd' as const, text: "العظيم" }] },
  // Q49
  { textFr: "Quel roi de France a été exécuté pendant la Révolution française ?", lang: 'ar' as const, text: "أي ملك فرنسي أُعدم خلال الثورة الفرنسية؟", explanation: "أُعدم لويس السادس عشر بالمقصلة في 21 يناير 1793 في ساحة الثورة بباريس. حوكم وحُكم عليه بالإعدام من قبل المؤتمر الوطني بتهمة الخيانة.", choices: [{ id: 'a' as const, text: "لويس السادس عشر" }, { id: 'b' as const, text: "لويس الرابع عشر" }, { id: 'c' as const, text: "لويس الخامس عشر" }, { id: 'd' as const, text: "شارل العاشر" }] },
  // Q50
  { textFr: "En quelle année Napoléon Ier est-il devenu empereur ?", lang: 'ar' as const, text: "في أي سنة أصبح نابليون الأول إمبراطورًا؟", explanation: "أصبح نابليون الأول إمبراطورًا للفرنسيين عام 1804. أُقيم حفل تتويجه في 2 ديسمبر 1804 في كاتدرائية نوتردام بباريس.", choices: [{ id: 'a' as const, text: "1804" }, { id: 'b' as const, text: "1789" }, { id: 'c' as const, text: "1799" }, { id: 'd' as const, text: "1815" }] },
  // Q51
  { textFr: "Lequel de ces personnages a un lien avec la République française ?", lang: 'ar' as const, text: "أي من هذه الشخصيات لها علاقة بالجمهورية الفرنسية؟", explanation: "ماريان هي الرمز المجازي للجمهورية الفرنسية. تمثل قيم الحرية والمساواة والإخاء وتمثالها النصفي موجود في جميع البلديات.", choices: [{ id: 'a' as const, text: "ماريان" }, { id: 'b' as const, text: "بريتانيا" }, { id: 'c' as const, text: "العم سام" }, { id: 'd' as const, text: "جون بول" }] },
  // Q52
  { textFr: "De quand date l'appel à la résistance du général de Gaulle ?", lang: 'ar' as const, text: "متى كان نداء المقاومة للجنرال ديغول؟", explanation: "كان نداء الجنرال ديغول في 18 يونيو 1940. من لندن دعا الفرنسيين للمقاومة ضد الاحتلال الألماني عبر إذاعة بي بي سي.", choices: [{ id: 'a' as const, text: "18 يونيو 1940" }, { id: 'b' as const, text: "8 مايو 1945" }, { id: 'c' as const, text: "14 يوليو 1940" }, { id: 'd' as const, text: "25 أغسطس 1944" }] },
  // Q53
  { textFr: "Pourquoi la Shoah est-elle étudiée à l'école ?", lang: 'ar' as const, text: "لماذا تُدرَّس الهولوكوست (الشواه) في المدرسة؟", explanation: "تُدرَّس الشواه في المدرسة لنقل ذكرى هذه الإبادة وتوعية التلاميذ بواجب الذاكرة. يساعد ذلك في مكافحة العنصرية ومعاداة السامية وكل أشكال التمييز.", choices: [{ id: 'a' as const, text: "لواجب الذاكرة ومكافحة العنصرية ومعاداة السامية" }, { id: 'b' as const, text: "لإعداد التلاميذ لامتحانات التاريخ" }, { id: 'c' as const, text: "لتدريس جغرافيا أوروبا" }, { id: 'd' as const, text: "لدراسة اقتصاد الحرب" }] },
  // Q54
  { textFr: "Quel pays a été colonisé par la France ?", lang: 'ar' as const, text: "أي بلد استعمرته فرنسا؟", explanation: "كانت السنغال مستعمرة فرنسية في غرب أفريقيا. حصلت على استقلالها عام 1960 مثل العديد من الدول الأفريقية الناطقة بالفرنسية.", choices: [{ id: 'a' as const, text: "السنغال" }, { id: 'b' as const, text: "نيجيريا" }, { id: 'c' as const, text: "جنوب أفريقيا" }, { id: 'd' as const, text: "إثيوبيا" }] },
  // Q55
  { textFr: "Depuis quand les Français élisent-ils le président de la République au suffrage universel direct ?", lang: 'ar' as const, text: "منذ متى ينتخب الفرنسيون رئيس الجمهورية بالاقتراع العام المباشر؟", explanation: "منذ عام 1962 ينتخب الفرنسيون رئيس الجمهورية بالاقتراع العام المباشر بعد الاستفتاء الذي أراده الجنرال ديغول. قبل هذا التاريخ كان الرئيس يُنتخب من قبل هيئة انتخابية.", choices: [{ id: 'a' as const, text: "1962" }, { id: 'b' as const, text: "1958" }, { id: 'c' as const, text: "1945" }, { id: 'd' as const, text: "1981" }] },
  // Q56
  { textFr: "Quelle est la première étape de la construction européenne en 1951 ?", lang: 'ar' as const, text: "ما هي الخطوة الأولى في البناء الأوروبي عام 1951؟", explanation: "الجماعة الأوروبية للفحم والصلب التي أُنشئت عام 1951 هي الخطوة الأولى في البناء الأوروبي. أسستها ست دول لتقاسم إنتاجها من الفحم والصلب.", choices: [{ id: 'a' as const, text: "إنشاء الجماعة الأوروبية للفحم والصلب" }, { id: 'b' as const, text: "إنشاء الاتحاد الأوروبي" }, { id: 'c' as const, text: "توقيع معاهدة ماستريخت" }, { id: 'd' as const, text: "اعتماد اليورو" }] },
  // Q57
  { textFr: "Durant le mandat de quel président la peine de mort a-t-elle été abolie ?", lang: 'ar' as const, text: "في عهد أي رئيس تم إلغاء عقوبة الإعدام؟", explanation: "تم إلغاء عقوبة الإعدام عام 1981 في عهد الرئيس فرانسوا ميتران بفضل وزير العدل روبير بادنتير. كانت فرنسا من آخر دول أوروبا الغربية التي ألغتها.", choices: [{ id: 'a' as const, text: "فرانسوا ميتران" }, { id: 'b' as const, text: "فاليري جيسكار ديستان" }, { id: 'c' as const, text: "جاك شيراك" }, { id: 'd' as const, text: "شارل ديغول" }] },
  // Q58
  { textFr: "Quel régime politique a été mis en place pendant la Révolution française en 1792 ?", lang: 'ar' as const, text: "أي نظام سياسي أُقيم خلال الثورة الفرنسية عام 1792؟", explanation: "أُعلنت الجمهورية الأولى في 21 سبتمبر 1792 بعد إلغاء الملكية. وهي أول نظام جمهوري في تاريخ فرنسا.", choices: [{ id: 'a' as const, text: "الجمهورية (الجمهورية الأولى)" }, { id: 'b' as const, text: "الإمبراطورية" }, { id: 'c' as const, text: "الملكية الدستورية" }, { id: 'd' as const, text: "الدكتاتورية العسكرية" }] },
  // Q59
  { textFr: "Qui était une figure de la Résistance française pendant la Seconde Guerre mondiale ?", lang: 'ar' as const, text: "من كان شخصية بارزة في المقاومة الفرنسية خلال الحرب العالمية الثانية؟", explanation: "جان مولان (1899-1943) كان موظفًا كبيرًا ومقاومًا فرنسيًا. وحّد حركات المقاومة تحت سلطة الجنرال ديغول قبل اعتقاله وقتله على يد الغستابو.", choices: [{ id: 'a' as const, text: "جان مولان" }, { id: 'b' as const, text: "فيليب بيتان" }, { id: 'c' as const, text: "بيير لافال" }, { id: 'd' as const, text: "أدولف تيير" }] },
  // Q60
  { textFr: "En 1944, qu'est-ce qui a changé pour les femmes ?", lang: 'ar' as const, text: "في عام 1944، ما الذي تغير بالنسبة للنساء؟", explanation: "في عام 1944 حصلت النساء على حق التصويت في فرنسا. صوتن لأول مرة في الانتخابات البلدية في 29 أبريل 1945.", choices: [{ id: 'a' as const, text: "حصلن على حق التصويت" }, { id: 'b' as const, text: "حصلن على حق العمل" }, { id: 'c' as const, text: "حصلن على حق الطلاق" }, { id: 'd' as const, text: "حصلن على حق فتح حساب مصرفي" }] },
  // Q61
  { textFr: "Quelle organisation internationale a été créée en 1945 après la Seconde Guerre mondiale ?", lang: 'ar' as const, text: "أي منظمة دولية أُنشئت عام 1945 بعد الحرب العالمية الثانية؟", explanation: "أُنشئت منظمة الأمم المتحدة عام 1945 للحفاظ على السلام والأمن الدوليين. فرنسا عضو دائم في مجلس الأمن من بين خمسة أعضاء.", choices: [{ id: 'a' as const, text: "منظمة الأمم المتحدة" }, { id: 'b' as const, text: "الاتحاد الأوروبي" }, { id: 'c' as const, text: "حلف الناتو" }, { id: 'd' as const, text: "الصليب الأحمر" }] },
  // Q62
  { textFr: "Quelle peine a été supprimée en 1981 ?", lang: 'ar' as const, text: "أي عقوبة أُلغيت عام 1981؟", explanation: "أُلغيت عقوبة الإعدام في فرنسا في 9 أكتوبر 1981 بموجب القانون الذي قدمه روبير بادنتير. انضمت فرنسا بذلك إلى الدول الأوروبية التي ألغت عقوبة الإعدام.", choices: [{ id: 'a' as const, text: "عقوبة الإعدام" }, { id: 'b' as const, text: "السجن المؤبد" }, { id: 'c' as const, text: "الأشغال الشاقة" }, { id: 'd' as const, text: "النفي" }] },
  // Q63
  { textFr: "En quelle année l'euro est-il devenu la monnaie utilisée en France ?", lang: 'ar' as const, text: "في أي سنة أصبح اليورو العملة المستخدمة في فرنسا؟", explanation: "أصبح اليورو العملة المستخدمة في فرنسا في 1 يناير 2002 ليحل محل الفرنك الفرنسي. اليورو اليوم هو العملة المشتركة لعشرين دولة في منطقة اليورو.", choices: [{ id: 'a' as const, text: "2002" }, { id: 'b' as const, text: "1999" }, { id: 'c' as const, text: "1992" }, { id: 'd' as const, text: "2005" }] },
  // Q64
  { textFr: "En quelle année a commencé la Première Guerre mondiale ?", lang: 'ar' as const, text: "في أي سنة بدأت الحرب العالمية الأولى؟", explanation: "بدأت الحرب العالمية الأولى عام 1914 بعد اغتيال الأرشيدوق فرانز فرديناند من النمسا. انخرطت فرنسا في الصراع منذ البداية.", choices: [{ id: 'a' as const, text: "1914" }, { id: 'b' as const, text: "1916" }, { id: 'c' as const, text: "1912" }, { id: 'd' as const, text: "1939" }] },
  // Q65
  { textFr: "Où a eu lieu le débarquement en 1944 ?", lang: 'ar' as const, text: "أين حدث الإنزال عام 1944؟", explanation: "حدث إنزال 6 يونيو 1944 (يوم النصر) على شواطئ نورماندي. هذه العملية العسكرية للحلفاء بدأت تحرير فرنسا من الاحتلال النازي.", choices: [{ id: 'a' as const, text: "في نورماندي" }, { id: 'b' as const, text: "في بريتاني" }, { id: 'c' as const, text: "في بروفانس" }, { id: 'd' as const, text: "في بيكاردي" }] },
  // Q66
  { textFr: "Quel continent a été le plus concerné par la décolonisation française après la Seconde Guerre mondiale ?", lang: 'ar' as const, text: "أي قارة كانت الأكثر تأثرًا بإنهاء الاستعمار الفرنسي بعد الحرب العالمية الثانية؟", explanation: "كانت أفريقيا القارة الأكثر تأثرًا بإنهاء الاستعمار الفرنسي. حصلت غالبية المستعمرات الفرنسية في أفريقيا على استقلالها في ستينيات القرن العشرين.", choices: [{ id: 'a' as const, text: "أفريقيا" }, { id: 'b' as const, text: "آسيا" }, { id: 'c' as const, text: "أمريكا الجنوبية" }, { id: 'd' as const, text: "أوقيانوسيا" }] },
  // Q67
  { textFr: "Que fête-t-on le 8 mai ?", lang: 'ar' as const, text: "ماذا نحتفل في 8 مايو؟", explanation: "يحيي الثامن من مايو ذكرى نهاية الحرب العالمية الثانية في أوروبا (انتصار الحلفاء على ألمانيا النازية عام 1945). وهو يوم عطلة رسمية في فرنسا.", choices: [{ id: 'a' as const, text: "نهاية الحرب العالمية الثانية في أوروبا" }, { id: 'b' as const, text: "عيد العمال" }, { id: 'c' as const, text: "هدنة الحرب العالمية الأولى" }, { id: 'd' as const, text: "العيد الوطني" }] },
  // Q68
  { textFr: "Quelle mer ou océan borde la France métropolitaine ?", lang: 'ar' as const, text: "أي بحر أو محيط يحد فرنسا الحضرية؟", explanation: "يحد البحر الأبيض المتوسط جنوب فرنسا الحضرية. كما يحدها المحيط الأطلسي من الغرب والقنال الإنجليزي من الشمال.", choices: [{ id: 'a' as const, text: "البحر الأبيض المتوسط" }, { id: 'b' as const, text: "بحر قزوين" }, { id: 'c' as const, text: "البحر الأسود" }, { id: 'd' as const, text: "البحر الأحمر" }] },
  // Q69
  { textFr: "Quel pays a une frontière terrestre avec la France métropolitaine ?", lang: 'ar' as const, text: "أي بلد له حدود برية مع فرنسا الحضرية؟", explanation: "تتقاسم إسبانيا حدودًا برية مع فرنسا في الجنوب على طول جبال البيرينيه. لفرنسا الحضرية أيضًا حدود مع بلجيكا ولوكسمبورغ وألمانيا وسويسرا وإيطاليا وموناكو.", choices: [{ id: 'a' as const, text: "إسبانيا" }, { id: 'b' as const, text: "البرتغال" }, { id: 'c' as const, text: "إنجلترا" }, { id: 'd' as const, text: "بولندا" }] },
  // Q70
  { textFr: "Quelle ville française est un port maritime ?", lang: 'ar' as const, text: "أي مدينة فرنسية هي ميناء بحري؟", explanation: "لوهافر ميناء بحري فرنسي كبير يقع في نورماندي عند مصب نهر السين. وهو أحد أهم موانئ التجارة في فرنسا.", choices: [{ id: 'a' as const, text: "لوهافر" }, { id: 'b' as const, text: "تولوز" }, { id: 'c' as const, text: "كليرمون فيران" }, { id: 'd' as const, text: "ستراسبورغ" }] },
  // Q71
  { textFr: "Quelle mer se situe entre la France et l'Angleterre ?", lang: 'ar' as const, text: "أي بحر يقع بين فرنسا وإنجلترا؟", explanation: "يفصل القنال الإنجليزي (المانش) بين فرنسا وإنجلترا. يربط المحيط الأطلسي ببحر الشمال ويعبره نفق المانش منذ عام 1994.", choices: [{ id: 'a' as const, text: "القنال الإنجليزي (المانش)" }, { id: 'b' as const, text: "بحر الشمال" }, { id: 'c' as const, text: "البحر الأبيض المتوسط" }, { id: 'd' as const, text: "بحر البلطيق" }] },
  // Q72
  { textFr: "Qu'est-ce que la France d'outre-mer ?", lang: 'ar' as const, text: "ما هي فرنسا ما وراء البحار؟", explanation: "تشير فرنسا ما وراء البحار إلى مجموع الأقاليم الفرنسية خارج أوروبا. تشمل أقاليم (غوادلوب ومارتينيك وغويانا ولاريونيون ومايوت) ومجموعات إقليمية أخرى.", choices: [{ id: 'a' as const, text: "مجموع الأقاليم الفرنسية خارج أوروبا" }, { id: 'b' as const, text: "مناطق جنوب فرنسا" }, { id: 'c' as const, text: "المستعمرات الفرنسية السابقة المستقلة" }, { id: 'd' as const, text: "الدول الأفريقية الناطقة بالفرنسية" }] },
  // Q73
  { textFr: "Quelle chaîne de montagnes est située entre la France et l'Espagne ?", lang: 'ar' as const, text: "أي سلسلة جبلية تقع بين فرنسا وإسبانيا؟", explanation: "تشكل جبال البيرينيه حدودًا طبيعية بين فرنسا وإسبانيا على مسافة حوالي 430 كم. أعلى قمة فيها هي بيك أنيتو (3404 م) على الجانب الإسباني.", choices: [{ id: 'a' as const, text: "جبال البيرينيه" }, { id: 'b' as const, text: "جبال الألب" }, { id: 'c' as const, text: "جبال الجورا" }, { id: 'd' as const, text: "جبال الفوج" }] },
  // Q74
  { textFr: "Quelle île française se trouve dans l'océan Indien ?", lang: 'ar' as const, text: "أي جزيرة فرنسية تقع في المحيط الهندي؟", explanation: "لاريونيون إقليم فرنسي فيما وراء البحار يقع في المحيط الهندي شرق مدغشقر. وهي جزيرة بركانية يبلغ عدد سكانها حوالي 900 ألف نسمة.", choices: [{ id: 'a' as const, text: "لاريونيون" }, { id: 'b' as const, text: "مارتينيك" }, { id: 'c' as const, text: "غوادلوب" }, { id: 'd' as const, text: "كورسيكا" }] },
  // Q75
  { textFr: "Quelle est la population approximative de la France en 2025 ?", lang: 'ar' as const, text: "ما هو عدد سكان فرنسا التقريبي في 2025؟", explanation: "يبلغ عدد سكان فرنسا حوالي 68 مليون نسمة في 2025 بما في ذلك أقاليم ما وراء البحار. وهي ثاني أكثر دول الاتحاد الأوروبي اكتظاظًا بالسكان بعد ألمانيا.", choices: [{ id: 'a' as const, text: "68 مليون نسمة" }, { id: 'b' as const, text: "50 مليون نسمة" }, { id: 'c' as const, text: "80 مليون نسمة" }, { id: 'd' as const, text: "45 مليون نسمة" }] },
  // Q76
  { textFr: "Quel fleuve traverse Paris ?", lang: 'ar' as const, text: "أي نهر يعبر باريس؟", explanation: "يعبر نهر السين باريس من الشرق إلى الغرب. هذا النهر الذي يبلغ طوله 776 كم ينبع من بورغوندي ويصب في القنال الإنجليزي عند لوهافر.", choices: [{ id: 'a' as const, text: "السين" }, { id: 'b' as const, text: "اللوار" }, { id: 'c' as const, text: "الرون" }, { id: 'd' as const, text: "الغارون" }] },
  // Q77
  { textFr: "Lequel de ces pays partage des frontières terrestres avec la France ?", lang: 'ar' as const, text: "أي من هذه الدول يتقاسم حدودًا برية مع فرنسا؟", explanation: "تتقاسم بلجيكا حدودًا برية مع فرنسا في الشمال. البلدان جاران وشريكان في الاتحاد الأوروبي.", choices: [{ id: 'a' as const, text: "بلجيكا" }, { id: 'b' as const, text: "هولندا" }, { id: 'c' as const, text: "المملكة المتحدة" }, { id: 'd' as const, text: "الدنمارك" }] },
  // Q78
  { textFr: "Quel pays a une frontière avec la France métropolitaine au nord-est ?", lang: 'ar' as const, text: "أي بلد له حدود مع فرنسا الحضرية في الشمال الشرقي؟", explanation: "تتقاسم ألمانيا حدودًا مع فرنسا في الشمال الشرقي على طول نهر الراين. كانت هذه الحدود مسرحًا للعديد من الصراعات قبل أن تصبح رمزًا للمصالحة الفرنسية الألمانية.", choices: [{ id: 'a' as const, text: "ألمانيا" }, { id: 'b' as const, text: "بولندا" }, { id: 'c' as const, text: "النمسا" }, { id: 'd' as const, text: "جمهورية التشيك" }] },
  // Q79
  { textFr: "Où se trouvent les principales activités économiques en France ?", lang: 'ar' as const, text: "أين تتركز الأنشطة الاقتصادية الرئيسية في فرنسا؟", explanation: "تتركز الأنشطة الاقتصادية الرئيسية في فرنسا في المدن الكبرى وخاصة منطقة باريس (إيل دو فرانس). ليون ومرسيليا ومدن كبرى أخرى هي أيضًا أقطاب اقتصادية رئيسية.", choices: [{ id: 'a' as const, text: "في المدن الكبرى ومنطقة باريس" }, { id: 'b' as const, text: "فقط في جنوب فرنسا" }, { id: 'c' as const, text: "بشكل رئيسي في المناطق الريفية" }, { id: 'd' as const, text: "حصريًا على السواحل" }] },
  // Q80
  { textFr: "Parmi ces pays, lequel attire le plus de visiteurs chaque année ?", lang: 'ar' as const, text: "من بين هذه الدول، أيها يستقطب أكبر عدد من الزوار سنويًا؟", explanation: "فرنسا هي الوجهة السياحية الأولى في العالم بحوالي 90 مليون زائر أجنبي سنويًا. يجذب تراثها الثقافي ومطبخها ومناظرها المتنوعة سياحًا من جميع أنحاء العالم.", choices: [{ id: 'a' as const, text: "فرنسا" }, { id: 'b' as const, text: "إيطاليا" }, { id: 'c' as const, text: "الولايات المتحدة" }, { id: 'd' as const, text: "إسبانيا" }] },
  // Q81
  { textFr: "Où habite la majorité des Français ?", lang: 'ar' as const, text: "أين يعيش غالبية الفرنسيين؟", explanation: "يعيش غالبية الفرنسيين في المدن (حوالي 80% من السكان حضريون). تتركز نسبة كبيرة من السكان في التجمعات الكبرى مثل باريس وليون ومرسيليا.", choices: [{ id: 'a' as const, text: "في المدن" }, { id: 'b' as const, text: "في الريف" }, { id: 'c' as const, text: "في الجبال" }, { id: 'd' as const, text: "على الساحل" }] },
  // Q82
  { textFr: "Quelle région est la plus peuplée ?", lang: 'ar' as const, text: "أي منطقة هي الأكثر اكتظاظًا بالسكان؟", explanation: "إيل دو فرانس هي المنطقة الأكثر اكتظاظًا بالسكان في فرنسا بحوالي 12 مليون نسمة. تضم باريس وضواحيها وتركز خمس سكان فرنسا.", choices: [{ id: 'a' as const, text: "إيل دو فرانس" }, { id: 'b' as const, text: "بروفانس-ألب-كوت دازور" }, { id: 'c' as const, text: "أوكسيتاني" }, { id: 'd' as const, text: "نوفيل أكيتان" }] },
  // Q83
  { textFr: "Quelle ville française fait partie des 10 plus grandes métropoles du pays ?", lang: 'ar' as const, text: "أي مدينة فرنسية تنتمي إلى أكبر 10 مدن حضرية في البلاد؟", explanation: "تولوز من بين أكبر 10 مدن حضرية في فرنسا. وهي رابع مدينة في فرنسا من حيث عدد السكان وقطب رئيسي لصناعة الطيران.", choices: [{ id: 'a' as const, text: "تولوز" }, { id: 'b' as const, text: "بازل" }, { id: 'c' as const, text: "لوزان" }, { id: 'd' as const, text: "شارلروا" }] },
  // Q84
  { textFr: "Lequel de ces départements de France est le plus touristique ?", lang: 'ar' as const, text: "أي من هذه الأقاليم الفرنسية هو الأكثر سياحية؟", explanation: "باريس (إقليم 75) هي الإقليم الأكثر سياحية في فرنسا. تستقطب العاصمة ملايين الزوار سنويًا بفضل معالمها ومتاحفها وحياتها الثقافية.", choices: [{ id: 'a' as const, text: "باريس" }, { id: 'b' as const, text: "لاكروز" }, { id: 'c' as const, text: "لوكانتال" }, { id: 'd' as const, text: "لالوزير" }] },
  // Q85
  { textFr: "Quand peut-on visiter gratuitement des lieux culturels en France ?", lang: 'ar' as const, text: "متى يمكن زيارة الأماكن الثقافية مجانًا في فرنسا؟", explanation: "تتيح الأيام الأوروبية للتراث التي تُنظم كل سنة في سبتمبر زيارة العديد من الأماكن الثقافية والمعالم التاريخية مجانًا في فرنسا.", choices: [{ id: 'a' as const, text: "خلال الأيام الأوروبية للتراث" }, { id: 'b' as const, text: "في 14 يوليو فقط" }, { id: 'c' as const, text: "كل أيام الأحد من السنة" }, { id: 'd' as const, text: "خلال العطل المدرسية" }] },
  // Q86
  { textFr: "Combien de personnes parlent français dans le monde ?", lang: 'ar' as const, text: "كم عدد الأشخاص الذين يتحدثون الفرنسية في العالم؟", explanation: "يتحدث حوالي 300 مليون شخص الفرنسية في العالم. الفرنسية هي خامس لغة الأكثر تحدثًا وهي لغة رسمية في 29 دولة.", choices: [{ id: 'a' as const, text: "حوالي 300 مليون" }, { id: 'b' as const, text: "حوالي 100 مليون" }, { id: 'c' as const, text: "حوالي 500 مليون" }, { id: 'd' as const, text: "حوالي 50 مليون" }] },
  // Q87
  { textFr: "Qui était Marguerite Yourcenar ?", lang: 'ar' as const, text: "من كانت مارغريت يورسنار؟", explanation: "مارغريت يورسنار (1903-1987) كانت كاتبة فرنسية وأول امرأة تُنتخب في الأكاديمية الفرنسية عام 1980. اشتهرت برواياتها التاريخية مثل مذكرات هادريان.", choices: [{ id: 'a' as const, text: "أول امرأة تُنتخب في الأكاديمية الفرنسية" }, { id: 'b' as const, text: "عالمة فيزياء حائزة على جائزة نوبل" }, { id: 'c' as const, text: "مستكشفة من القرن التاسع عشر" }, { id: 'd' as const, text: "مؤلفة موسيقى باروكية" }] },
  // Q88
  { textFr: "Quel peintre est français ?", lang: 'ar' as const, text: "أي رسام فرنسي؟", explanation: "كلود مونيه (1840-1926) كان رسامًا فرنسيًا مؤسس الحركة الانطباعية. اشتهر بسلسلة لوحات زنابق الماء وكاتدرائية روان.", choices: [{ id: 'a' as const, text: "كلود مونيه" }, { id: 'b' as const, text: "بابلو بيكاسو" }, { id: 'c' as const, text: "فنسنت فان غوخ" }, { id: 'd' as const, text: "سلفادور دالي" }] },
  // Q89
  { textFr: "Quel musée est situé à Paris ?", lang: 'ar' as const, text: "أي متحف يقع في باريس؟", explanation: "يقع متحف أورسيه في باريس في محطة قطار سابقة. يضم أكبر مجموعة من الفن الانطباعي وما بعد الانطباعي في العالم.", choices: [{ id: 'a' as const, text: "متحف أورسيه" }, { id: 'b' as const, text: "المتحف البريطاني" }, { id: 'c' as const, text: "متحف البرادو" }, { id: 'd' as const, text: "متحف المتروبوليتان" }] },
  // Q90
  { textFr: "Qui était Auguste Rodin ?", lang: 'ar' as const, text: "من كان أوغست رودان؟", explanation: "أوغست رودان (1840-1917) كان نحاتًا فرنسيًا يُعتبر أب النحت الحديث. وهو مؤلف تمثال المفكر وتمثال مواطنو كاليه.", choices: [{ id: 'a' as const, text: "نحات فرنسي مؤلف تمثال المفكر" }, { id: 'b' as const, text: "رسام انطباعي" }, { id: 'c' as const, text: "مهندس برج إيفل" }, { id: 'd' as const, text: "كاتب رومانسي" }] },
  // Q91
  { textFr: "Quel est le classement de la langue française parmi les langues les plus parlées dans le monde ?", lang: 'ar' as const, text: "ما هو ترتيب اللغة الفرنسية بين اللغات الأكثر تحدثًا في العالم؟", explanation: "الفرنسية هي خامس لغة الأكثر تحدثًا في العالم. وهي لغة رسمية في 29 دولة ويُتحدث بها في القارات الخمس.", choices: [{ id: 'a' as const, text: "خامس لغة الأكثر تحدثًا" }, { id: 'b' as const, text: "ثاني لغة الأكثر تحدثًا" }, { id: 'c' as const, text: "عاشر لغة الأكثر تحدثًا" }, { id: 'd' as const, text: "أول لغة الأكثر تحدثًا" }] },
  // Q92
  { textFr: "Quelle cathédrale célèbre a été en partie détruite par un incendie en 2019 ?", lang: 'ar' as const, text: "أي كاتدرائية شهيرة دُمرت جزئيًا بحريق عام 2019؟", explanation: "تضررت كاتدرائية نوتردام بباريس بشدة جراء حريق في 15 أبريل 2019. انهارت قمتها وجزء من سقفها. تم ترميمها وإعادة افتتاحها في ديسمبر 2024.", choices: [{ id: 'a' as const, text: "نوتردام باريس" }, { id: 'b' as const, text: "كاتدرائية ريمس" }, { id: 'c' as const, text: "كاتدرائية شارتر" }, { id: 'd' as const, text: "كاتدرائية ستراسبورغ" }] },
  // Q93
  { textFr: "Qui était une écrivaine française célèbre ?", lang: 'ar' as const, text: "من كانت كاتبة فرنسية شهيرة؟", explanation: "كوليت (1873-1954) كانت روائية فرنسية شهيرة مؤلفة العديد من الروايات مثل سلسلة كلودين. كانت ثاني امرأة تحظى بجنازة وطنية في فرنسا.", choices: [{ id: 'a' as const, text: "كوليت" }, { id: 'b' as const, text: "جين أوستن" }, { id: 'c' as const, text: "فرجينيا وولف" }, { id: 'd' as const, text: "أغاثا كريستي" }] },
  // Q94
  { textFr: "Qui était un célèbre musicien français ?", lang: 'ar' as const, text: "من كان موسيقيًا فرنسيًا شهيرًا؟", explanation: "كلود ديبوسي (1862-1918) كان مؤلفًا موسيقيًا فرنسيًا وشخصية بارزة في الموسيقى الانطباعية. اشتهر بأعمال مثل ضوء القمر والبحر.", choices: [{ id: 'a' as const, text: "كلود ديبوسي" }, { id: 'b' as const, text: "لودفيغ فان بيتهوفن" }, { id: 'c' as const, text: "فولفغانغ أماديوس موتسارت" }, { id: 'd' as const, text: "يوهان سيباستيان باخ" }] },
  // Q95
  { textFr: "Qui était Auguste Renoir ?", lang: 'ar' as const, text: "من كان أوغست رينوار؟", explanation: "أوغست رينوار (1841-1919) كان رسامًا فرنسيًا من كبار أساتذة الانطباعية. اشتهر بمشاهد الحياة اليومية وصوره الشخصية المشرقة.", choices: [{ id: 'a' as const, text: "رسام انطباعي فرنسي" }, { id: 'b' as const, text: "نحات من القرن الثامن عشر" }, { id: 'c' as const, text: "كاتب واقعي" }, { id: 'd' as const, text: "مهندس معماري من عصر النهضة" }] },
  // Q96
  { textFr: "Quelle fête est française ?", lang: 'ar' as const, text: "أي عيد فرنسي؟", explanation: "عيد الموسيقى الذي يُحتفل به في 21 يونيو هو عيد فرنسي الأصل أُنشئ عام 1982 على يد جاك لانغ. يُحتفل به اليوم في العديد من دول العالم.", choices: [{ id: 'a' as const, text: "عيد الموسيقى" }, { id: 'b' as const, text: "عيد الشكر" }, { id: 'c' as const, text: "الهالوين" }, { id: 'd' as const, text: "عيد القديس باتريك" }] },
  // Q97
  { textFr: "Parmi ces textes, lequel a été adopté sous Napoléon Ier ?", lang: 'ar' as const, text: "من بين هذه النصوص، أيها تم اعتماده في عهد نابليون الأول؟", explanation: "تم اعتماد القانون المدني عام 1804 في عهد نابليون الأول. يُعرف أيضًا بقانون نابليون وقد وحّد القانون الفرنسي ولا يزال أساس القانون المدني في فرنسا.", choices: [{ id: 'a' as const, text: "القانون المدني" }, { id: 'b' as const, text: "إعلان حقوق الإنسان والمواطن" }, { id: 'c' as const, text: "قانون فصل الكنائس عن الدولة" }, { id: 'd' as const, text: "دستور الجمهورية الخامسة" }] },
  // Q98
  { textFr: "Qui a été président de la Ve République ?", lang: 'ar' as const, text: "من كان رئيسًا للجمهورية الخامسة؟", explanation: "كان جاك شيراك رئيسًا للجمهورية الخامسة من 1995 إلى 2007. كان الرئيس الخامس للجمهورية الخامسة وسبقه فرانسوا ميتران.", choices: [{ id: 'a' as const, text: "جاك شيراك" }, { id: 'b' as const, text: "ونستون تشرشل" }, { id: 'c' as const, text: "كونراد أديناور" }, { id: 'd' as const, text: "بينيتو موسوليني" }] },
  // Q99
  { textFr: "Que signifie la date du 14 juillet pour les Français ?", lang: 'ar' as const, text: "ماذا يعني تاريخ 14 يوليو بالنسبة للفرنسيين؟", explanation: "الرابع عشر من يوليو هو العيد الوطني الفرنسي. يحيي ذكرى اقتحام الباستيل عام 1789 رمز نهاية الاستبداد وعيد الاتحاد عام 1790.", choices: [{ id: 'a' as const, text: "هو العيد الوطني إحياءً لذكرى اقتحام الباستيل" }, { id: 'b' as const, text: "هو ذكرى الدستور" }, { id: 'c' as const, text: "هو عيد أوروبا" }, { id: 'd' as const, text: "هو يوم الهدنة" }] },
  // Q100
  { textFr: "Lequel de ces pays est un pays fondateur de l'Union européenne ?", lang: 'ar' as const, text: "أي من هذه الدول هي دولة مؤسسة للاتحاد الأوروبي؟", explanation: "فرنسا هي إحدى الدول الست المؤسسة للبناء الأوروبي مع ألمانيا وإيطاليا وبلجيكا وهولندا ولوكسمبورغ. أُنشئت الجماعة الأوروبية للفحم والصلب عام 1951.", choices: [{ id: 'a' as const, text: "فرنسا" }, { id: 'b' as const, text: "المملكة المتحدة" }, { id: 'c' as const, text: "إسبانيا" }, { id: 'd' as const, text: "بولندا" }] },
  // Q101
  { textFr: "Dans quelle région est située une partie des plages du débarquement ?", lang: 'ar' as const, text: "في أي منطقة تقع جزء من شواطئ الإنزال؟", explanation: "تقع شواطئ إنزال 6 يونيو 1944 في نورماندي. الشواطئ الخمسة (يوتا وأوماها وغولد وجونو وسورد) هي مواقع ذاكرة رئيسية.", choices: [{ id: 'a' as const, text: "نورماندي" }, { id: 'b' as const, text: "بريتاني" }, { id: 'c' as const, text: "بيكاردي" }, { id: 'd' as const, text: "أكيتان" }] },
  // Q102
  { textFr: "Dans quelle ville les rois de France étaient-ils couronnés ?", lang: 'ar' as const, text: "في أي مدينة كان ملوك فرنسا يُتوّجون؟", explanation: "كان ملوك فرنسا يُتوّجون تقليديًا في كاتدرائية ريمس. يعود هذا التقليد إلى معمودية كلوفيس حوالي عام 496 واستمر لقرون.", choices: [{ id: 'a' as const, text: "ريمس" }, { id: 'b' as const, text: "باريس" }, { id: 'c' as const, text: "فرساي" }, { id: 'd' as const, text: "أورليان" }] },
  // Q103
  { textFr: "En quelle année l'Union européenne a-t-elle été fondée ?", lang: 'ar' as const, text: "في أي سنة تأسس الاتحاد الأوروبي؟", explanation: "تأسس الاتحاد الأوروبي عام 1992 بموجب معاهدة ماستريخت. حوّلت هذه المعاهدة المجموعة الاقتصادية الأوروبية إلى اتحاد أوروبي ووضعت أسس العملة الموحدة.", choices: [{ id: 'a' as const, text: "1992" }, { id: 'b' as const, text: "1957" }, { id: 'c' as const, text: "2002" }, { id: 'd' as const, text: "1951" }] },
  // Q104
  { textFr: "Qui a aboli l'esclavage en France ?", lang: 'ar' as const, text: "من ألغى العبودية في فرنسا؟", explanation: "فيكتور شولشر هو صاحب مرسوم الإلغاء النهائي للعبودية في فرنسا في 27 أبريل 1848. كان وقتها وكيل وزارة المستعمرات في عهد الجمهورية الثانية.", choices: [{ id: 'a' as const, text: "فيكتور شولشر" }, { id: 'b' as const, text: "نابليون بونابرت" }, { id: 'c' as const, text: "جول فيري" }, { id: 'd' as const, text: "ليون غامبيتا" }] },
  // Q105
  { textFr: "Lors de la Seconde Guerre mondiale, à quelle date Paris a-t-elle été libérée ?", lang: 'ar' as const, text: "خلال الحرب العالمية الثانية، في أي تاريخ تم تحرير باريس؟", explanation: "تم تحرير باريس في 25 أغسطس 1944 بعد انتفاضة شعبية ووصول الفرقة المدرعة الثانية بقيادة الجنرال لوكلير. يمثل هذا الحدث نقطة تحول في تحرير فرنسا.", choices: [{ id: 'a' as const, text: "25 أغسطس 1944" }, { id: 'b' as const, text: "6 يونيو 1944" }, { id: 'c' as const, text: "8 مايو 1945" }, { id: 'd' as const, text: "18 يونيو 1940" }] },
  // Q106
  { textFr: "Quel était le principal port français impliqué dans la traite négrière au XVIIIe siècle ?", lang: 'ar' as const, text: "ما كان الميناء الفرنسي الرئيسي المتورط في تجارة الرقيق في القرن الثامن عشر؟", explanation: "كانت نانت الميناء الفرنسي الرئيسي المتورط في تجارة الرقيق في القرن الثامن عشر. نظمت المدينة أكبر عدد من رحلات تجارة الرقيق الفرنسية وتضم اليوم نصبًا تذكاريًا لإلغاء العبودية.", choices: [{ id: 'a' as const, text: "نانت" }, { id: 'b' as const, text: "مرسيليا" }, { id: 'c' as const, text: "لوهافر" }, { id: 'd' as const, text: "بريست" }] },
  // Q107
  { textFr: "Quel célèbre philosophe des Lumières a dénoncé l'esclavage ?", lang: 'ar' as const, text: "أي فيلسوف شهير من عصر التنوير ندد بالعبودية؟", explanation: "فولتير (1694-1778) كان فيلسوفًا من عصر التنوير ندد بالعبودية خاصة في رواية كانديد. لعب فلاسفة التنوير دورًا رئيسيًا في التشكيك بهذه الممارسة.", choices: [{ id: 'a' as const, text: "فولتير" }, { id: 'b' as const, text: "نابليون بونابرت" }, { id: 'c' as const, text: "لويس الرابع عشر" }, { id: 'd' as const, text: "ريشيليو" }] },
  // Q108
  { textFr: "Quel plat est une spécialité de la cuisine française ?", lang: 'ar' as const, text: "أي طبق هو من تخصصات المطبخ الفرنسي؟", explanation: "الديك بالنبيذ هو طبق تقليدي من المطبخ الفرنسي يُحضّر من الدجاج المطهو في النبيذ الأحمر مع لحم مقدد وفطر. المطبخ الفرنسي مسجل في التراث العالمي غير المادي لليونسكو.", choices: [{ id: 'a' as const, text: "الديك بالنبيذ" }, { id: 'b' as const, text: "الباييلا" }, { id: 'c' as const, text: "السوشي" }, { id: 'd' as const, text: "السمك والبطاطا المقلية" }] },
  // Q109
  { textFr: "Qui était Marie Curie ?", lang: 'ar' as const, text: "من كانت ماري كوري؟", explanation: "ماري كوري (1867-1934) كانت فيزيائية وكيميائية فرنسية بولندية وأول امرأة تحصل على جائزة نوبل. حصلت على جائزتي نوبل (الفيزياء عام 1903 والكيمياء عام 1911) لأبحاثها حول النشاط الإشعاعي.", choices: [{ id: 'a' as const, text: "فيزيائية فرنسية بولندية حائزة على جائزتي نوبل" }, { id: 'b' as const, text: "روائية فرنسية من القرن التاسع عشر" }, { id: 'c' as const, text: "مقاومة في الحرب العالمية الثانية" }, { id: 'd' as const, text: "ملكة فرنسا" }] },
  // Q110
  { textFr: "Qui a peint « La Liberté guidant le peuple » ?", lang: 'ar' as const, text: "من رسم لوحة «الحرية تقود الشعب»؟", explanation: "رسم أوجين ديلاكروا لوحة الحرية تقود الشعب عام 1830. تصور هذه اللوحة الشهيرة ثورة يوليو 1830 وهي معروضة في متحف اللوفر.", choices: [{ id: 'a' as const, text: "أوجين ديلاكروا" }, { id: 'b' as const, text: "كلود مونيه" }, { id: 'c' as const, text: "بول سيزان" }, { id: 'd' as const, text: "أوغست رينوار" }] },
  // Q111
  { textFr: "Dans quel grand musée parisien est exposée la Joconde ?", lang: 'ar' as const, text: "في أي متحف باريسي كبير تُعرض الموناليزا؟", explanation: "الموناليزا للفنان ليوناردو دافنشي معروضة في متحف اللوفر بباريس. وهي اللوحة الأكثر شهرة في العالم وإحدى جواهر مجموعة المتحف.", choices: [{ id: 'a' as const, text: "متحف اللوفر" }, { id: 'b' as const, text: "متحف أورسيه" }, { id: 'c' as const, text: "مركز بومبيدو" }, { id: 'd' as const, text: "متحف رودان" }] },
  // Q112
  { textFr: "Quel château célèbre se trouve près de Paris et symbolise le pouvoir royal de Louis XIV ?", lang: 'ar' as const, text: "أي قصر شهير يقع بالقرب من باريس ويرمز للسلطة الملكية للويس الرابع عشر؟", explanation: "كان قصر فرساي المقر الرئيسي لملوك فرنسا من لويس الرابع عشر إلى لويس السادس عشر. بُني في القرن السابع عشر ويرمز لقوة الملكية المطلقة.", choices: [{ id: 'a' as const, text: "قصر فرساي" }, { id: 'b' as const, text: "قصر شامبور" }, { id: 'c' as const, text: "قصر فونتينبلو" }, { id: 'd' as const, text: "قصر شينونسو" }] },
  // Q113
  { textFr: "Où peut-on voir des peintures préhistoriques en France ?", lang: 'ar' as const, text: "أين يمكن رؤية رسومات ما قبل التاريخ في فرنسا؟", explanation: "يضم كهف لاسكو في دوردوني رسومات ما قبل التاريخ يعود تاريخها إلى حوالي 17000 عام. اكتُشف عام 1940 ويُلقب بكنيسة سيستين ما قبل التاريخ.", choices: [{ id: 'a' as const, text: "في كهف لاسكو" }, { id: 'b' as const, text: "في قصر فرساي" }, { id: 'c' as const, text: "في متحف اللوفر" }, { id: 'd' as const, text: "في كاتدرائية شارتر" }] },
  // Q114
  { textFr: "Quel peintre célèbre a peint les Nymphéas ?", lang: 'ar' as const, text: "أي رسام شهير رسم زنابق الماء؟", explanation: "رسم كلود مونيه سلسلة زنابق الماء الشهيرة في حديقته في جيفرني. رُسمت هذه اللوحات الانطباعية بين 1895 و1926 وهي معروضة في متحف الأورانجيري بباريس.", choices: [{ id: 'a' as const, text: "كلود مونيه" }, { id: 'b' as const, text: "إدغار ديغا" }, { id: 'c' as const, text: "بول غوغان" }, { id: 'd' as const, text: "إدوار مانيه" }] },
  // Q115
  { textFr: "Que symbolise le 1er mai ?", lang: 'ar' as const, text: "ماذا يرمز الأول من مايو؟", explanation: "الأول من مايو هو عيد العمال في فرنسا وهو يوم عطلة رسمية منذ عام 1947. إنه يوم احتفال بحقوق العمال ويتميز تقليديًا بتقديم أغصان زنبق الوادي.", choices: [{ id: 'a' as const, text: "عيد العمال" }, { id: 'b' as const, text: "العيد الوطني" }, { id: 'c' as const, text: "عيد الموسيقى" }, { id: 'd' as const, text: "عيد النصر" }] },
  // Q116
  { textFr: "Qui était Monsieur Rouget de Lisle ?", lang: 'ar' as const, text: "من كان السيد روجيه دو ليل؟", explanation: "كلود جوزيف روجيه دو ليل (1760-1836) كان ضابطًا ومؤلفًا موسيقيًا فرنسيًا مؤلف النشيد الوطني لامارسييز عام 1792. أصبح هذا النشيد الوطني الفرنسي.", choices: [{ id: 'a' as const, text: "مؤلف النشيد الوطني لامارسييز" }, { id: 'b' as const, text: "مؤسس الجمهورية الخامسة" }, { id: 'c' as const, text: "جنرال عند نابليون" }, { id: 'd' as const, text: "فيلسوف من عصر التنوير" }] },
  // Q117
  { textFr: "À quelle occasion a été construite la tour Eiffel ?", lang: 'ar' as const, text: "بأي مناسبة بُني برج إيفل؟", explanation: "بُني برج إيفل للمعرض العالمي عام 1889 الذي احتفل بالذكرى المئوية للثورة الفرنسية. صممه غوستاف إيفل وكان من المفترض تفكيكه بعد المعرض.", choices: [{ id: 'a' as const, text: "المعرض العالمي عام 1889" }, { id: 'b' as const, text: "الألعاب الأولمبية عام 1900" }, { id: 'c' as const, text: "انتصار 1918" }, { id: 'd' as const, text: "تتويج نابليون" }] },
  // Q118
  { textFr: "Qui était un célèbre compositeur français ?", lang: 'ar' as const, text: "من كان مؤلفًا موسيقيًا فرنسيًا شهيرًا؟", explanation: "موريس رافيل (1875-1937) كان مؤلفًا موسيقيًا فرنسيًا مؤلف البوليرو الشهير. وهو أحد أعظم المؤلفين الفرنسيين في القرن العشرين مع كلود ديبوسي.", choices: [{ id: 'a' as const, text: "موريس رافيل" }, { id: 'b' as const, text: "جوزيبي فيردي" }, { id: 'c' as const, text: "ريتشارد فاغنر" }, { id: 'd' as const, text: "بيوتر تشايكوفسكي" }] },
  // Q119
  { textFr: "Quel monument historique se trouve sur une île en Normandie ?", lang: 'ar' as const, text: "أي معلم تاريخي يقع على جزيرة في نورماندي؟", explanation: "مون سان ميشيل دير من العصور الوسطى يقع على جزيرة صخرية في نورماندي. وهو أحد أكثر المواقع زيارة في فرنسا ومصنف في التراث العالمي لليونسكو.", choices: [{ id: 'a' as const, text: "مون سان ميشيل" }, { id: 'b' as const, text: "قصر شامبور" }, { id: 'c' as const, text: "جسر دو غار" }, { id: 'd' as const, text: "مدينة كاركاسون" }] },
  // Q120
  { textFr: "Quelle île fait partie des Antilles françaises ?", lang: 'ar' as const, text: "أي جزيرة تنتمي إلى جزر الأنتيل الفرنسية؟", explanation: "غوادلوب جزء من جزر الأنتيل الفرنسية في البحر الكاريبي. وهي إقليم ومنطقة فرنسية فيما وراء البحار تتكون من عدة جزر.", choices: [{ id: 'a' as const, text: "غوادلوب" }, { id: 'b' as const, text: "كوبا" }, { id: 'c' as const, text: "جامايكا" }, { id: 'd' as const, text: "بورتوريكو" }] },
  // Q121
  { textFr: "Quelle île est française ?", lang: 'ar' as const, text: "أي جزيرة فرنسية؟", explanation: "كاليدونيا الجديدة إقليم فرنسي يقع في المحيط الهادئ. وهي مجموعة ذات وضع خاص فريد ضمن الجمهورية الفرنسية.", choices: [{ id: 'a' as const, text: "كاليدونيا الجديدة" }, { id: 'b' as const, text: "جزر البهاما" }, { id: 'c' as const, text: "جزر المالديف" }, { id: 'd' as const, text: "بورنيو" }] },
  // Q122
  { textFr: "Quelle est la plus haute montagne de France ?", lang: 'ar' as const, text: "ما هي أعلى قمة جبلية في فرنسا؟", explanation: "جبل مون بلان بارتفاع 4809 أمتار هو أعلى جبل في فرنسا وأوروبا الغربية. يقع في جبال الألب على الحدود بين فرنسا وإيطاليا.", choices: [{ id: 'a' as const, text: "مون بلان" }, { id: 'b' as const, text: "بوي دو دوم" }, { id: 'c' as const, text: "بيك دو ميدي" }, { id: 'd' as const, text: "مون فانتو" }] },
  // Q123
  { textFr: "Quelle île française est située au sud-est du continent africain ?", lang: 'ar' as const, text: "أي جزيرة فرنسية تقع جنوب شرق القارة الأفريقية؟", explanation: "مايوت جزيرة فرنسية تقع في المحيط الهندي جنوب شرق القارة الأفريقية. أصبحت الإقليم الفرنسي رقم 101 عام 2011.", choices: [{ id: 'a' as const, text: "مايوت" }, { id: 'b' as const, text: "مارتينيك" }, { id: 'c' as const, text: "غوادلوب" }, { id: 'd' as const, text: "سان بيير وميكلون" }] },
  // Q124
  { textFr: "Quel département français a une frontière avec le Brésil ?", lang: 'ar' as const, text: "أي إقليم فرنسي له حدود مع البرازيل؟", explanation: "غويانا الفرنسية إقليم فيما وراء البحار يقع في أمريكا الجنوبية ويتقاسم حدودًا مع البرازيل. وهو أكبر إقليم فرنسي من حيث المساحة.", choices: [{ id: 'a' as const, text: "غويانا" }, { id: 'b' as const, text: "مارتينيك" }, { id: 'c' as const, text: "لاريونيون" }, { id: 'd' as const, text: "مايوت" }] },
  // Q125
  { textFr: "De quelle ville française décolle la fusée Ariane ?", lang: 'ar' as const, text: "من أي مدينة فرنسية ينطلق صاروخ أريان؟", explanation: "ينطلق صاروخ أريان من كورو في غويانا الفرنسية. مركز الفضاء الغوياني هو قاعدة إطلاق وكالة الفضاء الأوروبية منذ عام 1968.", choices: [{ id: 'a' as const, text: "كورو" }, { id: 'b' as const, text: "تولوز" }, { id: 'c' as const, text: "بوردو" }, { id: 'd' as const, text: "مرسيليا" }] },
  // Q126
  { textFr: "Quel est le principal port maritime de France ?", lang: 'ar' as const, text: "ما هو الميناء البحري الرئيسي في فرنسا؟", explanation: "مرسيليا هي الميناء البحري الرئيسي في فرنسا والميناء الأول في البحر الأبيض المتوسط. يعالج ميناء مرسيليا الكبير ملايين الأطنان من البضائع سنويًا.", choices: [{ id: 'a' as const, text: "مرسيليا" }, { id: 'b' as const, text: "نانت" }, { id: 'c' as const, text: "بريست" }, { id: 'd' as const, text: "بوردو" }] },
  // Q127
  { textFr: "Quel est le chef-lieu de la région Auvergne-Rhône-Alpes ?", lang: 'ar' as const, text: "ما هي عاصمة منطقة أوفيرن-رون-ألب؟", explanation: "ليون هي عاصمة منطقة أوفيرن-رون-ألب. وهي ثالث أكبر مدينة في فرنسا ومركز اقتصادي وثقافي مهم.", choices: [{ id: 'a' as const, text: "ليون" }, { id: 'b' as const, text: "كليرمون فيران" }, { id: 'c' as const, text: "غرونوبل" }, { id: 'd' as const, text: "سانت إتيان" }] },
  // Q128
  { textFr: "Quel est le chef-lieu de la région Bretagne ?", lang: 'ar' as const, text: "ما هي عاصمة منطقة بريتاني؟", explanation: "رين هي عاصمة منطقة بريتاني. وهي مدينة نشطة وجامعية تقع في غرب فرنسا.", choices: [{ id: 'a' as const, text: "رين" }, { id: 'b' as const, text: "بريست" }, { id: 'c' as const, text: "نانت" }, { id: 'd' as const, text: "كامبير" }] },
  // Q129
  { textFr: "Quel est le chef-lieu de la région Provence-Alpes-Côte d'Azur ?", lang: 'ar' as const, text: "ما هي عاصمة منطقة بروفانس-ألب-كوت دازور؟", explanation: "مرسيليا هي عاصمة منطقة بروفانس-ألب-كوت دازور. وهي ثاني أكبر مدينة في فرنسا وميناء رئيسي في البحر الأبيض المتوسط.", choices: [{ id: 'a' as const, text: "مرسيليا" }, { id: 'b' as const, text: "نيس" }, { id: 'c' as const, text: "تولون" }, { id: 'd' as const, text: "إكس أون بروفانس" }] },
  // Q130
  { textFr: "Quel est le 101e département français depuis 2011 ?", lang: 'ar' as const, text: "ما هو الإقليم الفرنسي رقم 101 منذ عام 2011؟", explanation: "أصبحت مايوت الإقليم الفرنسي رقم 101 في 31 مارس 2011 بعد استفتاء 2009. وهي أحدث إقليم فيما وراء البحار انضم إلى الجمهورية الفرنسية.", choices: [{ id: 'a' as const, text: "مايوت" }, { id: 'b' as const, text: "غويانا" }, { id: 'c' as const, text: "كاليدونيا الجديدة" }, { id: 'd' as const, text: "سان مارتان" }] },
  // Q131
  { textFr: "Quelle région française est réputée pour ses stations de ski ?", lang: 'ar' as const, text: "أي منطقة فرنسية مشهورة بمنتجعات التزلج؟", explanation: "منطقة أوفيرن-رون-ألب هي الأكثر شهرة بمنتجعات التزلج في فرنسا. تضم العديد من المنتجعات الجبلية الشهيرة مثل شاموني وليدوزالب وفال ديزير.", choices: [{ id: 'a' as const, text: "أوفيرن-رون-ألب" }, { id: 'b' as const, text: "إيل دو فرانس" }, { id: 'c' as const, text: "نوفيل أكيتان" }, { id: 'd' as const, text: "بريتاني" }] },
];
