export const theme5Fa = [
  // Q1
  { textFr: "Quel numéro d'urgence permet d'appeler le SAMU ?", lang: 'fa' as const, text: "شماره اورژانس برای تماس با سامو (SAMU) چیست؟", explanation: "شماره ۱۵ شماره اورژانس سامو (خدمات کمک پزشکی فوری) است. این شماره امکان تماس با پزشک ناظر را فراهم می‌کند که وضعیت را ارزیابی کرده و نیروهای امدادی مناسب را اعزام می‌کند.", choices: [{ id: 'a' as const, text: "۱۵" }, { id: 'b' as const, text: "۱۷" }, { id: 'c' as const, text: "۱۸" }, { id: 'd' as const, text: "۱۱۲" }] },
  // Q2
  { textFr: "Quel numéro d'urgence permet d'appeler les pompiers ?", lang: 'fa' as const, text: "شماره اورژانس برای تماس با آتش‌نشانی چیست؟", explanation: "شماره ۱۸ شماره آتش‌نشانان است. این شماره برای گزارش آتش‌سوزی، تصادف یا هر وضعیتی که نیاز به مداخله اورژانسی دارد استفاده می‌شود.", choices: [{ id: 'a' as const, text: "۱۸" }, { id: 'b' as const, text: "۱۵" }, { id: 'c' as const, text: "۱۷" }, { id: 'd' as const, text: "۱۱۴" }] },
  // Q3
  { textFr: "Après avoir obtenu le permis de conduire, que faut-il faire pour pouvoir conduire sa voiture ?", lang: 'fa' as const, text: "پس از دریافت گواهینامه رانندگی، برای رانندگی با خودرو چه کاری باید انجام داد؟", explanation: "برای رانندگی قانونی، باید خودرو خود را نزد یک شرکت بیمه بیمه کنید. بیمه خودرو در فرانسه برای پوشش خسارات وارده به اشخاص ثالث اجباری است.", choices: [{ id: 'a' as const, text: "بیمه کردن خودرو نزد یک شرکت بیمه" }, { id: 'b' as const, text: "ثبت‌نام در اداره پلیس" }, { id: 'c' as const, text: "انجام معاینه پزشکی اجباری" }, { id: 'd' as const, text: "دریافت مجوز ویژه از شهرداری" }] },
  // Q4
  { textFr: "À quelles conditions un mariage est-il reconnu juridiquement ?", lang: 'fa' as const, text: "ازدواج تحت چه شرایطی از نظر قانونی به رسمیت شناخته می‌شود؟", explanation: "در فرانسه، فقط ازدواج مدنی که در شهرداری برگزار می‌شود از نظر قانونی به رسمیت شناخته می‌شود. ازدواج مذهبی بدون انجام ازدواج مدنی قبل از آن، ارزش قانونی ندارد.", choices: [{ id: 'a' as const, text: "اگر در شهرداری برگزار شود (ازدواج مدنی)" }, { id: 'b' as const, text: "اگر در یک مکان مذهبی برگزار شود" }, { id: 'c' as const, text: "اگر توسط خانواده زوجین به رسمیت شناخته شود" }, { id: 'd' as const, text: "اگر توسط یک دفتر اسناد رسمی سازماندهی شود" }] },
  // Q5
  { textFr: "Quand faut-il déclarer son enfant au service d'état civil de la mairie ?", lang: 'fa' as const, text: "چه زمانی باید فرزند خود را در اداره ثبت احوال شهرداری اعلام کرد؟", explanation: "اعلام تولد باید ظرف ۵ روز پس از تولد در شهرداری محل تولد انجام شود. این مهلت توسط قانون تعیین شده است.", choices: [{ id: 'a' as const, text: "ظرف ۵ روز پس از تولد" }, { id: 'b' as const, text: "ظرف ۳۰ روز پس از تولد" }, { id: 'c' as const, text: "ظرف ۳ ماه پس از تولد" }, { id: 'd' as const, text: "قبل از ترخیص از بیمارستان" }] },
  // Q6
  { textFr: "Le travail non déclaré est :", lang: 'fa' as const, text: "کار اعلام‌نشده (غیررسمی):", explanation: "کار اعلام‌نشده (کار سیاه) طبق قانون ممنوع است. این کار، کارگر را از حمایت اجتماعی محروم می‌کند و کارفرما و کارگر را در معرض مجازات‌های کیفری و مالی قرار می‌دهد.", choices: [{ id: 'a' as const, text: "طبق قانون ممنوع است" }, { id: 'b' as const, text: "برای کارهای کوچک مجاز است" }, { id: 'c' as const, text: "اگر کارگر موافق باشد قابل تحمل است" }, { id: 'd' as const, text: "برای کارگران خارجی مجاز است" }] },
  // Q7
  { textFr: "Que doit faire un employeur pour fixer un salaire ?", lang: 'fa' as const, text: "کارفرما برای تعیین حقوق باید چه کاری انجام دهد؟", explanation: "کارفرما باید حداقل دستمزد (SMIC) و قراردادهای جمعی قابل اجرا را رعایت کند. او نمی‌تواند حقوقی کمتر از حداقل قانونی تعیین کند.", choices: [{ id: 'a' as const, text: "حداقل SMIC و قرارداد جمعی را رعایت کند" }, { id: 'b' as const, text: "مبلغ را آزادانه و بدون هیچ محدودیتی تعیین کند" }, { id: 'c' as const, text: "از شهرداری مجوز بگیرد" }, { id: 'd' as const, text: "با سایر کارفرمایان محله مشورت کند" }] },
  // Q8
  { textFr: "Qu'est-ce que le SMIC ?", lang: 'fa' as const, text: "SMIC چیست؟", explanation: "SMIC حداقل دستمزد بین‌حرفه‌ای رشد است. این حداقل دستمزد ساعتی قانونی است که هیچ کارگری در فرانسه نمی‌تواند کمتر از آن دستمزد دریافت کند.", choices: [{ id: 'a' as const, text: "حداقل دستمزد قانونی که کارگر نمی‌تواند کمتر از آن دریافت کند" }, { id: 'b' as const, text: "میانگین حقوق فرانسوی‌ها" }, { id: 'c' as const, text: "کمک مالی دولتی به بیکاران" }, { id: 'd' as const, text: "حداکثر حقوق مجاز طبق قانون" }] },
  // Q9
  { textFr: "Quelle est la première démarche à réaliser pour chercher un emploi ?", lang: 'fa' as const, text: "اولین اقدام برای جستجوی کار چیست؟", explanation: "اولین اقدام برای جستجوی کار ثبت‌نام در فرانس تراوای (France Travail، که قبلاً پول آمپلوا نام داشت) است. این سازمان جویندگان کار را همراهی می‌کند و می‌تواند مقرری بیکاری پرداخت کند.", choices: [{ id: 'a' as const, text: "ثبت‌نام در فرانس تراوای (France Travail، قبلاً Pôle emploi)" }, { id: 'b' as const, text: "نوشتن مستقیم نامه به رئیس‌جمهور" }, { id: 'c' as const, text: "ثبت‌نام در شهرداری محل سکونت" }, { id: 'd' as const, text: "انتشار آگهی در روزنامه" }] },
  // Q10
  { textFr: "Quelle est la durée légale du temps de travail par semaine ?", lang: 'fa' as const, text: "مدت قانونی کار در هفته چقدر است؟", explanation: "مدت قانونی کار در فرانسه ۳۵ ساعت در هفته است. فراتر از آن، اضافه‌کاری مشمول افزایش حقوق یا استراحت جبرانی می‌شود.", choices: [{ id: 'a' as const, text: "۳۵ ساعت" }, { id: 'b' as const, text: "۳۹ ساعت" }, { id: 'c' as const, text: "۴۰ ساعت" }, { id: 'd' as const, text: "۳۲ ساعت" }] },
  // Q11
  { textFr: "Qui est aidé par France Travail ?", lang: 'fa' as const, text: "فرانس تراوای به چه کسانی کمک می‌کند؟", explanation: "فرانس تراوای (قبلاً Pôle emploi) به افرادی که به دنبال کار هستند کمک می‌کند. این سازمان همراهی شخصی، آموزش و پرداخت مقرری بیکاری ارائه می‌دهد.", choices: [{ id: 'a' as const, text: "افرادی که به دنبال کار هستند" }, { id: 'b' as const, text: "فقط بازنشستگان" }, { id: 'c' as const, text: "فقط کارفرمایان" }, { id: 'd' as const, text: "دانشجویان در دوره تحصیل اولیه" }] },
  // Q12
  { textFr: "Une personne étrangère en situation régulière peut créer son entreprise :", lang: 'fa' as const, text: "یک فرد خارجی دارای اقامت قانونی می‌تواند کسب‌وکار خود را راه‌اندازی کند:", explanation: "در فرانسه، یک فرد خارجی دارای اقامت قانونی حق ایجاد کسب‌وکار خود را دارد، مانند هر شهروند فرانسوی. اگر اجازه اقامت اجازه دهد، محدودیت ملیتی برای کارآفرینی وجود ندارد.", choices: [{ id: 'a' as const, text: "بله، مانند هر فرد دیگری" }, { id: 'b' as const, text: "خیر، فقط فرانسوی‌ها می‌توانند" }, { id: 'c' as const, text: "فقط با مجوز ویژه از استاندار" }, { id: 'd' as const, text: "فقط پس از ۱۰ سال اقامت در فرانسه" }] },
  // Q13
  { textFr: "Une femme peut-elle créer son entreprise ?", lang: 'fa' as const, text: "آیا یک زن می‌تواند کسب‌وکار خود را راه‌اندازی کند؟", explanation: "بله، یک زن می‌تواند در فرانسه کسب‌وکار خود را ایجاد کند. برابری بین زنان و مردان یک اصل بنیادین جمهوری است، از جمله در حوزه اقتصادی و حرفه‌ای.", choices: [{ id: 'a' as const, text: "بله، با همان شرایط یک مرد" }, { id: 'b' as const, text: "خیر، باید رضایت شوهرش را بگیرد" }, { id: 'c' as const, text: "فقط در برخی حوزه‌های فعالیت" }, { id: 'd' as const, text: "فقط اگر تابعیت فرانسوی داشته باشد" }] },
  // Q14
  { textFr: "À partir de quel âge un mineur peut-il travailler ?", lang: 'fa' as const, text: "یک فرد زیر سن قانونی از چه سنی می‌تواند کار کند؟", explanation: "در فرانسه، یک فرد زیر سن قانونی می‌تواند از ۱۶ سالگی با اجازه والدین کار کند. استثناهایی برای کارآموزی از ۱۵ سالگی تحت شرایط خاصی وجود دارد.", choices: [{ id: 'a' as const, text: "۱۶ سال" }, { id: 'b' as const, text: "۱۴ سال" }, { id: 'c' as const, text: "۱۸ سال" }, { id: 'd' as const, text: "۱۲ سال" }] },
  // Q15
  { textFr: "Auprès de quel organisme faut-il demander le remboursement des frais de santé ?", lang: 'fa' as const, text: "برای درخواست بازپرداخت هزینه‌های درمانی باید به کدام سازمان مراجعه کرد؟", explanation: "برای درخواست بازپرداخت هزینه‌های درمانی باید به تأمین اجتماعی (بیمه بیماری / CPAM) مراجعه کرد. این سازمان بخشی از هزینه‌های پزشکی را پوشش می‌دهد.", choices: [{ id: 'a' as const, text: "تأمین اجتماعی (بیمه بیماری)" }, { id: 'b' as const, text: "شهرداری" }, { id: 'c' as const, text: "فرانس تراوای" }, { id: 'd' as const, text: "بانک فرانسه" }] },
  // Q16
  { textFr: "Qu'est-ce qu'un numéro d'urgence ?", lang: 'fa' as const, text: "شماره اورژانس چیست؟", explanation: "شماره اورژانس یک شماره تلفن رایگان است که ۲۴ ساعته در دسترس است و امکان تماس با خدمات امدادی (سامو، آتش‌نشانی، پلیس) را در مواقع اضطراری فراهم می‌کند.", choices: [{ id: 'a' as const, text: "شماره رایگان برای تماس با خدمات امدادی در هر زمان" }, { id: 'b' as const, text: "شماره پولی مخصوص پزشکان" }, { id: 'c' as const, text: "شماره‌ای که فقط در طول روز در دسترس است" }, { id: 'd' as const, text: "شماره‌ای برای تماس با بیمه مکمل" }] },
  // Q17
  { textFr: "Concernant l'accès aux soins, quelle proposition est correcte ?", lang: 'fa' as const, text: "درباره دسترسی به مراقبت‌های بهداشتی، کدام گزاره صحیح است؟", explanation: "در فرانسه، هر فردی حق دارد درمان شود، صرف‌نظر از ملیت یا وضعیت مالی. دسترسی به مراقبت‌های بهداشتی یک حق بنیادین تضمین‌شده توسط قانون است.", choices: [{ id: 'a' as const, text: "هر فردی حق دارد درمان شود" }, { id: 'b' as const, text: "فقط شهروندان فرانسوی به مراقبت‌های بهداشتی دسترسی دارند" }, { id: 'c' as const, text: "دسترسی به مراقبت‌های بهداشتی به سطح درآمد بستگی دارد" }, { id: 'd' as const, text: "برای مراجعه به پزشک باید مجوز استانداری داشت" }] },
  // Q18
  { textFr: "En cas de problème de santé non urgent, à qui faut-il s'adresser en premier ?", lang: 'fa' as const, text: "در صورت مشکل بهداشتی غیرفوری، ابتدا باید به چه کسی مراجعه کرد؟", explanation: "در صورت مشکل بهداشتی غیرفوری، ابتدا باید به پزشک معالج خود مراجعه کرد. او مراقبت‌ها را هماهنگ می‌کند و در صورت نیاز به متخصص ارجاع می‌دهد. این کار از شلوغی اورژانس بیمارستان جلوگیری می‌کند.", choices: [{ id: 'a' as const, text: "به پزشک معالج خود" }, { id: 'b' as const, text: "به اورژانس بیمارستان" }, { id: 'c' as const, text: "به داروخانه" }, { id: 'd' as const, text: "به سامو با شماره ۱۵" }] },
  // Q19
  { textFr: "Quel est le rôle du médecin traitant ?", lang: 'fa' as const, text: "نقش پزشک معالج چیست؟", explanation: "پزشک معالج پیگیری پزشکی کلی بیمار را بر عهده دارد. او مراقبت‌ها را هماهنگ می‌کند، در صورت نیاز به متخصص ارجاع می‌دهد و پرونده پزشکی را به‌روز نگه می‌دارد. او اولین مرجع برای سؤالات بهداشتی است.", choices: [{ id: 'a' as const, text: "پیگیری پزشکی و هماهنگی مراقبت‌های بیمار" }, { id: 'b' as const, text: "فقط تجویز داروهای ژنریک" }, { id: 'c' as const, text: "مدیریت اورژانس بیمارستان" }, { id: 'd' as const, text: "بازپرداخت هزینه‌های درمانی" }] },
  // Q20
  { textFr: "Dans quelles situations doit-on se rendre aux urgences de l'hôpital ?", lang: 'fa' as const, text: "در چه شرایطی باید به اورژانس بیمارستان مراجعه کرد؟", explanation: "اورژانس بیمارستان برای وضعیت‌های جدی که نیاز به مراقبت فوری دارند اختصاص داده شده است: تصادف شدید، درد شدید، مشکل تنفسی و غیره. برای مشکلات غیرفوری، باید به پزشک معالج مراجعه کرد.", choices: [{ id: 'a' as const, text: "در صورت تصادف شدید یا وضعیتی که جان را تهدید می‌کند" }, { id: 'b' as const, text: "برای یک سرماخوردگی ساده یا آنفولانزای خفیف" }, { id: 'c' as const, text: "برای تمدید نسخه" }, { id: 'd' as const, text: "برای دریافت گواهی پزشکی ورزشی" }] },
  // Q21
  { textFr: "Quel est l'objectif des vaccinations obligatoires ?", lang: 'fa' as const, text: "هدف واکسیناسیون‌های اجباری چیست؟", explanation: "واکسیناسیون‌های اجباری هدفشان حفاظت از سلامت فردی و جمعی با جلوگیری از شیوع بیماری‌های جدی است. این اصل حفاظت جمعی نام دارد.", choices: [{ id: 'a' as const, text: "حفاظت از سلامت فردی و جمعی در برابر بیماری‌های جدی" }, { id: 'b' as const, text: "ایجاد سود برای شرکت‌های داروسازی" }, { id: 'c' as const, text: "کنترل جمعیت" }, { id: 'd' as const, text: "جایگزینی مراجعه به پزشک" }] },
  // Q22
  { textFr: "À quoi sert la carte Vitale ?", lang: 'fa' as const, text: "کارت ویتال (Vitale) چه کاربردی دارد؟", explanation: "کارت ویتال، کارت بیمه بیماری است. این کارت امکان بازپرداخت سریع‌تر هزینه‌های درمانی توسط تأمین اجتماعی را فراهم می‌کند. این کارت حاوی اطلاعات اداری بیمه‌شده است.", choices: [{ id: 'a' as const, text: "برای بازپرداخت هزینه‌های درمانی توسط تأمین اجتماعی" }, { id: 'b' as const, text: "برای دریافت تخفیف در داروخانه‌ها" }, { id: 'c' as const, text: "برای اثبات هویت" }, { id: 'd' as const, text: "برای پرداخت مالیات" }] },
  // Q23
  { textFr: "À quoi sert une mutuelle santé ?", lang: 'fa' as const, text: "بیمه مکمل سلامت چه کاربردی دارد؟", explanation: "بیمه مکمل سلامت برای تکمیل بازپرداخت‌های تأمین اجتماعی به کار می‌رود. این بیمه تمام یا بخشی از هزینه‌های درمانی باقی‌مانده بر عهده بیمه‌شده را پوشش می‌دهد.", choices: [{ id: 'a' as const, text: "تکمیل بازپرداخت‌های تأمین اجتماعی" }, { id: 'b' as const, text: "جایگزینی تأمین اجتماعی" }, { id: 'c' as const, text: "یافتن کار" }, { id: 'd' as const, text: "تأمین مالی بازنشستگی" }] },
  // Q24
  { textFr: "Jusqu'à quel âge l'école est-elle obligatoire ?", lang: 'fa' as const, text: "تحصیل تا چه سنی اجباری است؟", explanation: "آموزش در فرانسه برای تمام کودکان ۳ تا ۱۶ ساله اجباری است. از قانون ۲۰۱۹، تعهد آموزشی از ۳ سالگی آغاز و تا ۱۶ سالگی ادامه دارد.", choices: [{ id: 'a' as const, text: "۱۶ سال" }, { id: 'b' as const, text: "۱۴ سال" }, { id: 'c' as const, text: "۱۸ سال" }, { id: 'd' as const, text: "۱۲ سال" }] },
  // Q25
  { textFr: "L'autorité parentale prévoit l'obligation :", lang: 'fa' as const, text: "حق و مسئولیت والدینی شامل تعهد زیر می‌شود:", explanation: "حق و مسئولیت والدینی شامل تعهد حفاظت از کودک، تأمین آموزش و امکان رشد او می‌شود. والدین باید از سلامت، امنیت و اخلاق او مراقبت کنند.", choices: [{ id: 'a' as const, text: "حفاظت، آموزش و تأمین رشد کودک" }, { id: 'b' as const, text: "اجازه دادن به کودک برای تصمیم‌گیری درباره آینده‌اش از ۱۰ سالگی" }, { id: 'c' as const, text: "سپردن کودک به دولت از بدو تولد" }, { id: 'd' as const, text: "ثبت‌نام کودک در مدرسه خصوصی" }] },
  // Q26
  { textFr: "Pour qui l'école est-elle obligatoire ?", lang: 'fa' as const, text: "تحصیل برای چه کسانی اجباری است؟", explanation: "تحصیل (آموزش) برای تمام کودکان ساکن فرانسه، از ۳ تا ۱۶ سال، صرف‌نظر از ملیت یا وضعیت اداری آن‌ها اجباری است.", choices: [{ id: 'a' as const, text: "برای تمام کودکان ساکن فرانسه، از ۳ تا ۱۶ سال" }, { id: 'b' as const, text: "فقط برای کودکان دارای تابعیت فرانسوی" }, { id: 'c' as const, text: "فقط برای پسران" }, { id: 'd' as const, text: "برای کودکان ۶ تا ۱۸ سال" }] },
  // Q27
  { textFr: "Quel diplôme obtient-on à la fin du lycée ?", lang: 'fa' as const, text: "در پایان دبیرستان چه مدرکی دریافت می‌شود؟", explanation: "دیپلم بکالوریا (bac) مدرکی است که در پایان دبیرستان دریافت می‌شود. این مدرک پایان تحصیلات متوسطه را تأیید می‌کند و امکان ورود به آموزش عالی را فراهم می‌کند.", choices: [{ id: 'a' as const, text: "بکالوریا" }, { id: 'b' as const, text: "دیپلم راهنمایی" }, { id: 'c' as const, text: "CAP (گواهی مهارت حرفه‌ای)" }, { id: 'd' as const, text: "لیسانس" }] },
  // Q28
  { textFr: "Dans quels établissements scolaires vont les élèves après l'école élémentaire ?", lang: 'fa' as const, text: "دانش‌آموزان پس از دبستان به کدام مؤسسه آموزشی می‌روند؟", explanation: "پس از دبستان، دانش‌آموزان به راهنمایی (collège) می‌روند. راهنمایی دانش‌آموزان پایه ششم تا سوم را، معمولاً از ۱۱ تا ۱۵ سال، پذیرش می‌کند.", choices: [{ id: 'a' as const, text: "راهنمایی (collège)" }, { id: 'b' as const, text: "دبیرستان (lycée)" }, { id: 'c' as const, text: "دانشگاه" }, { id: 'd' as const, text: "مهدکودک" }] },
  // Q29
  { textFr: "Un enfant inscrit à l'école :", lang: 'fa' as const, text: "کودکی که در مدرسه ثبت‌نام شده:", explanation: "کودکی که در مدرسه ثبت‌نام شده باید به طور منظم به مدرسه برود. حضور منظم در مدرسه یک تعهد قانونی است. غیبت‌های غیرموجه می‌تواند منجر به مجازات والدین شود.", choices: [{ id: 'a' as const, text: "باید به طور منظم به مدرسه برود (تعهد حضور)" }, { id: 'b' as const, text: "می‌تواند هر وقت بخواهد غیبت کند" }, { id: 'c' as const, text: "مجبور نیست تمام دروس را دنبال کند" }, { id: 'd' as const, text: "می‌تواند هر لحظه از روز مدرسه را ترک کند" }] },
  // Q30
  { textFr: "Les enfants qui ne parlent pas français :", lang: 'fa' as const, text: "کودکانی که فرانسوی صحبت نمی‌کنند:", explanation: "کودکانی که فرانسوی صحبت نمی‌کنند از آموزش ویژه‌ای برای یادگیری فرانسوی بهره‌مند می‌شوند. برنامه‌های ویژه (UPE2A) در مدارس برای همراهی آن‌ها در یادگیری زبان وجود دارد.", choices: [{ id: 'a' as const, text: "از آموزش ویژه برای یادگیری فرانسوی در مدرسه بهره‌مند می‌شوند" }, { id: 'b' as const, text: "نمی‌توانند در مدرسه دولتی ثبت‌نام کنند" }, { id: 'c' as const, text: "باید ابتدا فرانسوی یاد بگیرند قبل از رفتن به مدرسه" }, { id: 'd' as const, text: "به مدارس ویژه خصوصی هدایت می‌شوند" }] },
  // Q31
  { textFr: "Quel mariage est reconnu par l'État ?", lang: 'fa' as const, text: "کدام ازدواج توسط دولت به رسمیت شناخته می‌شود؟", explanation: "فقط ازدواج مدنی، که در شهرداری در حضور مأمور ثبت احوال برگزار می‌شود، توسط دولت فرانسه به رسمیت شناخته می‌شود. ازدواج مذهبی هیچ ارزش حقوقی در فرانسه ندارد.", choices: [{ id: 'a' as const, text: "ازدواج مدنی برگزار شده در شهرداری" }, { id: 'b' as const, text: "ازدواج مذهبی برگزار شده در مکان عبادت" }, { id: 'c' as const, text: "ازدواج سنتی برگزار شده در خانواده" }, { id: 'd' as const, text: "هر نوع ازدواجی توسط دولت به رسمیت شناخته می‌شود" }] },
  // Q32
  { textFr: "Auprès de quelle institution les parents peuvent-ils inscrire leur enfant à l'école publique ?", lang: 'fa' as const, text: "والدین می‌توانند فرزند خود را نزد کدام نهاد در مدرسه دولتی ثبت‌نام کنند؟", explanation: "والدین باید فرزند خود را در مدرسه دولتی نزد شهرداری محل سکونت ثبت‌نام کنند. شهرداری مدرسه مربوطه را بر اساس محل سکونت اعلام می‌کند.", choices: [{ id: 'a' as const, text: "شهرداری محل سکونت" }, { id: 'b' as const, text: "استانداری" }, { id: 'c' as const, text: "مدیریت آموزش و پرورش منطقه" }, { id: 'd' as const, text: "وزارت آموزش ملی" }] },
  // Q33
  { textFr: "En cas de divorce, qui exerce l'autorité parentale ?", lang: 'fa' as const, text: "در صورت طلاق، چه کسی حق و مسئولیت والدینی را اعمال می‌کند؟", explanation: "در صورت طلاق، هر دو والد به طور مشترک حق و مسئولیت والدینی را اعمال می‌کنند، مگر اینکه قاضی تصمیم دیگری بگیرد. منافع کودک در تمام تصمیمات اولویت دارد.", choices: [{ id: 'a' as const, text: "هر دو والد به طور مشترک" }, { id: 'b' as const, text: "فقط مادر" }, { id: 'c' as const, text: "فقط پدر" }, { id: 'd' as const, text: "دولت سرپرستی کودک را بر عهده می‌گیرد" }] },
  // Q34
  { textFr: "Quelle aide permet aux personnes qui ont des difficultés financières d'avoir un avocat ?", lang: 'fa' as const, text: "کدام کمک به افرادی که مشکلات مالی دارند امکان داشتن وکیل را می‌دهد؟", explanation: "کمک حقوقی قضایی به افرادی با درآمد کم امکان بهره‌مندی از وکیلی را می‌دهد که هزینه‌اش تماماً یا بخشی توسط دولت تأمین می‌شود. این کمک دسترسی همه به عدالت را تضمین می‌کند.", choices: [{ id: 'a' as const, text: "کمک حقوقی قضایی" }, { id: 'b' as const, text: "RSA (درآمد حمایت فعال)" }, { id: 'c' as const, text: "کمک هزینه مسکن" }, { id: 'd' as const, text: "CMU (پوشش بیمارستانی همگانی)" }] },
  // Q35
  { textFr: "Où faut-il déclarer la naissance d'un enfant ?", lang: 'fa' as const, text: "تولد کودک را باید کجا اعلام کرد؟", explanation: "تولد کودک باید در شهرداری محل تولد، ظرف ۵ روز پس از زایمان اعلام شود. مأمور ثبت احوال سپس سند تولد را صادر می‌کند.", choices: [{ id: 'a' as const, text: "در شهرداری محل تولد" }, { id: 'b' as const, text: "در استانداری" }, { id: 'c' as const, text: "در کلانتری" }, { id: 'd' as const, text: "در دادگاه" }] },
  // Q36
  { textFr: "Quelle est l'une des conditions pour passer l'examen du permis de conduire ?", lang: 'fa' as const, text: "یکی از شرایط شرکت در آزمون گواهینامه رانندگی چیست؟", explanation: "برای شرکت در آزمون گواهینامه رانندگی در فرانسه، باید حداقل ۱۷ سال سن داشت (یا ۱۵ سال برای رانندگی همراه). همچنین باید آزمون آیین‌نامه راهنمایی و رانندگی را گذرانده باشید.", choices: [{ id: 'a' as const, text: "حداقل ۱۷ سال سن داشتن" }, { id: 'b' as const, text: "حداقل ۲۱ سال سن داشتن" }, { id: 'c' as const, text: "تابعیت فرانسوی داشتن" }, { id: 'd' as const, text: "داشتن خودروی شخصی" }] },
  // Q37
  { textFr: "Un bail locatif est valide s'il est :", lang: 'fa' as const, text: "قرارداد اجاره معتبر است اگر:", explanation: "قرارداد اجاره معتبر است اگر توسط مالک و مستأجر امضا شده باشد. باید کتبی باشد و شامل اطلاعات اجباری مانند توصیف مسکن، مبلغ اجاره و مدت باشد.", choices: [{ id: 'a' as const, text: "توسط مالک و مستأجر امضا شده باشد" }, { id: 'b' as const, text: "توسط شهرداری تأیید شده باشد" }, { id: 'c' as const, text: "در دادگاه ثبت شده باشد" }, { id: 'd' as const, text: "الزاماً توسط دفتر اسناد رسمی تأیید شده باشد" }] },
  // Q38
  { textFr: "Où peut-on déposer un lave-vaisselle cassé ?", lang: 'fa' as const, text: "ماشین ظرفشویی خراب را کجا می‌توان تحویل داد؟", explanation: "ماشین ظرفشویی خراب یک زباله الکتریکی و الکترونیکی (DEEE) است. می‌توان آن را در مرکز بازیافت تحویل داد یا هنگام خرید دستگاه جدید مشابه، به صورت رایگان توسط فروشگاه پس گرفته شود.", choices: [{ id: 'a' as const, text: "در مرکز بازیافت یا تحویل به فروشگاه" }, { id: 'b' as const, text: "روی پیاده‌رو جلوی خانه" }, { id: 'c' as const, text: "در سطل زباله خانگی" }, { id: 'd' as const, text: "در ظرف بازیافت شیشه" }] },
  // Q39
  { textFr: "Quel numéro d'urgence permet d'appeler la police ?", lang: 'fa' as const, text: "شماره اورژانس برای تماس با پلیس چیست؟", explanation: "شماره ۱۷ شماره اورژانس برای تماس با پلیس یا ژاندارمری است. این شماره برای گزارش وضعیت اضطراری که نیاز به مداخله نیروهای انتظامی دارد استفاده می‌شود.", choices: [{ id: 'a' as const, text: "۱۷" }, { id: 'b' as const, text: "۱۵" }, { id: 'c' as const, text: "۱۸" }, { id: 'd' as const, text: "۱۱۹" }] },
  // Q40
  { textFr: "À qui est accessible la contraception ?", lang: 'fa' as const, text: "پیشگیری از بارداری در دسترس چه کسانی است؟", explanation: "پیشگیری از بارداری در دسترس همه افراد، از جمله افراد زیر سن قانونی است. دختران زیر سن قانونی می‌توانند بدون اجازه والدین، به صورت رایگان و محرمانه وسایل پیشگیری دریافت کنند.", choices: [{ id: 'a' as const, text: "همه افراد، از جمله زیر سن قانونی" }, { id: 'b' as const, text: "فقط افراد بالای سن قانونی" }, { id: 'c' as const, text: "فقط زنان متأهل" }, { id: 'd' as const, text: "فقط با نسخه متخصص" }] },
  // Q41
  { textFr: "Qu'est-ce que le principe de confidentialité dans le domaine de la santé ?", lang: 'fa' as const, text: "اصل محرمانگی در حوزه سلامت چیست؟", explanation: "اصل محرمانگی (رازداری پزشکی) به این معناست که پزشک نمی‌تواند اطلاعات مربوط به سلامت بیمار خود را بدون رضایت او به اشخاص ثالث فاش کند. این یک حق بنیادین بیمار است.", choices: [{ id: 'a' as const, text: "پزشک نمی‌تواند اطلاعات پزشکی بیمار را بدون رضایت او فاش کند" }, { id: 'b' as const, text: "بیمار نمی‌تواند تشخیص خودش را بداند" }, { id: 'c' as const, text: "نتایج پزشکی برای تحقیقات منتشر می‌شوند" }, { id: 'd' as const, text: "کارفرما به پرونده پزشکی کارمند دسترسی دارد" }] },
  // Q42
  { textFr: "L'inscription à l'Assurance maladie est :", lang: 'fa' as const, text: "ثبت‌نام در بیمه بیماری:", explanation: "ثبت‌نام در بیمه بیماری اجباری است. هر فردی که در فرانسه کار می‌کند یا به صورت پایدار و قانونی اقامت دارد، حق پوشش هزینه‌های درمانی خود را دارد.", choices: [{ id: 'a' as const, text: "اجباری" }, { id: 'b' as const, text: "اختیاری" }, { id: 'c' as const, text: "مخصوص کارمندان" }, { id: 'd' as const, text: "پولی و اختیاری" }] },
  // Q43
  { textFr: "Qui peut demander un congé parental d'éducation ?", lang: 'fa' as const, text: "چه کسی می‌تواند مرخصی والدینی آموزشی درخواست کند؟", explanation: "مرخصی والدینی آموزشی می‌تواند توسط پدر یا مادر، بدون تمایز، درخواست شود. این مرخصی امکان توقف یا کاهش فعالیت حرفه‌ای برای مراقبت از فرزند را فراهم می‌کند.", choices: [{ id: 'a' as const, text: "پدر یا مادر" }, { id: 'b' as const, text: "فقط مادر" }, { id: 'c' as const, text: "فقط پدر" }, { id: 'd' as const, text: "هیچ‌کدام، خودکار است" }] },
  // Q44
  { textFr: "Quelles sont les affaires traitées par le conseil de prud'hommes ?", lang: 'fa' as const, text: "شورای حل اختلاف کار چه پرونده‌هایی را رسیدگی می‌کند؟", explanation: "شورای حل اختلاف کار (prud'hommes) به اختلافات بین کارمندان و کارفرمایان مربوط به قرارداد کار رسیدگی می‌کند: اخراج ناعادلانه، عدم پرداخت حقوق، آزار در محل کار و غیره.", choices: [{ id: 'a' as const, text: "اختلافات بین کارمندان و کارفرمایان مربوط به قرارداد کار" }, { id: 'b' as const, text: "پرونده‌های طلاق" }, { id: 'c' as const, text: "جرایم کیفری" }, { id: 'd' as const, text: "اختلافات بین همسایگان" }] },
  // Q45
  { textFr: "Lorsqu'un employeur veut qu'un salarié travaille plus longtemps que la durée prévue dans le contrat de travail :", lang: 'fa' as const, text: "وقتی کارفرما می‌خواهد کارمند بیشتر از مدت پیش‌بینی‌شده در قرارداد کار کند:", explanation: "اضافه‌کاری باید با افزایش حقوق پرداخت شود یا با استراحت جبران شود. کارفرما نمی‌تواند بدون رعایت قوانین، اضافه‌کاری تحمیل کند.", choices: [{ id: 'a' as const, text: "باید اضافه‌کاری را با افزایش حقوق پرداخت کند" }, { id: 'b' as const, text: "می‌تواند بدون جبران آن را الزام کند" }, { id: 'c' as const, text: "کارمند باید همیشه رد کند" }, { id: 'd' as const, text: "در همه موارد غیرقانونی است" }] },
  // Q46
  { textFr: "Quelle est la mission de France Travail ?", lang: 'fa' as const, text: "مأموریت فرانس تراوای چیست؟", explanation: "فرانس تراوای (قبلاً Pôle emploi) مأموریت دارد جویندگان کار را در جستجوی شغل همراهی کند، مقرری بیکاران را پرداخت کند و به شرکت‌ها در استخدام کمک کند.", choices: [{ id: 'a' as const, text: "همراهی جویندگان کار و پرداخت مقرری بیکاران" }, { id: 'b' as const, text: "تعیین حقوق در شرکت‌ها" }, { id: 'c' as const, text: "نظارت بر شرایط کار در شرکت‌ها" }, { id: 'd' as const, text: "مدیریت بازنشستگی کارمندان" }] },
  // Q47
  { textFr: "Dans une entreprise, le droit syndical permet :", lang: 'fa' as const, text: "در یک شرکت، حق سندیکایی اجازه می‌دهد:", explanation: "حق سندیکایی به کارمندان اجازه می‌دهد برای دفاع از منافع حرفه‌ای خود گرد هم آیند. سندیکاها شرایط کار و حقوق را با کارفرما مذاکره می‌کنند.", choices: [{ id: 'a' as const, text: "کارمندان برای دفاع از منافع حرفه‌ای خود گرد هم آیند" }, { id: 'b' as const, text: "کارفرما آزادانه اخراج کند" }, { id: 'c' as const, text: "کارمندان هر وقت بخواهند کار نکنند" }, { id: 'd' as const, text: "دولت شرکت را کنترل کند" }] },
  // Q48
  { textFr: "Dans une entreprise, le droit de grève autorise :", lang: 'fa' as const, text: "در یک شرکت، حق اعتصاب اجازه می‌دهد:", explanation: "حق اعتصاب، که در قانون اساسی به رسمیت شناخته شده، به کارمندان اجازه می‌دهد به صورت دسته‌جمعی کار را متوقف کنند تا از مطالبات حرفه‌ای خود دفاع کنند. این یک حق بنیادین در فرانسه است.", choices: [{ id: 'a' as const, text: "کارمندان به صورت دسته‌جمعی کار را متوقف کنند تا از مطالباتشان دفاع کنند" }, { id: 'b' as const, text: "کارفرما بدون اطلاع قبلی شرکت را تعطیل کند" }, { id: 'c' as const, text: "کارمندان تجهیزات شرکت را تخریب کنند" }, { id: 'd' as const, text: "کارمندان دیگر هرگز سر کار برنگردند" }] },
  // Q49
  { textFr: "Quelles sont les conditions pour toucher les allocations chômage ?", lang: 'fa' as const, text: "شرایط دریافت مقرری بیکاری چیست؟", explanation: "برای دریافت مقرری بیکاری، باید به اندازه کافی کار کرده باشید (حداقل ۶ ماه در ۲۴ ماه گذشته)، در فرانس تراوای ثبت‌نام کرده و فعالانه به دنبال کار باشید.", choices: [{ id: 'a' as const, text: "به اندازه کافی کار کرده، در فرانس تراوای ثبت‌نام کرده و فعالانه به دنبال کار باشید" }, { id: 'b' as const, text: "کافی است شغلی نداشته باشید" }, { id: 'c' as const, text: "تابعیت فرانسوی داشته باشید" }, { id: 'd' as const, text: "بالای ۲۵ سال باشید" }] },
  // Q50
  { textFr: "Qu'est-ce que l'école maternelle ?", lang: 'fa' as const, text: "مهدکودک (école maternelle) چیست؟", explanation: "مهدکودک کودکان ۳ تا ۶ ساله را پذیرش می‌کند. این مقطع اولین مرحله تحصیل است و کودکان را برای یادگیری‌های پایه‌ای دبستان آماده می‌کند.", choices: [{ id: 'a' as const, text: "مدرسه‌ای که کودکان ۳ تا ۶ ساله را پذیرش می‌کند" }, { id: 'b' as const, text: "مدرسه‌ای مخصوص دختران" }, { id: 'c' as const, text: "مؤسسه‌ای برای کودکان ۶ تا ۱۱ ساله" }, { id: 'd' as const, text: "مهد کودک تحت مدیریت دولت" }] },
  // Q51
  { textFr: "Comment s'appelle le diplôme passé par les élèves à la fin du collège ?", lang: 'fa' as const, text: "مدرکی که دانش‌آموزان در پایان راهنمایی می‌گیرند چه نام دارد؟", explanation: "دیپلم ملی بروه (DNB)، که معمولاً به آن بروه راهنمایی گفته می‌شود، در پایان کلاس سوم گرفته می‌شود. این مدرک دانش کسب‌شده در دوره راهنمایی را ارزیابی می‌کند.", choices: [{ id: 'a' as const, text: "دیپلم ملی بروه (بروه راهنمایی)" }, { id: 'b' as const, text: "بکالوریا" }, { id: 'c' as const, text: "گواهی تحصیلات ابتدایی" }, { id: 'd' as const, text: "CAP" }] },
  // Q52
  { textFr: "Les parents d'élève ont le droit de :", lang: 'fa' as const, text: "والدین دانش‌آموزان حق دارند:", explanation: "والدین دانش‌آموزان حق مشارکت در زندگی مدرسه را دارند، به ویژه با انتخاب نمایندگان والدین و شرکت در شوراهای مدرسه یا کلاس.", choices: [{ id: 'a' as const, text: "مشارکت در زندگی مدرسه و انتخاب نمایندگان والدین" }, { id: 'b' as const, text: "انتخاب معلمان فرزندشان" }, { id: 'c' as const, text: "تغییر برنامه درسی" }, { id: 'd' as const, text: "تصمیم‌گیری درباره ساعات کلاس" }] },
  // Q53
  { textFr: "Qui peut manger à la cantine scolaire ?", lang: 'fa' as const, text: "چه کسانی می‌توانند در غذاخوری مدرسه غذا بخورند؟", explanation: "تمام دانش‌آموزان ثبت‌نام‌شده در مؤسسه می‌توانند در غذاخوری مدرسه غذا بخورند. دسترسی به غذاخوری مدرسه حقی برای تمام کودکان مدرسه‌ای، بدون تبعیض، است.", choices: [{ id: 'a' as const, text: "تمام دانش‌آموزان ثبت‌نام‌شده در مؤسسه" }, { id: 'b' as const, text: "فقط دانش‌آموزانی که والدینشان کار می‌کنند" }, { id: 'c' as const, text: "فقط دانش‌آموزانی که دور از مدرسه زندگی می‌کنند" }, { id: 'd' as const, text: "فقط دانش‌آموزان بورسیه" }] },
  // Q54
  { textFr: "À quel âge commence l'instruction obligatoire des enfants ?", lang: 'fa' as const, text: "آموزش اجباری کودکان از چه سنی آغاز می‌شود؟", explanation: "از قانون ۲۶ ژوئیه ۲۰۱۹، آموزش از سن ۳ سالگی در فرانسه اجباری است. این مطابق با ورود به مهدکودک است.", choices: [{ id: 'a' as const, text: "۳ سال" }, { id: 'b' as const, text: "۵ سال" }, { id: 'c' as const, text: "۶ سال" }, { id: 'd' as const, text: "۴ سال" }] },
  // Q55
  { textFr: "Quel est l'âge de la majorité ?", lang: 'fa' as const, text: "سن قانونی بلوغ چند سال است؟", explanation: "سن بلوغ قانونی در فرانسه ۱۸ سال است. در این سن، فرد اهلیت حقوقی کامل کسب می‌کند: می‌تواند رأی دهد، قرارداد امضا کند، بدون اجازه والدین ازدواج کند و غیره.", choices: [{ id: 'a' as const, text: "۱۸ سال" }, { id: 'b' as const, text: "۱۶ سال" }, { id: 'c' as const, text: "۲۱ سال" }, { id: 'd' as const, text: "۱۷ سال" }] },
  // Q56
  { textFr: "À l'école, il est interdit aux parents de :", lang: 'fa' as const, text: "در مدرسه، والدین از انجام چه کاری منع شده‌اند:", explanation: "در مدرسه، والدین نمی‌توانند با تدریس برخی دروس اجباری برنامه درسی مخالفت کنند. محتوای آموزشی توسط آموزش ملی تعیین می‌شود و برای همه الزامی است.", choices: [{ id: 'a' as const, text: "مخالفت با تدریس برخی دروس اجباری" }, { id: 'b' as const, text: "شرکت در جلسات والدین و معلمان" }, { id: 'c' as const, text: "مشاهده دفتر برنامه درسی فرزندشان" }, { id: 'd' as const, text: "ملاقات با معلمان فرزندشان" }] },
  // Q57
  { textFr: "Quel motif d'absence est accepté par l'école ?", lang: 'fa' as const, text: "کدام دلیل غیبت توسط مدرسه پذیرفته می‌شود؟", explanation: "بیماری کودک (با گواهی پزشکی) یک دلیل غیبت موجه پذیرفته‌شده توسط مدرسه است. سایر دلایل پذیرفته شامل تعهدات خانوادگی ضروری یا اعیاد مذهبی است.", choices: [{ id: 'a' as const, text: "بیماری کودک" }, { id: 'b' as const, text: "سفر تعطیلات خانوادگی" }, { id: 'c' as const, text: "حراج‌ها در فروشگاه‌ها" }, { id: 'd' as const, text: "خستگی کودک" }] },
  // Q58
  { textFr: "Des parents ne respectent pas l'obligation d'instruction pour leurs enfants. Quelle sanction maximale risquent-ils ?", lang: 'fa' as const, text: "والدینی که تعهد آموزش فرزندانشان را رعایت نمی‌کنند، حداکثر چه مجازاتی در انتظارشان است؟", explanation: "والدینی که تعهد آموزش فرزندانشان را رعایت نمی‌کنند تا ۲ سال حبس و ۳۰,۰۰۰ یورو جریمه نقدی در خطر هستند. آموزش یک تعهد قانونی در فرانسه است.", choices: [{ id: 'a' as const, text: "۲ سال حبس و ۳۰,۰۰۰ یورو جریمه" }, { id: 'b' as const, text: "یک اخطار ساده از شهرداری" }, { id: 'c' as const, text: "جریمه ۱۵۰ یورو" }, { id: 'd' as const, text: "هیچ مجازاتی پیش‌بینی نشده" }] },
  // Q59
  { textFr: "Quand ont lieu les vacances scolaires de Noël ?", lang: 'fa' as const, text: "تعطیلات کریسمس مدارس چه زمانی است؟", explanation: "تعطیلات کریسمس مدارس در دسامبر-ژانویه، معمولاً حدود دو هفته در اطراف ۲۵ دسامبر و ۱ ژانویه برگزار می‌شود. این تعطیلات برای تمام مناطق آموزشی مشترک است.", choices: [{ id: 'a' as const, text: "در دسامبر-ژانویه، حدود دو هفته" }, { id: 'b' as const, text: "در نوامبر، یک هفته" }, { id: 'c' as const, text: "در فوریه، دو هفته" }, { id: 'd' as const, text: "در اکتبر، یک هفته" }] },
  // Q60
  { textFr: "À l'école, un enfant en situation de handicap :", lang: 'fa' as const, text: "در مدرسه، کودک دارای معلولیت:", explanation: "در فرانسه، کودک دارای معلولیت حق دارد در نزدیک‌ترین مدرسه به محل سکونتش ثبت‌نام شود. مدرسه فراگیر یک اصل بنیادین است: هر کودکی حق آموزش متناسب دارد.", choices: [{ id: 'a' as const, text: "حق دارد در نزدیک‌ترین مدرسه به محل سکونتش ثبت‌نام شود" }, { id: 'b' as const, text: "باید حتماً به مؤسسه تخصصی برود" }, { id: 'c' as const, text: "نمی‌تواند به مدرسه برود" }, { id: 'd' as const, text: "باید با یک معلم خصوصی در خانه بماند" }] },
  // Q61
  { textFr: "Quelle action peut réaliser le locataire d'un logement sans l'autorisation du propriétaire ?", lang: 'fa' as const, text: "مستأجر یک مسکن بدون اجازه مالک چه کاری می‌تواند انجام دهد؟", explanation: "مستأجر می‌تواند بدون اجازه مالک تغییرات کوچک (تزئینات، نقاشی، کارهای کوچک) انجام دهد، به شرط آنکه تغییرات ساختاری در مسکن ایجاد نکند.", choices: [{ id: 'a' as const, text: "انجام تغییرات کوچک مانند رنگ‌آمیزی دیوارها یا نصب قفسه" }, { id: 'b' as const, text: "خراب کردن یک دیوار جداکننده" }, { id: 'c' as const, text: "اجاره دادن مسکن به شخص دیگر" }, { id: 'd' as const, text: "تعویض پنجره‌ها و درب ورودی" }] },
  // Q62
  { textFr: "Le stationnement sur une place réservée aux personnes handicapées :", lang: 'fa' as const, text: "پارک کردن در جای مخصوص افراد معلول:", explanation: "پارک کردن در جای مخصوص افراد معلول بدون کارت تحرک فراگیر (CMI) ممنوع است. متخلفان با جریمه ۱۳۵ یورو و توقیف خودرو مواجه می‌شوند.", choices: [{ id: 'a' as const, text: "بدون کارت تحرک فراگیر ممنوع است و جریمه دارد" }, { id: 'b' as const, text: "روزهای یکشنبه برای همه مجاز است" }, { id: 'c' as const, text: "اگر برای مدت کوتاه باشد مجاز است" }, { id: 'd' as const, text: "توسط قانون تنظیم نشده است" }] },
  // Q63
  { textFr: "Si une machine à laver est cassée, il est possible de :", lang: 'fa' as const, text: "اگر ماشین لباسشویی خراب شد، می‌توان:", explanation: "یک لوازم خانگی خراب را می‌توان در مرکز بازیافت تحویل داد یا هنگام خرید دستگاه جدید توسط فروشگاه پس گرفته شود (تعهد بازپس‌گیری ۱ در مقابل ۱). نباید آن را با زباله‌های خانگی دور انداخت.", choices: [{ id: 'a' as const, text: "آن را در مرکز بازیافت تحویل داد یا توسط فروشگاه پس گرفته شود" }, { id: 'b' as const, text: "آن را در سطل زباله خانگی انداخت" }, { id: 'c' as const, text: "آن را روی پیاده‌رو گذاشت" }, { id: 'd' as const, text: "آن را در ظرف بازیافت انداخت" }] },
  // Q64
  { textFr: "Dans quel cas faut-il déclarer son enfant au service d'état civil ?", lang: 'fa' as const, text: "در چه موردی باید فرزند خود را در اداره ثبت احوال اعلام کرد؟", explanation: "باید فرزند خود را در هر بار تولد در اداره ثبت احوال شهرداری اعلام کرد. این اعلام ظرف ۵ روز پس از تولد اجباری است و امکان صدور سند تولد را فراهم می‌کند.", choices: [{ id: 'a' as const, text: "در هر بار تولد فرزند" }, { id: 'b' as const, text: "فقط برای فرزند اول" }, { id: 'c' as const, text: "وقتی کودک وارد مدرسه می‌شود" }, { id: 'd' as const, text: "وقتی کودک به سن ۱۸ سالگی می‌رسد" }] },
  // Q65
  { textFr: "Qui peut demander le divorce de personnes mariées ?", lang: 'fa' as const, text: "چه کسی می‌تواند طلاق افراد متأهل را درخواست کند؟", explanation: "طلاق می‌تواند توسط یکی از زوجین یا هر دو به طور مشترک (طلاق توافقی) درخواست شود. درخواست طلاق حقی است که برای هر یک از همسران به رسمیت شناخته شده است.", choices: [{ id: 'a' as const, text: "یکی از زوجین یا هر دو به طور مشترک" }, { id: 'b' as const, text: "فقط شوهر" }, { id: 'c' as const, text: "فقط خانواده زوجین" }, { id: 'd' as const, text: "شهردار" }] },
  // Q66
  { textFr: "La contraception :", lang: 'fa' as const, text: "پیشگیری از بارداری:", explanation: "پیشگیری از بارداری یک حق در فرانسه است. در دسترس همه، از جمله افراد زیر سن قانونی است و برای افراد زیر ۲۶ سال به صورت رایگان قابل دریافت است. انتخاب روش پیشگیری آزاد است.", choices: [{ id: 'a' as const, text: "حقی است در دسترس همه، از جمله افراد زیر سن قانونی" }, { id: 'b' as const, text: "در فرانسه ممنوع است" }, { id: 'c' as const, text: "نیاز به اجازه همسر دارد" }, { id: 'd' as const, text: "مخصوص افراد متأهل است" }] },
  // Q67
  { textFr: "Qu'est-ce que le tiers payant ?", lang: 'fa' as const, text: "پرداخت شخص ثالث (tiers payant) چیست؟", explanation: "پرداخت شخص ثالث سیستمی است که بیمار را از پرداخت اولیه هزینه‌های درمانی معاف می‌کند. متخصص بهداشت مستقیماً توسط بیمه بیماری و/یا بیمه مکمل پرداخت می‌شود.", choices: [{ id: 'a' as const, text: "سیستمی که بیمار را از پرداخت اولیه هزینه‌های درمانی معاف می‌کند" }, { id: 'b' as const, text: "مالیاتی بر داروها" }, { id: 'c' as const, text: "هزینه اضافی هنگام ویزیت" }, { id: 'd' as const, text: "بیمه اجباری برای پزشکان" }] },
  // Q68
  { textFr: "L'avortement est-il possible en France ?", lang: 'fa' as const, text: "آیا سقط جنین در فرانسه امکان‌پذیر است؟", explanation: "بله، سقط جنین (IVG - وقفه ارادی بارداری) در فرانسه قانونی است. از سال ۲۰۲۲، تا ۱۴ هفته بارداری قابل انجام است. از سال ۲۰۲۴ یک حق قانون اساسی است.", choices: [{ id: 'a' as const, text: "بله، حقی است که توسط قانون تضمین شده" }, { id: 'b' as const, text: "خیر، کاملاً ممنوع است" }, { id: 'c' as const, text: "فقط در صورت خطر برای مادر" }, { id: 'd' as const, text: "فقط با رضایت همسر" }] },
  // Q69
  { textFr: "Quels sont les textes qui définissent les règles au travail ?", lang: 'fa' as const, text: "کدام متون قوانین کار را تعیین می‌کنند؟", explanation: "قوانین کار توسط قانون کار، قراردادهای جمعی و قرارداد کار تعیین می‌شوند. قانون کار حداقل چارچوب قانونی را تعیین می‌کند که هر کارفرمایی باید رعایت کند.", choices: [{ id: 'a' as const, text: "قانون کار، قراردادهای جمعی و قرارداد کار" }, { id: 'b' as const, text: "فقط آیین‌نامه داخلی شرکت" }, { id: 'c' as const, text: "تصمیمات شهردار" }, { id: 'd' as const, text: "توافقات شفاهی بین همکاران" }] },
  // Q70
  { textFr: "Qui a le droit de se syndiquer ?", lang: 'fa' as const, text: "چه کسی حق عضویت در سندیکا دارد؟", explanation: "هر کارمندی حق عضویت در سندیکا دارد، صرف‌نظر از ملیتش. آزادی سندیکایی یک حق بنیادین است که توسط قانون اساسی فرانسه و کنوانسیون‌های بین‌المللی به رسمیت شناخته شده است.", choices: [{ id: 'a' as const, text: "هر کارمندی، صرف‌نظر از ملیتش" }, { id: 'b' as const, text: "فقط کارمندان فرانسوی" }, { id: 'c' as const, text: "فقط مدیران" }, { id: 'd' as const, text: "فقط کارمندان دولت" }] },
  // Q71
  { textFr: "Est-il possible de licencier une femme enceinte ou en congé maternité, en raison de sa grossesse ?", lang: 'fa' as const, text: "آیا امکان اخراج یک زن باردار یا در مرخصی زایمان، به دلیل بارداری‌اش وجود دارد؟", explanation: "خیر، اخراج یک زن به دلیل بارداری یا در طول مرخصی زایمان ممنوع است. قانون زنان باردار را در برابر هرگونه تبعیض مربوط به مادری حمایت می‌کند.", choices: [{ id: 'a' as const, text: "خیر، طبق قانون ممنوع است" }, { id: 'b' as const, text: "بله، کارفرما آزاد است هر کسی را اخراج کند" }, { id: 'c' as const, text: "بله، اما با اطلاع قبلی ۳ ماهه" }, { id: 'd' as const, text: "بله، اگر شرکت مشکلات اقتصادی داشته باشد" }] },
  // Q72
  { textFr: "L'instruction des enfants est obligatoire de :", lang: 'fa' as const, text: "آموزش کودکان اجباری است از:", explanation: "آموزش کودکان از ۳ تا ۱۶ سالگی در فرانسه اجباری است. این تعهد برای تمام کودکان ساکن خاک فرانسه، صرف‌نظر از ملیتشان، اعمال می‌شود.", choices: [{ id: 'a' as const, text: "۳ تا ۱۶ سالگی" }, { id: 'b' as const, text: "۶ تا ۱۶ سالگی" }, { id: 'c' as const, text: "۳ تا ۱۸ سالگی" }, { id: 'd' as const, text: "۵ تا ۱۴ سالگی" }] },
  // Q73
  { textFr: "Quelle est la définition de l'autorité parentale ?", lang: 'fa' as const, text: "تعریف حق و مسئولیت والدینی چیست؟", explanation: "حق و مسئولیت والدینی مجموعه حقوق و وظایف والدین نسبت به فرزند صغیرشان است. هدف آن منافع کودک است: حمایت، سلامت، امنیت، آموزش و رشد او.", choices: [{ id: 'a' as const, text: "مجموعه حقوق و وظایف والدین برای حمایت و آموزش فرزندشان" }, { id: 'b' as const, text: "حق والدین برای تنبیه آزادانه فرزندشان" }, { id: 'c' as const, text: "قدرت دولت بر خانواده‌ها" }, { id: 'd' as const, text: "حق پدربزرگ‌ها و مادربزرگ‌ها بر نوه‌هایشان" }] },
  // Q74
  { textFr: "En tant que parent d'élève, il est possible de :", lang: 'fa' as const, text: "به عنوان والد دانش‌آموز، امکان دارد:", explanation: "به عنوان والد دانش‌آموز، امکان مشارکت در نهادهای مدرسه (شورای مدرسه، شورای کلاس) و انتخاب شدن به عنوان نماینده والدین وجود دارد.", choices: [{ id: 'a' as const, text: "مشارکت در نهادهای مدرسه و انتخاب شدن به عنوان نماینده والدین" }, { id: 'b' as const, text: "انتخاب دروس تدریس‌شده به فرزند" }, { id: 'c' as const, text: "تصمیم‌گیری درباره ارتقای فرزند به کلاس بالاتر" }, { id: 'd' as const, text: "جایگزینی معلم غایب" }] },
  // Q75
  { textFr: "Quelle instruction est prévue pour les enfants qui ne parlent pas français ?", lang: 'fa' as const, text: "چه آموزشی برای کودکانی که فرانسوی صحبت نمی‌کنند پیش‌بینی شده است؟", explanation: "کودکان غیرفرانسوی‌زبان (آلوفون) از آموزش ویژه زبان فرانسوی در واحدهای آموزشی (UPE2A) بهره‌مند می‌شوند و همزمان در کلاس عادی مطابق سنشان ثبت‌نام هستند.", choices: [{ id: 'a' as const, text: "آموزش ویژه فرانسوی (UPE2A) همراه با کلاس عادی" }, { id: 'b' as const, text: "هیچ، باید خودشان یاد بگیرند" }, { id: 'c' as const, text: "به کشور مبدأشان بازگردانده می‌شوند" }, { id: 'd' as const, text: "در مدارس تخصصی جداگانه قرار می‌گیرند" }] },
  // Q76
  { textFr: "S'agissant de l'accueil des enfants en situation de handicap à l'école, laquelle des propositions est vraie ?", lang: 'fa' as const, text: "درباره پذیرش کودکان دارای معلولیت در مدرسه، کدام گزاره صحیح است؟", explanation: "مدرسه فراگیر یک حق در فرانسه است. هر کودک دارای معلولیت می‌تواند در مدرسه محله‌اش با تسهیلات مناسب (دستیار، تجهیزات تخصصی و غیره) تحصیل کند.", choices: [{ id: 'a' as const, text: "هر کودک معلول حق دارد با تسهیلات مناسب در محیط عادی تحصیل کند" }, { id: 'b' as const, text: "کودکان معلول نمی‌توانند به مدرسه بروند" }, { id: 'c' as const, text: "فقط کودکان با معلولیت خفیف می‌توانند به مدرسه بروند" }, { id: 'd' as const, text: "کودکان معلول باید به استان دیگری بروند" }] },
  // Q77
  { textFr: "Depuis le 1er juillet 2021, quelle est la durée du congé paternité ?", lang: 'fa' as const, text: "از اول ژوئیه ۲۰۲۱، مدت مرخصی پدری چقدر است؟", explanation: "از اول ژوئیه ۲۰۲۱، مرخصی پدری ۲۵ روز تقویمی (۳۲ روز در صورت تولد چندقلو) است. این اصلاحیه مدت قبلی ۱۱ روز را دو برابر کرد.", choices: [{ id: 'a' as const, text: "۲۵ روز تقویمی" }, { id: 'b' as const, text: "۱۱ روز تقویمی" }, { id: 'c' as const, text: "۱۴ روز تقویمی" }, { id: 'd' as const, text: "۳۰ روز تقویمی" }] },
  // Q78
  { textFr: "Est-ce possible de punir physiquement ses enfants ?", lang: 'fa' as const, text: "آیا تنبیه بدنی فرزندان امکان‌پذیر است؟", explanation: "خیر، خشونت فیزیکی علیه کودکان در فرانسه ممنوع است. از قانون ۱۰ ژوئیه ۲۰۱۹، هرگونه خشونت تربیتی عادی (سیلی، کتک و غیره) ممنوع شده است. حق والدینی بدون خشونت اعمال می‌شود.", choices: [{ id: 'a' as const, text: "خیر، هرگونه خشونت فیزیکی علیه کودکان ممنوع است" }, { id: 'b' as const, text: "بله، اگر به دلایل تربیتی باشد" }, { id: 'c' as const, text: "بله، تا زمانی که اثری باقی نگذارد" }, { id: 'd' as const, text: "بله، این حق والدین است" }] },
];
