export const questionsTheme1 = [
  // ── Q1: À quoi correspond la date du 14 juillet ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "À quoi correspond la date du 14 juillet ?",
    explanationFr: "Le 14 juillet commémore la prise de la Bastille en 1789, symbole de la fin de l'arbitraire royal. C'est la fête nationale française, célébrée chaque année avec un défilé militaire et des feux d'artifice.",
    choicesFr: [
      { id: 'a' as const, text: "À la prise de la Bastille et à la fête nationale" },
      { id: 'b' as const, text: "À la signature de la Constitution" },
      { id: 'c' as const, text: "À la fin de la Seconde Guerre mondiale" },
      { id: 'd' as const, text: "À l'abolition de la monarchie" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q2: Quel est l'un des symboles de la République française ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Quel est l'un des symboles de la République française ?",
    explanationFr: "Marianne est l'un des symboles officiels de la République française. Elle représente la liberté et la République, et son buste est présent dans toutes les mairies de France.",
    choicesFr: [
      { id: 'a' as const, text: "Marianne" },
      { id: 'b' as const, text: "L'aigle impérial" },
      { id: 'c' as const, text: "La couronne royale" },
      { id: 'd' as const, text: "Le lion" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q3: Le principe d'égalité signifie que : (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Le principe d'égalité signifie que :",
    explanationFr: "Le principe d'égalité, inscrit dans la devise républicaine, signifie que tous les citoyens ont les mêmes droits et les mêmes devoirs devant la loi, sans distinction d'origine, de race ou de religion.",
    choicesFr: [
      { id: 'a' as const, text: "Tous les citoyens ont les mêmes droits et les mêmes devoirs" },
      { id: 'b' as const, text: "Tout le monde doit gagner le même salaire" },
      { id: 'c' as const, text: "Les hommes ont plus de droits que les femmes" },
      { id: 'd' as const, text: "Seuls les Français ont des droits" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q4: "Liberté, égalité, fraternité", c'est : (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "\"Liberté, égalité, fraternité\", c'est :",
    explanationFr: "\"Liberté, égalité, fraternité\" est la devise de la République française. Elle est inscrite dans la Constitution et figure sur les bâtiments publics et les documents officiels.",
    choicesFr: [
      { id: 'a' as const, text: "La devise de la République française" },
      { id: 'b' as const, text: "Le titre de l'hymne national" },
      { id: 'c' as const, text: "Le nom d'une loi française" },
      { id: 'd' as const, text: "Un slogan publicitaire" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q5: A-t-on le droit d'insulter publiquement quelqu'un parce qu'il est différent ? (CSP + CR)
  {
    themeId: 1 as const,
    type: 'situational' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'cr'] as const,
    textFr: "A-t-on le droit d'insulter publiquement quelqu'un parce qu'il est différent (handicap, apparence physique, sexe...) ?",
    explanationFr: "Non, insulter publiquement quelqu'un en raison de sa différence est interdit par la loi. C'est une discrimination punie pénalement. La loi protège toute personne contre les injures liées au handicap, au sexe ou à l'apparence physique.",
    choicesFr: [
      { id: 'a' as const, text: "Non, c'est interdit par la loi" },
      { id: 'b' as const, text: "Oui, grâce à la liberté d'expression" },
      { id: 'c' as const, text: "Oui, si c'est de l'humour" },
      { id: 'd' as const, text: "Seulement dans un cadre privé" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q6: Certains métiers peuvent-ils être réservés aux hommes ? (CSP)
  {
    themeId: 1 as const,
    type: 'situational' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Certains métiers peuvent-ils être réservés aux hommes ?",
    explanationFr: "Non, en France, tous les métiers sont ouverts aux femmes comme aux hommes. Le principe d'égalité entre les sexes interdit toute discrimination à l'embauche fondée sur le sexe.",
    choicesFr: [
      { id: 'a' as const, text: "Non, tous les métiers sont ouverts aux femmes et aux hommes" },
      { id: 'b' as const, text: "Oui, certains métiers sont interdits aux femmes" },
      { id: 'c' as const, text: "Oui, les métiers physiques sont réservés aux hommes" },
      { id: 'd' as const, text: "Cela dépend de l'employeur" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q7: De quand date la Constitution de la Ve République ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "De quand date la Constitution de la Ve République ?",
    explanationFr: "La Constitution de la Ve République a été adoptée par référendum le 28 septembre 1958 et promulguée le 4 octobre 1958. Elle fonde le régime politique actuel de la France.",
    choicesFr: [
      { id: 'a' as const, text: "1958" },
      { id: 'b' as const, text: "1789" },
      { id: 'c' as const, text: "1945" },
      { id: 'd' as const, text: "1968" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q8: Le régime de la France est : (CSP + CR)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'cr'] as const,
    textFr: "Le régime de la France est :",
    explanationFr: "La France est une république démocratique. L'article 1er de la Constitution définit la France comme une République indivisible, laïque, démocratique et sociale.",
    choicesFr: [
      { id: 'a' as const, text: "Une république démocratique" },
      { id: 'b' as const, text: "Une monarchie constitutionnelle" },
      { id: 'c' as const, text: "Une dictature" },
      { id: 'd' as const, text: "Un empire" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q9: Lequel de ces symboles représente officiellement la République française ? (CSP + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'nat'] as const,
    textFr: "Lequel de ces symboles représente officiellement la République française ?",
    explanationFr: "Marianne est le symbole officiel de la République française. Elle incarne les valeurs de liberté et de démocratie. Son buste est présent dans les mairies et sur les timbres-poste.",
    choicesFr: [
      { id: 'a' as const, text: "Marianne" },
      { id: 'b' as const, text: "La fleur de lys" },
      { id: 'c' as const, text: "L'aigle" },
      { id: 'd' as const, text: "Le bélier" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q10: Où peut-on voir la devise de la République ? (CSP + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'nat'] as const,
    textFr: "Où peut-on voir la devise de la République ?",
    explanationFr: "La devise \"Liberté, Égalité, Fraternité\" est inscrite sur les frontons des bâtiments publics, comme les mairies, les écoles et les tribunaux. Elle figure aussi sur les pièces de monnaie.",
    choicesFr: [
      { id: 'a' as const, text: "Sur les bâtiments publics (mairies, écoles, tribunaux)" },
      { id: 'b' as const, text: "Uniquement sur les billets de banque" },
      { id: 'c' as const, text: "Sur les panneaux routiers" },
      { id: 'd' as const, text: "Seulement dans la Constitution" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q11: Quels sont des symboles officiels de la République française ? (CSP + CR + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'cr', 'nat'] as const,
    textFr: "Quels sont des symboles officiels de la République française ?",
    explanationFr: "Le drapeau tricolore, la Marseillaise et Marianne sont des symboles officiels de la République française. Ils représentent les valeurs et l'identité de la nation.",
    choicesFr: [
      { id: 'a' as const, text: "Le drapeau tricolore, la Marseillaise et Marianne" },
      { id: 'b' as const, text: "La tour Eiffel, le béret et la baguette" },
      { id: 'c' as const, text: "La fleur de lys, la couronne et le sceptre" },
      { id: 'd' as const, text: "Le croissant, le vin et le fromage" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q12: Qu'est-ce que l'égalité ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Qu'est-ce que l'égalité ?",
    explanationFr: "L'égalité est un principe fondamental de la République : tous les citoyens sont égaux devant la loi, sans distinction d'origine, de race ou de religion. Ce principe est inscrit dans la Déclaration des droits de l'homme et du citoyen de 1789.",
    choicesFr: [
      { id: 'a' as const, text: "Le fait que tous les citoyens aient les mêmes droits devant la loi" },
      { id: 'b' as const, text: "Le fait que tout le monde ait le même salaire" },
      { id: 'c' as const, text: "Le droit de faire ce que l'on veut" },
      { id: 'd' as const, text: "L'obligation de penser la même chose" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q13: Que signifie la liberté ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Que signifie la liberté ?",
    explanationFr: "La liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui. Elle est encadrée par la loi pour garantir le respect des droits de chacun, conformément à la Déclaration des droits de l'homme de 1789.",
    choicesFr: [
      { id: 'a' as const, text: "Pouvoir faire tout ce qui ne nuit pas à autrui" },
      { id: 'b' as const, text: "Faire tout ce que l'on veut sans limite" },
      { id: 'c' as const, text: "Obéir uniquement aux lois que l'on approuve" },
      { id: 'd' as const, text: "Ne pas avoir de responsabilités" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q14: Que signifie le mot "fraternité" dans la devise française ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Que signifie le mot \"fraternité\" dans la devise française ?",
    explanationFr: "La fraternité exprime la solidarité entre les citoyens et le devoir d'entraide mutuelle. Ce principe implique que les membres de la société se soutiennent les uns les autres.",
    choicesFr: [
      { id: 'a' as const, text: "La solidarité et l'entraide entre les citoyens" },
      { id: 'b' as const, text: "L'obligation d'avoir des frères et sœurs" },
      { id: 'c' as const, text: "Le droit de vivre en famille" },
      { id: 'd' as const, text: "La liberté de choisir ses amis" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q15: Quel animal est un symbole de la France ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Quel animal est un symbole de la France ?",
    explanationFr: "Le coq est un symbole de la France. Il représente la vigilance et la fierté. On le retrouve notamment sur les grilles du palais de l'Élysée et sur les maillots des équipes sportives françaises.",
    choicesFr: [
      { id: 'a' as const, text: "Le coq" },
      { id: 'b' as const, text: "L'aigle" },
      { id: 'c' as const, text: "Le lion" },
      { id: 'd' as const, text: "L'ours" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q16: Quel est l'un des rôles des associations ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Quel est l'un des rôles des associations ?",
    explanationFr: "Les associations jouent un rôle essentiel dans la vie citoyenne en permettant aux personnes de se réunir pour défendre une cause, pratiquer une activité ou aider les autres. Elles contribuent à la solidarité et à la participation citoyenne.",
    choicesFr: [
      { id: 'a' as const, text: "Permettre aux citoyens de se réunir pour défendre une cause ou s'entraider" },
      { id: 'b' as const, text: "Remplacer le gouvernement" },
      { id: 'c' as const, text: "Voter les lois" },
      { id: 'd' as const, text: "Collecter les impôts" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q17: Quel est le nom de l'hymne national ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Quel est le nom de l'hymne national ?",
    explanationFr: "L'hymne national français est la Marseillaise. Composée par Rouget de Lisle en 1792, elle a été déclarée hymne national en 1795.",
    choicesFr: [
      { id: 'a' as const, text: "La Marseillaise" },
      { id: 'b' as const, text: "La Parisienne" },
      { id: 'c' as const, text: "Le Chant du départ" },
      { id: 'd' as const, text: "La Carmagnole" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q18: Quel symbole de la République française est tricolore ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Quel symbole de la République française est tricolore ?",
    explanationFr: "Le drapeau français est tricolore : bleu, blanc, rouge. Il est le symbole de la République depuis la Révolution française et flotte sur tous les bâtiments publics.",
    choicesFr: [
      { id: 'a' as const, text: "Le drapeau" },
      { id: 'b' as const, text: "Marianne" },
      { id: 'c' as const, text: "Le coq" },
      { id: 'd' as const, text: "La devise" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q19: Quelle est la date de la fête nationale française ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Quelle est la date de la fête nationale française ?",
    explanationFr: "La fête nationale française est le 14 juillet. Elle commémore la prise de la Bastille (1789) et la Fête de la Fédération (1790), symboles de la liberté et de l'unité nationale.",
    choicesFr: [
      { id: 'a' as const, text: "Le 14 juillet" },
      { id: 'b' as const, text: "Le 1er mai" },
      { id: 'c' as const, text: "Le 11 novembre" },
      { id: 'd' as const, text: "Le 8 mai" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q20: Quelle est la devise de la République française ? (CSP + CR + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'cr', 'nat'] as const,
    textFr: "Quelle est la devise de la République française ?",
    explanationFr: "La devise de la République française est \"Liberté, Égalité, Fraternité\". Elle est inscrite dans la Constitution et figure sur les bâtiments publics, les pièces de monnaie et les documents officiels.",
    choicesFr: [
      { id: 'a' as const, text: "Liberté, Égalité, Fraternité" },
      { id: 'b' as const, text: "Liberté, Justice, Paix" },
      { id: 'c' as const, text: "Honneur, Patrie, Valeur" },
      { id: 'd' as const, text: "Égalité, Solidarité, Fraternité" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q21: Quelle est la langue officielle de la République française ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Quelle est la langue officielle de la République française ?",
    explanationFr: "Le français est la langue officielle de la République française, comme le précise l'article 2 de la Constitution. C'est la langue utilisée dans l'administration, la justice et l'enseignement.",
    choicesFr: [
      { id: 'a' as const, text: "Le français" },
      { id: 'b' as const, text: "Le français et l'anglais" },
      { id: 'c' as const, text: "Il n'y a pas de langue officielle" },
      { id: 'd' as const, text: "Le français et les langues régionales" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q22: Quelle est la place de la langue française dans la République ? (CSP + CR)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'cr'] as const,
    textFr: "Quelle est la place de la langue française dans la République ?",
    explanationFr: "Le français est la langue de la République selon l'article 2 de la Constitution. Elle est obligatoire dans les services publics, l'enseignement et les actes administratifs.",
    choicesFr: [
      { id: 'a' as const, text: "C'est la langue de la République inscrite dans la Constitution" },
      { id: 'b' as const, text: "C'est une langue parmi d'autres, sans statut particulier" },
      { id: 'c' as const, text: "Elle n'est obligatoire que dans les écoles" },
      { id: 'd' as const, text: "Elle est officielle uniquement à Paris" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q23: Quelle liberté permet à chacun d'exprimer ses idées ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Quelle liberté permet à chacun d'exprimer ses idées ?",
    explanationFr: "La liberté d'expression permet à chacun d'exprimer ses idées et ses opinions. Elle est garantie par la Déclaration des droits de l'homme et du citoyen de 1789, mais elle est limitée par le respect d'autrui et l'interdiction de la diffamation.",
    choicesFr: [
      { id: 'a' as const, text: "La liberté d'expression" },
      { id: 'b' as const, text: "La liberté de circulation" },
      { id: 'c' as const, text: "La liberté d'association" },
      { id: 'd' as const, text: "La liberté de commerce" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q24: Quelle proposition est correcte ? La liberté d'expression : (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Quelle proposition est correcte ? La liberté d'expression :",
    explanationFr: "La liberté d'expression permet de donner son opinion, mais elle a des limites. Les propos racistes, diffamatoires ou incitant à la haine sont interdits par la loi.",
    choicesFr: [
      { id: 'a' as const, text: "Permet de donner son opinion dans le respect de la loi" },
      { id: 'b' as const, text: "Permet de tout dire sans aucune limite" },
      { id: 'c' as const, text: "N'existe pas en France" },
      { id: 'd' as const, text: "Est réservée aux journalistes" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q25: Quelles sont les couleurs du drapeau français ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Quelles sont les couleurs du drapeau français ?",
    explanationFr: "Le drapeau français est composé de trois bandes verticales : bleu, blanc et rouge. Le bleu et le rouge sont les couleurs de Paris, et le blanc représente la monarchie.",
    choicesFr: [
      { id: 'a' as const, text: "Bleu, blanc, rouge" },
      { id: 'b' as const, text: "Bleu, jaune, rouge" },
      { id: 'c' as const, text: "Rouge, blanc, vert" },
      { id: 'd' as const, text: "Blanc, rouge, noir" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q26: Qu'est-ce que la Marseillaise ? (CSP + CR)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'cr'] as const,
    textFr: "Qu'est-ce que la Marseillaise ?",
    explanationFr: "La Marseillaise est l'hymne national de la France. Composée par Rouget de Lisle en 1792, elle est devenue hymne national en 1795 et est jouée lors des cérémonies officielles.",
    choicesFr: [
      { id: 'a' as const, text: "L'hymne national de la France" },
      { id: 'b' as const, text: "Une chanson populaire du sud de la France" },
      { id: 'c' as const, text: "Le nom du drapeau français" },
      { id: 'd' as const, text: "Une danse traditionnelle" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q27: Qu'est-ce qui est traditionnellement organisé sur les Champs-Élysées le 14 juillet ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Qu'est-ce qui est traditionnellement organisé sur les Champs-Élysées le 14 juillet pour célébrer la fête nationale ?",
    explanationFr: "Un défilé militaire est traditionnellement organisé sur les Champs-Élysées le 14 juillet. Il rassemble les forces armées françaises devant le président de la République.",
    choicesFr: [
      { id: 'a' as const, text: "Un défilé militaire" },
      { id: 'b' as const, text: "Un marathon" },
      { id: 'c' as const, text: "Un concert de rock" },
      { id: 'd' as const, text: "Un marché de Noël" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q28: Qui est Marianne ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Qui est Marianne ?",
    explanationFr: "Marianne est la figure allégorique de la République française. Elle représente les valeurs de liberté et de démocratie. Son buste est présent dans les mairies et elle figure sur les timbres-poste.",
    choicesFr: [
      { id: 'a' as const, text: "La figure qui représente la République française" },
      { id: 'b' as const, text: "Une reine de France" },
      { id: 'c' as const, text: "La femme de Napoléon" },
      { id: 'd' as const, text: "Une héroïne de la Résistance" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q29: Une personne peut-elle changer librement de religion ? (CSP + NAT)
  {
    themeId: 1 as const,
    type: 'situational' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'nat'] as const,
    textFr: "Une personne peut-elle changer librement de religion ?",
    explanationFr: "Oui, en France, chaque personne est libre de changer de religion ou de ne pas avoir de religion. La liberté de conscience et de culte est garantie par la loi de 1905 et par la Constitution.",
    choicesFr: [
      { id: 'a' as const, text: "Oui, chacun est libre de changer de religion" },
      { id: 'b' as const, text: "Non, on doit garder la religion de ses parents" },
      { id: 'c' as const, text: "Seulement avec l'autorisation de l'État" },
      { id: 'd' as const, text: "Non, c'est interdit en France" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q30: "La France est une République indivisible, ..., démocratique et sociale" (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "\"La France est une République indivisible, ..., démocratique et sociale\". Complétez cette phrase extraite de l'article 1er de la Constitution :",
    explanationFr: "L'article 1er de la Constitution dispose que \"La France est une République indivisible, laïque, démocratique et sociale\". La laïcité est donc un principe constitutionnel fondamental.",
    choicesFr: [
      { id: 'a' as const, text: "Laïque" },
      { id: 'b' as const, text: "Chrétienne" },
      { id: 'c' as const, text: "Libérale" },
      { id: 'd' as const, text: "Fédérale" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q31: En quelle année la loi de séparation des Églises et de l'État a-t-elle été votée ? (CSP + CR + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'cr', 'nat'] as const,
    textFr: "En quelle année la loi de séparation des Églises et de l'État a-t-elle été votée ?",
    explanationFr: "La loi de séparation des Églises et de l'État a été votée le 9 décembre 1905. Elle garantit la liberté de conscience et pose le principe de la laïcité de l'État.",
    choicesFr: [
      { id: 'a' as const, text: "1905" },
      { id: 'b' as const, text: "1789" },
      { id: 'c' as const, text: "1958" },
      { id: 'd' as const, text: "1848" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q32: Que permet le principe de laïcité ? (CSP)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Que permet le principe de laïcité ?",
    explanationFr: "Le principe de laïcité permet à chacun de pratiquer librement sa religion ou de ne pas en avoir, tout en assurant la neutralité de l'État en matière religieuse. L'État ne favorise aucune religion.",
    choicesFr: [
      { id: 'a' as const, text: "De pratiquer librement sa religion ou de ne pas en avoir" },
      { id: 'b' as const, text: "D'interdire toutes les religions" },
      { id: 'c' as const, text: "D'imposer une religion officielle" },
      { id: 'd' as const, text: "De pratiquer sa religion uniquement chez soi" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q33: Quel droit est garanti par la laïcité ? (CSP + CR)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'cr'] as const,
    textFr: "Quel droit est garanti par la laïcité ?",
    explanationFr: "La laïcité garantit la liberté de conscience : chacun est libre de croire ou de ne pas croire. L'État assure la liberté de culte tout en restant neutre vis-à-vis de toutes les religions.",
    choicesFr: [
      { id: 'a' as const, text: "La liberté de conscience et la liberté de culte" },
      { id: 'b' as const, text: "Le droit de vote" },
      { id: 'c' as const, text: "Le droit au travail" },
      { id: 'd' as const, text: "Le droit à la propriété" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q34: Pourquoi le principe de laïcité doit-il être respecté à l'école ? (CSP + CR)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'cr'] as const,
    textFr: "Pourquoi le principe de laïcité doit-il être respecté à l'école ?",
    explanationFr: "La laïcité doit être respectée à l'école pour garantir la neutralité du service public d'éducation et permettre à tous les élèves d'étudier ensemble sans pression religieuse.",
    choicesFr: [
      { id: 'a' as const, text: "Pour garantir la neutralité de l'enseignement et le vivre-ensemble" },
      { id: 'b' as const, text: "Pour interdire toute discussion sur la religion" },
      { id: 'c' as const, text: "Pour obliger les élèves à être athées" },
      { id: 'd' as const, text: "Pour favoriser une religion en particulier" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q35: Qu'est-ce que la laïcité ? (CSP + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'nat'] as const,
    textFr: "Qu'est-ce que la laïcité ?",
    explanationFr: "La laïcité est le principe de séparation des Églises et de l'État. L'État ne reconnaît, ne salarie ni ne subventionne aucun culte, tout en garantissant la liberté de conscience et le libre exercice des cultes.",
    choicesFr: [
      { id: 'a' as const, text: "Le principe de séparation des religions et de l'État" },
      { id: 'b' as const, text: "L'interdiction de toutes les religions" },
      { id: 'c' as const, text: "L'obligation d'être athée" },
      { id: 'd' as const, text: "La religion officielle de la France" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q36: Un enfant peut-il refuser d'aller à l'école pour une raison religieuse ? (CSP)
  {
    themeId: 1 as const,
    type: 'situational' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp'] as const,
    textFr: "Un enfant peut-il refuser d'aller à l'école pour une raison religieuse ?",
    explanationFr: "Non, l'instruction est obligatoire en France pour tous les enfants de 3 à 16 ans. Aucune raison religieuse ne peut justifier le refus de cette obligation. La laïcité garantit un enseignement neutre accessible à tous.",
    choicesFr: [
      { id: 'a' as const, text: "Non, l'instruction est obligatoire pour tous les enfants" },
      { id: 'b' as const, text: "Oui, si ses parents sont d'accord" },
      { id: 'c' as const, text: "Oui, la liberté religieuse le permet" },
      { id: 'd' as const, text: "Oui, pendant les fêtes religieuses uniquement" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q37: Une personne a-t-elle le droit de ne pas croire en une religion ? (CSP + CR)
  {
    themeId: 1 as const,
    type: 'situational' as const,
    difficulty: 1,
    isPremium: false,
    examTypes: ['csp', 'cr'] as const,
    textFr: "Une personne a-t-elle le droit de ne pas croire en une religion ?",
    explanationFr: "Oui, la liberté de conscience garantit à chacun le droit de croire ou de ne pas croire. En France, on peut être athée, agnostique ou croyant, c'est un choix personnel protégé par la loi.",
    choicesFr: [
      { id: 'a' as const, text: "Oui, c'est la liberté de conscience" },
      { id: 'b' as const, text: "Non, tout le monde doit avoir une religion" },
      { id: 'c' as const, text: "Seulement si l'État l'autorise" },
      { id: 'd' as const, text: "Non, c'est interdit en France" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q38: Parmi les propositions suivantes, laquelle constitue une participation citoyenne ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Parmi les propositions suivantes, laquelle constitue une participation citoyenne ?",
    explanationFr: "Voter est l'un des actes fondamentaux de la participation citoyenne. C'est le moyen par lequel les citoyens exercent leur souveraineté et participent à la vie démocratique.",
    choicesFr: [
      { id: 'a' as const, text: "Voter aux élections" },
      { id: 'b' as const, text: "Regarder les informations à la télévision" },
      { id: 'c' as const, text: "Partir en vacances" },
      { id: 'd' as const, text: "Faire ses courses" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q39: Que garantit la liberté d'expression ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Que garantit la liberté d'expression ?",
    explanationFr: "La liberté d'expression garantit le droit de chacun à exprimer librement ses opinions et ses idées. Elle est un pilier de la démocratie, mais elle est encadrée par la loi pour éviter les abus comme la diffamation ou l'incitation à la haine.",
    choicesFr: [
      { id: 'a' as const, text: "Le droit d'exprimer librement ses opinions dans le respect de la loi" },
      { id: 'b' as const, text: "Le droit de dire n'importe quoi sans conséquence" },
      { id: 'c' as const, text: "Le droit de ne pas parler français" },
      { id: 'd' as const, text: "Le droit de refuser de répondre à la police" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q40: À quoi sert un titre de séjour ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "À quoi sert un titre de séjour ?",
    explanationFr: "Un titre de séjour est un document officiel qui autorise un étranger à résider légalement en France. Il peut être temporaire ou permanent et conditionne l'accès au travail et aux droits sociaux.",
    choicesFr: [
      { id: 'a' as const, text: "À autoriser un étranger à résider légalement en France" },
      { id: 'b' as const, text: "À obtenir la nationalité française automatiquement" },
      { id: 'c' as const, text: "À voyager gratuitement en France" },
      { id: 'd' as const, text: "À voter aux élections" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q41: La liberté de circulation permet à toute personne de : (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "La liberté de circulation permet à toute personne de :",
    explanationFr: "La liberté de circulation est un droit fondamental qui permet à toute personne de se déplacer librement sur le territoire français et de choisir son lieu de résidence.",
    choicesFr: [
      { id: 'a' as const, text: "Se déplacer librement et choisir son lieu de résidence" },
      { id: 'b' as const, text: "Conduire sans permis" },
      { id: 'c' as const, text: "Entrer dans tous les bâtiments publics sans restriction" },
      { id: 'd' as const, text: "Voyager à l'étranger sans passeport" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q42: Sur quel site internet peut-on retrouver le symbole de la République française ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Sur quel site internet peut-on retrouver le symbole de la République française ?",
    explanationFr: "Le symbole de la République française (Marianne, le drapeau tricolore, la devise) figure sur les sites officiels du gouvernement, notamment sur le site service-public.fr et les sites en .gouv.fr.",
    choicesFr: [
      { id: 'a' as const, text: "Sur les sites officiels du gouvernement (en .gouv.fr)" },
      { id: 'b' as const, text: "Sur les réseaux sociaux uniquement" },
      { id: 'c' as const, text: "Sur Wikipédia" },
      { id: 'd' as const, text: "Sur les sites de commerce en ligne" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q43: Complétez ces paroles de la Marseillaise : "Aux armes [...] ! Formez vos bataillons" (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Complétez ces paroles de la Marseillaise : \"Aux armes [...] ! Formez vos bataillons\"",
    explanationFr: "Les paroles exactes du refrain de la Marseillaise sont : \"Aux armes, citoyens ! Formez vos bataillons\". Ce chant révolutionnaire appelle les citoyens à défendre la nation.",
    choicesFr: [
      { id: 'a' as const, text: "Citoyens" },
      { id: 'b' as const, text: "Soldats" },
      { id: 'c' as const, text: "Français" },
      { id: 'd' as const, text: "Camarades" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q44: Complétez les paroles de la Marseillaise : "Allons enfants de la patrie [...]" (CR + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr', 'nat'] as const,
    textFr: "Complétez les paroles de la Marseillaise : \"Allons enfants de la patrie [...]\"",
    explanationFr: "Les premières paroles de la Marseillaise sont : \"Allons enfants de la patrie, le jour de gloire est arrivé\". Ce chant a été composé par Rouget de Lisle en 1792.",
    choicesFr: [
      { id: 'a' as const, text: "Le jour de gloire est arrivé" },
      { id: 'b' as const, text: "La victoire est à nous" },
      { id: 'c' as const, text: "Défendons notre liberté" },
      { id: 'd' as const, text: "Marchons vers la victoire" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q45: En application de la liberté individuelle, quelle proposition est correcte ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "En application de la liberté individuelle, quelle proposition est correcte ? Une personne peut :",
    explanationFr: "La liberté individuelle permet à chacun de s'habiller comme il le souhaite dans l'espace public, dans le respect de la loi. C'est une expression de la liberté personnelle garantie par la Constitution.",
    choicesFr: [
      { id: 'a' as const, text: "S'habiller comme elle le souhaite dans le respect de la loi" },
      { id: 'b' as const, text: "Refuser de payer ses impôts" },
      { id: 'c' as const, text: "Ne pas respecter le code de la route" },
      { id: 'd' as const, text: "Ignorer les décisions de justice" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q46: Concernant la pratique de la religion, quelle proposition est correcte ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Concernant la pratique de la religion, quelle proposition est correcte ?",
    explanationFr: "En France, chacun est libre de pratiquer la religion de son choix ou de n'en pratiquer aucune. La laïcité garantit cette liberté tout en imposant la neutralité de l'État.",
    choicesFr: [
      { id: 'a' as const, text: "Chacun est libre de pratiquer la religion de son choix ou de n'en avoir aucune" },
      { id: 'b' as const, text: "Il faut obligatoirement pratiquer une religion" },
      { id: 'c' as const, text: "Seules certaines religions sont autorisées" },
      { id: 'd' as const, text: "La religion doit rester secrète" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q47: En tant que parent, peut-on refuser que son enfant participe aux cours de sport car ils sont mixtes ? (CR only)
  {
    themeId: 1 as const,
    type: 'situational' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "En tant que parent, peut-on refuser que son enfant participe aux cours de sport à l'école car ils sont mixtes ?",
    explanationFr: "Non, les cours de sport sont obligatoires à l'école et la mixité est un principe fondamental de l'école publique. Aucune raison religieuse ou personnelle ne peut justifier le refus de la mixité scolaire.",
    choicesFr: [
      { id: 'a' as const, text: "Non, les cours de sport sont obligatoires et la mixité est un principe de l'école" },
      { id: 'b' as const, text: "Oui, pour des raisons religieuses" },
      { id: 'c' as const, text: "Oui, si l'enfant est d'accord" },
      { id: 'd' as const, text: "Oui, avec un certificat médical" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q48: La répudiation de sa femme est : (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "La répudiation de sa femme est :",
    explanationFr: "La répudiation est interdite en France. Le droit français ne reconnaît pas la répudiation unilatérale. Seul le divorce, prononcé par un juge, permet de mettre fin à un mariage, dans le respect de l'égalité entre les époux.",
    choicesFr: [
      { id: 'a' as const, text: "Interdite en France" },
      { id: 'b' as const, text: "Autorisée sous certaines conditions" },
      { id: 'c' as const, text: "Possible avec l'accord du maire" },
      { id: 'd' as const, text: "Autorisée si les deux époux sont d'accord" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q49: Les impôts permettent de financer les dépenses publiques. Quelle proposition est correcte ? (CR + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr', 'nat'] as const,
    textFr: "Les impôts permettent de financer les dépenses publiques. Quelle proposition est correcte ?",
    explanationFr: "Les impôts financent les services publics comme l'éducation, la santé, la sécurité et les infrastructures. Chaque citoyen contribue selon ses moyens au fonctionnement de l'État et des collectivités.",
    choicesFr: [
      { id: 'a' as const, text: "Les impôts financent les services publics (écoles, hôpitaux, routes, sécurité)" },
      { id: 'b' as const, text: "Les impôts servent uniquement à payer les élus" },
      { id: 'c' as const, text: "Seuls les riches paient des impôts" },
      { id: 'd' as const, text: "Les impôts sont facultatifs" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q50: Peut-on brûler publiquement un drapeau français ? (CR + NAT)
  {
    themeId: 1 as const,
    type: 'situational' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr', 'nat'] as const,
    textFr: "Peut-on brûler publiquement un drapeau français ?",
    explanationFr: "Non, l'outrage au drapeau tricolore lors d'une manifestation publique est un délit puni par la loi. Le drapeau est un symbole de la République et sa destruction publique est interdite.",
    choicesFr: [
      { id: 'a' as const, text: "Non, c'est un délit puni par la loi" },
      { id: 'b' as const, text: "Oui, grâce à la liberté d'expression" },
      { id: 'c' as const, text: "Oui, si c'est lors d'une manifestation" },
      { id: 'd' as const, text: "Oui, si le drapeau vous appartient" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q51: Que fait l'État pour lutter contre les discriminations ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Que fait l'État pour lutter contre les discriminations ?",
    explanationFr: "L'État a mis en place des lois qui interdisent et punissent les discriminations. Le Défenseur des droits est une autorité indépendante qui peut être saisie par toute personne victime de discrimination.",
    choicesFr: [
      { id: 'a' as const, text: "Il vote des lois qui interdisent et punissent les discriminations" },
      { id: 'b' as const, text: "Il ne fait rien, c'est aux citoyens d'agir" },
      { id: 'c' as const, text: "Il autorise certaines discriminations" },
      { id: 'd' as const, text: "Il laisse les entreprises décider" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q52: Que représente Marianne ? (CR + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Que représente Marianne ?",
    explanationFr: "Marianne est l'allégorie de la République française. Elle incarne les valeurs de liberté et de la République. Coiffée du bonnet phrygien, elle symbolise le triomphe de la République.",
    choicesFr: [
      { id: 'a' as const, text: "La République française" },
      { id: 'b' as const, text: "La reine de France" },
      { id: 'c' as const, text: "L'Europe" },
      { id: 'd' as const, text: "La ville de Paris" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q53: Qu'est-ce que la liberté d'association ? (CR + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr', 'nat'] as const,
    textFr: "Qu'est-ce que la liberté d'association ?",
    explanationFr: "La liberté d'association est le droit de créer ou de rejoindre une association sans autorisation préalable. Elle est garantie par la loi du 1er juillet 1901 et permet aux citoyens de se regrouper pour défendre une cause commune.",
    choicesFr: [
      { id: 'a' as const, text: "Le droit de créer ou de rejoindre librement une association" },
      { id: 'b' as const, text: "L'obligation de faire partie d'une association" },
      { id: 'c' as const, text: "Le droit de créer une entreprise" },
      { id: 'd' as const, text: "Le droit de créer un parti politique uniquement" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q54: Qu'est-ce que la liberté ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Qu'est-ce que la liberté ?",
    explanationFr: "La liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui, selon l'article 4 de la Déclaration des droits de l'homme et du citoyen de 1789. Elle est limitée par la loi pour protéger les droits des autres.",
    choicesFr: [
      { id: 'a' as const, text: "Le droit de faire tout ce qui ne nuit pas à autrui, dans le respect de la loi" },
      { id: 'b' as const, text: "Le droit de faire absolument tout ce que l'on veut" },
      { id: 'c' as const, text: "Le droit de ne pas respecter la loi" },
      { id: 'd' as const, text: "Le droit de ne rien faire" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q55: Sur quel document peut-on voir Marianne ? (CR + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr', 'nat'] as const,
    textFr: "Sur quel document peut-on voir Marianne ?",
    explanationFr: "Marianne figure sur les timbres-poste français. On la retrouve aussi sur les pièces de monnaie, dans les mairies et sur les documents officiels de la République.",
    choicesFr: [
      { id: 'a' as const, text: "Sur les timbres-poste" },
      { id: 'b' as const, text: "Sur le permis de conduire" },
      { id: 'c' as const, text: "Sur les billets de train" },
      { id: 'd' as const, text: "Sur les ordonnances médicales" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q56: Un employeur refuse d'embaucher des femmes. Que dit la loi ? (CR only)
  {
    themeId: 1 as const,
    type: 'situational' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Un employeur refuse d'embaucher des femmes dans son entreprise. Que dit la loi ?",
    explanationFr: "La loi interdit toute discrimination à l'embauche fondée sur le sexe. Refuser d'embaucher des femmes est un délit passible de sanctions pénales. Le principe d'égalité entre les femmes et les hommes est garanti par la Constitution.",
    choicesFr: [
      { id: 'a' as const, text: "C'est interdit, c'est une discrimination punie par la loi" },
      { id: 'b' as const, text: "C'est autorisé si l'entreprise est petite" },
      { id: 'c' as const, text: "C'est autorisé dans certains secteurs" },
      { id: 'd' as const, text: "C'est le droit de l'employeur" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q57: Une des valeurs de la devise républicaine est l'égalité. Qu'est-ce que cela signifie ? (CR + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr', 'nat'] as const,
    textFr: "Une des valeurs de la devise républicaine est l'égalité. Qu'est-ce que cela signifie ?",
    explanationFr: "L'égalité dans la devise républicaine signifie que tous les citoyens sont égaux devant la loi, sans distinction d'origine, de race ou de religion, conformément à l'article 1er de la Constitution.",
    choicesFr: [
      { id: 'a' as const, text: "Tous les citoyens sont égaux devant la loi" },
      { id: 'b' as const, text: "Tous les citoyens doivent avoir le même revenu" },
      { id: 'c' as const, text: "Tous les citoyens doivent penser la même chose" },
      { id: 'd' as const, text: "Tous les citoyens doivent avoir le même métier" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q58: À l'école publique, qui peut porter des signes religieux très visibles ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "À l'école publique, qui peut porter des signes religieux très visibles ?",
    explanationFr: "Depuis la loi du 15 mars 2004, le port de signes religieux ostensibles est interdit pour les élèves dans les écoles, collèges et lycées publics. Personne (ni élèves ni personnels) ne peut porter de signes religieux très visibles.",
    choicesFr: [
      { id: 'a' as const, text: "Personne, c'est interdit par la loi de 2004" },
      { id: 'b' as const, text: "Tout le monde" },
      { id: 'c' as const, text: "Seulement les enseignants" },
      { id: 'd' as const, text: "Seulement les élèves majeurs" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q59: Selon le principe de laïcité, que signifie la neutralité de l'État ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Selon le principe de laïcité, que signifie la neutralité de l'État ?",
    explanationFr: "La neutralité de l'État signifie que l'État ne favorise ni ne défavorise aucune religion. Il ne reconnaît, ne salarie ni ne subventionne aucun culte, conformément à la loi de 1905.",
    choicesFr: [
      { id: 'a' as const, text: "L'État ne favorise aucune religion et n'en défavorise aucune" },
      { id: 'b' as const, text: "L'État interdit toutes les religions" },
      { id: 'c' as const, text: "L'État choisit une religion officielle" },
      { id: 'd' as const, text: "L'État contrôle les pratiques religieuses" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q60: Que peut faire un usager du service public dans une mairie ? (CR + NAT)
  {
    themeId: 1 as const,
    type: 'situational' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr', 'nat'] as const,
    textFr: "Que peut faire un usager du service public dans une mairie ?",
    explanationFr: "Un usager du service public peut porter un signe religieux dans une mairie car la neutralité s'impose aux agents publics, pas aux usagers. Cependant, l'usager doit respecter l'ordre public.",
    choicesFr: [
      { id: 'a' as const, text: "Porter un signe religieux, car la neutralité s'impose aux agents, pas aux usagers" },
      { id: 'b' as const, text: "Imposer ses convictions religieuses aux agents" },
      { id: 'c' as const, text: "Refuser d'être servi par un agent d'une autre religion" },
      { id: 'd' as const, text: "Exiger des horaires adaptés à sa religion" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q61: Qui doit respecter le principe de neutralité religieuse dans une préfecture ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Qui doit respecter le principe de neutralité religieuse dans une préfecture ?",
    explanationFr: "Le principe de neutralité religieuse s'impose aux agents du service public. Ils ne doivent pas manifester leurs convictions religieuses dans l'exercice de leurs fonctions, contrairement aux usagers qui restent libres.",
    choicesFr: [
      { id: 'a' as const, text: "Les agents du service public" },
      { id: 'b' as const, text: "Les usagers uniquement" },
      { id: 'c' as const, text: "Tout le monde sans exception" },
      { id: 'd' as const, text: "Personne, la préfecture est un lieu libre" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q62: La laïcité impose-t-elle aux agents publics d'être neutres vis-à-vis des usagers ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "La laïcité impose-t-elle aux agents publics d'être neutres vis-à-vis des usagers ?",
    explanationFr: "Oui, la laïcité impose aux agents publics de traiter tous les usagers de manière égale, sans distinction de religion. Les agents ne doivent pas manifester leurs convictions religieuses dans le cadre de leurs fonctions.",
    choicesFr: [
      { id: 'a' as const, text: "Oui, les agents publics doivent traiter tous les usagers de manière égale" },
      { id: 'b' as const, text: "Non, les agents sont libres de montrer leurs préférences" },
      { id: 'c' as const, text: "Seulement dans les écoles" },
      { id: 'd' as const, text: "Non, la laïcité ne concerne que les usagers" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q63: Que garantit le principe de laïcité ? (CR + NAT)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr', 'nat'] as const,
    textFr: "Que garantit le principe de laïcité ?",
    explanationFr: "Le principe de laïcité garantit la liberté de conscience et la liberté de culte pour tous. Il assure la neutralité de l'État et l'égalité de tous les citoyens devant la loi, quelle que soit leur religion.",
    choicesFr: [
      { id: 'a' as const, text: "La liberté de conscience, la liberté de culte et la neutralité de l'État" },
      { id: 'b' as const, text: "L'interdiction de toutes les pratiques religieuses" },
      { id: 'c' as const, text: "Le financement des religions par l'État" },
      { id: 'd' as const, text: "La supériorité d'une religion sur les autres" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q64: A-t-on le droit de changer de religion ? (CR only)
  {
    themeId: 1 as const,
    type: 'situational' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "A-t-on le droit de changer de religion ?",
    explanationFr: "Oui, la liberté de conscience permet à chaque personne de changer de religion, d'en adopter une ou de n'en avoir aucune. Ce droit est garanti par la Constitution et la Déclaration des droits de l'homme.",
    choicesFr: [
      { id: 'a' as const, text: "Oui, c'est un droit garanti par la liberté de conscience" },
      { id: 'b' as const, text: "Non, on doit garder la religion de sa naissance" },
      { id: 'c' as const, text: "Seulement avec l'accord d'un juge" },
      { id: 'd' as const, text: "Seulement si on devient athée" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q65: Que représente la laïcité ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Que représente la laïcité ?",
    explanationFr: "La laïcité représente la séparation des religions et de l'État, la neutralité de l'État vis-à-vis des cultes, et la garantie de la liberté de conscience pour tous les citoyens.",
    choicesFr: [
      { id: 'a' as const, text: "La séparation des religions et de l'État et la liberté de conscience" },
      { id: 'b' as const, text: "L'interdiction de pratiquer une religion" },
      { id: 'c' as const, text: "La promotion de l'athéisme" },
      { id: 'd' as const, text: "Le contrôle des religions par l'État" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q66: Qu'est-ce qui est interdit par la Charte de la laïcité à l'école ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Qu'est-ce qui est interdit par la Charte de la laïcité à l'école ?",
    explanationFr: "La Charte de la laïcité interdit le port de signes ou tenues manifestant ostensiblement une appartenance religieuse dans les écoles publiques. Elle vise à garantir la neutralité de l'espace scolaire.",
    choicesFr: [
      { id: 'a' as const, text: "Le port de signes religieux ostensibles par les élèves" },
      { id: 'b' as const, text: "L'étude de l'histoire des religions" },
      { id: 'c' as const, text: "Les discussions entre élèves sur la religion" },
      { id: 'd' as const, text: "La cantine scolaire" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q67: Que dit l'article 1er de la Constitution française ? (CR only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 2,
    isPremium: false,
    examTypes: ['cr'] as const,
    textFr: "Que dit l'article 1er de la Constitution française ?",
    explanationFr: "L'article 1er de la Constitution dispose que la France est une République indivisible, laïque, démocratique et sociale. Elle assure l'égalité devant la loi de tous les citoyens sans distinction.",
    choicesFr: [
      { id: 'a' as const, text: "La France est une République indivisible, laïque, démocratique et sociale" },
      { id: 'b' as const, text: "Le président est le chef de l'État" },
      { id: 'c' as const, text: "Le français est la langue officielle" },
      { id: 'd' as const, text: "Tous les citoyens doivent payer des impôts" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q68: Dans le cadre d'un entretien d'embauche, que peut-on demander au candidat ? (NAT only)
  {
    themeId: 1 as const,
    type: 'situational' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Dans le cadre d'un entretien d'embauche, que peut-on demander au candidat ?",
    explanationFr: "Lors d'un entretien d'embauche, les questions doivent porter uniquement sur les compétences professionnelles du candidat. Il est interdit de poser des questions sur la religion, l'origine, la situation familiale ou les opinions politiques.",
    choicesFr: [
      { id: 'a' as const, text: "Des questions sur ses compétences et son expérience professionnelle" },
      { id: 'b' as const, text: "Sa religion et ses pratiques religieuses" },
      { id: 'c' as const, text: "Ses opinions politiques" },
      { id: 'd' as const, text: "Son projet d'avoir des enfants" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q69: Déclarer ses revenus aux services fiscaux est : (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Déclarer ses revenus aux services fiscaux est :",
    explanationFr: "Déclarer ses revenus est une obligation légale pour tout contribuable en France. C'est un devoir civique qui permet de financer les services publics et d'assurer la solidarité nationale.",
    choicesFr: [
      { id: 'a' as const, text: "Une obligation légale" },
      { id: 'b' as const, text: "Un choix personnel" },
      { id: 'c' as const, text: "Obligatoire uniquement pour les riches" },
      { id: 'd' as const, text: "Facultatif pour les étrangers" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q70: La liberté d'association est : (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "La liberté d'association est :",
    explanationFr: "La liberté d'association est un droit fondamental garanti par la loi du 1er juillet 1901. Elle permet à toute personne de créer ou de rejoindre une association sans autorisation préalable de l'État.",
    choicesFr: [
      { id: 'a' as const, text: "Un droit fondamental garanti par la loi de 1901" },
      { id: 'b' as const, text: "Un droit réservé aux citoyens français" },
      { id: 'c' as const, text: "Soumise à l'autorisation du préfet" },
      { id: 'd' as const, text: "Interdite pour les étrangers" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q71: La liberté d'expression sur les réseaux sociaux en France est : (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "La liberté d'expression sur les réseaux sociaux en France est :",
    explanationFr: "La liberté d'expression sur les réseaux sociaux existe mais elle est encadrée par la loi. Les propos racistes, diffamatoires, l'incitation à la haine ou le cyberharcèlement sont interdits et punis.",
    choicesFr: [
      { id: 'a' as const, text: "Encadrée par la loi, certains propos sont interdits" },
      { id: 'b' as const, text: "Totale et sans aucune limite" },
      { id: 'c' as const, text: "Interdite en France" },
      { id: 'd' as const, text: "Réservée aux journalistes et influenceurs" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q72: Lequel de ces prénoms évoque un symbole de la République ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Lequel de ces prénoms évoque un symbole de la République ?",
    explanationFr: "Marianne est le prénom qui évoque un symbole de la République française. Elle est la figure allégorique de la République, représentant la liberté et la démocratie.",
    choicesFr: [
      { id: 'a' as const, text: "Marianne" },
      { id: 'b' as const, text: "Jeanne" },
      { id: 'c' as const, text: "Marie" },
      { id: 'd' as const, text: "Catherine" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q73: Quand la sécurité sociale a-t-elle été établie en France ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Quand la sécurité sociale a-t-elle été établie en France ?",
    explanationFr: "La sécurité sociale a été créée en 1945 par les ordonnances des 4 et 19 octobre 1945. Elle repose sur le principe de solidarité nationale et couvre les risques maladie, vieillesse, famille et accidents du travail.",
    choicesFr: [
      { id: 'a' as const, text: "En 1945" },
      { id: 'b' as const, text: "En 1789" },
      { id: 'c' as const, text: "En 1905" },
      { id: 'd' as const, text: "En 1968" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q74: Que commémore la fête nationale ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Que commémore la fête nationale ?",
    explanationFr: "La fête nationale du 14 juillet commémore la prise de la Bastille le 14 juillet 1789 et la Fête de la Fédération du 14 juillet 1790. Ces événements symbolisent la liberté et l'unité nationale.",
    choicesFr: [
      { id: 'a' as const, text: "La prise de la Bastille (1789) et la Fête de la Fédération (1790)" },
      { id: 'b' as const, text: "La fin de la Seconde Guerre mondiale" },
      { id: 'c' as const, text: "L'élection du premier président de la République" },
      { id: 'd' as const, text: "La signature du traité de Versailles" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q75: Que porte Marianne sur la tête ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Que porte Marianne sur la tête ?",
    explanationFr: "Marianne porte un bonnet phrygien, symbole de liberté hérité de l'Antiquité romaine. Ce bonnet était porté par les esclaves affranchis et est devenu un emblème de la Révolution française.",
    choicesFr: [
      { id: 'a' as const, text: "Un bonnet phrygien" },
      { id: 'b' as const, text: "Une couronne" },
      { id: 'c' as const, text: "Un béret" },
      { id: 'd' as const, text: "Un chapeau à plumes" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q76: Quel symbole de la République peut-on voir sur les maillots de l'équipe de France de football ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Quel symbole de la République peut-on voir sur les maillots de l'équipe de France de football ?",
    explanationFr: "Le coq est le symbole que l'on retrouve sur les maillots de l'équipe de France de football. Cet animal, associé à la France depuis l'Antiquité, représente la fierté et la combativité.",
    choicesFr: [
      { id: 'a' as const, text: "Le coq" },
      { id: 'b' as const, text: "Marianne" },
      { id: 'c' as const, text: "La tour Eiffel" },
      { id: 'd' as const, text: "Le drapeau tricolore" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q77: Qu'est-ce qu'une liberté ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Qu'est-ce qu'une liberté ?",
    explanationFr: "Une liberté est un droit fondamental qui permet à chaque individu d'agir selon sa volonté dans le cadre de la loi. Les libertés sont encadrées par la loi pour garantir le respect des droits d'autrui.",
    choicesFr: [
      { id: 'a' as const, text: "Un droit d'agir selon sa volonté dans le cadre fixé par la loi" },
      { id: 'b' as const, text: "Le droit de faire n'importe quoi" },
      { id: 'c' as const, text: "Un privilège réservé aux citoyens français" },
      { id: 'd' as const, text: "L'absence totale de règles" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q78: En France, il est possible pour l'État de financer : (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "En France, il est possible pour l'État de financer :",
    explanationFr: "L'État peut financer l'entretien des édifices religieux construits avant 1905, car la loi de séparation a transféré la propriété de ces bâtiments aux communes. En revanche, l'État ne finance pas les cultes eux-mêmes.",
    choicesFr: [
      { id: 'a' as const, text: "L'entretien des édifices religieux construits avant 1905" },
      { id: 'b' as const, text: "La construction de nouvelles églises" },
      { id: 'c' as const, text: "Les salaires des prêtres et imams" },
      { id: 'd' as const, text: "Les activités de prosélytisme religieux" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q79: Que dit la loi de 1905 ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Que dit la loi de 1905 ?",
    explanationFr: "La loi du 9 décembre 1905 établit la séparation des Églises et de l'État. Elle garantit la liberté de conscience et le libre exercice des cultes, tout en affirmant que la République ne reconnaît, ne salarie ni ne subventionne aucun culte.",
    choicesFr: [
      { id: 'a' as const, text: "Elle établit la séparation des Églises et de l'État" },
      { id: 'b' as const, text: "Elle interdit toutes les religions" },
      { id: 'c' as const, text: "Elle instaure le droit de vote des femmes" },
      { id: 'd' as const, text: "Elle crée l'école obligatoire" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q80: Quel jour célèbre-t-on officiellement la laïcité en France ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Quel jour célèbre-t-on officiellement la laïcité en France ?",
    explanationFr: "La Journée de la laïcité est célébrée le 9 décembre, date anniversaire de la promulgation de la loi de séparation des Églises et de l'État en 1905. Des événements sont organisés, notamment dans les écoles.",
    choicesFr: [
      { id: 'a' as const, text: "Le 9 décembre" },
      { id: 'b' as const, text: "Le 14 juillet" },
      { id: 'c' as const, text: "Le 1er janvier" },
      { id: 'd' as const, text: "Le 11 novembre" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q81: Quel symbole religieux peut être porté dans une école publique dans le respect de la laïcité ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Quel symbole religieux peut être porté dans une école publique dans le respect de la laïcité ?",
    explanationFr: "Seuls les signes religieux discrets sont autorisés dans les écoles publiques. La loi de 2004 interdit les signes ostensibles, mais un petit pendentif discret reste toléré s'il n'est pas ostentatoire.",
    choicesFr: [
      { id: 'a' as const, text: "Un signe discret, non ostensible" },
      { id: 'b' as const, text: "Un voile intégral" },
      { id: 'c' as const, text: "Une grande croix visible" },
      { id: 'd' as const, text: "Aucun symbole religieux n'est toléré" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q82: Quel terme désigne précisément la haine ou les préjugés contre les Juifs ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Quel terme désigne précisément la haine ou les préjugés contre les Juifs ?",
    explanationFr: "L'antisémitisme désigne la haine, les préjugés ou la discrimination envers les personnes juives. La France combat l'antisémitisme par la loi et la République condamne toute forme de racisme.",
    choicesFr: [
      { id: 'a' as const, text: "L'antisémitisme" },
      { id: 'b' as const, text: "La xénophobie" },
      { id: 'c' as const, text: "L'islamophobie" },
      { id: 'd' as const, text: "Le racisme" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q83: Quel texte est considéré comme le texte fondateur de la laïcité ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Quel texte est considéré comme le texte fondateur de la laïcité ?",
    explanationFr: "La loi du 9 décembre 1905 de séparation des Églises et de l'État est le texte fondateur de la laïcité en France. Elle pose les principes de liberté de conscience et de neutralité de l'État.",
    choicesFr: [
      { id: 'a' as const, text: "La loi de 1905 de séparation des Églises et de l'État" },
      { id: 'b' as const, text: "La Déclaration des droits de l'homme de 1789" },
      { id: 'c' as const, text: "La Constitution de 1958" },
      { id: 'd' as const, text: "Le Code civil de 1804" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q84: Quelle institution française doit rester neutre en matière de religion ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Quelle institution française doit rester neutre en matière de religion ?",
    explanationFr: "L'État et toutes les institutions publiques (écoles, hôpitaux, tribunaux, mairies) doivent rester neutres en matière de religion. C'est un principe fondamental de la laïcité inscrit dans la Constitution.",
    choicesFr: [
      { id: 'a' as const, text: "L'État et toutes les institutions publiques" },
      { id: 'b' as const, text: "Uniquement les écoles" },
      { id: 'c' as const, text: "Seulement les tribunaux" },
      { id: 'd' as const, text: "Les entreprises privées" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q85: À l'école, la charte de la laïcité permet de : (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "À l'école, la charte de la laïcité permet de :",
    explanationFr: "La Charte de la laïcité à l'école, affichée dans tous les établissements scolaires publics, permet de rappeler les règles du vivre-ensemble et le cadre laïque de l'enseignement public.",
    choicesFr: [
      { id: 'a' as const, text: "Rappeler les règles du vivre-ensemble et le cadre laïque" },
      { id: 'b' as const, text: "Interdire l'enseignement de l'histoire des religions" },
      { id: 'c' as const, text: "Obliger les élèves à être athées" },
      { id: 'd' as const, text: "Empêcher les parents d'entrer dans l'école" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q86: Qui doit respecter et veiller à la neutralité religieuse dans les services publics ? (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Qui doit respecter et veiller à la neutralité religieuse dans les services publics ?",
    explanationFr: "Les agents du service public doivent respecter et veiller à la neutralité religieuse. Ils ne peuvent pas manifester leurs croyances religieuses dans l'exercice de leurs fonctions.",
    choicesFr: [
      { id: 'a' as const, text: "Les agents du service public" },
      { id: 'b' as const, text: "Uniquement les usagers" },
      { id: 'c' as const, text: "Les élus seulement" },
      { id: 'd' as const, text: "Les associations religieuses" },
    ],
    correctChoice: 'a' as const,
  },
  // ── Q87: Une personne déclare ne croire en aucun dieu. On peut dire : (NAT only)
  {
    themeId: 1 as const,
    type: 'knowledge' as const,
    difficulty: 3,
    isPremium: false,
    examTypes: ['nat'] as const,
    textFr: "Une personne déclare ne croire en aucun dieu. On peut dire :",
    explanationFr: "Une personne qui ne croit en aucun dieu est athée. En France, la liberté de conscience garantit le droit de ne pas croire, de croire ou de changer de croyance. L'athéisme est pleinement respecté par la loi.",
    choicesFr: [
      { id: 'a' as const, text: "Qu'elle est athée, ce qui est un droit garanti par la liberté de conscience" },
      { id: 'b' as const, text: "Qu'elle enfreint la loi" },
      { id: 'c' as const, text: "Qu'elle doit quitter la France" },
      { id: 'd' as const, text: "Qu'elle doit choisir une religion" },
    ],
    correctChoice: 'a' as const,
  },
];
